### ISSUE TITLE
User testing of ABBYY processing for poor quality scanned PDFs

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#1]
Link to source documents available here:
https://docs.google.com/spreadsheets/d/1egEe46RU0McXLeHT5ms57p223Hi61dalmK_6TsHD1T8/edit#gid=573843848

**Comment by anderspeders** [comment]
Proposed approach:

For sprint 1: Start with *structured* and *image* categorised documents. 

For sprint 2: Follow up with *image poor*

**Comment by anderspeders** [comment]
I just tested the loading of this contract: http://ebproject-dev.elasticbeanstalk.com/contract/3, and it seems to have already taken a few hours to process. 

It might be useful to start considering the email-alert or other options for triggers that can ping the contract uploader. I will create a separate ticket for that.

**Comment by anderspeders** [comment]
This is pending getting the staging environment set up.

**Comment by anjesh** [comment]
Moving to sprint 4 to generate some sort of internal report of the pdf processing results - including abbyy.

**Comment by anjesh** [comment]
The pdf process appears ok for now. I am looking into the log to get the time duration for the processing.

**Comment by anjesh** [comment]
Here's the status of all the pdfs uploaded in the stage server till date. 

|Type   | Total Pages   |Total processing time in minutes   | Per page processing time (avg) |
|---|---|---|---|
| Scanned  | 1310  |   306. 6 |  14.04 sec |  
| Structured  |  2409  |  3.35  |  0.08 sec | 

Here's the breakdown of the individual scanned-pdf processing time 

| PDF Type | Total Pages | Duration |
|----------|-------------|----------|
| Scanned  | 44          | 0:10:29  |
| Scanned  | 1           | 0:00:12  |
| Scanned  | 1           | 0:00:13  |
| Scanned  | 20          | 0:04:35  |
| Scanned  | 135         | 0:35:14  |
| Scanned  | 70          | 0:14:20  |
| Scanned  | 12          | 0:02:35  |
| Scanned  | 79          | 0:40:05  |
| Scanned  | 82          | 0:15:02  |
| Scanned  | 87          | 0:17:08  |
| Scanned  | 83          | 0:17:10  |
| Scanned  | 1           | 0:00:12  |
| Scanned  | 1           | 0:00:24  |
| Scanned  | 83          | 0:16:31  |
| Scanned  | 70          | 0:14:11  |
| Scanned  | 57          | 0:12:01  |
| Scanned  | 72          | 0:10:15  |
| Scanned  | 10          | 0:02:29  |
| Scanned  | 16          | 0:03:38  |
| Scanned  | 83          | 0:15:59  |
| Scanned  | 89          | 0:18:35  |
| Scanned  | 82          | 0:17:35  |
| Scanned  | 83          | 0:16:36  |
| Scanned  | 20          | 0:11:11  |
| Scanned  | 29          | 0:09:56  |

**Comment by anderspeders** [comment]
Thanks very much @Anjesh, 

And just to confirm: the structured PDF does not route through ABBYY, right?

**Comment by anjesh** [comment]
The structured pdf doesn't route through ABBYY, so far 1310 pages have been processed through ABBY. Can you verify from the abbyy interface?

**Comment by anjesh** [comment]
Wrote the script https://github.com/anjesh/pdf-processor/blob/master/logs/logreport.py to prepare the report from the log.
