### ISSUE TITLE
Company names drop-down list

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1000]
Not all the captured company names are presented in the drop-down list (advanced search). 

An example is Tenke Fungurume Mining SARL which was captured as one of the 3 companies of below contract but doesn't appear in the company drop-down list. . 

http://resourcecontracts.elasticbeanstalk.com/contract/1395

**Comment by manishgs** [comment]
Fixed. There was limit (1000) in company name listing.  I've increased the limit.  Now all company names are showing on the dropdown list.

**Comment by charlesyoung** [comment]
Reopening because its related. Company name in the list but no search results. Example below. 

http://www.resourcecontracts.org/search?q=&company_name%5B%5D=ARROW
