### ISSUE TITLE
Data audit

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1002]
@anjesh can you please run a data audit to identify problems with duplicate company names, spelling mistakes, etc.

**Comment by manishgs** [comment]
I've generated list of distinct company names.
https://docs.google.com/spreadsheets/d/1JUJQMFhhBtophQoEt7ss63eFM0jCillK079msRmTv_A/edit#gid=0

Please go through the list, highlight the duplicate names and add corrected name.

**Comment by charlesyoung** [comment]
@manishgs please update the duplicate company names as noted in the [spreadsheet.](https://docs.google.com/spreadsheets/d/1JUJQMFhhBtophQoEt7ss63eFM0jCillK079msRmTv_A/edit?ts=583e5832#gid=0)

**Comment by manishgs** [comment]
Company names are updated.
