### ISSUE TITLE
Verify translation text (RC-Admin)

### ISSUE THREAD

**Issue by manishgs** [NRGI/resourcecontracts.org#1003]
We have updated all the translated text on google sheet. Please refer this document to verify and further updates on translation of RC-admin.

https://docs.google.com/spreadsheets/d/1_UL9RlQJ1ai5O_5qhpzYVpnHCrM_SV8slicOCAWCUJA/edit?ts=58380364#gid=1521023057

Please refer to the first tab (How to update) of the sheet if you have to correct the translation

**Comment by charlesyoung** [comment]
Is this ticket only for the backend translations?

**Comment by manishgs** [comment]
Yes, The google sheet only contains admin translation.

**Comment by charlesyoung** [comment]
Please update.

**Comment by anjesh** [comment]
implemented in admin

![image](https://cloud.githubusercontent.com/assets/120488/21930809/18474236-d9c0-11e6-8cae-6dcfb9a6bb63.png)
