### ISSUE TITLE
Verify Translation Text (Frontend)

### ISSUE THREAD

**Issue by manishgs** [NRGI/resourcecontracts.org#1004]
We have updated all the translated text on google sheet. Please refer this document to verify and further updates on translation of Frontend.

https://docs.google.com/spreadsheets/d/1FYGpCtUDczJzUtzmBn97zJH4BeGL2aO4VeBIKMnRWMo/edit?ts=58357f93#gid=0

Please refer to the first tab (How to update) of the sheet if you have to correct the translation

**Comment by charlesyoung** [comment]
Please implement on the RC site. 

@SamCCSI do we hold for the OLC site?

**Comment by SamCCSI** [comment]
For OLC, French version can go live. Please hold the Arabic version for now.

**Comment by manishgs** [comment]
French translation enabled on RC and OLC site. Please check the static pages they are not translated.

@charlesyoung  
Should we enable Arabic on RC site?

**Comment by charlesyoung** [comment]
Yes please.

**Comment by anjesh** [comment]
fr and ar enabled in http://resourcecontracts.org/
fr enabled in http://www.openlandcontracts.org/
