### ISSUE TITLE
Making *or* statements work in search 

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#1005]
I got this question today from an NRGI staff member. How can I search for multiple words using *or* statements. 

For example: I would like to search for stabilization and stability:
http://www.resourcecontracts.org/search?q=stablization%2C+stability 

This result currently generates 0 results. 

Any suggestions for quick fixes here?

**Comment by manishgs** [comment]
You can use  **|** for  _or statement_. In this case "stabilization | stability"

http://www.resourcecontracts.org/search?q=stabilization+%7C+stability

Please refer faqs page for other options.
http://www.resourcecontracts.org/faqs

**Comment by charlesyoung** [comment]
@anderspeders can we close this ticket?
