### ISSUE TITLE
Contracts from Kurdistan Regional Government of Iraq

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#1006]
We are contemplating listing contracts from Kurdistan Regional Government of Iraq under a separate country from "Iraq".

Examples of such contracts include: http://resourcecontracts.elasticbeanstalk.com/contract?year=all&country=all&category=all&resource=all&q=kurdistan

1. Does this pose any OCDS issues?

2. How do we add a new country to the database?

CC @charlesyoung @jpmckinney @anderspeders

**Comment by charlesyoung** [comment]
@SamCCSI we can add to the country list but the question is should we be adding KRG as a country when its actually a federal region of Iraq and not a country. Why don't we add it under Iraq?

**Comment by SamCCSI** [comment]
This has been resolved for now.
