### ISSUE TITLE
Clipping individual annotations 

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1007]
Some users are complaining that individual annotation clipping isn't working. See below. 

![image](https://cloud.githubusercontent.com/assets/13888372/20884657/3308ecb2-baf5-11e6-9c4e-b9f7eaec4df6.png)

@anjesh @SamCCSI

**Comment by SamCCSI** [comment]
Also not working on some people's OLC, but is for others.

It seems like it is switching on / off randomly, or maybe it only works with some contracts?

**Comment by SamCCSI** [comment]
My clipping for individual annotations works for OLC but not RC. I am using Chrome for Mac - Version 54.0.2840.98 (64-bit)

**Comment by charlesyoung** [comment]
Thomas Lassourd noted that he had the same issue but that the individual clips are now working. 

He is using Chrome version 55.0.2883.75 m (64-bit). 

@anjesh can you please prioritize this issue.

**Comment by manishgs** [comment]
We have tested on different PC but could not replicate the issue. Could you please provide the screenshot of console log?

**To get console log please follow the below steps:**
1. On chrome browser right click and select Inspect or (command + shift + c)
2. Go to console tab
![console](https://cloud.githubusercontent.com/assets/3942999/21007316/7d98d370-bd64-11e6-9c07-bfc178979563.jpg)
3. click on clip on/off
4. take screenshot of console.

**Comment by SamCCSI** [comment]
@manishgs here you go:

![image](https://cloud.githubusercontent.com/assets/12913915/21104544/efe8b65a-c054-11e6-8125-6fc2c9c1a51c.png)

**Comment by charlesyoung** [comment]
@SamCCSI will it be possible to update your version of Chrome to see if that resolves the issue? Anjesh is using Version 55.0.xxxx.90 (64-bit) and I've tested on Version 55.0.2883.95 (64-bit) with both versions working. 

cc @anjesh

**Comment by SamCCSI** [comment]
Working now.

Do we need to educate our users about this, however? Otherwise they may
miss out on key functionality.

@jesseccsi can you see if updating your browser solves your issues as well?

**Comment by JesseCCSI** [comment]
Working for me too. Thanks all. 

Agree with @SamCCSI re making this clear to users - perhaps in the FAQs?

**Comment by charlesyoung** [comment]
Thanks, I will close this ticket but will add above request to ticket #996.

**Comment by charlesyoung** [comment]
Linked to https://github.com/NRGI/resourcecontracts.org/issues/996
