### ISSUE TITLE
Tunisia mining contracts backend import

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1011]
Data captured in the standard template format will be ready for import during January 2017.

**Comment by charlesyoung** [comment]
As discussed with Perrine a new contract type (Cahier des Charges) will be added to accommodate the Tunisia mining contracts. 

cc @SamCCSI

**Comment by charlesyoung** [comment]
The 'Participation Share' was incorrectly captured in the Google sheet (0.1 rather than 1). 

@manishgs can you please update the imported mining contracts accordingly?

**Comment by manishgs** [comment]
Participation Share updated to 1. Please review and publish the contracts.

**Comment by charlesyoung** [comment]
Thanks @manishgs 

Is there no way you can do an auto publish of those contracts? I'm not that keen to manually publish 40 contracts.

**Comment by manishgs** [comment]
All 40 imported mining contracts are published. 4 contracts are in draft so they are not published.

**Comment by charlesyoung** [comment]
Many thanks @manishgs

Please send me the names of the 4 draft contracts.

**Comment by manishgs** [comment]
Cahier des Charges Jbel Essif
Cahier des Charges Bled El Adla  Delete
Cahier des Charges Jebel Hameima
Cahier des Charges Jebel Djerissa
