### ISSUE TITLE
Localisation of Annotation (backend)

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#1015]
Annotation localisation is slightly different from metadata - the way annotation is captured during annotation setup. This issue will take care of annotation localisation.

**Comment by charlesyoung** [comment]
@anjesh what is the status of this ticket?

**Comment by charlesyoung** [comment]
@anjesh is this already on the staging site so that we can test?

**Comment by manishgs** [comment]
We are working on this feature. We'll update on staging soon.

**Comment by manishgs** [comment]
Please review annotation localization workflow on admin site. 

You can choose language from dropdown in annotation popup.
![screenshot-admin-staging resourcecontracts org 2017-03-16 18-20-47](https://cloud.githubusercontent.com/assets/3942999/23996448/842338ee-0a75-11e7-806b-101d42ae499b.png)

You can view and update annotation text and article ref. in difference language from contract view.
![screenshot-admin-staging resourcecontracts org 2017-03-16 18-21-33](https://cloud.githubusercontent.com/assets/3942999/23996450/848102a8-0a75-11e7-9f61-ebfa6b73475e.png)

Note that  we haven't updated this feature on frontend yet.

**Comment by charlesyoung** [comment]
Just to note that its on the admin [staging ](http://admin-staging.resourcecontracts.org)site.

**Comment by manishgs** [comment]
Please review on [Frontend](http://staging.resourcecontracts.org/search?q=french) and let us know your feedback.

**Comment by charlesyoung** [comment]
@SamCCSI @JesseCCSI will you have time this week to review the annotation localization workflow?

**Comment by SamCCSI** [comment]
Backend:
1. If you set the language to French or Arabic, the drop down for annotation categories should appear in that language, not in english.

2. If the contract metadata language is French or Arabic, then can we make it so that the annotation language is automatically set to the right language as well?

Frontend 
- seems to be working well. 
- Only problem is that you can only set the language of the site from the home page of RC, not from any contract view page. @jedm is that a problem? Eg. If I click the link above that @manishgs shares, I can't change the language of the site. Instead I have to go the home page. Change the language and then do the search again.

**Comment by manishgs** [comment]
Backend:
1. fixed.
2. fixed.

Frontend
> Only problem is that you can only set the language of the site from the home page of RC, not from any contract view page. @jedm is that a problem? Eg. If I click the link above that @manishgs shares, I can't change the language of the site. Instead I have to go the home page. Change the language and then do the search again.

The language switcher is located at buttom of the page for inner pages. You don't need to go to home page for switching language.

@SamCCSI 
Let us know if you found any issue.

**Comment by charlesyoung** [comment]
@SamCCSI you happy with the updates?

**Comment by SamCCSI** [comment]
Yes looks good. I couldn't find a French language contract to test 2 above (all were still in processing mode) but I think we can roll this out now and report back if any issues.

**Comment by charlesyoung** [comment]
Thanks @SamCCSI 

@manishgs can you please deploy on the prod site? 

We will close this ticket once deployed and create a new one to note any issues.

**Comment by manishgs** [comment]
Deployed to production.
