### ISSUE TITLE
Minor textual frontend changes 

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1017]
1. Change the "Publish Contracts" link at the bottom of the homepage to "Country Sites” **(RC, OLC and country public sites)**
2. On the contract summary page, change "There’s no annotation added to this document yet." to "This document has no annotations." **(RC, OLC and country public sites)**
3. On the contract summary page, where there are no associated documents rather note that "There are no associated documents" than "There is no associated documents". **(Admin site)**

**Comment by charlesyoung** [comment]
4. Move the final line (photo credits) in the RC 'About' page to along the bottom of the homepage in small text

**Comment by KaitlinCCSI** [comment]
@charlesyoung Re point 1 - why do the country public sites even have a "Country Sites" link/page? I don't see what purpose the page serves for country sites and would suggest it be deleted.

**Comment by charlesyoung** [comment]
@KaitlinCCSI, sure we can delete the "Country Sites" link if you don't think its worth marketing the other country sites.

**Comment by KaitlinCCSI** [comment]
Would just place a short note about the other country sites somewhere else - maybe on FAQ page, or end of About page.

**Comment by charlesyoung** [comment]
OK, the "Country Sites" page for country public sites will be removed.

**Comment by shashikhanal** [comment]
@charlesyoung After the update made in point 1, now should we delete 'Publish Contracts' link from the footer ?
And regarding point 4, did you mean to move the photo credits line in 'About' page to footer text ?
Somewhat here ?
![footer](https://cloud.githubusercontent.com/assets/4457892/21600254/1d94ef62-d1a1-11e6-9a91-4984f40bebbe.png)

**Comment by charlesyoung** [comment]
Thanks @shashikhanal 

The "Publish Contracts" link just needs to be renamed to "Country Sites”.

**Comment by shashikhanal** [comment]
@charlesyoung Ok. And what should we do about 'photo credits' line ? Please, go through the second part of my previous comment.

**Comment by charlesyoung** [comment]
@SamCCSI @KaitlinCCSI, Tehtena requested that we move the photo credits on the 'About' page to somewhere along the bottom of the home page. Where do you want us to place the photo credit text on the home page?

**Comment by SamCCSI** [comment]
@charlesyoung If there is space, it could go below the following (starting on a new line): "This site provides summaries of contracts and their terms to facilitate understanding of important provisions in the documents. These summaries are not interpretations of the documents. Neither the summaries nor the full contracts are complete accounts of all legal obligations related to the projects in question. This site also includes document text that was created automatically; such text may contain errors and differences from the original PDF files. No warranty is made to the accuracy of any content on this website."

@charlesyoung is the current text still accurate for RC or does it need updating in view of the recent changes to RC homepage? "View from Entoto Mountain, Ethiopia (Arne Hoel/World Bank Photo Collection) Compagnie des Bauxites de Guinée, Sangarédi, Guinée (RWI); Oil rig worker, Niger Delta, Nigeria (Ed Kashi)"

**Comment by manishgs** [comment]
@charlesyoung  @SamCCSI 
Could you please confirm below text which we'll add after this line "This site provides summaries of contracts ..."?

"Photo credits, home page: View from Entoto Mountain, Ethiopia (Arne Hoel/World Bank Photo Collection) Compagnie des Bauxites de Guinée, Sangarédi, Guinée (RWI); Oil rig worker, Niger Delta, Nigeria (Ed Kashi)"

**Comment by anjesh** [comment]
@charlesyoung could you please get back to this issue? Thanks.
