### ISSUE TITLE
Improvements to annotation functionality needed

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#1019]
When annotating, the text box is way too small. Meaning that annotations more than one sentence long are very hard to read / edit.

![image](https://cloud.githubusercontent.com/assets/12913915/21187303/6c618554-c1e5-11e6-85e8-f8082443a5a9.png)

It is possible (in theory) to expand the window to make it larger, but when I try: (i) the text goes outside of the box; and (ii) the box keeps expanding and does not stay at a fixed size.

We need to fix these bugs; will lead to cleaner annotations, and potentially make process more efficient for annotators.

![image](https://cloud.githubusercontent.com/assets/12913915/21187378/b594914e-c1e5-11e6-995c-4bf34ff4fb2c.png)

**Comment by SamCCSI** [comment]
Feedback received from CCSI annotators and from annotators working on a RC Country-specific site.

**Comment by charlesyoung** [comment]
@anjesh what is the latest with this ticket?

**Comment by manishgs** [comment]
![screenshot-localhost-8000 2017-03-03 17-51-51](https://cloud.githubusercontent.com/assets/3942999/23550656/53d3b6b8-003a-11e7-9b1b-4b6870120843.png)

**Comment by SamCCSI** [comment]
Thanks @manishgs this now works nicely.
