### ISSUE TITLE
change in capitalization of annotation categories leads to broken links

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#1020]
I see that annotation categories were recently changed to all lower case. This has had the strange effect of invalidating URLs that have resources listed with a capital letter.

E.g. A recent blog links to http://www.openlandcontracts.org/search?q=&annotation_category%5B%5D=Location which shows zero results. But if you change the mention of "Location" in the URL to "location" then it returns 125 results.

Can we please create a fix so that links that have the old capitalized versions still work?

**Comment by manishgs** [comment]
fixed.
