### ISSUE TITLE
Time sensitive - Problem with annotation categories

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#1021]
Why are annotation categories only one word now?

![image](https://cloud.githubusercontent.com/assets/12913915/21243254/0d98a0e6-c2e6-11e6-89d4-5c400dc97ce1.png)

We need to return to the previous display of annotation categories, most of which contain more than one word.

CC @charlesyoung

**Comment by charlesyoung** [comment]
@anjesh can you please prioritize this ticket?

**Comment by manishgs** [comment]
Its due to ES mapping. Fixed.
