### ISSUE TITLE
Re-upload of PDF file deleted all annotations

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#1023]
http://resourcecontracts.elasticbeanstalk.com/contract/2323

This PDF file had pages out of order, but had been annotated.

When attempting to upload the contract in correct page order, the system failed to upload the file because it was a "scanned" PDF. Now all annotations have been deleted.

Can you please help us to:
1 - recover the old annotations
2 - upload the [file](https://www.dropbox.com/s/s8e13nnl8kc6we3/MOU-Magbas-Sugar-1.pdf?dl=0) with the correct page order?

![image](https://cloud.githubusercontent.com/assets/12913915/21280332/596ac3c8-c3b3-11e6-9248-882bf63899b5.png)

**Comment by manishgs** [comment]
There are 15 annotations in the contracts. Are they newly annotated?

**Comment by SamCCSI** [comment]
Thanks @manishgs those did not appear when I took the screenshot, so I guess the system just takes some time to restore the annotations?

Is it also a problem that the system told me the upload of the PDF failed, but then it actually worked? Anything we can fix up around this to make it less confusing?

**Comment by manishgs** [comment]
From your screenshot contract status is **processing**. We are hiding annotations for UI while contract is pending/processing so you did not see annotations.

Where did you saw PDF Failed message?

**Comment by charlesyoung** [comment]
@SamCCSI we are looking at closing out S18 tickets. Can we close this ticket?

**Comment by SamCCSI** [comment]
Thanks @charlesyoung the issue has been perfectly resolved for this contract.

I guess we can close now, though if we encounter the message that the upload of the PDF failed again in the future, we will need to find a tech solution, as this is confusing.
