### ISSUE TITLE
Re-order placement of "Associated Documents" in metadata column of contract view page

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#1024]
In righthand metadata column of contract view page, associated docs currently appear below the "more from" links. The PDF specs provided by @jedm had placed the associated docs above those links, which seems more intuitive and user-friendly. Can the placement be adjusted? 

![screen shot 2016-12-21 at 3 34 14 pm](https://cloud.githubusercontent.com/assets/14825437/21407265/3bc26296-c795-11e6-9a51-5e178d9bf40c.png)

**Comment by manishgs** [comment]
fixed.
