### ISSUE TITLE
Change email message when sharing from contract view page

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#1025]
I just emailed from the contract view page, and the message said "Email Saved Clips." However, the email did not contain clips and was rather a link to the contract view page. Message should probably say something like "Email Page Link" or "Email Contract View Page". 

@jedm @charlesyoung Do we know if we've audited all the messages sent when using sharing buttons throughout site?

![screen shot 2016-12-22 at 4 16 06 pm](https://cloud.githubusercontent.com/assets/14825437/21442280/8a300168-c862-11e6-8107-fcc6909dcb1f.png)

**Comment by charlesyoung** [comment]
Thanks @KaitlinCCSI, can we note 'Email Clipped Annotations Link'?

@manishgs can you please send me the list of messages sent when using sharing buttons? 

cc @jedm

**Comment by KaitlinCCSI** [comment]
No, because it was just emailing a page link to the Contract View Page - so not relevant to clips or annotations at all. I guess it should say something like "Email Page Link" or "Email Contract View Page", but @jedm might have ideas for refining that.

**Comment by manishgs** [comment]
Popup title updated to  "Email Page Link" .

**Comment by jedm** [comment]
Sounds very techie. 

How about "Share by Email"?

**Comment by KaitlinCCSI** [comment]
@jedm suggestion fine with me. (Do you think that it will be clear to users what they are sharing if we don't add "Page"?)

**Comment by jedm** [comment]
Yes.

**Comment by KaitlinCCSI** [comment]
Okay, let's please change to "Share by Email"

**Comment by manishgs** [comment]
Text updated.
