### ISSUE TITLE
Add filters to activity log page on backend

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#1026]
In order to make sure that no documents are mistakenly published when they should be left in draft mode, it would be helpful to have more filters on the activity logs page. The most useful for us appear to be:

- 'Category' (this will be RC or OLC or both)
- 'Activity' (such as contract published, contract edited, contract uploaded).

That way I can quickly search for activity logs for all contracts published on RC and not have to wade through many irrelevant activity entries.

**Comment by manishgs** [comment]
Filter added on activity log page.

**Comment by SamCCSI** [comment]
@manishgs I can't see those two new filters yet on the activity log page. Has this gone live yet? Thanks.

![image](https://cloud.githubusercontent.com/assets/12913915/22251677/a8976c60-e219-11e6-81b8-95ecfb09782e.png)

**Comment by manishgs** [comment]
Yes. Please check filter options on live.

**Comment by SamCCSI** [comment]
Working nicely at this URL: http://admin.resourcecontracts.org/activities

Can you make these appear here too: http://resourcecontracts.elasticbeanstalk.com/activities – this is where I am directed when I click on 'activity log' so it would be helpful to have those options working there.

**Comment by manishgs** [comment]
http://resourcecontracts.elasticbeanstalk.com is replaced with http://admin.resourcecontracts.org. It will no longer maintain and will be removed in future so now onward please use http://admin.resourcecontracts.org .

**Comment by charlesyoung** [comment]
@manishgs should we not redirect http://resourcecontracts.elasticbeanstalk.com to http://admin.resourcecontracts.org to avoid possible confusion?

**Comment by charlesyoung** [comment]
Thanks @manishgs, the old site now redirects. 

Closing, @SamCCSI please reopen if required.

**Comment by anjesh** [comment]
FYI - The old site  http://resourcecontracts.elasticbeanstalk.com will stop working once we close the AWS instance, since we have all systems moved to NRGI infrastructure. We don't own that domain and is part of AWS, using that domain for redirection only will also cost money as it requires a server instance.
