### ISSUE TITLE
Annotation numbering  

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1027]
Not sure if I'm missing something but [20 ](http://resourcecontracts.elasticbeanstalk.com/contract/2277/annotate)annotations are noted in the admin tool. 

![image](https://cloud.githubusercontent.com/assets/13888372/21879394/41112ec2-d8a1-11e6-82b8-ea0880d25f28.png)

While on the public site [30](http://www.resourcecontracts.org/contract/ocds-591adf-3986673209/view#/pdf) are noted. There are actually 20 annotations for this contract. 

![image](https://cloud.githubusercontent.com/assets/13888372/21879431/8b16ee76-d8a1-11e6-9488-8fb030419af9.png)

cc @manishgs

**Comment by manishgs** [comment]
On rc-admin, total annotations calculated on the basis of annotation category (A category may have multiple annotations) while on frontend, calculated on the basis of annotation itself therefore there is differences in total annotations.

We are showing actual no of annotations on frontend because user might confuse if we display total annotations based on category.

Let us know if we need to change total calculation on admin or frontend.

**Comment by charlesyoung** [comment]
OK thanks @manishgs. 

@SamCCSI should we change or leave as is?

**Comment by SamCCSI** [comment]
@manishgs @charlesyoung This is quite confusing. There is only ever ONE annotation per category, even if there are multiple markers for each annotation category. I think we should have the front end display "total annotations calculated on the basis of annotation category" as well. Please let me know if I have not understood something.

Thanks @charlesyoung for flagging.

**Comment by manishgs** [comment]
@SamCCSI 
So the total annotations in frontend will be same as rc-admin which is calculated on the basis of annotation category.

**Comment by SamCCSI** [comment]
Thanks @manishgs -- could you let us know when this change is made?

**Comment by manishgs** [comment]
Total number of annotations is updated on frontend.

**Comment by charlesyoung** [comment]
I notice that the annotations are now [unpublished](http://admin.resourcecontracts.org/contract/2277) so it shows 0 on the frontend. How many contracts are affected by this?

**Comment by manishgs** [comment]
@charlesyoung  Could you please provide more detail about the issue?

When I visit the link,  annotations are published and total number of annotations on frontend is same as rc- admin.

**Comment by charlesyoung** [comment]
Very strange. Closing for now.
