### ISSUE TITLE
Bug: Annotation hover / bubble appears above contract page

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#1028]
Bug: when clicking on this [link](http://www.openlandcontracts.org/contract/ocds-591adf-2248245813/view#/pdf/page/3/annotation/9926), colleague's screen looked like this. The annotation hover/bubble appeared above the contract.

![image](https://cloud.githubusercontent.com/assets/12913915/21939936/0c7ef898-d990-11e6-9a9c-a769b53fb45a.png)

More generally, the page appeared with footer in full view, rather than focusing on contract:

![image](https://cloud.githubusercontent.com/assets/12913915/21939926/0495da2a-d990-11e6-820b-05487878cfd9.png)

Problem not replicable on my computer, but posting in case it can be resolved.

**Comment by SamCCSI** [comment]
Bug occurred using Chrome Version 55.0.2883.95 (64-bit) for macbook

**Comment by charlesyoung** [comment]
Strange because it works for me on the same Chrome version on an iMac. 

I however noticed that PDF docs aren't opening on Safari.

**Comment by charlesyoung** [comment]
@anjesh what is the latest with this ticket?

**Comment by manishgs** [comment]
@SamCCSI 
We pushed the annotation popup backward and it will appear under the contract.
Please review on [staging](http://staging.openlandcontracts.org/contract/ocds-591adf-3647297493/view#/pdf/page/3/annotation/3075)

**Comment by SamCCSI** [comment]
Thanks @manishgs I am not sure I understand what I am reviewing / looking for?

**Comment by manishgs** [comment]
@SamCCSI 
> Bug: when clicking on this link, colleague's screen looked like this. The annotation hover/bubble appeared above the contract.

We fixed the design.  When you scroll down, annotation popup will appear under tab/pagination bar.
![screenshot-staging openlandcontracts org 2017-03-03 20-25-10](https://cloud.githubusercontent.com/assets/3942999/23555089/a9437e70-004f-11e7-9148-b6b1fd83cde3.png)


>More generally, the page appeared with footer in full view, rather than focusing on contract:

Are you still getting this issue?

**Comment by SamCCSI** [comment]
@manishgs the problem only was seen with the specific contract I linked to at the top of this thread, and that contract doesn't have annotations on the staging site so it is not possible to replicate in staging to see if problem has been solved

**Comment by manishgs** [comment]
Do you see this issue on other contracts on live/staging because when I click on the link, the page focus on the contract, not on the footer.

**Comment by SamCCSI** [comment]
@manishgs the problem appears to have been resolved on the live site. Thanks.

**Comment by charlesyoung** [comment]
@SamCCSI can we close this ticket?
