### ISSUE TITLE
Workflow bug: at least 4 contracts are in draft mode, but appear on the front-end site

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#1029]
I think there is a change needed to the workflow: when contract's State is 'Draft' or 'Completed', that means it is not published. Therefore the user should not have to click 'Unpublish' under 'Published info' to ensure it is not published. 

Not sure how many other contracts this has happened to on RC. 

I found 4 contracts like this; State is 'Draft' or 'Completed'; but they are currently published:
![image](https://cloud.githubusercontent.com/assets/12913915/21949946/455212ac-d9c4-11e6-8eee-1f917911b61f.png)

But they are still live, presumably because we haven't clicked the 'unpublish' button. But if publish mode is not published, why do we have to also click unpublish?

http://resourcecontracts.elasticbeanstalk.com/contract/2196
![image](https://cloud.githubusercontent.com/assets/12913915/21950003/b58e0a58-d9c4-11e6-9126-948f98af10da.png)

http://resourcecontracts.elasticbeanstalk.com/contract/2193
![image](https://cloud.githubusercontent.com/assets/12913915/21950016/d54d7bee-d9c4-11e6-89cf-1a7707aa89b6.png)

http://resourcecontracts.elasticbeanstalk.com/contract/2194
![image](https://cloud.githubusercontent.com/assets/12913915/21950028/e9a6feee-d9c4-11e6-9b0f-9b54fbdf40a0.png)

http://resourcecontracts.elasticbeanstalk.com/contract/2302
![image](https://cloud.githubusercontent.com/assets/12913915/21950041/fb991df8-d9c4-11e6-9255-1cdfe6744851.png)

**Comment by manishgs** [comment]
> ...when contract's State is 'Draft' or 'Completed', that means it is not published. Therefore the user should not have to click 'Unpublish' under 'Published info' to ensure it is not published.

These four contracts are already published by user therefore you can see "Unpublish" button and there are changes on contracts' data so the state is updated to 'Draft' or 'Completed' which means new changes are not published on subsite.

If contract is in 'draft' or 'completed' state and there is 'unpublished' button, that means contract is published but new changes are not published yet.

Let me know if there is any confusion.

**Comment by manishgs** [comment]
@SamCCSI  Do you have any confusion? or we can close this issue?

**Comment by SamCCSI** [comment]
@manishgs I unpublished all four contracts last week but they are still live on the front-end. Shouldn't they disappear from front-end after I click 'unpublish'?

http://www.openlandcontracts.org/search?q=&country%5B%5D=br&country%5B%5D=pe

**Comment by manishgs** [comment]
@SamCCSI  It should removed from frontend. We'll look into this.

**Comment by SamCCSI** [comment]
Updated list of contracts in draft mode that have been unpublished but still appear on the front-end:

http://resourcecontracts.elasticbeanstalk.com/contract/2193
http://resourcecontracts.elasticbeanstalk.com/contract/2194
http://resourcecontracts.elasticbeanstalk.com/contract/2302

http://resourcecontracts.elasticbeanstalk.com/contract/2196
http://resourcecontracts.elasticbeanstalk.com/contract/1872
http://resourcecontracts.elasticbeanstalk.com/contract/2133
http://resourcecontracts.elasticbeanstalk.com/contract/2325

**Comment by manishgs** [comment]
Fixed. Please reopen this issue If you encounter again.
