### ISSUE TITLE
Add free text search to annotation UI (as it is available to editing)

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#103]
Currently the free text search is only available in **contract editing view** but not in the **contract annotation view**.

Please add the free test search option in the **contract annotation view**.

For example it is not available here: 
http://ebproject-dev.elasticbeanstalk.com/contract/4/annotations/list#page-2

**Comment by anjesh** [comment]
This annotations-list page is replaced by the annotation dropdown. There's search feature in annotating page.
