### ISSUE TITLE
BUG: Annotation markers have moved several pixels upwards and now block the words of the contract

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#1030]
Annotation markers have moved several pixels upwards and now block the words of the contract. This has happened on contracts annotated by different people, to the point where I am fairly sure that it is not the annotator, but rather some automatic bug:

Examples:

http://resourcecontracts.elasticbeanstalk.com/contract/1871
![image](https://cloud.githubusercontent.com/assets/12913915/21950296/671cf840-d9c7-11e6-9972-d8e21b8b0ef4.png)

http://resourcecontracts.elasticbeanstalk.com/contract/1871
![image](https://cloud.githubusercontent.com/assets/12913915/21950311/81d47f14-d9c7-11e6-80b2-992f2d3bc4ca.png)

http://resourcecontracts.elasticbeanstalk.com/contract/2104
![image](https://cloud.githubusercontent.com/assets/12913915/21950322/92158b5c-d9c7-11e6-8fb3-b87242a2af12.png)

cc @charlesyoung

**Comment by manishgs** [comment]
PDF page is shifted down by 5px due to progress bar. This issue is fixed.
