### ISSUE TITLE
Change "All Contracts" to "All Documents" in Sidebar menu 

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#1031]
The "All Documents" page lists both contracts and associated docs. The link in the sidebar menu should thus be changed to "All Documents" (currently reads "All Contracts") 

cc @KaitlinCCSI

**Comment by manishgs** [comment]
fixed.

**Comment by JesseCCSI** [comment]
great, thanks @manishgs
