### ISSUE TITLE
Annotations with multiple page refs changed to single page ref?

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#1032]
It seems that some annotations with multiple page references have been changed to only having a single page reference. Was this caused by the developers by accident?

Example:

Screenshot from 2015 (taken from training module so ignore the read text) (annotation on page 4 and page 18):
![image](https://cloud.githubusercontent.com/assets/12913915/22024928/b9960614-dc99-11e6-8b9e-77d46c15f114.png)

Screenshot now (annotation only on page 18):
![image](https://cloud.githubusercontent.com/assets/12913915/22024901/8ee32212-dc99-11e6-8db0-9cd770a8cae4.png)

cc @charlesyoung @KaitlinCCSI

**Comment by manishgs** [comment]
@charlesyoung 

If you check the annotations of this contract on admin, http://admin.resourcecontracts.org/contract/1173,  all annotations have only one ref. 

We have not updated to change multiple refs to single ref. Here are some contracts which have multiple refs.

http://www.resourcecontracts.org/contract/ocds-591adf-3986673209/view#/pdf/page/24/annotation/2241

http://www.resourcecontracts.org/contract/ocds-591adf-0982191402/view#/pdf/page/1/annotation/18203

http://www.resourcecontracts.org/contract/ocds-591adf-3173477058/view#/pdf/page/14/annotation/7885

**Comment by charlesyoung** [comment]
cc @SamCCSI

**Comment by SamCCSI** [comment]
Thanks @manishgs I'll investigate further at our end.
