### ISSUE TITLE
Contract zoomed too far in, even when I have zoomed out as much as possible

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#1034]
The below is after I have zoomed out as much as the site will let me. I still can't see the full width of the PDF.

Is this issue appearing because of changes to PDF display (e.g. because of work done on PDF scrolling?)

http://www.openlandcontracts.org/contract/ocds-591adf-7804618381/view#/pdf/page/9/annotation/3072
![image](https://cloud.githubusercontent.com/assets/12913915/22028896/c5e130e4-dca6-11e6-9705-67a48ed7e85f.png)

![image](https://cloud.githubusercontent.com/assets/12913915/22028942/ed836612-dca6-11e6-8059-7b1850a34479.png)

**Comment by manishgs** [comment]
We are working on different git branch for PDF scrolling which will not affect the current functionality. 

Regarding PDF zoom if you check the pdf of the contract [here](https://resourcecontracts-nrgi.s3-us-west-2.amazonaws.com/1179/1179-sierra-leone-addax-bioenergy-sierra-leone-ltd-memorandum-of-understanding-and-agreement-9-february-2010.pdf) which is larger than the normal pdf size [here](https://resourcecontracts-nrgi.s3-us-west-2.amazonaws.com/2446/2446-forabola-clause-sociale-avenant-n-1-bamanga-2013.pdf). If you zoom out the pdf to 25% still it is larger than normal pdf therefore the pdf doesn't fit on the view.

You can also try by opening pdfs on chrome, zoom out the both pdfs and compare the size.

**Comment by SamCCSI** [comment]
@manishgs is there a way to auto-adjust the PDF's size so that it is entirely visible?

Not a priority for current sprint but flagging now.

cc @charlesyoung @anjesh

**Comment by SamCCSI** [comment]
Any updates @manishgs @charlesyoung ?

Also see screenshot for this contract: it looks like when it was annotated it was not so zoomed in on the site; the markers here (including the standard sized markers) are also zoomed in indicating that when they were added the contract was on a normal ratio / zoom. Would that mean that a recent change to the site is what caused this zoom-in bug?

![image](https://cloud.githubusercontent.com/assets/12913915/23081018/0ab4ae70-f521-11e6-80de-2d26ac349e3b.png)

**Comment by manishgs** [comment]
fixed and deployed to production.
