### ISSUE TITLE
Some contract text with french accents still appears as a [?] symbol

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#1035]
1. Some contract text with french accents still appears as a [?] symbol
http://www.openlandcontracts.org/contract/ocds-591adf-8844454518/view#/text

![image](https://cloud.githubusercontent.com/assets/12913915/22037357/d2f08b90-dcc4-11e6-981c-6c813b8e3e66.png)

2. This is carried over to word document downloads.

3. CSV downloads of annotations also have symbols in place of accents in some cases

**Comment by anderspeders** [comment]
Would be good to get @anjesh view here. 

@SamCCSI: 3. Is this occuring for annotations only or for the metadata text as well?

**Comment by SamCCSI** [comment]
@anderspeders I haven't seen metadata text having this problem

**Comment by anderspeders** [comment]
Thanks @SamCCSI, 

@anjesh @manishgs Could you have a look?

**Comment by manishgs** [comment]
Following pages contains [?] symbol. All the pages transcribe from mTurk. Not all the pages from contracts have this issue. 
143 - 19
143 - 27
143 - 30
143 - 83
143 - 90
747 - 20
1044 - 9
1044 - 10
1044 - 13
1044 - 20
1044 - 29
1044 - 30
1044 - 31
1044 - 32
1044 - 35
1044 - 36
1044 - 38
1044 - 39
1044 - 41
1046 - 4
1046 - 7
1046 - 21
1046 - 24
1046 - 26
1046 - 27
1046 - 28
1046 - 31
1046 - 35
1046 - 36
1046 - 37
1046 - 38
1046 - 40
1126 - 1
1126 - 6
1126 - 10
1301 - 89
1417 - 133
1470 - 111
1585 - 92

**Comment by SamCCSI** [comment]
@manishgs are you saying that the <?> symbol comes from the transcribers and not from a problem with the RC system?

**Comment by manishgs** [comment]
@SamCCSI  Yes the symbol comes from Mturk (from the transcribers).  If you check the other pages of same contract, french accents are correct.  The pages that I've listed above need to be corrected by manual editing.

**Comment by SamCCSI** [comment]
@manishgs okay, thanks, we will take care of this.
