### ISSUE TITLE
Country name in export table

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1037]
Any idea why when I download the contracts list below country names are in French while the rest of the DRC and Tunisia contracts have an English country name.  

![image](https://cloud.githubusercontent.com/assets/13888372/22098814/060004a8-de31-11e6-88b4-276ba245fdcb.png)

**Comment by manishgs** [comment]
When user is browsing rc-admin in FR and user updates a contract then country name stored in french. This issue is now fixed.
