### ISSUE TITLE
Delete 'Transfer of risk' from Annotation categories

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#1038]
Please delete 'Transfer of risk' from Annotation categories codelist. We do not plan to use this annotation category at all for either RC or OLC.

**Comment by shashikhanal** [comment]
There are [8 contracts](http://admin.resourcecontracts.org/contract?type=annotations&word=transfer-of-risk&issue=present) which currently use 'Transfer of risk' annotation category. Please, update those contracts' annotation category first.

**Comment by anjesh** [comment]
@charlesyoung @SamCCSI please let us know to which category does this "transfer of risk" map to, or we simply delete this annotation?

**Comment by SamCCSI** [comment]
Thanks @anjesh @shashikhanal we are investigating these further and will be back in touch

**Comment by charlesyoung** [comment]
@SamCCSI any feedback?

**Comment by SamCCSI** [comment]
@anjesh @shashikhanal these have been deleted, and we are now ready to entirely delete the Transfer of Risk annotation category.

Best,
Sam

**Comment by charlesyoung** [comment]
@shashikhanal can you please attend to this ticket?

**Comment by manishgs** [comment]
"Transfer of Risk annotation" category removed from category codelist.
