### ISSUE TITLE
Change "Stabilization clause" annotation category to "Stabilization"

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#1039]
Please reword the "Stabilization clause" annotation category to "Stabilization."

(Justification: some annotations under this category talk about clauses that *prevent* stabilization, rather than actually being stabilization clauses. It is therefore more accurate to refer to this clause as "stabilization")

**Comment by SamCCSI** [comment]
Once this change is made, can we also ensure URLs containing the old annotation category name still work?

E.g. make sure that anytime an RC or OLC URL has **search?q=&annotation_category%5B%5D=Stabilization+clause** in it, it should act as though the search query is just for "stabilization"?

**Comment by manishgs** [comment]
"Stabilization clause" changed to Stabilization.

http://resourcecontracts.org/search?q=&annotation_category%5B%5D=Stabilization+clause
