### ISSUE TITLE
PDF not loading

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1041]
PDF not loading although published. 

[Backend](http://resourcecontracts.elasticbeanstalk.com/contract/2015)
[Frontend](http://www.resourcecontracts.org/contract/ocds-591adf-6186641258/view#/pdf)

**Comment by manishgs** [comment]
There was an issue with signature date format. Elastic search failed to parse the date format (2011-5-27). I have updated signature date (2011-05-27). Now it is showing on frontend.

**Comment by charlesyoung** [comment]
Thanks @manishgs. Please check that other contracts don't have the same issue.

**Comment by manishgs** [comment]
We have updated signature date format of all contracts and implemented date validation.
