### ISSUE TITLE
Additional country subsite request (for S19 planning)

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#1043]
Per previous conversations with @charlesyoung, I'm logging this ticket for S19 planning purposes - we are currently in early discussions with partners regarding the establishment of an additional OLC subsite - if this proceeds, we'll need to establish a subdomain and demo site.

**Comment by charlesyoung** [comment]
@JesseCCSI just checking if the additional country subsite will need to be done by the end of March because all S19 tickets has to be closed by the 31 March.

**Comment by JesseCCSI** [comment]
Thanks @charlesyoung can we discuss on Friday? (and same for the DRC ticket)?

**Comment by JesseCCSI** [comment]
Please go ahead and set up this demo site (as discussed offline). Please see the Country Subsite Details Google Doc for details (URL etc.). 

Many thanks.

(cc @charlesyoung @KaitlinCCSI)

**Comment by JesseCCSI** [comment]
Please note that this site should not be made public - please launch as a demo site.

**Comment by anjesh** [comment]
There's no contract for the given country. Can we make sure that there's atleast one to deploy?

**Comment by charlesyoung** [comment]
@anjesh we can upload a test / demo doc but it will have to be on the staging site. 

cc @JesseCCSI

**Comment by JesseCCSI** [comment]
Thanks @charlesyoung @anjesh I meant to upload a test doc at the weekend - I can do so tonight, unless you plan to upload one? Apologies for delay.

**Comment by manishgs** [comment]
@charlesyoung @JesseCCSI 
I've updated staging site url on google doc. Please review the site and let know your comments.

**Comment by JesseCCSI** [comment]
Many thanks @manishgs @charlesyoung  just sent an email to you (copying Charles) with comments. After these comments have been addressed, we can close this ticket for now (leaving the site in demo site mode).

**Comment by manishgs** [comment]
Text and background image updated.

**Comment by JesseCCSI** [comment]
Thanks @manishgs looks like the CCSI logo disappeared from the footer?

**Comment by manishgs** [comment]
Yes the logo was removed on staging, Now showing CSSI logo on the footer.

**Comment by JesseCCSI** [comment]
Thanks @manishgs just two quick things: (1) the issue I flagged re "Voir par Resource" hasn't been addressed - I think this applies to all French sites, i.e. should be "Voir par Ressource"; (2) there's something strange going on with the name of the site in the box and along the top of the header when the site is in FR mode - the name of the country repeats itself.

**Comment by manishgs** [comment]
1. Fixed
2. Fixed. On mobile view, we have change the country name to short name.
