### ISSUE TITLE
Contracts not annotated noted as annotated 

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1044]
Search for all Tunisia contracts annotated shows 54 contracts on both the [public ](http://www.resourcecontracts.org/search?q=&country%5B%5D=tn&annotated=1)and [country ](http://tunisia.resourcecontracts.org/search?q=&annotated=1)site. 

The issue is that the search is displaying contracts that haven't been annotated like this [contract](http://admin.resourcecontracts.org/contract/2270).

**Comment by charlesyoung** [comment]
@anjesh can you please prioritize this ticket. 

It also relates to contracts from other countries besides Tunisia.

**Comment by manishgs** [comment]
fixed.
