### ISSUE TITLE
New feature display

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1045]
I have heard on numerous occasions that users are unaware of new RC functionality. Should we not add a note, like below website, on the home page to inform users of new functionality? The clipping functionality stands out and users could be notified of the new feature and be pointed to the clipping guide for reference. 

https://fts.unocha.org

cc @jedm @SamCCSI

**Comment by jedm** [comment]
@charlesyoung Some plans are emerging at CCSI to spec out something similar for OLC. Curious if this plan went anywhere in another Issue -- and how the latest "tours" and how-tos have been working for NRGI. cc @SamCCSI

**Comment by charlesyoung** [comment]
Closing this ticket because its part of the new home page design (#1225)
