### ISSUE TITLE
Bug: site not allowing any changes or new uploads

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#1046]
![image](https://cloud.githubusercontent.com/assets/12913915/22573210/ee6a86f6-e975-11e6-9043-08ad9b101b40.png)

Happened to a researcher and to me today. Apparently it happened on Monday as well. The above message occurs when they try to upload a new document and when either of us try to amend the metadata of a contract.

For me it happened for this contract: http://admin.resourcecontracts.org/contract/1166

cc @charlesyoung

**Comment by manishgs** [comment]
fixed.
