### ISSUE TITLE
Translation to French not working

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#1047]
When I have a contract and I want to translate the listing to French, the name generator still uses the English term for the document type, instead of the French:

![image](https://cloud.githubusercontent.com/assets/12913915/22762217/3c7793e2-ee2c-11e6-852b-490cace29cc3.png)

**Comment by man-git007** [comment]
The "Generate Contract Name" is now translating to preferred language (French or Arabic) on selecting language in "Contract Information Translation" in "Edit Metadata" page for any contract.
![french](https://cloud.githubusercontent.com/assets/23434972/23391865/09232208-fda0-11e6-96f7-946e4ae62dbd.png)

**Comment by SamCCSI** [comment]
When I click 'generate contract name' it still reverts to the English version of the doc type:
http://admin.resourcecontracts.org/contract/2355/edit/fr

![image](https://cloud.githubusercontent.com/assets/12913915/23406535/69903fd0-fd8d-11e6-8b5e-55b42765d7a4.png)

**Comment by man-git007** [comment]
It is now done. Please check @SamCCSI

**Comment by SamCCSI** [comment]
@man-git007 Thanks! Working now.
