### ISSUE TITLE
Add 'Cahier des charges' as contract type

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#1048]
Please add Add 'Cahier des charges' as another contract type
- needed by Tunisian country importers cc @charlesyoung 
- also relevant for OLC

**Comment by charlesyoung** [comment]
This has already been added to allow for the Tunisia Mining contracts import.

**Comment by SamCCSI** [comment]
@charlesyoung 

I don't see it on the list, and it looks like the Tunisian cahiers des charges are being uploaded as 'mining contracts':  example: http://admin.resourcecontracts.org/contract/2490

![image](https://cloud.githubusercontent.com/assets/12913915/22785412/2a4d07da-eea2-11e6-8897-79509ac16175.png)

**Comment by charlesyoung** [comment]
We had agreed with Perrine that the English translation for  'Cahier des Charges' is 'Mining Contract':

**Comment by SamCCSI** [comment]
Thanks @charlesyoung
