### ISSUE TITLE
Error for two Ukrainian contracts

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#1049]
From a partner organization:

I was "playing" with the API and I found this issue:

There are 2 contracts listed using the API (also can be searchable in
the web) that cannot be accessed

http://www.resourcecontracts.org/search?q=ocds-591adf-3556799773

http://www.resourcecontracts.org/search?q=ocds-591adf-9306866843

If I try to access to the contract, I get an error:
http://www.resourcecontracts.org/contract/ocds-591adf-3556799773/view#/pdf

http://www.resourcecontracts.org/contract/ocds-591adf-9306866843/view#/pdf

I hope that this information could be helpful for you.

**Comment by manishgs** [comment]
The issue was that both the contract's parent was the contract itself, so there was endless loop in API. I've removed the parent contract, now it is fixed. Please update the parent/associate contract.
