### ISSUE TITLE
Create simple links to mining legislation documents at a-mla.org

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#105]
If a document is from <country> this document need a link to the African Mining Legislation Atlas, which holds core legislative documents relevant to extractives. 

See the basic link list here: 
https://docs.google.com/spreadsheets/d/1EVuMc4R9NfDbJuANc1VAgLVfqCxP7aoaI2nkfXa1f8c/edit#gid=0

**Comment by anjesh** [comment]
Anders, can you be more specific about the linkage? basis of linkage?

**Comment by anderspeders** [comment]
Yes, 

An example: 
a) If metadata for contract is mali: http://resourcecontracts.elasticbeanstalk.com/contract/27
b) then place a link to: **Current mining legilation in the country as available at "African Mining Legislation Atlas**  
--> Link to here http://a-mla.org/index.php/countries/30

**Comment by anjesh** [comment]
Ok. If the contract country is one of [50 countries here](https://docs.google.com/spreadsheets/d/1EVuMc4R9NfDbJuANc1VAgLVfqCxP7aoaI2nkfXa1f8c/edit#gid=0), then we just show the link to the amla in the contract view page in both admin and subsite interface. Correct?

**Comment by anjesh** [comment]
Related to #49

**Comment by anderspeders** [comment]
Yes that is correct, 

This is correctly step 1 for completing user story #49. More specific requests might follow once a better API have been developed on the side of AMLA.

**Comment by anderspeders** [comment]
Thanks for this update. 

I suggest that we work a bit on the UI here. One suggestion is below:

![amla-relocation](https://cloud.githubusercontent.com/assets/1101585/8916909/ace0a314-347c-11e5-8b0a-1d48ac165108.JPG)

**Comment by anjesh** [comment]
Fixed.
