### ISSUE TITLE
API listing a different number of published contracts to the front-end

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#1050]
There are 171 on the OLC front-end but only 167 returned through the API. From a partner organization that is pulling information on published OLC contracts:

 

I developed a program to retrieve the full metadata for each contract (available on github under MIT license).
https://github.com/landportal/data/blob/master/landlibrary/importers/OLC/olc-get-all-contracts-metadata.py

I have re-run the script and there are again 167 contracts (probably includes some "non-existing" ones (like ocds-591adf-5517188061)). The list of contracts is obtained directly from the RC API.

http://rc-api-stage.elasticbeanstalk.com/api/contracts?category=olc&per_page=500

So, I think that there is an issue on the API side (maybe a caché issue).

**Comment by manishgs** [comment]
http://rc-api-stage.elasticbeanstalk.com/api/contracts?category=olc&per_page=500 
This API URL is old which is no longer maintained. We have moved the API URL to http://api.resourcecontracts.org/contracts?category=olc. Please use the new one.

@charlesyoung 
Could you please confirm Philippines subsite is using new API URL so that we can remove the old  API URL?

**Comment by SamCCSI** [comment]
Can we make this information public? E.g. on the page of the old API can we
notify users that this is the case.



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School | The Earth Institute, Columbia University
435 W116th St. New York, NY 10027
| (+1)(646) 630-4123 <+1646-630-4123>
| s.burke@columbia.edu
| ccsi.columbia.edu <http://www.ccsi.columbia.edu/> | @CCSI_Columbia
<https://twitter.com/CCSI_Columbia> | @samszokeburke
<http://twitter.com/samszokeburke>

**Comment by charlesyoung** [comment]
@manishgs the Philippines is using the new API URL.

**Comment by manishgs** [comment]
Wiki has been updated. We'll remove the old API from next week.
