### ISSUE TITLE
More problems with obsolete elasticbeanstalk URL refs

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#1051]
Again, reported from a partner org:

just to say that, after run the script (with the updated API URL) to obtain all the metadata from resourcecontracts, the are some references to "elasticbeanstalk" that maybe you would like to curate and update.

Please, find attached the file with all the metadata that could help that in that process.
https://www.dropbox.com/s/h8xeok79rv2q4u2/rc-contracts-metadata.json?dl=0

**Comment by charlesyoung** [comment]
@manishgs can you please take a look at this.

**Comment by anjesh** [comment]
Users are writing elasticbeanstalk url in opencorporates metadata and also mentioning these links in the notes section e.g. 

![image](https://cloud.githubusercontent.com/assets/120488/23117922/1d582f60-f77a-11e6-9428-fcd33554949a.png)

![image](https://cloud.githubusercontent.com/assets/120488/23117936/30474fca-f77a-11e6-9467-42f1fba0edff.png)

This is the issue with data entry itself and not with the system. These should be fixed manually by the users themselves. 

Thanks.

**Comment by anjesh** [comment]
I am closing this as this is to be fixed by users themselves in the data.
