### ISSUE TITLE
Changes to French OLC homepage recorded in Google doc

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#1052]
FYI - some of these changes reflect previous requests in tickets #971 and #873.  

All changes have been recorded on the OLC hompage tab in this doc: https://docs.google.com/spreadsheets/d/1FYGpCtUDczJzUtzmBn97zJH4BeGL2aO4VeBIKMnRWMo/edit?ts=5874b615#gid=1944805571 

Some changes are also relevant for RC (as mentioned to @charlesyoung via email).

**Comment by manishgs** [comment]
French Text has been changed according to Google Sheet. Please do verify.

**Comment by JesseCCSI** [comment]
Thanks @manishgs looks good - just removed some extra spaces in cell C5.
