### ISSUE TITLE
Associated documents not displaying for main contract

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#1054]
http://www.openlandcontracts.org/contract/ocds-591adf-5399370669/view#/
http://admin.resourcecontracts.org/contract/682

This contract has multiple associated documents but they are not displaying on the right hand column of the contract page.
![image](https://cloud.githubusercontent.com/assets/12913915/23279826/ca3e8528-f9e4-11e6-9325-2ed387e899c0.png)

**Comment by charlesyoung** [comment]
I'm having the same problem. @manishgs can you please investigate and resolve.

**Comment by manishgs** [comment]
This issue happens when user publish a contract which has associated documents and these are already published on subsite. When user publish a contract, system publish its metadata only not all the associated document metadata therefore other associated documents will not show latest published contract on the list.
To fix this issue, we need to publish other associated documents as well.

**Comment by charlesyoung** [comment]
@manishgs I'm not sure that I follow you, I never had this issue when publishing associated documents on the Sierra Leone country site. Anyway this needs to be resolved so can you please address the issue.

**Comment by charlesyoung** [comment]
@manishgs what is the status re this ticket?

**Comment by manishgs** [comment]
@SamCCSI @charlesyoung 
Please check again we have fixed on production.

**Comment by charlesyoung** [comment]
Works for me. 

Just two minor things. 

There seems to be a difference on how the text of the associated documents is noted. 

The associated document text for this [contract](http://resourcecontracts.org/contract/ocds-591adf-0858102407/view#/) is aligned correctly and is in bold 

The associated document text for this [contract ](http://resourcecontracts.org/contract/ocds-591adf-4460143117/view#/pdf) is not aligned correctly and is not in bold

**Comment by SamCCSI** [comment]
Working for me, thanks.

@charlesyoung Bold means main doc and unbold and more narrow allignment means it is an associated doc.

E.g. In the screenshot, the first doc is main, the rest are associated.

![image](https://cloud.githubusercontent.com/assets/12913915/23751599/13637f72-04a0-11e7-9515-ded041e13bae.png)
