### ISSUE TITLE
Back-end annotation bug

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#1055]
Sometimes, for no reason, the Art. references of an annotation move up to the previous annotation.

E.g. here. Infrastructure has references of Art. 3.1.3 and 8.2. But in the screenshot, those references are given to "Income tax" and Infrastructure has references to Art. 17, which are actually for the "Language" category, below.

![image](https://cloud.githubusercontent.com/assets/12913915/23315624/0e068c0a-fa95-11e6-886c-f2ed8728dc59.png)

This makes it hard to edit and update annotations. I don't think this is a new problem either, though I have encountered more recently.

**Comment by SamCCSI** [comment]
Update: it seems to be caused when an earlier annotation is deleted on the back-end.

It can be solved by hitting refresh. But this still seems very buggy, so a fix, if not too time-intensive, would be good to keep the system stable, and to avoid our annotators being distracted.

**Comment by man-git007** [comment]
@SamCCSI @charlesyoung We have fixed the annotation bug issue and deployed it in the staging server. Could you please verify it.

**cc** @anjesh @bizaybsnt

**Comment by SamCCSI** [comment]
thanks @man-git007 this change affects the back-end. Is there a staging for the back-end that i should test it on? I tried http://admin.staging.resourcecontracts.org/ but that didn't work. Thanks

**Comment by bizaybsnt** [comment]
please check http://admin-staging.resourcecontracts.org/
Thanks.

**Comment by SamCCSI** [comment]
thanks @bizaybsnt -- i'm trying to load this annotated contract to experiment but it's not loading. any tips? http://admin-staging.resourcecontracts.org/contract/2738/annotate#/pdf/page/9/annotation/24988

**Comment by bizaybsnt** [comment]
Hi @SamCCSI,
This is staging site. All the pdf of contracts are not properly updated/uploaded in the system properly. Please test for the contract with pdf file or you can upload the new pdf for particular contract.

**Comment by SamCCSI** [comment]
Hi @bizaybsnt we need to see how the annotation module works in staging in order to let you know if the problem is resolved. So accessing the PDF won't be enough. Any ideas for how we can do this?

**Comment by bizaybsnt** [comment]
Hi @SamCCSI,
Here is the working mechanism for annotation module.

The annotations are added in the staging site via admin panel http://admin-staging.resourcecontracts.org/.
![image](https://user-images.githubusercontent.com/25411368/77617596-adb1b380-6f5c-11ea-9dc5-8290a1c16473.png)

 Once the annotation are added and saved, this needs to be complete and publish. 
![Screenshot from 2020-03-26 12-59-16](https://user-images.githubusercontent.com/25411368/77620240-02a3f880-6f62-11ea-932d-7dd12ec2ae3e.png)


After publishing the annotation, It may takes few minutes for processing. We can see the annotation reflected on the main site only after publishing the annotation from the admin panel.
![image](https://user-images.githubusercontent.com/25411368/77628466-3259fd00-6f70-11ea-9b53-f6e15b1216ab.png)


Here is the admin link and website link for a sample contract:
https://admin-staging.resourcecontracts.org/contract/2903/annotate
https://staging.openlandcontracts.org/contract/ocds-591adf-6858445103/view#/pdf

You can test by adding completely new contract in the staging site.

Please feel free to mention if you have any confusions.

cc: @man-git007 @anjesh

**Comment by SamCCSI** [comment]
Thanks, it seems to work now.

Please note: this annotation module is still very buggy. I believe this is the issue that YI will be doing research into (# 1.a. "Problem saving annotations, incorrect category listings - background research" in our spreadsheet for sprint 25.)

Example. I tried to change annotation 1's article ref to be "Art. 1". Clicked save. and no changes save. This is the exact problem that annotators often face and needs to be fixed in this sprint. cc @anjesh 

![image](https://user-images.githubusercontent.com/12913915/77651778-a9c56780-6f43-11ea-932d-bde37af97593.png)

![image](https://user-images.githubusercontent.com/12913915/77651835-bcd83780-6f43-11ea-872e-7286bf3087fa.png)

**Comment by bizaybsnt** [comment]
@SamCCSI Did you receive any error message while saving the annotation? I tried editing the same annotation and able to successfully edit.
![image](https://user-images.githubusercontent.com/25411368/77728139-fb452380-7023-11ea-857c-b7d91b1c7b67.png)
Could you please elaborate the issue? Also please check console if there is any javascript error.
![image](https://user-images.githubusercontent.com/25411368/77728681-19f7ea00-7025-11ea-92e6-c0e578c35b4f.png)

cc: @anjesh @man-git007

**Comment by SamCCSI** [comment]
@bizaybsnt just tried again and the editing function is working without bugs.

Delete function also still working smoothly.

**Comment by man-git007** [comment]
@SamCCSI Are we good to go on the live server?

**Comment by SamCCSI** [comment]
@man-git007 yes, thanks. I will check it once it's live as well, to make sure no new issues. Please let me know.

**Comment by man-git007** [comment]
@SamCCSI The issue fix has been deployed to the production site. We can close this issue and #1106 as well.

cc @anjesh @bizaybsnt

**Comment by SamCCSI** [comment]
Confirming we can close this and #1106. I just checked on a live contract and the annotation edit and delete functions are working really nicely. Thank you @man-git007 and all!

**Comment by SamCCSI** [comment]
I just edited the text of the arbritation annotation for this contract in the contract annotation view. It said it saved, but the changes didn't appear. Included after I hit refresh. @man-git007 could you please take a look? 
![image](https://user-images.githubusercontent.com/12913915/82101521-b4e27b80-96da-11ea-9eca-928711efe2f9.png)

**Comment by bizaybsnt** [comment]
Hi @SamCCSI, 
We have fixed the issue and deployed it in the staging. Would you please check if it is working on the staging site?
Thanks.
cc: @man-git007 @anjesh

**Comment by SamCCSI** [comment]
working, thanks @bizaybsnt. Please deploy

**Comment by bizaybsnt** [comment]
Deployed in production. Thanks :)

**Comment by SamCCSI** [comment]
Working nicely. Thanks @bizaybsnt
