### ISSUE TITLE
Toolbar fixes

### ISSUE THREAD

**Issue by jedm** [NRGI/resourcecontracts.org#1059]
1) When user switches between PDF and TXT view, Toolbar icon must switch to bold to show which view is live.

2) Per previous requests, please make clip icon same weight as Share and Download icons. (See https://github.com/NRGI/resourcecontracts.org/issues/893#issuecomment-255961987)

![screen shot 2017-03-20 at 1 23 51 pm](https://cloud.githubusercontent.com/assets/2153664/24120227/1106ec4e-0d71-11e7-98cd-8f28101f0c42.png)

**Comment by manishgs** [comment]
fixed.
