### ISSUE TITLE
Commenting feature by researcher in the publishing workflow

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#106]
There needs to be commenting feature by anyone in the contract for metadata, annotation and text. Currently only administrator can comment during rejection and researcher can't give feedback after making changes in the contract.

**Comment by anderspeders** [comment]
I wonder if Hypothes.is have come up with a solution for **public commenting** and discussion of annotations?

https://hypothes.is/

cc @byndcivilization

**Comment by byndcivilization** [comment]
I thought we explicitly did not want public commenting at this stage. I think @anjesh is only talking about researcher commenting, right? Should check with CCSI if there needs to be this type of back and forth.

**Comment by anjesh** [comment]
Yes, i was talking about researcher commenting only - because when the admin rejects their work - annotation, text or metadata, the researcher might want to want his/her comments to what s/he has updated or fixed.
