### ISSUE TITLE
Partner logo

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1060]
@anjesh can you please add the OpenOil logo I sent you to the RC [staging ](http://staging.resourcecontracts.org/)site. The logo should appear under 'Partners' and be placed to the right of the World Bank logo.

**Comment by manishgs** [comment]
Logo is added in RC site.

**Comment by charlesyoung** [comment]
Thanks @manishgs 

I will close the ticket once we get the green light to update the prod site.

**Comment by anjesh** [comment]
open oil logo displayed in production @anderspeders 

![image](https://user-images.githubusercontent.com/120488/41221865-220946ca-6d85-11e8-8839-2e7aaacd99b4.png)

**Comment by anjesh** [comment]
@anderspeders reverted back
