### ISSUE TITLE
Mobile design

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1061]
Address any outstanding issues noted in #896

**Comment by SamCCSI** [comment]
Mobile view of new site has visual noise / some design elements that to be improved. For example:
- "Learn how to use this site" should be in White text
- Annotation boxes appear as numbers in a bubble - not clear what they are 
- there are view icons over the map

cc @anjesh @man-git007 @charlesyoung 

![IMG_7241](https://user-images.githubusercontent.com/12913915/88563627-30787700-d000-11ea-8fe8-cb94c01d60b8.jpg)
![IMG_7242](https://user-images.githubusercontent.com/12913915/88563633-32423a80-d000-11ea-8611-a9803f3401f3.jpg)

**Comment by man-git007** [comment]
@SamCCSI The mobile view has been updated and deployed in live server

**Comment by SamCCSI** [comment]
thanks @man-git007 -- this looks really nice.

Inside the search box the "Search [#] contracts and..." is cut off. Should we just remove the text there? Or change it to "Search [#] documents" ?

**Comment by charlesyoung** [comment]
@man-git007 ??

**Comment by man-git007** [comment]
@charlesyoung The search filed placeholder mentioned by @SamCCSI has been updated and deployed in live server. The screenshots are attached below.
![Screenshot from 2020-08-07 15-54-09](https://user-images.githubusercontent.com/23434972/89635243-6a7e2e80-d8c6-11ea-9689-975bc85103b7.png)
![Screenshot from 2020-08-07 15-55-47](https://user-images.githubusercontent.com/23434972/89635292-7d90fe80-d8c6-11ea-80e6-51efb3588d07.png)

**Comment by man-git007** [comment]
@charlesyoung @SamCCSI Is there anything left in this ticket? If not let's close this ticket.

**Comment by charlesyoung** [comment]
@SamCCSI ??
