### ISSUE TITLE
Admin site down

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1064]
@iprunache can you please take a look at the [backend ](http://resourcecontracts.elasticbeanstalk.com/contract) site because its down. Should we not get a notification when the sites go down? 

![image](https://cloud.githubusercontent.com/assets/13888372/24848586/b7a3525c-1dc7-11e7-98ee-b7a692c1caa8.png)

**Comment by anjesh** [comment]
@charlesyoung you should be using http://admin.resourcecontracts.org/ and not http://resourcecontracts.elasticbeanstalk.com/, which is using instance from our account, which is now discontinued.
