### ISSUE TITLE
OLC name/logo in top left was changed - please change back

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#1067]
The "OPENLAND" part of the name has been italicized without our requesting that. Not sure why that happened, but could you please revert back to original version, which was not italicized?

current version:
![screen shot 2017-04-12 at 4 20 38 pm](https://cloud.githubusercontent.com/assets/14825437/25025368/93c0cbec-2067-11e7-84f2-fb4d4982b18e.png)

original version (upper left corner):
![image](https://cloud.githubusercontent.com/assets/14825437/25025414/cfaac518-2067-11e7-98b8-cccc5c227795.png)

**Comment by jedm** [comment]
This is an even smaller matter, and up to @KaitlinCCSI, but would recommend
consistency between prose title and logotype with the spacing -- ie, CCSI
should choose between "OpenLand" and "Open Land"

**Comment by KaitlinCCSI** [comment]
Thanks, Jed. @anjesh - At the very least, we would like to revert OPENLAND to its original non-italicized version. If possible, could you please also add a small space between OPEN and LAND, so that the two words are slightly separated but still aligned with the CONTRACTS on the line below?

**Comment by charlesyoung** [comment]
@SamCCSI can this ticket be closed?
