### ISSUE TITLE
Contract default view includes embedded error message at bottom of the page

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#107]
See for exampl: http://resourcecontracts.elasticbeanstalk.com/contract or http://resourcecontracts.elasticbeanstalk.com/contract/12

**Comment by anjesh** [comment]
Currently [pdfprocessing - pdfseparate](https://github.com/anjesh/pdf-processor) generates huge files (hence occupying huge space in current server of 7.8GB, and causing memory problem) during split and also seems to take long time for separating pdf pages. It's changed to [pdftk](https://github.com/anjesh/pdf-processor/commit/f1c5516a0f2ab84900d6e3ccbdc7eeb7a8f49a7f), which is much faster and generates smaller pdf files.
