### ISSUE TITLE
Other document type

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1072]
Remove the option of capturing free-text when selecting the 'Other' document type. This is to stop new document types being added creating an unstandardized list. 

![image](https://user-images.githubusercontent.com/13888372/29663946-cc886ec0-88cd-11e7-8408-79d451e76337.png)

**Comment by charlesyoung** [comment]
A note that this ticket needs to be completed by the 15/11.

**Comment by anjesh** [comment]
All these should have been 15/12 except for the subsites.
