### ISSUE TITLE
Standardize document types

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1073]
Update document types as noted in below Google Sheet.

https://docs.google.com/spreadsheets/d/1Gcki2iL95trnMFvJI44iDW4wZvtwBVKe84Ca8anNxxA/edit#gid=1236274355

**Comment by SamCCSI** [comment]
For most of these I suggest we use existing categories. This will keep in harmony with our original thinking on doc and contract types, and will reduce having too many very similar doc and contract types, which will reduce utility of drop-down lists:

1 - Suggest using *Doc type = Private contract*
2 - Suggest using *Doc type = contract*; *Contract type = Contract Annex*
4 - Whenever Doc type = Contract, we are talking about 'company state contracts', so I would suggest you use *Doc type = Contract*; *Contract type = Concession* [or whichever else is most appropriate from the existing list]
5 - Suggest using *Doc type = Model Contract*

**Comment by charlesyoung** [comment]
@SamCCSI below is the suggestions from Perrine. We need to reduce and standardize the exiting doc types. 

https://docs.google.com/spreadsheets/d/1Gcki2iL95trnMFvJI44iDW4wZvtwBVKe84Ca8anNxxA/edit#gid=1236274355

**Comment by charlesyoung** [comment]
A note that this ticket needs to be completed by the 15/11.

**Comment by anjesh** [comment]
@charlesyoung 
Looked at the database and it has different types than the ones listed in the sheet above. Created a [new sheet](https://docs.google.com/spreadsheets/d/1Gcki2iL95trnMFvJI44iDW4wZvtwBVKe84Ca8anNxxA/edit#gid=655013550) with existing doc.types as per database and need to fill the missing NA (Not Available)

**Comment by charlesyoung** [comment]
Thanks @anjesh 

Can you please check your list because I have 'Annulation de permis' and 'Private Contract' noted as a Company-State Contract while you have it as NA. 

Also please only list RC doc types and not OLC doc types.

**Comment by anjesh** [comment]
I have re-generated the list again here https://docs.google.com/spreadsheets/d/1Gcki2iL95trnMFvJI44iDW4wZvtwBVKe84Ca8anNxxA/edit#gid=973523524 for RC only there are still few missing labels. @charlesyoung please have a look.

**Comment by anjesh** [comment]
@charlesyoung 

I tried to map with the existing [doc-type codelist](https://github.com/NRGI/resourcecontracts.org/blob/master/resources/lang/fr/codelist/documentType.php) and here's the [situation](https://docs.google.com/spreadsheets/d/1Gcki2iL95trnMFvJI44iDW4wZvtwBVKe84Ca8anNxxA/edit#gid=1022966203) 

There are 4 new proposed doc-types compared to linked codelist above. 
```
Company-State Contract
Company-Company Contract
Environmental and Social Document
Company-State Model Contract
```
* Do we include these in the [codelist](https://github.com/NRGI/resourcecontracts.org/blob/master/resources/lang/en/codelist/documentType.php#L11)? If yes, then we will need fr and ar translations for these as well. 

* There's one missing label. If we remove `Ratification`, there's no alternative for 1 contract. See red-[colored row](https://docs.google.com/spreadsheets/d/1Gcki2iL95trnMFvJI44iDW4wZvtwBVKe84Ca8anNxxA/edit#gid=1022966203)

* There are [4 ?](https://docs.google.com/spreadsheets/d/1Gcki2iL95trnMFvJI44iDW4wZvtwBVKe84Ca8anNxxA/edit#gid=1022966203) which need filling

* [`Environmental Impact Assessment`](https://github.com/NRGI/resourcecontracts.org/blob/master/resources/lang/en/codelist/documentType.php#L11) is valid codelist. Is it to be removed?

The above discussion applies to RC only and OLC isn't affected.

![image](https://user-images.githubusercontent.com/120488/34866319-59e526e2-f7a4-11e7-98d3-b1922f9d6725.png)

**Comment by charlesyoung** [comment]
1. Yes, needs to be added to the codelist. Will get the translations
2. What is the ratification contract name because this was added to the main contract and unpublished
3. Will get back to you
4. Yes

**Comment by charlesyoung** [comment]
Translations completed. 

cc @anjesh

**Comment by charlesyoung** [comment]
@anjesh just checking when this will be done. 

https://docs.google.com/spreadsheets/d/1Gcki2iL95trnMFvJI44iDW4wZvtwBVKe84Ca8anNxxA/edit#gid=1022966203

cc @SamCCSI

**Comment by charlesyoung** [comment]
Please note that the updates should only apply to RC and not OLC. 

cc @KaitlinCCSI @SamCCSI @anjesh

**Comment by charlesyoung** [comment]
@anjesh just following up on the status of this ticket.

**Comment by anjesh** [comment]
@charlesyoung this is the status after updates in staging site. 

document.type | olc | rc
-- | -- | --
Amendment to Social Agreement of Contract   Specifications | 1 | NA
Annulation de permis | NA | 1
Clause sociale | 1 | NA
Company-Company Contract | NA | 4
Company-State Contract | NA | 1514
Company-State Model Contract | NA | 71
Contract | 214 | NA
Decree | 6 | NA
Document Summary | 6 | 1
Environmental and Social Document | NA | 17
Forest Management Plan | 30 | NA
List of Attendees | 1 | NA
Minutes of Meeting | 8 | NA
Model Contract | 2 | NA
Notice | NA | 10
Ratification | NA | 1
Social Agreement | 112 | NA
Social Agreement of Contract   Specifications | 1 | NA

**Comment by charlesyoung** [comment]
I know this is still on the staging site but there are 47 documents with contract document type which should be Company-State Contract.

**Comment by anjesh** [comment]
Can you list those contracts - with the URLs? Are you referring to staging-admin or staging-subsite. If it's staging-subsite, you might be right because staging-subsite is using ES-index which is updated for the newly updated contracts. There shouldn't be issue with the data in staging-admin.

**Comment by anjesh** [comment]
"Annulation de permis" and "Ratification" still appear here as it doesn't have substitution. They are to be removed as per [this](https://docs.google.com/spreadsheets/d/1Gcki2iL95trnMFvJI44iDW4wZvtwBVKe84Ca8anNxxA/edit#gid=1022966203) @charlesyoung

**Comment by anjesh** [comment]
Updated in production now. @charlesyoung

**Comment by charlesyoung** [comment]
Thanks @anjesh 

Just noticed that there is 1 [doc ](http://www.resourcecontracts.org/search?q=&document_type%5B%5D=Model+Contract)still noted as doc type = model contract while in the [backend ](http://admin.resourcecontracts.org/contract/2174)it is correctly noted as Company-State Model Contract. 

Also strange that its even displayed on the global site because it hasn't been published yet.

**Comment by anjesh** [comment]
I am not sure how this happened. The reason it's appearing in global site with different doc-type is because we can't re-publish that contract from the interface. I will see if that could be removed from ES index.

**Comment by charlesyoung** [comment]
@anjesh I can always delete, re-add the metadata and republish the model contract if that will be easier.

**Comment by anjesh** [comment]
Thanks - that would be easier :)

**Comment by anjesh** [comment]
working now.

**Comment by charlesyoung** [comment]
Thanks @anjesh
