### ISSUE TITLE
Add new contract type (Tunisia) 

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1074]
Add a new contract type 'Memorandum of Obligations' to allow for the batch update of all 'Mining Contract' contract types in Tunisia

**Comment by charlesyoung** [comment]
A note that this ticket needs to be completed by the 15/11.

**Comment by anjesh** [comment]
`Mining Contract` is the english translation of the contract-type = `Cahier des Charges`

See http://resourcecontracts.org/contract/ocds-591adf-9274016935/view?lang=fr#/ and http://resourcecontracts.org/contract/ocds-591adf-9274016935/view?lang=en#

Here are the translations
https://github.com/NRGI/resourcecontracts.org/blob/7ece6948faf80f507657b707280f8057f483e067/resources/lang/en/codelist/contract_type.php#L7

https://github.com/NRGI/resourcecontracts.org/blob/365661f600b101e33234d7ec9684b699edee9cde/resources/lang/fr/codelist/contract_type.php#L17

https://github.com/NRGI/resourcecontracts.org/blob/7ece6948faf80f507657b707280f8057f483e067/resources/lang/ar/codelist/contract_type.php#L7

`Cahier des Charges` is used in 43 contracts of Tunisia only

@charlesyoung, what should we do?

Option 1:

* Delete `Cahier des Charges` 
* Add `Memorandum of Obligations`
* change contract-type of 43 Tunisia contracts to `Memorandum of Obligations` from `Cahier des Charges` 

Option 2:

* Retain `Cahier des Charges` 
* Add `Memorandum of Obligations`
* change contract-type of 43 Tunisia contracts to `Memorandum of Obligations` from `Cahier des Charges` 

In any case, we need fr and ar translations for `Memorandum of Obligations`

**Comment by charlesyoung** [comment]
Yes we need to delete 'Cahier des Charges' and replace with 'Memorandum of Obligations'. 

Will get the translations.

**Comment by charlesyoung** [comment]
What I noted above is incorrect. The following should be followed. 

1. Add a new contract type 'Memorandum of Obligations' 
2. Batch update all docs with 'Mining Contract' contract type to 'Memorandum of Obligations'
3. Delete 'Mining Contract' contract type
4. Translations below

English: Memorandum of Obligations
French: Cahier des Charges
Arabic: كراس شروط

**Comment by charlesyoung** [comment]
@anjesh required translations added.
