### ISSUE TITLE
Hit batching

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1075]
Batch hits instead of creating individual hits.

**Comment by anjesh** [comment]
Looks like batching is not available through API. This has details https://forums.aws.amazon.com/thread.jspa?messageID=422027#422027 

**Can HITs created through the API be grouped into batches?**

> My guess is no, although I don't see any reason why it couldn't be. All the RUI does is create HITs from a template (which you can do with the API using hitlayoutid and hitlayoutparameters) and then store a batch id number in the annotation field for each HIT. So, you could mimic this by annotating all of your HITs with some kind of batch number and control them through the API based on that annotation.
> 
> I've tried just using the BatchId syntax generated by the RUI in an annotation for a HIT created through the API to see if it will force the RUI to display those HITs as a batch, but it doesn't work. So, presumably there is a hidden variable that the RUI attaches to HITs to make them available as a batch.
> 
> If all you want to do is manage HITs through the RUI, you can still manage the ones created via the API on https://requester.mturk.com/mturk/manageHITs

@charlesyoung do you have access to RC Mturk account? I can't access with the one i have.

**Comment by charlesyoung** [comment]
There must be a way because we have had so many complaints from people requesting that we change from individual to batch HITs. 

Do we do it through the API or publishing interface (see below)? 

http://docs.aws.amazon.com/AWSMechTurk/latest/RequesterUI/PublishingYourBatchofHITs.html

I will get the RC Mturk account details.

**Comment by charlesyoung** [comment]
I received below messages today relating to batching hits. We will need address this issue. 
---------------------------
Hello, um can't you just condense your surveys in hits. The license read survey can have many different hits condense in their one survey. One survey with 400+ hits. Not one survey per one hit.
---------------------------
Please put these up as one hit group.  You putting up 1000 individual hits is making it difficult for the rest of us search hits. 
---------------------------
I estimate that you put up 440 HITS.  Are you kidding me?  Don't spam mTurk.  Not cool.
---------------------------
Please don't spam Mturk with so many  hits. We have to skip through 7 pages just to find work that isn't yours now. It greatly impacts us workers ability to earn money on this website due to your selfish actions.
---------------------------

**Comment by SamCCSI** [comment]
@charlesyoung this is at our end; my apologies. We had a group of new documents all needing transcription, and hadn't realized (or remembered) that this was a concern. Will try to limit it to one new doc at a time to avoid creating these problems for MT workers again

**Comment by charlesyoung** [comment]
No problem @SamCCSI. I think we need to in any case look at this issue because it have been raised on numerous times by Turkers.
