### ISSUE TITLE
Staging recurring errors in logs

### ISSUE THREAD

**Issue by adinuca** [NRGI/resourcecontracts.org#1076]
In resourcecontracts.org application there are some log messages that are constantly reoccurring.

Attached, you can find a few of the logs : 
[resource_contracts.log](https://github.com/NRGI/resourcecontracts.org/files/1434015/resource_contracts.log)

**Comment by charlesyoung** [comment]
Thanks @adinuca 

What do these error messages actually mean? 

cc @iprunache

**Comment by iprunache** [comment]
@charlesyoung staging.resourcecontracts.org was unavailable because the ElasticSearch instance it was using for indexing the contracts was no longer accessible.

Compose.io which is hosting the ES instance has changed the connection parameters so we had to update them. This is fixed now.
