### ISSUE TITLE
Setup Guinea RC country site

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#1077]
guinea.resourcecontracts.org currently points to resourcecontracts.org. This should be similar to tunisia.resourcecontracts.org.

**Comment by charlesyoung** [comment]
Just a note that we will be using the existing URL - www.contratsminiersguinee.org, so will need to provide the site administrator with the required redirect details.

**Comment by anjesh** [comment]
sure guinea.resourcecontracts.org will be setup anyways and get redirected to the existing url

**Comment by iprunache** [comment]
What's the plan for deploying the Guinea site? We have the `guinea.resourcecontracts.org` domain pointing to the subsite container now but the subsite is not defined yet.

@charlesyoung to use the existing URL the administrator will have to define it as a CNAME that points to `rc-subsite-master-lb-882022876.us-east-1.elb.amazonaws.com`. But that's after we get the site online.

**Comment by charlesyoung** [comment]
Thanks @iprunache. 

@anjesh will YI define the subsite?

**Comment by anjesh** [comment]
we will be deploying the guinea subsite next week and will let you know when it's ready.

**Comment by charlesyoung** [comment]
Thanks @anjesh. 

Please first deploy on a staging site (staging.guinea.resourcecontracts.org) so that I can test and update the home page as well as not preempt the launch.

**Comment by charlesyoung** [comment]
A note that this ticket needs to be completed by the 15/11.

**Comment by charlesyoung** [comment]
Just checking on the status of the Guinea country site development. 

cc @anjesh @manishgs

**Comment by manishgs** [comment]
I've submitted pull request. @iprunache Please review.
https://github.com/younginnovations/resourcecontracts-rc-subsite/pull/6/files

Please add two new env variables in rc-subsite.
GN_TRACKING_ID - I'll send code in email.
GN_CONTACT_MAIL - Charles will provide the email.

@charlesyoung 
Please provide the admin email to Vitamin.

**Comment by charlesyoung** [comment]
Just to confirm as noted above please first deploy a staging site (staging.guinea.resourcecontracts.org).

**Comment by charlesyoung** [comment]
@manishgs just to confirm, what admin email is required? 

cc @iprunache

**Comment by manishgs** [comment]
Admin email is site owner's email address and will display on the site. Visitor will use this email to contact site admin for feedback and comments.

**Comment by charlesyoung** [comment]
Will follow up with the client and revert.

**Comment by iprunache** [comment]
We can change the email later on when Charles determines what email to be used. Until then we'll use Charles' email.

@manishgs I've reviewed the changes and they look good. The only thing is the build fails because of updates to the `alpine` image we use for the container. I've left a comment on the PR to change that to `alpine:3.4` and see if the build succeeds.

The guinea.resourcecontracts.org and staging.guinea.resourcecontracts.org are already setup so you can push to staging whenever you want to test.

**Comment by charlesyoung** [comment]
Ministry of Mines and Geology
Boulevard du Commerce – BP 295
Quartier Almamya / Kaloum
Conakry, Republic of Guinea
Phone. (+224) 625 215 567 /  625 215 568
Email : info@mines.gov.gn

**Comment by charlesyoung** [comment]
@manishgs do we have the correct filters setup on the staging site. 

RC site shows [40 ](http://resourcecontracts.org/search?q=&country%5B%5D=gn&annotated=1)annotated contracts
Guinea staging site shows [13 ](http://staging.guinea.resourcecontracts.org/search?q=&annotated=1)annotated contracts

Also there are 77 Guinea contracts on RC and 96 on the Guinea staging site.

**Comment by charlesyoung** [comment]
As noted in ticket #1079 do not migrate documents noted on lines 30-39 & 69 because they are not contracts and are already on the ministries website for download.

**Comment by manishgs** [comment]
Guinea staging site is using staging api so its showing 13 annotated contacts.
you can compare from staging site.
http://staging.resourcecontracts.org/search?q=&country%5B%5D=gn&annotated=1
http://staging.guinea.resourcecontracts.org/search?q=&annotated=1&lang=en

**Comment by charlesyoung** [comment]
@manishgs can you update the staging DB with the prod DB to allow me to run proper tests.

**Comment by iprunache** [comment]
I think Vitamin needs to do this. @manishgs what should we copy?

**Comment by manishgs** [comment]
@iprunache Did you updated env variable to use production API?

**Comment by iprunache** [comment]
@manishgs I've just added the new ENV variable and triggered a rebuild on staging. Deploy should complete in less than 10 minutes.

**Comment by charlesyoung** [comment]
@iprunache just checking if the Guinea staging site is referencing the prod DB? 

cc @manishgs

**Comment by iprunache** [comment]
@charlesyoung It's still using the staging DB.

I think @manishgs has to merge the Guinea updates to staging again for it to switch using the production DB. At the moment the changes are only on development branch.

**Comment by manishgs** [comment]
@charlesyoung Please check the staging site. It is using production API.

**Comment by charlesyoung** [comment]
Many thanks @manishgs

**Comment by charlesyoung** [comment]
Linked ticket #1079

**Comment by charlesyoung** [comment]
Please redirect guinea.resourcecontracts.org to staging.guinea.resourcecontracts.org

cc @iprunache @manishgs @anjesh

**Comment by iprunache** [comment]
@charlesyoung just to make sure, you want an actual redirect, like 302 status code, and not to actually show the staging content on guinea.resourcecontracts.org? Is that correct?
