### ISSUE TITLE
Setup Tanzania RC country site

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#1078]
http://tanzania.resourcecontracts.org/

**Comment by iprunache** [comment]
It looks like we were previously trying to set this up as `tanzania.openlandcontracts.org`.

Sample from `config/init.sh` in the subsite repo:
```
#country-tanzania
export SERVER_NAME="tanzania.openlandcontracts.org *.tanzania.openlandcontracts.org"
export TRACKING_ID=${TZ_TRACKING_ID}
export DB_DATABASE=${COUNTRY_DB_DATABASE}
export CONTACT_MAIL=${TZ_CONTACT_MAIL}
export COUNTRY=tz
```

Are we sticking with tanzania.resourcecontracts.org now?

**Comment by iprunache** [comment]
We only lacked the DNS record for http://tanzania.openlandcontracts.org. I've added that and the site is now accessible but seems broken.

**Comment by charlesyoung** [comment]
@iprunache this is a RC and not OLC site. So should be http://tanzania.resourcecontracts.org. 

The OLC site was a demo site from what I can remember.

**Comment by charlesyoung** [comment]
Please hold this ticket until further notice. 

cc @anjesh

**Comment by charlesyoung** [comment]
Please also add password protection to the tanzania.resourcecontracts.org site

**Comment by charlesyoung** [comment]
The site might also need to point to the staging DB for now.

**Comment by anjesh** [comment]
Please create staging.tanzania.resourcecontracts.org in the DNS @iprunache

**Comment by adinuca** [comment]
Hi @anjesh , I have set up the DNS but the application is responding with the resourcecontracts site. 
This might be because of the following line in [init.sh](https://github.com/younginnovations/resourcecontracts-rc-subsite/blob/e993806a70b03362e99f335b5a019a4b9712f12c/config/init.sh):
```
#country-tanzania
export SERVER_NAME="tanzania.openlandcontracts.org *.tanzania.openlandcontracts.org"
```

**Comment by anjesh** [comment]
Hi @adinuca we won't be needing tanzania.openlandcontracts.org. OLC is just a demo and mightn't be needed anymore. 

http://staging.tanzania.resourcecontracts.org is working but not http://tanzania.resourcecontracts.org/

**Comment by adinuca** [comment]
Both our set up now. I will check the logs to see what is happening.

**Comment by anjesh** [comment]
Thanks. I just pushed to the staging branch to check the staging site. Since TZ is already configured, i reckoned that the ENV variable for TZ are already present.

**Comment by anjesh** [comment]
Also Charles wants this site to be password-protected. Updates in dockerfile with regards to htpasswd?

**Comment by adinuca** [comment]
For the site to be password protected, the NGINX config for TZ needs to be changed and credentials need to be generated, also the build pipeline needs to be updated.

**Comment by adinuca** [comment]
staging.tanzania.resourcecontracts.org works now and tanzania.resourcecontracts.org as well, it will serve tanzania subsite, once you push the changes to production.

To have it password protected, you will have to create a new nginx config file and configure tanzania to use it, something like the following: 
```
server {
  server_name ${SERVER_NAME};
  root        /var/www/${CATEGORY}/public;
  index       index.php;

  client_max_body_size 100M;
  fastcgi_read_timeout 1800;

  location / {
    try_files $uri $uri/ /index.php?$query_string;
     auth_basic "Restricted content";
     auth_basic_user_file /etc/nginx/users_passwd/.htpasswd;
  }

  location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
    expires       max;
    log_not_found off;
    access_log    off;
  }

  location ~ \.php$ {
    try_files     $uri =404;
    include       fastcgi_params;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_pass  127.0.0.1:9000;
  }
}
```

You will have to change the Dockerfile to copy inside the container the newly created nginx config, and also change the init script, to use this configuration file instead of the normal subsite nginx configuration file.

Once you have done that, I can do the rest.

**Comment by charlesyoung** [comment]
Thanks both. 

Can you please however change below 

![image](https://user-images.githubusercontent.com/13888372/38028575-a3381532-3293-11e8-9c53-6a6bb2c5987a.png)

to this:

A directory of
Resource Contracts from Tanzania

Like we do for the other country sites. 
http://www.contratsminiersguinee.org/?lang=en

**Comment by anjesh** [comment]
Yes Charles. That's old configuration. So working on that. 

@adinuca Updated the dockerfile, init, and added nginx template. And pushed to staging. Now need to create .htpasswd - you do that from your end?

**Comment by adinuca** [comment]
Thank you @anjesh , doing it now.

**Comment by adinuca** [comment]
Done, for both staging and master. Only user created so far is admin@nrgi.com/password . I can change it to another user, or add additional users if you need it.

I have also configured the certificate for tanzania.resourcecontracts.org, same for staging.

**Comment by JesseCCSI** [comment]
Hi @charlesyoung i just emailed you about the TZ OLC site - hoping you catch that before more work is done on this.

**Comment by charlesyoung** [comment]
Thanks @anjesh and @adinuca. 

@JesseCCSI the http://tanzania.openlandcontracts.org site is still operational. We are setting up a RC Tanzania country site.

**Comment by JesseCCSI** [comment]
thanks @charlesyoung for clarifying - it looks like a few things have been changed so would be useful to clarify those (e.g. the original link we had for the staging site no longer works). will write offline now so as not to spam this ticket.

**Comment by charlesyoung** [comment]
@anjesh and @adinuca can you please take a look at the PDF and Text documents display. They don't seem to be displaying as shown below. 

![image](https://user-images.githubusercontent.com/13888372/38032155-3aedc846-329d-11e8-9a6c-580c1d023cf0.png)

**Comment by adinuca** [comment]
http://tanzania.openlandcontracts.org  will no longer work once the changes made by @anjesh will reach production. That is the reason why staging does no longer work.

**Comment by charlesyoung** [comment]
We need to keep http://tanzania.openlandcontracts.org as well as have http://staging.tanzania.resourcecontracts.org. These are 2 different sites.

**Comment by adinuca** [comment]
The issue with the PDF, text not showing is because the user needs to be authenticated when accessing any resources of the website, but some of the resources on the website are loaded by some libraries, that do not take into account the fact that the user is logged in. 

@charlesyoung why did you ask for the website to be protected by login? We could protect only the main pages and leave the '/api' endpoints unprotected or we could try to find where the requests are made from, and always pass a username and password.


What will be the difference between the tanzania.openlandconratcs.org site and the tanzania.resourcecontracts.org site? From what I understand it is using the same code and same configuration.

**Comment by charlesyoung** [comment]
Thanks @adinuca. tanzania.openlandcontracts.org displays open land contracts (agriculture, etc) while staging.tanzania.resourcecontracts.org will display extractives contracts (mining, etc). 

Protecting only the main pages and leaving the '/api' endpoints unprotected will be ok.

**Comment by adinuca** [comment]
OK, that means we need 2 different instances, we need the old configuration and a new one for resourcecontracts.org. I will try to add it back now.

**Comment by adinuca** [comment]
The issue with text/PDF is now fixed on staging.

There are now 2 instances, one for RC and one for OLC, but  for me they look the same. @anjesh could you please take a look and see what I missed.

@anjesh , I did my changes on 1078-set-up-tanzania-rc-subsite branch, which I merged  with staging, should I merge it with master as well?

**Comment by charlesyoung** [comment]
Thanks @adinuca. Just one request please. The Open Land Contracts site should preferably be http://staging.tanzania.openlandcontracts.org because its only a demo site. We only remove the staging part when the site is live to the public.

**Comment by adinuca** [comment]
Hi @charlesyoung, so you don't want neither of the 2 Tanzania production sites, the tanzania.openlandcontracts.org or the tanzania.resourcecontracts.org to be available for now?

**Comment by charlesyoung** [comment]
That's correct, both are demo sites. 

So the site should be http://staging.tanzania.openlandcontracts.org and http://staging.tanzania.resourcecontracts.org

Thanks

**Comment by charlesyoung** [comment]
Many thanks.

**Comment by anjesh** [comment]
@charlesyoung the current system seems to be designed in a way that there can be only one country subsite i.e. either RC or OLC for a given country. The reason we are seeing RC tagline in tz-OLC site is because of that. This needs to be handled as well if we are targetting both RC and OLC for TZ and might require a day or so to fix and handle this situation. If OLC is not of that priority, we can tackle this issue later.

**Comment by KaitlinCCSI** [comment]
We need to handle this, as there are multiple countries where this could
become an issue.

**Comment by charlesyoung** [comment]
Agree that we need to address this issue because we could have multiple countries requiring both a RC and OLC country site.

**Comment by anjesh** [comment]
We will handle only TZ RC subsite in this issue. For addressing the RC and OLC site for any given country, I have created a new issue https://github.com/NRGI/resourcecontracts.org/issues/1099
