### ISSUE TITLE
Verify the guinea contracts document count

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#1079]
http://www.contratsminiersguinee.org/#documents has 83 documents while http://guinea.resourcecontracts.org/search?q=&country%5B%5D=gn shows 77. We need to sort the discrepancies between these 2 sites and add the missing contracts to rc.org

**Comment by anjesh** [comment]
Out of [83 contracts in documentcloud](https://docs.google.com/spreadsheets/d/1GAEg_VeJbXwDIVUcwpHo74I3Sx5uOkZfAU_6mVP1wPg/edit#gid=925538363), 13 are not found in rc.org based on the pdf-file-hash (highlighted red). We need to import only 13 contracts in rc.org. After import there will be 78+13 = 91 contracts in guinea RC subsite. 

@charlesyoung Please confirm these 13 contracts - the linkages are found based on file hash only, there still might be linkage if there's slight change in the pdf file between the 2 sites. Scroll to the right of the sheet to see the linkage with rc.org contracts. 

Note: There are [78 contracts in rc.org](https://docs.google.com/spreadsheets/d/1GAEg_VeJbXwDIVUcwpHo74I3Sx5uOkZfAU_6mVP1wPg/edit#gid=1291769673) in admin interface and 9 are not present in documentcloud (highlighted orange). I believe we do not need to worry about these.

**Comment by charlesyoung** [comment]
Thanks @anjesh. 

Yes no need to worry about the 9 contracts on RC but not in documentcloud. 

Please hold on importing the 13 contract because some seem to be Codes not relevant to RC i.e. Forest Code, Tax Code, Pastoral Code, etc. I will check and get back to you.

**Comment by charlesyoung** [comment]
@anjesh are you sure the documentcloud API is pulling the correct language data because see below. The Google sheet notes that this contract is in English. 

![image](https://user-images.githubusercontent.com/13888372/32363686-2bd92ae4-c079-11e7-8139-47be1a9c3238.png)

**Comment by anjesh** [comment]
API seems correct. I checked and there are only 3 French lang mentioned but in different columns. Not sure what that language:eng means. 

![image](https://user-images.githubusercontent.com/120488/32365428-ebd91002-c0a1-11e7-902d-534668d7bdee.png)

**Comment by charlesyoung** [comment]
A note that this ticket needs to be completed by the 15/11.

**Comment by anjesh** [comment]
I think this should have been 30/11

**Comment by charlesyoung** [comment]
Relating to the Google [Sheet](https://docs.google.com/spreadsheets/d/1GAEg_VeJbXwDIVUcwpHo74I3Sx5uOkZfAU_6mVP1wPg/edit?ts=59faf395#gid=925538363). 

1. Migrate contracts noted on lines 20 and 24
2. Do not migrate documents noted on lines 30-39 & 69 because they are not contracts and are already on the ministries website for download

**Comment by charlesyoung** [comment]
@manishgs just checking when the missing contracts will be migrated.

**Comment by anjesh** [comment]
Hi Charles, since it's just 2 contracts, we will manually add these to the system. It will be easy and time-saver than writing a migration script. Please confirm that it's only 2 contracts.

**Comment by charlesyoung** [comment]
Thanoks @anjesh 

Yes its 2 contracts.

**Comment by anjesh** [comment]
Both the contracts have been published 
http://www.resourcecontracts.org/contract/ocds-591adf-0484705559
http://www.resourcecontracts.org/contract/ocds-591adf-3032468364

**Comment by charlesyoung** [comment]
Add a filter to exclude resource = hydrocarbon from the Guinea country site. Only mining contracts should be displayed.
