### ISSUE TITLE
Copy Guinea static content from staging to production

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1087]
Copy FAQ and other static content from staging to production.

cc @iprunache

**Comment by manishgs** [comment]
We've one database which is used for both production and staging country site therefore we don't need to copy content. However s3 bucket is different so I'v copied files from staging to production.

**Comment by iprunache** [comment]
@manishgs then can we merge the 1077 branch to master? Is there anything else left to do?

**Comment by manishgs** [comment]
@iprunache  yes. we can merge the branch. Did you setup DNS for production site?

@charlesyoung Are we ready to live Guinea site? So that I can merge and deploy to production.

**Comment by iprunache** [comment]
Yes, http://guinea.resourcecontracts.org/ is set up. Once we merge the branch to master the nginx config for the Guinea subsite will handle that domain name.

**Comment by charlesyoung** [comment]
Can we get the http://guinea.resourcecontracts.org site live?

**Comment by manishgs** [comment]
Guinea site is live.
