### ISSUE TITLE
Contract status: "failed" - not sure the cause - maybe because the pdf is unstructured?

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#109]
![image](https://cloud.githubusercontent.com/assets/12913915/8555688/a10c0bb8-24bf-11e5-957a-175dc0a70f5a.png)

**Comment by anjesh** [comment]
Agree - Failed is confusing. That was due to the incorrect credentials being used for OCR service. Such error shouldn't appear in future, just in case the log are maintained to look into details. Will see if those uncertain errors could be trapped and displayed accordingly. Closing this for now.
