### ISSUE TITLE
Renew SSL certificate for `*.resourcecontracts.org`

### ISSUE THREAD

**Issue by iprunache** [NRGI/resourcecontracts.org#1092]
## Why
The SSL certificate for `*.resourcecontracts.org` has expired and users receive a warning when accessing RC sites over HTTPS.

MTurk users are not able to complete their tasks on RC because of the certificate warning.

## What
- [x] generate a new AWS SSL certificate for `*.resourcecontracts.org`
   - [x] use DNS validation to validate the certificate
- [x] set up all load balancers serving resource contracts sites to use the new certificate
- [x] delete the expired SSL certificate
- [ ] set up an alert if possible to notify us when the certificate expires and renewal validation fails

## Notes
The certificate was configured for auto renewal but during renewal we need to validate the certificate by replying to an email that AWS sends to the AWS root email account and a series of web admin email addresses. We control none of those emails so we failed to see the notification of renewal.

AWS ACM provides a second option for certificate validation that we should explore: DNS validation, since we control the DNS record in Route 53.

**Comment by charlesyoung** [comment]
Many thanks @iprunache

**Comment by adinuca** [comment]
Only admin.resourcecontracts.org was configured to use the certificate. This is now using the new certificate.

**Comment by adinuca** [comment]
Sites done:
- api.resourcecontracts.org
- admin.resourcecontracts.org
- index.resourcecontracts.org


Sites not done because the CSS does not render correctly over HTTPS:
- https://tunisia.resourcecontracts.org/
- https://guinea.resourcecontracts.org/ 
- https://resourcecontracts.org/ 
Will raise another issue for the last 3.

**Comment by adinuca** [comment]
Raised #1093 for RC subsites.

**Comment by adinuca** [comment]
Hi @charlesyoung , this has been done for the sites that previously had SSL configured.  Can you please confirm if MTurk users can now perform their tasks?

**Comment by iprunache** [comment]
@adinuca according to this we may risk automatic renewal to fail if we don't get `resourcecontracts.org` to work over https: https://docs.aws.amazon.com/acm/latest/userguide/how-domain-validation-works.html#how-automatic-domain-validation-works

If I understand correctly, to check that the old certificate is in use, ACM will do a request to resourcecontracts.org and compare the returned certificate.

**Comment by adinuca** [comment]
@iprunache you are right. I will prioritise the issue that I raised for resourcecontracts.org and subsites for next week. Probably this is why the certificate was not renewed automatically.
