### ISSUE TITLE
Investigate RC annotation errors

### ISSUE THREAD

**Issue by adinuca** [NRGI/resourcecontracts.org#1097]
## Why
RC Admin is sending error emails when something goes wrong. In the 1st of March, there were 15 errors generated when hitting the annotations endpoint.

## What
- [ ] investigate why the errors occur

## Notes
Stacktrace sent by email : [https://app.zenhub.com/files/36373515/3d295f44-b13d-492b-a6fd-3b10f92e0270/download](https://app.zenhub.com/files/36373515/3d295f44-b13d-492b-a6fd-3b10f92e0270/download)

**Comment by adinuca** [comment]
The problem is that the **article_reference_en** is not provided in the form when trying to save an annotation.

Even if article_reference_en is provided, the exception might still occur if **article_reference_fr** and **article_reference_ar** are not provided.

**Comment by charlesyoung** [comment]
Thanks @adinuca 

We never had this problem before. Any idea what changed to introduce this error?

**Comment by adinuca** [comment]
It is not a new issue, I have checked the emails received in the past and my oldest email regarding this is from November and from what I can see from the code, the functionality was added on the 28th of March 2017. 
I am not familiar with how rc-admin works, but if you could provide me with an account I can check where the API calls are made from and why we don't have that field set.

Sorry we did not look at this sooner, we usually checked if there is an issue with Elasticsearch or AWS and we dismissed this as being a user error.

**Comment by charlesyoung** [comment]
Thanks. I will send you an email with the details.

**Comment by adinuca** [comment]
Received, thank you.

**Comment by adinuca** [comment]
It's interesting, I couldn't log in first time when I first tried and an error was generated.

**Comment by adinuca** [comment]
The requests are triggered when updating an annotations. They are triggered from the front end, Javascript and they all happened for the same user - Dechert. 
If any error occurred on the site when he updated the annotation, it might have triggered an incomplete request. I am unable to reproduce it for the moment.

**Comment by adinuca** [comment]
I will send an email to Chelsea.Fish@dechert.com, to find out what is the behaviour that causes the errors.

**Comment by charlesyoung** [comment]
Thanks @adinuca

**Comment by adinuca** [comment]
Hi @charlesyoung, I have sent the email and will update the issue as soon as I get an answer. 

Do you think YIPL team could take over the investigation? Our budget is quite low and also they have more knowledge on how the application works.

[Papertrail logs](https://github.com/NRGI/resourcecontracts.org/files/1776035/rc-admin-papertrail-logs.txt) and [error email](https://github.com/NRGI/resourcecontracts.org/files/1776033/rc_annotations.txt) attached.

**Comment by adinuca** [comment]
Here is Katharine's response:

> Adina,
>  
> Many thanks for your email. I was adding the annotations using Chelsea’s log in details. I did not receive any error messages but found that my edits to annotations were not going through. I’m not entirely sure why this was the case but it seems to be fine today.
>  
> Kind regards,
>  
> Katharine
>  
> Katharine Wheatcroft 
> Trainee Solicitor
> Dechert LLP
> 160 Queen Victoria Street
> London EC4V 4QQ
> +44 20 7184 7595 Direct
> +44 7835 489 030 Mobile
> +44 20 7184 7001 Fax
> katharine.wheatcroft@dechert.com
> dechert.com

**Comment by adinuca** [comment]
Hi @charlesyoung , can you please confirm if YIPL can take over the investigation? 
There has been one more error yesterday and one more today which seems to be from a different reason, but still related to annotations.

**Comment by adinuca** [comment]
As agreed with Charles, we will monitor this through March to see if there is a pattern for its occurrence.

**Comment by adinuca** [comment]
Error from 8th of March happened for user `Dechert`.

**Comment by SamCCSI** [comment]
Hi @adinuca Can you please delete the email and other contact information (including surnames) for Chelsea and Katharine that are noted in two of your messages above? I am mindful that this is a public site, and don't want to have their contact information published without their consent. Many thanks!

**Comment by adinuca** [comment]
Sorry, I didn't realise this. Removed.

**Comment by SamCCSI** [comment]
Thanks @adinuca for the prompt response! Much appreciated.

**Comment by adinuca** [comment]
It has happened 11 times on the 11th of March. User `Dechert`.

**Comment by adinuca** [comment]
The errors from the 16th of March were caused by the actions of the user `Sam Szoke-Burke`. There were 16 error emails.

**Comment by SamCCSI** [comment]
That's me. I can confirm that these occur when trying to edit the text of annotations or the size of the yellow annotation markers. 

Most times that I tried to edit text, the edit would not save and sometimes an error message would appear. I would have to reload the entire page and try again.

**Comment by SamCCSI** [comment]
Chrome

Mac OS X Yosemite v 10.10.5

On Mar 19, 2018, at 9:16 AM, Adina-Dumitrita Petrean <
notifications@github.com> wrote:

Hello @SamCCSI <https://github.com/samccsi>,

Can you tell us what browser you are using and on what operating system?
This might help us narrow down the problem.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/NRGI/resourcecontracts.org/issues/1097#issuecomment-374207713>,
or mute the thread

**Comment by adinuca** [comment]
Thank you!

**Comment by adinuca** [comment]
This has been raised again as part of #1106. 

Closing this as duplicate.

**Comment by charlesyoung** [comment]
@adinuca received over 100 error emails today. Can you please try investigate if you have time? Is this the same as #1106?

**Comment by adinuca** [comment]
Hi @charlesyoung . I only received one email today from `nrgi@yipl.com.np` and this is related to the issue described in #1106. 

Could you please forward one of the emails you received to make sure it is the same thing?
