### ISSUE TITLE
Fix the code to enable separate RC and OLC sites for a given country.

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#1099]
## What

- [ ] update code to enable the possibility of RC and OLC for the given country
- [ ] fix the code to reflect this change for the existing subsites tunisia.resourcecontracts.org, drc.openlandcontracts.org, guinea.resourcecontracts.org, tanzania.openlandcontracts.org and tanzania.resourcecontracts.org

## Why

Current code structure doesn't allow two subsites (RC and OLC) for a given country. Somehow this issue was not issue until there's a need of RC and OLC for Tanzania. Because of this issue, we see the same tagline for both RC or OLC site for Tanzania. There's no way to fix this unless we fix the code. However based on discussion here https://github.com/NRGI/resourcecontracts.org/issues/1078#issuecomment-378151823, we will be needing the feature to have RC and OLC site for a given country.

**Comment by charlesyoung** [comment]
@anjesh as discussed, below are the details of the Tanzania staging country site. 

URL: https://staging.tanzania.resourcecontracts.org/
User name: admin@nrgi.com
Password: password

**Comment by man-git007** [comment]
@charlesyoung This has been deployed to staging server. Could you please verify it.

cc @anjesh

**Comment by anjesh** [comment]
@charlesyoung @adinuca could we also have the protected staging for http://staging.tanzania.openlandcontracts.org/ to test this change?

**Comment by adinuca** [comment]
Hi @anjesh, what do you mean by protected?

**Comment by anjesh** [comment]
i meant password protected like https://staging.tanzania.resourcecontracts.org/

**Comment by charlesyoung** [comment]
Yep we will need a OLC Tz site to test that its working.

**Comment by adinuca** [comment]
Hi @anjesh , I've set up the domain name. To make the site protected, you just need to change the init.sh file to use the nginx_subsite_protected.template
```
#country-tanzania-olc
export SERVER_NAME="tanzania.openlandcontracts.org *.tanzania.openlandcontracts.org"
export TRACKING_ID=${TZ_TRACKING_ID}
export GTM_ID=${TZ_GTM_ID}
export DB_DATABASE=${COUNTRY_DB_DATABASE}
export CONTACT_MAIL=${TZ_CONTACT_MAIL}
export COUNTRY=tz

export CATEGORY=country-tz-olc
```
`envsubst '$SERVER_NAME $CATEGORY'< `**./nginx_subsite_protected.template**` > /etc/nginx/sites-enabled/country-tz-olc
`

Let me know if you need help with this.

**Comment by rawalrajen** [comment]
Ths issues has been resolved. For further discussion I have opened new ticket on #1170

**Comment by anjesh** [comment]
@charlesyoung 

Working now

http://staging.tanzania.openlandcontracts.org/
https://staging.tanzania.resourcecontracts.org/

Use the following to access

User name: admin@nrgi.com
Password: password

This is good to deploy to production @rawalrajen

**Comment by anjesh** [comment]
Sure, the sites won't be live, but the codebase may be pushed to master-branch (production). Later once the production sites are enabled, this change will take into effect.
