### ISSUE TITLE
Document metadata at upload stage	

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#11]
Webform (with typing and validation) to supply metadata on new document creation. If metadata is limited, webform should be on upload. If metadata is more detailed, should be after but before annottion and should allow for side by side comparison of webform and document.

**Comment by anjesh** [comment]
Right now we will have all the metadata during the contract creation. Lets see the process and then we can decide on the fields we want to capture during creation and others after the creation (more like add more info or as a part of the edit contract). Or if you could identify those basic fields, we can start working on this as well.

**Comment by anjesh** [comment]
Include option/link to select "today" rather than selecting date hear "Date of retrieval"

**Comment by anderspeders** [comment]
Basic metadata form complete. Reiteration of metadata at end of sprint 2.
