### ISSUE TITLE
Investigate Curl error

### ISSUE THREAD

**Issue by adinuca** [NRGI/resourcecontracts.org#1100]
## Why
There have been a few emails and a few Papertrail alerts regarding "Curl error"
 coming from rc-admin

## What
- [ ] cause for  "Curl error" is found
- [ ] issues to fix the "Curl error" are raised

**Comment by charlesyoung** [comment]
@adinuca just checking if this issue has been resolved.

**Comment by adinuca** [comment]
I haven't seen it recently but I don't think it has been fixed.

**Comment by charlesyoung** [comment]
@adinuca can you please take a look so that we can either address the issue or close the case. Thanks

**Comment by adinuca** [comment]
The error last occurred in Production on the 3rd of July and there hasn't been a fix for it.

We can close it for now and investigate if it occurs again.
