### ISSUE TITLE
Fixing errors introduced to OLC TZ staging site 

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#1102]
When OLC TZ staging site was accidentally changed to an RC staging site (see #1078), the name of the site was changed (to "A directory of Resource Contracts from Tanzania, United Republic of") and other aspects of the site were changed. 

Is it possible for the staging site to revert in full to how it was prior to the mix up? If not, these issues should be fixed. Issues include: 
- name should be "An online repository of OpenLandContracts from Tanzania"
- the logo should include the country name "United Republic of Tanzania" (rather than "Tanzania, United Republic of" - screenshot below

![image](https://user-images.githubusercontent.com/14910764/40249844-45f7c3f4-5aa2-11e8-9b07-3bc75bab2a5d.png)

- resources should be OLC resources 
- The FAQ page should be the same as the OLC FAQ page 
- A french version was also available when we had set up the site - the name of the site used was "Un répertoire de contrats agricoles et forestiers de la Tanzanie" 

Many thanks in advance.

**Comment by charlesyoung** [comment]
@JesseCCSI can this ticket be closed?

**Comment by JesseCCSI** [comment]
Many thanks @charlesyoung yes, I'll close (we'll retain the staging site in the event that future work on this emerges).
