### ISSUE TITLE
Add "minerals" filter option - beyond the current selection

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#1105]
## Why

As a user I would like to not have to browse the full list of minerals but simply be able to filter all minerals contracts. 

## What

This would potentially require an additional category.

**Comment by charlesyoung** [comment]
@anjesh will below be possible to implement? 

Changes to the resources search box: Can we have a search for “minerals” generally? Right now you would have to select each and every mineral from quite a long list. While it’s obviously useful to be able to search and compare for specific minerals, often for search we  just want to see terms across minerals contracts or hydrocarbons contracts. So I actually think leading the list with “hydrocarbons” then “minerals” following by a break line and then the alphabetical list that allows for searching for specific minerals only, would be helpful. The idea would be that clicking minerals in the top half of the search list would automatically highlight all the specified minerals below. A user could then deselect some if they chose.

**Comment by charlesyoung** [comment]
@anjesh just checking if you can give me a yes this is possible or not for now.

**Comment by man-git007** [comment]
@charlesyoung Could you please provide us the resources that fall under the mineral category.

**Comment by charlesyoung** [comment]
Thanks. Please note that this obviously only applies to RC and not OLC. Do we have separate resource lists for RC and OLC to allow for the separation? 

So its basically all minerals in 1 group and then hydrocarbons in another group. I did however noticed that there are also gas contracts so I need to find out if that will be a separate group or included in the hydrocarbons group. 

What will be the process when new minerals are added?

**Comment by man-git007** [comment]
@charlesyoung The resource list is the same for both RC and OLC. We can show the categorized resources in RC and not in OLC. As for the resource list, I have attached the excel file. For the addition of new resources, we need to update it in the codebase itself.

[Resource List.xlsx](https://github.com/NRGI/resourcecontracts.org/files/4756942/Resource.List.xlsx)

**Comment by charlesyoung** [comment]
Thanks. Do I need to add a column to the xls noting if relevant or not and if then the grouping?

**Comment by man-git007** [comment]
@charlesyoung Yes, could you please categorize these resources.

**Comment by charlesyoung** [comment]
OK. Just so that we agree is the following envisaged. 

The resource list will lead with “Hydrocarbons” and  “Minerals”. This will be followed by a break line that will then list all the resources in alphabetical order.

**Comment by charlesyoung** [comment]
@man-git007 please see list attached. 

Couple of points. 
- Can you please run a query and check that all the currently recorded resources in RC are noted in the xls. I noticed that 'Methane' and 'Other Minerals' were missing but we need to confirm that there aren't more.
- Both OLC and RC uses 'Not Specified'. What do we do in this case? 

[Resource grouping list.xlsx](https://github.com/NRGI/resourcecontracts.org/files/4770455/Resource.grouping.list.xlsx)

**Comment by man-git007** [comment]
@charlesyoung I have crossed checked with the database. There are no other missing resources for RC besides Methane and Other Minerals.
As for the `Not Specified` I Suggest it be listed as separate in the resource list option at last.

Do we need to cross-check for OLC as well?

**Comment by charlesyoung** [comment]
Thanks @man-git007 

I don't follow, what do you mean by listing Not Specified as separate in the resource list? 

Yes please cross-check OLC because there seemed many missing resources from the list.

**Comment by man-git007** [comment]
@charlesyoung I meant not grouped in the list like mineral.

**Comment by charlesyoung** [comment]
No it needs to be included in the minerals list. 

Can we not run a query where if Resource = Not Specified and Category = ResourceContracts then add to the minerals group?

**Comment by man-git007** [comment]
@charlesyoung Is the excel sheet you have provided is final?

**Comment by charlesyoung** [comment]
Yes thanks, NA and blank means leave out. 

Their is only 1 related hydrocarbon category. 

The list is basically final so you can start working on the ticket. 

Below is what we envisage. 

![image](https://user-images.githubusercontent.com/13888372/85110987-00c19c80-b214-11ea-962b-16c5e69449ea.png)

**Comment by man-git007** [comment]
@charlesyoung The changes are been implemented in the staging site. Could you please verify?

**Comment by charlesyoung** [comment]
Thanks. Three things please. 

- Can you please check your query, there are 1654 docs. Hydrocarbons group = 941 and the minerals group = 557 which totals 1498 (156 short). 
- Why when I deselect a resource like Barite does the cursor move to the end of the list? 
- Can you double the length of the line break.

**Comment by birendragurung** [comment]
@charlesyoung by line break, do you mean line breaks between selected list or drop-down list?

**Comment by charlesyoung** [comment]
I'm referring to below. Take a look at above image to see what is envisaged. 

![image](https://user-images.githubusercontent.com/13888372/87126577-b8ceec00-c28c-11ea-8e34-e4f4e6a9f3ff.png)

**Comment by birendragurung** [comment]
> * Why when I deselect a resource like Barite does the cursor move to the end of the list?

The default behavior is to let user type something to search resources and select from drop-down list.

**Comment by birendragurung** [comment]
@charlesyoung We checked on the resource data and there are some resources other than in - Hydrocarbons and Minerals categories as well as Methane and 'Other minerals'. So the remaining contract count is from non-categorized resources.

Also, the gap in the dropdown is added. Please verify and let us know about improvements.

**Comment by charlesyoung** [comment]
OK thanks. The gap was fine, please set to what it was, its the line (shown in red above) that needs to be made longer. Like below. 

![image](https://user-images.githubusercontent.com/13888372/87653255-8ffb9a80-c755-11ea-989a-96a3ea87ae11.png)

**Comment by birendragurung** [comment]
@charlesyoung The changes have been sent to staging server. Please check and verify.

cc: @man-git007

**Comment by charlesyoung** [comment]
@birendragurung please deploy to the Prod site. Thanks

**Comment by birendragurung** [comment]
@charlesyoung This has been deployed to production.

cc: @man-git007

**Comment by charlesyoung** [comment]
Thanks. Please check why when selecting the Minerals group the display isn't the same as its shown on the Staging site. 

Prod
![image](https://user-images.githubusercontent.com/13888372/88037984-e72eb000-cb45-11ea-8ac9-aff41e48d0c2.png)

Staging
![image](https://user-images.githubusercontent.com/13888372/88037936-d4b47680-cb45-11ea-8bb2-99ff18694e78.png)

**Comment by birendragurung** [comment]
@charlesyoung This has been fixed.

**Comment by birendragurung** [comment]
@charlesyoung This has been fixed and this issue can be closed if everything's ok.

![Screenshot from 2020-07-21 17-41-58](https://user-images.githubusercontent.com/13505748/88052141-828d4880-cb79-11ea-9a18-abcd28c57fcf.png)
