### ISSUE TITLE
Annotations not always saving; listing wrong categories

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#1106]
## Why
Bug reporting

## What
Our pro bono annotators have been entering annotations but (i) some annotations don't save, so they lose their work and (ii) for those that DO save, initially, in the back-end they are listed in the left column but the heading is for a different annotation category.
@anjesh is there anything you can do to help?

## Notes
Here is the contract that was being annotated: http://admin.resourcecontracts.org/contract/2834/annotate

Computer: Dell Optiplex 3020;
Operating system: Windows 10 64-bits;
Browsers: Internet Explorer 11.2311.14393.0 (Update version 11.0.70) and Google Chrome Version 67.0.3396.87

Example of categories wrongly displaying. E.g. first category should be "Name of company", not "language"
![image](https://user-images.githubusercontent.com/12913915/41626002-d66dc6b8-73e8-11e8-96ef-3eb769b47b7c.png)

**Comment by adinuca** [comment]
Hi @anjesh , there have been a few emails today, regarding errors when saving notifications.  Have you had a chance to look at this issue yet? Maybe the stacktrace from the emails will be helpful.

**Comment by SamCCSI** [comment]
I am also noticing that some (older) annotated contract don't let me edit existing annotations in the annotation view at all. I make a change to the annotation, save it, it notifies me that the annotation is saved but the changes don't register, even when i refresh the page.

So instead i have to go to the metadata page, scroll down to the annotations and edit them there, which is more laborious.

This contract is one example: http://admin.resourcecontracts.org/contract/2432

@anjesh @jedm @KaitlinCCSI

**Comment by man-git007** [comment]
This issue is the same as #1055. So it is now being closed
