### ISSUE TITLE
OLC Search by annotation category bug

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#1107]
## What
When I search for contracts with the "Community consultation" annotation category, I get zero results.
![screenshot 2018-07-10 11 05 12](https://user-images.githubusercontent.com/12913915/42519049-29263efa-8431-11e8-9a15-005f331fbe24.png)

But there *are* contracts with these annotation category. E.g. http://www.openlandcontracts.org/contract/ocds-591adf-8366243767/view#/pdf/page/17/annotation/1362
![screenshot 2018-07-10 11 06 23](https://user-images.githubusercontent.com/12913915/42519119-4f6342c0-8431-11e8-9dbb-3ebda46567d6.png)

This means the search by annotation category function is not working properly.

@anjesh could you please investigate what might be causing this bug?

cc @jedm @KaitlinCCSI

**Comment by jedm** [comment]
Hi @SamCCSI and everyone. Sam, is there any chance that this is one of the contracts or annotations that has been changed since the other annotation problems (#1097 and  #1106) were occurring? Or more likely fully unrelated?

**Comment by SamCCSI** [comment]
@jedm It is a different contract from the other ones I had issues with in #1097 and #1106, but the problem is the same. So they are related insofar as they are examples of the same bugs in the annotation function

**Comment by man-git007** [comment]
@jedm @SamCCSI The annotation category search issue has been resolved and has been deployed in the staging server. Could you all please verify.

cc @bizaybsnt

**Comment by SamCCSI** [comment]
Thanks @man-git007 the "community consultation" category now is producing search results in the staging site. So I guess it can be deployed to live site?

**Comment by man-git007** [comment]
@SamCCSI @jedm It has been deployed to live server This issue is now closed

cc @anjesh @bizaybsnt
