### ISSUE TITLE
License identifier 

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1108]
Allow for the representation of license identifiers with a backslash, dash, slash, etc (examples: SML 44/99 and 20584-HQ-LML) to allow for future linkages to the relevant cadastre public map portals.

**Comment by anjesh** [comment]
I tried in staging and this seems to be working. Am i missing something here? @charlesyoung 

https://staging.resourcecontracts.org/contract/ocds-591adf-1806714229

![image](https://user-images.githubusercontent.com/120488/48051846-5a578d80-e1ce-11e8-8e8d-85aeae4f5553.png)

**Comment by charlesyoung** [comment]
@anjesh the issue isn't related to capturing license identifiers with a backslash, dash, etc in the admin tool but rather the use of license identifiers with a slash, etc through the API.

**Comment by anjesh** [comment]
Is it problem visible somewhere? Please give some examples of where you have seen in this problem 
 - API or the map-app you were showing last time?

**Comment by charlesyoung** [comment]
@anjesh this was our last email correspondence. I will create a staging mapping site for testing. 

'We are using Elasticsearch in the backend for the API. It looks like / in the text "SML 44/99" seems to be the issue here. Thanks for noticing. This would require changes in the codebase and probably proper testing if this is going to work or not as per https://stackoverflow.com/questions/31963643/escaping-forward-slashes-in-elasticsearch'.

**Comment by charlesyoung** [comment]
@anjesh hold this ticket for now because it seems to work. 

Go to http://portals.flexicadastre.com/MalawiStaging
Click continue 
Search for SML 44/99 (top right)
Click on the search results link
You will see a popup box with license details and a RC link
Click on the link 
There will be a hyperlink displayed on the right, click on the link
The doc will open in RC

**Comment by charlesyoung** [comment]
Completed
