### ISSUE TITLE
Renewable energy contracts

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1109]
For discussion, inclusion of renewable energy contracts.

**Comment by SamCCSI** [comment]
This is a question the OLC team has been reflecting on, as well. We would therefore love to be kept in the loop on this.

OLC already has 3 biofuels contracts http://www.openlandcontracts.org/resource/Biofuels and 2 Buchanan renewables contracts http://www.openlandcontracts.org/search?q=buchanan
