### ISSUE TITLE
Metadata: Bundling of related contracts

### ISSUE THREAD

**Issue by byndcivilization** [NRGI/resourcecontracts.org#111]
As a user it would be useful to see bundles of documents relating to a specific well or mine or concession block. Tags maybe?

**Comment by anderspeders** [comment]
Yes, to elaborate on that: 

As a user I need to see when contract <documentA> relates to the translated version <documentB> and the environmental protection agreement <documentC>. 

There will almost always be a main contract while thre might often be supporting documents to that main document. 

Suggested steps: As part of the "contract page" create a box for supporting contracts. 

*Example 1: The main contract and the translation of the contract*

*Example 2: A master contract and supporting contracts*
One agreement for a concession area will often involve multiple contracts. See for example this list below all relating to the same contract area.  

Kenya Block-11A dd0000 Assignment	Assignment	ERHC Energy Kenya Limited, CEPSA Kenya Limited		No	English		download
Kenya Block-11A dd0000 PSC	PSC	Government of the Republic of Kenya, ERHC AGC Profond Ltd		Yes	English		download
Kenya Block-11A dd0000 Participation-Agree	Participation-Agree	Government of the Republic of Kenya, ERHC AGC Profond Ltd		Yes	English		download
Kenya Block-11A dd20131007 Farmout-Agreement	Farmout-Agreement	ERHC Energy Kenya Ltd, CEPSA Kenya Ltd	October 7, 2013	yes	English		download
Kenya Block-11A dd20131007 Operating-Agree	Operating-Agree	ERHC Energy Kenya Limited, CEPSA Kenya Limited	October 7, 2013	No	English		download
Kenya Block-11A dd20131007 Transitional-Agree	Transitional-Agree	ERHC Energy Kenya Limited, CEPSA Kenya Limited	October 7, 2013	No	English		download

**Comment by anjesh** [comment]
For the translated contract, currently we have open text field. 
![image](https://cloud.githubusercontent.com/assets/120488/9193756/84e70c94-4035-11e5-9b2b-360a0ba52301.png)
So the "translation parent" should be "Translated from" with the drop of the all the contracts we have in the system and the user chooses one from the list. Or is it that there will be an file upload field where the user will upload the contract? Please confirm. 

As for the supporting documents, there needs to be "add multiple supporting document" section with title of the file and file. Or is it that we upload all these supporting documents in the system and link to these supporting documents from the contract.

**Comment by byndcivilization** [comment]
This looks good. Only corner case I can think of is where we have translation but not the parent. @anderspeders can you think of any examples like this?

**Comment by anjesh** [comment]
Just to confirm the understanding, we will have all the supporting contracts in the system and the researcher chooses the related supporting contracts as shown below

**Option 1**

--
![image](https://cloud.githubusercontent.com/assets/120488/9216389/3fbadeb8-40d8-11e5-8d46-fa2159637eda.png)
--

**Option 2**

Or is it that these supporting documents are to be uploaded for each contract as shown below. Please confirm.

--
![image](https://cloud.githubusercontent.com/assets/120488/9216427/c97891a4-40d8-11e5-9a46-6bf6387a7744.png)
--

**Comment by anjesh** [comment]
The associated contracts could be now added to the contracts 
![image](https://cloud.githubusercontent.com/assets/120488/9486737/ca3354ea-4bea-11e5-9a1c-39a7a99f8d40.png)

and they are displayed in the subsite. 
![image](https://cloud.githubusercontent.com/assets/120488/9486733/bc8c3226-4bea-11e5-8cd5-d23806e4dcfc.png)

Now there need some change in the wording and need to add Parent contract, will be taken care in #192
