### ISSUE TITLE
Propose a solution for Elasticsearch from RC staging scaling up

### ISSUE THREAD

**Issue by adinuca** [NRGI/resourcecontracts.org#1111]
## Why
The Elasticsearch deployment used by RC staging keeps scaling up which involved an increase in costs.

## What
- [x] investigation is done on the increase of memory usage which cause the deployment to scale up
- [x] findings are communicated to Anders, Frank and the RC team

## Notes
The deployment has been scaled down in April from 10GB and 1GB memory to 5GB disk space and 510MB memory. Since then, it was scaled up twice due to lack of memory .

**Comment by charlesyoung** [comment]
@adinuca can you please keep me in the loop on your findings. How much time will you need to run your investigation?

**Comment by adinuca** [comment]
Hi @charlesyoung , all my findings will be added on this issue. I will try to tackle it tomorrow. I have added a 5h estimate on this.

**Comment by adinuca** [comment]
Findings on the issue: 
- we are using an Elasticsearch version that has reached end of life on the 28th of February, 2018([Elasticsearch documentation](https://www.elastic.co/support/eol)), we should upgrade to a newer version
- normal usage of memory is close to the limit or a bit above the limit. Whenever the application is used intensively, hitting Elasticsearch, the amount of memory used increases, causing an out of memory and causing the Elasticsearch deployment to scale up.

**Comment by charlesyoung** [comment]
Thanks @adinuca. 

What is involved upgrading to the new version? 

Will the new version handle memory usage better?

**Comment by adinuca** [comment]
My advice for now would be to scale the staging deployment up to 10GB of disk space and 1GB of RAM to avoid downtime for RC staging.

On the long term, my advice is to update index.resourceontracts.org and api.resourcecontracts.org to use a newer version of Elasticsearch, this will involve code changes, migrating Elasticsearch to a newer version and also lots of testing. The transition will have to be done step by step, going through the intermediary versions.

The upgrade of Elasticsearch will also enable us to migrate the data from Compose.io to a better provider, like Elasticsearch Cloud or AWS, which offer more resources for less money:
- Current Compose.io deployment for staging offers 5GB space and 510 MB RAM for $99
- Elasticsearch Cloud deployment suitable for staging would offer 24GB disk space and  1GB RAM  for $45

**Comment by adinuca** [comment]
Sent email to the team.
