### ISSUE TITLE
Contract Import CSV / Excel file

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1114]
Extend the contract import CSV / Excel file to include additional data like if its a main or supporting document, document URL, etc.

**Comment by anjesh** [comment]
could you please list all the additional data that you would like to include in the template?

**Comment by anjesh** [comment]
@charlesyoung Can you list the fields you want to be included in the template? [Current CSV Template](https://github.com/NRGI/resourcecontracts.org/files/2656390/rc-template-sample.xlsx) includes the following field. Ideally if you could upload an updated template with the field-names, that would be great. 



Fields
--
Category
Contract Name
Contract Identifier
Language
Country Code
Resource
Contract Type
Signature Date
Document Type
Government Entity
Government Identifier
Company Name
Jurisdiction of Incorporation
Registration Agency
Company Number
Company Address
Participation Share
Corporate Grouping
Open Corporate Link
Incorporation Date
Operator
Project Title
Project Identifier
License Name
License Identifier
Source Url
Disclosure Mode
Retrieval Date
Pdf Url

**Comment by charlesyoung** [comment]
@anjesh please take a look at below updated template link. 

https://docs.google.com/spreadsheets/d/1QYgVzAqxyqZX8WCIcSp48iPoh2oRK6vA1jDK3ude_20/edit#gid=526935487

Questions / Comments:
1. Yellow columns are to be added
2. Can we use dropdown lists? 
3. Include required fields (marked in red)
4. Auto generate the contract name
5. Contract identifier?
6. Use commas rather than double pipes for multi values
7. Date columns to be formatted as date fields
8. Is the Signature Year pulled from the Signature Date?

**Comment by charlesyoung** [comment]
Call notes: 

1. Change the template from CSV to XLS
2. Run validations, before the import, to confirm that all the required fields have been populated. Also apply validations to drop down lists like Language, Country Code, Resource, Contract Type and Document Type. 
3. Format date fields 






cc @anjesh

**Comment by anjesh** [comment]
@man-git007 lets look into the possibility of using excel instead of csv as that would give us flexibility to add validation in excel as well.

**Comment by charlesyoung** [comment]
@anjesh what is the status of this ticket?

**Comment by man-git007** [comment]
@charlesyoung I have posted a table for the excel import regarding validation and formatting fields.
Could please got through it ? 

Columns | Include | New | Remarks
-- | -- | -- | --
Category | yes |   | rc or olc and validation should be done upon import and if any other values besides these list import is aborted
Main / Associated | yes | yes | 1 or 0
Main Document OCID (if already published) | yes | yes | main document OCID and validate if exists
Document URL | yes or no | yes | Is this column same as Pdf Url column?
Contract Name | yes |   | This field is required so auto generate contract name doesn’t seem to make sense
Language | yes |   | ar or en or fr and validation should be done upon import and if any other values besides these list import is aborted
Country Code | yes |   | all the country codes and validation should be done upon import and if any other values besides these list import is aborted
Resource | yes |   | multi value and for separation we used pipeline but now changes to two semicolons ;;
Contract Type | yes |   | all contract types
Signature Date | yes | yes | date filed in yyyy-mm-dd format
Signature Year | yes or no | yes | can be fetched from Signature Date so there will be no need of this field
Contract Signed? | yes |   | 1 or 0
Document Type | yes |   | all document type list
Government Entity | yes |   | government entity list
Government Identifier | yes |   |  
Company Name | yes |   | multi value and for separation we used pipeline but now changes to two semicolons ;;
Jurisdiction of Incorporation | yes |   | multi value and for separation we used pipeline but now changes to two semicolons ;;
Registration Agency | yes |   |  
Company Number | yes |   | multi value and for separation we used pipeline but now changes to two semicolons ;;
Company Address | yes |   |  
Participation Share | yes |   | multi value and for separation we used pipeline but now changes to two semicolons ;;
Corporate Grouping | yes |   | multi value and for separation we used pipeline but now changes to two semicolons ;;
Open Corporate Link | yes |   |  
Incorporation Date | yes |   | multi value and for separation we used pipeline but now changes to two semicolons ;; and in the format of yyyy-mm-dd
Operator | yes |   | multi value and for separation we used pipeline but now changes to two semicolons ;;
Project Title | yes |   |  
Project Identifier | yes |   |  
License Name | yes |   |  
License Identifier | yes |   |  
Source Url | yes |   |  
Disclosure Mode | yes |   |  
Retrieval Date (yyyy-mm-dd) | yes |   |  
Pdf Url | yes or no |   | Should Document Url replace this column?

Columns | Include | New | Remarks
-- | -- | -- | --
Category | yes |   | Values can be rc or olc and validation should be done upon import and if any other values besides these list import is aborted?
Main / Associated | yes | yes | Values can be 1 or 0
Main Document OCID (if already published) | yes | yes | If Main / Associated has 1 then validates the main document OCID?
Document URL | yes or no | yes | Is this column same as Pdf Url column?
Contract Name | yes |   | This field is required so auto generate contract name doesn’t seem to make sense
Language | yes |   | Values can be ar or en or fr and validation should be done upon import and if any other values besides these list import is aborted
Country Code | yes |   | all the country codes and validation should be done upon import and if any other values besides these list import is aborted
Resource | yes |   | multi value and for separation we used pipeline but now changes to two semicolons ;;
Contract Type | yes |   | all contract types
Signature Date | yes | yes | date filed in yyyy-mm-dd format
Signature Year | yes or no | yes | can be fetched from Signature Date so there will be no need of this field
Contract Signed? | yes |   | Values can be 1 or 0
Document Type | yes |   | all document type list
Government Entity | yes |   | government entity list
Government Identifier | yes |   | no changes
Company Name | yes |   | multi value and for separation we used pipeline but now changes to two semicolons ;;
Jurisdiction of Incorporation | yes |   | multi value and for separation we used pipeline but now changes to two semicolons ;;
Registration Agency | yes |   | no changes
Company Number | yes |   | multi value and for separation we used pipeline but now changes to two semicolons ;;
Company Address | yes |   | multi value and for separation we used pipeline but now changes to two semicolons ;;
Participation Share | yes |   | multi value and for separation we used pipeline but now changes to two semicolons ;;
Corporate Grouping | yes |   | multi value and for separation we used pipeline but now changes to two semicolons ;;
Open Corporate Link | yes |   | no changes
Incorporation Date | yes |   | multi value and for separation we used pipeline but now changes to two semicolons ;; and in the format of yyyy-mm-dd
Operator | yes |   | multi value and for separation we used pipeline but now changes to two semicolons ;;
Project Title | yes |   | no changes
Project Identifier | yes |   | no changes
License Name | yes |   | no changes
License Identifier | yes |   | no changes
Source Url | yes |   | no changes
Disclosure Mode | yes |   | no changes
Retrieval Date (yyyy-mm-dd) | yes |   | no changes
Pdf Url | yes or no |   | Should Document Url replace this column?

**Comment by anjesh** [comment]
Excel based import with changes in template has been setup as per @man-git007 

The following fields are yet to be handled and i am suggesting the followings for those fields

* "Contract Name" could be left blank (it is mandatory in the suggested template), in that case it will be auto-generated, otherwise it uses the name mentioned in the excel. 
* "Signature year" to be removed as it will be generated from the signature date.
* "Pdf Url" to be removed as it is same as "Document url"
* "Government Entity" is free text field and shouldn't be checked against the list as we mightn't have comprehensive list of the entities. 

Please confirm @charlesyoung

**Comment by charlesyoung** [comment]
Thanks @anjesh and @man-git007. Couple points. 

1. Although I asked to replace ||  I think we should keep it as the separation method
2. Will the contract and doc types be listed in the xls? 
3. Why not have a check against Government Entity to avoid incorrect spellings? 
4. Will the date field be a date formatted field?
5. Agree with your points on the contract name, auto-generate if blank otherwise use the name captured

We will use the Colombia docs as a test import. Fields like Document Name, Noted Contract Type, Company 1, Company 2, Company 3 and Company 4 will be removed before the final import. We are busy capturing missing info. 

https://docs.google.com/spreadsheets/d/1GR2lbqqtHjAaBVB2y0nbb6mU30OEXL9bbfEIXkyYI9A/edit#gid=674180829

**Comment by man-git007** [comment]
@charlesyoung we have completed the Contract Import CSV / Excel file and have deployed to staging server. The file should be in .xls format. 

Could you please verify the changes?

The changes are:

1. Add new fields   
    Main / Associated
    Main Document OCID (if already published)
    Document URL
    Signature Date
    Contract Signed?    
    
2. Remove fields    
    Signature Year
    Pdf Url
    
3. Validate fields  
    Category
    Main Document OCID (if already published)
    Language
    Country Code
    Resource
    Contract Type
    Document Type
    Government Entity
    Jurisdiction of Incorporation
    Signature Date (yyyy-mm-dd)
    Retrieval Date (yyyy-mm-dd)
    
4. Required fields  
    Category
    Document URL
    Contract Name if not present auto generate
    Language
    Country Code
    Resource
    Signature Date
    Document Type
    Government Entity
    Company Name

**Comment by rawalrajen** [comment]
@charlesyoung and @anjesh  This ticket has still some issue, We are working on it.

**Comment by rawalrajen** [comment]
@charlesyoung and @anjesh the issues have been resolved and I tested it on staging. Please verify the changes 
![screenshot_2019-01-03 admin - resource contracts 1](https://user-images.githubusercontent.com/34540506/50624546-8468ca00-0f49-11e9-98e7-5792f68530b6.png)

**Comment by charlesyoung** [comment]
Thanks @rawalrajen 

I will be running test imports this week but have the following questions and input for now. 

1. Rename the xls from 'sample' to 'Backend import template'
2. Make the field names in the xls bold to distinguish it from the general text
3. Do we need the Contract Identifier field in the template? 
4. Do we need the Government Identifier field in the template? 
5. Change the Document Url field to Document URL
6. Move the Document Url field to after Main Document OCID (if already published)
7. To clarify, 0 = no and 1 = yes
8. Required fields need to be highlighted in red
9. Will adding a new tab to the xls, for notes, impact the import process? 

cc @anjesh

**Comment by charlesyoung** [comment]
Some more points based on attached xls (I added some erroneous data on purpose to check the validations). 

1. Government entity is invalid; Agencia Nacional de Hidrocarburos is captured but notes as invalid
2. Jurisdiction of Incorporation is invalid; this isn't a required field so should pass if left blank 
3. Invalid Type of Contract; this isn't a required field so should pass if left blank 
4. Document Type is required; Company-State Contract is specified which is a correct doc type
5. It didn't pick up that the last entry is missing the Document URL
6. Standardize the remarks, for instance there are remarks noting 'Invalid Contract Type' and 'Document Type is invalid'. Please change all remarks to xxx is invalid.   
7. Does it import any data if it picks up an issue with the xls? Best will be to only allow for the full import once all the issues have been fixed. 
8. Its also trying to upload 17 docs when there is only 5, see below. 

![image](https://user-images.githubusercontent.com/13888372/50821263-734bfe80-1337-11e9-88f2-a8002580c2d3.png)



[test backend import.xlsx](https://github.com/NRGI/resourcecontracts.org/files/2736193/test.backend.import.xlsx)

**Comment by charlesyoung** [comment]
@rawalrajen has there been any progress on this ticket? 

cc @anjesh

**Comment by rawalrajen** [comment]
@charlesyoung We are working on this ticket.

**Comment by anjesh** [comment]
@rawalrajen please find the confusing points

- Do we need the Contract Identifier field in the template?
lets remove this
- Do we need the Government Identifier field in the template?
lets remove this
- Will adding a new tab to the xls, for notes, impact the import process?
This should not be a problem. Please send us the notes to be included in the new sheet.
- Do we need the Source Url field?
Lets remove this. This is replaced by Document URL now
- Government entity is invalid; Agencia Nacional de Hidrocarburos is captured but notes as invalid
We don't need to check validity of "Government entity"

**Comment by charlesyoung** [comment]
@anjesh please don't remove noted fields as they could all be used. We just need to make sure that validations are run with the only fields that should be removed being Source Url (replaced by Document URL) as well as contract identifier and government Identifier (not sure how this can be filled in before the import). 

@rawalrajen 



.

**Comment by rawalrajen** [comment]
@charlesyoung 
I have updated the following changes.

- Updated readme section with noted texts.
- Main / Associated field noted in red
-  Government Identifier and contract identifier fields  removed from excel.
- Signature date and Retrieval date invalid issue fixed

I have tested it against the [backend_import_template.xlsx](https://github.com/NRGI/resourcecontracts.org/files/2767642/backend_import_template.xlsx) excel file.

I will notify about other changes in next update.
cc @anjesh

**Comment by charlesyoung** [comment]
Thanks @rawalrajen. Please let me know when I can run more tests.

**Comment by charlesyoung** [comment]
Thanks @rawalrajen, looking really good. Minor comments below. 

1. The readme section is blank
2. The Main / Associated field still needs to be noted in red and be required 
3. Just checking that the import will handle doc and contract types in the other supported languages (French and Arabia)? 
4. Do we check that the Participation Share totals 100% or doesn't exceed 100%? I captured  0.8||0.5 and it didn't pick up the problem. 
5. I tested the Associated Document import with OCID link and it worked well

I will do some more testing in the morning. 

cc @anjesh @anderspeders

**Comment by rawalrajen** [comment]
@charlesyoung 
Please check the template format from http://admin-staging.resourcecontracts.org/contract/import. I have uploaded the above template for testing purpose only.

**Comment by charlesyoung** [comment]
OK. Last question; will the import handle doc and contract types in the other supported languages (French and Arabia)?

**Comment by rawalrajen** [comment]
@charlesyoung Currently excel upload only supports English language.

**Comment by charlesyoung** [comment]
@rawalrajen can you please move the code to production? Thanks 

cc @anjesh

**Comment by charlesyoung** [comment]
Please also change the following. 

1. Only Excel file format for upload, remove CSV
2. Please make sure that the Excel file follows the following format. Also note that the file contains a Readme tab that outlines standard capturing details. 
3. The Readme needs to include details of how multi-values are captured i.e. double pipe

**Comment by rawalrajen** [comment]
@charlesyoung The following changes have been made and deployed on production.

* Only Excel file format will support on import.

* Contract help text updated with the noted text

* The readme updated for multi values fields

**Comment by charlesyoung** [comment]
Thanks @rawalrajen. Can I confirm that a Main doc is noted as 0 and an Associated doc as 1.

**Comment by rawalrajen** [comment]
@charlesyoung Yes, as I have already mentioned it on readme section.

**Comment by charlesyoung** [comment]
We need to name contracts with the same name according to our standard i.e. Hocol S.A., Concession, 2014 (first doc no number), Hocol S.A., Concession, 2014-1 (second doc a number 1, etc). 

![image](https://user-images.githubusercontent.com/13888372/52772621-9c9c3080-3041-11e9-8b18-d88dcc377d52.png)

**Comment by charlesyoung** [comment]
@anjesh @rawalrajen any luck looking at above issue?

**Comment by charlesyoung** [comment]
@anjesh @rawalrajen any luck looking at above issue?

**Comment by SamCCSI** [comment]
@charlesyoung @anjesh is the bulk upload functionality currently working? What is the URL if so. And should I use @rawalrajen 's xls file, above? Thanks.

**Comment by charlesyoung** [comment]
@SamCCSI you can download the xls template from http://admin.resourcecontracts.org/contract/import. I have used it to import over 400 docs for Mexico and Colombia. We still need to do some mods like mentioned above wrt duplicate doc names. Please note that this is only an import with no publishing. We have also developed a standalone tool that bulk publishes the metadata that I can explain to you when you have time. The PDF text will need to be checked and published manually. 

@anjesh @rawalrajen have you had time to look at the duplicate names issue?

**Comment by anjesh** [comment]
@charlesyoung we haven't yet looked into that duplicate name issue. Will let you know once we sort that out. Thanks. 

cc @man-git007

**Comment by charlesyoung** [comment]
Picked up a bug. 

Error: File does not exist at path /var/www/rc-admin/public/data/3889/stats.json
Source URL: https://drive.google.com/open?id=1LT4zHRoMbZ4GOodHck2iHTUSPZOj79HX

**Comment by charlesyoung** [comment]
We need the inclusion of a 'Signature Year' column. When I captured 2016 in the 'Signature Date' column it populated today's date. 

![image](https://user-images.githubusercontent.com/13888372/57509129-c349ca80-7303-11e9-81f9-42cd931ecab2.png)

**Comment by charlesyoung** [comment]
1. Contract names generated via the import needs to adhere to our standard i.e. Hocol S.A., Concession, 2014 (first doc no number), Hocol S.A., Concession, 2014-1 (second doc a number 1, etc). It’s currently creating duplicate names. 
2. Bug as noted above
3. Signature date issue
4. Add additional columns in the xls

**Comment by anjesh** [comment]
Closing this. Further issues will be handled in https://github.com/NRGI/resourcecontracts.org/issues/1242
