### ISSUE TITLE
The AWS Access Key Id you provided does not exist in our records.

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1119]
@adinuca any idea why I'm getting this error? 

![image](https://user-images.githubusercontent.com/13888372/45217705-60e88800-b2a5-11e8-8cf3-4ca4ca34bde5.png)

**Comment by adinuca** [comment]
Hi @charlesyoung , no idea but I can check. Can you tell me where are you seeing this, on which page?

**Comment by adinuca** [comment]
Waiting for more instructions regarding the server where the application is running.

**Comment by charlesyoung** [comment]
@adinuca while we recommend hosting RC country sites some governments, like Sierra Leone and DRC, have requested that they host the country site. Can we arrange a call to discuss the implications?

**Comment by adinuca** [comment]
Hi @charlesyoung , I am available either today or tomorrow for a chat. Let me know what works best for you.

**Comment by adinuca** [comment]
Hi @charlesyoung, what is the status on this?

**Comment by adinuca** [comment]
@charlesyoung is this still an issue?

**Comment by charlesyoung** [comment]
Yep still an issue. Trying to resolve with the Ministry. Thanks
