### ISSUE TITLE
Annotation workflow needs structure

### ISSUE THREAD

**Issue by byndcivilization** [NRGI/resourcecontracts.org#112]
This was brought up in review today. Annotators will need a check list of clauses that should be annotated be for a contract is complete. One way would be to create a set of empty annotations on document creation that are not linked to text and only have annotation title.

**Comment by byndcivilization** [comment]
linked to #113

**Comment by anjesh** [comment]
Here's my proposed UI and workflow for the annotation process.

The researcher will see that there are 3 categories for which she needs to annotate. The annotation button shows that there requires at least 3 annotations. 

![image](https://cloud.githubusercontent.com/assets/120488/8671992/827d1bbc-2a49-11e5-8539-a11861e2bb80.png)

Now researcher knows the major areas to look for and annotate. She chooses the right tags for the annotation. 

![image](https://cloud.githubusercontent.com/assets/120488/8672023/ed26140a-2a49-11e5-917e-d2352ffaa775.png)

Now the admin and researcher can both see that 1 out of 3 annotations is done. 

![image](https://cloud.githubusercontent.com/assets/120488/8672030/04d0d810-2a4a-11e5-9d30-833d808b28f6.png)

The researcher can still continue annotating for the same category. 

![image](https://cloud.githubusercontent.com/assets/120488/8672033/11cc1c3c-2a4a-11e5-9cb7-b26af39a6707.png)

After annotating for the same category, the total number of desired annotations in the button doesn't change, reminding researchers that there's still 2 more to go. 

![image](https://cloud.githubusercontent.com/assets/120488/8672046/3671ce6a-2a4a-11e5-9a16-fe7e86010a4c.png)

cc @anderspeders @byndcivilization

**Comment by byndcivilization** [comment]
I like this solution a lot. @anderspeders or @SamCCSI?

**Comment by SamCCSI** [comment]
This looks great!

In practice there are over 80 annotation fields, and we can never tell which will be able to be filled in and which won't.

How do you think this solution would work with 80 (as opposed to 3) potential annotation categories?

Is it possible to have the list reorder, so that the unfulfilled annotation categories always remain at the top of the list, to prompt the annotator?

Also, for lengthy annotations, is there a way of shortening them on this list (eg have an 'expand' or '[...]' button) to maximize visibility of unfulfilled categories?

**Comment by byndcivilization** [comment]
@anjesh correct me if I'm wrong but ordering shouldn't be a problem. On general UI, I think maybe an accordion view would be super helpful here. So initially you'd see a list of <clause>: <status>. When you click on any individual status it expands to show annotation info if available. see for ex. http://getbootstrap.com/javascript/#collapse-example-accordion

**Comment by anjesh** [comment]
I have prepared the working proto for the annotation workflow here https://rawgit.com/anjesh/annotatorjs-hacks/master/index.html 
It doesn't save the annotations to the database so every refresh loses all the annotations, but it gives you the feel of how it would appear in rc interface. 
Yes ordering shouldn't be a problem.

**Comment by SamCCSI** [comment]
This looks great

1 - As an annotator, it would also be useful for the unannotated fields to appear in the order that they appear on our previous excel annotation spreadsheet. That way they are grouped in terms of:
- General information; 
- 1. Fundamental provisions; 
- 2. Community and social obligations; 
- 3. Developer's financial obligations; 
- 4. Environmental provisions; 
- 5. Operational provisions; 
- 6. Miscellaneous provisions. 
Makes it easier to have a sense of which annotations are missing.

2 - is it possible to have those 7 headings (above) on the list of unannotated fields? Just to add more structure to orient the annotator.

The text search for the annotation drop down when I add an annotation is working nicely now btw - thanks for this!!

@anderspeders  @byndcivilization  @anjesh

**Comment by SamCCSI** [comment]
I also like how the completed items appear below with green next to them.

Perhaps we could add one line of blank space or a 'completed annotations' heading to further differentiate?
