### ISSUE TITLE
Update RC description

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1121]
Change from: An online repository of publicly available contracts for large-scale land, agriculture, and forestry projects. The repository includes the full text of contracts; plain language summaries of each contract’s key social, environmental, human rights, fiscal, and operational terms; and tools for searching and comparing contracts.

To: An online repository of publicly available oil, gas, and mining contracts. The repository features plain language summaries of each contract’s key social, environmental, human rights, fiscal, and operational terms, and tools for searching and comparing contracts.

**Comment by anderspeders** [comment]
👍

**Comment by adinuca** [comment]
Hi @charlesyoung , should the description change only for resourcecontracts.org or for olc, drc and country sites as well?

**Comment by charlesyoung** [comment]
@adinuca the changes should only apply to RC and the RC country sites and not OLC. See below examples. 

![image](https://user-images.githubusercontent.com/13888372/46405411-7b791a00-c708-11e8-899f-00f8da5a4e39.png)

![image](https://user-images.githubusercontent.com/13888372/46405463-9e0b3300-c708-11e8-81ae-d41b66be6be3.png)

**Comment by adinuca** [comment]
The changes have been made for Staging. Waiting for Google to pick them out to be able to test this.

**Comment by adinuca** [comment]
Changes haven't been done for Google, for Staging yet. Moving it for next week.

**Comment by adinuca** [comment]
Hi @charlesyoung, I just wanted to make sure I changed the right thing. Changes came through for staging so I am going to deploy it to production now.

**Comment by adinuca** [comment]
Will close this issue once the changes are available in search engines for resourcecontracts.org and subsites.

**Comment by adinuca** [comment]
This has been done.
