### ISSUE TITLE
Redirect requests coming on http to https 

### ISSUE THREAD

**Issue by adinuca** [NRGI/resourcecontracts.org#1123]
## Why
Resourcecontracts.org is flagged as `not secure` when it is accessed using http protocol.

## What
- [x] http://resourcecontracts.org is redirected to https://resourcecontracts.org
- [x] the above is applied to all subsites
## Notes
This was flagged by Anders in #1122

**Comment by anderspeders** [comment]
👍

**Comment by adinuca** [comment]
This has been deployed to production.

Also, certificates have been generated for openlandcontracts.org and openladcontracts.com.
