### ISSUE TITLE
Potential security vulnerability in one of your dependencies .

### ISSUE THREAD

**Issue by adinuca** [NRGI/resourcecontracts.org#1124]
## Why
GitHub is reporting a potential security vulnerability in [RC subsites](https://github.com/younginnovations/resourcecontracts-rc-subsite) because of the jquery version that we are using.

## What
- [ ] Jquery is upgraded to the recommended version

## Notes
![Screen Shot 2018-09-18 at 17.17.02.png](https://images.zenhubusercontent.com/59816b15f8b79f8376e1a068/0b761d1d-4506-488f-a093-c145f10a832b)

**Comment by charlesyoung** [comment]
@adinuca can we close this ticket?

**Comment by adinuca** [comment]
Hi @charlesyoung , this will not be done this year, but we will still have to handle it at some point. I would leave it open.

**Comment by adinuca** [comment]
There are no security alerts for RC Subsite. Closing this.
