### ISSUE TITLE
Update RC API Staging to use Elasticsearch 5

### ISSUE THREAD

**Issue by adinuca** [NRGI/resourcecontracts.org#1129]
## Why
- We want to move away from Compose as their customer support is not the best and they to not have an alerting system to let you know if your deployments have scaled up. This has caused huge unexpected invoices in the past.
- Elasticsearch version currently used is no longer maintained and Compose will no longer support it starting with October 31st

## What
- [x] RC-API now works with Elasticsearch 5

## Notes
Check findings from #1126

**Comment by adinuca** [comment]
Query format has changed and `fields` has been removed and `_source` should be used.

**Comment by adinuca** [comment]
Hi @charlesyoung . Staging is ready for testing.

Please let me know if you find any issues.

Thank you!

**Comment by charlesyoung** [comment]
@adinuca I did some backend checks and all looks good. The public global staging site however seems down. 

![image](https://user-images.githubusercontent.com/13888372/46130229-09509300-c239-11e8-9bbf-8ee9573ff7de.png)

**Comment by adinuca** [comment]
@charlesyoung thank you. Which is the global staging site? What is the URL?
https://staging.resourcecontracts.org/ works fine for me.

**Comment by charlesyoung** [comment]
Try running a search.

**Comment by adinuca** [comment]
Thank you, I will take a look.

**Comment by adinuca** [comment]
Hi @charlesyoung ,

The search issue should be fixed. Please take a look and let me know if you find any other problems.

Thank you!

**Comment by charlesyoung** [comment]
Thanks @adinuca; the search issue seems resolved. 

Can you however please check the number of contracts because it seems lower than what's published in the backend.

**Comment by adinuca** [comment]
Hi @charlesyoung , I did indeed find an issue related to counting the documents, but I am not sure this is related to the issue you reported. 

Could you please tell me how you checked the number of contracts and what are you expecting this to be?

Thank you!

**Comment by charlesyoung** [comment]
All good, thanks.

**Comment by adinuca** [comment]
This has been done on Staging.
