### ISSUE TITLE
Metadata needs to be linked to annotations

### ISSUE THREAD

**Issue by byndcivilization** [NRGI/resourcecontracts.org#113]
This was brought up in review today. The workflow currently requires metadata on upload and then annotators must tag metadata. These are not linked and should be so there is only one data entry process. One way would be to create un linked annotations on upload for placement later.

**Comment by byndcivilization** [comment]
linked to #112

**Comment by jpmckinney** [comment]
Replacing "Metadata" tag with "Metadata - backend", as this is a backend issue, not a data modeling issue.

**Comment by charlesyoung** [comment]
@anjesh can we close this ticket?

**Comment by charlesyoung** [comment]
@anjesh can we close this ticket?

**Comment by anjesh** [comment]
> "The workflow currently requires metadata on upload and then annotators must tag metadata."

My understanding here is to include annotation as a part of metadata. for e.g. signature year is captured in metadata as well as in annotation. So there are same 2 entries for the same metadata, and the question here is whether we could just capture annotation and that would appear in metadata as well. So i am not sure how much important is it to link these two. Also this would bring other issues like validation as annotation is free-text as the entered text could have other char other than numbers (in case of year). But we need to have clarity on details here and discuss further. 

If we are happy with the current process, then we can close this issue.

**Comment by charlesyoung** [comment]
@SamCCSI @KaitlinCCSI thoughts?

**Comment by SamCCSI** [comment]
There is a trade-off between (i) the convenience of having annotations for date, country, etc auto-populate (with annotator still needing to create annotation markers as appropriate) vs. (ii) the amount of time to develop this feature.

No strong demand from our annotators but it would be a nice feature.
