### ISSUE TITLE
Update RC Index to work with Elasticsearch 6

### ISSUE THREAD

**Issue by adinuca** [NRGI/resourcecontracts.org#1131]
## Why
- We want to move away from Compose as their customer support is not the best and they to not have an alerting system to let you know if your deployments have scaled up. This has caused huge unexpected invoices in the past.
- Elasticsearch version currently used is no longer maintained and Compose will no longer support it starting with October 31st

## What
-  [ ] RC-Index works with Elasticsearch 6

**Comment by charlesyoung** [comment]
@adinuca can we close this ticket?

**Comment by adinuca** [comment]
We can close it for now, we will open another ticket once Elastic 5.6 reaches End of life.
