### ISSUE TITLE
Migrate Elasticsearch to version 5 in Production

### ISSUE THREAD

**Issue by adinuca** [NRGI/resourcecontracts.org#1137]
## Why
- We want to move away from Compose as their customer support is not the best and they to not have an alerting system to let you know if your deployments have scaled up. This has caused huge unexpected invoices in the past.
- Elasticsearch version currently used is no longer maintained and Compose will no longer support it starting with October 31st

## What
- [x] rc-admin is taken down or it is set in maintenance mode
- [x] A backup of the production data is made
- [x] A new deployment is created in Compose from the latest backup, upgrading to Elasticsearch 5
- [x] The beta environment is changed to use the new Elasticsearch deployment
- [x] Testing is done
- [x] Elasticsearch config and images are changed for rc-api and rc-index
- [x] nrgi-dcos for rc-api and rc-index production is changed to use the new elasticsearch urls
- [x] #1129 and #1138 are merged into master
- [x] Testing is done
- [x] rc-admin is brought back up

**Comment by anderspeders** [comment]
Thanks - it is great to see this plan shape up!

**Comment by adinuca** [comment]
Because of the errors in the logs(#1143), this issue has been postponed for next week.

**Comment by adinuca** [comment]
Hi @charlesyoung ,

I would like to try and migrate Elasticsearch in Production on Thursday morning. Would that be OK?

The biggest risk factor is Compose not working properly, if this happens I will have to abort and retry at another time. It happened a few times with the other migrations.

Let me know what hour would be best for this.

As previously mentioned, no downtime is expected for resourcecontracts.org and subsites.

Thank you!

**Comment by charlesyoung** [comment]
@adinuca is there any chance that we can rather do the migration on Friday morning?

**Comment by adinuca** [comment]
Friday morning is fine as well. Can I start at 8am your time?

**Comment by adinuca** [comment]
All has been done. RC-API and RC-INDEX are now using Elasticsearch 5 in production.
