### ISSUE TITLE
Guinea country site 

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1139]
Filter out hydrocarbon documents on the Guinea country site

**Comment by anjesh** [comment]
Here are you saying that we show all the contracts except hydrocarbons in https://guinea.resourcecontracts.org/resources?

**Comment by anjesh** [comment]
@charlesyoung will there will be a situation where the contract may have "Hydrocarbon" along with one or more resources (say Aluminium)? If yes, should we include in the site or not that particular contract with Hydrocarbon and Aluminium? If no, that would be easy, otherwise it gets tricky.

**Comment by charlesyoung** [comment]
No there won't be a combination of "Hydrocarbons" with another resource.

**Comment by anjesh** [comment]
Thanks. Good to know. 

cc @man-git007

**Comment by man-git007** [comment]
@charlesyoung The hydrocarbon filter in RC and OLC has been implemented and deployed in staging server. Could you please verify it?

**Comment by man-git007** [comment]
@charlesyoung The link to staging server for guinea is : 

https://staging.guinea.resourcecontracts.org/resources

https://staging.resourcecontracts.org/countries/gn

cc @anjesh

**Comment by rawalrajen** [comment]
There were issues on fetching resources for https://staging.guinea.resourcecontracts.org/resources, which is now fixed. Now hydrocarbons filter is implemented on guinea coutnry site only.

**Comment by charlesyoung** [comment]
Thanks @rawalrajen. Just to clarify that the hydrocarbon filter has only been applied to the RC Guinea subsite and not to all the RC and OLC subsites. I'm reopening the ticket because the code still needs to be pushed to the Guinea country prod site. https://www.contratsminiersguinee.org

![image](https://user-images.githubusercontent.com/13888372/50815035-61149500-1324-11e9-953c-b70f7f98c432.png)

**Comment by charlesyoung** [comment]
@rawalrajen what is the latest re this ticket?

**Comment by anjesh** [comment]
Now guinea site doesn't show hydrocarbon contracts https://www.contratsminiersguinee.org/ but resourcecontracts.org shows that. We are good to close this.
