### ISSUE TITLE
Metadata creation side by side with pdf

### ISSUE THREAD

**Issue by byndcivilization** [NRGI/resourcecontracts.org#114]
The current process requires annotator to have pdf open in separate window while looking for appropriate metadata in the contract. Side by side with original document would be helpful.

**Comment by anjesh** [comment]
Moving to sprint 5. This first needs some UI thinking as the current upload process needs to be split into 2 steps - upload pdf and some metadata, then view pdf side-by-side and add remaining metadata.

**Comment by anderspeders** [comment]
Let's discuss how we can advance this issue. Has been requested multiple times from uploaders as a practical help for making the metadata form easier to complete.

**Comment by anjesh** [comment]
I am thinking of 2 step process for uploading the contract to achieve side-by-side pdf or text view while filling contract metadata.

First step is to upload the document and add two fields - title and country

---

![image](https://cloud.githubusercontent.com/assets/120488/9194240/8898b848-4039-11e5-9550-a7633c7dbca6.png)

---

Submitting to above form takes to edit form with all the fields and the pdf view side by side. We need to rethink about the pagination here as discussed in #84

---

![image](https://cloud.githubusercontent.com/assets/120488/9194258/a9586dd0-4039-11e5-8067-1475b8d1d0ea.png)

---

We could have the text view as well, provided that the pdf process has successfully taken place. We can think about this later but would be a useful addition as it will allow to do the search in the text while filling the metadata. 

---

![image](https://cloud.githubusercontent.com/assets/120488/9194322/10ea603e-403a-11e5-9d9e-dd31f33d157f.png)

**Comment by charlesyoung** [comment]
@anderspeders @SamCCSI @anjesh is this still required?

**Comment by SamCCSI** [comment]
@charlesyoung would be helpful, but we probably need to weigh up the advantages of this against how long it would take to set up before we decide whether to proceed or not.

**Comment by charlesyoung** [comment]
@anderspeders @SamCCSI @anjesh can I close this ticket?

**Comment by anjesh** [comment]
Like Sam mentioned above, we need to weigh the advantages here and also understand the existing process. Are there any researchers who have been flipping through PDFs to enter the metadata or not, if there are number of such cases, then we might put some thoughts on this feature. If they are doing that, what about using separate pdf-viewer in their computer instead of side-by-side pdf view in the metadata entry page. This might be fast compared to side-by-side loading. 

This is again heavy feature due to pdf and pdf loading scripts and might affect the page loading.

**Comment by charlesyoung** [comment]
Thanks @anjesh. @SamCCSI what are your thoughts?

**Comment by SamCCSI** [comment]
Every researcher I work with flips through the PDF to enter metadata; that's the only way to ensure the metadata is accurate.

@charlesyoung perhaps we should discuss in our next tech meeting?

**Comment by charlesyoung** [comment]
Thanks, have labelled as needing further discussion.

**Comment by charlesyoung** [comment]
@SamCCSI can I close this ticket? I cannot see us implementing this feature in the future.
