### ISSUE TITLE
Investigate if auto-scaling should be configured for rc-api

### ISSUE THREAD

**Issue by adinuca** [NRGI/resourcecontracts.org#1153]
## Why
RC-API needs to handle a big number of requests when resourcecontracts.org is being scanned by bots.

## What
- [ ] Investigation is done on the need of auto scaling for RC-API
- [ ] Further issues are raised if it is needed.

## Notes
The amount of memory that RC-API can use has been increased(#1151). If bots scanning the site will still produce downtime, we should consider scaling RC-API up when the load is higher.

**Comment by charlesyoung** [comment]
@adinuca what is the status of this ticket?

**Comment by adinuca** [comment]
Hi @charlesyoung, I will close this ticket for now because we need to work on optimising the number of requests sent to Elasticsearch(#1155).
