### ISSUE TITLE
OLC down

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#1154]
OLC has been down on several occasions. @anjesh can your team please look into what might be causing this? Some of these outages have been fairly long. Not sure if RC has also been dropping cc @charlesyoung @anderspeders @jedm @KaitlinCCSI 

Pingdom DOWN alert:
NRGI - Production - RC Subsite OpenLandContracts (www.openlandcontracts.org) is down since 16/11/2018  00:43:07.
Reason: Could not find redirect location

PingdomAlert UP:
NRGI - Production - RC Subsite OpenLandContracts (www.openlandcontracts.org) is UP again at 16/11/2018  01:29:07, after 46m of downtime.

Pingdom DOWN alert:
NRGI - Production - RC Subsite OpenLandContracts (www.openlandcontracts.org) is down since 16/11/2018  01:30:07.
Reason: HTTP Server Error 502 Bad Gateway

PingdomAlert UP:
NRGI - Production - RC Subsite OpenLandContracts (www.openlandcontracts.org) is UP again at 16/11/2018  01:54:07, after 24m of downtime.

PingdomAlert UP:
NRGI - Production - RC Subsite OpenLandContracts (www.openlandcontracts.org) is UP again at 12/11/2018  21:48:07, after 4m of downtime.

PingdomAlert UP:

NRGI - Production - RC Subsite OpenLandContracts (www.openlandcontracts.org) is UP again at 10/11/2018  17:04:07, after 4m of downtime.

Pingdom DOWN alert:
NRGI - Production - RC Subsite OpenLandContracts (www.openlandcontracts.org) is down since 10/11/2018  17:00:07.
Reason: HTTP Server Error 503 Service Unavailable

**Comment by candrei** [comment]
@SamCCSI the site should be back up. 
@anjesh looks like ElasticSearch was unable to deal with the amount of queries/load. Any insight into whether there are recent changes that might trigger more queries per page load?

**Comment by anjesh** [comment]
No, we haven't done any changes to the code, i can only think of ES upgrade by Vitamin. Has that been done in production? @adinuca @charlesyoung

**Comment by adinuca** [comment]
Hi @anjesh , the migration has been done in Production.
There were several factors that lead to this:
- Resource Contracts ( main site, OLC site, country sites) were crawled by bots
- for some of the pages crawled by the bots, there were even 20 requests done to the API ( so traffic for the API was multiplied by 20)
- and the API, for one request does several other requests to Elasticsearch, which could not deal with the amount of load.

Catalin has scaled up the Elasticsearch server and also blocked 2 of the bots that were scanning the website. We will look further on what else has aggravated the issue and how we can improve this situation.

**Comment by adinuca** [comment]
Catalin took the IP from which the bots issue requests and blocked them. The IP used by the bots might change in the future.

**Comment by charlesyoung** [comment]
Yep bot IP's change dynamically. Do we not have a more automatic way of detecting and blocking bots?

**Comment by adinuca** [comment]
Not at the moment.

**Comment by charlesyoung** [comment]
@SamCCSI can we close this ticket?

**Comment by SamCCSI** [comment]
Closing now, though we may need to reopen if problem presents itself again
