### ISSUE TITLE
OLC/admin password reset

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#1156]
Hello, a couple of us are struggling to log into openlandcontracts.org/admin - is there a way to reset passwords for myself and Jesse? cc @adinuca @anjesh

**Comment by charlesyoung** [comment]
@SamCCSI I can help reset passwords. Pls send me a Skype with the user name and new password.

**Comment by SamCCSI** [comment]
@adinuca @anjesh Charles doesn't have ability to reset password for openlandcontracts.org/admin -- can you please help?

**Comment by adinuca** [comment]
Hi @SamCCSI , I do not have an account at all for openladcontracts.org/admin. 

I will be on vacation for the following week, so if @anjesh  cannot help you, please ask @candrei to take a look.

**Comment by anjesh** [comment]
Looks like something is not right, need to do some debugging. I see that https://resourcecontracts.org/login is also not working with the correct credentials but working fine with https://staging.resourcecontracts.org/login. i pushed the master changes to staging as these two are in different commits however it worked in staging. So i wonder if this is the server issue, still difficult to point now. 

I checked the API used for auth from olc and rc subsites - https://admin.resourcecontracts.org/api/login with the correct username and password and it's working. 

Could you share the following log from the https://resourcecontracts.org?

* https://github.com/younginnovations/resourcecontracts-rc-subsite/blob/master/config/log_files.yml.template#L5
* https://github.com/younginnovations/resourcecontracts-rc-subsite/blob/master/config/log_files.yml.template#L7
* https://github.com/younginnovations/resourcecontracts-rc-subsite/blob/master/config/log_files.yml.template#L15

**Comment by charlesyoung** [comment]
@anjesh can this possibly relate to the Compose to Elastic migration?

**Comment by anjesh** [comment]
I don't think elastic migration is the issue here as the authentication is taking place over the API in admin.resourcecontracts.org on the database directly. I hope we might get some ideas from the log.

**Comment by candrei** [comment]
@anjesh sorry for the delay. Here are the logs from [Papertrail](https://papertrailapp.com/searches/52703132) for the past few days: 
[ResourceContracts - PROD nginx error php fpm and storage logs.txt](https://github.com/NRGI/resourcecontracts.org/files/2620692/ResourceContracts.-.PROD.nginx.error.php.fpm.and.storage.logs.txt)

**Comment by SamCCSI** [comment]
@charlesyoung @anjesh any updates on this? We hope to make textual changes to the site soon.

Many thanks!

**Comment by adinuca** [comment]
@anjesh  please let us know if you need any assistance from Vitamin.

**Comment by charlesyoung** [comment]
@SamCCSI we are looking into the issue. It works on the staging site which is confusing. Will revert ASAP when we have more info. 

cc @anjesh

**Comment by anjesh** [comment]
@adinuca can you please check what value is set for ADMIN_API_URL in .env variables in https://resourcecontracts.org and https://staging.resourcecontracts.org/?

**Comment by anjesh** [comment]
@adinuca Let me know when you are done. There shouldn't be a problem. http://admin.rc redirects to https://admin.rc but for staging for http and https work separately. So the API auth over http://admin.rc throws error as the code doesn't handle the redirection.

**Comment by adinuca** [comment]
Please check now.

**Comment by anjesh** [comment]
working now. many thanks @adinuca 

cc @SamCCSI @charlesyoung

**Comment by charlesyoung** [comment]
@SamCCSI can you confirm that you can access the OLC admin page.
