### ISSUE TITLE
Remove the required annotation summary 

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#1160]
## Why

Annotation is to be used as tagging. Now text is required to add annotation as shown below. 

![image](https://user-images.githubusercontent.com/120488/49581366-c9fd9b80-f979-11e8-86e8-b460a8a32f5a.png)

## What

- [ ] Remove the annotation summary required option to allow for tagging

**Comment by anjesh** [comment]
@charlesyoung please confirm the above task - we need to make that annotation-text field optional.

**Comment by charlesyoung** [comment]
That’s correct @anjesh. Can you please remove the required annotation summary option on the staging site.

**Comment by charlesyoung** [comment]
@anjesh can you also please remove English being mandatory when capturing annotations. A user should be able to select French without first doing it in English. 

![image](https://user-images.githubusercontent.com/13888372/49932324-67545480-fed1-11e8-8a8c-efe5e977e476.png)

**Comment by man-git007** [comment]
@charlesyoung we have removed the annotation text which was required and have deployed to staging server.
Could you please verify the changes? The link is below:
https://admin-staging.resourcecontracts.org/contract/2865/annotate#/text

**Comment by charlesyoung** [comment]
@man-git007 it worked for the first annotation but is now noting again that the annotation text is required.

**Comment by charlesyoung** [comment]
@man-git007 have you made any progress with this ticket? 

cc @anjesh

**Comment by man-git007** [comment]
@charlesyoung Could you please add screenshot of the error. Can you please do hard refresh on the browser as it might be due to cache also.

**Comment by rawalrajen** [comment]
@charlesyoung The annotations categories of English and French are exactly the same in staging server.

**Comment by charlesyoung** [comment]
@man-git007 can you please deploy on the production site. 

cc @anjesh

**Comment by charlesyoung** [comment]
@man-git007 has this been deployed on the production site.

**Comment by man-git007** [comment]
@charlesyoung this has been deployed to production.

cc @anjesh

**Comment by charlesyoung** [comment]
Thanks @man-git007
