### ISSUE TITLE
Text searching 

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1163]
- [x] text searching in [contract view page](https://resourcecontracts.org/contract/ocds-591adf-3433899670/view#/search/Province) is working 

Now you will see that province is present in the text and yet it's not found during search.

![image](https://user-images.githubusercontent.com/120488/68449903-18ae5800-0211-11ea-8d55-833ead41d027.png)

---

Text searching on contracts doesn't work. 
Examples below. 

https://resourcecontracts.org/contract/ocds-591adf-3433899670/view#/search/contract
https://resourcecontracts.org/contract/ocds-591adf-4256816203/view#/search/petroleum
https://resourcecontracts.org/contract/ocds-591adf-2219177832/view#/search/omv

**Comment by anjesh** [comment]
text searching is not working in both OLC and RC staging and prod. Direct API is not returning the results.
@adinuca could you share the credentials for elastic.co for staging site index so that we can see what's happening.

**Comment by adinuca** [comment]
Hi @anjesh, here is the elasticsearch endpoint: https://54e756e310564547a3ad70b2275c5a3c.us-east-1.aws.found.io:9243 and the user is `elastic`. I will send you the password by email.
The index used is rc_demo_3 .

**Comment by charlesyoung** [comment]
@anjesh any luck identifying the issue?

**Comment by anjesh** [comment]
We will looking into this - this week. 

cc @man-git007

**Comment by charlesyoung** [comment]
@anjesh @man-git007 any luck identifying the issue?

**Comment by anderspeders** [comment]
Hi @anjesh, Did you have any luck looking into this?

**Comment by bizaybsnt** [comment]
@charlesyoung 
This issue has been fixed and deployed to the master. Please check and verify it.

cc: @anjesh

**Comment by charlesyoung** [comment]
Thanks @bizaybsnt 

I will test and get back to you.
