### ISSUE TITLE
Text updates in country pages

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#1169]
## What

- [x] On “All Countries” Page http://www.openlandcontracts.org/countries, Change totals to “[X] Documents" instead of “[X] Contracts" 
- [x] Change wording in Search boxes/Column headings in country page http://www.openlandcontracts.org/countries/kh
  - [x] Change “Search within [Cambodia] contracts” to just “Search [Cambodia] documents”
  - [x] Change heading “Contracts in [Cambodia]” to “Documents from [Cambodia]”
  - [x] Change capitalization of heading from “Resources In [Cambodia]” to “Resources in [Cambodia]” (lower-case “I”)

**Comment by charlesyoung** [comment]
Thanks @rawalrajen. 

cc @SamCCSI @jedm

**Comment by charlesyoung** [comment]
@jedm are you happy to move to prod?

**Comment by SamCCSI** [comment]
@rawalrajen @charlesyoung thank you. This looks great, and OLC is happy for you to move these changes to the live site.

cc @jedm

**Comment by jedm** [comment]
Agree it looks great. I join Charles and Sam in approving. Thanks, @anjesh!

**Comment by charlesyoung** [comment]
Thanks @rawalrajen
