### ISSUE TITLE
Improve comparison feature

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#117]
Enable pinning
Improve UI

**Comment by anderspeders** [comment]
We should include this feature as part of the UI discussion.

**Comment by anderspeders** [comment]
Can we receive a new mock up of the side by side comparison feature that can to into the betalaunch?

**Comment by anjesh** [comment]
Improve functionality is present now but it needs to have selection menu in the interface. Closing this and taking this issue in #234 for the selection menu and UI updates.
