### ISSUE TITLE
Investigate the purpose of the 4 requests made by RC API for /metadata

### ISSUE THREAD

**Issue by adinuca** [NRGI/resourcecontracts.org#1174]
## Why
Each requests made to RC-API /metadata generates 4 requests to ES.

## What
- [ ] An investigation is done on why 4 requests are made to ES with the purpose of decreasing the number of requests.
- [ ] Follow up issues are raised based on the results of the investigation

**Comment by adinuca** [comment]
Hi @anjesh , 
Do you know why we are using the `contract_id` to retrieve annotations for the search page but we are using `open_contracting_id` to retrieve annotations, metadata and text when viewing a contract?
Eg: 
The following request to the API is made when the user accesses https://staging.resourcecontracts.org/contracts : `/contract/84/annotations?lang=fr&category=rc`
But when the user views the first contract in the results, the request for annotation will be made to `/contract/ocds-591adf-8082857980/annotations?lang=fr&category=rc`.

Thanks!

**Comment by anjesh** [comment]
@adinuca that is the legacy issue, but both contract_id and ocid works in all the urls and APIs as far as i remember. The public site now uses ocid to retrieve the data, but contract_id works as well. We started with contract_id and later it was decided to use ocid in public sites and eventually that is reflected in APIs as well. But previous source-codes might not have been updated as it works with both ids.

**Comment by adinuca** [comment]
Hi @anjesh , 
Thank you for your answer. I am not looking to deprecate this feature, I was asking because using the same ID everywhere in RC Subsites would reduce the number of calls to the API, because the call for the annotations might be already cached when a user clicks on a contract.

**Comment by adinuca** [comment]
The request for metadata is retrieving data about the contract itself, the parent contract(the contract from which the requested contract is translated from) and based on the parent contract it retrieves information about the supporting contracts. 
The number of requests to Elasticsearch cannot be decreased.
