### ISSUE TITLE
Decrease the number of requests made to API for a RC Subsite search page viewed

### ISSUE THREAD

**Issue by adinuca** [NRGI/resourcecontracts.org#1176]
## Why
For each search page viewed in RC subsites we are doing up to 26 requests to RC API(and Elasticsearch). Performance of the websites can be improved by decreasing the number of requests made to RC API and Elasticsearch.

## What
- [ ] Numbers of requests made to RC API(and Elasticsearch) for each search page is decreased from 26 to 1 or 2. 

## Notes
This is a follow up issue for #1172 .
Any search made on https://resourcecontracts.org/search or on any of the search pages of the subsites can generate up to 26 requests. Same happens when the sorting is used in the tables.

**Comment by adinuca** [comment]
Hi @anjesh , any idea when this will be done?
Thank you!

**Comment by anjesh** [comment]
@charlesyoung for your decision on whether to move forward with this or not? Not urgent but helps with the performance.

**Comment by charlesyoung** [comment]
This is something we need to look at but lets put in on hold for now.

**Comment by adinuca** [comment]
This still needs to be done. Every time bots crawl one of the subsite, Elasticsearch gets overloaded due to the number of requests made to the API, which in turn queries Elasticsearch. 
Our current way of avoiding the site going down when a bot crawls the subsites is to block the bot.

**Comment by SamCCSI** [comment]
Seeing these bots in our user referrals in google analytics. @charlesyoung is this something that Vitamin is helping to minimize?

![image](https://user-images.githubusercontent.com/12913915/100907692-a4d49280-3498-11eb-852b-43c6d78b447f.png)

**Comment by charlesyoung** [comment]
Yep, Vitamin has been looking at this. 

cc @iprunache @candrei

**Comment by iprunache** [comment]
We did manage to reduce the load on the sites from such bots which allowed us to cut costs with the infrastructure.

@SamCCSI what is your concern about the bots you mention? Is it infrastructure cost or something else? Just trying to make sure we understand how to help best.

**Comment by SamCCSI** [comment]
Thanks @iprunache it's not really my field, i just know that they previously increased demand/costs on infrastructure, like you say, and also that they can mess up the analytics a little.

This one still seems active, but maybe that's not an issue. I'm not really sure. Just wanted to flag, as I was checking analytics for another purpose. Thanks!

![image](https://user-images.githubusercontent.com/12913915/100920533-4237c280-34a9-11eb-8019-2d5876f0ed22.png)

**Comment by candrei** [comment]
@SamCCSI @charlesyoung it's expected to see bots under the "referrals" section of GA. Referrals simply imply that humans have been directed by these search engines (eg: Baidu.com) to access RC pages. Hope this clarifies things.

**Comment by charlesyoung** [comment]
80% completed.
