### ISSUE TITLE
Abbyy account details

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1177]
@anjesh what coding updates will be required if we change the Abbyy account details?

cc @anderspeders

**Comment by anjesh** [comment]
We will need abbyy appid and password https://github.com/anjesh/pdf-processor/blob/master/settings.config.bak

**Comment by charlesyoung** [comment]
@anjesh so its just a config update with no code changes? 

@anderspeders

**Comment by anderspeders** [comment]
@anjesh So can I take from this that it is an easy fix? If yes, I can go ahead and do this tomorrow (Thursday).

**Comment by anjesh** [comment]
Yes, infact @adinuca will need to do that, just update the global config variables - ABBYY_APP_ID 
 and ABBYY_PASSWORD 
 https://github.com/NRGI/resourcecontracts.org/blob/master/conf/settings.config.template

**Comment by adinuca** [comment]
Hi @anderspeders , @charlesyoung ,

I can change the ABBYY credentials. Just let me know which are the new credentials and if they should be changed for both Staging and production.

**Comment by charlesyoung** [comment]
Thanks @adinuca. We will need it on both sites, the staging is used for demo's and testing.

**Comment by adinuca** [comment]
@anderspeders , @charlesyoung , please let me know when you have the new ABBYY account details.

Thank you!

**Comment by adinuca** [comment]
Hi @charlesyoung , the changes have been made. Is there a way to test it?

**Comment by charlesyoung** [comment]
Tested.
