### ISSUE TITLE
RC down: Possible issue in ES

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#1185]
## Why

https://resourcecontracts.org/?lang=en works and gets down in subsequent refresh.

## What

http://api.resourcecontracts.org/contracts sometimes works and gives error in next refresh

![image](https://user-images.githubusercontent.com/120488/52190660-753aac00-2868-11e9-961b-a95a3b237ac6.png)

Here it says "requested cluster unavailable". i am assuming some issue in ES
![image](https://user-images.githubusercontent.com/120488/52190670-8d123000-2868-11e9-8a7f-fd1fb26d64dc.png)

**Comment by adinuca** [comment]
Hi @anjesh , how often does it happen?

**Comment by adinuca** [comment]
@anjesh , thank you for reporting it. It looks like Elasticsearch is having some connectivity issues : https://cloud-status.elastic.co/

**Comment by anjesh** [comment]
Thanks @adinuca

**Comment by adinuca** [comment]
This has been fixed after about 12-14 hours.
