### ISSUE TITLE
Post mortem for Elasticsearch downtime on the 02/04/2019

### ISSUE THREAD

**Issue by adinuca** [NRGI/resourcecontracts.org#1188]
## Why

Resource contracts  was unavailable for about 12h on 02/04/2019. 

## What
- [x] A proper post mortem is shared with the team

## Notes
#1186 was raised to return an error code when an error page is displayed, for RC subsites.

**Comment by adinuca** [comment]
@candrei , please review: https://docs.google.com/document/d/1t7xTJq1qtp9hoD2PTi2pCwAwm86xb5ugKQGiibmQKxU/edit

**Comment by candrei** [comment]
@adinuca completed review, left a couple of comments.

**Comment by adinuca** [comment]
Thanks @candrei .

@charlesyoung, I have shared the document with you, by email.
