### ISSUE TITLE
Make sure OLC domain is renewed before March 11th 2020

### ISSUE THREAD

**Issue by adinuca** [NRGI/resourcecontracts.org#1191]
## Why
openlandcontracts.org domain is not set up to auto renew itself and it expires on March 11th 2020.

## What
- [x] openlandcontracts.org is renewed before March 11th 2020. 

## Notes
Not renewing the domain in time will cause downtime for OLC

**Comment by adinuca** [comment]
This is just a reminder to check if the domain got renewed, I would leave this open.

**Comment by charlesyoung** [comment]
cc @SamCCSI

**Comment by adinuca** [comment]
Domain has been renewed: 
```
Registered On:2014-03-11
Expires On:2021-03-11
Updated On:2020-02-10
```
