### ISSUE TITLE
Category attribute

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#1192]
Hi @anjesh, Is the OLC/RC coding the item that’s returned as this attribute in the [documentation](https://github.com/NRGI/resourcecontracts.org/wiki/Search-Contracts)?:
 

> category: [
>         "rc"
>       ],

Asking because an external site is pulling contracts from the API but needs to be able to distinguish between RC and OLC contracts

 cc @anderspeders

**Comment by anjesh** [comment]
Yes only if you first get the list of contracts using the search API http://api.resourcecontracts.org/contracts/search?q=&country=GN&group=metadata 

category is not present when you pull specific contract http://api.resourcecontracts.org/contract/ocds-591adf-3433899670/metadata

**Comment by charlesyoung** [comment]
@SamCCSI can I close this ticket?
