### ISSUE TITLE
Backend project names import

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1196]
- [x] add the following disclosure modes in the dropdown
   - Government
   - Company
   - Security exchange

![image](https://user-images.githubusercontent.com/120488/69231961-29b47d00-0bb2-11ea-8554-d0a959fe5e63.png)

- [ ] update disclosure mode in the excel
   - Company website = company
  - EITI = other
   - Civil society = other
   - Media = other
   - OpenOil = other
   - Found elsewhere = delete
   - Informal = delete
- [ ] fix the excel in case of spelling mistakes. There are few spelling mistakes in disclosure modes.
- [x] write a script that will update the following values for the given OCIDs in this [excel](https://docs.google.com/spreadsheets/d/1y5OqZtO4kXfa81GooCuUE5Dc79q9BGah-pu95eBb4PY/edit#gid=1457221475). The script will update the value in the database if it's present in both db and excel. The script will create value in the database if it's present in the excel but not in the db. The script will not delete any value in the database if it's not present or null in the excel.

  * Project title
  * License title
  * License Identifier
  * Source URL
  * Disclosure mode

**Comment by charlesyoung** [comment]
https://docs.google.com/spreadsheets/d/1y5OqZtO4kXfa81GooCuUE5Dc79q9BGah-pu95eBb4PY/edit#gid=1457221475

**Comment by anjesh** [comment]
There's a confusion on the data between License name and Project name and which fields to update in the database.

For ex: Excel file row 2060 says `project Title:  Block 72, Al-Ain Area`. But in the system, that's `Licence Title`

![image](https://user-images.githubusercontent.com/120488/68450451-3f6d8e00-0213-11ea-8f6d-3df4ac8d2447.png)

![image](https://user-images.githubusercontent.com/120488/68450661-e81bed80-0213-11ea-8598-8959d78103e8.png)

Similarly And this license name in excel is project name in the system.

![image](https://user-images.githubusercontent.com/120488/68450761-421cb300-0214-11ea-88e0-72914b5cc2f7.png)

![image](https://user-images.githubusercontent.com/120488/68450777-52349280-0214-11ea-8af1-206e2389fdf0.png)

@charlesyoung please verify.

**Comment by anjesh** [comment]
@charlesyoung need more info on this issue?

**Comment by charlesyoung** [comment]
Should be the Project Title and not License Name. So for below example 'Patoz Marinza' should be removed from the License Name and 'Patos Marinza' added to the Project Title. 

![image](https://user-images.githubusercontent.com/13888372/68909655-bcd75800-0757-11ea-97d9-4ded92934f28.png)


![image](https://user-images.githubusercontent.com/13888372/68909628-a3cea700-0757-11ea-9c82-ea8814630003.png)

**Comment by anjesh** [comment]
Not clear what you are trying to say?

## Examples 

### Example 1 

https://resourcecontracts.org/contract/ocds-591adf-2547744131

![image](https://user-images.githubusercontent.com/120488/68927754-91cd2280-07b0-11ea-81fd-7dd19750e8fb.png)

![image](https://user-images.githubusercontent.com/120488/68927789-a90c1000-07b0-11ea-9d2d-1234ea7ff8c3.png)

- [ ] Do we delete `Amu Darya Basin EPSC` from License name (as Iicence name column is blank for this row) and Project name?

### Example 2

https://resourcecontracts.org/contract/ocds-591adf-1393397662

![image](https://user-images.githubusercontent.com/120488/68928010-318ab080-07b1-11ea-9947-ac037bc54fc1.png)

![image](https://user-images.githubusercontent.com/120488/68927956-161fa580-07b1-11ea-838c-f2bf00c9966a.png)

- [ ] Do we delete `Kucova Oilfield` from License name (as Iicence name column is blank for this row) and Project name and put `Kucova` in Project name?

- [ ] What is project title reference name? Do we ignore that?

## Approach

- [ ] Shall we just delete all the project name and license name for all the listed contracts and put whatever project name and license name is mentioned for these contracts as per excel? Does this sound good? @charlesyoung

**Comment by charlesyoung** [comment]
1. No, only delete license names if different from the Google sheet. Ignore and retain all license names if null in the Google sheet. 
2. Yes, delete existing license names if different from the Google sheet
3. Seems to be no place to store the project title reference name so ignore

**Comment by anjesh** [comment]
I see that there are still more highlighted columns. Here's my understanding and further confusions on other columns in the [copied sheet](https://docs.google.com/spreadsheets/d/1y5OqZtO4kXfa81GooCuUE5Dc79q9BGah-pu95eBb4PY/edit#gid=1797780160)

* `Project title` is replaced by `corrected project title` if `corrected project title` is present, otherwise we don't delete existing `project title`
* `License name` and `License Identifier` if present in the excel will update the  existing license name/identifier in the system if present in the database, otherwise create licence name/identifier.

- [ ] is `source url` to be updated?
- [ ] cnf is not valid url if it is to be updated
- [ ] what if `source url` is present and there's no `Source Url correction`. 
- [ ] same 3 above Qs for disclosure mode? 

@charlesyoung 

![image](https://user-images.githubusercontent.com/120488/69221246-e7ce0b80-0b9e-11ea-9f44-97d75d192db4.png)

**Comment by anjesh** [comment]
## Disclosure mode

For the disclosure mode, we found the following items. Are all of these to be added in the dropdown? @charlesyoung 

- Government
- Company
- Security   exchange
- Company   website
- EITI
- Civil   society
- Media
- OpenOil
- Found   elsewhere
- Informal

**Comment by charlesyoung** [comment]
- Don’t use ‘Found elsewhere’ and Informal’
- Can we add ‘Security exchange’ to the lookup table? 
- ‘Company website’ = ‘Company’
- Can we add ‘EITI’, ‘Civil society‘, ‘Media’ and ‘OpenOil’ as ‘Other’ Rather than adding it to the look up table?

**Comment by man-git007** [comment]
@charlesyoung we have updated the metadata of the contracts in live server and have added ‘Security exchange’  to the lookup table. Could you please verify?

The update metadata are

- Project title
- License title
- License Identifier
- Source URL
- Disclosure mode

cc @anjesh

**Comment by charlesyoung** [comment]
Great thanks.

**Comment by charlesyoung** [comment]
Have the project names been imported?

**Comment by man-git007** [comment]
@charlesyoung The project name is Project Title in excel and in the system and has been updated.
