### ISSUE TITLE
Remove basic auth for zambia.resourcecontracts.org

### ISSUE THREAD

**Issue by adinuca** [NRGI/resourcecontracts.org#1197]
## Why
Charles has requested that basic auth should be removed to make the site public.

## What
- [x] Basic auth is removed for staging.zambia.resourcecontracts.org and zambia.resourcecontracts.org 

## Notes
This line https://github.com/younginnovations/resourcecontracts-rc-subsite/blob/161bc1c51c4f37f70d9a8f970bdae91be639940d/config/init.sh#L113 needs to be changed to use the `nginx_subsite.template`instead of the `nginx_subsite_protected.template`

**Comment by iosifnicolae2** [comment]
@charlesyoung Basic auth has been removed for `zambia.resourcecontracts.org` and `staging.zambia.resourcecontracts.org `

**Comment by charlesyoung** [comment]
Many thanks @iosifnicolae2
