### ISSUE TITLE
Build pipeline has a problem

### ISSUE THREAD

**Issue by iosifnicolae2** [NRGI/resourcecontracts.org#1198]
## Why
No builds can be deployed in production.

## What
- [ ] the root cause of the problem has been identified
- [ ] the solution for the problem has been implemented
- [ ] a successful build has been deployed into production
## Notes
https://app.shippable.com/github/NRGI/nrgi-dcos/runs/2755/1/console

**Comment by adinuca** [comment]
Issue moved to [NRGI/nrgi-dcos #384](https://github.com/NRGI/nrgi-dcos/issues/384) via [**ZenHub**](https://www.zenhub.com/)
