### ISSUE TITLE
Recovering favicon for OLC

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#1199]
## Why
Favicon image was accidentally replaced for OLC

## What
Is there a way to recover the previous favicon image (A green square with a white O, I believe). If not, does anyone at YI have the original file? @anjesh 

## Notes
Many thanks!

**Comment by SamCCSI** [comment]
Just noting that this appears to have already be done on the staging site (Left tab), so all that's needed is to also use that favicon for the openlandcontracts.org main site (Right tab). Thanks! 

![image](https://user-images.githubusercontent.com/12913915/78028008-516bdc80-732c-11ea-8ffe-8af5ba48a6da.png)

**Comment by man-git007** [comment]
@SamCCSI The favicon has been restored. Could you verify it?

**Comment by SamCCSI** [comment]
@man-git007 i'm still getting the old one on safari and chrome, include in private/incognito mode

![Screenshot 2020-05-05 08 27 06](https://user-images.githubusercontent.com/12913915/81065838-3a2f8a00-8eaa-11ea-869f-8942b9c561ba.png)
![Screenshot 2020-05-05 08 26 49](https://user-images.githubusercontent.com/12913915/81065842-3ac82080-8eaa-11ea-932a-fb818c44a292.png)

**Comment by charlesyoung** [comment]
Works for me. 

![image](https://user-images.githubusercontent.com/13888372/81066354-46810a80-8edd-11ea-9e5e-947a85491505.png)

**Comment by charlesyoung** [comment]
@SamCCSI can we close this ticket. Works from my side. 

BTW the favicon can be updated from the OLC admin site. 

![image](https://user-images.githubusercontent.com/13888372/82446413-e5ddfa00-9aa6-11ea-9a0e-55923c9a351f.png)

**Comment by SamCCSI** [comment]
working, thanks
