### ISSUE TITLE
Document managment UI

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#12]
Should allow admin to deal with admin tasks of maintaining document library (Pydio or OwnCloud for example).

**Comment by anjesh** [comment]
See the UI for the interface here.
https://projects.invisionapp.com/share/SQ35WP05D#/screens/81456389 
https://projects.invisionapp.com/share/SQ35WP05D#/screens/81456390
https://projects.invisionapp.com/share/SQ35WP05D#/screens/81564510

**Comment by byndcivilization** [comment]
That looks good though I just want to reiterate #25 in that some of these fields like 'resource' aren't discrete values but rather arrays so tagging rather than bucketing.

**Comment by anderspeders** [comment]
Further iterations to be submitted based on user feedback / bug reports.
