### ISSUE TITLE
Plan and implementation of migration from old to new site

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#120]
Things to consider: 
- mapping of metadata: old to new format
- migration of annotations (page by page)

**Comment by anjesh** [comment]
Linked to https://github.com/NRGI/resourcecontracts.org/issues/29

Need to discuss about annotations. The old annotation has the following format, which provides the position in the pdf page. 
```json
           {
                "access":"public",
                "title":"Nom du Projet//Project title ",
                "page":1,
                "content":"PROJET BAUXITE DE KOUMBIA AMC\n",
                "location":{
                    "image":"144,644,163,83"
                },
                "resource_url":"http://www.documentcloud.org/documents/422720-amc_amc-convention-2010/annotations/70924.js",
                "id":70924
            }
```
We can migrate the annotations, however it will not be linked with the text i.e. annotated text will not be highlighted, though we can link with the page and make sure that when that annotation is clicked, the particular page is selected. Need discussion on how to move ahead on the annotations.

For the metadata, it seems only mapping of the metadata.

**Comment by anderspeders** [comment]
Metadata mapping (old annotation schema --> current metadata schema):
 
Resource --> Resource
Date of contract signature  --> Singature date
Country --> Country
Type of document --> Type of document
Local company name --> Company name
Name and/or number of field, block or deposit --> License/concession name
Project title --> Project name

**Comment by anjesh** [comment]
Tested http://www.documentcloud.org/documents/457904-drc-highwind.html in the demo and the annotations positions are close. For page 4 for http://resourcecontracts-demo.elasticbeanstalk.com/contract/49/pages?action=annotate 
![image](https://cloud.githubusercontent.com/assets/120488/9171736/bc1aeec2-3f8d-11e5-823f-f510461f7799.png)

Still need to do number of things
- Need to do the mapping for the old annotation title e.g `Nom de la société locale//Local company name` to annotation category
- Number of mistakes in the annotation title, need to map those mistakes into appropriate categories

This [data spreadsheet](https://docs.google.com/spreadsheets/d/1K0wlloEAPFncrNA_mwBjqvW81A5xRpFlK0qlv-j5ZYo/edit#gid=841744725) shows the data that could be mapped to the metadata in the new system. See the spellings.

This [sheet](https://docs.google.com/spreadsheets/d/1K0wlloEAPFncrNA_mwBjqvW81A5xRpFlK0qlv-j5ZYo/edit#gid=1612543715) shows the annotations categories that need to be fixed. Lots of variations in the labels. Just wondering if all these could be mapped to the existing [annotation categories](https://docs.google.com/spreadsheets/d/12UCQA422r5Dg3wruUmYHL2SCLdDrlesCPcm2tHD8Yu4/edit#gid=242312400).

**Comment by anjesh** [comment]
The data is now migrated to test-site rc-migration for testing. Waiting for annotation mapping https://github.com/NRGI/resourcecontracts.org/issues/206 to migrate to the staging portal before closing this issue.

**Comment by anjesh** [comment]
RC data have been migrated to staging portal.
