### ISSUE TITLE
Narrowing: Link free text and drop-down search results/functions 

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1226]
- [x] when search is performed (whether free-text or dropdown), the free-text and dropdown should be present

![image](https://user-images.githubusercontent.com/120488/68450123-fbc65480-0211-11ea-837c-6d4197a6c577.png)

**Comment by rumus007** [comment]
- [x]  Free text and advanced search results are now linked. 

Text will be now present in the free text search bar and users will be able to continue with the advanced search selecting any of the options.

**Comment by anjesh** [comment]
@charlesyoung please verify.

**Comment by charlesyoung** [comment]
Is this deployed on staging? 

Can we run it the other way round i.e. user runs advanced search and users will be able to continue with a free text search?

cc @jedm

**Comment by jedm** [comment]
Agree with Charles. This should function fully in “both directions.”

**Comment by rumus007** [comment]
@charlesyoung 
The search functionality in both directions is implement in staging site.
cc @anjesh

**Comment by charlesyoung** [comment]
Thanks, please implement on prod.

**Comment by rumus007** [comment]
@charlesyoung 
The search functionality has been implemented in production. Please do have a look.
cc @anjesh
