### ISSUE TITLE
Option to hide advanced search bar

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1227]
- [x] hide option is enabled in search in document listing

![image](https://user-images.githubusercontent.com/120488/68449762-93c33e80-0210-11ea-86bc-58949e1cff03.png)

That hide search is enabled in document-view page so we need to replicate that feature in listing page

![image](https://user-images.githubusercontent.com/120488/68449803-ba817500-0210-11ea-8c55-e13d06c93ab9.png)

**Comment by rumus007** [comment]
- [x] Hide search option is enabled in document view page

**Comment by anjesh** [comment]
@charlesyoung please verify and close this issue.

**Comment by charlesyoung** [comment]
Works but we need a more obvious way to unhide.

**Comment by charlesyoung** [comment]
Please hold for now. Getting feedback from some RC users.

**Comment by charlesyoung** [comment]
Below PowerPoint outlines the suggested display. Some points. 
- Search text is changed from 'Search all documents' to 'Free text document search' to make it more obvious
- The hide and show bars and displayed permanently
- The newly added hide icon is removed  

[RC search hide and display.pptx](https://github.com/NRGI/resourcecontracts.org/files/3869166/RC.search.hide.and.display.pptx)

@jedm do we keep the search option on the document text and PDF pages? I know it has been there from the beginning but I'm not sure it makes sense. If yes then we should standardize and also display the search toolbar which again to me doesn't make much sense.  

![image](https://user-images.githubusercontent.com/13888372/69239214-6c6e5900-0ba2-11ea-921f-e6367e184ec2.png)

**Comment by jedm** [comment]
@charlesyoung My recommendations:

- Agree about removing Advanced Search from PDF and doc text page
- Agree about conforming the open/close/expand/collapse/hide mechanism so it's the same wherever the Advanced Search appears
- I don't think a term like "free text search" is useful in the prompt. Let's take a minute to finalize what the text should be in the buttons/open-close prompts

**Comment by charlesyoung** [comment]
Thanks @jedm 

@anjesh can you please remove the advanced search option from the PDF and text page. 

@jedm are you happy with the proposed display noted in the PowerPoint? 

Will wait before updating the 'Search all documents' text.

**Comment by jedm** [comment]
Could the button that opens/closes simply say “Show Search Tools” and “Hide Search Tools?”

Also, after the new Hide control is in place do we still want the red “Hide” button that’s next to Search and Reset? I don’t think it is necessary, but if people prefer to keep it, would change it to same text, and change colors to same colors as show/hide button above (gray on gray).

**Comment by charlesyoung** [comment]
Thanks @jedm, PowerPoint updated with “Show Search Tools” and “Hide Search Tools". Yep I suggest that we remove the newly added "Hide" button. 

[RC search hide and display.pptx](https://github.com/NRGI/resourcecontracts.org/files/3873542/RC.search.hide.and.display.pptx)

**Comment by rumus007** [comment]
@charlesyoung 

- [x] Search bar is removed in the document text and PDF page.

- [x] "Show Search Tools" and "Hide Search Tools" button structure is implemented.

- [x] Previously added hide button is removed

All changes are implemented in staging site.

cc @anjesh

**Comment by charlesyoung** [comment]
Thanks. 

I don't see the "Hide Search Tools" button. 

![image](https://user-images.githubusercontent.com/13888372/69327791-c3ce0100-0c56-11ea-8fb9-0fd0c4f32dd2.png)

**Comment by rumus007** [comment]
It maybe due to cache. Please hard refresh the page.

**Comment by charlesyoung** [comment]
Please move to the Prod Site. Thanks

**Comment by rumus007** [comment]
@charlesyoung 
Changes are implemented in prod site.
cc @anjesh

**Comment by charlesyoung** [comment]
Thanks @rumus007 

How can we address the caching issue because I'm concerned that all existing RC users will see the 'hide' but not 'show' button as I have experienced on the Staging and Prod sites?

**Comment by rumus007** [comment]
It is due to browser cache. Quickest way is to hard refresh the page to remove the cache. Chrome or any other browsers tend to refresh cache automatically after certain period of time usually 24 hours.

**Comment by charlesyoung** [comment]
I'm going to leave this ticket open for now. 

The staging sites cache still hasn't refreshed since yesterday so I'm concerned that RC users will hide the search bar and then have no way of getting it back which is currently the case. I will check again on Monday.

**Comment by charlesyoung** [comment]
@rumus007 

Same issue persists both on Staging and Prod. Any suggestions to sort this out because users wont know that they need to refresh their cache. Once they hide the search bar they cannot currently get it back.

**Comment by rumus007** [comment]
@charlesyoung 

I have recently made some changes. Please check for staging site if the problem still persists.

**Comment by charlesyoung** [comment]
Great that works. Can you please apply the fix to the Prod site. 

What changes did you apply to fix the issue?

**Comment by rumus007** [comment]
The browser did not detect the changes made in the file so it loaded the JavaScript file from cache. Hence i add an optional argument in the script tag so that the browser is forced to re-download the file and cache the new file.

I will apply the changes in the prod site and comment as soon as it is deployed.

**Comment by rumus007** [comment]
@charlesyoung 
This has been deployed to prod site
cc @anjesh

**Comment by jedm** [comment]
So glad this is live! Thanks, @anjesh and YI. 

If it's possible to reduce the font size of "Show/Hide Search Tools" and make the font color a little bit more gray, I think it would make it look more like a Search control and a little less distracting. 

(But this is not an important change.) Thank you!

**Comment by charlesyoung** [comment]
@rumus007 could you reduce the font size of "Show/Hide Search Tools" and make the font color a little bit more gray as requested. Want to close relevant tickets. Thanks

**Comment by charlesyoung** [comment]
Please also hide the search bar on the 'About', 'FAQs', 'Guides', 'Glossary', 'Country Sites' and 'Contact' pages.

**Comment by rumus007** [comment]
@charlesyoung  
The requested changes are implemented in staging site please verify
@anjesh

**Comment by charlesyoung** [comment]
Thanks @rumus007 

@jedm please let me know if the changes are OK to move to the Prod site. 

Old: 
![image](https://user-images.githubusercontent.com/13888372/69784331-304c8100-11be-11ea-85ef-6786b152d84e.png)

New: 
![image](https://user-images.githubusercontent.com/13888372/69784309-27f44600-11be-11ea-8437-3ea05ba41e36.png)

**Comment by jedm** [comment]
Ok to move to Prod!

**Comment by charlesyoung** [comment]
@rumus007 please deploy on the Prod site.

**Comment by rumus007** [comment]
@charlesyoung 
This has been implemented to prod site
@anjesh

**Comment by charlesyoung** [comment]
@rumus007 can you please hide the search bar at the same places for the mobile site. 

![image](https://user-images.githubusercontent.com/13888372/70932487-8afd2e00-2042-11ea-91dd-f1279a894c84.png)

**Comment by man-git007** [comment]
@charlesyoung The search bar have been hidden in the mobile view and has been deployed to live server.

cc @anjesh

**Comment by charlesyoung** [comment]
Thanks @man-git007
