### ISSUE TITLE
Front end: Search opportunities

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#123]
As a user I would like to be able to search across three layers of content: 
i. a) metadata with basic data, 
ii. b) human-generated annotations of the contracts in accordance with annotation schema and 
iii. c) the full OCR’ed contract text 

For example: 
As a user I need to search and filter across contract a) content, b) annotations and c) metadata. This should include free text search on content, fuzzy matching of key terms, autocomplete search, and similarity recommendations. Example: As a researcher I would like a table with all the <Royalty Clauses>, for all <gold> contracts, from <2000 – 2014> in <Africa>. The result of the search should be available as clear interface and as download in an open format.

@anjesh Do we have this covered at this stage?

**Comment by anjesh** [comment]
To some extend, the above feature is there in the existing sub-site. Need to add download feature in the search results. Sprint 6. 
Still need more discussion on this.

**Comment by anjesh** [comment]
Need to have the download feature in the search results.

**Comment by anjesh** [comment]
Download option enabled.
