### ISSUE TITLE
Log Files Deleted

### ISSUE THREAD

**Issue by man-git007** [NRGI/resourcecontracts.org#1230]
We were expecting some error or info logs but there seems to be deletion of log files in `/storage/logs/` path. Does the log files get deleted after some period of time or gets deleted after deployment?

Since we are logging the MTurk API error logs. If there is periodic deletion of log files we might not be able to debug MTrul API errors.

cc @charlesyoung @adinuca @anjesh

**Comment by adinuca** [comment]
Hi @man-git007 , the logs get deleted with each deployment. You can configure the app to send the specific logs to Papertrail and access them from there. Configuration needs to go in https://github.com/NRGI/resourcecontracts.org/blob/master/conf/log_files.yml.template ( if not already there). 

I am not sure if you have access to https://papertrailapp.com/groups/3881793/events?q=ecs-rc-admin&focus=1107691733124288530 . If not, please give me your email and I will add you.

**Comment by man-git007** [comment]
@adinuca mey email:manish.pradhan@yipl.com.np

**Comment by adinuca** [comment]
> @adinuca my email:[manish.pradhan@yipl.com.np](mailto:manish.pradhan@yipl.com.np)

You should receive an invite.

**Comment by man-git007** [comment]
@adinuca Thank you for giving papertrail access. I have also updated the 
[https://github.com/NRGI/resourcecontracts.org/blob/master/conf/log_files.yml.template](https://github.com/NRGI/resourcecontracts.org/blob/master/conf/log_files.yml.template)

**Comment by charlesyoung** [comment]
@man-git007 can we close this ticket? 

cc @adinuca

**Comment by man-git007** [comment]
@charlesyoung yes we can close this ticket
