### ISSUE TITLE
DRC 'View by Resource' bug

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1234]
Clicking on 'View by Resource' and 'View all resources' opens the Ministries website and not the resource list in RC. 

![image](https://user-images.githubusercontent.com/13888372/64773368-86f8d600-d552-11e9-891a-6e9a315c2f64.png)

https://www.mines-rdc.cd/resourcecontracts/

**Comment by anjesh** [comment]
@charlesyoung  We need server access to www.mines-rdc.cd. The credentials mentioned [here](https://docs.google.com/spreadsheets/d/1EyHcGzATL0hrNgbREeTvUh47mVbxcLVMOu0bY30rGa8/edit#gid=0) doesn't work.

**Comment by adinuca** [comment]
Hi @charlesyoung , we don't have access to the document nor the website.

**Comment by charlesyoung** [comment]
Truing to get the server credentials, haven't had any luck yet.

**Comment by charlesyoung** [comment]
On hold until the Ministry provides server access.

**Comment by charlesyoung** [comment]
If I don't hear back from the Ministry by the end of Jan this ticket will be closed and the allocated time (1 day) will be moved to monthly RC support.

**Comment by charlesyoung** [comment]
Ticket closed, time moved to monthly RC support.
