### ISSUE TITLE
Fatal error: Class 'Illuminate\Foundation\Application' not found in /var/www/html/resourcecontracts/bootstrap/app.php on line 14

### ISSUE THREAD

**Issue by vishnu337** [NRGI/resourcecontracts.org#1235]
## Why
![resourcecontracts dev resourcecontracts public ](https://user-images.githubusercontent.com/55528482/65220752-16653280-dad9-11e9-935a-ccd46b053bde.png)

**Comment by adinuca** [comment]
Hi @vishnu337 , can you give us more details on how to reproduce this?

**Comment by vishnu337** [comment]
when access http://resourcecontracts.dev /public shows this error. I download the code and perform all commands. php version 7. Os :ubintu 14
