### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined method Illuminate\Foundation\Bootstrap\ConfigureLogging::configureCustomHandler() in /var/www/html/resourcecontracts/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/ConfigureLogging.php:54

### ISSUE THREAD

**Issue by vishnu337** [NRGI/resourcecontracts.org#1236]
PHP Fatal error:  Uncaught Error: Call to undefined method Illuminate\Foundation\Bootstrap\ConfigureLogging::configureCustomHandler() in /var/www/html/resourcecontracts/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/ConfigureLogging.php:54
Stack trace:
#0 /var/www/html/resourcecontracts/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/ConfigureLogging.php(17): Illuminate\Foundation\Bootstrap\ConfigureLogging->configureHandlers(Object(Illuminate\Foundation\Application), Object(Illuminate\Log\Writer))
#1 /var/www/html/resourcecontracts/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(183): Illuminate\Foundation\Bootstrap\ConfigureLogging->bootstrap(Object(Illuminate\Foundation\Application))
#2 /var/www/html/resourcecontracts/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(195): Illuminate\Foundation\Application->bootstrapWith(Array)
#3 /var/www/html/resourcecontracts/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(92): Illuminate\Foundation\C in /var/www/html/resourcecontracts/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/ConfigureLogging.php on line 54
Script php artisan clear-compiled handling the post-update-cmd event returned with error code 255

**Comment by charlesyoung** [comment]
@vishnu337 can you please identify yourself seeing that you don't work for any of the ResourceContracts system development companies.
