### ISSUE TITLE
Annotations entered in under "French" do not show up when viewing English version

### ISSUE THREAD

**Issue by SolinaCCSI** [NRGI/resourcecontracts.org#1239]
![Screen Shot 2019-10-23 at 6 39 23 PM](https://user-images.githubusercontent.com/54867922/67439535-7f523580-f5c4-11e9-9de2-5ecac05d7dcb.png)

![Screen Shot 2019-10-23 at 6 40 21 PM](https://user-images.githubusercontent.com/54867922/67439571-985ae680-f5c4-11e9-804b-4a9acbf1c4f6.png)

![Screen Shot 2019-10-23 at 6 40 46 PM](https://user-images.githubusercontent.com/54867922/67439592-a7da2f80-f5c4-11e9-839b-f786958c7527.png)
![Screen Shot 2019-10-23 at 6 41 35 PM](https://user-images.githubusercontent.com/54867922/67439629-c3ddd100-f5c4-11e9-9fc3-417646f70cce.png)

**Comment by SamCCSI** [comment]
Thanks @SolinaCCSI 

Also noting that this bug is a problem because (a) a pro bono annotator has used the "french" option for dozens of contracts and (b) Users on the site who have the site's language set as English will just see the annotation markers, but no annotation text.
![image](https://user-images.githubusercontent.com/12913915/67522879-8c7e2b80-f67b-11e9-9101-e3f57db14df3.png)

**Comment by anjesh** [comment]
This is not a bug but the system was designed that way. English is the default and fallback language, which means that annotation or any other metadata should be (ideally) mentioned in english first, and then other languages (french or arabic) can override them and if not overridden then english values are shown. 

For example, for this [contract](https://resourcecontracts.org/contract/ocds-591adf-2944436063/view#/), you will see annotation in [fr](https://resourcecontracts.org/contract/ocds-591adf-2944436063/view?lang=fr#/) as well as in [ar](https://resourcecontracts.org/contract/ocds-591adf-2944436063/view?lang=ar#/). 

If this feature (where any language could be fallback with priority like english, french and arabic) is desired, this needs some serious look into the system,  

This will need few hours research on how the system is structured and whether the desired functionality could be achieved before we dive into this. 

@charlesyoung

**Comment by charlesyoung** [comment]
Thanks @anjesh 

Just a note that we don't have much if any budget for this. 

cc @SamCCSI

**Comment by SolinaCCSI** [comment]
Thank you @anjesh and @charlesyoung. Given the limited budget and the time this will take, I think we will hold off activity on this issue for now. Thanks again for your help!

cc @SamCCSI
