### ISSUE TITLE
Under contract: Add "Participation share"

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#124]
This should be a non-mandatory numeric value between: [0 and 1.00]

**Comment by anderspeders** [comment]
Apologies, but this should be listed under the company section, as this will be an non-mandatory field for each company: 

![participation-share](https://cloud.githubusercontent.com/assets/1101585/8919009/1f657628-348a-11e5-86e3-ee60d7391520.JPG)

**Comment by anjesh** [comment]
Fixed in the admin and reflected in the sub-site.
