### ISSUE TITLE
Fixes in "Contract Import CSV / Excel file"

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#1242]
- [x] Contract names generated via the import needs to adhere to our standard i.e. Hocol S.A., Concession, 2014 (first doc no number), Hocol S.A., Concession, 2014-1 (second doc a number 1, etc). It’s currently creating duplicate names. 
- [x] add signature year column but if signature date is present, then signature year column will be ignored and pulled from signature date column.
- [x] update readme sheet with regards to OCID, association of main and supporting contracts
- [x] update the import process such that it prepares the download URL for files hosted in drive.google.com and downloads the file
- [ ] file doesn't exist bug https://github.com/NRGI/resourcecontracts.org/issues/1114#issuecomment-491175330

Followup from https://github.com/NRGI/resourcecontracts.org/issues/1114

**Comment by anjesh** [comment]
what are the additional columns to be added in excel? @charlesyoung

**Comment by charlesyoung** [comment]
1. We need a more elegant way of importing main and associated documents. The current method of first importing the main document and then capturing the OCID for the related associated documents is cumbersome. 
2. Take a look at this Google [sheet](https://docs.google.com/spreadsheets/d/1Qn9Z-ILIkuacwNk3CWSz7p9-_sY28tdvyRqrHrYol0o/edit#gid=1642145229). There is an issue uploading the documents noted in the 'Document URL' column.

**Comment by anjesh** [comment]
## Issue with document URL with google-drive

For the Document URL using google-drive, the URL is a html page with download URL. you need to use download url, i have created new column with download-url [here](https://docs.google.com/spreadsheets/d/1Qn9Z-ILIkuacwNk3CWSz7p9-_sY28tdvyRqrHrYol0o/edit#gid=1690570418). Please try. This should work.

## Linking main and associated documents in the same CSV

For importing main and associated documents, I am wondering if we could follow this approach.

* Use Column C `Main   Document OCID (if already published)` to show the linkage in the absence of OCID. 
  * If `above` keyword is used, it will link the associated document with above main document. 
  * Missing `above` keyword will not link the document. 
  * Anything for `main` document will be ignored.

What do you say? @charlesyoung 

![image](https://user-images.githubusercontent.com/120488/68653145-29cdd080-0553-11ea-812d-173793bea4ee.png)

## Extra columns

Are there any extra columns that need to be imported from csv?

**Comment by charlesyoung** [comment]
Thanks @anjesh Would we ever use the 'missing above keyword' option because all associated documents should have a main document. Or does it just give us another option in case its required for some reason.

**Comment by anjesh** [comment]
## Linking main and associated documents in the same CSV

Shall we assume that unless OCID is mentioned, associated is always linked with main (which always appears in row above associated) 

![image](https://user-images.githubusercontent.com/120488/68926858-8bd64200-07ae-11ea-91b7-d307ed4c5a6b.png)

And there might be a case where incorrect OCID is types, in that case, we will still import associated contract into the system but without linking with main contract. Message will be shown that contract couldn't be linked because OCID is not present in the system

Please confirm if this sounds like reasonable assumptions to follow. @charlesyoung 

## Contract names generation

This is the process to follow for contract names during import 

If contract name is mentioned in excel, it copies the same in the system.
If contract name is not mentioned, it is generated as it used to. During contract generation, if the same contract name is found in the system, it will append number. 

Here's example for our clarity

For eg, if `Hocol S.A., Concession, 2014` is found for subsequent contract, the name becomes `Hocol S.A., Concession, 2014-1`. And again next time, if the next contract names appearslike  `Hocol S.A., Concession, 2014`, the name should be `Hocol S.A., Concession, 2014-2` and so on. 

## Extra columns

I am confirming that there are not extra columns to be added in excel, as you haven't replied to my question above, asked 2 times? @charlesyoung

**Comment by charlesyoung** [comment]
We should add a signature year column because we currently only have a signature date column and there are documents without a signature date. 

Also please try import attached xls. I get below error after changing the URL as noted above. 

![image](https://user-images.githubusercontent.com/13888372/69032915-5ddb4280-09e6-11ea-8179-0bcd02a4790e.png)

[Zambia test import.xlsx](https://github.com/NRGI/resourcecontracts.org/files/3857283/Zambia.test.import.xlsx)

**Comment by anjesh** [comment]
Then in that case, we will have new signature year column but signature date will override signature year if both these values are present, to avoid confusion when both are present and have different years.

**Comment by rumus007** [comment]
@charlesyoung 
The excel file upload now consists of the following and is implemented in the staging:
- [x] The contract name generation adheres to our standard i.e. if contract name is present in the excel file the same name is stored. If there is no contract name present it will be generated via system. If the contract names are same the number will be appended.

- [x] Signature year column is added to the excel file. Signature date is not mandatory. If Signature date is present then it will override the signature year information.

- [x] Unless OCID is mentioned in the **Main Document OCID**  it is assumed that the associated document is linked with the main document mentioned in the excel file 

![image](https://user-images.githubusercontent.com/51116139/69232317-edcde780-0bb2-11ea-900a-443ffabb9b32.png)


Regarding the above attached xls file. It seems the document url is not downloadable.
I uploaded the file in the staging site after changing the document url. The file that i uploaded is attached here. 
[Zambia.test.import.xlsx](https://github.com/NRGI/resourcecontracts.org/files/3868801/Zambia.test.import.xlsx)

![image](https://user-images.githubusercontent.com/51116139/69232567-72b90100-0bb3-11ea-85a6-92861d6a29b5.png)

cc @anjesh

**Comment by charlesyoung** [comment]
Thanks @rumus007 

Can you please add some details re the linking of docs i.e. OCID, etc to the xls readme tab. 

I don't understand your comment that the 'document url is not downloadable'. What link format is required from Google Drive, Dropbox, Box, etc?

**Comment by rumus007** [comment]
@charlesyoung 

The link in the first xls file was: https://drive.google.com/file/d/1g2Q0QuqTp5oU7qIcDBwiifXC0PsZUIXS/view?export=download
If you click on the link it will open the document however it will not download the file.

You have to click on the download icon in order to get the download link which
https://drive.google.com/a/yipl.com.np/uc?authuser=0&id=1g2Q0QuqTp5oU7qIcDBwiifXC0PsZUIXS&export=download

If you click on the second link it will download the file.

cc @anjesh

**Comment by charlesyoung** [comment]
I tested the main and supporting documents import and that works. 

We will however need to find a better solution re the URL. I cannot expect a user who has copied 100 documents to a Google Drive to get the required download link for each document.

**Comment by anjesh** [comment]
Does it make sense to give a proper instruction on how to convert the [url](https://drive.google.com/file/d/1g2Q0QuqTp5oU7qIcDBwiifXC0PsZUIXS/view?export=download) to [download url](https://drive.google.com/a/yipl.com.np/uc?authuser=0&id=1g2Q0QuqTp5oU7qIcDBwiifXC0PsZUIXS&export=download) in case of google drive? Can we  expect user to follow such instructions when while preparing the data for import?

**Comment by charlesyoung** [comment]
Is there a command / routine that the user could run to convert from url to download url rather than having to do it individually? I monitor and manage all imports so will provide the required instructions to the user.

**Comment by anjesh** [comment]
One thing we could do is to update the import process such that if it finds drive.google.com in the URl, it would create the download link and downloads the pdf. But for others hosted files, user will have to make sure that they use proper link.

**Comment by charlesyoung** [comment]
That would work. I manage the import process so I will make sure that only Google Drive is used to store the documents.

**Comment by rumus007** [comment]
@charlesyoung 
I have recently made changes in the staging site. If the document url's in the excel file are of google drive then it will create a downloadable link but for other hosted files (such as dropbox etc) user will have to provide proper download link.

Please check the changes in staging site.
cc @anjesh

**Comment by charlesyoung** [comment]
Thanks @rumus007 

I ran a test backend import and still get a PDF error as shown below as well as 'Could not process Google drive document' (file below). 

[backend_import_template.xlsx](https://github.com/NRGI/resourcecontracts.org/files/3886464/backend_import_template.xlsx)


![image](https://user-images.githubusercontent.com/13888372/69538798-c2207800-0f8b-11ea-977c-4b16cb6e6205.png)

**Comment by rumus007** [comment]
@charlesyoung 
I've recently made some changes in the staging site. Please try to upload the file again.
Here are some instructions on the adding the link in the excel file.
cc @anjesh 
![1](https://user-images.githubusercontent.com/51116139/69600778-01a59d80-103a-11ea-8a99-f5bf5547391e.png)

![2](https://user-images.githubusercontent.com/51116139/69600851-43cedf00-103a-11ea-9c6e-7a76d2230300.png)

**Comment by charlesyoung** [comment]
Thanks @rumus007 

Seems like your changes made a difference as its now working.

**Comment by rumus007** [comment]
@charlesyoung 
Should the changes be implemented in prod site?
And is the read me tab sufficient as mentioned in the sample excel file mentioned in:
https://github.com/NRGI/resourcecontracts.org/issues/1242#issuecomment-556908265

**Comment by charlesyoung** [comment]
Good point. Please implement on the Prod site. 

The readme seems fine.

**Comment by charlesyoung** [comment]
@rumus007 has this been implemented in Prod? What to close relevant tickets. Thanks

**Comment by rumus007** [comment]
@charlesyoung 
We are doing few last tests in staging site. I will notify as soon as it is deployed in production.
@anjesh

**Comment by charlesyoung** [comment]
@rumus007 has this been implemented in Prod? Want to close relevant tickets. I would like to run a bulk import next week for DRC documents.

**Comment by rumus007** [comment]
@charlesyoung 
This has been implemented in prod site
@anjesh

**Comment by charlesyoung** [comment]
Get below errors when importing the DRC xls. Signature year is captured and the resources are also correct. @rumus007 @anjesh 

[DRC import.xlsx](https://github.com/NRGI/resourcecontracts.org/files/3955755/DRC.import.xlsx)

![image](https://user-images.githubusercontent.com/13888372/70713419-a25cb400-1cee-11ea-94a1-455f06d09a48.png)

**Comment by rumus007** [comment]
@charlesyoung 
- The correct signature date format is yyyy-mm-dd the format in the attached excel file is yyyy-dd-mm. That caused the signature year validation error.

- To separate the resources double pipe operator should be used which is ||. In the excel file two capital I alphabet is used. This caused the resource validation error.

I have attached the excel file after the small changes are made please upload this file.
[DRC.import.xlsx](https://github.com/NRGI/resourcecontracts.org/files/3959087/DRC.import.xlsx)
 cc @anjesh

**Comment by charlesyoung** [comment]
Great, this was done by the Ministry staff so I will let them know about the formatting for future imports. It now works well. Thanks

**Comment by charlesyoung** [comment]
@rumus007 trust all is well. 

I'm trying to upload docs from Dropbox but get a 'Status: Failed (Pdf file is )' error. Below is an example link. 

https://www.dropbox.com/preview/Rep%20Congo%20(Brazza)/PSCs%20for%20Resourcecontracts/Congo%20PSCs%20Gazette%20versions/CPP%20Marine%20III_2006_scan.pdf?role=personal

You mentioned previously that for other hosted files (such as dropbox etc) users will have to provide a proper download link. What does that mean? Is the above link correct?

**Comment by rumus007** [comment]
@charlesyoung 

The link that you have provided doesn't seem to be publicly accessible. I am not able to view or download the pdf file when I click the link. In order to import the pdf, the link should be publicly accessible.

cc @anjesh

**Comment by charlesyoung** [comment]
@rumus007 any idea why I'm getting below import error? The xls, see below, seems fine. 

![image](https://user-images.githubusercontent.com/13888372/80971917-b9c34780-8e1d-11ea-8ba3-a5c9180f6569.png)

[R4D - Congo template import v2.xlsx](https://github.com/NRGI/resourcecontracts.org/files/4574980/R4D.-.Congo.template.import.v2.xlsx)

**Comment by rumus007** [comment]
@charlesyoung 
The PDF file link for the first three contracts is the same, hence the hash produced will be the same. That's why the "contract could not be saved" remark appears for 2nd and 3rd contracts.
The Document URL should be unique.
cc @anjesh

**Comment by charlesyoung** [comment]
Thanks @rumus007 

I should have noticed the duplication's.
