### ISSUE TITLE
Update search API with weightage for different elements

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#1244]
More details here 
[google docs](https://docs.google.com/document/d/1Rqtsm-B-T0yEhm5rAUjYVDQ_2pGiW7B03rR9LLJJHwg/edit#heading=h.9no24l1h6n2h) and https://rpubs.com/anjesh/508203

**Comment by charlesyoung** [comment]
@SamCCSI @jedm, ticket for further comms on the weighting.

**Comment by anjesh** [comment]
Further discussion will continue at #1096
