### ISSUE TITLE
Create a country RC site - Ivory Coast

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1249]
@anjesh I will get back to you with the country once selected.

**Comment by charlesyoung** [comment]
@anjesh please create a country site for the Ivory Coast. We will need a reusable background image like below. 

![Ivory Coast home page image](https://user-images.githubusercontent.com/13888372/82421165-ee233e80-9a80-11ea-96d0-945d29a33f6b.jpg)

https://www.levinsources.com/knowledge-centre/insights/lsm-approaches-to-managing-artisanal-and-small-scale-mining-time-for-proactive-engagement

**Comment by charlesyoung** [comment]
@anjesh can you pls give me a timeframe on completing this ticket.

**Comment by anjesh** [comment]
I think we should treat "Recent Documents" and doc grouping feature in a separate issue as mentioned https://github.com/NRGI/resourcecontracts.org/issues/1096#issuecomment-642568233. We will need these changes in other country sites as well. We might need to do some thinking/minor updates on country sites design as well.

**Comment by charlesyoung** [comment]
Thanks @man-git007

I've added the French language support? Which favicon should be used?

**Comment by charlesyoung** [comment]
Please move to Prod. Only change is to add the IC favicon. Thanks

**Comment by man-git007** [comment]
@charlesyoung The site has been moved to [production](https://ivorycoast.resourcecontracts.org/) .
We will add the fav icon by tomorrow. The fav icon should have initials `IC` or `CI`

cc @anjesh @nirvanalama

**Comment by charlesyoung** [comment]
Thanks

Please make the fav icon IC

**Comment by man-git007** [comment]
@charlesyoung Is this fav icon OK?

![Group 77](https://user-images.githubusercontent.com/23434972/85099846-41261800-b21e-11ea-8d05-a77b182aabbe.png)

**Comment by charlesyoung** [comment]
That's great thanks. I've uploaded the image.

**Comment by charlesyoung** [comment]
The IC country site now shows 0 contracts ..... This seems to be affecting all the country sites. 

![image](https://user-images.githubusercontent.com/13888372/87641709-c848ac00-c748-11ea-87de-90c66382128b.png)

**Comment by man-git007** [comment]
@charlesyoung We are working on it. Are there other country sites in staging server? So that we could test it on other staging country sites.

**Comment by charlesyoung** [comment]
https://staging.guinea.resourcecontracts.org
https://staging.zambia.resourcecontracts.org

**Comment by man-git007** [comment]
@charlesyoung The fixes have been deployed to staging server but the staging country sites are pointing to production API. This needs to be fixed.

**Comment by charlesyoung** [comment]
Let me know when I can test. Still shows zero.

**Comment by man-git007** [comment]
@charlesyoung The API issue has been fixed. Please check the staging country sites.

**Comment by charlesyoung** [comment]
Great, can you please deploy to the Prod country sites.

**Comment by man-git007** [comment]
@charlesyoung Deployed to live sites.

**Comment by charlesyoung** [comment]
Thanks

**Comment by charlesyoung** [comment]
@man-git007 I was just asked by the client to add password protection to the IC site for now. Can you please add this to the Prod site. Thanks

**Comment by charlesyoung** [comment]
@man-git007 will it be possible to add password protection to the IC site?

**Comment by man-git007** [comment]
@charlesyoung We are working on it. There seems to be an issue in staging deployment.

**Comment by charlesyoung** [comment]
We just need the password on the prod site and not on staging.

**Comment by man-git007** [comment]
@charlesyoung The authentication in the [IvoryCoast](https://ivorycoast.resourcecontracts.org/) country site has been implemented. I have forwarded a mail containing the credentials. 

cc @birendragurung

**Comment by charlesyoung** [comment]
Many thanks @man-git007

**Comment by man-git007** [comment]
@charlesyoung If this is all done, we can close this issue.

**Comment by charlesyoung** [comment]
I will close it for now but will request the removal of the password protection when the client gives the approval.

**Comment by charlesyoung** [comment]
@man-git007 we want to launch the Ivory Coast country site but the Guides link doesn't work. This seems to be a theme with all the country sites although in these cases none of the links work.

**Comment by man-git007** [comment]
@charlesyoung There is no guide page for IvoryCoast in the admin side. We need to add `guides` from admin panel

**Comment by charlesyoung** [comment]
Thanks. Can you please also add the missing pages to the country sites as it looks like all have been removed.

**Comment by man-git007** [comment]
@charlesyoung I have added the guides to the Ivory coast site.

**Comment by charlesyoung** [comment]
Thanks but why are the pages empty (we use the same text as the RC pages)? Also, why were all the country site pages deleted during the upgrade?

**Comment by man-git007** [comment]
@charlesyoung This might be due to using the same database for staging and production country site.

cc @anjesh

**Comment by charlesyoung** [comment]
I don't understand. How can we be using the same database for staging and production?

**Comment by man-git007** [comment]
@charlesyoung Can we close this ticket now?
