### ISSUE TITLE
Sorting bug

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1250]
Some users cannot sort columns like date (shown below)

![image](https://user-images.githubusercontent.com/13888372/69228003-80f32700-0b8b-11ea-9652-879d6aa537ef.png)

Tehtena Mebratu-Tsegaye (tm2675@columbia.edu) noted this issue.

**Comment by charlesyoung** [comment]
@anjesh please see below. 

![image](https://user-images.githubusercontent.com/13888372/69602300-c1392600-101f-11ea-9f80-a0ba1ae8fada.png)

**Comment by anjesh** [comment]
it is about font-not-found and doesn't affect the functionality in the page. there should have been other kind of errors related to javascript if there's a problem with the functionality.

**Comment by charlesyoung** [comment]
What else can we try. As you can see from below screenshot the dates aren't ordered correctly after a sort. 

![image](https://user-images.githubusercontent.com/13888372/69609969-6d383c80-1033-11ea-8506-6ff33e3541f2.png)

**Comment by anjesh** [comment]
Could you put us in touch with the user? We will do a quick skype and see if we could figure out something.

**Comment by anjesh** [comment]
error is found in the listing page when one goes from country page e.g.

https://resourcecontracts.org/countries/ao?order=asc&sortby=year

![image](https://user-images.githubusercontent.com/120488/70150295-e4c03880-16d1-11ea-9d3e-99db47882239.png)

**Comment by charlesyoung** [comment]
@anjesh have you had time to look at this issue?

**Comment by charlesyoung** [comment]
cc @bizaybsnt

**Comment by charlesyoung** [comment]
@anjesh have you had time to look at this issue?

cc @bizaybsnt

**Comment by man-git007** [comment]
@charlesyoung We are looking into this. The issue is in the api query and might take some time. We will work on it next week.

cc @anjesh

**Comment by man-git007** [comment]
@charlesyoung The sorting bug in the signature year has been fixed and deployed in live server.

cc @anjesh

**Comment by charlesyoung** [comment]
Many thanks
