### ISSUE TITLE
ResourceContracts support

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1255]
ResourceContracts support of 6 days.

**Comment by charlesyoung** [comment]
+ 1 day from the DRC ticket

Total = 7 days

**Comment by anjesh** [comment]
@charlesyoung https://github.com/NRGI/resourcecontracts.org/issues/1250 is not part of TOR. So 1 day of effort (fix/comms/deployment) will be part of this support. Please confirm.

**Comment by charlesyoung** [comment]
That's correct. 

Support sheet below to track time spent. 

https://docs.google.com/spreadsheets/d/1nl92slsiyccaq0wLLfAAfChaudCAxXFWJ0ZmptL2ntA/edit#gid=0

**Comment by anjesh** [comment]
1 day of work for https://github.com/NRGI/resourcecontracts.org/issues/1284
