### ISSUE TITLE
Associated documents without a main document

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1256]

**Comment by charlesyoung** [comment]
@anjesh I can understand that there might have been a problem between associated and main documents during the import from the 1st version of RC to the current version in 2015 but I'm not sure how that is possible post 2015. As you know you either have to select main or associated, there is no other way of adding a document. Below document that you highlighted was added this year. 

http://admin.resourcecontracts.org/contract/3190

![image](https://user-images.githubusercontent.com/13888372/69700690-b94ab600-10f3-11ea-9c68-1080bc82f8a2.png)

**Comment by anjesh** [comment]
Could it have been the issue with CSV import?

**Comment by charlesyoung** [comment]
I doubt that because most (94%) of the noted documents have been added by CCSI and from my understanding they have never used the CSV import. 

cc @SamCCSI

**Comment by SamCCSI** [comment]
Correct I don’t think CCSI has ever used the csv import.

**Comment by charlesyoung** [comment]
@anjesh not sure how to resolve this issue besides checking each document to check if its a main or supporting document. 

@SamCCSI I've added a document URL (the first 50 records) to below xls. Will it be possible for someone at CCSI to check if these are main or supporting OLC documents? 

[supporting-doc-without-main- doc.xlsx](https://github.com/NRGI/resourcecontracts.org/files/3901531/supporting-doc-without-main-.doc.xlsx)

**Comment by SamCCSI** [comment]
@charlesyoung what is the issue here, exactly? 

All OLC ones were entered in manually. One reason for some of the associated docs is that there is an anticipation of a main doc being added but that hasn't been done yet. 

Does having 'orphan' associated documents mess up the tech changes we are implementing?

**Comment by charlesyoung** [comment]
@SamCCSI how did you even add these documents seeing that you can only select a main or associated and if associated you have to select which document it relates to. 

@anjesh am I right that associated documents without a main document will not be shown in the new grouping display methodology?

**Comment by anjesh** [comment]
Yes, the orphan associated documents wouldn't appear in new grouped result.

It looks like these orphan are created after the main document got deleted. There's no error checking at the moment when you delete the document (whether main or associated). One thing we could do is list all the orphan associated documents and you could either update the associated document to include its main or convert that to main document.

**Comment by charlesyoung** [comment]
@anjesh can you please convert the 12 RC documents to main documents. 80% do seem like main documents and I will work on the remaining issue documents.

**Comment by anjesh** [comment]
Do you mean this 12 documents in the xlsx attached?

![image](https://user-images.githubusercontent.com/120488/70113378-080ec780-1681-11ea-9019-6f44857e1936.png)

**Comment by charlesyoung** [comment]
Yes

**Comment by SamCCSI** [comment]
> @SamCCSI how did you even add these documents seeing that you can only select a main or associated and if associated you have to select which document it relates to.

From memory, we may have uploaded the doc as a main doc, then edited it as an associated but left the doc blank? But that might be a guess. @charlesyoung

**Comment by charlesyoung** [comment]
@anjesh have you managed to convert the 12 RC documents to main documents?

**Comment by charlesyoung** [comment]
@SamCCSI, will it be possible to change these docs back to main docs otherwise it won't show on the newly designed grouping configuration. 

cc @anjesh

**Comment by SamCCSI** [comment]
> @SamCCSI, will it be possible to change these docs back to main docs otherwise it won't show on the newly designed grouping configuration.

Yes, we have someone working on this now. Thanks.

**Comment by charlesyoung** [comment]
@anjesh have you managed to convert the 12 RC documents to main documents?

**Comment by man-git007** [comment]
@charlesyoung The contracts have been updated to main documents in live server.

The updated document ids are 837, 2121, 2150, 2151, 2155, 2179, 4026, 4031, 4036, 4041, 4047, 4053

Please verify.

cc @anjesh

**Comment by charlesyoung** [comment]
Many thanks @man-git007 

I will keep this ticket open as a reminder for @SamCCSI that the noted 170 OLC docs need to be changed back to main documents.

**Comment by charlesyoung** [comment]
Ticket closed to remove from the Sprint 24 list but separate ticket created as a reminder. 

cc @SamCCSI
