### ISSUE TITLE
Problem with long annotation search results

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#1259]
**Problem:** when an annotation is relevant to a text search: (a) currently there is no part of it bolded (so we don’t know why it’s relevant); and (b) the excerpt is of the entire annotation. 
Example of crazily long annotation excerpt and no bolded term, in a search for “consult”:

![pasted image 0](https://user-images.githubusercontent.com/12913915/71491224-71f03c00-27fd-11ea-8607-ddfdcafef3f7.png)

**Suggested solution:** bold the term in the annotation and limit the excerpt to max 4 lines. 

To be discussed with @charlesyoung and @jedm

**Comment by SamCCSI** [comment]
@charlesyoung should this be resolved before closing issue #1096 ? Interested in your thoughts.

**Comment by man-git007** [comment]
@SamCCSI The long annotation text has been fixed and have set the character limit. It has been deployed on the staging site. Could you verify the changes?

**Comment by SamCCSI** [comment]
Thanks @man-git007 this looks great.

@charlesyoung note that the text field shows the text search result in bold but the annotation field result does not bold the result (circled in yellow). I think it would help users if the annotation search result term (here, "consult" or similar) were bolded. Would you agree for RC? If so, we can likely cover that as part of this Sprint 25.  

@jedm -- does that sound good to you?

cc @anjesh 

![image](https://user-images.githubusercontent.com/12913915/78028426-043c3a80-732d-11ea-94f5-cd1bb69afc22.png)

**Comment by charlesyoung** [comment]
Looks very useful. Will be good if this could be rolled out to RC in S25. Thanks @SamCCSI

**Comment by SamCCSI** [comment]
Thanks @charlesyoung 

@anjesh will adding this change to bold the term in the annotation search results have any budget implications?

**Comment by anjesh** [comment]
@SamCCSI making bold is not much of a big issue. @man-git007 will take care of that.

**Comment by SamCCSI** [comment]
Thanks @anjesh i can check once bold change made and then we'll be ready to deploy on live site

**Comment by man-git007** [comment]
@SamCCSI The keyword found in the annotation text has been made bold in the staging server. Verify it and if all OK we will deploy it in live server.

**Comment by SamCCSI** [comment]
working nicely. please deploy on live sites @man-git007 !

**Comment by man-git007** [comment]
@SamCCSI @charlesyoung  Deployed on live site and this issue is closed

cc @anjesh @bizaybsnt

**Comment by SamCCSI** [comment]
text search terms that return results in annotation field are still not being bolded on live site. (text search terms that return results in text field are bolded, though). Example: https://www.openlandcontracts.org/search/group?q=consent
![image](https://user-images.githubusercontent.com/12913915/79760838-9f9e4b00-82ee-11ea-8078-a555dd847761.png)

@man-git007 can you please address? cc @anjesh Thanks both.

**Comment by man-git007** [comment]
@SamCCSI 

The search highlight seems working. This could be due to the browser. Could you please provide us the browser info you are using.

![Screenshot from 2020-05-05 15-37-13](https://user-images.githubusercontent.com/23434972/81054416-84cef780-8ee6-11ea-8b90-f8b5f16500b3.png)

**Comment by SamCCSI** [comment]
@man-git007 <https://github.com/man-git007> It works on Safari.

It does not show on Google chrome Version 81.0.4044.129 (Official Build)
(64-bit)


>

**Comment by man-git007** [comment]
@SamCCSI I have made changes and deployed in the staging server. Could you please check.

**Comment by SamCCSI** [comment]
@man-git007 it works on staging

**Comment by man-git007** [comment]
@SamCCSI It has been deployed in live server. Please check.

**Comment by SamCCSI** [comment]
@man-git007 it works on live site. thank you!
