### ISSUE TITLE
Upgrade PostgresSql database from v9.4 to v9.5

### ISSUE THREAD

**Issue by adinuca** [NRGI/resourcecontracts.org#1263]
## Why
PostgresSql database v 9.4 will no longer be supported by AWS starting February 15th, 2020

## What 
- [x] resource-contracts database is upgraded to v9.5

## Notes
Database is used by resourcecontracts.org and admin.resourcecontracts.org

**Comment by charlesyoung** [comment]
Thanks @adinuca 

Has this been done or is it still scheduled?

**Comment by candrei** [comment]
Hi @charlesyoung the upgrade will take place tonight, sorry for the delay.

**Comment by candrei** [comment]
The maintenance was completed successfully, we are now running PostgresSQL v9.5.19 for RC.

**Comment by charlesyoung** [comment]
Many thanks

cc @anjesh
