### ISSUE TITLE
Main documents

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1264]
170 OLC docs need to be changed back to main documents.

cc @SamCCSI

**Comment by charlesyoung** [comment]
@SamCCSI just a reminder now that the grouping functionality has been deployed.

**Comment by SolinaCCSI** [comment]
@charlesyoung Hi Charles, I was under the impression these documents got associated /or changed to main doc a few weeks ago. I will work on this now. Can you please clarify where I can find the list of 170 documents that need to be reviewed?

**Comment by charlesyoung** [comment]
Hi @SolinaCCSI it could have been done, I was just checking that it was done because these docs wont show in the new grouping feature. See the xls below. I had started to create the doc URLs to make it easier to find but haven't done it for all. Its just adding the OCID (3190) to the RC admin URL (admin.resourcecontracts.org/contract/3190). 

[supporting-doc-without-main-.doc.xlsx](https://github.com/NRGI/resourcecontracts.org/files/4591276/supporting-doc-without-main-.doc.xlsx)

**Comment by SolinaCCSI** [comment]
Got it, thank you @charlesyoung. @michaelCCSI and I are working on this and will let you know when the 170 are updated. Thanks so much!

@SamCCSI
