### ISSUE TITLE
DRAFT: Upgrading Guide (text) Pages - design, consistency, versioning

### ISSUE THREAD

**Issue by jedm** [NRGI/resourcecontracts.org#1270]
_Issue still being drafted by Jed/CCSI_

Research on Open Land Contracts suggested users will benefit from simpler, clearer "How-To" instructions and more prominent links to How-To/Guide pages. Current About and Guide pages have several years of content and training "modules" by CCSI. We would like to update the look and feel of the Guides page and all text pages, to make them easier to use, find and manage.

https://openlandcontracts.org/guides

_[DRAFT]_ Changes to include: _[DRAFT]_

1. Main Guides page to be redesigned in style of [Nirvana's recent mockup](https://user-images.githubusercontent.com/57661914/71797213-2cd9ce80-3075-11ea-8a1c-de63842caa17.png).

2. Redesigned Main Guides page will incorporate stylesheet/style tags so CCSI admins can maintain consistent look and feel of Nirvana's layout and all fonts, margins, etc.

3. ALL text "Pages" to be updated with consistent layout, fonts, margins, etc.

4. Redesigned Main Guides page will also allow admins to upload jpgs to change content while maintaining layout designed by Nirvana.

5. The Main Guides page will have "versioning" function so that admins can Undo edits and recover older versions of page (up to a certain number of changes or date history).

6. YI designers to also create a downloadable PDF version of redesigned Main Guides page. This PDF will be available for download as part of final layout/design of Main Guides page.

7. GLOBAL CHANGE: Header area of site will have new prompt/link directly to Main Guides page.
— text of prompt/link TBD
— delete the word "Beta" from header
— see sample jpg attached

![Screen Shot 2020-01-27 at 10 25 49 AM](https://user-images.githubusercontent.com/2153664/74183303-b3ed0a00-4c12-11ea-8bc2-cce8327753cd.jpg)

Related issues: #1225 , #22 , #1036

**Comment by SamCCSI** [comment]
Re point 7: after internal discussions, @nirvanalama could we please also see a mock up of having the link on the top **right** hand corner of the page? (There is concern that it will look too messy on/under logo on the top left of page).

More generally: Nirvana's mock up really is more of a "how to use the site" and we will then, if i'm not mistaken, also incorporate links to guidance docs underneath that. We therefore think that the link should say "How to use this site" or similar -- not "Guides". We think a first time user will be more likely to click on "how to..."

The question then becomes what do we call this page if we still have page links down the bottom of the site. 

Interested in your thoughts @jedm 

cc @JesseCCSI

**Comment by SamCCSI** [comment]
(removed ref to @nirvanalama given that:
> Issue still being drafted by Jed/CCSI

**Comment by jedm** [comment]
@SamCCSI and @nirvanalama

These are good questions. Please advise if YI can proceed with the basic work while CCSI and I discuss more for a final decision. 

Placement and wording are more cosmetic questions, so I am hoping we can go ahead with YI building the new Guide/How To pages and functions while we discuss these final display questions.

Please confirm.

Thanks!

**Comment by SamCCSI** [comment]
Fine by me. @nirvanalama / @anjesh are you ok to begin?
> Please advise if YI can proceed with the basic work while CCSI and I discuss more for a final decision.

**Comment by man-git007** [comment]
@SamCCSI @jedm Should we consider [Nirvana's recent mockup](https://user-images.githubusercontent.com/57661914/71797213-2cd9ce80-3075-11ea-8a1c-de63842caa17.png) final? As @jedm has mentioned the placement and wording can be changed in the future. Also, this guide page is related to the #1225 issue and we will be needing further discussion in that 1225 issue.

So, for now, I need confirmation on whether the layout is OK for the guide page. Layout in a sense the placing of images and content. So that would work on the designing of the guide page.

**Comment by jedm** [comment]
@man-git007,  I will provide an updated wireframe for the main guide page (to replace this page) by Friday. It will be based on the final 3 rows of Nirvana's recent mockup. Thank you very much.

**Comment by man-git007** [comment]
@jedm If you have the wireframe, we are ready to work on it. Also, I didn't get you on this `final 3 rows of Nirvana's recent mockup`.

**Comment by man-git007** [comment]
@jedm Have implemented the versioning of the pages in the [staging site](https://staging.resourcecontracts.org/admin). Please go through it.

cc @anjesh @charlesyoung

**Comment by man-git007** [comment]
@jedm and @charlesyoung 

The **workflow** of the page version is like this.

1. Upon creating a new page, the version of that page is V0 by default.
2. When the user needs to create a new version of that page then the user needs to edit the page and save as a new version. 
3. Users can edit delete the pages and its version as well.
4. Users cannot delete the page if that page is published in the live site.

Please provide **feedback** if any. I have attached a few **screenshots** of the workflow of the page versioning.
![Screenshot from 2020-06-18 14-38-20](https://user-images.githubusercontent.com/23434972/85000142-c0a9dd80-b171-11ea-9d0d-495d56730c4d.png)
![Screenshot from 2020-06-18 14-39-20](https://user-images.githubusercontent.com/23434972/85000151-c43d6480-b171-11ea-999d-ecc19f9f5bc5.png)
![Screenshot from 2020-06-18 14-39-34](https://user-images.githubusercontent.com/23434972/85000171-c8698200-b171-11ea-894d-f2b2a831a2a9.png)
![Screenshot from 2020-06-18 14-39-42](https://user-images.githubusercontent.com/23434972/85000184-cbfd0900-b171-11ea-8408-da5697e6ff69.png)

**If all OK we will deploy this in the production server.**

cc @anjesh @birendragurung

**Comment by charlesyoung** [comment]
@man-git007 I don't see the 'Add New page' button. 

![image](https://user-images.githubusercontent.com/13888372/85847042-13554c00-b7a7-11ea-817e-dc4fae98f65d.png)

**Comment by man-git007** [comment]
@charlesyoung The `Add New Page` button is there.

![Screenshot from 2020-06-26 16-07-55](https://user-images.githubusercontent.com/23434972/85847528-427bb580-b7c7-11ea-808e-3f437d81a397.png)

**Comment by charlesyoung** [comment]
Not for me. Same issue using Incognito. 

![image](https://user-images.githubusercontent.com/13888372/85847637-0dac3600-b7a8-11ea-829e-365300980e2d.png)

**Comment by man-git007** [comment]
@charlesyoung Might be the issue of browser. Could you please send us the browser version.

**Comment by charlesyoung** [comment]
Not sure if its a browser issue. I'm using Chrome version 83.0.4103.116 (64-bit).

**Comment by man-git007** [comment]
@charlesyoung The `Add New Page` button is shown to admin user only.

**Comment by charlesyoung** [comment]
I am an administrator

![image](https://user-images.githubusercontent.com/13888372/85848884-40572e00-b7aa-11ea-9078-20e3f3764d39.png)

**Comment by charlesyoung** [comment]
From @man-git007 
@charlesyoung We need to preset these routes in code itself. Can you provide us the new pages list?

**Comment by charlesyoung** [comment]
I don't understand. Do you still have to update the code for new pages so its not a dynamic process.

**Comment by man-git007** [comment]
@charlesyoung No, we don't need to update the code for the new pages but need to point the page to a specific route. Like https://staging.resourcecontracts.org/research-and-analysis, the  `research-and-analysis` needs to be pointed to research and analysis page

**Comment by charlesyoung** [comment]
OK

I however get a 404 error when clicking https://staging.resourcecontracts.org/research-and-analysis

I'm assuming that the new page should be added to the footer without the route.

**Comment by charlesyoung** [comment]
@man-git007 just checking the status of this ticket.

**Comment by man-git007** [comment]
@charlesyoung I am confused with the comment `I'm assuming that the new page should be added to the footer without the route.`
Are you suggesting to add `research-and-analysis` link in the footer as well? As for the new page, we can add/create a new page from the admin side but need to manually add the route `https://staging.resourcecontracts.org/research-and-analysis` in the code. Therefore, if there are other new pages as well, can you provide us the page name, so that we can add the routes for those pages as well.

**Comment by charlesyoung** [comment]
Surely the 'Add new page' function should add the new page text i.e. Research & Analysis to the footer otherwise whats the point. I understand that the route needs to be added manually.

**Comment by man-git007** [comment]
@charlesyoung I got the point. If any new page has been added via the admin site, we need to add a link to the footer or somewhere in the site which will be done manually in code. Now regarding this ticket, the functionality for page versioning has more or less completed however this ticket also includes the guide page design. I suggest this ticket be deployed on the live site and closed. Regarding the designing of the guide page and other pages to be moved to a new ticket,

cc @SamCCSI @jedm @anjesh

**Comment by charlesyoung** [comment]
Thanks @man-git007 

Sprint 25 is managed by CCSI so I will ask @SamCCSI and @jedm to comment.

**Comment by jedm** [comment]
Agree with @man-git007 suggestion to complete the add page portion and move completion of Guide page(s) and admin to separate ticket.

**Comment by man-git007** [comment]
@charlesyoung @jedm So we will deploy this functionality to live site by today.

cc @anjesh @birendragurung

**Comment by charlesyoung** [comment]
Thanks @man-git007 

Please close this ticket when done and create a new guide page design ticket under Sprint 25.

**Comment by man-git007** [comment]
Closing this ticket and creating a new ticket for Guide page design

cc @charlesyoung @SamCCSI @jedm @anjesh

**Comment by SamCCSI** [comment]
> 7. GLOBAL CHANGE: Header area of site will have new prompt/link directly to Main Guides page.
>    — text of prompt/link TBD
>    — delete the word "Beta" from header
>    — see sample jpg attached
> 
> ![Screen Shot 2020-01-27 at 10 25 49 AM](https://user-images.githubusercontent.com/2153664/74183303-b3ed0a00-4c12-11ea-8bc2-cce8327753cd.jpg)
 
Reopening this page, as the OLC logo still has "Beta". Can this please be removed? @nirvanalama @man-git007

**Comment by man-git007** [comment]
@SamCCSI beta tag has been removed from the live site. Please verify, if anything missing please let us know

**Comment by SamCCSI** [comment]
Working. Thank you!
