### ISSUE TITLE
Searching by annotation state

### ISSUE THREAD

**Issue by MichaelCCSI** [NRGI/resourcecontracts.org#1271]
## What : How can we sort for contracts according to their annotation status? As stated above, we want to find contracts whose annotation status is marked as "draft". 

@man-git007 @charlesyoung

**Comment by charlesyoung** [comment]
@MichaelCCSI is this what you are looking for from the backend? 

![image](https://user-images.githubusercontent.com/13888372/80872531-c37c6c00-8cb2-11ea-88bf-22a8b528ec35.png)

**Comment by charlesyoung** [comment]
@MichaelCCSI can we close this ticket?

**Comment by MichaelCCSI** [comment]
@charlesyoung Yes, the ticket can be closed. Thank you.
