### ISSUE TITLE
setup staging.openlandcontracts.org

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#1273]
## Why

we only have staging.resourcecontracts.org during development and testing. But there are changes specific to OLC and couldn't test in RC.

## What

- [x] staging.openlandcontracts.org works

## Notes

Not sure what is needed for staging.olc to work. It looks like the domain is pointed to the same server as RC.

cc @charlesyoung @man-git007

**Comment by adinuca** [comment]
Hi @anjesh , I think it is enough to add the domain in `nginx_olx_com` file.

**Comment by adinuca** [comment]
You can also try specifying staging.openlandcontracts.org in SERVER_NAME in `init.sh`
```
#olc
export SERVER_NAME="www.openlandcontracts.org openlandcontracts.org *.openlandcontracts.org "
export CATEGORY=olc
export TRACKING_ID=${OLC_TRACKING_ID}
export GTM_ID=${OLC_GTM_ID}
export DB_DATABASE=${OLC_DB_DATABASE}
export CONTACT_MAIL=${OLC_CONTACT_MAIL}
export COUNTRY=''

envsubst '$SERVER_NAME $CATEGORY'< ./nginx_subsite.template > /etc/nginx/sites-enabled/olc
envsubst < ./env.template > /var/www/olc/.env
```

**Comment by adinuca** [comment]
@anjesh , I removed my previous 2 comments. The load balancer was not set up for this subdomain. It should be working now.

**Comment by anjesh** [comment]
Thanks @adinuca. It's working.
