### ISSUE TITLE
Adding resources

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1274]
Is there a simple way to add missing resources. 

I'm doing a DRC import and 'coltan' is missing from the list.  

cc @anjesh

**Comment by charlesyoung** [comment]
@anjesh how do we add missing resources?

**Comment by anjesh** [comment]
@man-git007 could you have a look here?

**Comment by charlesyoung** [comment]
@man-git007 any feedback?

**Comment by charlesyoung** [comment]
@man-git007 any feedback?

**Comment by man-git007** [comment]
@charlesyoung Sorry for the late reply. I think we need to update the code list on the admin side itself. Let me check and get to you by tomorrow

**Comment by charlesyoung** [comment]
Thanks @man-git007 

Does it not just pull from the Google sheet code list? 

https://docs.google.com/spreadsheets/d/1tRRcib0VNynipkk83m4Be1vRaSslCKHzoIxmmC1oPLQ/edit#gid=215354368

**Comment by man-git007** [comment]
@charlesyoung I have updated the code list in the admin site. The resource 'coltan' has been added to the resource field of contract form. This is deployed in the staging server.

**Comment by charlesyoung** [comment]
Thanks @man-git007 

Please note that its Coltan an not Colton as added to the staging server. 

![image](https://user-images.githubusercontent.com/13888372/81399656-aa990e00-912b-11ea-9bf7-6e419b1b6ac1.png)

Isn't there a more sustainable way of adding new resources like updating the Google sheet?

**Comment by man-git007** [comment]
@charlesyoung Noted and done.

**Comment by charlesyoung** [comment]
Thanks, please move to Prod.

**Comment by man-git007** [comment]
@charlesyoung Moved to production

cc @anjesh
