### ISSUE TITLE
Bugs editing size and shape of existing annotation markers

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#1279]
## Why
Annotators sometimes enter in annotation markers in sizes and shapes that are messy and obscure text. We need to be able to easily resize them. Right now we can't: if you try to resize an existing marker, it reverts back to original size.

## What
Fix the above

## Notes
There is a work around: draw a second annotation marker in the correct shape and then choose same annotation category, then delete the original one. But this takes time and it would be great to be able to resize markers as was initially intended.

Here's an example: 1 - bad marker; 2 - changed shape; 3 - says it saves but it actually reverts to original shape
![Screenshot 2020-04-03 16 31 12](https://user-images.githubusercontent.com/12913915/78402518-b2afdc00-75c8-11ea-9dd3-c64f7b03f37d.png)
![Screenshot 2020-04-03 16 31 42](https://user-images.githubusercontent.com/12913915/78402522-b5aacc80-75c8-11ea-9d2c-a9dc42afb064.png)
![Screenshot 2020-04-03 16 31 50](https://user-images.githubusercontent.com/12913915/78402532-b8a5bd00-75c8-11ea-830c-9bdee194e299.png)

@anjesh could your team investigate how long this would take to fix so that we can consider whether to address? Thanks very much

**Comment by anjesh** [comment]
after our discussion in team, we think this might take around a day work to investigate the issue in details and fix this?

**Comment by SamCCSI** [comment]
Many thanks Anjesh. Let's put this on hold for now and see how days worked
on other task matches up to the quote/estimate.

**Comment by bizaybsnt** [comment]
@SamCCSI 
We have fixed the bug while resizing the annotation markers shape. Please check it on the staging site (https://admin-staging.resourcecontracts.org/ ). 
We will deploy it on the production once it is confirmed.

cc: @anjesh @man-git007

**Comment by SamCCSI** [comment]
Confirming this works nicely now. Ready to deploy, thank you!

**Comment by man-git007** [comment]
@SamCCSI The bug has been fixed and deployed in the live server

cc @anjesh @bizaybsnt

**Comment by SamCCSI** [comment]
Works great on live site thanks @man-git007

**Comment by charlesyoung** [comment]
@SamCCSI can we close this ticket?
