### ISSUE TITLE
Contract view: Add download option for OCR-ed text

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#128]
We already have a download option for the PDF. 

However we also need **a download option for the OCR-ed text** for each contract where the OCR has been done. 

As a user (especially from a low bandwidth community) I would like to access contracts in text format as these are often filling up less space.

**Comment by anderspeders** [comment]
This should be next to the PDF-option: 

Name of PDF download: "Original contract in PDF-format"
OCR contract: "Contract in machine readable format" (is this in txt?)

**Comment by anjesh** [comment]
The option to download the contract text (in docx whether ocr-ed or not) is now available and working in Linux. But i am seeing some problem in docx file in Mac due to some unknown characters. Moving to sprint 6 for bug fix for docx in Mac and probably windows.

**Comment by anderspeders** [comment]
Excellent, thanks.

**Comment by anjesh** [comment]
Fixed.
