### ISSUE TITLE
Website speed

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1284]
@anjesh something has changed the past month because the site has become very slow. So as an example I've got a fast fibre connection at home but most times for instance it displays the doc text version rather than the PDF because of slow bandwidth. Can you run a Pagespeed test your side to see if you get similar results? 

[Pagespeed ](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.resourcecontracts.org%2F)gives a very low performance score.

**Comment by anjesh** [comment]
@man-git007 @sweta-shrestha Could you please see if there are any obvious issues that are causing the slow in the site?

**Comment by charlesyoung** [comment]
@man-git007  @sweta-shrestha can you please take a look at this? I have now had 3 RC users contact me and complain about the slow access speed. Pagespeed still shows a very low performance score.

**Comment by sweta-shrestha** [comment]
@charlesyoung Regarding the performance, we have optimized the images in staging server and also maintained css and images which has increased the performance score. This change in score might get better in production server.

Also, we are working on other possibilities to speedup the site.

**Comment by charlesyoung** [comment]
Thanks @sweta-shrestha 

Improving the sites performance will be important.

**Comment by charlesyoung** [comment]
@sweta-shrestha any further feedback on the performance issues?

**Comment by sweta-shrestha** [comment]
@charlesyoung We have optimised the images on the production site as well as worked on the critical css which has increased the performance score.

Also, certain factors on server can also help to speed up the website. I would suggest you to enable compression on the server side.

**Comment by charlesyoung** [comment]
Thanks. The performance seems to have improved. 

How, where do I enable compression on the server side?

cc @adinuca

**Comment by charlesyoung** [comment]
@sweta-shrestha the site still seems sluggish and I don't think its an image problem because none of the images have changed and the performance was find a couple of months ago. It has to be related to the new code that has been added.

**Comment by man-git007** [comment]
@charlesyoung We have enabled gzip in server and speed rating has significantly increased. The site should now perform smoothly. 
![Screenshot from 2020-04-30 13-19-17](https://user-images.githubusercontent.com/23434972/80684335-3e902780-8ae5-11ea-8acf-03177d243a42.png)

**cc** @sweta-shrestha

**Comment by charlesyoung** [comment]
Great, many thanks!!

**Comment by charlesyoung** [comment]
@anjesh I have been running pagespeed in the desktop view.
