### ISSUE TITLE
Highlight and zoom the annotation in the clip's document view page 

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#1289]
## Why

Currently when you clip the annotation and go to clips page and view the document containing that clipped annotation, the document doesn't show the annotated box, confusing the user where to look for that annotations. The series of screenshots show the problem.

![image](https://user-images.githubusercontent.com/120488/80699311-786c2880-8afb-11ea-9278-6bfb27c3a71a.png)

![image](https://user-images.githubusercontent.com/120488/80699335-83bf5400-8afb-11ea-9231-6fcf3be14cd1.png)

![image](https://user-images.githubusercontent.com/120488/80699358-8d48bc00-8afb-11ea-9492-42f04c46f143.png)

## What

- [x] show the box where annotation was created in 
- [x] zoom/scroll the page with focus at the point where annotation box is present
 
## Notes

cc @charlesyoung

**Comment by charlesyoung** [comment]
@man-git007 no stress but just checking if you have started working on this ticket.

**Comment by charlesyoung** [comment]
@anjesh just checking if you have started working on this ticket. If not then when will you start with the development?

**Comment by man-git007** [comment]
@charlesyoung We are working on this ticket

**Comment by charlesyoung** [comment]
Thanks @man-git007 

@anjesh can we however please first look at #1249 first?

**Comment by charlesyoung** [comment]
It works for some like YIPL-Mturk-Test-2, Company-Company Contract, 2020 and crashes (404) on others like ETAP, YNG, Concession Permis Araifa - Tunisia, 2013. 

![image](https://user-images.githubusercontent.com/13888372/87536136-e48d1000-c698-11ea-8c7e-dd1921c8dc37.png)

Also the documents aren't the same. Look at below popup window document from the Clips page compared to the original document. 

![image](https://user-images.githubusercontent.com/13888372/87536697-cb389380-c699-11ea-9a0a-6a5548dbbad6.png)

**Comment by birendragurung** [comment]
@charlesyoung I checked from admin panel, seems like the documents were not saved properly and also pdf was not found for these contracts in admin panel too.

@man-git007

**Comment by birendragurung** [comment]
> Also the documents aren't the same. Look at below popup window document from the Clips page compared to the original document.

This has been fixed. Please go through #1289 and #1290 and let us know if we are ready for deploying these changes.

**Comment by charlesyoung** [comment]
I added a new contract on staging. 

https://staging.resourcecontracts.org/contract/ocds-591adf-8233962448/view#/pdf/page/1/annotation/25871

I cannot test the zoom feature because I get below error when clicking on the View Clause link. 

![image](https://user-images.githubusercontent.com/13888372/87669652-a7934d00-c76e-11ea-8d53-d30b810cd88d.png)

**Comment by birendragurung** [comment]
@charlesyoung The problem in popup view has been resolved.

**Comment by charlesyoung** [comment]
OK I will test.

**Comment by charlesyoung** [comment]
Please deploy to the RC production site.

**Comment by birendragurung** [comment]
@charlesyoung This has been deployed to production.

cc: @man-git007
