### ISSUE TITLE
Add a new URL column in the clips download file

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#1290]
- [x] "annotation page" link is added as a new column in the clips download page. Note the highlighted column is to be added in the XLS file

![image](https://user-images.githubusercontent.com/120488/80705446-2e3c7480-8b06-11ea-9bea-546f0b1f9e7f.png)

The download is available in the clips page after adding clips as shown below.

![image](https://user-images.githubusercontent.com/120488/80705250-d3a31880-8b05-11ea-949e-84566b59be9e.png)

**Comment by charlesyoung** [comment]
We want to add a column in the xls export that notes the relevant page annotation URL for reference and sharing.

**Comment by charlesyoung** [comment]
@anjesh no stress but just checking if you have started working on this ticket.

**Comment by man-git007** [comment]
@charlesyoung We have started working on this ticket

**Comment by man-git007** [comment]
@charlesyoung We have deployed this in [staging](https://staging.resourcecontracts.org/clip) server. Please verify it and if all OK we will deploy to live server.

**Comment by charlesyoung** [comment]
Thanks @man-git007 

Couple points. 
1. Please hyperlink the URL in the xls
![image](https://user-images.githubusercontent.com/13888372/84114216-43bd8c00-aa2c-11ea-9077-ef6e488252f0.png)
2. Not a crisis but can you make the xls column names bold
3. This is linked to #1289 I hope but will the annotation box be shown when opening a link in the URL?

**Comment by man-git007** [comment]
@charlesyoung We have made the changes you suggested. Please verify. If all OK we will deploy it to production

**Comment by charlesyoung** [comment]
Thanks. Just a small update please. Can you make the annotation text URL blue so that the user sees it as a standard hyperlink. 

Also will #1289 deal will the annotation box shown when clicking on the annotation text URL?

**Comment by man-git007** [comment]
@charlesyoung The update you provided have been implemented in staging. We are working on [#1289](https://github.com/NRGI/resourcecontracts.org/issues/1289) issue. For now, it will just link to the page.

**Comment by charlesyoung** [comment]
Thanks, looks good. 

Lets keep this on staging until #1289 has also been completed so that I can test the whole process.

**Comment by man-git007** [comment]
@charlesyoung Seems logical. We will update you as soon as we have completed the #1289 issue

cc @anjesh

**Comment by man-git007** [comment]
@charlesyoung We have implemented the changes and deployed in staging. Issue #1289  also have been incorporated. Could you please verify

cc @birendragurung

**Comment by charlesyoung** [comment]
OK great. Lets park this for now. 

I'm chatting with @anjesh about adding more on this ticket.

**Comment by charlesyoung** [comment]
Some additions. 

Additional columns need to be include in the Clipping spreadsheet export with existing column names also needing to be changed. 

Clipping spreadsheet export columns:
Document > Unchanged
Country	 > Unchanged
New column > Resource
Year > Unchanged
Annotation Category > Key Clause
New column > View Clause
Text > Clause Summary

Clipping web page columns:
Document > Unchanged
Category > Key Clause
Text > Clause Summary
Country > Unchanged
Resource > Unchanged
Year > Unchanged
View > View Clause

The column names should be in the same order for both the Clipping page and spreadsheet export. The order should be as follows. 
Document
Year
Key Clause
Clause Summary
Country
Resource
View Clause

**Comment by man-git007** [comment]
@charlesyoung OK we will start working on it.

**Comment by man-git007** [comment]
@charlesyoung We have implemented the changes you have suggested and deployed in the staging site. Please verify and if anything missing please let us know.

cc @birendragurung

**Comment by charlesyoung** [comment]
OK I will test. Can you however look at why the clips are not shown by default. See below, there are 3 existing clips but its only shown when clicking on the clips icon. The number of clips, if any, should be shown by default to the user. 

![image](https://user-images.githubusercontent.com/13888372/87044039-46abc800-c1f6-11ea-80e6-9d378b08e201.png)

![image](https://user-images.githubusercontent.com/13888372/87044067-51fef380-c1f6-11ea-8a8b-7894f3d98436.png)

**Comment by charlesyoung** [comment]
Can we try get the resources on the same line? Also the View Clause column has no links to click on.  

![image](https://user-images.githubusercontent.com/13888372/87045408-24b34500-c1f8-11ea-8c14-1fb1568023dc.png)

**Comment by birendragurung** [comment]
@charlesyoung We have implemented above mentioned changes on staging server. Please verify and let us know if any thing needs to be improved. 

cc @man-git007

**Comment by charlesyoung** [comment]
Thanks @birendragurung 

I however don't see the changes. Seems to be a caching issue again even in an Incognito window.

**Comment by birendragurung** [comment]
@charlesyoung Please verify the recent changes and let us know if anything is missing.

cc: @man-git007

**Comment by charlesyoung** [comment]
Thanks @birendragurung

The resource info looks good but why is there no view clause info? 

![image](https://user-images.githubusercontent.com/13888372/87308783-0745ea00-c51c-11ea-9704-30f0f60d8604.png)

The info is in the xls but not on the site. 

![image](https://user-images.githubusercontent.com/13888372/87308858-20e73180-c51c-11ea-90e0-fac131a67c70.png)

**Comment by birendragurung** [comment]
@charlesyoung Is it missing on Incognito too? I found it visible on both general and incognito mode. Might be the cache issue here.

**Comment by charlesyoung** [comment]
Not sure whats going on with my Chrome. I can now see it in incognito mode but clicking on the view clause causes a crash.

**Comment by birendragurung** [comment]
@charlesyoung Do you mean the chrome crashes or is just the page?

**Comment by charlesyoung** [comment]
I cannot even test at the moment, below just turns. 

![image](https://user-images.githubusercontent.com/13888372/87405642-01a1e000-c5c0-11ea-90b5-ddbee699e0ef.png)

This is my speedtest results, there should be no speed issue. 

![image](https://user-images.githubusercontent.com/13888372/87405739-21d19f00-c5c0-11ea-9e8f-58f77750be68.png)

This is from pagespeed. 

![image](https://user-images.githubusercontent.com/13888372/87405800-344bd880-c5c0-11ea-8d71-d339cbbad66d.png)

cc @man-git007

**Comment by birendragurung** [comment]
@charlesyoung We have fixed the issues. Please verify changes and let us know if we're ready to go for production deployment

cc @man-git007

**Comment by charlesyoung** [comment]
Thanks @birendragurung, looks good. 

Lets however deploy this ticket when #1289 has also been developed and tested.

**Comment by bezunakarmi** [comment]
@charlesyoung We have already worked on ticket #1289 along with this ticket and deployed to staging server. Please proceed with testing and verification and let us know if anything can be improved. 

cc @man-git007

**Comment by birendragurung** [comment]
@charlesyoung We have already worked on ticket #1289 along with this ticket and deployed to staging server. Please proceed with testing and verification and let us know if anything can be improved and deploy on production.

cc @man-git007

**Comment by charlesyoung** [comment]
@birendragurung the only comment is change the xls name from clipped_annotation_DATE to Clipped clauses DATE. Do we need the underscores in the file name?

**Comment by birendragurung** [comment]
@charlesyoung The download file name has been changed. Please verify and let us know if we're ready to go for deployment. 

cc @man-git007

**Comment by charlesyoung** [comment]
OK thanks. Lets only deploy to prod once #1289 and #1304 has also been completed.

**Comment by charlesyoung** [comment]
Also please apply the file name changes to the zip file to keep to a standard. 

1. Should be 'Clipped clauses DATE' (xls)
2. Should be 'Clipped clauses DATE' (PDF)
3. Should be 'Clause contract pages' (PDF) 

![image](https://user-images.githubusercontent.com/13888372/87669996-48820800-c76f-11ea-9569-38a11b8b8906.png)

**Comment by birendragurung** [comment]
@charlesyoung The changes have been made according to your request. Please verify recent changes on staging server and let us know for any improvements.

cc: @man-git007

**Comment by charlesyoung** [comment]
Thanks. Can we also change the zip file name. The test I did created a 'pdf-1595403888' file name which doesn't make any sense.

**Comment by birendragurung** [comment]
@charlesyoung Can you suggest any proper name for the zip file? Maybe we could use clipped clauses.zip if it's appropriate.

**Comment by charlesyoung** [comment]
Lets use the standard used for the xls, 'Clipped clauses [date].zip'

**Comment by charlesyoung** [comment]
Once the zip file name has been changed please deploy to the RC production site.

**Comment by birendragurung** [comment]
@charlesyoung The zip file name looks as follows.

![Screenshot from 2020-07-24 11-31-43](https://user-images.githubusercontent.com/13505748/88363969-4e946c00-cda1-11ea-97c3-24bf8a0acd86.png)

**Comment by charlesyoung** [comment]
Thanks, why however do we have the 159... number added? What does that mean? Can we not just have the name and date?

**Comment by birendragurung** [comment]
@charlesyoung We need to distinguish each files uniquely.

**Comment by charlesyoung** [comment]
I dont understand, the date adds to the unique file name. It should be the same as the xls download that only has the name and date.

**Comment by birendragurung** [comment]
@charlesyoung Let's for instance consider two users have requested for the zip file download. In such case, the number will distinguish the files created for each user.

cc: @man-git007

**Comment by charlesyoung** [comment]
Why dont we need the number for the xls download?

**Comment by birendragurung** [comment]
@charlesyoung Zip file download has a different process than xls file. Hence this was mandatory due to technical circumstances.

**Comment by birendragurung** [comment]
@charlesyoung We've made changes to maintain same naming for the zip file. We are ready to deploy this on production.

cc: @man-git007

**Comment by birendragurung** [comment]
@charlesyoung This has been deployed to production.
