### ISSUE TITLE
Notifications 

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1292]
@anjesh for some reason the email notifications I used to received reminding me that I can publish uploaded docs, after ABBYY was run, has stopped working.

**Comment by charlesyoung** [comment]
@anjesh can you please look at this and let me know how much time will be required.

**Comment by anjesh** [comment]
~ 4 hours.

**Comment by charlesyoung** [comment]
Double and irrelevant notifications received. 

![image](https://user-images.githubusercontent.com/13888372/110742405-f67e7d00-823e-11eb-93e0-f2dcbbb2e67c.png)

**Comment by charlesyoung** [comment]
Completed. 

Just need to deploy to Prod site.
