### ISSUE TITLE
Change the “Annotation Category” search field name (RC only)

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1296]

**Comment by charlesyoung** [comment]
Change the “Annotation Category” search field name to “Key Clauses”
Also want to change the title of “Annotated Contracts Only” filter but still need to decide to what. 

cc @SamCCSI

**Comment by SamCCSI** [comment]
Have changed title of ticket to reflect that this is only for RC -- OLC is sticking with existing wording for annotations.

**Comment by birendragurung** [comment]
> Change the “Annotation Category” search field name to “Key Clauses”
> Also want to change the title of “Annotated Contracts Only” filter but still need to decide to what.


@charlesyoung What should be the title for "Annotated Contracts Only"?

**Comment by charlesyoung** [comment]
Change the “Annotation Category” search field name to “Key Clauses”. 
Change the title of “Annotated Contracts Only” filter to “Tagged Contracts Only”

**Comment by birendragurung** [comment]
@charlesyoung Now RC site's search section will look as follows.
![Screenshot from 2020-07-22 13-01-33](https://user-images.githubusercontent.com/13505748/88146384-82de2000-cc1b-11ea-906a-4415f7357f9b.png)

Also there's a concern regarding RC and OLC with regard to this https://github.com/NRGI/resourcecontracts.org/issues/1290#issuecomment-654687731 
We have applied the name changes regardless of RC, OLC, country sites in #1290 for renaming the terms for 'Annotation category' and 'Annotation text' with 'Key clause' and 'Clause summary' respectively. But in this issue, we've only changed for RC only. What do you think about this? Please let us know if we are fine with this and then we can go for production deployment and close this issue.


cc: @man-git007

**Comment by charlesyoung** [comment]
Just checking with @SamCCSI 

So on OLC we will retain the Annotation text as shown below. 

![image](https://user-images.githubusercontent.com/13888372/88150524-caf04900-cc01-11ea-93d6-c83fc8799764.png)

The clipping headings have however changed. 

![image](https://user-images.githubusercontent.com/13888372/88150883-3fc38300-cc02-11ea-923f-4fcdca562f01.png)

@birendragurung can we not retain the old clipping column text labels for OLC?

**Comment by birendragurung** [comment]
@charlesyoung Yes we can do it on `Clipping page`. These changes are also done in spreadsheet download files as well. So, the general idea must be changing the term only on RC right?

cc: @man-git007

**Comment by charlesyoung** [comment]
Yes please. 

cc @SamCCSI

**Comment by charlesyoung** [comment]
You can update the 'Key clause' and 'Clause summary' labels on the **RC** production site when ready.

**Comment by SamCCSI** [comment]
> @charlesyoung Yes we can do it on `Clipping page`. These changes are also done in spreadsheet download files as well.
> The general idea must be changing the term only on RC right? This way it will provide consistency across each individual sites.
> 
> cc: @man-git007

Correct -- for OLC we are not making any changes in this regard and want to keep "annotation" terminology

**Comment by birendragurung** [comment]
@SamCCSI Should we retain the old terminologies for all country sites as well? 

cc: @man-git007

**Comment by charlesyoung** [comment]
No, there are for now only RC country sites so the new terminologies should also be added to the country sites. 

We just need to remember to retain the old terminologies for future OLC country sites.

**Comment by birendragurung** [comment]
@charlesyoung We are deploying changes made in this issue along with #1290 , #1289 and #1304 
Please verify these changes and we can deploy it to production thereafter.

cc: @man-git007

**Comment by charlesyoung** [comment]
#1290 can be deployed once the zip file name is done
#1289 can be deployed
#1304 can be deployed

**Comment by birendragurung** [comment]
@charlesyoung This has been deployed to production.

cc: @man-git007

**Comment by charlesyoung** [comment]
@birendragurung I have been asked to find out if it will be simple to change reference to annotated and annotation_category in the search results URLs. 

- Selecting the 'Tagged Contracts only' [box](https://www.resourcecontracts.org/search/group?q=&annotated=1)
- Selecting a key clause from the drop down [menu](https://www.resourcecontracts.org/search/group?q=&annotation_category%5B%5D=Arbitration+and+dispute+resolution)

**Comment by charlesyoung** [comment]
It also relates to other parts if the site like below. 

![image](https://user-images.githubusercontent.com/13888372/89403689-01a58380-d719-11ea-8070-767988c0e87d.png)

**Comment by birendragurung** [comment]
@charlesyoung Do we replace the term 'Annotations' with 'Tags'?

**Comment by charlesyoung** [comment]
Thanks @birendragurung 

Can you also please check the export of a key clause search to Excel. When I run a search on a key clause like bonuses, as noted below, it finds 185 documents but the download Excel file is empty. 

![image](https://user-images.githubusercontent.com/13888372/89511211-e6e31580-d7d1-11ea-975e-2bfbd18ed620.png)

**Comment by birendragurung** [comment]
@charlesyoung The above mentioned changes regarding annotation terms have been deployed to staging server. Please review and let us know if to deploy to production.

cc: @man-git007

**Comment by charlesyoung** [comment]
Thanks. Please deploy to Prod.

**Comment by charlesyoung** [comment]
Sorry please hold. Only noticed your 'Do we replace the term 'Annotations' with 'Tags'?' question now.

**Comment by charlesyoung** [comment]
So 'Annotations' should be names 'Key Clauses'.

**Comment by birendragurung** [comment]
@charlesyoung 'Annotation category' is replaced by 'Key clauses'. Will it be same for 'Annotation' also?

**Comment by charlesyoung** [comment]
We need to keep things consistent. The search page notes 'Key Clauses' 
![image](https://user-images.githubusercontent.com/13888372/90021024-fd490f80-dcb0-11ea-8fcd-b2385db24e71.png)

So this needs to be replicated below. 
![image](https://user-images.githubusercontent.com/13888372/90021078-0cc85880-dcb1-11ea-9570-3a14a871e5fe.png)

**Comment by birendragurung** [comment]
@charlesyoung The term 'Annotation' has been replaced by 'Key clauses' for RC as per your suggestion. Please let us know if we are ready to go for deployment to production

cc: @man-git007

**Comment by charlesyoung** [comment]
Many thanks, I will test and get back.

**Comment by charlesyoung** [comment]
@birendragurung 

Seems like 'Annotations' is still noted on the summary page. 

![image](https://user-images.githubusercontent.com/13888372/90367056-81f8ac80-e068-11ea-8b55-c8202f5a9201.png)

**Comment by birendragurung** [comment]
@charlesyoung This is due to the cache issues. Please hard refresh your browser and let me know if this problem still persists.

**Comment by charlesyoung** [comment]
This is from an Incognito window. I also tested it in IE which I never use.

**Comment by birendragurung** [comment]
@charlesyoung The changes have been updated in staging server. Please verify and let us know if we are ready for production.

cc: @man-git007

**Comment by charlesyoung** [comment]
Thanks, please deploy to Prod.

**Comment by birendragurung** [comment]
@charlesyoung This has been deployed to production.

**Comment by charlesyoung** [comment]
Thanks

**Comment by charlesyoung** [comment]
More annotation text updates. 

![image](https://user-images.githubusercontent.com/13888372/98778045-6cdab200-23fa-11eb-9119-269d9d1e969f.png)

![image](https://user-images.githubusercontent.com/13888372/98778142-94ca1580-23fa-11eb-91f4-4e1188cc96c8.png)

**Comment by charlesyoung** [comment]
I have allocated 3 hours for this task.

**Comment by SamCCSI** [comment]
Again, Charles's request is for RC only -- OLC text should not be changed.

**Comment by surazneupane** [comment]
@charlesyoung  we have deployed it to staging server can you see the change and verify it? Thanks !
cc @man-git007

**Comment by charlesyoung** [comment]
Thanks. 

Please rename to 'This contract has key clauses. View all key clauses'

(change case and remove the fullstop)

**Comment by charlesyoung** [comment]
Please also run a check that there is no more reference to annotations in RC.

**Comment by surazneupane** [comment]
@charlesyoung  can you see the above mentioned change in staging ? please verify it . Thanks !

**Comment by charlesyoung** [comment]
Looks good.

**Comment by surazneupane** [comment]
@charlesyoung  can this be deployed on production?

**Comment by charlesyoung** [comment]
Yes please

**Comment by surazneupane** [comment]
@charlesyoung  can you see the change in production site? And can this issue be closed?

**Comment by charlesyoung** [comment]
@surazneupane can I please aks that you rename below with just 'View key clauses'. NRGI staff are back from leave and this was a request from one of the primary RC users. No need to do it on Staging, do it straight on Prod. Thanks 

![image](https://user-images.githubusercontent.com/13888372/104413292-c2584a00-5576-11eb-86a2-ecf0b8cce072.png)

**Comment by surazneupane** [comment]
@charlesyoung  please verify the change in production . Thanks .

**Comment by charlesyoung** [comment]
Will do, still seems cached, however.

**Comment by surazneupane** [comment]
@charlesyoung  can this issue be closed ?

**Comment by charlesyoung** [comment]
Sorry, what I meant is to ONLY have 'View key clauses' text. 

So no 'This contract has key clauses.'

**Comment by surazneupane** [comment]
@charlesyoung  please verify at production .Thanks

**Comment by charlesyoung** [comment]
Many thanks @surazneupane

**Comment by jedm** [comment]
Reopening this because it looks like this change was made in error on OLC. Per @SamCCSI **[in comment above](https://github.com/NRGI/resourcecontracts.org/issues/1296#issuecomment-662437244)**, "Annotation" terminology and phrasing should have been retained.

Also please note that the left-side menu on OLC is now wrong. See OLC staging for correct menu. Thank you!

**Comment by charlesyoung** [comment]
Thanks for picking this up @jedm 

@surazneupane please ensure that RC **only** changes are not applied to OLC.

**Comment by surazneupane** [comment]
@jedm  soory dinot noticed the change in **OLC** while working on **RC** . @charlesyoung  @jedm  please verify if all is good for both **OLC** and **RC**.

**Comment by charlesyoung** [comment]
Are the staging sites down? Cannot seem to run any searches. 

I still see below on Prod

![image](https://user-images.githubusercontent.com/13888372/104729944-e3b96180-5741-11eb-876c-87a8114f6fb7.png)

and not this. 

![image](https://user-images.githubusercontent.com/13888372/104729986-f3d14100-5741-11eb-9647-843a2e49a219.png)

**Comment by surazneupane** [comment]
@charlesyoung  i have created fresh staging . please verify . Thanks !

**Comment by jedm** [comment]
@surazneupane The menu on OLC staging is now correct. However, I think that the hover is wrong. Is it possible to recover the OLC hover format from before the RC hovers were added to OLC in error? 

cc @SamCCSI @anjesh

**Comment by surazneupane** [comment]
@jedm  can you please provide the screenshot of which hover is wrong ? Thanks 1

**Comment by surazneupane** [comment]
@jedm  i think everything is up to date with OLC at staging as we have retained the errors .Please Verify so that we can go on to production . Thanks !

**Comment by charlesyoung** [comment]
@surazneupane the hover on the OLC site needs to say 'This contract has Annotations' (like the staging site) and not 'This contract has Key Clauses'. Please update the OLC site.

**Comment by surazneupane** [comment]
@charlesyoung  please verify if all good at production . And if all looks good can this issue be closed. Thanks !

**Comment by charlesyoung** [comment]
Thanks, looks good. 

@SamCCSI / @jedm please confirm that the updates are correct?

**Comment by charlesyoung** [comment]
@surazneupane I still notice annotation references that need to be upadtd. See below URL. 

https://www.resourcecontracts.org/contract/ocds-591adf-2108050504/view#/pdf/page/19/annotation/5635

Should be 

https://www.resourcecontracts.org/contract/ocds-591adf-2108050504/view#/pdf/page/19/**tagged**/5635

**Comment by man-git007** [comment]
@charlesyoung The annotation references have been updated and deployed in the [staging](https://staging.resourcecontracts.org/contract/ocds-591adf-9403334972/view#/pdf/page/8/tagged/37203) server. Please verify

cc @surazneupane

**Comment by charlesyoung** [comment]
Not sure if its a caching issue but I still see the annotation reference in the URL. 

https://staging.resourcecontracts.org/contract/ocds-591adf-1022255942/view#/pdf/page/17/annotation/15227

**Comment by man-git007** [comment]
@charlesyoung Try incognito mode or do a hard refresh.

[https://staging.resourcecontracts.org/contract/ocds-591adf-9403334972/view#/pdf/page/8/tagged/37203](https://staging.resourcecontracts.org/contract/ocds-591adf-9403334972/view#/pdf/page/8/tagged/37203)

**Comment by charlesyoung** [comment]
I have. 

![image](https://user-images.githubusercontent.com/13888372/105806693-17e81a00-5fad-11eb-89e4-3d1552cdd66e.png)

**Comment by man-git007** [comment]
@charlesyoung This hasn't been deployed in the [live](https://resourcecontracts.org/) server. Please check in the [staging](https://staging.resourcecontracts.org/) server.

**Comment by charlesyoung** [comment]
No change. 

https://staging.resourcecontracts.org/contract/ocds-591adf-5648979642/view#/pdf/page/12/annotation/21277

**Comment by man-git007** [comment]
@charlesyoung The link is updated to **tagged**.

[https://staging.resourcecontracts.org/contract/ocds-591adf-5648979642/view#/pdf/page/12/tagged/21277](https://staging.resourcecontracts.org/contract/ocds-591adf-5648979642/view#/pdf/page/12/tagged/21277)

**Comment by charlesyoung** [comment]
That's fine but I still get the annotation ref when clicking on the Pg link. 

https://staging.resourcecontracts.org/search/group?q=&key_clause%5B%5D=Bonuses

**Comment by man-git007** [comment]
@charlesyoung Are you talking about the [summary](https://staging.resourcecontracts.org/contract/ocds-591adf-1022255942#keyclauses) page? This has been fixed and deployed in the staging server.

**Comment by charlesyoung** [comment]
Click on the [Pg xx] links of below. There should be no annotation ref in any of the RC links. 

https://staging.resourcecontracts.org/search/group?q=&key_clause%5B%5D=Bonuses

**Comment by man-git007** [comment]
@charlesyoung Thanks for pointing it out. This has been resolved and deployed. Please check.

**Comment by charlesyoung** [comment]
Thanks, please push to Prod.

**Comment by man-git007** [comment]
@charlesyoung Moved to Prod. If all OK we can close this ticket
