### ISSUE TITLE
Create a Research and Analysis page

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1297]

**Comment by SamCCSI** [comment]
For RC only -- not for OLC.

**Comment by charlesyoung** [comment]
A Research and Analysis page link should be added at the bottom of each page along with the other pages of the site.

**Comment by anjesh** [comment]
Duplicate of https://github.com/NRGI/resourcecontracts.org/issues/1305

**Comment by charlesyoung** [comment]
@anjesh can we keep this ticket because there are 2 separate issues noted in the ToR. 1 to create the page and the other to design it.

**Comment by nirvanalama** [comment]
@charlesyoung Here is the design for research and analysis page https://www.figma.com/file/OK1BSOpfKTokEoBZYQCXss/RC__UI_v2?node-id=552%3A0
The second box is empty please provide the content. Also, the banner image for research and analysis page.

**Comment by charlesyoung** [comment]
Many thanks @nirvanalama 

I will revert with comments.

**Comment by charlesyoung** [comment]
This is linked to #1305

**Comment by charlesyoung** [comment]
@nirvanalama how much of the text, titles, etc will we be able to update / add?

**Comment by man-git007** [comment]
@charlesyoung Let's discuss the design in #1305  issue and after the design has been finalized, we will discuss the functionality in this issue.

**Comment by charlesyoung** [comment]
This issue is just to create the R&A link at the bottom of the pages. 

![image](https://user-images.githubusercontent.com/13888372/88051005-3251be80-cb58-11ea-8cde-9393ac48d2c1.png)

**Comment by birendragurung** [comment]
@charlesyoung We have developed the backend for managing research links. Please go through the admin panel and provide us feedback about any improvements.

cc: @man-git007 

Main page
![Screenshot from 2020-08-04 17-50-06](https://user-images.githubusercontent.com/13505748/89291854-fc91f700-d67a-11ea-9296-7765dbb76548.png)

Text configuration page (for heading and description)
![Screenshot from 2020-08-04 17-50-50](https://user-images.githubusercontent.com/13505748/89291895-0ddb0380-d67b-11ea-9897-d6af2f7f5593.png)

Page for adding links 
![Screenshot from 2020-08-04 17-51-33](https://user-images.githubusercontent.com/13505748/89291950-2814e180-d67b-11ea-9158-d4704cddb353.png)

For managing featured links
![Screenshot from 2020-08-04 17-52-11](https://user-images.githubusercontent.com/13505748/89291986-3ebb3880-d67b-11ea-9bb1-b44d4ddde17d.png)

**Comment by charlesyoung** [comment]
Is this just to create the 3 R&A boxes? I created 3 titles but how do I add descriptions to each title (if I understand it correctly)? 

![image](https://user-images.githubusercontent.com/13888372/89299603-2e00c780-d667-11ea-8ef7-18d5d24c70e4.png)

**Comment by birendragurung** [comment]
@charlesyoung 
- As discussed in the TOR in #1305 , the admin can add/edit URL with title that will be shown in research and analysis page. 
- These links can be set as featured by going to `Featured` page which will then be shown in the 3 boxes on the page.

cc: @man-git007

**Comment by charlesyoung** [comment]
OK. I will test once we have a page where I can see the results.

**Comment by birendragurung** [comment]
@charlesyoung Can you provide the background image for this page?
Also, should the admin be able to change the background image or will it be static?

**Comment by charlesyoung** [comment]
A background image for the top area or the entire page?

**Comment by birendragurung** [comment]
@charlesyoung It's the one illustrated on the design here in https://github.com/NRGI/resourcecontracts.org/issues/1305#issuecomment-668516649

**Comment by charlesyoung** [comment]
Let me find out.

**Comment by charlesyoung** [comment]
@birendragurung we are happy with the current image but would want a backend tool allowing us to update the image in the future.

**Comment by birendragurung** [comment]
@charlesyoung The new design has been deployed to staging server. Please review and provide feedbacks. 

cc: @man-git007

**Comment by birendragurung** [comment]
@charlesyoung We added the link for the page on top right position of the page. On mobile layout, the link does not look good. Could we add it only to the footer and sidebar?

Here are the screen shots on how it appears on the screen.

Added on top right:
![Screenshot from 2020-08-12 11-24-26](https://user-images.githubusercontent.com/13505748/89979061-94e93680-dc8e-11ea-9b6a-e556cc2a848a.png)

On mobile layout: 
![Screenshot from 2020-08-12 11-25-17](https://user-images.githubusercontent.com/13505748/89979120-b34f3200-dc8e-11ea-82b3-a93057a53895.png)


On footer:
![Screenshot from 2020-08-12 11-24-49](https://user-images.githubusercontent.com/13505748/89979087-9ca8db00-dc8e-11ea-9531-7e68453a590a.png)

**Comment by charlesyoung** [comment]
Thanks @birendragurung 

How much control do we have over the mobile display? The issue is that its not that obvious in the footer.

**Comment by birendragurung** [comment]
@charlesyoung Alternatively we can hide the link on smaller screens.

**Comment by charlesyoung** [comment]
So that's what I'm asking. Can we show the R&A link differently on mobile devices? I wouldn't hide the link with 35% of users (in 2020) accessing RC on mobile devices.

**Comment by birendragurung** [comment]
@charlesyoung 
Since the header feels compact on mobile device screens, we have three possible solutions for what you are proposing: 

1. Can we rename to 'Research links' such that it occupies less space on the header?
2. We can add the link to sidebar hamburger menu also and mobile screens will be able to view the link there.
3. Another alternative would be to rethink and redesign the header such that it can accommodate the link there and will require more time.

cc: @man-git007

**Comment by charlesyoung** [comment]
OK thanks, let me get back to you. Can you confirm that for the mobile view you could only have the R&A link in the side menu? 

Can you in the interim look at below. 
- Do we open the window in a new window or open in the current window? 
- Which of the 2 options in attached PowerPoint works? 
- Can you remove the 'underline', like the language links, when clinking on the link 

![image](https://user-images.githubusercontent.com/13888372/90101771-9888c600-dd3f-11ea-99d1-f91a1c08b05a.png)

[RA title location-NW.pptx](https://github.com/NRGI/resourcecontracts.org/files/5067457/RA.title.location-NW.pptx)

**Comment by birendragurung** [comment]
@charlesyoung 
1. Currently the link opens in the same window. 
2. Could you explain more about this? 
3. Yes, it can be done.

**Comment by charlesyoung** [comment]
@birendragurung 
1. What do you suggest?
2. Which option is preferred from a design point of view? @nirvanalama 

![image](https://user-images.githubusercontent.com/13888372/90102940-f8806c00-dd41-11ea-933b-295b87d8145a.png)

![image](https://user-images.githubusercontent.com/13888372/90102961-033b0100-dd42-11ea-8ba8-1da825e22e62.png)

**Comment by birendragurung** [comment]
@charlesyoung 
1. I would suggest to open on new window.

**Comment by charlesyoung** [comment]
Agree

**Comment by nirvanalama** [comment]
@charlesyoung Option two looks good but with the RC system font "Open sans" @birendragurung oPEN

**Comment by birendragurung** [comment]
@charlesyoung  
- We can hide the 'Research and analysis' link in header in mobile view and show in sidebar (in both desktop and mobile view).

- Also, we'll implement this on the link in header.

![](https://user-images.githubusercontent.com/13888372/90102961-033b0100-dd42-11ea-8ba8-1da825e22e62.png)

**Comment by charlesyoung** [comment]
Thanks both. Good that I know that we can hide the link on the mobile view. Can I ask that you include it for now so that I can get internal agreement that it should be hidden. Thanks

**Comment by birendragurung** [comment]
@charlesyoung Do you mean we do not hide the link on mobile screens for now?

**Comment by charlesyoung** [comment]
Yes please. I would first like to show NRGI the mobile view as is before we hide the link.

**Comment by birendragurung** [comment]
@charlesyoung 
We have made changes according to your suggestions. Following things have been implemented: 
- Research and analysis link on top right of the screen with border
![Screenshot from 2020-08-14 18-21-06](https://user-images.githubusercontent.com/13505748/90249894-fb22b480-de5a-11ea-9c08-fe43d4c9936b.png)

- The Research and analysis link is visible in all screen sizes (mobile and desktop). The image below illustrates the new changes as seen on iPhone X.
![Screenshot from 2020-08-14 18-22-22](https://user-images.githubusercontent.com/13505748/90250014-21485480-de5b-11ea-8b51-875d3df4ade2.png)

- Research and analysis admin panel to manage research links, page background image, page heading and introduction text and to manage featured links.

Please review the staging server and let us know for any improvements and if we are ready to deploy to production.

cc: @man-git007

**Comment by charlesyoung** [comment]
@birendragurung I had an internal meeting last week and we are happy with the current R&A text placement on PC and mobile.

**Comment by charlesyoung** [comment]
@birendragurung 

I want to look at adding text for R&A page. Just a question re editing text. I changed below nr 2 to increase the font size but reduced the size. 

![image](https://user-images.githubusercontent.com/13888372/90379595-34396f80-e07b-11ea-9529-59479e68e782.png)

**Comment by birendragurung** [comment]
@charlesyoung I couldn't understand what you are explained above.

**Comment by charlesyoung** [comment]
I changed the font size for heading 2 to increase but it actually decreased in size.

**Comment by birendragurung** [comment]
@charlesyoung Are you talking about the research and analysis page here? Or is it related to guides?

**Comment by charlesyoung** [comment]
Just general editing of text through the text editor. This will affect the R&A page, etc as well.

**Comment by birendragurung** [comment]
@charlesyoung 
First of all, you might be editing on the new design for guides. If that is the case, please remember that the design is implemented by editing the source code (Tools - Source code) and has custom styles which might have caused the above mentioned problem in your case. The problem won't arise if you edited on other versions of the content. Also, the new guide design is meant for OLC and not for RC, so it won't have problem on RC.

Can you check if the problem exists for other pages/versions?

cc: @man-git007

**Comment by charlesyoung** [comment]
This has nothing to do with the guides page. This is just general editing of the text from the backend.

**Comment by birendragurung** [comment]
@charlesyoung How can we replicate the scenario on staging server? Can you provide some steps on how you encountered this issue?

**Comment by man-git007** [comment]
@charlesyoung The [issue](https://github.com/NRGI/resourcecontracts.org/issues/1297#issuecomment-674767326) you have mentioned is a special case. The `faq page` has a sidebar link and to maintain the layout, font size, CSS of the sidebar with the content, we had to do this through the code level itself. Therefore, upon changing the font size of the header, it is behaving abnormally. The changes you make via editor would not be an issue for other pages like `contact page`.

cc @anjesh @birendragurung

**Comment by charlesyoung** [comment]
Thanks @man-git007 

What dev work is required to allow admin users to update the FAQ page?

**Comment by charlesyoung** [comment]
@birendragurung please change below to Research & Analysis 

![image](https://user-images.githubusercontent.com/13888372/90864165-7d960180-e390-11ea-9abe-702ef96c8534.png)

**Comment by man-git007** [comment]
@charlesyoung You can change the content of the `FAQ` page via editor itself but in the case of a change in styling of the page, we need to do it manually in code level.

cc @birendragurung @anjesh

**Comment by charlesyoung** [comment]
@birendragurung re the backend tool for managing research links.

How is the date determined? I added a new link but the date is noted as 10 July 2020. 

I will run through the backend tool with NRGI next week and report back.

**Comment by birendragurung** [comment]
@charlesyoung The date is the published date i.e. when the link is added in the admin panel. It has been fixed now.

**Comment by charlesyoung** [comment]
@birendragurung can you pls check because all reference to the R&A work has disappeared from the staging site. Below link now also doesn't work. 

https://staging.resourcecontracts.org/research-and-analysis

**Comment by birendragurung** [comment]
@charlesyoung The staging server is now updated.

**Comment by charlesyoung** [comment]
Closing this ticket because I'm getting confused with this one and ticket 1305.
