### ISSUE TITLE
UI List of the availability of contracts by company

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#130]

**Comment by anjesh** [comment]
Moving to Sprint 8 after we implement https://github.com/NRGI/resourcecontracts.org/issues/179

**Comment by anjesh** [comment]
We can now search the contracts by corporate grouping.

![image](https://cloud.githubusercontent.com/assets/120488/9896637/eb7fd608-5c5e-11e5-991b-af5865a779fa.png)
