### ISSUE TITLE
Publishing crash

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1303]
@anjesh has anything changed at the backend. I get below error now when I want to publish new contracts. 

Is this related to #1301? 

![image](https://user-images.githubusercontent.com/13888372/86366291-e5767880-bc7a-11ea-8eac-1f7c054bbe91.png)

**Comment by charlesyoung** [comment]
Could it be a file size issue. I can publish smaller docs but this one is 90 MB. 

https://drive.google.com/file/d/1FEjMyW5UZMXdWXQ3MEch5iIab_3tRo5x/view?usp=sharing

**Comment by charlesyoung** [comment]
@anjesh please confirm if there is a doc size limitation.

**Comment by anjesh** [comment]
~ 4 hours - check the current file upload size, confirm if this is size issue or other issue, show the doc size limit in the upload page, and coordinate with Vitamin to change the upload limit if needed.

**Comment by charlesyoung** [comment]
Completed. 

Just need to deploy to Prod site.
