### ISSUE TITLE
Add predefined text to the “Clause Summary” column for tagged contracts

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1304]
Predefined text needs to be inserted to the “Clause Summary” column when contracts have been tagged and not annotated because tagging doesn’t capture the clause summary information. The text needs to be added on the Clipping page as well as to the spreadsheet export. The predefined text is “Clause summaries have not been prepared for this document”.

**Comment by birendragurung** [comment]
@charlesyoung We have added predefined text for those that have empty annotation text on Clipping page as well as spreadsheet export.
![Screenshot from 2020-07-22 12-39-25](https://user-images.githubusercontent.com/13505748/88146003-021f2400-cc1b-11ea-8c2e-7af209f49532.png)

In spreadsheet, it's looks as follow:
![Screenshot from 2020-07-22 12-41-50](https://user-images.githubusercontent.com/13505748/88145954-f29fdb00-cc1a-11ea-85ff-b6d895460c12.png)

Also, we have done the same on contract view page as shown below.
![Screenshot from 2020-07-22 12-57-00](https://user-images.githubusercontent.com/13505748/88145917-e4ea5580-cc1a-11ea-9014-44a6e6a57d6a.png)

Let us know about any improvements and deployment to production if everything's good.
cc: @man-git007

**Comment by charlesyoung** [comment]
Thanks, will test and revert.

**Comment by birendragurung** [comment]
@charlesyoung Can you provide the predefined text for sites other than RC?
This is with reference to this https://github.com/NRGI/resourcecontracts.org/issues/1296#issuecomment-662437244 

cc: @man-git007

**Comment by charlesyoung** [comment]
Please deploy to the RC production site.

**Comment by birendragurung** [comment]
@charlesyoung This has been deployed to production.

cc: @man-git007
