### ISSUE TITLE
Design and implement a Research and Analysis page

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1305]
Details of the Research and Analysis page are outlined in the ToR.

**Comment by anjesh** [comment]
Here's the detail from the TOR.

----

The Research and Analysis page should be roughly designed like this page: https://resourcegovernance.org/topics/coronavirus

There should be a heading, description (which may be contained in a simple rectangular coloured box that spans the page in lieu of the photograph in the example above), three boxes (which partially overlap with the rectangle) that can contain URLs (which we may update from time to time) to examples of research and the ability to list further research below the boxes in a simple list. The URLs should have a text face that we can input such that the box displays the title of the research and clicking on the title in the box takes one to the webpage of the research

Initial URLs for a mockup can include:

* https://resourcegovernance.org/blog/force-majeure-coronavirus-legal-challenges-resource-dependent- zambia-glencore
* https://www.igfmining.org/new-database-reveals-prominence-of-tax-incentives-in-mining/ Middle box can be blank for now.

[Heading] Research & Analysis

[Description below heading]

Governments, civil society, companies and other actors can use ResourceContracts.org to conduct various kinds of research and analysis. Such research can inform policymaking or contract negotiations. It can also empower oversight actors to monitor whether companies and governments are fulfilling their obligations under contracts, and to take action if not. Examples are provided below to demonstrate the kinds of research and analysis that can be done.

Colours of the boxes and font should match those currently used for the site. Consultant should propose a design and provide a mock-up for review.

----

> Here's the understanding that YI has shared earlier with NRGI


## Front end interface

We will put a link "Research and Analysis" in the footer, which takes to a page that has the heading "Research and Analysis" with the following description below the heading

    Governments, civil society, companies and other users can use the contracts and search and comparison features in ResourceContracts.org to conduct various kinds of research and analysis. Such research can inform policymaking or contract negotiations, and can enable oversight actors to monitor whether companies and governments are fulfilling their obligations under contracts and take action if not. Examples of research and analysis are provided below.

 
Below the description are 3 boxes as shown in this page https://resourcegovernance.org/topics/coronavirus
- the first box will have the following title and url for that title

    Title: Force Majeure and Other Coronavirus-Era Legal Challenges: Lessons for Resource-Dependent Countries from the Glencore-Zambia Dispute
    URL: https://resourcegovernance.org/blog/force-majeure-coronavirus-legal-challenges-resource-dependent-zambia-glencore

- the second box will be empty box
- the third box will have the following title and url

    Title: New Database Reveals Prominence of Tax Incentives in Mining
    URL: https://www.igfmining.org/new-database-reveals-prominence-of-tax-incentives-in-mining/


It's not clear what the content will be below the boxes. I am assuming we will list all the page URLs, the two of which are also shown above. The 3 boxes is a way to highlight few specific important URLs. Later there will be more URLs. Unlike this page https://resourcegovernance.org/topics/coronavirus, Research and Analysis page won't have publications, News & Insights, Other Topics and Related events.

## Backend Interface

We will create an interface where the user may add/edit/delete the URL and Title that goes in the list and the boxes in Frontend interface. We will need to make database table to store the URLs and Titles. Also the interface will have option to select the URLs/Titles that goes into the 3 boxes. With this arrangement, user gets the CMS interface where the user enters the URL and Title and that appears in the page. 

---

We will create a separate issue for implementation once design is finalized.

**Comment by man-git007** [comment]
@charlesyoung The link to design is https://www.figma.com/file/OK1BSOpfKTokEoBZYQCXss/RC__UI_v2?node-id=552%3A0. Is the page layout fine?

**Comment by charlesyoung** [comment]
I'm busy getting feedback.

**Comment by charlesyoung** [comment]
Comments below. 

**Introduction paragraph** (to be updated)
Governments, civil society, companies and other actors can use ResourceContracts to conduct various kinds of research and analysis. Such research can inform policy making or contract negotiations. It can also empower oversight actors to monitor whether companies and governments are fulfilling their obligations under contracts, and to take action if not. Examples are provided below to demonstrate the kinds of research and analysis that can be done. 

**Colours** 
The green boxes looked a bit dark. Can we see a few options in terms of colours? Can we see how it looks with the orange colour we have used for the search button and documents box on the home page? The top part would still be the photo. Can we see how it looks still with the orange boxes but replacing the photo with solid blue (see countries box on home page)? Can we see how it looks with orange boxes but replacing the photo with solid green (the recent documents box on home page)? Then we can see which of the four colour schemes looks best (including the existing one). 

**Font size and dates**
The titles in the boxes should be more prominent than the titles in the list below. It looks like the font in the boxes is smaller than the font for the titles in list. We should swap that. However, the date can remain the same size. In fact, for the boxes the date should be less prominent than the title so the font for date should be smaller than title and place the date below the title for the boxes. Similarly for the list below, let’s make the title the first thing with the date below and the date in a smaller font relative to the title.The date appears to be in bold whereas if anything the titles should be bold and the dates unbolded. 

**Box size**
The boxes themselves should also be more prominent. Can we enlarge them so the row of boxes extends beyond the central margin by approx. 2cm on either side? I also note that on the home page when you hover on a box it enlarges. It would be nice if the boxes on the research page did that too.

**Comment by nirvanalama** [comment]
@charlesyoung The orange boxes and the background color do not go well at all. We would suggest to use the background image and orange color for the box.
https://www.figma.com/file/OK1BSOpfKTokEoBZYQCXss/RC__UI_v2?node-id=552%3A0

**Comment by charlesyoung** [comment]
Thanks @nirvanalama 

Will get back with feedback.

**Comment by charlesyoung** [comment]
@nirvanalama please see questions and comments below. 

- We are still debating the box colour scheme
- Is font in the box on the right smaller than the box on the left
- Are the titles in the boxes bold. Please bold them if not, but not the titles in the list below
- Will the boxes enlarge when you hover over as on the home page

**Comment by charlesyoung** [comment]
More comments. 

- The image, compared to the solid colours, is preferred.
- Can we please see mockups of orange, green (already done) and blue (countries box on home page) boxes? 
- Where do you suggest we place the R&A link? We feel it might be lost at the bottom of the page. Would it make sense to put it at the top right of the page like the Using the Site link on OLC? Other suggestions?

**Comment by man-git007** [comment]
@charlesyoung Do we need this page in FR and AR language?

**Comment by charlesyoung** [comment]
Let me check and come back to you.

**Comment by nirvanalama** [comment]
@charlesyoung If the research and analysis page is very important it can be placed at the top right otherwise it would be appropriate in the footer section. 

We think the blue or the green color would be better for the boxes, we do not suggest using orange as it is a very prominent color.

Here is the final design:
https://www.figma.com/file/OK1BSOpfKTokEoBZYQCXss/RC__UI_v2?node-id=553%3A49

**Comment by charlesyoung** [comment]
Many thanks, I will get back to you with comments.

**Comment by charlesyoung** [comment]
Comments below. 

- FR and AR language translations will be required
- Will the boxes enlarge when you hover over as on the home page (question asked before) 
- Box colour should be blue
- We will get back re the link location but it will most probably be on the top right

**Comment by man-git007** [comment]
@charlesyoung Yes, the boxes will enlarge upon hover, same as that of on the new homepage.

**Comment by charlesyoung** [comment]
Will it be possible to get your design feedback on placing the R&A box on the top right of the box. See attached PowerPoint with 2 examples. The first example could be a bit more translucent like the popular searches box. Right now it’s fully opaque so that might affect the look. 

[RA title location-NW.pptx](https://github.com/NRGI/resourcecontracts.org/files/5039958/RA.title.location-NW.pptx)

**Comment by charlesyoung** [comment]
@man-git007 @nirvanalama what is the latest re the R&A page design?

**Comment by man-git007** [comment]
@charlesyoung There are no updates regarding the design. The changes you had suggested have been implemented in the staging site. If any queries please followup with @birendragurung.

**Comment by charlesyoung** [comment]
Where on the staging site? Below is not the final design we discussed. 

https://staging.resourcecontracts.org/research-and-analysis

**Comment by iprunache** [comment]
@charlesyoung we had an issue with the automated deployment to the staging site and the changes Manish is referencing might not have gotten deployed at the time of your comment. Could you please have another look? I just fixed the deploy today.

**Comment by birendragurung** [comment]
@charlesyoung 
The implementation has some differences from the final design. Some of the differences are: 
**1. Heading text alignments**
The heading is aligned according to the second design of this design. (https://www.figma.com/file/OK1BSOpfKTokEoBZYQCXss/RC__UI_v2?node-id=553%3A49)
**2. Featured box sizing** 
The boxes are not squared as in design since the box grows with respect to the internal content. Should we cut off the long text and maintain the square shape of the box?
**3. Links hover effect**
The links have red hover effect to maintain consistency with RC's theme. 
**4. Pagination links**
Pagination links are different and needs to be changed according to the design

cc: @man-git007

**Comment by charlesyoung** [comment]
Thanks @birendragurung 

1. Heading text alignments: Keep the current heading [placement](https://staging.resourcecontracts.org/research-and-analysis)
2. Featured box sizing: Let me check, I will get back to you
3. Links hover effect: Let me check, I will get back to you
4. Pagination links: OK
5. I will also check if we need to note R&A twice
![image](https://user-images.githubusercontent.com/13888372/90629795-3d177600-e220-11ea-971c-91d79375c5aa.png)

**Comment by charlesyoung** [comment]
Relates to above. 

3. Links hover effect. The links have red hover effect to maintain consistency with RC's theme.

**Comment by birendragurung** [comment]
@charlesyoung 
The changes have been deployed to the staging server. Please review the design and functionality and let us know if we can deploy it to production.

cc: @man-git007

**Comment by charlesyoung** [comment]
Thanks, will check and get back to you. Please note that NRGI is closed this week so I will only get the final comments by next week.

**Comment by charlesyoung** [comment]
Thanks. 

Lets keep the box shape squared so that it doesn't expand. Is there however a way to 'cut off' the text that extends over the box shape and replace the 'overflow' text with .......? 

I will get more feedback next week.

**Comment by birendragurung** [comment]
@charlesyoung We can limit the number of characters and replace the exceeding with ellipsis.

cc: @sweta-shrestha

**Comment by charlesyoung** [comment]
Thanks. I'm chatting to Nicola on Monday to get the final feedback. We might want to remove the "View' link but will get more clarity next week.

**Comment by charlesyoung** [comment]
Sorry one more request. Can you make the box text slightly bigger that the below text links.

**Comment by birendragurung** [comment]
@charlesyoung If everything's good, then shall we send this to production?

**Comment by charlesyoung** [comment]
Final comments below. 

- Remove the 'View' links. 
![image](https://user-images.githubusercontent.com/13888372/91944831-fb49fd80-ecfe-11ea-8d62-83ef7e2c4cc8.png)

- Add a 'Publications' heading between the boxes and the rest of the links. 
![image](https://user-images.githubusercontent.com/13888372/91944767-e40b1000-ecfe-11ea-990b-1de77123612b.png)

**Comment by man-git007** [comment]
@charlesyoung The changes you have suggested have been implemented. Please check and if all OK we will deploy to live site.

cc @anjesh @birendragurung

**Comment by charlesyoung** [comment]
Thanks @man-git007 

Can we possibly move the date further down to allow room for more text. Example below. 

![image](https://user-images.githubusercontent.com/13888372/91966812-a617e700-ed12-11ea-9e07-8247eed46e4f.png)

**Comment by man-git007** [comment]
@charlesyoung Date is adjusted according to the text in the card. But we have managed the text length. Could you please check?

**Comment by charlesyoung** [comment]
Agree, thanks. Will ask Nicola to do a final check today. 

I will then populate the page with text that we can move over to Prod.

**Comment by charlesyoung** [comment]
While we wait for final feedback from Nicola can you please capitalize analysis on the home page link (top right). Should be 'Research & Analysis'. Only noticed this today. Thanks  

![image](https://user-images.githubusercontent.com/13888372/91995886-a3c88380-ed38-11ea-8d3f-fe9c51e97803.png)

**Comment by charlesyoung** [comment]
A question from Nicola. 

Can we update the dates to the actual publication dates? The dates reflecting when we added it are somewhat misleading because as an example some of the publications are from 2019.

**Comment by charlesyoung** [comment]
@man-git007 @birendragurung just checking that you received above. Thus is the last outstanding item for Sprint 26.

**Comment by birendragurung** [comment]
@charlesyoung The changes have been deployed to the staging server. Please verify the changes.

**Comment by charlesyoung** [comment]
I dont see any publication dates?

**Comment by birendragurung** [comment]
The migration for database needs to be run. We'll have to wait till @candrei runs the migration on staging server.

**Comment by birendragurung** [comment]
@charlesyoung The migration has been ran on staging server. Please proceed with testing. Also note that the publication dates are empty for all items since the field is added recently (only on staging server, on production this will not be an issue because the publication date field is mandatory). You may set the publication dates from admin panel.

cc: @man-git007

**Comment by charlesyoung** [comment]
Many thanks @birendragurung, works well. 

Two questions however. Is there a way to allow for the capture of only the year and month for publications, like below, without a day? Also can we arrange the publication list order with the most recent, based on date, first. 

https://resourcegovernance.org/sites/default/files/documents/assessing-tunisia-upstream-petroleum-fiscal-regime.pdf

**Comment by charlesyoung** [comment]
@birendragurung just wonder if you have managed to look at above 2 comments. I'm  very keen to close out Sprint 26.

**Comment by charlesyoung** [comment]
@birendragurung any feedback? I have an interval NRGI call this week and would like to report back that Sprint 26 has been completed. 

cc @anjesh

**Comment by birendragurung** [comment]
@charlesyoung The publication dates now are shown with only month and year format(but the publication date will be stored as full date from admin panel). Also the links are ordered with most recent based on date. 
Please check the changes as let us know if we are ready to send it to production.

**Comment by charlesyoung** [comment]
Thanks @birendragurung 

The ordering looks good. 

Sorry but I don’t think I explained it properly. What I meant is that there are some publications without a day but most publications do note the full date. What I would like to have is that the day field isn’t required so that we can publish publications with both options. One showing the full date, if available, and another only showing the month and year.

**Comment by man-git007** [comment]
@charlesyoung As you are suggesting to have a feature of published date without day. For this feature, we can add a checkbox that will enable the user to ignore the day value for the selected date. For clarity, I have added some screenshots. 
![Screenshot from 2020-09-16 16-04-03](https://user-images.githubusercontent.com/23434972/93325192-a3e77980-f836-11ea-8cc7-a2847da469d2.png)
![Screenshot from 2020-09-16 16-04-14](https://user-images.githubusercontent.com/23434972/93325198-a518a680-f836-11ea-976f-8e7ebe4b5c16.png)

cc @birendragurung

**Comment by charlesyoung** [comment]
Perfect, that will work. 

Will the user just add a dummy day (like the 1st) that will be ignored in any case when published?

**Comment by birendragurung** [comment]
@charlesyoung The recent updates have been sent to staging server and will be ready to test once @candrei runs database migrations on staging server.

cc: @man-git007

**Comment by charlesyoung** [comment]
I get a crash when adding in a new publication. 

![image](https://user-images.githubusercontent.com/13888372/93586373-80dcd700-f9a8-11ea-998a-0f0b27efbf5b.png)

**Comment by charlesyoung** [comment]
@birendragurung have you had time to look at above crash? I really want to try finish this task and Sprint 26 ASAP.

**Comment by birendragurung** [comment]
@charlesyoung Sorry for the inconvenience. We had a problem in migration and have requested @candrei to run migration on the server. We will notify as soon as the migration succeeds. 

cc: @man-git007

**Comment by birendragurung** [comment]
@charlesyoung The changes have been successfully updated on the staging server. Please verify the changes and let us know if we are ready to go for production.

**Comment by charlesyoung** [comment]
Thanks @birendragurung 

I will get internal feedback later today. Hope to be able to move this to the Prod site by tomorrow.

**Comment by charlesyoung** [comment]
Please move this to the Prod site. Can I ask that you also copy over the publications because I would prefer not to do it again. Thanks

**Comment by birendragurung** [comment]
@charlesyoung This has been deployed to the production servers.

**Comment by charlesyoung** [comment]
Thanks

**Comment by charlesyoung** [comment]
@man-git007 I'm busy applying the Research and Analysis page translations. Some questions.

- How do I translate the Publications heading? 
- As you can see from below image the dates (French as an example) do not change when another language is selected. 

![image](https://user-images.githubusercontent.com/13888372/115523197-1e74ed80-a28d-11eb-960c-712d2ec818d8.png)

**Comment by man-git007** [comment]
@charlesyoung The French and Arabic translations can be added from the edit [page](https://staging.resourcecontracts.org/admin/research-and-analysis/10/edit).

![Screenshot from 2021-04-22 09-56-58](https://user-images.githubusercontent.com/23434972/115654623-37df6d80-a351-11eb-8b58-95e55643ff07.png)

![Screenshot from 2021-04-22 09-57-11](https://user-images.githubusercontent.com/23434972/115654621-36ae4080-a351-11eb-8408-e64f785179db.png)

**Comment by charlesyoung** [comment]
@man-git007 I understand that is where the title can be translated but where are the date and 'Publication' title text translated.

**Comment by man-git007** [comment]
@charlesyoung The Publication and date cannot be changed from the admin panel. We need to translate the 'Publication' title from code and regarding the date translation that needs to change from the code also and will take some time

**Comment by charlesyoung** [comment]
@man-git007 YI seriously needs to factor these things into the design and development process. It's ridiculous and not sustainable that we need to ask YI to update text from code.

**Comment by man-git007** [comment]
@charlesyoung Sorry for the inconvenience, the publication title, and dates that you have mentioned are normally controlled and translated from the codebase. Such texts are also on the homepage and are being maintained from the code. We both have missed out on the text and date translation during the design, development, and testing phase. The French translation of the `Publication` will be `Les publications` and the date conversion should be done from code. We will work on it.

cc @anjesh

**Comment by charlesyoung** [comment]
We need to be designing elements of RC /OLC with sustainability in mind so that we dont have to update the code for minor changes. 

How much time will it take?

**Comment by man-git007** [comment]
@charlesyoung About 0.5 hr

**Comment by charlesyoung** [comment]
OK thanks.

**Comment by man-git007** [comment]
@charlesyoung Could you please check the [staging](https://staging.resourcecontracts.org/research-and-analysis) site?

**Comment by charlesyoung** [comment]
Looks good. I'm busy getting all the translations.

**Comment by man-git007** [comment]
@charlesyoung Shall I deploy to the live server?

**Comment by charlesyoung** [comment]
Let me first get you the translations i.e 'Publications' in Arabic, etc.

**Comment by man-git007** [comment]
@charlesyoung Can we deploy this on the live site?

**Comment by charlesyoung** [comment]
Thanks @man-git007 

Please see below Google Sheet link noting the French and Arabic translations for 'Publications'. 

https://docs.google.com/spreadsheets/d/1kQg8wJcW1nP6EywMs35PGco9-i0C7xiYlhIZ2ygdZis/edit#gid=0

**Comment by man-git007** [comment]
@charlesyoung The changes have been implemented in the [live](https://resourcecontracts.org/research-and-analysis?lang=ar) site.

**Comment by charlesyoung** [comment]
Thanks
