### ISSUE TITLE
Business-humanrights.org / ResourceContracts.org API Integration

### ISSUE THREAD

**Issue by alexg0581** [NRGI/resourcecontracts.org#1308]
## Why
We’re currently in the process of a substantial website rebuild of business-humanrights.org, and are looking to also rebuild our integration with the ResourceContracts / OpenLandContracts API. Currently when you carry out a search on our website, the query terms are also passed to RC / OLC and the filtered search results returned. However, in reimplementing the feature we’re having some trouble with passing a query to the Search Contracts endpoint, and it doesn’t seem to be filtering based on the query parameters we’re defining.

## What
For example, `contracts/search?group=metadata|annotations|text&q=shell&sort_by=year&order=desc` returns 
 
`<b>Warning</b>:  array_push() expects parameter 1 to be array, null given in <b>/var/www/rc-api/app/Services/FulltextSearch.php</b> on line <b>148</b><br />`
 
Along with a “total” of 3228, which would appear to be every document on the site.

**Comment by man-git007** [comment]
@alexg0581 The `warning` message in API endpoint has been fixed.

cc @anjesh

**Comment by alexg0581** [comment]
Fab, thank you!
