### ISSUE TITLE
Search results problem -- tally wrong and irrelevant main doc not grayed out

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#1309]
In this filter search, the main doc is not a decree, so should be greyed out.

And the tally should read 3, not 0.
https://www.openlandcontracts.org/search/group?q=&company_name%5B%5D=SG+Sustainable+Oils+Cameroon+PLC&company_name%5B%5D=Sithe+Global+Sustainable+Oils+Cameroon+Limited&document_type%5B%5D=Decree
![image](https://user-images.githubusercontent.com/12913915/87719372-432db900-c781-11ea-9a49-042d946bdd3a.png)

**Comment by SamCCSI** [comment]
cc @charlesyoung @anjesh does this problem come from the new grouping functionality?

**Comment by charlesyoung** [comment]
I think it does relate to the new grouping functionality. I logged below issue where the tally shows 2 docs but there is nothing in the list, when running a free text search. 

![image](https://user-images.githubusercontent.com/13888372/87756820-e5917f00-c809-11ea-88c4-a95793ef3e05.png)

**Comment by SamCCSI** [comment]
Another example of both problems

![image](https://user-images.githubusercontent.com/12913915/88059400-cb6dde80-cb32-11ea-8b6b-d0e7b08e8fed.png)

**Comment by charlesyoung** [comment]
@SamCCSI is this still a problem?

**Comment by SamCCSI** [comment]
The tally problem has been resolved.

But when the main doc is not a search result it should appear greyed out -- right now it is in black.

![image](https://user-images.githubusercontent.com/12913915/89782734-d689ae00-dae3-11ea-859f-218f28b76a27.png)
![image](https://user-images.githubusercontent.com/12913915/89782747-da1d3500-dae3-11ea-8f27-3479f162bdcb.png)

**Comment by charlesyoung** [comment]
@SamCCSI has this been resolved?

**Comment by SamCCSI** [comment]
no, still waiting for the below to be fixed @charlesyoung @anjesh 

> The tally problem has been resolved.
> 
> But when the main doc is not a search result it should appear greyed out -- right now it is in black.
> 
> ![image](https://user-images.githubusercontent.com/12913915/89782734-d689ae00-dae3-11ea-859f-218f28b76a27.png)
> ![image](https://user-images.githubusercontent.com/12913915/89782747-da1d3500-dae3-11ea-8f27-3479f162bdcb.png)

**Comment by charlesyoung** [comment]
@SamCCSI can we close this ticket?

**Comment by SamCCSI** [comment]
@charlesyoung @anjesh the below issue is still outstanding.

> The tally problem has been resolved.
> 
> But when the main doc is not a search result it should appear greyed out -- right now it is in black.
> 
> ![image](https://user-images.githubusercontent.com/12913915/89782734-d689ae00-dae3-11ea-859f-218f28b76a27.png)
> ![image](https://user-images.githubusercontent.com/12913915/89782747-da1d3500-dae3-11ea-8f27-3479f162bdcb.png)

**Comment by charlesyoung** [comment]
@SamCCSI is this still an issue? Please send me the query you are running if not yet resolved.
