### ISSUE TITLE
Metadata: "Jurisdiction of Incorporation" must be ISO-3166

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#131]
Currently the field is a free test string. 

Additionally: Is the currently applied country list the official ISO-3166?

**Comment by anjesh** [comment]
We are using IATI codelist http://iatistandard.org/201/codelists/Country/ which uses 3166 Alpha-2 codes.
https://github.com/NRGI/resourcecontracts.org/issues/28#issuecomment-110592274
