### ISSUE TITLE
Security advisory on lodash

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1310]
@candrei will you be able to look at below security issues. 

https://github.com/NRGI/resourcecontracts.org/network/alert/package-lock.json/lodash/open

cc @anjesh

**Comment by candrei** [comment]
@anjesh I think you're better suited to decided how to mitigate the security warnings related to the software packages in use within the app. Over to you, please see the complete list below:
<img width="1040" alt="Screen Shot 2020-07-20 at 7 31 55 PM" src="https://user-images.githubusercontent.com/6289513/87996292-b73cc980-cabf-11ea-85c5-17e823805d2c.png">

**Comment by charlesyoung** [comment]
@anjesh can you please look at this and let me know how much time will be required.

**Comment by charlesyoung** [comment]
@iprunache can we close this ticket?

**Comment by candrei** [comment]
@charlesyoung closing, we'll open separate one(s) as needed.
