### ISSUE TITLE
Update DRC country site 

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#1311]
## Why

DRC country site is hosted in a different domain in a separate server https://www.mines-rdc.cd/resourcecontracts/. The source code is updated manually there and was lasted updated in 2017 only. The site is not working as there's recent changes in the API and in the homepage. 

## What

We need to investigate the server compatibility and update the code to reflect the new changes and make the site running.

**Comment by charlesyoung** [comment]
@anjesh how long will this take? We can possibly look at using a couple of hours from the budget buffer.

**Comment by man-git007** [comment]
@charlesyoung We need to upgrade the PHP version and enable the mechanism of auto-deployment. Another way is that we can clone the project itself in the server and git pull every time change in the master branch. Ideally PHP version upgrade can be to any version but the minimum upgrade should be php5.5. Also, we might need to upgrade the composer version as well.

cc @anjesh

**Comment by anjesh** [comment]
@charlesyoung the issue is its current php version in the DRC server. They already have other apps installed in the same shared server so php upgrade might be tricky.

**Comment by charlesyoung** [comment]
Is this the time I need to chat to the client and suggest that we host the DB and the code? 

Can you give me some info that could strengthen our case?

**Comment by candrei** [comment]
@anjesh @charlesyoung as far as I can tell there are multiple PHP versions on that server. The mines-rdc.cd project runs on top of PHP 7.3: https://www.mines-rdc.cd:2083/cpsess0898305670/frontend/paper_lantern/multiphp_manager/index.html#/config/
<img width="1543" alt="Screen Shot 2020-07-30 at 3 53 26 PM" src="https://user-images.githubusercontent.com/6289513/88968123-d6d0b080-d27c-11ea-9a3a-006b0b25e03f.png">

The binary is available at: 
```
-bash-4.1$ /opt/cpanel/ea-php73/root/usr/bin/php --version
PHP 7.3.20 (cli) (built: Jul 14 2020 19:15:20) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.20, Copyright (c) 1998-2018 Zend Technologies
    with the ionCube PHP Loader + ionCube24 v10.4.0, Copyright (c) 2002-2020, by ionCube Ltd.
    with Zend OPcache v7.3.20, Copyright (c) 1999-2018, by Zend Technologies
```

As to `composer`, they have a decently new version:
```
-bash-4.1$ composer --version
Composer version 1.8.6 2019-06-11 15:03:05
```

**Comment by charlesyoung** [comment]
Thanks @candrei 

So we don't have to upgrade the versions of PHP or Composer as previously anticipated? How can we move this forward? The Minister of Mines was asking yesterday how quickly we can get the site up and running because he is giving a presentation to cabinet on contact disclosures on Monday.

**Comment by man-git007** [comment]
@candrei As I was working on DRC, I found out that we need to have PHP 7.0. Could you please install the PHP 7.0.

cc @anjesh @charlesyoung

**Comment by man-git007** [comment]
@charlesyoung  We have fixed the [DRC](https://www.mines-rdc.cd/resourcecontracts/) country site. Could you please verify. As the deployment of this site is manual, we need to rethink the deployment of this site. For now, any changes in this country site would have to be done manually which is inefficient.

@candrei  Regarding the installation of PHP7.0, ignore this for now.

cc @anjesh

**Comment by charlesyoung** [comment]
Thanks @man-git007 

The site was deployed in 2017 and I think we have had to sort out issues only twice so I don't think its a major problem. The Ministry wants to host the site so we don't have much of a choice. 

Some issues noted
- The home page background has changed and is incorrect (seems like an OLC image). Can you please add the original RC DRC background image. 
- The fonts look different from the other country pages

![image](https://user-images.githubusercontent.com/13888372/89025964-199b9280-d328-11ea-8d32-16967bd036d2.png)

![image](https://user-images.githubusercontent.com/13888372/89025981-261feb00-d328-11ea-81b1-a97bc8320fe3.png)

**Comment by man-git007** [comment]
@charlesyoung Could you provide me the image. So that it can be uploaded from the admin site.

**Comment by charlesyoung** [comment]
I don't have it. Why can't you find the original image?

**Comment by charlesyoung** [comment]
![DRC Home page](https://user-images.githubusercontent.com/13888372/89034073-84ed6080-d338-11ea-8ca5-74874540f333.jpg)

here it is although I also get the AWS Access Key Id you provided does not exist in our records error

**Comment by charlesyoung** [comment]
The error message "The AWS Access Key Id you provided does not exist in our records" indicates that there's an issue with the credentials that you're using. The access key that you're using might have been deleted, or the associated AWS Identity and Access Management (IAM) role or user might have been deleted.

**Comment by man-git007** [comment]
@charlesyoung For now, the image has been updated manually. Need to work on the AWS credentials in the env file.

cc @anjesh

**Comment by charlesyoung** [comment]
OK thanks, I might find a better image next week. Have a good weekend.

**Comment by anjesh** [comment]
@charlesyoung just that you know this is manually fixed for now, so any changes in future needs to be manually fixed again, unless it gets auto-deployed along with other country sites. We spent 5 hours in getting this site updated and fixed.
