### ISSUE TITLE
Child contract reindex in ES upon change in admin side

### ISSUE THREAD

**Issue by man-git007** [NRGI/resourcecontracts.org#1312]
## Why
Child contract may vary in subsite listing page 

## What
Child contract should be reindexed in ES if its parent contract changes

## Notes
Need to automate the indexing of child contract or need to manually reindex from admin site via publish/unpublish feature

**Comment by anjesh** [comment]
This fix will ensure that when the parent contract changes child contracts, the child contracts also get auto-indexed without having to find the child contracts and manually re-publish it inorder to list it under new parent contracts. Currently this has caused some confusions in the search result.

**Comment by man-git007** [comment]
@anjesh Deployed to the production site and issue closed.

**Comment by anjesh** [comment]
spent around 6 hours of work in fixing this.

**Comment by charlesyoung** [comment]
Thanks. OK so we have used up all of the buffer budget.
