### ISSUE TITLE
Mimicing document grouping in Excel download (RC only)

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#1313]
Followup from https://github.com/NRGI/resourcecontracts.org/issues/1096#issuecomment-669769539, document grouping is implemented in the main site however in excel download, the documents are listed randomly. It would be good to have similar listing in the excel.

**Comment by anjesh** [comment]
@charlesyoung could you give us some idea on how you are thinking about grouping in excel. Just maintain the order only or have some kind of grouping within excel (need to think what that would look like though).

cc @man-git007

**Comment by charlesyoung** [comment]
This is how it currently downloads the data (random) 

![image](https://user-images.githubusercontent.com/13888372/89789889-803b6000-db21-11ea-9f6e-3ac8a180c57b.png)

We could look at removing the Category column and replacing it with a new column named 'Association' which notes either Main or Supporting. Signature Date could also be moved. The ordering, etc should be the same as how the document grouping has been implemented.  

![image](https://user-images.githubusercontent.com/13888372/89792172-79621c80-db24-11ea-8f94-8759841d8bff.png)

@SamCCSI let me know of you have any comments if you also want this for OLC. 

@anjesh how long will this take to develop?

**Comment by anjesh** [comment]
This might take around 7-10 hours.

**Comment by charlesyoung** [comment]
Please hold.

**Comment by charlesyoung** [comment]
@anjesh I'm going to budget 8 hours for this activity.

**Comment by anjesh** [comment]
Might take a little long than 8 hours - around 1.5 days of work.

**Comment by charlesyoung** [comment]
@anjesh can we have different document xls download formats for RC and OLC? 

So for example for RC we would like to remove the 'Category', 'Contract Identifier' and 'Government Identifier' columns as well as move the 'PDF URL' column to after the 'Contract Name' column. We also want to rename the 'PDF URL' column to 'Document Link' and hyperlink the links.

**Comment by anjesh** [comment]
Yes, we could have different downloads for RC and OLC but it will add some more hours.

**Comment by charlesyoung** [comment]
Hours updated from 12 to 16.

**Comment by surazneupane** [comment]
@charlesyoung  Can you verify if all data are correct in Staging server?

**Comment by charlesyoung** [comment]
The list needs to group the docs (main first followed by supporting) as displayed on the site (like below). 

![image](https://user-images.githubusercontent.com/13888372/102589191-528da580-4117-11eb-8358-6912b2b20b2c.png)

Can we also populate the Key Clauses and Clause Summary columns when the info is available? 

Also, rename Key Clauses to Key Clause. 

Many thanks.

**Comment by surazneupane** [comment]
@charlesyoung  can you verify in staging if grouping of documents are fine?
And i am little bit confused on how to populate key clauses .should key clauses be separated by semi-colon? Thanks !

**Comment by charlesyoung** [comment]
@surazneupane any idea why I got below message via email but why it's not added to this ticket? 

@charlesyoung can you verify in staging if grouping of documents are fine?
And i am little bit confused on how to populate key clauses .should key clauses be separated by semi-colon? Thanks !

**Comment by charlesyoung** [comment]
The grouping is looking good. 

Can you, however, please sort just like we do on the RC site i.e. by date with the most recent main docs published first. Supporting docs also need to be sorted by date with the most recent published first. Take a look at the RC contracts list to see how its displayed. 

Good question re the clauses, let me think about it.

**Comment by surazneupane** [comment]
@charlesyoung  can you please verify the output at staging server. And Please also verify the result of key clauses search excel download , as i am seeing a single document contains same key clause with their corresponding clause summary multiple times, the documents are repeating . Please check if the outputs are okay . Thanks!

**Comment by surazneupane** [comment]
@charlesyoung  re mentioning if  all is ok at staging. Thanks!

**Comment by surazneupane** [comment]
@charlesyoung  can you verify if all good and can this be moved to production?

**Comment by charlesyoung** [comment]
Please check because I'm getting a blank xls. 

![image](https://user-images.githubusercontent.com/13888372/103646566-8d3e6d00-4f62-11eb-9730-4725b6759425.png)

**Comment by charlesyoung** [comment]
@surazneupane pls take a look at the above issue.

**Comment by surazneupane** [comment]
@charlesyoung  yes i can see the empty xls . but key clauses filter are giving us data in xls . This might be due to upgrade in elastic search. We are working on to solving this issue . @iprunache  can you please email the changes on credentials in staging. Thanks!

**Comment by iprunache** [comment]
@surazneupane what email address should I use to send the ES staging credentials?

If there's anything else I can help with regarding the upgrade to ES 7.x, let me know.

**Comment by surazneupane** [comment]
please send at suraznep@gmail.com @iprunache

**Comment by iprunache** [comment]
@surazneupane I've sent the credentials. Please also keep me updated if the issue is related to ES 7.x.

**Comment by surazneupane** [comment]
@iprunache 
Thank you,I think there is some dirty data at staging server .
**Staging API excel download  URL:**
[api.staging-resource/contracts/search?q=&country_code=ph&corporate_group&company_name&contract_type&document_type&language&year&resource&group=metadata|text|annotations&annotation_category&sort_by&order&per_page=10&from=0&all=0&download=true&annotated&category=rc](url)
**Production API excel download  URL:**
[](http://api.resourcecontracts.org/contracts/search?q=&country_code=ph&corporate_group&company_name&contract_type&document_type&language&year&resource&group=metadata|text|annotations&annotation_category&sort_by&order&per_page=10&from=0&all=0&download=true&annotated&category=rc
)
Please can you check above both links  . I think there is some dirty data in staging that gives error while downloading the excel file. I came to find out that the document error document belongs to philippines thanks !

**Comment by surazneupane** [comment]
Thank you,I think there is some dirty data at staging server .
Staging API excel download  URL:

api-staging.resourcecontracts.org/contracts/search?q=&country_code=ph&corporate_group&company_name&contract_type&document_type&language&year&resource&group=metadata|text|annotations&annotation_category&sort_by&order&per_page=10&from=0&all=0&download=true&annotated&category=rc
Production API excel download  URL:

api.resourcecontracts.org/contracts/search?q=&country_code=ph&corporate_group&company_name&contract_type&document_type&language&year&resource&group=metadata|text|annotations&annotation_category&sort_by&order&per_page=10&from=0&all=0&download=true&annotated&category=rc

Please can you check above both links  . I think there is some dirty data in staging that gives error while downloading the excel file. I came to find out that the document error document belongs to philippines and might be a supporting document. Thanks !

**Comment by charlesyoung** [comment]
There should be no dirty data in the staging DB because it’s basically a replica of the Prod DB.

**Comment by iprunache** [comment]
Thanks, @surazneupane , I'll look into that.

Charles, Suraj might be onto something here. When I switched staging to ES 7.x recently, I used a production clone reindexed for 7.x that was a few weeks old. That might be out of sync with the application database if the mentioned document was modified recently.

I'll clone staging again from production to see if it fixes the issue.

**Comment by charlesyoung** [comment]
Ok thanks. Don’t think we modified any Philippines documents but it’s worth doing a clone again.

**Comment by iprunache** [comment]
@surazneupane I cloned the production ES indices to staging. The new staging index prefix is `rc_staging_1`.

The results for the API requests you linked above are identical for prod and staging but I still get a blank Excel when I try to download all documents. Please have another look.

**Comment by surazneupane** [comment]
@iprunache 
This issue might be due to staging API pointing to wrong index. Using the staging index you provided which is **rc_staging_3_master** in local there is no issue. Also to verify we uploaded a new testing contract in staging admin side and published the contract but it is not showing in the staging subsite. I think the staging API must be pointing to **rc_staging_1_master.** Could you please verify the index API is pointing . if so could you change the API elastic search index to **rc_staging_3_master** .
cc @charlesyoung  @man-git007

**Comment by iprunache** [comment]
@surazneupane earlier today I recreated the staging environment as a fresh clone from production so I had to create new indices. I mentioned in the previous comment that the new indices prefix is `rc_staging_1`.

Unfortunately, I only updated `rc-api` with the new prefix and forgot about `rc-index`. Sorry for wasting your time with that.

That being said, the API now returns the same content for the 2 requests you posted earlier, both on staging and production.

Since `rc_staging_3` also works fine on local then perhaps the `staging` branch is in a bad state. I recommend looking at that too.

**Comment by iprunache** [comment]
Just to reconfirm, both http://api-staging.resourcecontracts.org/ and http://index-staging.resourcecontracts.org/ are using the `rc_staging_1` indices now which are production clones I made today.

The excel download and the Phillipines page are still not working on staging.resourcecontracts.org.

@surazneupane I'd like to delete the `staging` branches for both `rc-subsite` and `rc-api` and recreate them from master then deploy them to the staging environment to confirm we don't have a data issue. After that you would merge again to `staging` the changes you have in progress for both repos.

This would give us a clean slate and allow us to test in a controlled environment. Do you agree with this approach?

**Comment by surazneupane** [comment]
@iprunache  i have checked with staging branch on my local machine as well it is working well there with INDICES_PREFIX **rc_subsite_3** .
We have solved some issues on the index **rc_subsite_3** so it will be great for testing if API INDICES_PREFIC will point to **rc_subsite_3** index . Thanks

**Comment by iprunache** [comment]
@surazneupane what issues did you fix? Is it corrupted data or something with the index mapping?

Because those issue must also exist in production since staging is not working with the production clone. And we'll likely have to fix them there.

**Comment by surazneupane** [comment]
@iprunache  didnot seen any error on production api-url .
 But there was a small error on supporting contract of Philippines( whose id was found to be 1086) which didnot contained its parent_contracts field . 
It will be easy if API-index will point to **rc_admin_3** for testing staging site . Thanks

**Comment by iprunache** [comment]
Thanks @surazneupane for pointing to the corrupted contract!

I'll switch to `rc_admin_3` shortly but I need to understand where the data error comes from first. Because I just created a production clone today and it seems that the staging branch doesn't work with it. We'll have the same issue when we deploy to production so I want to figure out what's going on.

**Comment by iprunache** [comment]
I'll give you an update once I switch staging back to `rc_admin_3`.

**Comment by iprunache** [comment]
@surazneupane I switched staging back to `rc_staging_3`. Thank for looking into this.

Did you also update `1086` in production to fix the data issue?

I realized that even though the data was corrupted in production too, the issue was manifesting just on staging because `DEBUG` is enabled and the error was reported in the API response as a **Notice**.

**Comment by surazneupane** [comment]
@iprunache  now we can see the data in xls in staging.
After solving the corrupted data and we havenot  solved any data in production .
Cc @charlesyoung  @man-git007

**Comment by iprunache** [comment]
@surazneupane I've seen this activity on production which seems related to the corrupted contract and I thought it was you:
```
Krominco, Incorporated - MPSA No. 291-2009-XIII (Surigao Mineral Reservation), 2009 | Contract metadata status updated from completed to publishedby admin On January 08, 2021 at 11:10 AM
Krominco, Incorporated - MPSA No. 291-2009-XIII (Surigao Mineral Reservation), 2009 | Contract metadata status updated from draft to completedby admin On January 08, 2021 at 11:10 AM
Krominco, Incorporated - MPSA No. 291-2009-XIII (Surigao Mineral Reservation), 2009 | Contract updatedby admin On January 08, 2021 at 11:10 AM
```

**Comment by surazneupane** [comment]
@charlesyoung  @iprunache  we may be not getting data on **staging** currently . its because **staging** branch currently is not in clean state .  we will re-create the **staging** branch from **master** then everyting will work fine as i have already checked it on local machine . Thanks !

**Comment by surazneupane** [comment]
@charlesyoung  can you verify at staging please . Thanks !

**Comment by charlesyoung** [comment]
@surazneupane can you please drop the Key Clause and Clause Summary columns from the general download xls. We will only have these columns when running a search for clauses. (again only for RC)

How does the ordering work? On the page display, the Sabril docs follow directly after the Proton Cuarzos docs but in the xls its not the case. 

![image](https://user-images.githubusercontent.com/13888372/104153216-711b4f80-53ea-11eb-8117-9da7232bfa21.png)

**Comment by surazneupane** [comment]
@charlesyoung  please verify the order of documents in xls. Thanks !

**Comment by charlesyoung** [comment]
Looks good. 

Couple changes before you can move to Prod.
- Bold the first row
- Add hyperlinks to the 2 columns with links

**Comment by surazneupane** [comment]
@charlesyoung  i have added hyperlinks to all columns with links . please verify at staging .

**Comment by charlesyoung** [comment]
Good to go. 

We are however having the same issues with the hyperlinks not opening. 

This must relate to the GH security or ES updates 

cc @iprunache

**Comment by surazneupane** [comment]
@charlesyoung  can we move to production? 
The links are working perfectly on my machine cant figure out the problems.  Thanks!

**Comment by charlesyoung** [comment]
Yes please move over. 

The hyperlink issue is well an issue that I just discussed with @man-git007 that relates to our server setup.

**Comment by surazneupane** [comment]
@charlesyoung  if everything is good for this ticket . Can this issue be closed ? Thanks !
