### ISSUE TITLE
Guides / resources page (French) has dead links 

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#1315]
All the resources here work: https://www.openlandcontracts.org/guides?lang=en

At the French version of the page they all don't work: https://www.openlandcontracts.org/guides?lang=fr

I'm thinking it relates to changes made to home or guide page?

cc @anjesh @man-git007 

![image](https://user-images.githubusercontent.com/12913915/90826143-f3a25600-e307-11ea-9857-dcb0c301ffd1.png)

**Comment by man-git007** [comment]
@SamCCSI The issue is not caused by changes in the home or guide page. As the content of the page is managed in the admin side of OLC itself, the links of the pdf might have updated or the AWS credentials might have changed which is causing this issue.

cc @anjesh

**Comment by SamCCSI** [comment]
Thanks @man-git007 -- I've copied links from English version.
