### ISSUE TITLE
Change French contact page title

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#1317]
We need to change [this page](https://www.openlandcontracts.org/contact?lang=fr)'s link title (see red circle in image below) to from "Contrat" to "Nous contacter" 

I tried to do it myself but couldn't see a place to make this change. Could you please help? cc @anjesh @man-git007 

![image](https://user-images.githubusercontent.com/12913915/92121390-37956080-edc8-11ea-8340-59cd8fa66059.png)

**Comment by man-git007** [comment]
@charlesyoung Is it both for RC and OLC?

**Comment by SamCCSI** [comment]
OLC only

**Comment by charlesyoung** [comment]
@man-git007 please include the time estimate.

**Comment by man-git007** [comment]
@charlesyoung The time estimate would be 0.75hrs

**Comment by charlesyoung** [comment]
@man-git007 please work on this ticket. Thanks

**Comment by charlesyoung** [comment]
@man-git007 just checking how far you are with this issue? Thanks

**Comment by man-git007** [comment]
@charlesyoung This issue seems to be already resolved on the [live](https://www.openlandcontracts.org/contact?lang=fr) site.

**Comment by charlesyoung** [comment]
@SamCCSI can we close this ticket?
