### ISSUE TITLE
API Error

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1318]
@anjesh not sure if this is related to #1308 but I was contacted this morning my a researcher from Verona University in Italy who noted that they get the following error when using the RC API. Do you possibly know what could be causing the error? 

"{"error":{"code":400,"message":"The API you are currently looking is not available."}}"

**Comment by anjesh** [comment]
Not sure Charles. That issue was fixed then. What is the API end point they are using?

**Comment by tomazzoli** [comment]
REQUEST : http://api.resourcecontracts.org/contracts/741
ANSWER:{"error":{"code":400,"message":"The API you are currently looking is not available."}}

REQUEST: http://api.resourcecontracts.org/contracts/741/metadata
ANSWER:{"error":{"code":400,"message":"The API you are currently looking is not available."}}

REQUEST:http://api.resourcecontracts.org/contracts
ANSWER:{ "total": 3306, "per_page": 25, "from": 0, "results": [ { "id": 741, "open_contracting_id": "ocds-591adf-9864231586", "name": "Island Oil Belize Ltd., PSA, 2004".....
so id 741 shold be a valid id.
Browser: firefox 80.0.1 on a macosx 10.13.6

**Comment by charlesyoung** [comment]
Thanks @tomazzoli 

@anjesh please see above.

**Comment by candrei** [comment]
@tomazzoli it looks like the first couple of URLs are invalid, please notice the correct URLs should read:
- https://api.resourcecontracts.org/contract/741/metadata
or
- https://api.resourcecontracts.org/contract/741/text
ir
- https://api.resourcecontracts.org/contract/741/annotations
etc
(cc @charlesyoung)

**Comment by candrei** [comment]
@tomazzoli for reference, here's the wiki page describing the available endpoints: https://github.com/NRGI/resourcecontracts.org/wiki/API

**Comment by tomazzoli** [comment]
Thanks so much. It works.
