### ISSUE TITLE
Metadata: Add dropdown list for "Corporate Group"

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#132]
This shall have a picklist, which might be generated by NRGI in a separate repository. 

This issue will await the appropriate solution which is being developed for ResourceProjects.org

**Comment by anjesh** [comment]
linked to https://github.com/NRGI/resourcecontracts.org/issues/142

**Comment by anjesh** [comment]
Moving to sprint 6, need list for this.

**Comment by anderspeders** [comment]
Postponing this for now.

**Comment by anjesh** [comment]
Need to pull the corporate group from opencorporates using auto-suggest.
e.g. https://opencorporates.com/corporate_groupings/tullow+oil

**Comment by anjesh** [comment]
linked to #142

**Comment by anjesh** [comment]
duplicate of https://github.com/NRGI/resourcecontracts.org/issues/179
closing this issue.
