### ISSUE TITLE
Change the menu/navigation bar 

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1320]
Change the menu/navigation bar, on the left, to align with the links at the bottom of the page. Below outlines the updated menu/navigation bar. 

![image](https://user-images.githubusercontent.com/13888372/97183281-4421ae00-17a6-11eb-84b2-9cfa28300024.png)

This only applies to RC and not OLC.

**Comment by charlesyoung** [comment]
@anjesh I'm going to budget 5 hours for this activity. Let me know if that is OK.

**Comment by surazneupane** [comment]
![Screenshot from 2020-12-07 14-16-40](https://user-images.githubusercontent.com/37624741/101327630-0af55700-3897-11eb-8ee1-7e72ace370bc.png)
![Screenshot from 2020-12-07 14-17-03](https://user-images.githubusercontent.com/37624741/101327642-1052a180-3897-11eb-95f7-d7f24409b9f4.png)

@charlesyoung  can you review it if it is okay? Thanks !

**Comment by charlesyoung** [comment]
Thanks. I'm having the same caching issue asl on Friday. Will test later. Can I ask that you make the navbar text the same as want is noted in the footer. So change 'About ResourceContracts' to 'About' and change Frequently Asked Questions' to FAQS".

**Comment by charlesyoung** [comment]
@surazneupane I still can't see the updates.

**Comment by charlesyoung** [comment]
Updates look good. Just please update the 2 changes mentioned. Thanks

**Comment by surazneupane** [comment]
@charlesyoung  can you see the change in staging server now?

**Comment by charlesyoung** [comment]
Thanks. Can you please deploy to Prod? Can I ask that you rename FAQS to FAQs (in the navbar)?

**Comment by surazneupane** [comment]
@charlesyoung  can you verify if all good in staging server before deploying to production? Thanks !

**Comment by charlesyoung** [comment]
Good to go to Prod.

**Comment by surazneupane** [comment]
@charlesyoung  we have updated it to production . Can you see the changes And Can this issue be closed?
