### ISSUE TITLE
Change 'Recent Documents' text 

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1321]
Change the 'Recent Documents' text on the home page and the advanced search toolbar because it makes it seem as if the contracts are recent (new) which is not the case. The new wording should be 'Recently Added'. 

This only relates to RC and not OLC. 

cc @SamCCSI

**Comment by charlesyoung** [comment]
@anjesh I'm going to budget 4 hours for this activity. Let me know if that is OK.

**Comment by surazneupane** [comment]
@charlesyoung  this has been done and deployed in the staging (https://staging.resourcecontracts.org) server. Could you please verify it .  if all ok we will deploy in live server.

cc @man-git007

**Comment by charlesyoung** [comment]
Thanks @surazneupane 

Looks good, let me however get approval before moving to the Prod site.

**Comment by charlesyoung** [comment]
Please move to the Prod site. Thanks

**Comment by surazneupane** [comment]
@charlesyoung  we have moved it to  production site .
Can this issue be closed? Thanks

**Comment by charlesyoung** [comment]
Not seeing it yet. Have removed image cache but still not updating. Will try later and close the ticket if all good.

**Comment by surazneupane** [comment]
@charlesyoung  now you can see change in production.
