### ISSUE TITLE
Add search by OCID to backend

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#1322]
@anjesh do you have a sense of how many days it would take YI to add this feature to this page http://admin.resourcecontracts.org/contract ?

**Comment by anjesh** [comment]
You mean search by OCID like ocds-591adf-3906951154? Should be around .75 day of work - fix in the code, testing, deployment.

**Comment by SamCCSI** [comment]
Thanks @anjesh for your recent email. Let's proceed to implement this, then. Should it be included in any specific sprint number?

**Comment by SamCCSI** [comment]
@anjesh it's also my hoope that the OCID search field would be included in this section, along with other back-end contract search functionality
![image](https://user-images.githubusercontent.com/12913915/96735192-4db3ac00-1389-11eb-866c-6658da720d47.png)

**Comment by anjesh** [comment]
Yes @SamCCSI i am thinking to include OCID and title in the same box like shown below. Does that look ok to you?

![image](https://user-images.githubusercontent.com/120488/96736063-f1c64300-13db-11eb-88f7-f22d1c7f3dd9.png)

cc @charlesyoung

**Comment by SamCCSI** [comment]
Thanks @anjesh I am happy for it to be combined as you propose or for a separate field for OCID. Both fine, depending on what will work best and be least complicated to implement and maintain in practice.

**Comment by man-git007** [comment]
@SamCCSI We have added the OCID filter to the [admin site](https://admin-staging.resourcecontracts.org/contract). Please verify and if OK we will deploy it on the live server

**Comment by SamCCSI** [comment]
@man-git007 could you please help me set up a login for that part of the staging site? I can't log in.

**Comment by charlesyoung** [comment]
I just did, will email you the log in details.

**Comment by SamCCSI** [comment]
@man-git007 confirming that this works nicely. Please deploy.

**Comment by anjesh** [comment]
Deployed and working in prod.

![image](https://user-images.githubusercontent.com/120488/99762820-76ae9480-2b21-11eb-9e0f-05142d3604a1.png)
