### ISSUE TITLE
MT resubmit not possible

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#1323]
A batch of contract MT jobs were auto approved because no one reviewed them in time.

We want to resubmit them to MT but when we try there is no longer a button to send to MT after rating it as RED.

@anjesh any idea how to get around this? cc @charlesyoung 

![image](https://user-images.githubusercontent.com/12913915/96303173-fa77dd00-0fc7-11eb-9824-74efebd5f47f.png)

**Comment by SamCCSI** [comment]
These three need a new submission to MTurk (they are some of the ones whose time to reject elapsed and bad transcriptions got accepted). We cannot resubmit, however, with our current system. 
https://admin.resourcecontracts.org/contract/3817
https://admin.resourcecontracts.org/contract/3829
https://admin.resourcecontracts.org/contract/4118

Can YI please advise

**Comment by charlesyoung** [comment]
@man-git007 what is the latest with this ticket? I'm on leave from tomorrow.

**Comment by man-git007** [comment]
@charlesyoung We will work on this ticket after [this ticket](https://github.com/NRGI/resourcecontracts.org/issues/676).

cc @sriza

**Comment by sriza** [comment]
@SamCCSI 
Currently, the auto-approval of MTurk assignment occurs in 30 days. 
The assignment once approved cannot be rejected. However, we can add `Reset` button for the reset of `Approved` HIT in the MTurk view page of the contract as shown in image below.
![image](https://user-images.githubusercontent.com/24825118/147455309-aa154b82-53a6-4ae5-9dc1-2f51acc957a2.png)

cc @man-git007 @anjesh

**Comment by sriza** [comment]
@charlesyoung @SamCCSI 
Should we go ahead with the implementation of the `Reset` button for `Approved` HIT?

cc @man-git007 @anjesh

**Comment by charlesyoung** [comment]
Thaks @sriza 

I don't follow your suggestion of adding a reset button since we already have a reset option. Can you please explain in more detail? Thanks

**Comment by sriza** [comment]
@charlesyoung 
Currently, the reset option is only available to HITs that are in a pending state or are rejected, and there is no provision for resetting the HIT that has been approved.
![image](https://user-images.githubusercontent.com/24825118/148915617-dd43ba83-56f8-41fd-8a38-89867de7f758.png)
![image](https://user-images.githubusercontent.com/24825118/148916953-cf440d2e-35e2-4a44-9e61-5bc2b8c4e09e.png)

Adding a reset button to the approved HIT would allow us to reset the HIT ID of the approved transcription thus resubmitting them to the MTurk for transcription.  
![image](https://user-images.githubusercontent.com/24825118/148917980-ee64ccc2-6665-4277-b2c5-cd05e0efb86d.png)

The changes related to adding a reset button in approved HIT are currently deployed to the staging site. Please have a look and let us know if you have any questions or suggestions.

Thank you

cc @man-git007

**Comment by charlesyoung** [comment]
Thanks. A question, however, if I understand it correctly. 

How do we know if the HIT was approved manually by an Admin user or by MTurk using auto-approvals (past 30 days)? It currently just notes 'Approved'.

**Comment by sriza** [comment]
Currently, we can't distinguish between the HIT approved manually by the user and auto-approved by MTurk. Both the manual approval and auto-approval are seen with the status 'Approved'.

**Comment by charlesyoung** [comment]
That seems to be a problem because we won't know how it was approved. This is bigger than initially discussed so can we, for now, just flag if the HIT was manually (M-Approved) or automatically (A-Approved) approved?

**Comment by sriza** [comment]
@charlesyoung 
We had further discussion on this issue today and have come up with a solution. 

We have decided on adding a flag to differentiate between auto-approved and manually-approved assignments. The reset button will now only be present for the HIT whose assignments were auto-approved by the MTurk.
Please follow [Google docs](https://docs.google.com/document/d/13nrphjwi4deAwxa6Kf2216-D5QP7qm8NkU_sIIe7OsI/edit?usp=sharing) for the details of the solution.

The discussion for this issue took 2 hours. We will be requiring 4 hours to implement this solution.
Please have a look at the shared [Google docs](https://docs.google.com/document/d/13nrphjwi4deAwxa6Kf2216-D5QP7qm8NkU_sIIe7OsI/edit?usp=sharing) and let us know how we should further proceed.

Thank you

cc @man-git007

**Comment by charlesyoung** [comment]
Thanks. 

@man-git007 please confirm that we still have remaining support hours. 

We initially had 48 hours left  [https://docs.google.com/spreadsheets/d/1Uh7srC3mSa0SUviFBf1qdutcWC2TfXGDUlcg4a5NGlk/edit#gid=0](url)

And the additional work was 43 hours [https://docs.google.com/spreadsheets/d/121JKg3VYmQxUT-QaudvBNzijBRIFjWku5COkmtIRigA/edit#gid=0](url)

**Comment by charlesyoung** [comment]
@man-git007 do we still have 5 hours left to spend on this task? As you are aware we don't currently have any budget for RC / OLC support in 2022.

**Comment by man-git007** [comment]
@charlesyoung We have [48hrs](https://docs.google.com/spreadsheets/d/1Uh7srC3mSa0SUviFBf1qdutcWC2TfXGDUlcg4a5NGlk/edit#gid=0) in total out of which [43hrs](https://docs.google.com/spreadsheets/d/121JKg3VYmQxUT-QaudvBNzijBRIFjWku5COkmtIRigA/edit#gid=0) have been exhausted. So we can use the remaining 5hrs for this ticket.

**Comment by charlesyoung** [comment]
Thanks @man-git007 

So there is enough time to implement above solution.

**Comment by man-git007** [comment]
@charlesyoung We have started working on it.

**Comment by charlesyoung** [comment]
@man-git007 @sriza just following up on the status of this ticket.

**Comment by sriza** [comment]
@charlesyoung 
The solution is implemented and is currently deployed to the staging site.
For the test purpose, we have set the auto-approval delay to 60 seconds, i.e. once the worker submits the assignment, it automatically gets approved after a minute.

Please have a look and let us know if it is working correctly and if any changes are to be done.

Thank you
cc @man-git007

**Comment by charlesyoung** [comment]
Thanks. I can see that when manually approving a HIT 'M-Approved' is added to the 'Approved' column which is good. Can you however point me to any 'A-Approved' HITs?

**Comment by sriza** [comment]
Please follow this link to see auto-approved HIT:
https://admin-staging.resourcecontracts.org/mturk/4660

**Comment by charlesyoung** [comment]
@SamCCSI have you had time to do a final test before we move the code to Prod?

**Comment by SamCCSI** [comment]
Looks good.

Is there a way to have a text explainer at top of page so that future users
know what M-approved and A-Approved mean?

**Comment by sriza** [comment]
@SamCCSI @charlesyoung 
Regarding the text explainer for M-approved and A-approved, please have a look at the following approaches :
- I
![image](https://user-images.githubusercontent.com/24825118/151745718-daa09943-dcfa-45bd-8975-f2dcd3069087.png)
- II
![image](https://user-images.githubusercontent.com/24825118/151746397-5cc86810-1a08-4fb6-84fe-4a40d3efa338.png)

Please let us know which one do you like the best. If you would like the text explainer to have different text, please let us know about that as well.

Thank you

cc @man-git007

**Comment by charlesyoung** [comment]
Thanks. @SamCCSI what are your thoughts on the 2 options. 

Can we also remove the '?' in the 'Approved' heading?

**Comment by SamCCSI** [comment]
I like the second one. Could you please copy the text into github, so that
I can offer some minor text edits. Many thanks!

**Comment by sriza** [comment]
@SamCCSI 
The text used in the second image is as follows:

> M-Approved refers to user-approved HIT and A-Approved are HIT that are automatically approved by MTurk.<br> HITs are automatically approved after 30 days of assignment submission. A-Approved HIT can be reset and sent to MTurk for retranscription.

Thank you

**Comment by charlesyoung** [comment]
Looks good to me!

**Comment by sriza** [comment]
@charlesyoung @SamCCSI 
We have added the text explainer and removed the '?' after the 'Approved' heading. 
The changes are now deployed to the staging site. Please confirm the changes.

Thank you

cc @man-git007

**Comment by charlesyoung** [comment]
The text is too small to read. 

<img width="751" alt="image" src="https://user-images.githubusercontent.com/13888372/151924069-0fe3bd37-9d37-4427-b08c-42e21dc949c0.png">

**Comment by sriza** [comment]
I have fixed the issue with the text. Could you please have a look at it again?

**Comment by charlesyoung** [comment]
@SamCCSI you happy to move this to the Prod site?

**Comment by SamCCSI** [comment]
Yes, please move to prod site

**Comment by sriza** [comment]
@charlesyoung 
The changes related to this issue are deployed to the production site. Please confirm the changes.

Thank you

cc @man-git007 @anjesh

**Comment by sriza** [comment]
@charlesyoung @SamCCSI 
Are the changes related to this issue tested in the production site?
Please let us know if the changes are working correctly and if this issue can be closed.

Thank you

cc @man-git007
