### ISSUE TITLE
Prevent crawlers from crawling search and sort pages on RC subsites

### ISSUE THREAD

**Issue by iprunache** [NRGI/resourcecontracts.org#1324]
## Why
Search index crawlers generate a lot of requests to the API by crawling duplicate content on search pages and sorted pages. This puts too much stress on the Elasticsearch server resulting in higher monthly costs.

## What
- [x] a robots.txt file is added for all subsites disallowing crawling of search and sorted pages.

## Notes
This will only work for well-behaved crawlers. We might need a different way to handle crawlers that disobey robots.txt.

**Comment by iprunache** [comment]
Added a robots.txt file.

**Comment by charlesyoung** [comment]
@iprunache thanks for the help. 

What type of crawlers do you foresee the robots.txt file will not stop? 

Also will this try block crawlers for RC, OLC and all the country RC subsites?

**Comment by charlesyoung** [comment]
@iprunache thanks for the help. 

What type of crawlers do you foresee the robots.txt file will not stop? 

Also will this try block crawlers for RC, OLC and all the country RC subsites?

**Comment by iprunache** [comment]
@charlesyoung the robots.txt file will be present on all sites: RC, OLC and country sites.

Mainstream search engine crawlers respect the robots.txt file and we should see traffic from them drop. Most of the crawlers visiting us should fall into this category.

Smaller or shadier organizations are more aggressive with crawling and often don't respect the rules. We'll have to see what's the proportion of these ones after we monitor the traffic a few days.

**Comment by charlesyoung** [comment]
Thanks. Will be interesting to see by how much the traffic will be reduced.

**Comment by jedm** [comment]
@iprunache Hi Ionut - Just a curiosity question: Do these crawlers impact server load or overall performance? Or would that degree of impact be unusual/malicious?

cc @charlesyoung

**Comment by iprunache** [comment]
Hi @jedm ! At the moment server performance is not impacted because we scaled the Elasticsearch instance to have enough CPU power to handle all these crawlers.

But it's expensive and inefficient considering that we don't get any benefit from bots crawling duplicate content. We'd like to reduce costs but as soon as we downscale the instance it gets overloaded by the constant traffic from the bots. When that happens all the RC sites become unresponsive since they all depend on the service.

For even more context, downscaling even one step at the current service provider switches us to a CPU credit system where the CPU gets throttled severely when all the credits are consumed. Credits are consumed while CPU usage is above a certain threshold and accumulated in the rest. The constant crawling prevents us from accumulating credits and when there's a spike in traffic all credits get consumed leading to the severe throttling.

Let me know if that answers your question.

**Comment by jedm** [comment]
@iprunache This is a great and helpful answer! Happy to discuss with you and/or @anjesh what measures we could consider to block the crawlers more aggressively without losing search traffic (perhaps in combo with other SEO measures).

Copying @charlesyoung and @SamCCSI to check what has been considered to date in this regard -- I am probably late to the party.

**Comment by iprunache** [comment]
Some updates here, the added robots.txt has a promising effect. At least the well-behaved crawlers like Google and Bing are no longer crawling duplicate content.

Metrics show there's a considerable drop in the number of requests being made to the ES server that translates into about 50% lower CPU usage. 

We'll need to review the numbers after one more week though, before proceeding to downscale the instance, just to make sure that the perceived improvement is not caused by a lull in crawler activity.

Metrics for before and after:
<img width="1123" alt="Screen Shot 2020-10-23 at 23 34 56" src="https://user-images.githubusercontent.com/15313824/97051815-82418680-1588-11eb-8a42-fc6e229b9d14.png">

The drop for the request count is also visible for the API site:

<img width="1377" alt="Screen Shot 2020-10-23 at 23 23 00" src="https://user-images.githubusercontent.com/15313824/97052008-e3695a00-1588-11eb-9fc8-749f5840ecd8.png">

**Comment by iprunache** [comment]
I'll be on vacation for the next week but @candrei will be available to help with questions or updates.

**Comment by charlesyoung** [comment]
Thanks @iprunache, this looks promising. As you say lets keep reviewing the numbers of the next couple of weeks. 

@candrei will it be possible to run another check on the numbers later in the week?

**Comment by candrei** [comment]
@charlesyoung sure, I would run it on Monday once Ionut is back. It will be quicker for him to draw a conclusion + better timing since a full week has passed.

**Comment by iprunache** [comment]
@charlesyoung checked the numbers again and the request count remains low if crawlers behave. But, as can be seen in the screenshot below, not all crawlers respect the `robots.txt` rules completely and we can still expect spikes:

<img width="1367" alt="Screen Shot 2020-11-02 at 23 07 57" src="https://user-images.githubusercontent.com/15313824/97970256-eacf0580-1dc9-11eb-87d5-7105b5c4d1f9.png">

I downscaled the ES instance anyway from 15GB to 8GB(CPU power and credits limit are tied to memory size) and will keep monitoring it for performance issues.

**Comment by charlesyoung** [comment]
Many thanks @iprunache 

Sounds promising.

**Comment by charlesyoung** [comment]
@iprunache seems like we were hit by a bot (trafficbot.live) last week. Can this be blocked? 

![image](https://user-images.githubusercontent.com/13888372/107186809-9c935900-69ed-11eb-8b1b-a51cd47e380e.png)

**Comment by iprunache** [comment]
@charlesyoung I don't see any traffic to that page on our servers access logs.

It seems to be an attack on Google Analytics itself as pointed out by many users on this thread: https://community.cloudflare.com/t/bottraffic-live/240745/38. Basically they get the GA ID from our sites and then just send the requests directly to GA. Not sure what's the purpose.

Since we can't block it from the servers, the best approach is to **filter out that traffic in Google Analytics**. Here's a good post on how to do that for existing and future data: https://delante.co/traffic-bot-in-google-analytics/

**Comment by iprunache** [comment]
Note that the attackers may change the URI string in the future so keep that guide at hand. Sorry that I don't have a better solution for it. Let us know how it works.

**Comment by charlesyoung** [comment]
OK thanks.
