### ISSUE TITLE
Re-route Learn How To Get Started to FAQs

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1325]
Open the FAQ page, and not the Guides page when clicking on the 'Learn how to get started' link on the home page. 

Only for RC and not OLC.

**Comment by charlesyoung** [comment]
@anjesh I'm going to budget 2 hours for this activity. Let me know if that is OK.

**Comment by surazneupane** [comment]
@charlesyoung  this has been done and deployed in the staging (https://staging.resourcecontracts.org) server. Could you please verify it . if all ok we will deploy in live server.

cc @man-git007

**Comment by charlesyoung** [comment]
Thanks @surazneupane 

Looks good, let me however get approval before moving to the Prod site.

**Comment by charlesyoung** [comment]
Please move to the Prod site. Thanks

**Comment by surazneupane** [comment]
@charlesyoung  we have moved this to production site.thanks! Can this issue be closed?

**Comment by charlesyoung** [comment]
Not seeing it yet. Have removed image cache but still not updating. Will try later and close the ticket if all good.

**Comment by surazneupane** [comment]
@charlesyoung  now you can see the change in production.
