### ISSUE TITLE
General inconstant issues

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1329]
1. Clipping - For some users the clipping function works but for others (like below) the page just notes 'Loading' but nothing happens. 

![image](https://user-images.githubusercontent.com/13888372/98642786-aba73400-2336-11eb-8d52-cec0047f3a83.png)

2. Site generally - For some users the share button is displayed and for others not 

![image](https://user-images.githubusercontent.com/13888372/98642927-e8732b00-2336-11eb-9882-ace2badf2204.png)
![image](https://user-images.githubusercontent.com/13888372/98642955-f4f78380-2336-11eb-88f4-0f8da21daa3f.png)

**Comment by anjesh** [comment]
It would be good to get more info on browser version and operating system and we need to see if we could replicate this or not. Without replication, it would be difficult to debug this.

**Comment by charlesyoung** [comment]
My Chrome version is 86.0.4240.193 (Official Build) (64-bit). This relates to the Share button not working. 

I will get the same info for Nicola. 

I have allocated 3 hours
