### ISSUE TITLE
Annotations showing on English view but not on French view

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#1330]
This contract has 4 annotations that don't display when the view has selected FR view. But do display when the view has selected EN view.
https://www.openlandcontracts.org/contract/ocds-591adf-2171430573/view?lang=en#/
https://admin.resourcecontracts.org/contract/2876/annotate#/pdf/page/10/annotation/27219

- Infrastructure / L'infrastructure
- Location / Emplacement
- Renewal / Renouvellement
- Work commitments / obligations de travaux

Screenshots of each below in Eng and Fre. @anjesh is this a bug? Seems related to, but different from #1239

![Screen Shot 2020-11-12 at 5 25 50 PM](https://user-images.githubusercontent.com/12913915/99003906-9f74cf80-250c-11eb-8c4c-cf9bde116e68.png)
![Screen Shot 2020-11-12 at 5 26 57 PM](https://user-images.githubusercontent.com/12913915/99003947-a26fc000-250c-11eb-929c-e099eb3ac0bc.png)
![Screen Shot 2020-11-12 at 5 27 15 PM](https://user-images.githubusercontent.com/12913915/99004061-aac7fb00-250c-11eb-9c2a-27c00386ea4e.png)
![Screen Shot 2020-11-12 at 5 27 40 PM](https://user-images.githubusercontent.com/12913915/99004065-aac7fb00-250c-11eb-94a1-b996bcbe6e84.png)
![Screen Shot 2020-11-12 at 5 27 22 PM](https://user-images.githubusercontent.com/12913915/99004108-aef41880-250c-11eb-86fc-4ef3db3e88f5.png)
![Screen Shot 2020-11-12 at 5 27 31 PM](https://user-images.githubusercontent.com/12913915/99004112-aef41880-250c-11eb-8a5c-0bc27fe40afa.png)

**Comment by anjesh** [comment]
@SamCCSI i see that in the admin, there's no annotation text defined under French but available in english. Please have a look. This might have been the case since 2018 when the annotation was last published as can be seen here https://admin.resourcecontracts.org/activities?contract=2876. Do you remember if you have seen those annotations in French before?

![image](https://user-images.githubusercontent.com/120488/99060599-5bdf9b80-25c8-11eb-9bbc-e0c4c35bb54e.png)

![image](https://user-images.githubusercontent.com/120488/99060612-6306a980-25c8-11eb-8e10-2abe540da7c2.png)

**Comment by SamCCSI** [comment]
@anjesh no idea.

I suspect the fix is to delete the blank french versions for those four (keeping the english version). can that be done?

**Comment by SamCCSI** [comment]
Here is another example https://admin.resourcecontracts.org/contract/4184

@anjesh do you have any ideas about how we can eridcate this issue? I'm happy to have someone manually delete the blank French versions, I just don't know how that is done

**Comment by anjesh** [comment]
Unfortunately, there isn't delete feature for the annotation of a particular language only. There hasn't been any need as far as i remember until this case. Now it makes sense to have this feature. Our initial assumption was people would add annotation in english first and then they may add for other language. 

We will need to add this feature of listing the annotations in different languages and delete option for individual language. Currently the list also doesn't appear to be intuitive in the admin interface as well. 

One option is to have someone copy annotation from english to the french text-box. You shared 2 instances, but there might be possibility of more instances with such problems. If there are few such problems (say 3-5 documents), manual copy/paste might be quick as a temporary fix but definitely not the proper way to fix. Any further updates in annotation will require changes in 2 places. 

Second option is to directly fix in the database using script, which will need proper testing and careful updates. Second option might be quick when there are lots of problematic annotated documents. But this might take few days as well. I will discuss with the developer and get back on this. This is one time fix but we will again run into such problems in future. 

Third option is to replace the current interface to manage the annotations to handle the issue that OLC is currently facing. This is definitely the sustainable one where annotators will be able to fix the issue by themselves in case of current issues. This will need discussion with you and Charles and will take more effort as well. 

In any case, we first need to find the list of documents with annotation-lang issue and then choose either option 1 or 2. Then in the long run, go with option 3.

**Comment by SamCCSI** [comment]
Thanks @anjesh 

> One option is to have someone copy annotation from english to the french text-box. You shared 2 instances, but there might be possibility of more instances with such problems. If there are few such problems (say 3-5 documents), manual copy/paste might be quick as a temporary fix but definitely not the proper way to fix. Any further updates in annotation will require changes in 2 places.

I actually tried this option 1 yesterday and it didn't seem to work. 
I copied the text for assignment/transfer to the french version (cession ou transfert)
https://www.openlandcontracts.org/contract/ocds-591adf-6291757901/view?lang=fr#/
https://admin.resourcecontracts.org/contract/4184

**Comment by SamCCSI** [comment]
@charlesyoung are there any examples where you have annotations in 2 separate languages on the same contract?

We have no examples. If it would be easier to just eliminate the annotation language function, so that you just have one version of annotations, I would be open to that too @anjesh

**Comment by SamCCSI** [comment]
Scratch that; it looks like option 1 does work; there is just a time lag to it appearing on the live site

**Comment by anjesh** [comment]
> @charlesyoung are there any examples where you have annotations in 2 separate languages on the same contract?
> 
> We have no examples. If it would be easier to just eliminate the annotation language function, so that you just have one version of annotations, I would be open to that too @anjesh

That would make the work easy and straight forward for the annotators and also make the code/system a bit simple. We  invested good amount of time in this feature before. Since Sam raised this issue, maybe it's time to evaluate the feature and downsize the feature if it's not used and instead creates more confusion. But removal of feature is also effort intensive - we need to remove the feature in the admin, make necessary changes in database, API and in the subsites. 

This definitely requires further discussion whether to remove this feature or go with option 3 above.

**Comment by anjesh** [comment]
@SamCCSI we discussed internally and the quicker solution would be to make changes in the subsite such that if fr-annotation is blank then en-annotation will be pulled and shown. That should fix most of these blank annotation issues. @man-git007 will be looking at this particular issue. We will update you when we have more information.

**Comment by man-git007** [comment]
@SamCCSI As previously discussed, we have shown the fallback language annotation which is English in staging site, if the contract doesn't have french annotation. For your reference please check this contract on the [admin](https://admin-staging.resourcecontracts.org/contract/2968/annotate) site and in [subsite](https://staging.openlandcontracts.org/contract/ocds-591adf-6747336977/view#/).

If this solves the problem we will deploy to live server.

cc @anjesh

**Comment by anjesh** [comment]
I think this is good to deploy. When the french annotation is blank, it pulls the english annotation. Before once you enter the french annotation and delete it from the text box, you will still get blank as the system thinks that annotation is present. 
@SamCCSI please confirm before we deploy.

**Comment by SamCCSI** [comment]
> I think this is good to deploy. When the french annotation is blank, it pulls the english annotation. Before once you enter the french annotation and delete it from the text box, you will still get blank as the system thinks that annotation is present.
> @SamCCSI please confirm before we deploy.

If it works as described above (including when French is added but then cleared) then that is perfect. Please deploy @anjesh @man-git007

**Comment by SamCCSI** [comment]
and thanks for your quick work on this!

**Comment by man-git007** [comment]
@SamCCSI The changes have been deployed to the live server. Could you please verify?

cc @anjesh

**Comment by SamCCSI** [comment]
Working nicely. Thank you!
