### ISSUE TITLE
Update uk aid logo for OLC

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#1331]
On the footer, can you please replace the old UKaid logo with this one:
https://www.ukaiddirect.org/img/banner-logo.png

@anjesh this can be taken out of YI's standing retainer for OLC work. Thanks!

**Comment by SamCCSI** [comment]
![image](https://user-images.githubusercontent.com/12913915/99005531-f8ddfe00-250e-11eb-91c5-a4806590902a.png)

**Comment by anjesh** [comment]
Sure. Will allocate 2 hours for this. @man-git007

**Comment by man-git007** [comment]
@SamCCSI The image has been updated in deployed in the [staging](https://staging.openlandcontracts.org/) server. Please, verify and if OK we will deploy it to the live server

**Comment by anjesh** [comment]
@man-git007 the image looked stretched in my browser. Could we show the image in its original proportion?

![image](https://user-images.githubusercontent.com/120488/100090585-798beb00-2e7b-11eb-9b32-a10191d83e2a.png)

**Comment by SamCCSI** [comment]
Mine too

**Comment by man-git007** [comment]
@SamCCSI The image stretch has been fixed. Please verify if its OK?

cc @anjesh

**Comment by SamCCSI** [comment]
It appears blurry.

Would you mind inserting this version instead? It might be of better
quality.
https://drive.google.com/file/d/15qQXTqHl9wHgTctaCG_NvZNOF3POa8LA/view?usp=sharing

Also, the CCSI logo on staging looks like it has been stretched, and we
want to avoid that on the live site.

Many thanks!

>

**Comment by man-git007** [comment]
@SamCCSI The logo has been updated and deployed in the staging site. If OK, we will deploy it in live site.

**Comment by SamCCSI** [comment]
Thanks @man-git007 

Can you make sure the height is exactly the same as the CCSI logo so that it looks apportioned? Right now it looks too small.

Can you please change hyperlink to https://www.gov.uk/government/organisations/foreign-commonwealth-development-office

**Comment by man-git007** [comment]
@SamCCSI The changes have been made and deployed in the [live](https://openlandcontracts.org/) server. Could you please check.

cc @anjesh

**Comment by SamCCSI** [comment]
Thanks @man-git007

**Comment by SamCCSI** [comment]
@man-git007 problem - it now appears like this

![image](https://user-images.githubusercontent.com/12913915/101647031-42cedc80-3a06-11eb-8d34-488fbb73b249.png)

**Comment by man-git007** [comment]
@SamCCSI Can you check it again? It's OK at our end.

![Screenshot from 2020-12-09 21-23-16](https://user-images.githubusercontent.com/23434972/101651132-d1724680-3a64-11eb-8261-a9ca5198c275.png)

**Comment by SamCCSI** [comment]
Working now. Thanks!
