### ISSUE TITLE
Tagged search results 

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1332]
The tagging search option where the clause is highlighted in the results needs to be added back to ResourceContracts because it was inadvertently removed during the last code fork. 

This does not apply to OLC. 

I have added 1 hour for this task. 

cc @anjesh

**Comment by anjesh** [comment]
Can you give an example? I see that search query is being highlighted in the result.

![image](https://user-images.githubusercontent.com/120488/99059029-1ae68780-25c6-11eb-9832-9b6867c13eb0.png)

**Comment by charlesyoung** [comment]
Above the red line is OLC and below the line in RC

![image](https://user-images.githubusercontent.com/13888372/99059370-2a0a0d00-25a7-11eb-91e9-9a724cdc305e.png)

**Comment by charlesyoung** [comment]
Could this be related to #1329

**Comment by charlesyoung** [comment]
Your result is from a free text search. Try to run a search from the key clauses dropdown list.

**Comment by anjesh** [comment]
Understood. The words (tags, annotations, key clauses) got me mixed up :)

**Comment by rumus007** [comment]
@charlesyoung 
Hello, I have deployed changes to the staging site regarding this issue. The key clause is highlighted in the result for the RC site. 

![Screenshot from 2020-12-14 16-15-46](https://user-images.githubusercontent.com/51116139/102071018-01846580-3e28-11eb-88ce-e5cf33e8841b.png)

 cc @anjesh @man-git007

**Comment by charlesyoung** [comment]
Seems to be a caching issue because I don't see the changes yet.

**Comment by rumus007** [comment]
@charlesyoung 
If changes are not seen please hard reload, as your browser may have cached the page.

**Comment by rumus007** [comment]
@charlesyoung 
if this is ok, can we move this to production?

**Comment by charlesyoung** [comment]
I ran a search on 'Capital gains tax' with the search result shown below (1 main and 4 supporting docs). The issue is that only 1 of the 5 docs has annotations and that's just for 'Income tax: other' and not 'Capital gains tax'. 

![image](https://user-images.githubusercontent.com/13888372/102203445-457f7500-3ed1-11eb-8c12-acc7df4945f5.png)

**Comment by rumus007** [comment]
@charlesyoung 
This may have occurred due to a data issue in the staging site. It will not affect the tagging of the key clauses. 
If there are no other issues regarding the tagging can we move this to production?

**Comment by charlesyoung** [comment]
Works now with the Prod DB on Staging. 

Please move to RC Prod.

**Comment by rumus007** [comment]
@charlesyoung 
This has been deployed to production
