### ISSUE TITLE
Additional import spreadsheet columns 

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1333]
Can the following columns be added to the backend import spreadsheet template. 

- Source URL
- Matrix Page
- Deal Number 

@anjesh how much time will it take to add the new columns? 

cc @SamCCSI

**Comment by charlesyoung** [comment]
@anjesh ??

**Comment by anjesh** [comment]
~ 6 hrs work to add the fields in the template, update template, make necessary validations during import, test, deployment

**Comment by charlesyoung** [comment]
@SamCCSI can we use 6 hours from the standing OLC retainer for this activity?

**Comment by SamCCSI** [comment]
yes. @anjesh can you please update our shared spreadsheet once the 6 hours have been worked, so that we can see how much time we still have in your retainer? Many thanks

**Comment by charlesyoung** [comment]
@anjesh just confirming that you are working on this request?

**Comment by anjesh** [comment]
Yes. And we are including this under sprint 25 (CCSI).

**Comment by man-git007** [comment]
@charlesyoung The `Matrix Page` and `Deal Number` attributes are for OLC only. Should this be added to RC as well? If so this might take some time.

**Comment by charlesyoung** [comment]
Correct @man-git007 

The Matrix Page and Deal Number only relate to OLC so will not be filled in for RC docs. The Source URL however relates to both RC and OLC.

**Comment by charlesyoung** [comment]
@man-git007 just a question on capturing 'Other' in the xls template. 

How do we record the details for example for 'Other' Contract Type or Disclosure Mode? While 'Other' is imported how do we capture the free-text info in the xls template that is normally captured when manually publishing docs.

**Comment by SamCCSI** [comment]
It’s only needed for OLC, not for RC. Thanks!

**Comment by charlesyoung** [comment]
@man-git007 just checking on the completion timeframe as we are in the process of importing docs using the xls template.

**Comment by charlesyoung** [comment]
@man-git007 just checking when this will be on Staging.

**Comment by man-git007** [comment]
@charlesyoung We have deployed the excel file changes in the staging server. As we don't have a valid pdf file URL, we aren't able to test it. Could please test it?

cc @anjesh @surazneupane

**Comment by charlesyoung** [comment]
Seems to work well. Can I however please ask that you update the column headings as follows. 

Source URL
Matrix Page
Deal Number

![image](https://user-images.githubusercontent.com/13888372/101157009-1f84e580-3632-11eb-8e05-3e5902388989.png)

cc @SamCCSI

**Comment by surazneupane** [comment]
@charlesyoung we have update the columns heading as mentioned above. can you please test it?

cc @man-git007  @anjesh

**Comment by charlesyoung** [comment]
Looks good. Please move to Prod.

**Comment by surazneupane** [comment]
@charlesyoung  we have moved it to production serve. Thanks.
Cc @man-git007  @anjesh

**Comment by surazneupane** [comment]
@charlesyoung  can this issue be closed ?
