### ISSUE TITLE
Composer install fails for rc-subsite when installing from fresh

### ISSUE THREAD

**Issue by iprunache** [NRGI/resourcecontracts.org#1334]
## Why
We should be able to install the rc-subsite project on a fresh environment.

Deployments to production are not affected now because we use previously cached Docker images but if we need to build the Docker image from scratch it will fail.

## What
- [ ] `composer.json` and `composer.lock` are updated so that `composer install` executes without failing

## Notes
This is the error that currently stops the installer(might be others further down the road):
```
  [RuntimeException]
  Failed to clone https://github.com/LynX39/lara-pdf-merger.git via https, ssh protocols, aborting.

  - https://github.com/LynX39/lara-pdf-merger.git
    Cloning into bare repository '/root/.composer/cache/vcs/https---github.com-LynX39-lara-pdf-merger.git'...
    remote: Invalid username or password.
    fatal: Authentication failed for 'https://github.com/LynX39/lara-pdf-merger.git/'

  - git@github.com:LynX39/lara-pdf-merger.git
    Cloning into bare repository '/root/.composer/cache/vcs/https---github.com-LynX39-lara-pdf-merger.git'...
    error: cannot run ssh: No such file or directory
    fatal: unable to fork
```

**Comment by iprunache** [comment]
@charlesyoung please prioritize this. It's not affecting production now because we're using cached packages but the project should be in a buildable state in case we lose the cache.

**Comment by charlesyoung** [comment]
Thanks. How much time will it take to resolve?

**Comment by iprunache** [comment]
Charles, I was hoping YI already has a working version of the requirements file since they do active development. I think it would be a matter of hours to fix otherwise.

@man-git007 @birendragurung do you have a more recent version of `composer.json` for `rc-subsite` that composer can install from scratch(no locally cached packages)?

**Comment by man-git007** [comment]
@iprunache We don't have the recent version of `composer.json`. The issue might be related to updating the composer.lock file. The `https://github.com/LynX39/lara-pdf-merger.git` seems to have changed to `https://github.com/DALTCORE/lara-pdf-merger.git`. Updating the URL in `composer.lock` might fix the issue.

**Comment by iprunache** [comment]
Thanks, @man-git007 . It's not urgent now, we'll update `composer.json` with the correct link for the package when we'll need to rebuild.

I also wanted to make sure there won't be conflicts in case you had a different compose file locally.
