### ISSUE TITLE
Add contract published date in the subsites

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#1335]
@charlesyoung Do you think adding the following `Published on: date` is ok? Please suggest if label is to be changed like created on, document published on or ..

Should this be done for RC only or also on OLC?

![image](https://user-images.githubusercontent.com/120488/100840147-92108c80-349d-11eb-83ff-caf084fb4517.png)

cc @SamCCSI

**Comment by charlesyoung** [comment]
Thanks @anjesh 

Would be good to make it a bit more prominent. 

![image](https://user-images.githubusercontent.com/13888372/100845026-481bac80-3485-11eb-8aa7-1bfd2efc31f0.png)

This is an initial solution for now. We will try to add the publication date in the xls export next year using the support budget.  

@SamCCSI for some context. I have been asked on numerous occasions to include a doc publication date in RC. As an example, the IMF asked me last month to include the date so that they can see if their onsite interventions are resulting in contract disclosures. Let us know if you also want this for OLC.

**Comment by SamCCSI** [comment]
@charlesyoung is this date published on RC? or date made public more generally?

**Comment by charlesyoung** [comment]
We don’t currently show the doc publish date on RC or OLC. I would like to add this to the RC summary page now and the xls export next year.

**Comment by SamCCSI** [comment]
I meant, is this the date the doc was published on RC? or the date the doc was first disclosed more generally?

**Comment by charlesyoung** [comment]
It’s the doc RC publish date.

**Comment by charlesyoung** [comment]
@SamCCSI just checking if you also want this for OLC.

**Comment by charlesyoung** [comment]
@SamCCSI will you be able to add your comments on this ticket once received? It will be good to get your input before we implement.

**Comment by SamCCSI** [comment]
We are happy for this to be added to OLC as well for now.

We think the wording should be changed to *Date posted on
OpenLandContracts* for
OLC and *Date posted on ResourceContracts* for RC to avoid confusion about
what the date represents.

**Comment by charlesyoung** [comment]
Thanks @SamCCSI 

@anjesh can you see if you will be able to fit 'Date posted on ResourceContracts: **February 12, 2020**' and 'Date posted on
OpenLandContracts **February 12, 2020** (as examples) in the space noted in above image.

**Comment by charlesyoung** [comment]
@anjesh will it be possible to work on this ticket in this week?

**Comment by surazneupane** [comment]
@charlesyoung  we have deployed it to staging server can you please verify it? thanks!

**Comment by charlesyoung** [comment]
Thanks @surazneupane 

- Please update the 'Publication Date' text to 'Date published on ResourceContracts' and 'Date posted on OpenLandContracts'
- Please update the date from November 20 2019 to November 20, 2019 (include the comma to keep to the standard) 
- Remove the colon in the 'Open Contracting ID :' text
- Remove the space before 'ocds-591adf-7024761652'

**Comment by surazneupane** [comment]
@charlesyoung  can you see the change in staging server? please verify it . Thanks !

**Comment by charlesyoung** [comment]
Great, good to move to the RC prod site. 

@SamCCSI will need to confirm the OLC site. 

https://staging.openlandcontracts.org/contract/ocds-591adf-6858445103

**Comment by SamCCSI** [comment]
Thanks @surazneupane <https://github.com/surazneupane>

Could you please update the 'Date posted' text to 'Date posted *on
ResourceContracts*' for RC and 'Date posted* on OpenLandContracts*' for OLC?

**Comment by charlesyoung** [comment]
OK possibly best to add the RC and OLC bit just to clarify. 

Please however keep the RC text as published and not posted.

**Comment by surazneupane** [comment]
@charlesyoung  @SamCCSI  i think OLC already have Date posted text .

**Comment by charlesyoung** [comment]
Yep, it does but as Sam noted can you please add 'Date published **on ResourceContracts**' and 'Date posted **on OpenLandContracts**'.

**Comment by charlesyoung** [comment]
The text shouldn't be bold, just showing what still needs to be added.

**Comment by surazneupane** [comment]
![Screenshot from 2020-12-08 19-46-36](https://user-images.githubusercontent.com/37624741/101493410-24c59580-398e-11eb-91c4-19180a008c6d.png)
@charlesyoung  should it look like this?

**Comment by charlesyoung** [comment]
Yes, but can you make the 'On' rather 'on'. 

Can you also fit 'ResourceContracts' on the same line as 'Date published on...'? There seems to be sufficient space.

**Comment by surazneupane** [comment]
![Screenshot from 2020-12-09 10-31-47](https://user-images.githubusercontent.com/37624741/101586320-c938ed80-3a09-11eb-962d-b3eb0f207af6.png)
@charlesyoung  Does This look good?

**Comment by charlesyoung** [comment]
Thanks, can we, however, try to align the box and text with the country? Looks currently out of sync. Can we move the text below the Type of Contract and Resource boxes if the text is too long in the current position?

![image](https://user-images.githubusercontent.com/13888372/101604957-43697200-3a0a-11eb-8d92-8d88d69b3951.png)

**Comment by surazneupane** [comment]
![charles](https://user-images.githubusercontent.com/37624741/101610571-8b9b8b00-3a30-11eb-87c7-4f346565b2c5.png)
@charlesyoung  is it okay? please tell if any thing needs to be changed. Thanks!

**Comment by charlesyoung** [comment]
Looks good to move to RC Prod. 

@SamCCSI needs to approve the OLC site.

**Comment by SamCCSI** [comment]
Looks good for OLC; please proceed.

**Comment by surazneupane** [comment]
@charlesyoung  @SamCCSI  can you see the changes in production site? And can this issue  be closed? Thanks !

**Comment by surazneupane** [comment]
@charlesyoung  @SamCCSI  Can you see changes in production site? And can this issue be closed? Thanks !

**Comment by SamCCSI** [comment]
All looks good on live site. Thanks!!

**Comment by charlesyoung** [comment]
Many thanks @surazneupane

**Comment by charlesyoung** [comment]
@man-git007 it seems that when you view the OLC doc summary page in French the 'Date posted on OpenLandContracts' text changes to 'Date publiée sur ResourceContracts'. 

cc @SamCCSI @anjesh

**Comment by SamCCSI** [comment]
Change to 'Date publiée sur OpenLandContracts'.

**Comment by man-git007** [comment]
@charlesyoung @SamCCSI The issue has been fixed and deployed in the [live](https://openlandcontracts.org/contract/ocds-591adf-1281238394?lang=fr) server. Please check once.

![Screenshot from 2021-03-26 10-05-49](https://user-images.githubusercontent.com/23434972/112576696-e8be1f80-8e1a-11eb-9b0c-5d8cb950979c.png)

**Comment by charlesyoung** [comment]
Many thanks.
