### ISSUE TITLE
Additional doc types and resources 

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1355]
@man-git007 what is involved in adding doc types and resources? 

Time for this will come from the 2021 support agreement.

**Comment by charlesyoung** [comment]
@man-git007 just a follow up on my question. I just want to understand the process.

**Comment by charlesyoung** [comment]
@man-git007 ??

**Comment by man-git007** [comment]
@charlesyoung Are you suggesting adding new values to **Document Type** and **Resource** in the contract metadata?.
![Screenshot from 2021-02-04 13-53-10](https://user-images.githubusercontent.com/23434972/106863267-5c339280-66f0-11eb-8977-06b28dd04447.png)
![Screenshot from 2021-02-04 13-53-00](https://user-images.githubusercontent.com/23434972/106863276-5dfd5600-66f0-11eb-9d57-017c86a331ab.png)

If that's the case then we need to add new data to all three languages (EN, AR, FR). This might take around 4hrs.

**Comment by charlesyoung** [comment]
Yes, that's what I'm asking for. 

Can you please explain the process of updating code lists? Do you update a xls file? 

We have limited support budget for 2021 so I will need to understand how the 4 hrs will be spent.

**Comment by man-git007** [comment]
@charlesyoung We will update the code lists in the code itself as the list is maintained in the code. As this is maintained in three languages, we will need to test which might take time.

**Comment by charlesyoung** [comment]
@man-git007 its for OLC so will it be fine just to have the additions in English and French?

**Comment by charlesyoung** [comment]
@man-git007 do we need Arabic for OLC?

We are busy adding the missing code lists to below Sheet. Will let you know when you can add. 

We also need to think of a more sustainable way to update the code lists. Maintaining it in the code  is far from ideal 

https://docs.google.com/spreadsheets/d/1gNZ2C-KhKZlxqsKZIYqFv5Vm_Dt9umpK4tqOptxjyYo/edit#gid=0

**Comment by man-git007** [comment]
@charlesyoung As OLC is in Eng and French only. So, we will not need it in Arabic. As for sustainability, we can have that code list UI on the admin site and this will take time.

cc @anjesh

**Comment by charlesyoung** [comment]
@man-git007 can you please add the 3 resources and 1 doc type to the code list (above xls). Note that its for OLC so no Arabic translations are required. The 4 hours will be deducted from the 2021 support agreement. 

cc @SamCCSI @anjesh

**Comment by man-git007** [comment]
@charlesyoung @SamCCSI This has been deployed in the [staging](https://admin-staging.resourcecontracts.org/) server. Could you please verify?

**Comment by charlesyoung** [comment]
Looks good thanks. Can you however, in both cases, ensure that the additions are listed in alphabetical order.

**Comment by man-git007** [comment]
@charlesyoung The listing is ordered alphabetically.

**Comment by charlesyoung** [comment]
Thanks, please move to Prod.

**Comment by man-git007** [comment]
@charlesyoung Moved to production. If all OK we can close this ticket

cc @anjesh
