### ISSUE TITLE
Typo on French page

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#1359]
French "reset" button should read "Réinitialiser" not "Rénitialiser".

![image](https://user-images.githubusercontent.com/12913915/109360458-4465af00-7855-11eb-8266-62ca53e3bfd1.png)
![image](https://user-images.githubusercontent.com/12913915/109360546-6b23e580-7855-11eb-8baa-5f876a20b54e.png)

cc @anjesh & @charlesyoung

**Comment by man-git007** [comment]
@charlesyoung 
Is it both for RC and OLC? Are there any other language mistakes?

cc @SamCCSI

**Comment by SamCCSI** [comment]
Both -- as shown in both images - one from OLC, one from RC

**Comment by charlesyoung** [comment]
@man-git007 please include the time estimate.

**Comment by man-git007** [comment]
@charlesyoung This might take 0.75 hrs

**Comment by charlesyoung** [comment]
@manishgs please work on this ticket. Thanks

**Comment by sriza** [comment]
@charlesyoung 
The changes for this issue have been deployed in the staging([RC](https://staging.resourcecontracts.org/search/group), [OLC](https://staging.openlandcontracts.org/search/group)) site. Please verify.

![image](https://user-images.githubusercontent.com/24825118/115190612-07f15980-a108-11eb-9858-3635843ce464.png)

![image](https://user-images.githubusercontent.com/24825118/115191287-f2c8fa80-a108-11eb-9a1b-5c89fe31dd45.png)

cc @man-git007

**Comment by charlesyoung** [comment]
Looks good thanks. 

@SamCCSI please approve before we move it to the Prod site.

**Comment by SamCCSI** [comment]
approved

**Comment by sriza** [comment]
@charlesyoung 
The changes are now deployed on the production site.  Please verify and let us know if we can close this issue?

cc @man-git007

**Comment by charlesyoung** [comment]
Thanks @sriza
