### ISSUE TITLE
Scraping geo-refences from contracts

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#136]
For the Blue sky wish list.

![anyak](https://cloud.githubusercontent.com/assets/1101585/8641114/85655d3a-28dc-11e5-92eb-bc354a7c1af3.PNG)

Once we have a significant sample of contracts loaded into RC.org we should seek a method for extracting these datapoints.

**Comment by byndcivilization** [comment]
To add on to this, we should create a way to enter data from contracts directly into a json data type column. This can either be an excel/csv ingestor, a direct api link with something like google docs or a metadata form directly within the site. An ideal implementation would add postGIS functionality to our db but we could also just store geojson objects as raw json. datatype will need to be able to accommodate both polygon/vectors and points. This is becoming a priority for some folks so while it is blue sky, we should push it for shortly after launch.

**Comment by byndcivilization** [comment]
I should add that the ultimate goal is that resulting data should be added to api metadata response for a given contract.

**Comment by jpmckinney** [comment]
Overlaps #447

**Comment by jpmckinney** [comment]
Leaving resolution of the metadata data modeling issue to #447, tagging this as "Metadata - backend" to reflect the scraping of geo-references.

**Comment by charlesyoung** [comment]
Linked to 'Add geo-data metadata in the Admin interface #942'. 

Closing this ticket.
