### ISSUE TITLE
Clause searching 

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1365]
@anjesh what is involved to add an AND search for key clauses? The current search uses OR but users might what to only see results that contain the search term i.e Bonuses AND Withholding tax.

**Comment by charlesyoung** [comment]
@anjesh @man-git007 ?

**Comment by man-git007** [comment]
@charlesyoung The default logic is **OR**. But if we need to implement **AND** logic we might need to make some changes in UI as well.For Example, to get the AND results, one would type "coal AND mining" or "coal + mining". I think we need some discussion on this. Also, Is it for annotation keyword only?

**Comment by charlesyoung** [comment]
@SamCCSI do you also want this update for OLC? 

@man-git007 please include the time estimate.

**Comment by SamCCSI** [comment]
Is this additional functionality or are you changing the existing functionality?

If it's additional (i.e. default is still OR, but users can use a typed word or symbol to use AND functionality), then no harm to add it to OLC.

Having it only for annotation dropdowns seems like NRGI has a very specific use in mind, rather than this being based on a broader user need. So I would want to see how it would affect the site (both visually and also in terms of how it works) before making a decision.

**Comment by man-git007** [comment]
@charlesyoung If it's changing the default logic OR to AND for Clauses / Annotations only then the time estimate would be 5hrs.

**Comment by charlesyoung** [comment]
@SamCCSI do you want to include this option for other dropdowns?

**Comment by charlesyoung** [comment]
Thanks @man-git007 

We would want users to have both options. So by default use the OR logic but allow the user to switch to AND. 

How would you suggest we do that and how will that be designed? 

cc @SamCCSI

**Comment by man-git007** [comment]
@charlesyoung We can have a checkbox `Apply AND Logic` just like the `Recently added`

cc @SamCCSI

**Comment by charlesyoung** [comment]
Thanks. Can you show us a simple design on how it will be presented? We need to keep the design simple while also making it obvious to the user what they can select.

**Comment by man-git007** [comment]
@charlesyoung The filter would look like this
<img width="1440" alt="Screen Shot 2021-04-09 at 9 51 32 AM" src="https://user-images.githubusercontent.com/23434972/114127155-8d5f5780-9919-11eb-9998-50ee255ac391.png">

cc @sweta-shrestha @SamCCSI

**Comment by charlesyoung** [comment]
Thanks @man-git007 

Not sure that is going to work because we might want to apply the same logic to other search parameters and then it will get too messy. The wording will also need to be more clear because no one will know what OR or AND means. 

How about these 2 options. 

1. Add a Search Options link next to the Key Clause text? This takes you to an option to select AND / OR but with a better description. 
![image](https://user-images.githubusercontent.com/13888372/114155894-488bee80-9922-11eb-85f7-5aedbe872f69.png)

2. Add a Search Options link when clicking on the dropdown Key Clause menu. This takes you to an option to select AND / OR but with a better description. 
![image](https://user-images.githubusercontent.com/13888372/114156030-6ce7cb00-9922-11eb-91ce-04be2e5f55b7.png)

Will be good to get @SamCCSI input.

**Comment by man-git007** [comment]
@charlesyoung Has the UI for this ticket finalized?

**Comment by charlesyoung** [comment]
@man-git007 please see attached design. Some points to note. 

- By default, the OR search should be used
- Add an 'OR | AND' button next to the 'Key Clauses' (RC) and 'Annotation Category' (OLC) text
- Users can select OR as well as AND searches by click on the relevant search link
- Display a popup box when hovering over the button item that notes help text presented in the proposed design
- For RC the help text should state tagged while for OLC it should be annotated 

[Clause and annotation design.pptx](https://github.com/NRGI/resourcecontracts.org/files/6348974/Clause.and.annotation.design.pptx)

**Comment by man-git007** [comment]
@charlesyoung OK we will work on it.

**Comment by charlesyoung** [comment]
@man-git007 just checking how far you are with this issue? Thanks

**Comment by man-git007** [comment]
@charlesyoung We are working on this and will inform you as soon we deploy to the staging site.

**Comment by charlesyoung** [comment]
@man-git007 I'm busy updating the Google 2021 support sheet. 

Is this task still estimated at 5hrs?

**Comment by adhikari-anish** [comment]
@charlesyoung The UI and logic for AND, OR search for Clauses / Annotations have been deployed to staging sites. Please have a look. 

[RC-EN](https://staging.resourcecontracts.org/search/group)
![image](https://user-images.githubusercontent.com/35035442/116707382-55b26f80-a9ee-11eb-9227-c47268118761.png)

[RC-FR](https://staging.resourcecontracts.org/search/group?lang=fr)
![image](https://user-images.githubusercontent.com/35035442/116707495-78dd1f00-a9ee-11eb-8191-b68759748507.png)

[RC-AR](https://staging.resourcecontracts.org/search/group?lang=ar)
![image](https://user-images.githubusercontent.com/35035442/116707699-b04bcb80-a9ee-11eb-84d8-2c769ee051a8.png)

[OLC-EN](https://staging.openlandcontracts.org/search/group?q=&lang=en)
![image](https://user-images.githubusercontent.com/35035442/116707914-e9843b80-a9ee-11eb-888b-2a6af52540ca.png)

[OLC-FR](https://staging.openlandcontracts.org/search/group?q=&lang=fr)
![image](https://user-images.githubusercontent.com/35035442/116708023-0751a080-a9ef-11eb-8125-8941fa57a3a2.png)

cc @SamCCSI @man-git007 @sriza @sweta-shrestha

**Comment by SamCCSI** [comment]
Could the grey window appear to the right of the annotation field, rather
than to the left?

Could the coloring be way less pronounced?
- Change grey to white background (for And/Or and for text)
- change the orange/green component to light grey

**Comment by charlesyoung** [comment]
Thanks @adhikari-anish 

I will get internal feedback for RC and get back to you ASAP. 

There are 2 minor updates, please. 
- Change the orange 'slider' so that it is in line with the grey box. It seems as if the top orange border is not in line with the box while the bottom one is. 
- Center the OR and AND text

**Comment by charlesyoung** [comment]
@adhikari-anish internal comments below. Disregard my feedback above. 

- Use rounded edges like the other boxes in the advanced search area
- AND I OR should both be visible and separated by a vertical bar
- Half of the box with the selected search option should be slightly shaded (like the search box on the home page)

This only applies to RC. 

cc @SamCCSI

**Comment by adhikari-anish** [comment]
@SamCCSI Are you suggesting like this?
![image](https://user-images.githubusercontent.com/35035442/116992664-1f2e6a80-acf6-11eb-93d1-7df27366a32f.png)

**Comment by charlesyoung** [comment]
@adhikari-anish let's try to keep the OLC and RC designs the same. 

Can you take below into account for the design? 
- Use rounded edges like the other boxes in the advanced search area
- AND I OR should both be visible and separated by a vertical bar
- Half of the box with the selected search option should be slightly shaded (like the search box on the home page) thereby indicating see which one has been selected

**Comment by adhikari-anish** [comment]
@charlesyoung Sure. I'll let you know once it is done.

**Comment by adhikari-anish** [comment]
@charlesyoung Do you mean like this?

![image](https://user-images.githubusercontent.com/35035442/117246718-d47b3280-ae5c-11eb-90e1-738c4e2bb633.png)

**Comment by charlesyoung** [comment]
Thanks, will check internally and get back to you.

**Comment by adhikari-anish** [comment]
@charlesyoung  According to the feedback, the AND/OR and help tooltip UI hasve been done like this. Please have a look and provide feedback if there is any. Thank you. 

![image](https://user-images.githubusercontent.com/35035442/117613171-2d610880-b186-11eb-96f1-325d2afafe57.png)
![image](https://user-images.githubusercontent.com/35035442/117613241-4bc70400-b186-11eb-9e82-9581be49ff15.png)
![image](https://user-images.githubusercontent.com/35035442/117613347-7ca73900-b186-11eb-9a02-e6b54939b29a.png)
![image](https://user-images.githubusercontent.com/35035442/117613668-f50dfa00-b186-11eb-8989-8a2eacc70444.png)
![image](https://user-images.githubusercontent.com/35035442/117613701-048d4300-b187-11eb-8efa-f2549a1e52b0.png)
![image](https://user-images.githubusercontent.com/35035442/117613751-153db900-b187-11eb-972e-df5079c01a7c.png)

Also, when the screen is smaller, the AND/OR box will go below the label. Is it okay?

![image](https://user-images.githubusercontent.com/35035442/117613914-4b7b3880-b187-11eb-9789-f53fe4b490dd.png)

@SamCCSI @man-git007 @sweta-shrestha

**Comment by charlesyoung** [comment]
@adhikari-anish I was just about to give the green light. The mockups look good. 

FYI, OLC doesn't need an Arabic page. 

Can we not fix the menu for smaller screens? It doesn't look good under the label.

**Comment by SamCCSI** [comment]
The last mock-up works (for smaller screens). But where does the hover
window appear?

For larger screens this one is good.
[image: image.png]
Thanks.

**Comment by charlesyoung** [comment]
Please implement.

**Comment by adhikari-anish** [comment]
@charlesyoung The above UI changes have been implemented and deployed to the [RC staging site](https://staging.resourcecontracts.org/search/group?q=), but haven't been deployed to OLC yet. Please check. Thank you.

![image](https://user-images.githubusercontent.com/35035442/119965674-3e08df80-bfca-11eb-9575-1e5ebbd12e7e.png)

![image](https://user-images.githubusercontent.com/35035442/119965539-19146c80-bfca-11eb-853e-f134e3349079.png)

![image](https://user-images.githubusercontent.com/35035442/119968282-00598600-bfcd-11eb-8b1a-c7c1e974ec73.png)

cc @SamCCSI @man-git007 @sweta-shrestha @sriza

**Comment by charlesyoung** [comment]
Many thanks, I will get internal feedback.

**Comment by charlesyoung** [comment]
@adhikari-anish something small but can you please 'round' the edges of the box better? 

![image](https://user-images.githubusercontent.com/13888372/120154140-d3d18400-c1ef-11eb-809a-3a9eb3dd4a42.png)

**Comment by charlesyoung** [comment]
@adhikari-anish you can deploy to the OLC and RC Prod sites once the following has been done. 

- Box edges sorted out
- French text updated to the Google sheet. As an example, OU and ET should be on the buttons and some of the text isn't correct. 

https://docs.google.com/spreadsheets/d/1kQg8wJcW1nP6EywMs35PGco9-i0C7xiYlhIZ2ygdZis/edit#gid=0

**Comment by charlesyoung** [comment]
@adhikari-anish will it be possible to look at this?

**Comment by adhikari-anish** [comment]
@charlesyoung Thank you for the feedback and it is possible. I am looking at it. Can you please provide the translated text for OLC website too? For OLC, we have word annotated and for RC, we have word tagged. Right now we have put the google translated text but it's different from the text in the google sheet. So, it would be helpful if you provide for OLC too.

**Comment by charlesyoung** [comment]
@SamCCSI can you pls help with the above request?

**Comment by SamCCSI** [comment]
My intuition is that the OLC text would be as follows, but I am going to
double check with a native speaker

OU (par défaut) renvoie les documents annotés avec au moins l'un des
critères sélectionnés.
ET renvoie les documents annotés avec tous les critères sélectionnés.

**Comment by SamCCSI** [comment]
OLC text has been confirmed. Thanks

**Comment by adhikari-anish** [comment]
@charlesyoung 
The above changes have been done and are pushed to production sites ([RC](https://www.resourcecontracts.org/search/group?q=&lang=fr), [OLC](https://openlandcontracts.org/search/group?q=&lang=fr)). Please check it. Thank you.

![image](https://user-images.githubusercontent.com/35035442/121125420-407afd00-c846-11eb-9aa4-ee57a81d7615.png)

![image](https://user-images.githubusercontent.com/35035442/121125541-702a0500-c846-11eb-9a93-2e7bc6ea7281.png)

@SamCCSI @man-git007 @sriza @sweta-shrestha

**Comment by charlesyoung** [comment]
Thanks @adhikari-anish but I get the same search result using OR as well as AND. Using AND doesn't reduce the search results as it should do.

**Comment by adhikari-anish** [comment]
@charlesyoung 
The clause searching branch wasn't merged in the API repo. Now, it's merged and should be working. Please verify. Thank you.

**Comment by charlesyoung** [comment]
Thanks. 

@SamCCSI please check OLC and let us know if the ticket can be closed.

**Comment by SamCCSI** [comment]
On OLC the lay out is all messed up (see bottom right of screenshot) -- can
this be fixed, as a priority?

[image: image.png]

**Comment by SamCCSI** [comment]
posting screenshot again

![image](https://user-images.githubusercontent.com/12913915/121195151-5afca880-c83d-11eb-963b-b8d279d8b809.png)

**Comment by charlesyoung** [comment]
It's a caching issue, see below. 

![image](https://user-images.githubusercontent.com/13888372/121195289-c3647d80-c86f-11eb-9019-581413405792.png)

**Comment by SamCCSI** [comment]
OK it was a caching issue. Looks good now, and I confirm that it is working as planned based on a quick test of two categories (OR produced 140+ results, AND produced 4 results)

**Comment by charlesyoung** [comment]
@man-git007 is there anything we can do from the backend to resolve caching issues? Users might not realise what this issue is when presented with the image Sam just uploaded.

**Comment by adhikari-anish** [comment]
@charlesyoung The CSS version is now updated in both production sites. So, there won't be a cache issue as above. Thanks.
cc @SamCCSI @man-git007

**Comment by charlesyoung** [comment]
Thanks. Can we do the same for future development tasks to remove the caching issues experienced?

**Comment by adhikari-anish** [comment]
@charlesyoung Sure. Actually, I had forgotten to update the CSS version. I will keep it in my mind from now on.

**Comment by charlesyoung** [comment]
@adhikari-anish I have to apologise but there have been some French text changes. Will it be possible to look at  below Sheet text marked in yellow? Thanks 

https://docs.google.com/spreadsheets/d/1kQg8wJcW1nP6EywMs35PGco9-i0C7xiYlhIZ2ygdZis/edit#gid=0

**Comment by adhikari-anish** [comment]
@charlesyoung The French text has been changed and deployed to the prod site. Please verify [RC](https://www.resourcecontracts.org/search/group?q=&lang=fr).

**Comment by charlesyoung** [comment]
Many thanks.
