### ISSUE TITLE
Document sorting by year

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1366]
Documents are sorted chronologically by year when clicking on the [country ](https://www.resourcecontracts.org/countries/eg)link.

Documents are however not sorted chronologically by year when running a countries [search](https://www.resourcecontracts.org/search/group?q=&country%5B%5D=EG).

**Comment by charlesyoung** [comment]
The same issue with recently added. 

https://www.resourcecontracts.org/search/group?recent=1

**Comment by man-git007** [comment]
@charlesyoung Is it both for RC and OLC? Also, recent contracts are within 3 months gap and ordered in descending order

**Comment by SamCCSI** [comment]
Both.

Descending order according to what?

**Comment by man-git007** [comment]
@SamCCSI with signature year

**Comment by charlesyoung** [comment]
Below is the list of recent docs and it's not sorted by year. 

![image](https://user-images.githubusercontent.com/13888372/113677053-6f95b680-96bd-11eb-9578-d67209c2528a.png)

**Comment by charlesyoung** [comment]
@man-git007 please include the time estimate.

**Comment by man-git007** [comment]
@charlesyoung The time estimate for this ticket would be 4hrs

**Comment by charlesyoung** [comment]
@man-git007 please work on this ticket. Thanks

**Comment by sriza** [comment]
@charlesyoung 
The changes for this issue have been deployed to [staging](https://staging.resourcecontracts.org/search/group?q=&country%5B%5D=AR) site. Please verify.

![image](https://user-images.githubusercontent.com/24825118/115393600-9c8bb280-a201-11eb-962a-ac434e368815.png)

cc @man-git007

**Comment by charlesyoung** [comment]
Thanks @sriza. Please apply to the OLC and RC Prod sites.

**Comment by sriza** [comment]
@charlesyoung 
The changes are now deployed to both RC and OLC production sites. Please verify the changes.

cc @man-git007

**Comment by charlesyoung** [comment]
Thanks @sriza
