### ISSUE TITLE
Streamlining number of clicks to publish - backend

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#1368]
The process for publishing text/PDF/annotations involves a lot of clicks. Can any of these be removed?

- For OCR text: once rated green, can "publish button" immediately appear in action column rather than the blue "complete" button?
- For PDF/annotations, can we also just remove the "complete" button step and make the "publish" button appear?

![image](https://user-images.githubusercontent.com/12913915/113019001-21c5ff00-914f-11eb-931f-030f2e66a410.png)

More generally are there other ways to streamline this process? 

cc @charlesyoung

**Comment by man-git007** [comment]
@charlesyoung Should we remove the **complete** status from the admin side completely. We still need some clarity on this ticket

cc @SamCCSI

**Comment by charlesyoung** [comment]
@man-git007 please include the time estimate.

**Comment by man-git007** [comment]
@charlesyoung The time estimate for this ticket might be 18hrs

**Comment by charlesyoung** [comment]
@man-git007 how much time will be required to do below?

PDF/annotations, remove the "complete" button step and make the "publish" button appear

**Comment by charlesyoung** [comment]
@man-git007 will it be possible to get a time estimation?

**Comment by man-git007** [comment]
@charlesyoung The time estimation is already mentioned in the [excel file ](https://docs.google.com/spreadsheets/d/1CbNtEy8wTdyRNBzUFiWRbaPJmWq2h4Y0AjIOh2ao35U/edit#gid=0&range=9:9)that I have shared. Since [Mturk](https://github.com/NRGI/resourcecontracts.org/issues/1400) issue is also related to this so an additional of 4 hrs might add up. Also, should we also do this for annotation publish as well?

**Comment by charlesyoung** [comment]
Thanks, what xls file.

**Comment by man-git007** [comment]
@charlesyoung Sorry meant to say [google sheet](https://docs.google.com/spreadsheets/d/1CbNtEy8wTdyRNBzUFiWRbaPJmWq2h4Y0AjIOh2ao35U/edit#gid=0&range=9:9).

**Comment by sriza** [comment]
@charlesyoung 
Since this issue is now moved to sprint 30, when do you suggest we start working on this issue?

cc @man-git007

**Comment by charlesyoung** [comment]
@man-git007 please confirm that this task will take 16 hours.

**Comment by man-git007** [comment]
@charlesyoung This task can be completed within 16 hours.

cc @sriza

**Comment by charlesyoung** [comment]
@man-git007 please proceed.

cc @sriza @SamCCSI

**Comment by sriza** [comment]
@charlesyoung 
We have prepared a [google sheet](https://docs.google.com/spreadsheets/d/1peVci7Q7E-lCQ4rjXuy8qFZ035fojGJ7y37c6lUMjgk/edit#gid=0) with the list of contracts having the status `completed`. 
- The first sheet contains the list of contracts whose PDF status is set completed. Could you please publish those contracts? 
- The second sheet contains all the contracts that have either the metadata, PDF, or annotation status set as `completed`.
 
 We will be publishing all the data with the `completed` status. This can be done either manually or through the script. We will start working on the script. Could you please publish the data with `completed` status manually until then?
 
 Please let us know if you suggest otherwise.
 
 Thank you
 
 cc @man-git007 @anjesh @SamCCSI

**Comment by charlesyoung** [comment]
Not sure that we can do this automatically. See below examples. 

1. https://admin.resourcecontracts.org/contract/3622 - Actually needs to be transcribed so cannot be published. 
2. https://admin.resourcecontracts.org/contract/2719 - The document still needs to be published

Can you add a column to the xls noting and sorting if its a RC or OLC document.

**Comment by sriza** [comment]
@charlesyoung 
I have added a column to the first and second sheets to categorize contracts based on OLC and RC. Please have a look.

cc @man-git007

**Comment by charlesyoung** [comment]
Thanks, I will look at the RC docs on Monday. 

@SamCCSI will you be able to look at the OLC docs?

**Comment by SamCCSI** [comment]
Do we need to publish all docs with completed status in order for YI to proceed with the streamlining?

I ask because it may takes us some time to work through all of the docs. Many thanks

**Comment by charlesyoung** [comment]
@sriza the RC docs are done. 

@SamCCSI it shouldn't take too much time because most of the OLC docs relate to annotations not being published like the below doc. 

https://admin.resourcecontracts.org/contract/2910/annotate

**Comment by sriza** [comment]
@charlesyoung 
Shall we proceed with changes regarding the [removal of unpublish window](https://github.com/NRGI/resourcecontracts.org/issues/1368#issuecomment-906469263) ? 
Please let us know if you suggest any other changes to be done.

Thank you

cc @man-git007 @SamCCSI

**Comment by charlesyoung** [comment]
@sriza please proceed with @SamCCSI suggestion. 

'Eliminate this step and make it re-publish automatically when we click save on metadata.'

**Comment by sriza** [comment]
@SamCCSI 
I had few questions regarding the automatic republish.
- Should we automatically publish metadata that has the current status of `published` only or metadata with current status `draft`, `unpublished` and `rejected` should also get automatically published on save?
- Is automatic republish applicable to annotations as well?

It would be really helpful to proceed further if the above confusions were cleared.

As for now, we have removed the unpublished window and have also re-published the metadata with `published` status automatically on edit. The changes required by issue #1400 (automatically publishing the  pdf once the transcribed document is sent back to RC/OLC) is deployed to the staging site as well.

Please have a look and let us know if they are functioning as required.

Thank you

cc @man-git007 @charlesyoung

**Comment by SamCCSI** [comment]
> Should we automatically publish metadata that has the current status of published only or metadata with current status draft, unpublished and rejected should also get automatically published on save?
**Sam: Yes, auto-publish only when metadata has the current status of published and is then edited and saved.**

> Is automatic republish applicable to annotations as well?
**Sam: Yes.**

The staging site is working really nicely.

Can you please change the "Submit" button in metadata editing mode to "Save changes" ? This will make it clearer to users.

**Comment by SamCCSI** [comment]
New request -- can we have the same rule for published text?

Currently: when I edit a text page that is already published, then go back to contract page, it lists text as "Draft". Please change it so that it auto-saves the text changes that I make (when the text is already published.)

cc @charlesyoung

**Comment by SamCCSI** [comment]
![image](https://user-images.githubusercontent.com/12913915/131528386-17c6c3a6-657c-400f-85c3-4b74e368de2c.png)

**Comment by sriza** [comment]
@SamCCSI 
The changes related to re-publishing the text and annotations along with replacing 'submit' with 'save changes' in metadata edit form are now deployed to the staging site. Please have a look and let us know if it is functioning as it should.

Thank you

cc @man-git007 @charlesyoung

**Comment by SamCCSI** [comment]
all working nicely

i believe we have removed all docs with 'completed' status on the live back end. Could you please check this?

Ready to move to live site from my perspective.

Thank you!

**Comment by SamCCSI** [comment]
@sriza

**Comment by charlesyoung** [comment]
@sriza can you please confirm that all docs with a 'completed' status have been removed. 

cc @SamCCSI

**Comment by sriza** [comment]
@SamCCSI @charlesyoung 
We checked the contracts present in the live database and found that the completed status seems to have been removed from all the RC contracts whereas there were few OLC contracts having annotation status completed. These contracts are listed in a sheet named '20th Sept, OLC with completed status' on the [spreadsheet](https://docs.google.com/spreadsheets/d/1peVci7Q7E-lCQ4rjXuy8qFZ035fojGJ7y37c6lUMjgk/edit#gid=256496966). Could you please have a look at them and publish them?

Thank you

cc @man-git007

**Comment by SamCCSI** [comment]
An intern has just been assigned these 11 docs. I will report back once they are processed -- apologies for the hold up.

**Comment by SamCCSI** [comment]
@sriza all now changed to published.

**Comment by sriza** [comment]
@SamCCSI @charlesyoung 
We have checked the live database again and the contracts were found to be devoid of completed status. Thus, the changes related to `'Streamlining the number of clicks to publish'` and #1400 `'Mechanical Turk Workflow'` are now deployed to the production site.

Please have a look and let us know if they are functioning well.

Thank you

@man-git007

**Comment by SamCCSI** [comment]
Wonderful! I just tested one live contract and it appeared to work very
nicely. Many thanks for your work on this Shreeja!
