### ISSUE TITLE
Mobile view: collapse listing overlaps with title

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#1369]
If I try to collapse search results on my phone, it thinks i am clicking on the title, so it simultaneously collapses the results and takes me to the contract view page. 

We need to make the > sit apart from the title to avoid this overlap

cc @charlesyoung 

![OpenLandContracts org - Search Contracts](https://user-images.githubusercontent.com/12913915/113200212-08e44900-9236-11eb-8d0e-3842b76a8a02.png)

**Comment by man-git007** [comment]
@charlesyoung The time estimate for this task would be 0.75hrs

cc @sweta-shrestha @SamCCSI

**Comment by charlesyoung** [comment]
@man-git007 please work on this ticket. Thanks

**Comment by adhikari-anish** [comment]
@SamCCSI The above issue has been fixed and deployed to the [staging site](https://staging.resourcecontracts.org/search/group?q=).
![image](https://user-images.githubusercontent.com/35035442/115190646-1475b200-a108-11eb-97c9-a738e8767bf2.png)
cc @man-git007 @sweta-shrestha

**Comment by charlesyoung** [comment]
Looks good thanks.

@SamCCSI please approve before we move it to the Prod site.

**Comment by SamCCSI** [comment]
Approved

**Comment by adhikari-anish** [comment]
@charlesyoung The changes have been deployed to the [production site](https://www.resourcecontracts.org/search/group?q=). If it's okay, we can close this issue.

cc @man-git007 @sweta-shrestha

**Comment by charlesyoung** [comment]
Might be a caching issue but I don't see the changes yet on the Prod site accessed via a mobile device. Will check later today again. 

![image](https://user-images.githubusercontent.com/13888372/115352648-e6e84180-a1b7-11eb-9fe1-1c2fac762e00.png)

**Comment by adhikari-anish** [comment]
@charlesyoung I think it's because of the browser cache. Can you try it once again clearing the browser cache? I guess you are using Safari on IOS. You can clear a specific site's cache on Safari by following this [guide](https://apple.stackexchange.com/a/73697). Please, let me know if the issue still persists.
