### ISSUE TITLE
Failed PDF

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#1370]
How do we resolve contracts like this, and what causes this to happen? Would help to have the error message actually describe what happened. 

![image](https://user-images.githubusercontent.com/12913915/113875825-25780800-9785-11eb-8378-bfc42bb30609.png)

cc @charlesyoung

**Comment by charlesyoung** [comment]
@SamCCSI please attached the PDF doc.

**Comment by SamCCSI** [comment]
This was identified during a stock-take, so we don't even know what the doc
is or who uploaded it

**Comment by charlesyoung** [comment]
Could be a host of issues that can include the PDF being password protected, etc. 

I found the doc, see below. Can you get me the PDF doc? 

https://admin.resourcecontracts.org/contract/3877

**Comment by SamCCSI** [comment]
Thanks Charles. It looks like the uploader subsequently uploaded and
published this doc, so I will simply delete this entry. No further action
needed.
