### ISSUE TITLE
Backend drop down filters not working

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#1371]
I know this has been raised before but couldn't find the ticket.

Country filter not working. I select Congo, yet get results from Egypt, Turkey, etc

![image](https://user-images.githubusercontent.com/12913915/113879710-cb794180-9788-11eb-9e50-6135295edca9.png)

**Comment by charlesyoung** [comment]
I do below search and it seems to work. I get a search result of 175 documents. How many docs show in your search result? 

![image](https://user-images.githubusercontent.com/13888372/113880322-af42c800-97bb-11eb-8382-dd8c8ccf9b78.png)

**Comment by SamCCSI** [comment]
Still not working for me. It might be buggy when text search is also being
used -- e.g. i have "933" typed into text search, as well as using the
dropdowns
https://admin.resourcecontracts.org/contract?year=all&country=CG&category=olc&resource=all&q=933

**Comment by charlesyoung** [comment]
@SamCCSI should we still investigate this ticket?

If the full OCID, for example, isn't specified in the free text search box then it finds all docs with the 'shorten' ID and breaks the rest of the search queries like country and category.

**Comment by SamCCSI** [comment]
Yes please, given large number of docs on both RC and OLC, it is important that we can track down docs quickly when edits are needed. And right now the search sill seems buggy as you describe

**Comment by charlesyoung** [comment]
@man-git007 how much time will it take to address this issue?

**Comment by charlesyoung** [comment]
@man-git007 will it be possible to get a time estimation?

**Comment by man-git007** [comment]
@charlesyoung The time estimation for this would be 0.5 hr.

**Comment by charlesyoung** [comment]
OK thanks @man-git007, please work on this task when you have time. 

cc @SamCCSI

**Comment by sriza** [comment]
@charlesyoung 
The issue related to the backend filter has been resolved and is now deployed to the [staging](https://admin-staging.resourcecontracts.org/contract?year=all&country=CD&category=all&resource=Zinc&q=united+resource) site. Please have a look and verify if it is functioning properly.

Thank you

cc @man-git007

**Comment by charlesyoung** [comment]
Thanks @sriza 

@SamCCSI will you be able to run some test searches on the Staging admin site to confirm that the filtering has been fixed?

**Comment by SamCCSI** [comment]
Seems to be working. Please deploy; thanks!

**Comment by sriza** [comment]
@charlesyoung 
The fixes for the backend filter have been deployed to the [production](https://admin.resourcecontracts.org) site as well. Please verify the changes.

Thank you

cc @man-git007
