### ISSUE TITLE
Countries page URL

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1374]
@manishgs is it not possible for this link to work https://resourcecontracts.org/countries/sl compared to https://www.resourcecontracts.org/countries/sl

The Sierra Leone website http://www.nma.gov.sl/ has a RC link but it's the one without www so it doesn't work.

**Comment by charlesyoung** [comment]
@man-git007 can you look at this, please. 

I was just contacted by the Equatorial Guinea EITI office saying that the RC link that used to work on their site is now broken. This urgently needs to be addressed. 

https://eiti-ge.org/datos-estadisticos/

The link, like for Sierra Leone, is without the www (https://resourcecontracts.org/search?q=Guinea+equatorial). It used to work when I checked last year so not sure what has changed.

**Comment by man-git007** [comment]
@charlesyoung The link seems to be working even without `www`.

![Screenshot from 2021-04-22 11-46-56](https://user-images.githubusercontent.com/23434972/115663589-792b4980-a360-11eb-8792-c8baf675e8f8.png)
![Screenshot from 2021-04-22 11-46-38](https://user-images.githubusercontent.com/23434972/115663611-80eaee00-a360-11eb-8f0e-881dbb4315c6.png)

**Comment by charlesyoung** [comment]
Thanks, seemed to be an issue with my hosts site entries.
