### ISSUE TITLE
Contact information 

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1376]
@man-git007 please update all contact info to resourcecontracts@resourcegovernance.org. 

I see there is an info-resourcecontracts@resourcegovernance.org email address used to notify users when the site crashes which is incorrect. 

We are sorry. There is a problem loading the contract. Please contact info-resourcecontracts@resourcegovernance.org to let us know about the issue.

**Comment by man-git007** [comment]
@charlesyoung Is this for RC or OLC as well?

**Comment by charlesyoung** [comment]
This is only for RC.

**Comment by man-git007** [comment]
@charlesyoung The email is maintained in the environment variable `CONTACT_MAIL`. So need to contact with `cloudelligent` team.

**Comment by charlesyoung** [comment]
Thanks but why if it's maintained in CONTACT_MAIL are there different email addresses?

**Comment by man-git007** [comment]
@charlesyoung Since it's been used across the RC, OLC, and CountrySite. So, if the email changes in the future it won't affect the other sites.

**Comment by charlesyoung** [comment]
@zaid-azmat will you be able to look at this ticket?

**Comment by qakhtar2** [comment]
@man-git007 I can see multiple contact email variables, may I know the exact variables, and the just to make sure this should be the contact email ? 
resourcecontracts@resourcegovernance.org

**Comment by zaid-azmat** [comment]
@man-git007 I can see multiple contact email variables, may I know the exact variables, and the just to make sure this should be the contact email ?
resourcecontracts@resourcegovernance.org

**Comment by charlesyoung** [comment]
@zaid-azmat resourcecontracts@resourcegovernance.org is the correct email address.

**Comment by charlesyoung** [comment]
Remember the update only needs to happen to RC and not OLC. The OLC email address is info@openlandcontracts.org

**Comment by qakhtar2** [comment]
@charlesyoung i have replaced info-resourcecontracts@resourcegovernance.org with resourcecontracts@resourcegovernance.org

**Comment by zaid-azmat** [comment]
@charlesyoung i have replaced info-resourcecontracts@resourcegovernance.org with resourcecontracts@resourcegovernance.org

**Comment by charlesyoung** [comment]
Many thanks.
