### ISSUE TITLE
Sorting search results by year or resource leads to 404 error

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#1377]
https://www.openlandcontracts.org/search/group?q=&country%5B0%5D=LR&document_type%5B0%5D=Contract&page=2&order=asc&sortby=year

https://www.openlandcontracts.org/search/group?q=&country%5B0%5D=LR&document_type%5B0%5D=Contract&page=2&order=asc&sortby=resource

![image](https://user-images.githubusercontent.com/12913915/116108192-ae49db80-a681-11eb-92c7-bbd81be8e712.png)

**Comment by charlesyoung** [comment]
This also occurs on RC. 

@man-git007 can you please look at this bug?

**Comment by charlesyoung** [comment]
@man-git007 how much time is required to resolve this issue?

**Comment by sriza** [comment]
@charlesyoung 
The fixes for this issue have been deployed to the production site. Please have a look and let us know if the issue persists.
The time required to solve this issue was 0.75 hours.

cc @man-git007

**Comment by charlesyoung** [comment]
Great thanks, works well. 

@SamCCSI please verify and close the ticket if all OK. BTW below doc has a signature year of 1001. 

https://openlandcontracts.org/contract/ocds-591adf-6204888114/view#/pdf

**Comment by SamCCSI** [comment]
Working beautifully, thanks.

(Charles, that contract has 1001 for year because it's undated)

**Comment by charlesyoung** [comment]
OK thanks.
