### ISSUE TITLE
Auto-saving of annotation?

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#138]
As an annotator, I would like to be able to enter an annotation and then 'click out' of the annotation balloon, and have the annotation save itself without me having to click 'save'.

That said, I would like the 'cancel' button to remain, so that I can cancel and not create unwanted annotations.

![image](https://cloud.githubusercontent.com/assets/12913915/8661717/865c1278-2987-11e5-8c45-ddf5c4092b8d.png)

@anderspeders do you think this is a sensible request? Or is it better to keep as is?

**Comment by anderspeders** [comment]
We will need to examine if this is within the core features of annotator.js. 

I will park it on our wishlist for now.

**Comment by charlesyoung** [comment]
@SamCCSI is this still required?

**Comment by SamCCSI** [comment]
@charlesyoung Not at this stage. Thanks!
