### ISSUE TITLE
Government Entity

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1380]
@man-git007 I cannot seem to add a new Government Entity in the RC Prod site while I can on the Staging Site. 

I'm trying to add Société Aurifère du Kivu et du Maniema under DR Congo.

**Comment by man-git007** [comment]
@charlesyoung You are talking about the admin side right? Could you please provide some screenshots?

**Comment by charlesyoung** [comment]
Thanks @man-git007 

Yes, it relates to the admin tool, although it now seems to work which is strange. 

Will close this ticket and reopen it when the problem arises again.
