### ISSUE TITLE
Search results number vs. Excel export number

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1382]
@man-git007 there seems to be a bug wrt the number of search results versus the number exported to Excel. 

Below search for instance returns 54 documents but only 38 are exported to Excel. 

https://resourcecontracts.org/search/group?q=&resource%5B0%5D=Hydrocarbons&year%5B0%5D=2021&year%5B1%5D=2020&year%5B2%5D=2019&year%5B3%5D=2018&year%5B4%5D=2017&year%5B5%5D=2016&language%5B0%5D=en&page=1

**Comment by charlesyoung** [comment]
@man-git007 have you had time to look at this issue? How much time will be required to fix the issue?

**Comment by sriza** [comment]
@charlesyoung 
We found the number of contracts in excel and the ones displayed in the listing page to be equal when counted manually. The issue seems to be with the count shown in the listing page.
This might take quite some time to debug. We have estimated it to be around 4 hours for now. 

cc @man-git007

**Comment by charlesyoung** [comment]
Thanks @sriza 

Let's try to keep it to 4 hours if possible.

**Comment by charlesyoung** [comment]
@sriza just checking on the status of this ticket.

**Comment by sriza** [comment]
@charlesyoung 
We have been looking into this issue but couldn't give it quite enough time as we are also working with tickets related to additional columns and the code list. We will continue working on this ticket next week and will inform you once it's done.
Thank you 

cc @man-git007

**Comment by charlesyoung** [comment]
Thanks @sriza

**Comment by charlesyoung** [comment]
@sriza just checking what the latest is with this ticket.

**Comment by sriza** [comment]
@charlesyoung 
It seems like we might require some more time to work on this issue. We will get back to you once it's done.

cc @man-git007

**Comment by man-git007** [comment]
@charlesyoung We are not able to give time to this ticket. We will work on it by next week.

cc @sriza

**Comment by charlesyoung** [comment]
@man-git007 can we try to finish this ticket by Friday?

**Comment by man-git007** [comment]
@charlesyoung OK we will try to finish this ticket by this Friday.

**Comment by man-git007** [comment]
@charlesyoung We have worked on this ticket and have deployed it in the [staging](https://staging.resourcecontracts.org/search/group?q=&resource%5B0%5D=Hydrocarbons&year%5B0%5D=2021&year%5B1%5D=2020&year%5B2%5D=2019&year%5B3%5D=2018&year%5B4%5D=2017&year%5B5%5D=2016&language%5B0%5D=en&page=1) server. Could you please verify. If all is OK we will deploy this to the [live](https://resourcecontracts.org/search/group?q=&resource%5B0%5D=Hydrocarbons&year%5B0%5D=2021&year%5B1%5D=2020&year%5B2%5D=2019&year%5B3%5D=2018&year%5B4%5D=2017&year%5B5%5D=2016&language%5B0%5D=en&page=1) site.

cc @sriza @anjesh

**Comment by charlesyoung** [comment]
Many thanks @man-git007 

I will get confirmation internally and revert back on Monday.

**Comment by charlesyoung** [comment]
@man-git007 please deploy to Prod. Thanks

**Comment by man-git007** [comment]
@charlesyoung Has been deployed to the live server. If all is OK please close this ticket.

cc @anjesh @sriza

**Comment by charlesyoung** [comment]
Thanks.
