### ISSUE TITLE
Additional columns in Excel download file 

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1385]
Add below fields to the RC and OLC Excel download file. 

- Signature Year - We have a signature date but not a year, needs to be added after the signature date field
- ResourceContracts/OpenLandContracts Document URL - We have a PDF URL field but that only opens the actual doc on AWS, we want to add a link that will open the document directly in RC or OLC. Needs to be added before the PDF URL field. 

@man-git007 please let me know how much time will be required to add the 2 columns? 

cc @SamCCSI

**Comment by sriza** [comment]
@charlesyoung 
We will be requiring 4 hours to add these two columns to the Excel download file.
Since I will be on leave next week, we will only begin working on this issue the week after the next week.

cc @man-git007

**Comment by charlesyoung** [comment]
Great, many thanks @sriza

**Comment by sriza** [comment]
@charlesyoung
Is the ResourceContract/OpenLandContracts Document URL the link to contract [view](https://openlandcontracts.org/contract/ocds-591adf-1281238394/view#/pdf) page? 
Also, the OLC Excel download file doesn't seem to contain a PDF URL field. Is it ok if we add the Document URL right after the contract name?

cc @man-git007

**Comment by charlesyoung** [comment]
Thanks @sriza 

Yes, that is the correct page.

**Comment by SamCCSI** [comment]
Is it possible to make the OLC excel download have the same fields as the
RC one?

(Charles, do you know if there are any RC-specific fields that wouldn't be
applicable?)

**Comment by charlesyoung** [comment]
@SamCCSI I think it might be easier to add the 2 columns to the existing RC and OLC spreadsheet formats. 

So as an example the RC xls has an additional 'Association' column (defining if a main or supporting doc) and it doesn't have the "Deal Number' column because it's not relevant to RC. 

Agree?

**Comment by SamCCSI** [comment]
Sounds good, thanks Charles

>

**Comment by sriza** [comment]
@charlesyoung
I found that the links in the RC excel file were underlined, colored in blue, and had hyperlinks which was not the case with OLC excel files. 
- RC Excel File
![image](https://user-images.githubusercontent.com/24825118/122896617-f5dea200-d368-11eb-8f9f-304a6607b1ce.png)
- OLC Excel File
![image](https://user-images.githubusercontent.com/24825118/122897898-22df8480-d36a-11eb-91a2-04beeb8abd71.png)

Should we add similar properties to links in OLC Excel files too?

cc @man-git007

**Comment by charlesyoung** [comment]
Yes thanks, will be good to hyperlink all URLs.

**Comment by charlesyoung** [comment]
@sriza just checking on the status of this ticket.

**Comment by sriza** [comment]
@charlesyoung 
The changes for this issue have been deployed to the staging sites.
- OLC
![image](https://user-images.githubusercontent.com/24825118/123364513-3ec66e80-d594-11eb-801c-27a5aad6f12b.png)
![image](https://user-images.githubusercontent.com/24825118/123364536-4e45b780-d594-11eb-8ff0-fd0e1e80328f.png)
- RC
![image](https://user-images.githubusercontent.com/24825118/123364782-c8763c00-d594-11eb-9ddd-52ed364c7bed.png)
![image](https://user-images.githubusercontent.com/24825118/123365000-24d95b80-d595-11eb-8f61-0ecf6a390bb0.png)

Please verify and let us know if any changes are to be made.
Thank you

cc @man-git007

**Comment by charlesyoung** [comment]
Thanks @sriza. 

Will it be possible to make the year a number and not a text field?

![image](https://user-images.githubusercontent.com/13888372/123379257-26535580-d58e-11eb-8e35-cd617dcbce87.png)

**Comment by sriza** [comment]
@charlesyoung 
The column 'Signature Year' has been converted to a number field. The changes are deployed to the staging sites. Could you please have a look and let us know if it is ok?
Thank you

cc @man-git007

**Comment by charlesyoung** [comment]
Thanks, will get internal approval by Monday.

**Comment by charlesyoung** [comment]
Looks good except the “Document URL” should be "ResourceContracts/OpenLandContracts Document URL”. Seeing that the xls downloads are slightly different I think we should have “ResourceContracts Document URL” for RC and "OpenLandContracts Document URL” for OLC. 

@SamCCSI what do you think?

**Comment by charlesyoung** [comment]
@sriza please add “ResourceContracts Document URL” for RC and "OpenLandContracts Document URL” for OLC.

**Comment by sriza** [comment]
@charlesyoung 
The column title "Document URL" has been replaced by "ResourceContracts Document URL" for RC and "OpenLandContracts Document URL" for OLC. 
- RC
![image](https://user-images.githubusercontent.com/24825118/125400105-357d3480-e3d1-11eb-8c36-51bc2a918665.png)

- OLC
![image](https://user-images.githubusercontent.com/24825118/125398604-3f059d00-e3cf-11eb-92b7-916ee9a47fd2.png)

Please have a look and let us know if it is ok.
Thank you

cc @man-git007

**Comment by charlesyoung** [comment]
Please implement for RC. 

@SamCCSI you happy to implement for OLC?

**Comment by SamCCSI** [comment]
Please implement for OLC

**Comment by sriza** [comment]
@charlesyoung 
These changes have been implemented to both RC and OLC production sites.
- RC
![image](https://user-images.githubusercontent.com/24825118/126101525-4b98d10e-454f-4552-af66-043b06acfbab.png)
![image](https://user-images.githubusercontent.com/24825118/126101553-3478913e-9943-4178-a768-1fc068f14ee7.png)

- OLC
![image](https://user-images.githubusercontent.com/24825118/126101703-7aba6de2-d7ff-454a-ae6e-04838c19ab2a.png)
![image](https://user-images.githubusercontent.com/24825118/126101661-334db2f7-6daf-4b32-8410-3f54b914103a.png)

Please verify the changes.

Thank you

cc @man-git007 @SamCCSI

**Comment by charlesyoung** [comment]
Many thanks.
