### ISSUE TITLE
Replacing 'contract type' with 'doc type' in search results and doc view - OLC only

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#1387]
## Why
OLC features a lot of docs that aren't contracts, meaning that the final column in search results is often blank.
![image](https://user-images.githubusercontent.com/12913915/122109080-f6b48880-cdea-11eb-87da-cb4c42ef70d6.png)

## What
Replace 'contract type' with 'doc type' for (1) search result display and (2) right column in doc view mode

**Comment by charlesyoung** [comment]
@man-git007 how much time will be required to implement this ticket?

**Comment by adhikari-anish** [comment]
@SamCCSI Do you mean to change this table column title from "Contract Type" to "Document Type"?
![image](https://user-images.githubusercontent.com/35035442/122706959-c3557c00-d278-11eb-9d36-2dad29ff5707.png)

and this "Type of Contract" to "Type of Document" in the document view page?
![image](https://user-images.githubusercontent.com/35035442/122707209-3c54d380-d279-11eb-8a87-a5c79b5b906f.png)

Also in See summary page
![image](https://user-images.githubusercontent.com/35035442/122707334-8b9b0400-d279-11eb-8bee-d2f742fa0150.png)

If so, can you please provide the French translation for "Document Type" and "Type of Document"? Otherwise, if it's okay, we will put google translated text.

@charlesyoung @man-git007

**Comment by charlesyoung** [comment]
Yes, that's correct but I will ask that @SamCCSI confirms. 

How much time will it take to implement?

**Comment by adhikari-anish** [comment]
@charlesyoung This may take 2.5 hours to implement.

**Comment by charlesyoung** [comment]
Thanks. Please go ahead once @SamCCSI agrees to above.

**Comment by SamCCSI** [comment]
Correct, thanks all.

The french is : Type de document

>

**Comment by adhikari-anish** [comment]
@charlesyoung In see summary page, after the above change, these two fields conflicted in their name.

![image](https://user-images.githubusercontent.com/35035442/122882847-50bdcc80-d35c-11eb-9d7b-1e58486cdd93.png)

Also, in French translation, both "Document Type" and "Type of document" translates to "Type de document".

![image](https://user-images.githubusercontent.com/35035442/122883060-89f63c80-d35c-11eb-9242-a8b0419f5eb6.png)

@SamCCSI @man-git007 @sriza

**Comment by SamCCSI** [comment]
@adhikari-anish this is a mistake at our end -- those are indeed the same fields, so we should not duplicate.

In this contract summary page, could you please revert to the contract type field that was there before? Effectively, no changes should be made to this page.

The changes to search results and left column of contract view page are still valid though.

**Comment by adhikari-anish** [comment]
@SamCCSI The changes have been made and deployed to staging sites. Please verify. Thank you. [RC](https://staging.resourcecontracts.org/search/group?q=&lang=en), [OLC](https://staging.openlandcontracts.org/search/group?q=&lang=en)

![image](https://user-images.githubusercontent.com/35035442/123364351-f5761f00-d593-11eb-93c6-54537b3568a2.png)

![image](https://user-images.githubusercontent.com/35035442/123364137-9912ff80-d593-11eb-8ab1-50a2996da8b0.png)

![image](https://user-images.githubusercontent.com/35035442/123364416-15a5de00-d594-11eb-8e67-c098a609e60f.png)

@charlesyoung @man-git007 @sriza

**Comment by charlesyoung** [comment]
@adhikari-anish please note that this ticket only relates to OLC and not RC.

**Comment by adhikari-anish** [comment]
@charlesyoung I just put RC image and link to verify that the changes aren't reflected in RC site.

**Comment by adhikari-anish** [comment]
@charlesyoung Are the changes okay?

**Comment by charlesyoung** [comment]
@SamCCSI needs to approve this ticket.

**Comment by charlesyoung** [comment]
FYI, @SamCCSI is on leave until the 12 July.

**Comment by adhikari-anish** [comment]
@charlesyoung Thank you for the info.

**Comment by SamCCSI** [comment]
Thanks @adhikari-anish 

The heading looks good. 

However, the field shown for each doc under the heading is still contract type (e.g. Concession Agreement). It should be document type (e.g. Contract, or Environmental and Social Document).

Can you please make that change or let us know if it will take a lot of work so that we can reassess?

**Comment by adhikari-anish** [comment]
@SamCCSI The fields under the heading have been changed to document type as well. Please verify. [olc](https://staging.openlandcontracts.org/search/group?q=)

![image](https://user-images.githubusercontent.com/35035442/125912016-6036c346-3036-40e9-a8b8-62844d7dcdeb.png)
![image](https://user-images.githubusercontent.com/35035442/125912538-0c7fe7a4-c951-4a1d-bdf5-00a771f56125.png)

cc @man-git007 @sriza @charlesyoung

**Comment by SamCCSI** [comment]
Looks good to me. Please proceed.

**Comment by adhikari-anish** [comment]
@SamCCSI Thanks. This will be moved to production together with the code list updates issue. Once it is moved, I'll inform you.

**Comment by adhikari-anish** [comment]
@charlesyoung This issue and code list updates issue both have been pushed to production. Please verify. 
cc @SamCCSI @man-git007

**Comment by charlesyoung** [comment]
Thanks @adhikari-anish 

@SamCCSI can you please confirm that you are happy to close this ticket.

**Comment by SamCCSI** [comment]
Perfect
