### ISSUE TITLE
Missing annexes and pages

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1390]
@man-git007 how much time will be needed to update below to 'This document has missing annexes' and 'This document has missing pages'? So replace all the current text with the above. 

![image](https://user-images.githubusercontent.com/13888372/123211462-c8f2d200-d4c3-11eb-9e29-e6a208529456.png)

cc @SamCCSI

**Comment by adhikari-anish** [comment]
@charlesyoung Do you mean like this? 

![image](https://user-images.githubusercontent.com/35035442/123623655-71d75f00-d82d-11eb-9c05-9eae7c9f90b2.png)

Also, do you want this change in the admin site? 
![image](https://user-images.githubusercontent.com/35035442/123623727-8582c580-d82d-11eb-8d93-2916dfef004f.png)

![image](https://user-images.githubusercontent.com/35035442/123623833-9fbca380-d82d-11eb-83b6-c4749fe57fcc.png)

cc @man-git007

**Comment by charlesyoung** [comment]
Hi. It should only show the new text without the 'Yes'. 

It's fine from the admin side.

**Comment by adhikari-anish** [comment]
@charlesyoung This will take 1.5 hrs. Do you want this change on both sites (RC and OLC)? Also, can you please provide me the above text in French and Arabic?

**Comment by charlesyoung** [comment]
Thanks @adhikari-anish 

Yes, it's both for RC and OLC. 

Arabic:
Annex: هذه الوثيقة بها ملاحق مفقودة
Pages: هذا المستند يحتوي على صفحات مفقودة

@SamCCSI can you please help with the French transaltions?

**Comment by charlesyoung** [comment]
@adhikari-anish just checking what the latest is with this ticket.

**Comment by adhikari-anish** [comment]
@charlesyoung I'm working on this. Will push the changes tomorrow.

**Comment by adhikari-anish** [comment]
@charlesyoung The changes have been deployed to both staging sites [rc](https://staging.resourcecontracts.org/contract/ocds-591adf-7028481710/view#/pdf), [olc](https://staging.openlandcontracts.org/contract/ocds-591adf-2106604888/view#/pdf). Please verify.

![image](https://user-images.githubusercontent.com/35035442/124890971-45270280-dff8-11eb-9da2-d9510a9c7733.png)

![image](https://user-images.githubusercontent.com/35035442/124891036-540db500-dff8-11eb-8af3-040460f230c2.png)

cc @man-git007

**Comment by charlesyoung** [comment]
Thanks @adhikari-anish 

I will get internal feedback and get back to you.

**Comment by charlesyoung** [comment]
@adhikari-anish please implement on the Prod site. Thanks

**Comment by adhikari-anish** [comment]
@charlesyoung The changes have been implemented on Prod sites [olc](https://openlandcontracts.org/contract/ocds-591adf-6204888114/view#/pdf). Please verify. Thanks. 

![image](https://user-images.githubusercontent.com/35035442/125613086-dd3635e2-a67c-49e4-a438-b590348e2f14.png)

cc @man-git007

**Comment by charlesyoung** [comment]
OLC Prod site only or also the RC Prod site?

**Comment by adhikari-anish** [comment]
@charlesyoung Also RC prod site.

**Comment by charlesyoung** [comment]
@SamCCSI you happy for us to close this ticket?

**Comment by SamCCSI** [comment]
English version looks good on [this example](https://www.openlandcontracts.org/contract/ocds-591adf-6994465275/view?lang=en#/).

Is the French language just from google translate? If so I will check with a native speaker.

**Comment by SamCCSI** [comment]
Have confirmed that the French should be:

**Ce document n'inclut pas les annexes**

Can this language be used on RC and OLC?

**Comment by adhikari-anish** [comment]
@SamCCSI Yes, it can be used. I'm changing it. Is the french text okay for "This document has missing pages"?

**Comment by SamCCSI** [comment]
"This document has missing pages" should be "Ce document ne contient pas
toutes les pages"

**Comment by charlesyoung** [comment]
@adhikari-anish can we try to finish this ticket.

**Comment by adhikari-anish** [comment]
@charlesyoung The changes of french text have been deployed to prod sites. Please verify.

**Comment by charlesyoung** [comment]
Thanks. @SamCCSI are you happy to close this ticket?

**Comment by SamCCSI** [comment]
Yes, thanks
