### ISSUE TITLE
ABBYY Documents Rerun 

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1399]
@man-git007 there seem to be old documents that never underwent an OCR process due to not having enough credits. Is there a quick way to rerun the OCR process rather than for me to delete the document with metadata and recapture the information? 

https://admin.resourcecontracts.org/contract/2599/review
https://admin.resourcecontracts.org/contract/2601/review
https://admin.resourcecontracts.org/contract/2600/review
https://admin.resourcecontracts.org/contract/2603/review
https://admin.resourcecontracts.org/contract/2602/review

**Comment by charlesyoung** [comment]
@man-git007 any ideas?

**Comment by man-git007** [comment]
@charlesyoung For contracts to redo the OCR process we need to run a PHP command in the server itself and would be needing the assistance of cloudelligent. Also, it would be helpful if we could test this in the staging server first before implementing it in the production server.

**Comment by charlesyoung** [comment]
Thanks @man-git007 

Will you be able to run a query to identify the documents where no OCR process was run? Also, can the PHP command be run on a list of documents rather than the entire set?

**Comment by man-git007** [comment]
@charlesyoung I have listed the contracts in the [google sheet](https://docs.google.com/spreadsheets/d/1R3kHumTtGnmPN0OKzwAw62UlmOYFBmAHQC_0Ez1UbJ8/edit#gid=0). Please look into this.

The OCR command cannot be run for a specific page and will be run for the whole document pages.

cc @anjesh

**Comment by charlesyoung** [comment]
Thanks @man-git007 

So you can run be run on the 12 noted documents?

**Comment by man-git007** [comment]
@charlesyoung We need server access to run the command on these documents. For this cloudelligent should run a PHP command in the production server. I could mail them the command.

**Comment by charlesyoung** [comment]
Thanks @man-git007 but can I confirm that you can run the script for only those 12 documents? It will create a mess if it's run on already OCR'ed documents.

**Comment by man-git007** [comment]
@charlesyoung Yes the command would be run for those 12 documents only, but note that the command would be run for all the pages of those documents.

**Comment by charlesyoung** [comment]
OK thanks. How much time will you need (want to add it to the support Google sheet)? Can you contact cloudelligent?

**Comment by man-git007** [comment]
@charlesyoung This won't take that much time as it's just a command but for doing some preliminary research for this ticket it took about 4hrs. The command execution time for all the 12 documents might take 0.5hr at the cloudelligent end.

**Comment by charlesyoung** [comment]
@man-git007 Zaid ran the commands but I now get below error on those specific documents. 

Sorry, the page you are looking for could not be found.

**Comment by man-git007** [comment]
@charlesyoung The three documents seem to have the OCR process failed. We could rerun the OCR process for those three documents. If that doesn't work we might need to re-upload those three documents.
