### ISSUE TITLE
Mechanical Turk Workflow

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1400]
Once the transcribed document is sent back to RC / OLC

![image](https://user-images.githubusercontent.com/13888372/128666343-8937fe3c-edcb-43cf-92b0-75d145df8ccf.png)

The text status changes from 'Needs Transcription' to 'Acceptable'. 

![image](https://user-images.githubusercontent.com/13888372/128666512-48597db0-e60a-42fa-9a9e-1ed6dd893f9e.png)

![image](https://user-images.githubusercontent.com/13888372/128666560-531341ae-1e33-4ad9-92cc-3e0e01c0027e.png)

But the text still needs to be published manually even after the transcribed document was reviewed beforehand. 

Request: Automatically update the text quality to 'Acceptable' **AND** publish the text.

**Comment by charlesyoung** [comment]
@man-git007 how much time will this task take?

**Comment by man-git007** [comment]
@charlesyoung Are you suggesting publishing the pdf text directly after `Acceptable` is clicked in the text quality section?

cc @sriza

**Comment by charlesyoung** [comment]
@man-git007 
1. Publish the text automatically after 'Acceptable' is selected in the text quality section
2. Publish the text automatically once the 'Send to RC' button is selected in Mechanical Turk.

**Comment by charlesyoung** [comment]
@man-git007 will it be possible to get a time estimation?

**Comment by charlesyoung** [comment]
@man-git007 please confirm that this task will take 4 hours.

**Comment by man-git007** [comment]
@charlesyoung Since this ticket is related to [https://github.com/NRGI/resourcecontracts.org/issues/1368](https://github.com/NRGI/resourcecontracts.org/issues/1368) ticket we have estimated 4hrs for this ticket if have to work only on this ticket there might be the addition of 2hrs.

cc @sriza

**Comment by charlesyoung** [comment]
@man-git007 please proceed. 

cc @sriza @SamCCSI

**Comment by charlesyoung** [comment]
@man-git007 just checking on the progress of this ticket.

cc @sriza @SamCCSI

**Comment by sriza** [comment]
@charlesyoung 
The changes related to this issue are deployed in the staging site. Please have a look and let us know if the changes are functioning as required.

Thank you

cc @man-git007

**Comment by charlesyoung** [comment]
@sriza there arent any documents in such a state on the staging site so we might have to deploy to the production site and test when documents have been fully transcribed. 

cc @SamCCSI

**Comment by charlesyoung** [comment]
@sriza can you deploy this to the production site? As mentioned there are no documents on the staging site that this can be tested on so we will need to do this on the production site.

**Comment by charlesyoung** [comment]
OK, will do. Thanks

**Comment by sriza** [comment]
@charlesyoung 
Are the changes related to this ticket working well at the production site? If everything is working fine, can this ticket be closed?

cc @man-git007

**Comment by charlesyoung** [comment]
I still haven't managed to test this on the prod site without documents that need to be sent to RC. Let's keep this ticket open for now. Thanks

**Comment by sriza** [comment]
@charlesyoung 
Are the changes related to this ticket tested on the production site? Please let us know if they are functioning well.

Thank you

cc @man-git007

**Comment by charlesyoung** [comment]
Will do, I still need to publish a transcribed contract in full.
