### ISSUE TITLE
Add new filters to backend contract search

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#1407]
Request from longtime administrator to help save time locating dos on the backend.

Can YI please provide a quote for this work?

Add the following two dropdown filters on the below search page:
- Filter for document type
- Filter for contract type
- Filter for language
- Filter for company name

All should be ordered in the same way as on the front-end search page.

![image](https://user-images.githubusercontent.com/12913915/131048464-aa846e13-0629-4f0f-8546-24fe4baf506f.png)

cc @charlesyoung

**Comment by charlesyoung** [comment]
@SamCCSI just a heads-up that we won't include a filter for company names because of the various company name spellings.

**Comment by SamCCSI** [comment]
@charlesyoung  Is it much extra work? My staff saw value in it, even if there is some variation

**Comment by charlesyoung** [comment]
It's more about dirty data (duplicate company names) like shown below. 

<img width="960" alt="image" src="https://user-images.githubusercontent.com/13888372/144252209-79117aa0-9712-475b-92a3-a54a74811790.png">

**Comment by SamCCSI** [comment]
Understood. We can clean this up.

**Comment by charlesyoung** [comment]
@mabuturab1 tested and approved on Staging.
