### ISSUE TITLE
Add additional published labels on backend search results

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#1408]
**The problem**
On backend, in the search results, a "Published" label shows for metadata published, but it does not show if text is published and annotations are published.

**The request**
Change the one published label to 3 different ones - one for metadata, one for text, and one for annotations. Each needs to be labeled so that it is clear.

![image](https://user-images.githubusercontent.com/12913915/131048828-a13652e7-ee7e-48e0-b58e-bcabd9e348bd.png)

Can YI please prepare a quote?

**Comment by charlesyoung** [comment]
@mabuturab1 tested and approved on Staging.

**Comment by charlesyoung** [comment]
Tested on Prod and its working.
