### ISSUE TITLE
Problems accessing two listed docs on the backend

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#1409]
There two documents that I am not able to access for some reason. Whenever I try to open [UPC Renewable, Social Impact Assessment (FR), 2015 ](https://admin.resourcecontracts.org/contract/5107)or [UPC Renewable, Environmental and Social Action Plan (FR), 2015](https://admin.resourcecontracts.org/contract/5107), I get a screen saying “Whoops, looks like something went wrong.” 

Could YI please check why that is the case?

These 2 docs are accessible on the front end:

- https://www.openlandcontracts.org/contract/ocds-591adf-0874791048/view#/pdf
- https://www.openlandcontracts.org/contract/ocds-591adf-1656529821/view#/pdf

**Comment by charlesyoung** [comment]
Just a further note that the public site also crashes on those 2 docs when clicking on the links. 

![image](https://user-images.githubusercontent.com/13888372/131342555-de418e08-0df2-49ba-b38b-cd80b9727c4a.png)

**Comment by charlesyoung** [comment]
Received errors for docs 5104 and 5107 which relate to those 2 docs. 

![image](https://user-images.githubusercontent.com/13888372/131345944-379d9bd8-6659-4e63-87c4-50b8480150dc.png)

**Comment by charlesyoung** [comment]
Please only focus on the backend because these documents cannot even be opened on the backend which is causing the frontend error. 

https://admin.resourcecontracts.org/contract/5104
https://admin.resourcecontracts.org/contract/5107

**Comment by mabuturabcloudelligent** [comment]
Hi @charlesyoung 
We looked into database values of above contracts(5104, 5107) and it looks like that some of the fields are corrupted(looks like document type has invalid values).
As a resolution that you are expecting against this ticket, would you be fine that 

1. we manually interfere with database to get those values corrected for these 2 contracts and get these 2 contracts up and running
2. Add a few liner code to handle the kind of data corruption that we have for document type so that in case any other contract have invalid document type we can avoid error from that part of code which is breaking right now

**Comment by mabuturabcloudelligent** [comment]
I found out that the issue may possibly be with all these contracts
863
2586
2757
2759
2761
2764
2772
2777
2779
2781
2797
3500
4823
4824
4825
4826
4830
4831
4832
4833
4834
4835
4836
4837
4838
4839
4840
4841
4842
4843
4844
4845
4846
4847
4848
4849
4850
4851
4852
4853
4854
4855
4856
4857
4858
4859
4860
4861
4862
4863
4864
4865
4866
4867
4868
4869
4870
4871
4872
4873
4874
4876
4877
4878
4879
4880
4881
4882
4883
4884
4885
4886
4887
4888
4889
4890
4891
4928
4929
4930
4931
4932
4933
4934
4935
4936
4937
4938
4939
4940
4941
4942
4943
4944
4945
4946
4947
4948
4949
4950
4951
4952
4953
4954
4955
4956
4957
4958
4959
4960
4961
4962
4963
4964
4965
4966
4967
4968
4969
4970
4971
4972
4975
4976
4977
4978
4979
5016
5030
5033
5045
5051
5060
5061
5062
5063
5065
5066
5069
5070
5088
5089
5091
5092
5094
5096
5097
5099
5100
5101
5104
5105
5106
5107
5108
5118
5124
5125
5134
5135
5136
5139
5140
5142
5143
5150

**Comment by mabuturabcloudelligent** [comment]
I believe the same issue is occurring with all these contracts

863,2586,2757,2759,2761,2764,2772,2777,2779,2781,2797,3500,4823,4824,4825,4826,4830,4831,4832,4833,4834,4835,4836,4837,4838,4839,4840,4841,4842,4843,4844,4845,4846,4847,4848,4849,4850,4851,4852,4853,4854,4855,4856,4857,4858,4859,4860,4861,4862,4863,4864,4865,4866,4867,4868,4869,4870,4871,4872,4873,4874,4876,4877,4878,4879,4880,4881,4882,4883,4884,4885,4886,4887,4888,4889,4890,4891,4928,4929,4930,4931,4932,4933,4934,4935,4936,4937,4938,4939,4940,4941,4942,4943,4944,4945,4946,4947,4948,4949,4950,4951,4952,4953,4954,4955,4956,4957,4958,4959,4960,4961,4962,4963,4964,4965,4966,4967,4968,4969,4970,4971,4972,4975,4976,4977,4978,4979,5016,5030,5033,5045,5051,5060,5061,5062,5063,5065,5066,5069,5070,5088,5089,5091,5092,5094,5096,5097,5099,5100,5101,5104,5105,5106,5107,5108,5118,5124,5125,5134,5135,5136,5139,5140,5142,5143,5150

**Comment by charlesyoung** [comment]
Thanks @mabuturabcloudelligent. I didn't realise that so many documents were impacted. Do all these documents relate to invalid document types? I wonder why the document types are invalid because it can only be added from a dropdown menu. 

Can I ask that you get back to us with the time and budget expectations to resolve the noted GitHub tickets and the site crashing issue we discussed on Wednesday? 

cc @SamCCSI

**Comment by SamCCSI** [comment]
Our intern reports "whoops, something went wrong" errors when trying to access the following docs, too. @charlesyoung has anyone been allocated to look into this issue? Many thanks!

https://admin.resourcecontracts.org/contract/4930

https://admin.resourcecontracts.org/contract/5016

https://admin.resourcecontracts.org/contract/5065

https://admin.resourcecontracts.org/contract/5066

https://admin.resourcecontracts.org/contract/5060

https://admin.resourcecontracts.org/contract/5061

https://admin.resourcecontracts.org/contract/5069

https://admin.resourcecontracts.org/contract/5070

https://admin.resourcecontracts.org/contract/5092

https://admin.resourcecontracts.org/contract/5091

https://admin.resourcecontracts.org/contract/5094

https://admin.resourcecontracts.org/contract/5097

https://admin.resourcecontracts.org/contract/5096

https://admin.resourcecontracts.org/contract/5099

https://admin.resourcecontracts.org/contract/5100

https://admin.resourcecontracts.org/contract/5101

https://admin.resourcecontracts.org/contract/5030

https://admin.resourcecontracts.org/contract/5134

https://admin.resourcecontracts.org/contract/5135

https://admin.resourcecontracts.org/contract/5143

https://admin.resourcecontracts.org/contract/5142

https://admin.resourcecontracts.org/contract/4972

https://admin.resourcecontracts.org/contract/4976

https://admin.resourcecontracts.org/contract/4977

https://admin.resourcecontracts.org/contract/4978

https://admin.resourcecontracts.org/contract/4932

https://admin.resourcecontracts.org/contract/4933

https://admin.resourcecontracts.org/contract/4934

https://admin.resourcecontracts.org/contract/4935

https://admin.resourcecontracts.org/contract/4938

https://admin.resourcecontracts.org/contract/4941

https://admin.resourcecontracts.org/contract/4947

https://admin.resourcecontracts.org/contract/4948 

https://admin.resourcecontracts.org/contract/4952

**Comment by charlesyoung** [comment]
@SamCCSI this is one of the tasks we have to address but first need to sort out the development contract, etc.

**Comment by SamCCSI** [comment]
Thanks Charles.

The reverse also seems to be happening: This
<https://admin.resourcecontracts.org/contract/4806> doc (among many others)
is accessible on the backend, but not on the frontend.

**Comment by charlesyoung** [comment]
This is strange. 

When I unpublish the PDF text it works and when I published the PDF text again it doesn't. 

cc @mabuturabcloudelligent

**Comment by charlesyoung** [comment]
@SamCCSI please confirm that this is now working on the prod site.

**Comment by SamCCSI** [comment]
Confirmed
