### ISSUE TITLE
Create "company group" and "concession" look up table

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#142]
As an uploader I would like to be able to look up the concession/license name from a look up table. 

For example: IF contract is=Afghanistan, pull concession list from Afghanistan + an optional field for creating a new concession.

![sanduqli block](https://cloud.githubusercontent.com/assets/1101585/8699093/edbac834-2ad0-11e5-82d6-b53e7ba156c9.PNG)

This implementation will need to share practise with RP.org.

cc @practicalparticipation @byndcivilization

**Comment by timgdavies** [comment]
To fully co-ordinate data between RC.org and RP.org it might make sense to have some modular component providing these lists - and then distributing the data to both services.

Alternatively, providing this could be a future feature for RP.org. 

We should be able to cover oil concessions fairly easily with Open Oil data, but for other concessions it might be a more patchy process initially.

**Comment by anderspeders** [comment]
As a temporary solution this will be implemented as: 
code list of company groups + "other" option as string response

cc fyi @timgdavies - let me know if that is not ideal

**Comment by anderspeders** [comment]
Company group has now been completed as look up table. 

For the [license_name] we should in similar ways create a lookup table against the Open Oil Concession API. Documentation here: http://openoil.net/openoil-api/

**Comment by charlesyoung** [comment]
@anderspeders is this still required?
