### ISSUE TITLE
How to tell user that contract is not signed?

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#143]
Some contract PDFs are missing pages or annexes. Other contracts are word documents and do not have signatures. 

As a user, I need to be informed when a contract is incomplete so that I do not base my entire analysis / research on this incomplete contract / annotations. At the same time, we do not want the notification to be an eyesore or too prominent as to take away from the value of having the contract there.

@anderspeders or others, would you have any ideas?

**Comment by anderspeders** [comment]
"Some contract PDFs are missing pages or annexes. Other contracts are word documents and do not have signatures."

I think the easiest step here would be to provide an annotation stating that it is incomplete. 

"As a user, I need to be informed when a contract is incomplete so that I do not base my entire analysis / research on this incomplete contract / annotations. At the same time, we do not want the notification to be an eyesore or too prominent as to take away from the value of having the contract there."

I do not have a good answer here. I think that we want to have documents which are related (eg. contract plus amendment) to appear in a way so that the user does not miss that the documents are related. I believe that YI will be working on this later in the process.

**Comment by SamCCSI** [comment]
Hi Anders,

I think the discussion of related contracts is separate from how we deal
with incomplete contracts.

Would you, Chris and the folks at YI be able to see if there is some way of
notifying the user when a contract is incomplete?

On Thu, Jul 16, 2015 at 3:13 PM, Anders <notifications@github.com> wrote:

> "Some contract PDFs are missing pages or annexes. Other contracts are word
> documents and do not have signatures."
>
> I think the easiest step here would be to provide an annotation stating
> that it is incomplete.
>
> "As a user, I need to be informed when a contract is incomplete so that I
> do not base my entire analysis / research on this incomplete contract /
> annotations. At the same time, we do not want the notification to be an
> eyesore or too prominent as to take away from the value of having the
> contract there."
>
> I do not have a good answer here. I think that we want to have documents
> which are related (eg. contract plus amendment) to appear in a way so that
> the user does not miss that the documents are related. I believe that YI
> will be working on this later in the process.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/143#issuecomment-122054626>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by anderspeders** [comment]
I think my sugestion would be to add an attribute section to the metadata, which could include for example: 

Pages are missing from contract: Check box
Comment: 

Contract is not signed by the parties: Check box
Comment: 

In this way we could flag the issue to the user with a red / orange or similar note when users look up the contract. 

What do you think @SamCCSI ?

**Comment by SamCCSI** [comment]
Sounds great, Anders!

Could the metadata also translate into some form of visual alert, when
pages are missing?

Also, when the contract is complete, is there  a way to indicate
(internally) that it is complete, but not notify the user about this? Will
be distracting if it says "Contract is complete" or "Contract is not
missing any pages".

Thanks again.

On Fri, Jul 24, 2015 at 3:52 PM, Anders <notifications@github.com> wrote:

> I think my sugestion would be to add an attribute section to the metadata,
> which could include for example:
>
> Pages are missing from contract: Check box
> Comment:
>
> Contract is not signed by the parties: Check box
> Comment:
>
> In this way we could flag the issue to the user with a red / orange or
> similar note when users look up the contract.
>
> What do you think @SamCCSI <https://github.com/SamCCSI> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/143#issuecomment-124683940>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by anderspeders** [comment]
In principle we can add all the features we will to the metadata form. The challenge is to monitor the researchers / uploaders to ensure compliance with the metadata standard and form. 

I would there fore suggest that we assume that the contract is complete unless specifically noted. 

Regarding "signed contract": 
Could this be a confusing field to the researchers uploading SEC contracts which are signed but do not appear signed (as it is electronic copies)?

**Comment by SamCCSI** [comment]
Thanks, Anders. My responses are below inline.

I would there fore suggest that we assume that the contract is complete
unless specifically noted.

*-- Ok, but can we have a metadata field that we can tick for incomplete
contracts?*

*-- Also, how will this be displayed to users? It will need to be more than
just a metadata field, to notify the user of this. Otherwise the user might
miss it.*


Regarding "signed contract":
Could this be a confusing field to the researchers uploading SEC contracts
which are signed but do not appear signed (as it is electronic copies)?

*-- I don't think it is confusing -- if the only version we have is not
signed, then it should be displayed as such. It does not matter that there
might be a signed copy in existence in the government's possession but not
publicly available, as there is no telling that our unsigned version, and
the final signed version are exactly the same.*

On Fri, Aug 7, 2015 at 11:11 AM, Anders <notifications@github.com> wrote:

> In principle we can add all the features we will to the metadata form. The
> challenge is to monitor the researchers / uploaders to ensure compliance
> with the metadata standard and form.
>
> I would there fore suggest that we assume that the contract is complete
> unless specifically noted.
>
> Regarding "signed contract":
> Could this be a confusing field to the researchers uploading SEC contracts
> which are signed but do not appear signed (as it is electronic copies)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/143#issuecomment-128726262>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by anderspeders** [comment]
@jpmckinney Any suggestions here for what could be recommended?

**Comment by jpmckinney** [comment]
I think it makes sense to add a checkbox for incompleteness (default unchecked, so default complete).

For display, it depends how common incomplete contracts are. If they are rare, then a dismissible modal alert may be an option. Otherwise, perhaps a designer can think of a visible but non-obtrusive icon; for example, a dog ear on the rendered contract in a bright color is visible and unobtrusive, whereas a modal alert is visible but obtrusive.

**Comment by SamCCSI** [comment]
Thanks @jpmckinney 

As a stop gap measure we are currently using the "Note" feature to alert users to this issue, where relevant:

![image](https://cloud.githubusercontent.com/assets/12913915/11785885/bcb01c00-a251-11e5-98b2-17ddc572f4ef.png)

CCSI's preference would be for a simple (and permanent / stable) text notification that contract is incomplete or has been amended. A dismissible notification would need to appear each time the user went back to the contract page anyway, and so might become fatiguing for the user. An icon might not be immediately recognizable to most first time users, and so might not be the most effective way of communicating this.

**Comment by jpmckinney** [comment]
Sure, I'm not responsible for UI after all, so whatever makes sense :)

**Comment by SamCCSI** [comment]
Also referencing https://github.com/NRGI/resourcecontracts.org/issues/723 for completeness

**Comment by jpmckinney** [comment]
And seems to be duplicate with #715?

**Comment by jpmckinney** [comment]
Closing in favor of #715, which suggests having two checkboxes (pages missing, annexes missing) instead of one (stuff missing).

**Comment by jpmckinney** [comment]
The original issue not only describe incomplete contracts, but also contracts with no visible signatures. @SamCCSI Can you confirm that it's important to flag contracts as not having any visible signatures? @anderspeders already mentioned some issues with this feature, e.g. what if there are no visible signatures, but the editor knows that the document is in fact signed (but that the signatures simply don't appear on the available document)?

**Comment by SamCCSI** [comment]
Thanks @jpmckinney 

It could be important to tell the user if the copy of the contract being housed on RC does not contain signatures -- eg. if it is a word document version. This is because we don't have any proof that we can provide to the user to assure them that this is the form the agreement signed. I think that would be the case even if we were certain that the agreement between the parties was reached.

1. We are in favor of having a checkbox for whether the contract has been signed or not. (Default should be 'yes').
2. The wording that should appear to notify the user if the contract has not been signed should be "This document does not contain signatures." Or possibly "This document is not a signed copy".

We should avoid the wording "This contract is not signed," as this might imply that the agreement itself was not concluded, rather than that this version of the doc doesn't contain signatures. 

cc @KaitlinCCSI

**Comment by jpmckinney** [comment]
Thanks - renaming issue to be about signatures.

**Comment by anjesh** [comment]
We are yet to cover this checkbox

>We are in favor of having a checkbox for whether the contract has been signed or not. (Default should be 'yes').

Please confirm if we need this checkbox.

**Comment by SamCCSI** [comment]
Yes we do. Thanks @anjesh

**Comment by hello-deepak** [comment]
@SamCCSI 

Need feedback .

When contract is not signed, we can display in contract view page as : 

![notsigned](https://cloud.githubusercontent.com/assets/7577697/18950959/456e1872-8662-11e6-94f1-81601a4f5ce2.png)

Should the contract not signed also be reflected in contract summary page ?

**Comment by KaitlinCCSI** [comment]
I think so -- same wording on summary page.

**Comment by manishgs** [comment]
Added on contract summary page too .
![screenshot-www resourcecontracts org 2016-10-03 15-04-02](https://cloud.githubusercontent.com/assets/3942999/19033418/fe7267f6-897d-11e6-8d15-0a336c472b59.png)
 Please review on live site.
