### ISSUE TITLE
Document URL path 

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1432]
@sriza @rumus007 

We had this problem before but I cannot remember how it was fixed. I want to run a backend xls import and have captured the below URL in the URL column. The URL however doesn't point directly to the PDF but prompts to save the document. Can I add anything to the URL to point directly to the PDF and not ask for it to be saved so that the backend import will work? 

https://dataogauthority.blob.core.windows.net/external/Redacted_Licence_Docs/P2503_Licence_Redacted.pdf

cc @man-git007

**Comment by sriza** [comment]
@charlesyoung 
The issue with UK docs not being seen on the map has been solved and is currently deployed to the staging site. Could you please have a look and let us know if the changes can be deployed to the production server?

Thank you

cc @rumus007

**Comment by charlesyoung** [comment]
Looks good, please deploy to the Prod site. Thanks

**Comment by sriza** [comment]
@charlesyoung 
The changes are now deployed to the production site. Please verify.

cc @rumus007

**Comment by charlesyoung** [comment]
Many thanks.
