### ISSUE TITLE
Admin profile page

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1437]
There seems to be a problem with the admin profile page. Please see the attached error. Can you please investigate? 

cc @man-git007 @sweta-shrestha

[Profile page.docx](https://github.com/NRGI/resourcecontracts.org/files/7561943/Profile.page.docx)

**Comment by charlesyoung** [comment]
@man-git007 @sweta-shrestha will you be able to look at this issue?

**Comment by charlesyoung** [comment]
@man-git007 Can you look at this issue please.

**Comment by charlesyoung** [comment]
@man-git007 Can you look at this issue, please. We are constantly getting this error. Thanks

**Comment by charlesyoung** [comment]
@man-git007 can I please ask that you also look at the below issues that relate to the admin site. 

- I get an error when trying to access https://admin.resourcecontracts.org/contract/5104
- I get the attached annotations error

[Annotations.docx](https://github.com/NRGI/resourcecontracts.org/files/7647640/Annotations.docx)

**Comment by man-git007** [comment]
Sure Charles we will look into it on Monday. It might take an hour.

**Comment by sriza** [comment]
@charlesyoung 
The issue has been solved and deployed to the staging server. Please have a look and verify.

Thank you

cc @man-git007

**Comment by charlesyoung** [comment]
Thanks. How do I test this?

**Comment by sriza** [comment]
Please try editing your profile at staging site.

**Comment by man-git007** [comment]
@charlesyoung Should we send this to live site?

cc @sriza

**Comment by charlesyoung** [comment]
Yes please

**Comment by sriza** [comment]
@charlesyoung 
The changes related to this issue have been deployed to the live site.

Thank you

cc @man-git007

**Comment by sriza** [comment]
@charlesyoung 
Are the changes related to this issue tested on the production site? Please let us know if this issue can be closed.

cc @man-git007

**Comment by charlesyoung** [comment]
Please move to Prod.

**Comment by sriza** [comment]
@charlesyoung 
The changes related to this issue have already been moved to the production site. Please verify the changes.

Thank you

cc @man-git007
