### ISSUE TITLE
Enable multiple license/concessions to each contract

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#144]
For the metadata field, license/concession we will need to enable multiple license names, as we are doing for companies. 

For example: 
For the contract below, there are actually three licenses/concessions attached namely: 
1) Manga
2) Chari-Ouest 
3) BDS 2008

![three licenses - one contract](https://cloud.githubusercontent.com/assets/1101585/8734661/7271b3d6-2bd9-11e5-8fd3-475dbfb5d7a0.PNG)

**Comment by anjesh** [comment]
So you mean there needs to be "add more" feature for Concession/Licence Name and Concesssion/License Identifier. Does this suffice?

![image](https://cloud.githubusercontent.com/assets/120488/8740943/8b3d9b94-2c71-11e5-9872-349efe024e03.png)

**Comment by anderspeders** [comment]
Looks good!

**Comment by anjesh** [comment]
Fixed in the admin interface, API, subsite.
