### ISSUE TITLE
Ui / front end: Facet and filtering example

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#145]
User story: As a CSO I would like to easily filter between contracts where tagssuch as "royalty" or "environmental protection clause" appear. 

Example of facet / filtering: 
This project from OCCRP looks like a nice way of solving this challenge: https://www.occrp.org/corruptistan/uzbekistan/gulnara_karimova/the-prodigal-daughter/docs.php

**Comment by anderspeders** [comment]
As discussed yesterday, here is an example: 
http://facts.contentmine.org/

Each search term will appear in a box with a sentence on each side of the term.

**Comment by anjesh** [comment]
We seem to have covered the above use case in the current search functionality.
