### ISSUE TITLE
Add *operator* as bolean value to company list

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#148]
![image](https://cloud.githubusercontent.com/assets/1101585/8883415/c647cbfa-321c-11e5-8644-13791a989a9f.png)

For the metadata company section we will need to add for each company a check box for: **Is operator**

For example in this case Dragon Oil is appointed as the operator.

**Comment by anderspeders** [comment]
For example this addition: 

![operator metadata rc - add](https://cloud.githubusercontent.com/assets/1101585/8883549/82af6d84-321d-11e5-80dd-faa02f569776.JPG)

**Comment by anjesh** [comment]
The field label: Is Operator? [checkbox] 
Help text besides checkbox: Please check the box if the contractor is operator.

**Comment by anjesh** [comment]
"Is Operator?" field is added.
