### ISSUE TITLE
Basic front end for light editing and correction of ascii outbout for both

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#15]
Should provide for side by side comparison with the original PDF document.	This will allow annotators to make minor changes for errors caught in annotation process.

**Comment by anderspeders** [comment]
Confirmed on track. Will be the same interface as for annotations.

**Comment by anjesh** [comment]
Editing and annotation can't occur at the same time. See #8

**Comment by anderspeders** [comment]
We will have user testing and iterate during sprint 2.
