### ISSUE TITLE
Enable annotation in scanned pdf

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#150]
In case of the issues with MTurk, there should also be possibility to annotate directly in the pdf, as we don't have pdf-text from the poorly scanned document. Current annotatorjs doesn't work in pdf and need to explore http://annotorious.github.io/ to make it work for pdf. Also it needs to be integrated with existing annotation process.

**Comment by anderspeders** [comment]
This sprint will include a test transfer form the old database to see how annotations match up.

Note that not all contracts have annotations.

**Comment by anjesh** [comment]
@anderspeders it appears that current https://github.com/annotorious/annotorious/ doesn't work with annotatorjs 1.2.9, which we are using (which supports tags and categories) as mentioned [here](https://github.com/annotorious/annotorious/issues/103#issue-32495045). This would require hack in the existing annotorious plugin to make it work for annotatorjs and might affect the timeline i had assumed earlier. Will keep you updated.

**Comment by anjesh** [comment]
This is working now but there still might be few issues here and there.

**Comment by anjesh** [comment]
Closing this issue, will create new one if there are issues.
