### ISSUE TITLE
Review of upload workflow from Open Oil

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#151]

**Comment by anderspeders** [comment]
1) Generate a spreadsheet: http://repository.openoil.net/w/index.php?title=Special:Ask&offset=0&limit=500&q=%5B%5BCategory%3AContract%5D%5D&p=format%3Dtemplate%2Fmainlabel%3D-2D%2Fsearchlabel%3Dmore-20contracts...%2Ftemplate%3DCountryBody2%2Fintrotemplate%3DCountryHeader2%2Foutrotemplate%3DFooter&po=%3FContract%0A%3FContractType%0A%3FContractor%0A%3FHostGovernmentContract%0A%3FLocalStoreURLPlain%0A

2) Generate upload workflow - maybe with suggestions for autogenerated metadata

3) A user check for duplicates

**Comment by anjesh** [comment]
The following flow is suggested.

The researcher uploads the csv file as per given template. The template should follow [this template](http://repository.openoil.net/w/index.php?title=Special:Ask&offset=0&limit=500&q=%5B%5BCategory%3AContract%5D%5D&p=format%3Dtemplate%2Fmainlabel%3D-2D%2Fsearchlabel%3Dmore-20contracts...%2Ftemplate%3DCountryBody2%2Fintrotemplate%3DCountryHeader2%2Foutrotemplate%3DFooter&po=%3FContract%0A%3FContractType%0A%3FContractor%0A%3FHostGovernmentContract%0A%3FLocalStoreURLPlain%0A). Currently the list doesn't contain all the metadata present in the [contract file](http://repository.openoil.net/wiki/Afghanistan_AmuDarya_dd20111211_PSC). So we need to see how to get those fields in the csv. 

![image](https://cloud.githubusercontent.com/assets/120488/8930276/53f7bb4a-354c-11e5-9d6e-a9b6a30c0b56.png)


![image](https://cloud.githubusercontent.com/assets/120488/8930278/55cfa02c-354c-11e5-976c-c47f78e0e067.png)


![image](https://cloud.githubusercontent.com/assets/120488/8930280/59c4137a-354c-11e5-86b5-83566a664fce.png)

cc @anderspeders

**Comment by anderspeders** [comment]
Looks good. However can we ensure that metadata is suggested added by this matching?

*OpenOil* --> **RC**
- Jurisdiction --> Country
- Contract area --> Concession/License name
- Contractor --> Company (note that this is comma-separated, thus often more than one company will appear. Please make sure that all company entries are added)
- Signed --> Signature date
- Language --> Language
- Disclosure mode --> Disclosure mode

See example: http://repository.openoil.net/wiki/Afghanistan_AmuDarya_dd20111211_PSC

**Comment by anderspeders** [comment]
Just tested this. It appears that **Jurisdiction --> Country** is not working properly as country is not migrated.

**Comment by anjesh** [comment]
All the imported contracts should have "Hydrocarbon" as resource when importing the oil contracts.

**Comment by anjesh** [comment]
I see that Country field from csv goes to Country under Metadata. Do you mean that it should also go to Jurisdiction under Company? 

Also we could add "Resource" as one of the columns in csv rather than directly injecting "Hydrocarbon" for oil contracts.

**Comment by anderspeders** [comment]
This is to confirm: 
- Resource: Hydrocarbon should be added automatically

@anjesh: You write: "I see that Country field from csv goes to Country under Metadata."
I have now checked this with Albania, Bolivia and Benin. It is *not correct*. 

Please ensure that thedata field [country] in the upload spreadsheet should be added as [country] in the metadata for the contract.

**Comment by anjesh** [comment]
@anderspeders can you share the csv that you used to import oil import contracts that caused issues. It should have been fixed. We tested at our end and working fine.

**Comment by anjesh** [comment]
This can be closed as we will be replacing the open oil format with the generic one. https://github.com/NRGI/resourcecontracts.org/issues/339
