### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#153]
The API should be properly documented: 
https://docs.google.com/document/d/1lawSuSak4sAHitaCtbPs3nhNEM5aR20tdMMj_c_JKtk/edit#heading=h.phyu2pezfgcu

**Comment by anjesh** [comment]
Tested http://www.documentcloud.org/documents/457904-drc-highwind.html in the demo and the annotations positions are close. For page 4 for http://resourcecontracts-demo.elasticbeanstalk.com/contract/49/pages?action=annotate 
![image](https://cloud.githubusercontent.com/assets/120488/9171736/bc1aeec2-3f8d-11e5-823f-f510461f7799.png)

Still need to do number of things
- Need to do the mapping for the old annotation title e.g `Nom de la société locale//Local company name` to annotation category
- Number of mistakes in the annotation title, need to map those mistakes into appropriate categories

This [data spreadsheet](https://docs.google.com/spreadsheets/d/1K0wlloEAPFncrNA_mwBjqvW81A5xRpFlK0qlv-j5ZYo/edit#gid=841744725) shows the data that could be mapped to the metadata in the new system. See the spellings.

This [sheet](https://docs.google.com/spreadsheets/d/1K0wlloEAPFncrNA_mwBjqvW81A5xRpFlK0qlv-j5ZYo/edit#gid=1612543715) shows the annotations categories that need to be fixed. Lots of variations in the labels. Just wondering if all these could be mapped to the existing [annotation categories](https://docs.google.com/spreadsheets/d/12UCQA422r5Dg3wruUmYHL2SCLdDrlesCPcm2tHD8Yu4/edit#gid=242312400).

**Comment by anjesh** [comment]
Documented here https://github.com/NRGI/resourcecontracts.org/wiki/API and the API bulk download issue #175  also fixed and documented.
