### ISSUE TITLE
Set up Mech Turk key 

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#154]

**Comment by anderspeders** [comment]
Hi @anjesh, Let's clarify the blockers here as soon as possible.

**Comment by anjesh** [comment]
We just need AWS key and access-key that is associated with Mturk to do the real Mturk testing. 
https://github.com/NRGI/resourcecontracts.org/blob/master/.env.example#L30-L31

**Comment by anjesh** [comment]
Setup the key in the stage and the HITs are created in mturk now.
