### ISSUE TITLE
Create and share data model / schema 

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#156]
Share schema that documents how tables are currently connected. 

The data model will need to be reviewed and approved before we run the migration of documents. 

cc @byndcivilization

**Comment by byndcivilization** [comment]
As simple as just creating a visual schema diagram with a plugin on top.

These three are free and quite good:

pgDesigner: http://pgdesigner.sourceforge.net/en/index.html
SQL PowerArchitect: http://www.sqlpower.ca/page/architect (download without registration from: http://code.google.com/p/power-architect/)
OpenModelSphere http://www.modelsphere.org

**Comment by byndcivilization** [comment]
you start to answer some of this in #24 btw

**Comment by anjesh** [comment]
The schema is now available in wiki https://github.com/NRGI/resourcecontracts.org/wiki/Schema
