### ISSUE TITLE
Improved page navigation

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#159]
![page navigation](https://cloud.githubusercontent.com/assets/1101585/8958394/a252fe04-35d2-11e5-94e4-dc6163ad5faf.JPG)

We need a better way for navigation across large size contracts. 

For example for the contract above:
In order to get to page 47 I will need to click 20 times with the mouse. There must be a better way for page by page navitation when I know I need to get to pay - eg. 47.

**Comment by byndcivilization** [comment]
Have we thought anymore about implanting scrolling? #84 and #115. Wouldn't this just be displaying the text content in bulk. Since these are discrete elements in the db, you could make an ajax call to load on demand.

**Comment by anderspeders** [comment]
@byndcivilization We have a ticket for this here #84 and should prioritize it among added features for next sprint  

@anjesh Let's discuss if this can make it into sprint 6.

**Comment by anjesh** [comment]
page scrolling out in place #84
