### ISSUE TITLE
Displaying one language only for metadata / annotations

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#160]
In the current platform, the annotation categories appear in French, then in English. 

![image](https://cloud.githubusercontent.com/assets/12913915/8986917/6449db84-36ac-11e5-946b-695488afb7b6.png)

[See annotation categories on Right hand side in dark blue]

This is confusing for users who only speak English (or French).

Is there a way to only have the language that a user selects appear on the site - eg FRE, ENG, ESP - rather than both?

**Comment by anjesh** [comment]
Will be taken care of here https://github.com/NRGI/resourcecontracts.org/issues/47
