### ISSUE TITLE
Adjust UI for "Add another license/concession"

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#162]
For purpose of UI consitency we should provide the button for "Add another license/concession" in the same design as the one we do for "Add another company".

![add concession license2](https://cloud.githubusercontent.com/assets/1101585/9005984/a56b8d34-3750-11e5-89fd-d02f1f3cbe63.JPG)

**Comment by anjesh** [comment]
Fixed.
