### ISSUE TITLE
Scraping text from PDF - but still displays PDF area as empty 

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#163]
![page blackout - on pdf side](https://cloud.githubusercontent.com/assets/1101585/9006081/7697123e-3751-11e5-85bd-d02c73760672.JPG)

I have now encountered this in two different contracts. In both cases the blackout is just for a couple of pages. 

cc @byndcivilization

**Comment by anjesh** [comment]
That particular pdf has some issue when we tried to split into multiple pages using pdftk. Trying to work around this issue. 
```
Error: Unexpected Exception in open_reader()
Unhandled Java Exception in main():
```

**Comment by anderspeders** [comment]
Thanks @anjesh, 

Given that we found it in two separete issues. Can the solution be scaled and adopted. What is the work required for fixing this?

**Comment by anjesh** [comment]
We have updated the pdf-processor for fallback processing in case of such issues with the pdftk. Have re-run the processing for that particular contract and it's working now. Closing this for now.
