### ISSUE TITLE
commenting on metadata

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#165]
As a reviewer, i need to comment on individual metadata categories.

I also need to be able to do this without clicking "complete" on metadata, which right now seems to be the only way to add comments.

(No worries if this is already in the pipeline - I'm just relaying feedback from reviewing real metadata entries)

**Comment by anderspeders** [comment]
Thanks Sam, 

We have added some commenting to the pipeline, so I hope to have something to share there relatively soon.

**Comment by anjesh** [comment]
Duplicate of #146 
Further discussion there.
