### ISSUE TITLE
Adjust opencorporates id

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#167]
Currently the matadataform has "https://opencorporates.com/companies" pre-inserted. 

When contributors enters this field - this appears to be non-intuitive. 

So many editions look like this: "https://opencorporates.com/companies/https://opencorporates.com/companies/gb/02160234" 

Thus: Please remove the pre-written: https://opencorporates.com/companies from the metadataform

Change the name of the field from: **Open Corporate Id** to **OpenCorporates link**

**Comment by anjesh** [comment]
Fixed.
