### ISSUE TITLE
Contract query tool for oil and mining contracts in SEC Edgar

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#168]
We assume that a significant amont of mining and oil contracts are left within SEC Edgar filings as already demonstrated in repository.openoil.net. 

A basic workflow could be:
1) Uploader can access a feed of SEC filings "flagged" as potential contracts
2) Uploader can decide Yes/No if this si a contract which should be loaded
3) Uploader can add to basic upload workflow on RC.org 
4) Uploader can refine the amount of pages wihtin the SEC filing which constitues the contract (eg. often the contract is buried within the last 100 pages of a 1000 page filing). 

Source for scraping repo: 
https://github.com/pudo/edgar-oil-contracts

@byndcivilization Any thoughts?

**Comment by charlesyoung** [comment]
@anderspeders is this still required?
