### ISSUE TITLE
Integration with Overview to create: fiscalterms.resourcecontracts.org

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#169]
Based on a list of fiscal terms *and* using the OverviewProject load API, we will generate a tool for exploring fiscal terms within the contracts. 

Links: 
https://blog.overviewdocs.com/2013/12/20/advanced-search-quoted-phrases-boolean-operators-fuzzy-matching-and-more/

**Comment by hello-deepak** [comment]
Related to 
https://github.com/NRGI/resourcecontracts.org/issues/892
