### ISSUE TITLE
Setup and implement index in Elasticsearch (ES) for Contract Metadata

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#17]
Should make basic metadata available and provide documentation. Oauth for POST and PUT functionality. GET functionallity for document data should be fully exposed.

**Comment by anjesh** [comment]
This will be implemented in Elasticsearch and will cover the aspects of full text search, annotation search and other APIs needed by the websitees.

**Comment by anjesh** [comment]
The elasticsearch (ES) will be setup and indexing will be implemented for the contracts metadata. The indexing will occur when the contract metadata gets published as described in the workflow #75 

ES could reside in different server later for performance. 

The json schema for the ES needs to be defined first the the contracts metadata. 

There will be two independent processes for getting the published contracts metadata to the ES. 
* Bulk import - one time or when the ES index gets crashed or we need to flush it
* Real-time import - when the contract gets published after #75 

Bulk import
There will be a script that pulls all the published contracts metadata from the database, prepares the desired document object (as per json schema) and indexes to the ES.

Real-time import
When the contract gets published, the system will prepare the document json object of the published contract and calls the service to index that particular contract to ES.

The service to index the document to ES will handle create or update. It will check whether the contract metadata is to be updated or created and takes action accordingly.
