### ISSUE TITLE
Contracts Quality Monitoring for admin/researchers

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#170]
@anderspeders  has mentioned about the need of the interface where the admin/researcher should be able to see which contracts are completed and which are missing the key metadata. The idea is to list all the metadata and annotation-categories and the contracts which are missing those. 

This could be the part of the dashboard or due to long list, i am thinking of this as a separate page with the menu "Contract Quality issues" 

![image](https://cloud.githubusercontent.com/assets/120488/9061077/f00470f0-3ad8-11e5-81a5-3f67568a420b.png)

**Comment by anderspeders** [comment]
Think this looks good. 
Feel free to implement - or await for the next sprint.

**Comment by anderspeders** [comment]
Hi @anjesh, apologies for the confusion, but I would ask that we push this forward to blue sky, until we have the core pieces fixed.

**Comment by anjesh** [comment]
Completed.
