### ISSUE TITLE
Add opencontracting identifier

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#173]
Implement a randomised Open Contracting ID generator for all contracts where a government identifier is available.

**Comment by anderspeders** [comment]
We have now been issued a publishing ID from Open Contracting: ocds-591adf

Next up is to set up a random generator which is in compliance with the schema outlined here:
http://ocds.open-contracting.org/standard/r/1__0__RC/en/key_concepts/identifiers/

Construction

An OCID is made up of four parts. The first three can generally be set as constant values in most systems:

A prefix agency (characters 1 - 4) - currently only ‘ocds’ (Open Contracting Data Standard)
A - separator
A registered prefix (charachters 6 - 11) - a random alphanumeric string given to publishers
A publisher namespace (charachters 12 - 13) - for allow publishers to maintain separate series of local identifiers.
A ‘-’ separator
An internal identifier (charachters 15 and above) - drawn from publishers existing systems
This allows publishers to use an internal identifier from within their own systems, and simple to prepend the prefix and namespace to this when publishing data, making their local identifier into a globally unique identifier.

The OCID is case sensitive.

Examples

The following are examples of valid OCIDs:

ocds-a2ef3d01-1594121

ocds-df4534dg-eu-192301-2009

**Comment by anderspeders** [comment]
@anderspeders to provide a few examples.

**Comment by anjesh** [comment]
Examples of OCID for the contracts that is present in our RC system with link to that contracts.

**Comment by anderspeders** [comment]
I see 2 or 3 ways we can implement the OCDS id process for RC/OLC: 

1) The simple solution: Publishing ID + randomized number

ocds-591adf-[randomized id] 

Do we have an opinion on the number of carachters needed?

2) More advanced option (not sure if this is needed)
OCDS does allow us to insert a local seperator for us as publisher. This could for example be by inserting a country code or a seperator between RC and OLC, for example:

ocds-591adf-[rc or ol]-[randomized id] 
ocds-591adf-[country code]-[randomized id] 

My opinion would be that we stick with the basic option 1)

Any thoughts @byndcivilization?

**Comment by anderspeders** [comment]
Here is the final recommendation @anjesh: 

We will go with option 1)

ocds-591adf-[randomized id]

The randomised id (created automaticall in the db) will be comprised of the following:
**[iso-2][ten random digits][RC or OL]** 

These are examples of our local generated ID: 
UK1285730573RC
GH4398562949OL

To summarize a full OCID for the RC or OLC db would be:
ocds-591adf-UK1285730573RC
ocds-591adf-GH4398562949OL

Can you quickly review and confirm: @byndcivilization 

FYI @bjwebb67 @practicalparticipation

**Comment by timgdavies** [comment]
This looks good

**Comment by anderspeders** [comment]
@anjesh: I suggest that we postpone this to after sprint 9 to allow us to focus on annotations and UI in the current sprint.

**Comment by anjesh** [comment]
Completed in the sprint 9.
