### ISSUE TITLE
Elasticsearch API exposure

### ISSUE THREAD

**Issue by byndcivilization** [NRGI/resourcecontracts.org#174]
There are secondary use cases for the underlying RC.org data that will need access both to the RC.org database but also to elasticsearch. The most prominent user story is the application of NLP methods to do text mining.

**Comment by byndcivilization** [comment]
Sorry missed the api docs. Good start but would be good to have access to more of elastic search api at least for experimentation with NLP.

**Comment by anjesh** [comment]
Do we still want this? Please open and lets discuss if the current way of accessing ES needs improvement.
