### ISSUE TITLE
API bulk download

### ISSUE THREAD

**Issue by byndcivilization** [NRGI/resourcecontracts.org#175]
From what I can see right now, API responses are limited to single records. For some (many?) calls we will need bulk options, both as a dump and as a range. For instance with text I need the ability to ask for an object array of all the pages in a single contract so I can concatinate text value into a single text element for NLP.

**Comment by anjesh** [comment]
Makes sense.  I have updated the API definition and will be fixing the APIs accordingly. 
https://github.com/NRGI/resourcecontracts.org/wiki/Get-Contract-Text
https://github.com/NRGI/resourcecontracts.org/wiki/Get-Contract-Annotations

**Comment by anderspeders** [comment]
Thanks @anjesh, and really good to have the API documented!

**Comment by anjesh** [comment]
Fixed the APIs and documented.
