### ISSUE TITLE
Deploy google analytics at separate account for RC and OLC

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#176]
- Both OLC and RC will be using Google Analytics

- We should explore if annotator.js will allow detailed tracking

**Comment by anjesh** [comment]
Lets quickly implement analytics for both olc and rc.

**Comment by anderspeders** [comment]
Was this implemented? If so who has the google analytics credentials?

**Comment by anjesh** [comment]
No not yet. I might have accidentally closed this. We will give access to you once the account is setup from the analytics interface.

**Comment by anjesh** [comment]
This is in place. Will send you the invite to analytics dashboard.
