### ISSUE TITLE
Field renamining: "Parent company" --> "Corporate group"

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#179]
For now we will go with a basic string list. Later we will begin to apply a more elaborate picklist.

**Comment by anjesh** [comment]
Waiting for list.

**Comment by anderspeders** [comment]
This will need to be implemented with an API call to OpenCorporates. 

1) Call Open Corporates APi **GET corporate_groupings/:name**

https://api.opencorporates.com/documentation/API-Reference

2) Design autocomplete process

For example: As a user I type out: "Tull" and get the following suggestion: https://opencorporates.com/corporate_groupings/tullow+oil 

@byndcivilization Correct approach?

____

Description: This returns information on a given CorporateGrouping. A CorporateGrouping is a user-curated collection of companies that belong to some human-understand concept of a corporation (which maps to the Wikipedia article about that corporation). See (https://blog.opencorporates.com/2011/06/01/introducing-corporategroupings-where-fuzzy-concepts-meet-legal-entities/). The name of the CorporateGrouping is case-insensitive Included in the response will be core information for the CorporateGrouping (:name, :wikipedia_url, :companies_count), together an array of membership of the CorporateGrouping (each membership will contain a company and an OpenCorporates Source Object), and an array of the users that are curating this CorporateGrouping

**Comment by anjesh** [comment]
We scrapped all the corporate-groups and are now auto-populated in the admin interface. Also their API sends only 100 items per call, and need to make 8 calls to get their close-to 800 group names. 
Their APIs get blocked after number of calls made to the API. We will ensure that they are updated on a regular basis, maybe in every few days. These list can be seen in this [spreadsheet](https://docs.google.com/spreadsheets/d/1pNihdxoWJEFU7EG0Yue3Hd266nCUXG96jVNxYMLzDmY/edit#gid=0)

If the group you are looking for is not available in the list, you may type your own group name.
![image](https://cloud.githubusercontent.com/assets/120488/9809739/aabb4f12-588a-11e5-87da-906a9cb93e1e.png)
