### ISSUE TITLE
Add OCR-evaluation status to internal dashboard

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#180]
Add the evaluation status from the OCR-process to the internal dashboard: 
- Accepted
- Needs editing
- Rejected - needs transcription

![add text status](https://cloud.githubusercontent.com/assets/1101585/9152588/a06d9e22-3dfd-11e5-9c0c-f39fa898b956.JPG)

**Comment by anderspeders** [comment]
Unless this is complate - I suggest that we postpone this until the next sprint.

**Comment by anjesh** [comment]
duplicate of #212
