### ISSUE TITLE
Update the MTurk HIT page with proper information including language in the title

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#182]
It needs to be clear when added to meh turk what language the specific page is written in.

**Comment by anjesh** [comment]
Use the following structure while creating HIT in Mturk

![image](https://cloud.githubusercontent.com/assets/120488/9189476/94813d78-4008-11e5-98df-c7abf0507590.png)

Title: Transcription of Contract '<Contract Title - limit the length of title to 100 char if longer>' - Pg: <page number>, Lang: <lang>
Description: Transcription of the scanned contract pdf
Keywords: transcription, pdf, <language>
Time: 2 weeks
Cost: 50 cents

--

Description in the HIT page - shown below (remove MTurk and put the following text)
"In this HIT, you are to transcribe the text as shown in the scanned pdf in the right. It is possible that your HIT will be rejected if we find that there are number of spelling mistakes or missing text in the transcribed text.

You must accept HIT before you can submit the result. 

![image](https://cloud.githubusercontent.com/assets/120488/9189459/560179d2-4008-11e5-9dc5-c73b032ef819.png)

Put "Write the text here" as placeholder in the edit box.

**Comment by anderspeders** [comment]
@anjesh I have just checked MTurk and I am seeing no movement in terms of pages completed. 

Could you please provide a status update:  
http://resourcecontracts.elasticbeanstalk.com/mturk/108

**Comment by anjesh** [comment]
The assignments are now coming and information updated in the assignment page.
