### ISSUE TITLE
UI: header tab with viewer selection options

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#183]
text only | text / PDF | PDF only | annotations only

**Comment by anjesh** [comment]
UI is designed as per https://projects.invisionapp.com/d/main/default/#/console/3736944/85681169/preview

![image](https://cloud.githubusercontent.com/assets/120488/9486705/675df1c2-4bea-11e5-8370-c136367301e5.png)

and implemented under this #84
