### ISSUE TITLE
Add view function for: draft / completed metadata in internal dashboard

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#184]
As a researcher I need to be able to sellect/view all contracts that have not been approved/published. 

Currently I cannot view only the contracts which have: 
- not been published
- not had metadata marked as complete

This is needed as i want to go through this specifically.

**Comment by anderspeders** [comment]
Unless anything has been done on this, I suggest that we push this to **blue sky**. 

We need to focus on the core bigger pieces for the moment.

**Comment by anjesh** [comment]
Duplicate of https://github.com/NRGI/resourcecontracts.org/issues/212
Closing this.
