### ISSUE TITLE
Narrative and visua; introduction story: How to read a contract

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#187]
This could borrow from: 
http://www.globalresiliencepartnership.org/surat-story/

Or more familiarly: 
http://thelensnola.org/2014/05/29/how-to-read-a-government-contract/

Check list: 
- Identify writer of the piece (Anders)
- Review content
- Design intro-page (YI)

thanks for idea @jedm

**Comment by charlesyoung** [comment]
@anderspeders is this still required?
