### ISSUE TITLE
Frame / define terms for: Tagging / metadata / annotation

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#19]

**Comment by anjesh** [comment]
Fields to be captured in the contract metadata, which will be stored in JSON datatype.

Field name | Remarks
-----------------------------
Language | language of the contract
CountryCode | http://unstats.un.org/unsd/tradekb/Knowledgebase/Country-Code vs http://iatistandard.org/201/codelists/Country/
Resource
Type of Mining Title
Signature Date 
Signature Year | This could be easily pulled from signature date
Contract Term (duration) in Years | Need to see if the start date and end date are to be captured than the duration

There are other advanced fields which still need more discussion and could easily be included in the JSON store.

**Comment by anjesh** [comment]
Anders, what's this issue about?

**Comment by anderspeders** [comment]
I think we can close this.
