### ISSUE TITLE
Add <Contract status> to metadata

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#190]
The category will have the following options: 
- Pending: This contract has been proposed, but is not yet in force. It may be awaiting signature.  
- Active: This contract has been signed by all the parties, and is now legally in force.  
- Cancelled: This contract has been cancelled prior to being signed.
- Terminated: This contract was signed and in force, and has now come to a close. This may be due to successful completion of the contract, or may be early termination due to some non-completion.

This category will be in compliance with the Open Contracting Data Standard: 
http://ocds.open-contracting.org/standard/r/1__0__0/en/schema/codelists/#contract-status

**Comment by jpmckinney** [comment]
Overlaps #723, may want to remove "blue sky" tag if #723 proceeds.

**Comment by jpmckinney** [comment]
@anderspeders: @SamCCSI had requested a metadata field to flag termination. Do we remove "blue sky" or not? If not, then I'll not worry about this issue.

**Comment by KaitlinCCSI** [comment]
Note that this is a suggestion that was raised a long time ago by advisory
group for RC. Main obstacle is that we don't have resources to do extensive
research on each contract to determine if something has been terminated,
and we don't do much outside research on projects as a matter of course.
But to the extent that we do know something has been terminated, it seems
useful to be able to flag. Ideally this could be done in a way that does
not imply that a document has not been terminated if the notice doesn't
appear (in other words, in the absence of a message, there is no assumption
either way about whether it has been terminated or not).

On Mon, Dec 14, 2015 at 12:40 PM, James McKinney <notifications@github.com>
wrote:

> @anderspeders <https://github.com/anderspeders>: @SamCCSI
> <https://github.com/SamCCSI> had requested a metadata field to flag
> termination. Do we remove "blue sky" or not? If not, then I'll not worry
> about this issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/190#issuecomment-164521503>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PRuExIa&m=d372ae67ff34&t=20151214&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PRuExIa&m=d372ae67ff34&t=20151214&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01PRuExIa&m=d372ae67ff34&t=20151214&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by charlesyoung** [comment]
Is adding contract status to the metadata likely to happen?

**Comment by anderspeders** [comment]
The data that we capture in RC.org is based on the time of the contract signature. Thus the information is not meant to be correct and updated at all times. 

Therefore contract status should in my opinion not be included. 

For extractives projects - which has a related contract - we will be capturing this type of information in resourceprojects.

**Comment by KaitlinCCSI** [comment]
@anderspeders Given that the advisory group raised this years ago, shouldn't we consider this further? Not all info on the summary page necessarily comes from the time of the contract sig. There are other pieces of info that have been added to this new platform that are pulled from other places and not strictly from the contract -- for example, OpenCorporates ID. Also, if we have the ability (even limited) to help make the info more correct/updated, is there a reason why we wouldn't want to?

**Comment by charlesyoung** [comment]
@anderspeders @KaitlinCCSI is this still required?

**Comment by KaitlinCCSI** [comment]
No, I think not. We will deal with most of it in: https://github.com/NRGI/resourcecontracts.org/issues/723
