### ISSUE TITLE
Add categories to <Document type>

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#191]
The following categories should be added to the field Document types.

*field name | name in metadata form* 
environmentalImpact <Environmental Impact> 
contractAnnexe	<Annexes to the Contract> This section includes annexes such as contract maps		
contractGuarantees	<Guarantees>		
subContract	<Subcontracts>	A document detailing subcontracts or the subcontract itself
needsAssessment	<Needs Assessment>		
feasibilityStudy	<Feasibility study>		
projectPlan	<Project plan>

**Comment by anjesh** [comment]
Currently there are 3 document types in the system

* Contract
* Model Contract
* Translated Contract

We are adding the above now and will have the following list.

* Contract
* Model Contract
* Translated Contract
* Environmental Impact
* Contract Annexe
* Contract Guarantees
* Sub Contract
* Needs Assessment
* Feasiblity Study
* Project Plan
* Others (with free text)

Others is suggested by Sam here https://github.com/NRGI/resourcecontracts.org/issues/194 

@anderspeders, please confirm.

**Comment by anjesh** [comment]
Done.
