### ISSUE TITLE
Entering OpenCorporates Link

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#193]
This is still causing problems for our uploader.

See http://resourcecontracts.elasticbeanstalk.com/contract/109

link entered goes to http://resourcecontracts.elasticbeanstalk.com/contract/us_de/3772096

**Comment by anjesh** [comment]
Currently the field takes the link with the http://opencorporates.com and not just id. Need to do the validation in the form. For now i have updated the link to https://opencorporates.com/companies/us_de/3772096 in the form.

**Comment by anderspeders** [comment]
Excellent, thanks

**Comment by anjesh** [comment]
Validation in place for the proper URL with http
