### ISSUE TITLE
Document Type - Add 'other' / free text 

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#194]
We have some documents that are not contracts that will be included in RC.

Currently there are only three document types which are all contract types.

It would be great to have a free form category for non-contract documents. Eg detailed government decrees/announcements re contracts. Eee, eg, http://resourcecontracts.elasticbeanstalk.com/contract/109

**Comment by anjesh** [comment]
Moving discussion here https://github.com/NRGI/resourcecontracts.org/issues/191#issuecomment-136293234
Closing this.
