### ISSUE TITLE
AMLA entries for Congo directing to Cote d'Ivoire

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#195]
Not sure if this is an automatic process but the following contracts' AMLA links erroneously direct to Cote D'Ivoir AMLA instead of Rep of Congo 

http://resourcecontracts.elasticbeanstalk.com/contract/105

http://resourcecontracts.elasticbeanstalk.com/contract/110

http://resourcecontracts.elasticbeanstalk.com/contract/112

http://resourcecontracts.elasticbeanstalk.com/contract/113

http://resourcecontracts.elasticbeanstalk.com/contract/114

**Comment by anjesh** [comment]
The file shared with us https://docs.google.com/spreadsheets/d/1EVuMc4R9NfDbJuANc1VAgLVfqCxP7aoaI2nkfXa1f8c/edit?pli=1#gid=0 seems to have mis-mapping. Will go through http://a-mla.org/index.php/countries/ to fix those mis-matches.

**Comment by anjesh** [comment]
Fixed.
