### ISSUE TITLE
Codelist for government identifiers

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#196]
For each contract one or government entities will act as "owners" of the contract.

These government entities are currently available as string. However as we seek to update the data quality for RC/OLC we will need proper standardised entities. 

Here are the required steps: 
1) NRGI and CCSI will update the list of government entities: 
https://docs.google.com/spreadsheets/d/1xiph4Gfm_n5yJWUB2dvo1z_aDJ_POHpeUbAqLoiFWUA/edit#gid=0
2) A government entity code will be assigned
3) The codelist will be added to the metadata form
4) Current contracts in the portal will be matched / reconciled to the new government entity codelist

**Comment by jpmckinney** [comment]
Overlaps #588

**Comment by anjesh** [comment]
duplicate as mentioned by james.
