### ISSUE TITLE
UI round one implementation

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#198]
Comments provided to the site: 
https://projects.invisionapp.com/share/VZ3SHI63A#/screens/93792697

Please implement this during sprint 6 to ensure that we have something proper to comment on.

**Comment by anjesh** [comment]
Most of the pages have been completed for RC - there are still few left. Now need to create similar one for OLC. Moving to Sprint 7.

**Comment by anjesh** [comment]
Round one implementation done for RC and OLC subsites. Ready for feedback.
