### ISSUE TITLE
Sys admin check list pre-launch

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#199]
- clarify domain for OpenLandContracts.org - can YIPL deploy to the site / does NRGI have access to it?
- setup google analytics for OLC and RC
- backup of datastore (this might already be in place)

@byndcivilization Let's discuss this sometimes this week if possible.

**Comment by anderspeders** [comment]
@byndcivilization Do we need anything else here: 

I assume that we can the shortly before launch simply point openlandcontracts.org to the site living at: alpha.openlandcontracts.org, right?

**Comment by byndcivilization** [comment]
I have OLC and RC domains.

Database is on our rds instance which does daily snapshots and stores for up to 7 days. Can modify whenever we want.

For GA I can supply our account info to @anjesh whenever we want.

**Comment by byndcivilization** [comment]
Only thing I'd add is I'd like to know scaling strategy if we've gotten there

**Comment by anderspeders** [comment]
For CCSI (for OLC) - I assume that we can simply forward to GA key to them - and they can check them selves...?
