### ISSUE TITLE
Sort out document types - eg. model contracts

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#20]

**Comment by anjesh** [comment]
What is document type? "Type Of Contract" or "Document Type". The document types are defined and have the following list in [spreadsheet](https://docs.google.com/spreadsheets/d/12UCQA422r5Dg3wruUmYHL2SCLdDrlesCPcm2tHD8Yu4/edit#gid=1329720090).

* contract
* model contract
* translated contract

@anderspeders - close this?

**Comment by anderspeders** [comment]
Yes, let's close. 

We can re-open if any other issues arise around this.
