### ISSUE TITLE
Workflow for including SEC oil and mining contracts in RC.org

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#202]
Steps should include: 

1) Shamelessly fork @pudo's SEC oil contract scraper: https://github.com/pudo/edgar-oil-contracts

2) Add SICS for mining (with oil SICS)
1000    9       METAL MINING
1040    9       GOLD AND SILVER ORES
1090    9       MISCELLANEOUS METAL ORES
1220    9       BITUMINOUS COAL & LIGNITE MINING
1221    9       BITUMINOUS COAL & LIGNITE SURFACE MINING
1400    9       MINING & QUARRYING OF NONMETALLIC MINERALS (NO FUELS)

3) Add mining terms to search language: https://github.com/pudo/edgar-oil-contracts/blob/master/searches.txt

4) Generate seedlist with regular updates

5) Develop review workflow for uploaders: Using for example the idea of http://www.gender-balance.org/ to prompt reviewers for response to: "Does this SEC document contain a contract?"

6) Extract suggestions for core metadata: **Company name**, **Signatory date**, **Commodity**. 

7) Buy @pudo a Mate

**Comment by charlesyoung** [comment]
@anderspeders is this still required?
