### ISSUE TITLE
Partner and funder logos for RC.org and OLC.org

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#203]
**For RC.org**

Text: 
"ResourceContracts.org is a project of the Natural Resource Governance Institute, the Columbia Center on Sustainable Investment and the World Bank Governance for Extractive Industries program. The project is supported by the African Legal Support Facility and UK Department for International Development."

Partners: 
- For CCSI: https://drive.google.com/file/d/0B0itojFFyvjCSGR5ZDhqakFtbEk/view?usp=sharing
- World Bank: http://www.socialprogressimperative.org/system/images/W1siZiIsIjIwMTUvMDMvMTgvMTgvMDYvMzIvMjE5L1RoZV9Xb3JsZF9CYW5rX2xvZ28ucG5nIl1d/The-World-Bank-logo.png or http://www.columbia.edu/cu/openlandcontracts/images/wbgroup.jpg
- NRGI: coming

Funding support from
- African Legal Support Facility: https://drive.google.com/file/d/0B0itojFFyvjCeXk5dmRMRWJ6Qnc/view?usp=sharing
- UK Department for International Development: https://drive.google.com/file/d/0B0itojFFyvjCb0syREljUy1wclk/view?usp=sharing

**OLC.org**
@SamCCSI: Could you provide the details here on language, links to logos and introductions on funder attribution?

**Comment by SamCCSI** [comment]
Text should read: "OpenLandContracts.org is a project of the Columbia Center on Sustainable Investment and the World Bank. The project is supported by the UK Department for International Development."

CCSI logo: https://www.dropbox.com/s/owf01noczwjs4or/CCSI_logo_tree_icon.jpg?dl=0
WB logo: 
![wbg-governance-horizontal-rgb-high](https://cloud.githubusercontent.com/assets/12913915/9772951/5eea8e00-570d-11e5-87c3-58ccfb7f72d1.png)

**Comment by SamCCSI** [comment]
Slight amendment: The sentence should say: "OpenLandContracts.org is a project of the Columbia Center on Sustainable Investment and the World Bank. The project is supported by UKaid from the Department for International Development."

Also, if possible:
- The DFID logo (either of the logos below) should link to "www.dfid.gov.uk"
- Can CCSI and WB's logos also link to our sites, please.

![uk aid logo black and white](https://cloud.githubusercontent.com/assets/12913915/9795760/8dadf976-57c0-11e5-9149-2bfa8c546e18.JPG)
![uk aid logo](https://cloud.githubusercontent.com/assets/12913915/9795762/8f1a3e32-57c0-11e5-8476-043854c72b65.png)

**Comment by anderspeders** [comment]
Questions: 

1) Do you need the UK logo on the front page (alternative is to add in about page, which you can edit your self): If yes, could you add a screen dump to indicate where?

2) Again, where on the front page do you want this: "OpenLandContracts.org is a project of the Columbia Center on Sustainable Investment and the World Bank. The project is supported by UKaid from the Department for International Development."

If not on front page - this could also go on the about page...

3) To be 100 pct sure, please confirm the URLs for WB and CCSI and I will check if we can link to these. Should not be a problem. 

Thanks again for the patience here.

**Comment by SamCCSI** [comment]
1. Please add the DFID logo next to the CCSI and WB logos in the footer. It can go to the right of the WB's logo (like in our flyer).   Can you please confirm that we would be able to easily remove this from the footer once our grant runs out (a year from Nov) if the funding is not renewed? If this would present a problem, we should just put it on the About page.  

2. The current logos in the footer of OLC are not correct (neither the CCSI logo nor the WB logo); need to be fixed using the logos included above  

3. The hyperlinks for WB logo - http://www.worldbank.org/en/topic/governance and CCSI logo - http://ccsi.columbia.edu/  

4. I don't think we need the sentence ("OpenLandContracts.org is a project of the Columbia Center on Sustainable Investment and the World Bank. The project is supported by UKaid from the Department for International Development.") on the home page. I have added it to the About page instead.  

Many thanks!

**Comment by anderspeders** [comment]
@SamCCSI On 1) - yes it should be easy to remove again. 

Also thanks for the detailed outline. 

Thanks @anjesh for pushing this forward.

**Comment by SamCCSI** [comment]
Thank you both!!

On Mon, Sep 21, 2015 at 7:59 PM, Anders <notifications@github.com> wrote:

> @SamCCSI <https://github.com/SamCCSI> On 1) - yes it should be easy to
> remove again.
>
> Also thanks for the detailed outline.
>
> Thanks @anjesh <https://github.com/anjesh> for pushing this forward.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/203#issuecomment-142061627>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by anderspeders** [comment]
@SamCCSI This is now implemented on front page. Could you approve?

**Comment by SamCCSI** [comment]
Hi Anders,

This is approved with one small qualification: can you remove the green
filter over the photo? We prefer the background to just be the photo itself.

The crop looks good, too!

Sam

On Tue, Sep 22, 2015 at 1:07 PM, Anders <notifications@github.com> wrote:

> @SamCCSI <https://github.com/SamCCSI> This is now implemented on front
> page. Could you approve?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/203#issuecomment-142250996>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by anjesh** [comment]
@sweetanzell @anjhero need to remove the green overlay over the image.

**Comment by anderspeders** [comment]
Excellent, thanks @anjesh @SamCCSI

**Comment by SamCCSI** [comment]
Thanks for removing the green filter!

Unfortunately the title is now hard to read. Is it possible to try moving
the photo slightly upwards, so that there is a darker part of the image
behind the white text title, making the title more readable?


On Wed, Sep 23, 2015 at 4:58 PM, Anders <notifications@github.com> wrote:

> Excellent, thanks @anjesh <https://github.com/anjesh> @SamCCSI
> <https://github.com/SamCCSI>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/203#issuecomment-142628871>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by KaitlinCCSI** [comment]
Another option is having the title (Open Land Contracts) shaded so that it starts in white and ends in dark gray or black, so that the white letters are in front of the dark part of the photo and the dark gray/black letters in front of the light part of the photo? (Ie, gradient blending from white (on the left side) to dark grey/black (on the right)). If we were able to send the lettering, could it be implemented?

**Comment by anjesh** [comment]
Thanks Kaitlin. We will fix that.

**Comment by anjhero** [comment]
We've made an update to the homepage design as per your suggestions.  However, we feel this has produced some hard contrast making it harder for the eyes to scan. Please check:
![homepage i](https://cloud.githubusercontent.com/assets/528549/10099142/8d7b01c8-63a6-11e5-9acb-650ea462f6ae.png)
![homepage ii](https://cloud.githubusercontent.com/assets/528549/10099151/a384b25c-63a6-11e5-8c33-3126dd396aa6.png)

We're thinking of manipulating the pic a bit so that the white text properly contrasts with the background. We'll send an update on Monday.

**Comment by KaitlinCCSI** [comment]
Okay, thanks. Agree that the shaded name is a bit hard to read. Manipulating the pic, and then keeping the title all in white, sounds fine. Thanks.

**Comment by anjesh** [comment]
we have slightly added the shade to the image and the text looks distinct now. Please close this issue if that looks good. 

![image](https://cloud.githubusercontent.com/assets/120488/10140469/5dc2454e-6627-11e5-9de5-ed7ed2634109.png)

**Comment by anderspeders** [comment]
@KaitlinCCSI @SamCCSI Can you sign off on this? 

If another review is required we will need very precise directions.

**Comment by SamCCSI** [comment]
Happy to close for now (given everyone' workloads), but will need to alter
the design slightly post launch.

On Tue, Sep 29, 2015 at 2:53 PM, Anders <notifications@github.com> wrote:

> @KaitlinCCSI <https://github.com/KaitlinCCSI> @SamCCSI
> <https://github.com/SamCCSI> Can you sign off on this?
>
> If another review is required we will need very precise directions.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/203#issuecomment-144155135>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by anderspeders** [comment]
thanks @SamCCSI, 

Maybe a few scetches from your designer can make us hit the final design. else precise directins can do. 

I will push this to sprint 10 as agreed.

**Comment by anderspeders** [comment]
A new ticket for specific design tweaks to front page image has now been created #479, 

Thus closing this ticket on partner logos.
