### ISSUE TITLE
RC.org data migration leftowers - contract unaccessible from S3 server

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#204]
We have now completed the S3 migration of Rc.org to the demo site. 

However approx. 20 contracts could not be migrated as there was no access to their S3 link?

@anjesh will provide a list of the URLs which were rendered inaccessble

@byndcivilization might have ideas?

**Comment by anjesh** [comment]
These are the list of contracts that are not accessible and hence not included in the migration list. Find the json file here https://www.dropbox.com/sh/d3ouhoa8flfzyj6/AAC1tHE2N8KzUpQj-6GQy5zJa/api-data?dl=0

E.g. For the first one, https://www.dropbox.com/sh/d3ouhoa8flfzyj6/AAD_zX8vUDbSr5rVNC0eAax8a/api-data/1173874-western-cluster-limited-liberia.json?dl=0

https://s3.amazonaws.com/s3.documentcloud.org/documents/1173874/western-cluster-limited-liberia.pdf files says 
![image](https://cloud.githubusercontent.com/assets/120488/9490545/3ff7651e-4c08-11e5-960f-db26c3bca35f.png)


Contract Name : Western Cluster Limited - Liberia, 2011
File Name : 1173874-western-cluster-limited-liberia.json

Contract Name : Griffiths Energy (Tchad) Ltd - Tchad, 2011, French
File Name : 1372269-psc-griffiths-energy-chad-ltd-and-chad-jan-2011.json

Contract Name : Griffiths Energy (DOH) Ltd - Tchad, 2011, French
File Name : 1372270-psc-griffiths-energy-doh-ltd-and-chad-aug-2011.json

Contract Name : Petrochad (Mangara) Limited - Tchad, 2011, French
File Name : 1372272-psc-petrochad-mangara-limited-and-chad-may-2011.json

Contract Name : Kosmos Energy - Suriname, Block 45, 2011
File Name : 1385899-kosmos-energy-suriname-block-45-2011.json

Contract Name : ONGC, GSPC, HOEC - India, 2000
File Name : 1505885-ongc-gspc-hoec-india-2000.json

Contract Name : ADDAX, ABACAN, Block 4 - Benin, 1997
File Name : 1506127-addax-abacan-block-4-benin-1997.json

Contract Name : Kosmos Energy, Block C8 - Mauritania, 2012
File Name : 1509885-kosmos-energy-block-c8-mauritania-2012.json

Contract Name : Kosmos Energy, Block C12 - Mauritania, 2012
File Name : 1509888-kosmos-energy-block-c12-mauritania-2012.json

Contract Name : Kosmos Energy, Block C13 - Mauritania, 2012
File Name : 1509890-kosmos-energy-block-c13-mauritania-2012.json

Contract Name : Kosmos - Morocco, 2011 (Cap Boujdour)
File Name : 1710314-petroleum-agreement-kosmos-cap-boujdour-see.json

Contract Name : Kosmos - Morocco, 2013 (Tarhazoute)
File Name : 1710318-kosmos-morocco-2013-tarhazoute.json

Contract Name : DRC Dino Steel
File Name : 408950-drc-dino-steel.json

Contract Name : SOKIMO - DRC, 2011
File Name : 472398-drc-ferro.json

Contract Name : GECAMINES - DRC, 2009
File Name : 486149-drc-central-african-mining-and-exploration.json

Contract Name : COMINIERES - DRC, 2010
File Name : 486153-drc-dbb-corp.json

Contract Name : SOKIMO - DRC, 2011
File Name : 496389-drc-good-engineering-sprl.json

Contract Name : 3PL Helalin Annulation Permis
File Name : 560260-3pl-helalin-annulation-permis.json

**Comment by anderspeders** [comment]
@byndcivilization any suggestions here?

**Comment by anjesh** [comment]
@anderspeders @byndcivilization We need to make sure that pdf are available for these contracts need to unpublish them for RC launch.

**Comment by byndcivilization** [comment]
Sorry I missed this one. Where are these coming from? Our s3 or doc cloud s3?

**Comment by anderspeders** [comment]
Doc cloud, I think. These are from the initial migration from RC.org which we did back in August...

**Comment by anderspeders** [comment]
@byndcivilization @anjesh Let's make sure we find a fix here. Are we any closer on a diagnosis of why they could not migrate?

**Comment by sadhakbj** [comment]
2) Contract Name : Griffiths Energy (Tchad) Ltd - Tchad, 2011, French
File Name : 1372269-psc-griffiths-energy-chad-ltd-and-chad-jan-2011.json
Pdf Link: https://s3.amazonaws.com/s3.documentcloud.org/documents/1372269/psc-griffiths-energy-chad-ltd-and-chad-jan-2011.pdf (WORKING)

3) Contract Name : Griffiths Energy (DOH) Ltd - Tchad, 2011, French
File Name : 1372270-psc-griffiths-energy-doh-ltd-and-chad-aug-2011.json
Pdf Link: https://s3.amazonaws.com/s3.documentcloud.org/documents/1372270/psc-griffiths-energy-doh-ltd-and-chad-aug-2011.pdf (working)

4) Contract Name : Petrochad (Mangara) Limited - Tchad, 2011, French
File Name : 1372272-psc-petrochad-mangara-limited-and-chad-may-2011.json
Pdf Link: https://s3.amazonaws.com/s3.documentcloud.org/documents/1372272/psc-petrochad-mangara-limited-and-chad-may-2011.pdf (WORKING)

5)Contract Name : Kosmos Energy - Suriname, Block 45, 2011
File Name : 1385899-kosmos-energy-suriname-block-45-2011.json 
Pdf Link: https://s3.amazonaws.com/s3.documentcloud.org/documents/1385899/kosmos-energy-suriname-block-45-2011.pdf (WORKING)

6) Contract Name : ONGC, GSPC, HOEC - India, 2000
File Name : 1505885-ongc-gspc-hoec-india-2000.json
Pdf: https://s3.amazonaws.com/s3.documentcloud.org/documents/1505885/ongc-gspc-hoec-india-2000.pdf (WORKING)

7) Contract Name : ADDAX, ABACAN, Block 4 - Benin, 1997
File Name : 1506127-addax-abacan-block-4-benin-1997.json
Pdf: https://s3.amazonaws.com/s3.documentcloud.org/documents/1506127/addax-abacan-block-4-benin-1997.pdf (WORKING)

8) Contract Name : Kosmos Energy, Block C8 - Mauritania, 2012
File Name : 1509885-kosmos-energy-block-c8-mauritania-2012.json
Pdf: https://s3.amazonaws.com/s3.documentcloud.org/documents/1509885/kosmos-energy-block-c8-mauritania-2012.pdf (WORKING)

9) Contract Name : Kosmos Energy, Block C12 - Mauritania, 2012
File Name : 1509888-kosmos-energy-block-c12-mauritania-2012.json
Pdf: https://s3.amazonaws.com/s3.documentcloud.org/documents/1509888/kosmos-energy-block-c12-mauritania-2012.pdf (Working)

10) Contract Name : Kosmos Energy, Block C13 - Mauritania, 2012
File Name : 1509890-kosmos-energy-block-c13-mauritania-2012.json
Pdf: https://s3.amazonaws.com/s3.documentcloud.org/documents/1509890/kosmos-energy-block-c13-mauritania-2012.pdf (WORKING)

11) Contract Name : Kosmos - Morocco, 2011 (Cap Boujdour)
File Name : 1710314-petroleum-agreement-kosmos-cap-boujdour-see.json
Pdf: https://s3.amazonaws.com/s3.documentcloud.org/documents/1710314/petroleum-agreement-kosmos-cap-boujdour-see.pdf (working)

12) Contract Name : Kosmos - Morocco, 2013 (Tarhazoute)
File Name : 1710318-kosmos-morocco-2013-tarhazoute.json
Pdf: https://s3.amazonaws.com/s3.documentcloud.org/documents/1710318/kosmos-morocco-2013-tarhazoute.pdf (working)

13) Contract Name : DRC Dino Steel
File Name : 408950-drc-dino-steel.json
Pdf: https://s3.amazonaws.com/s3.documentcloud.org/documents/408950/drc-dino-steel.pdf (working)

14) Contract Name : SOKIMO - DRC, 2011
File Name : 472398-drc-ferro.json
Pdf: https://s3.amazonaws.com/s3.documentcloud.org/documents/472398/drc-ferro.pdf (working)

15) Contract Name : GECAMINES - DRC, 2009
File Name : 486149-drc-central-african-mining-and-exploration.json
Pdf: https://s3.amazonaws.com/s3.documentcloud.org/documents/486149/drc-central-african-mining-and-exploration.pdf (working)

16) Contract Name : COMINIERES - DRC, 2010
File Name : 486153-drc-dbb-corp.json
Pdf: https://s3.amazonaws.com/s3.documentcloud.org/documents/486153/drc-dbb-corp.pdf (working)

17) Contract Name : SOKIMO - DRC, 2011
File Name : 496389-drc-good-engineering-sprl.json
Pdf: https://s3.amazonaws.com/s3.documentcloud.org/documents/496389/drc-good-engineering-sprl.pdf (working)

18) Contract Name : 3PL Helalin Annulation Permis
File Name : 560260-3pl-helalin-annulation-permis.json
Pdf: https://s3.amazonaws.com/s3.documentcloud.org/documents/560260/3pl-helalin-annulation-permis.pdf (working)

**Comment by anjesh** [comment]
We looked into these documents again.

There's one pdf with access denied.

* 1173874-western-cluster-limited-liberia.json
https://s3.amazonaws.com/s3.documentcloud.org/documents/1173874/western-cluster-limited-liberia.pdf

There are 5 documents which contains the same pdf (content wise) as 1385899-kosmos-energy-suriname-block-45-2011.json  https://s3.amazonaws.com/s3.documentcloud.org/documents/1385899/kosmos-energy-suriname-block-45-2011.pdf

* 1509885-kosmos-energy-block-c8-mauritania-2012.json	 https://s3.amazonaws.com/s3.documentcloud.org/documents/1509885/kosmos-energy-block-c8-mauritania-2012.pdf
* 509888-kosmos-energy-block-c12-mauritania-2012.json	https://s3.amazonaws.com/s3.documentcloud.org/documents/1509888/kosmos-energy-block-c12-mauritania-2012.pdf
* 1509890-kosmos-energy-block-c13-mauritania-2012.json	https://s3.amazonaws.com/s3.documentcloud.org/documents/1509890/kosmos-energy-block-c13-mauritania-2012.pdf
* 1710314-petroleum-agreement-kosmos-cap-boujdour-see.json	 https://s3.amazonaws.com/s3.documentcloud.org/documents/1710314/petroleum-agreement-kosmos-cap-boujdour-see.pdf
* 1710318-kosmos-morocco-2013-tarhazoute.json	 https://s3.amazonaws.com/s3.documentcloud.org/documents/1710318/kosmos-morocco-2013-tarhazoute.pdf

All other are fixed.

**Comment by anderspeders** [comment]
Great. Closing this and reopening question of dealing with duplicate PDFs.
