### ISSUE TITLE
Integration / cleaning of annotations terms

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#206]
Columns from previous unstructured annotations needs to be streamlined/structured by @anderspeders and possibly @samccsi if time permits. 

Old annotations (unstructured) are in column A. These needs to be mapped/harmosed to a structured format in column C: 
https://docs.google.com/spreadsheets/d/1K0wlloEAPFncrNA_mwBjqvW81A5xRpFlK0qlv-j5ZYo/edit?usp=drive_web

**Comment by anderspeders** [comment]
Please review carefully. This is now completed in this google doc: https://docs.google.com/spreadsheets/d/1K0wlloEAPFncrNA_mwBjqvW81A5xRpFlK0qlv-j5ZYo/edit#gid=1612543715

Column C includes the new mapped annotation categories (from the original annotations in column A) 

Column D includes a new **Annotation cluster category** which would be helpful to add for grouping of search and drilldown functionalities on the site. 

Each Annotation Category is therefore also mapped to one of the following **Annotation cluster categories**:   
General
Financial/fiscal
Social/human rights
Environmental
Operational
Other

This is now complete and ready for deployment in sprint 7!

**Comment by anjesh** [comment]
The annotations are imported as per mapped annotation category but the cluster category still needs to be handled. Current implementation doesn't handle those cluster category in the system.

**Comment by anjesh** [comment]
New issue created for clusters https://github.com/NRGI/resourcecontracts.org/issues/348
