### ISSUE TITLE
Contract download error (Major)

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#208]
Error when downloading a contract in MS Word format. 

![image](https://cloud.githubusercontent.com/assets/13888372/9410775/53a0dc7e-4822-11e5-9789-47e6b29dd4d0.png)

**Comment by anderspeders** [comment]
Can you add the example of the contract (though it might be all?)

**Comment by charlesyoung** [comment]
I downloaded three contracts in Word format and experienced the issue on all three.

**Comment by anjesh** [comment]
Yes. These files appears to work with open office and libre office. There's certain characters in the document when generating the docx file from the contract text - that crashes the microsoft word. Will be fixing this soon.

**Comment by anjesh** [comment]
It's fixed now.
