### ISSUE TITLE
Create notification email system for Mech Turk

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#209]
@byndcivilization Please describe how this can be delivered by @anjesh and team.

**Comment by byndcivilization** [comment]
Linked to #182 and #73.

We need to fix the workflow for mechanical turk. I should be the following:
* User uploads contract and routes to MTurk as page separated HITs **(request records should contain link to requester --  including email)**
* HIT assignment created and assigned in MTurk system
* Turker completes work and submits completed HIT
* Email notification is sent to requester letting them know that HIT is complete and needs to be approved or not.
* Approvals disperse funds to turker and load text to system. denials need to send info back to Turker on what is wrong.


Notes:
I'm not sure how you're currently handling smtp (notification for when a contract is back from ABBYY for example). If it makes it any easier, we can use our Mandrill acct to handle smtp through the http://laravel.com/docs/4.2/mail module. API access is at the app level so I can just generate you a key. Let me know.

###Blue sky
questions are currently sent to rc-turk@recgov... We should set up a rule to route these through to requestor. API service from rc.org db?

**Comment by byndcivilization** [comment]
Heres an example email:
TITLE: Regarding Amazon Mechanical Turk HIT 3VDVA3ILID32TXLB6O2LJY6ZAKL1GW


Message from Anthony Ryan Bradley (aryanbradley@gmail.com)
---------------------------------
Customer ID: A2GJ45P0Z57DRD
I've completed this HIT, but the submit function doesn't seem to be working. I've copied the text to a Word document, but I don't know how to proceed.

Thanks
---------------------------------

Greetings from Amazon Mechanical Turk,

The message above was sent by an Amazon Mechanical Turk user.
Please review the message and respond to it as you see fit.

Sincerely,
Amazon Mechanical Turk

**Comment by anjesh** [comment]
The process is as follows

1. uploader uploads the contract
2. uploader/admin decides whether to send the contract to Mturk or not
3. uploader/admin sends the contract to Mturk
4. scheduler/cron runs the script once everyday to check if any task has been completed by the worker or not
5. if the executed script finds any task that has been completed but not approved/rejected yet, it sends email to the uploader to review the task.

The following brief email content should be good for now to notify the uploaders. 

--

Subject: Mturk assignments for your action for [Contract-name]

Body: 

Contract name: ....
Total tasks: 20
Tasks completed: 8
Tasks approved: 5
Tasks requiring your action: 3

Please review the completed tasks before approval.

--

**Comment by anjesh** [comment]
The email process is in-place and sends one email per day only if there are any actions to be taken.

**Comment by anderspeders** [comment]
This is what I get now. To me this looks ok. 

---

From: NRGI [mailto:nrgi@mail187-15.suw11.mandrillapp.com] On Behalf Of NRGI
Sent: Thursday, October 15, 2015 9:00 AM
To: Anders Pedersen
Subject: Mturk assignments for your action for [Liberia, Salala Rubber Corporation, Concession, 1 August 1959]

Liberia, Salala Rubber Corporation, Concession, 1 August 1959
click here to check 
•	Total tasks: 20
•	Tasks completed: 19
•	Tasks approved: 18
•	Tasks requiring your action: 1 
Please review the completed tasks before approval.

**Comment by SamCCSI** [comment]
Apologies: I just started a new issue that should probably rolled into this issue: https://github.com/NRGI/resourcecontracts.org/issues/533
