### ISSUE TITLE
Dashboard for internal metrics

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#21]
As an administrator, I would like to have an overview of key metrics from the site: 
- how many contracts were added the last month
- how many contracts were tagged and annotated for example

**Comment by anderspeders** [comment]
This should also include a tracker, which would enable administrators to check the compliance / completion of metadata.

**Comment by anjesh** [comment]
Are there any validation rules for checking compliance?

**Comment by anderspeders** [comment]
No. First step could be to have a tracker showing: 

- timeline of [contracts added] by [user] by [metadata, annotated, published]

Let me know how complicated this is to generate.

**Comment by anjesh** [comment]
Related to #92. We could see which the timeline of the overall contracts in the system as well as for individual users and individual contracts. We could say something like "Activity Log". We have already started working on the logging part in sprint2 but need to create dashboard and proper presentation of the collected information.

**Comment by anjesh** [comment]
The dashboard will show the numbers as shown below. Later there will be charts/graphs showing these numbers. Any other information that would make sense in the dashboard welcome. 

![image](https://cloud.githubusercontent.com/assets/120488/8446585/9076c984-1fcc-11e5-92ad-8b0125da0493.png)
