### ISSUE TITLE
Contract download name

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#210]
Will it be possible to name the downloaded contract appropriately and not by the current machine produced name like '51937f3aadbf30f623b9aaa5ef16c1ad462c4089.pdf' which has no reference to the contract?

**Comment by anderspeders** [comment]
@anjesh Can you review and estimate the time required to do this?

We can then discuss which sprint to allocate this for.

**Comment by anjesh** [comment]
Fixed now. All the uploaded files in the S3 have also been renamed - the pdf filename is now [contract-id]-[truncated-contract-name]
 There might be few misses in the subsite as they require re-publishing the contracts again. Will take care of that. Will close for now.
