### ISSUE TITLE
Add search features for interface

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#212]
As an administrator I would like to be able to filter by the following:

OCR: 
- Acceptable
- Needs editing
- Needs full trasncription

Metadata: 
- Draft  
- Complete  
- Published

PDF Text: 
- Draft  
- Complete  
- Published

*Why*: This is important as we wish to track which documents needs review and editing before publication. 

@anjesh: Can we include this in sprint 7 or 8?

**Comment by anderspeders** [comment]
These can be added under the view *Contract quality issues*: 

![image](https://cloud.githubusercontent.com/assets/1101585/9468057/9451aeea-4b0d-11e5-8fb0-a271b9de8c77.png)

**Comment by anjesh** [comment]
Enabled in admin.
