### ISSUE TITLE
Launch sites - alpha.resourcecontracts.org and alpha.openlandcontracts.org

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#214]

**Comment by anderspeders** [comment]
@byndcivilization to follow up on registration details asap.

**Comment by anderspeders** [comment]
@anjesh We have confirmed that NRGI has access to RC.org and checking with the other domain at CCSI.

**Comment by anjesh** [comment]
@santosh-neupane Please document the process of setting up custom domain in amazon.

**Comment by santosh-neupane** [comment]
- Log into the cpanel of the web hosting server i.e. WHM
- Create an account/domain to the server
- Go to Edit DNS Zone
- Select the account to be edited, then the url of the aws instace can be set to value at CNAME of the account
- Edit the CNAME with value ``<url of the site>``

![aws1](https://cloud.githubusercontent.com/assets/7973604/9900336/cddefc66-5c7f-11e5-9cbe-6fa826eef66c.png)

- Save the setting

Note: Since, IP might change, we work with CNAME rather than A record in DNS Zone

**Comment by anjesh** [comment]
@byndcivilization Could you please followup with the domain owners to create the CNAME records for alpha domains as mentioned above.

**Comment by byndcivilization** [comment]
I should get access to name cheap a little later. I'll reroute to route54 and handle it all from in there.

**Comment by byndcivilization** [comment]
so @anjesh and @santosh-neupane what are we redirecting alpha.rc.org to?

**Comment by byndcivilization** [comment]
and actually why are we doing this with cnames and not something like elastic IP's.

**Comment by byndcivilization** [comment]
and I guess all of this points to the need to start migrating front end over to our own AWS system. Starting with S3 maybe?

**Comment by anjesh** [comment]
That sounds good, moving to NRGI AWS. There are 3 different systems to migrate and then S3. RDS is already NRGI's. 

1. NRGI RC admin
2. RC Elasticsearch engine with API
3. RC Subsites

I propose to do the pointing of alpha sites to our AWS for now for this wednesday launch to avoid any last minute panic. In the meantime we can do the migration in the background and tests, and if things goes fine by Monday, then we can do have alpha sites point to NRGI AWS. 

We could have system-wise movement in the following order one component at a time.

1. Move Subsites first (this should be pretty easy as no dependencies except for php)
2. Move RC-elastisearch component (only dependency is elasticsearch and php, and supervisord to monitor elasticsearch)
3. S3
4. NRGI RC admin (supervisord, beanstalkd)

**Comment by byndcivilization** [comment]
agree with spacing and waiting till post launch. In the meantime i still need the cname that i will be pointing alpha to.

**Comment by byndcivilization** [comment]
Please advise because this is what we're getting...http://alpha.resourcecontracts.org

**Comment by anjesh** [comment]
Could you point CNAME to rc-site-stage.elasticbeanstalk.com, i just configured in vhosts for alpha.resourcecontracts.org

**Comment by byndcivilization** [comment]
Done. have you done the same with OLC?

**Comment by byndcivilization** [comment]
Okay @anjesh whenever you guys reconfigure the hosts to accommodate alpha.olc.org the domain is already pointing there.

**Comment by anjesh** [comment]
alpha.resourcecontracts.org is now working. I also configured for alpha.olc.org, but it's not working. 
I don't see the entry for CNAME in dig for alpha.olc.org, it should work once CNAME is reflected. 

![image](https://cloud.githubusercontent.com/assets/120488/9938561/a95b264c-5d85-11e5-8b96-d5645ca4a52f.png)

**Comment by byndcivilization** [comment]
sorry i was abbreviating. alpha.openlandcontracts.org

**Comment by anjesh** [comment]
CNAME not reflected yet for alpha.openlandcontracts.org. Should work once CNAME appears there. 

![image](https://cloud.githubusercontent.com/assets/120488/9939337/785be3d4-5d89-11e5-8570-cdf2a04d56e5.png)

**Comment by anjesh** [comment]
both sites in place
