### ISSUE TITLE
Turker auto-approve

### ISSUE THREAD

**Issue by byndcivilization** [NRGI/resourcecontracts.org#215]
To cut down on review time we should keep a table of "good" turker ids. We can figure out the criteria as we develop this.  Maybe its a certain threshold of approved HITs. Maybe its an admin curated list. An incoming HIT submission will be checked against this table. If the turker is in the table, the HITs they submit will automatically be approved. 

We should still maintain a very light approval process once the contract is complete to make sure that everything is whole.

**Comment by anderspeders** [comment]
Pushing this to post-RC launch
