### ISSUE TITLE
Additional search paramaters

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#217]
There should be another search item titled ‘Industry’ (mining, oil, gas, land, forestry, etc) allowing for a more refined search? 

Another option is to extend the 'ResourceContracts' drop-down to include mining, oil, gas, land, forestry, etc.

**Comment by anderspeders** [comment]
Add the following search terms to the UI: 
- "Company name"
- "Corporate group"
- "Contract type"

**Comment by anjesh** [comment]
duplicate of #253
