### ISSUE TITLE
Standardised data element descriptions 

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#218]
Standardise data element descriptions to all uppercase i.e. 'Company Address' vs. 'Company number' and 'Parent company'. 

Concession / license and Project (‘l’ in lowercase), ‘Concession / license and Project’ (‘l’ is lowercase) and Company number (‘n’ in lowercase) and ‘Concession/License Name’ should have a space in between the ‘/’ to be consistent with ‘Concession / License Identifier’.

**Comment by anjesh** [comment]
Sure. All the label words will be "Title case" where all the first letters of the words will be capitalized except for certain parts of speech like conjunctions, articles.

**Comment by anjesh** [comment]
Fixed in both Admin and subsite.
