### ISSUE TITLE
Glossary description to appear when hovering over a specific term /  word

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#22]
As a user I would like to be able to read short explanations of various types of contractual provisions. For example, the tag / annotation of a _stabilization clause_ could somehow be linked to a brief explanation of what a stabilization clause is, which would then appear when the user hovers over the text.

**Comment by anjesh** [comment]
@anderspeders How do you see this feature? Where ever the term appears in the annotations listing, we show the link to the term explanation in popup. The annotation process is more or less done now, perhaps we can now think about this feature as well. We can also have a separate page for glossary as well, isn't it?

**Comment by anderspeders** [comment]
Thanks Anjesh, Let's review priorities for the coming sprints.

**Comment by SamCCSI** [comment]
Just checking - will this feature be included in the next sprint?

**Comment by jedm** [comment]
_Per recent call with @anderspeders, posting re UI/IA missing pieces:_

Several places require hovers to help guide users, in particular in the main toolbar on the single Contract page, but also in Annotations left bar (per #22, #372, #389).

Other places that could especially benefit are the search tools, the right bar with Associated/Related docs.

Is there a tech challenge to hovers? If not, maybe we could begin an inventory in a spreadsheet and start composing draft text for them.

**Comment by anjesh** [comment]
No this is not technically challenging. Please do prepare the list.

**Comment by jedm** [comment]
@anjesh - @anderspeders created an inventory document and I have contributed the first round of content and questions here:

**https://docs.google.com/spreadsheets/d/1Mn9hlhvqObC6MFOylkqRuN9gYpNfCCTGYnRgiEkWUws/edit?usp=sharing**

As the site and sub-sites get refined, the hovers document will likely need to be a living document for a 1 or 2 sprints. Thanks very much!

Jed

**Comment by SamCCSI** [comment]
Very helpful, thanks @jedm.

I've included some comments and suggested changes, and CCSI can provide
summaries of the six annotation types if needed. Anders to confirm.



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School | The Earth Institute, Columbia University
435 W116th St. New York, NY 10027
| (+1)(212) 854-2635 <+1212-854-2635> | (+1)(646) 630-4123 <+1646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

*New Report: Land Deal Dilemmas: Grievances, Human Rights, and Investor
Protections
<http://ccsi.columbia.edu/2016/03/10/land-deal-dilemmas-grievances-human-rights-and-investor-protections/>*
Available at: *http://goo.gl/qctX9I <http://goo.gl/qctX9I>*

**Comment by jedm** [comment]
@SamCCSI Agree @anderspeders should confirm but since CCSI created these categories originally I think it'd be fine if you all did first draft of those 6 explanations.

@anjesh The first post in this thread proposes links between tags and the glossary. Has there also been discussion about _auto-detection_ of glossary terms in raw text? or in Annotation text? We discussed these options in the past but I do not know if @anderspeders or @byndcivilization have raised it recently.

**Comment by upasna01** [comment]
Please update text for the hover link in the spreadsheet.
https://docs.google.com/spreadsheets/d/1Mn9hlhvqObC6MFOylkqRuN9gYpNfCCTGYnRgiEkWUws/edit#gid=1207143153

**Comment by upasna01** [comment]
@jedm 
How prompt differs from description,(in design or text)?
Please update text for the hover link in the spreadsheet.
https://docs.google.com/spreadsheets/d/1Mn9hlhvqObC6MFOylkqRuN9gYpNfCCTGYnRgiEkWUws/edit#gid=1207143153

**Comment by SamCCSI** [comment]
@upasna01 @jedm we have inserted the hover descriptions for the six annotation categories.

Jed, I left the "Description or prompt?" status for each as "Description (Prompt?)" in line with your original entry. We defer to you on what works best.

**Comment by SamCCSI** [comment]
Apologies closure was an accident.

**Comment by jedm** [comment]
@SamCCSI  - have made suggested copy edits for shorter hover text and greater consistency between hovers. 

Also, all hovers to be descriptions, not action prompts or links, per prior discussions with @anderspeders

**Comment by SamCCSI** [comment]
Thanks @jedm, these look great to us.

Could the "e.g." in "General", "Operations," and "Legal rules" be replaced
with "such as" or "including" to make the language more clean/simple? Happy
to stick with "e.g." if you prefer (we don't feel strongly), but suggesting
these alternatives in case either works.

**Comment by upasna01** [comment]
Shorter text on hover will appear as below, changes are not implemented, its just been done locally.
Please provide your feedback if any changes required. Also Please update text for the hover link in the spreadsheet.

https://docs.google.com/spreadsheets/d/1Mn9hlhvqObC6MFOylkqRuN9gYpNfCCTGYnRgiEkWUws/edit#gid=120714315

![22](https://cloud.githubusercontent.com/assets/11477899/17137024/72bc5722-5358-11e6-9410-4eda940fa6d7.png)

**Comment by hello-deepak** [comment]
@SamCCSI @jedm 
Please update the [doc](https://docs.google.com/spreadsheets/d/1Mn9hlhvqObC6MFOylkqRuN9gYpNfCCTGYnRgiEkWUws/edit#gid=0) for hover text.

**Comment by charlesyoung** [comment]
Who is running with the ticket? 

cc @SamCCSI @anderspeders @jedm

**Comment by manishgs** [comment]
We have updated the [google sheet.](https://docs.google.com/spreadsheets/d/1Mn9hlhvqObC6MFOylkqRuN9gYpNfCCTGYnRgiEkWUws/edit#gid=1451295701) Each sheet represent the single webpage and "global" sheet for the hover text which can be found in multiple pages.

@SamCCSI @charlesyoung @jedm

**Comment by manishgs** [comment]
@SamCCSI @charlesyoung 
Could you please check the google sheet and let me know if we are ready to implement?

**Comment by SamCCSI** [comment]
1. There are still some square brackets that need to be removed / replaced with correct text – @jedm is this something you can help with?

2. What about for OLC? Some of these comments refer to 'extractives projects' and have links to RC, so we need to have a separate spreadsheet for OLC.

3. This field from the "contract-view" tab can be deleted (unless @jedm feels differently?): *Page arrows and box	| Toolbar	| Go to a specific page of the contract*

**Comment by KaitlinCCSI** [comment]
From a quick scan, the only hover that seems to mention "extractives" is
the one for *Type of Contract *(which appears on two different types of
pages). If that's the case, then I have two alternative suggestions. Either:

1. We keep as is for RC (Different types of contracts can regulate
extractives projects. See glossary [
http://www.resourcecontracts.org/glossary]), and then for OLC we swap that
for "Different types of contracts can regulate land projects. See glossary [
http://www.resourcecontracts.org/glossary]" ; OR
2. We change "extractives" to "natural resource" and then can use the same
hover for both RC and OLC - "Different types of contracts can regulate
natural resource projects. See glossary [
http://www.resourcecontracts.org/glossary]"

I think I have a slight preference for #1 (distinct language) but would
also be fine with #2 if that is much easier.

**Comment by manishgs** [comment]
hover text which are listed on google sheet implemented on [staging](http://staging.resourcecontracts.org/).

**Comment by SamCCSI** [comment]
**Contract View page**

1. 
![image](https://cloud.githubusercontent.com/assets/12913915/21787937/0e0efbd0-d720-11e6-91be-ab45774e9e0f.png) – needs re-wording cc @jedm 

2. 
![image](https://cloud.githubusercontent.com/assets/12913915/21787956/1f436562-d720-11e6-97c4-b29c602aef43.png) – needs rewording

3. 
![image](https://cloud.githubusercontent.com/assets/12913915/21787976/3a0b468a-d720-11e6-84c5-4810e5b60e93.png) – I would remove this hover. If you want to keep it, the current text is wrong and should be changed to "All annotations" or something similar.

**Search results page**

4. 
![image](https://cloud.githubusercontent.com/assets/12913915/21788014/99b662cc-d720-11e6-95ba-a6cbe6000664.png) –
Needs rewording 

**Contract summary page**

5. Open Contracting ID hover not working

**Clipping**

6. 
![image](https://cloud.githubusercontent.com/assets/12913915/21788112/126145ac-d721-11e6-83c6-304df4aeef33.png) - 
Wording is different from spreadsheet

7. 
![image](https://cloud.githubusercontent.com/assets/12913915/21788122/1924c3dc-d721-11e6-9666-79d0590aba37.png) - wording is different from spreadsheet

**Comment by jedm** [comment]
By the way, do admins have access to the hovers, or can that be arranged? Would add efficiency and extensibility over time, instead of only having back-end editing.

**Comment by manishgs** [comment]
We have not created feature to update hover text from admin panel. Currently we have [google sheet ](https://docs.google.com/spreadsheets/d/1Mn9hlhvqObC6MFOylkqRuN9gYpNfCCTGYnRgiEkWUws/edit#gid=1451295701), where you can update the hover text.

@jedm @SamCCSI @charlesyoung 
Let us know if we need to create this feature.

**Comment by charlesyoung** [comment]
Thanks @manishgs 

Let's keep with the Google sheet updates for now. We can always look at an admin function at a later stage.

**Comment by charlesyoung** [comment]
@SamCCSI @jedm can we try wrapping this up in January?

**Comment by charlesyoung** [comment]
@SamCCSI what is still outstanding on this ticket?

**Comment by charlesyoung** [comment]
@jedm, will you have time to look at the queries relating to the hover wording?

**Comment by jedm** [comment]
Charles - is next week an acceptable time frame?

**Comment by charlesyoung** [comment]
No problem, thanks Jed!!

**Comment by charlesyoung** [comment]
@jedm just checking if you have had time to look at this ticket?

**Comment by jedm** [comment]
@charlesyoung and @manishgs - I have updated the Clippings tab of YI's spreadsheet with new text for hovers and a few revisions to old text. Please see next comment for related questions about Clips functions and UX/UI.

**Comment by jedm** [comment]
Questions/requests re Clips features/UI:

1. In any Contract page, if user has selected ALL CLIPS in left column, the link that says “Clip All” at top of left (Annotation) column should change to “Clear All” not “Clip All”

2. In All Clips page, link that says “Clear All Clips” should be changed from:
**[black clip icon] Clear All Clips**
to
**Clear All [orange clip icon] [checkmark]**
This will make it consistent with the same function on Contract view page

3. For All Clips page, we had requested an option to download the XLS with clips list AND a PDF bundling all relevant contracts in a single download (eg, Zip file). Was this option eliminated? 

4. If answer to 3. is Yes, what does PDF option under Download do? (See same question in google sheet)

5. In All Clips page, Share icon is a disk. Very confusing. Please change to usual Share icon.

6. Change Share button from "Share Clips" to "Share"

7. For All Clips page, what happened to "SELECT" column? Has it been replaced by Trashcan? Trashcan function is much more permanent. Please confirm YI, NRGI, CCSI all agree this is best.

8. If Trashcan function is final functionality, please change Trashcan icon to an "x" icon with a similar style to PDF icon and other site icons. (see [a couple of examples here](http://fsymbols.com/thumbs/76.png)) Trashcan is confusing since user is deselecting, not deleting.

9. Change last column title from "Actions" to "Action"

10. For warning dialog boxes:
- in box “Are you sure you want to clear all clips?”, capitalize “Clips”
- in box “Are you sure you want to remove the Clip?”, change last two words to “this Clip” and add sentence "This action cannot be undone."

**Comment by manishgs** [comment]
@jedm 

1. fixed.
2. fixed.
3 & 4. PDF renamed to Zip which will download PDF bundle and xls file
5. fixed
6. fixed
7 & 8.  We've removed the trash icon as individual annotation can be removed by using select checkbox.
9. action column renamed to view.
10. fixed.

**Comment by charlesyoung** [comment]
Thanks @manishgs 

@jedm can we close this ticket and create a new one for additional requirements?

**Comment by jedm** [comment]
Before we close, please:

- change Clip icon in main toolbar to BLUE not ORANGE when Clipping is on (see attached)

- confirm that hover requests in Google spreadsheet have NOT been implemented. If YI has implemented these, then please confirm because some are not correct.

Thanks.
![screen shot 2017-03-27 at 11 41 57 am](https://cloud.githubusercontent.com/assets/2153664/24372811/0f41710e-12e4-11e7-91af-6cab5fa48736.png)

**Comment by manishgs** [comment]
change Clip icon in main toolbar to BLUE not ORANGE when Clipping is on (see attached)
- fixed and deployed on live

confirm that hover requests in Google spreadsheet have NOT been implemented. If YI has implemented these, then please confirm because some are not correct.
- We haven't implemented hover text so We'll address this feature in coming sprint.

**Comment by jedm** [comment]
@anjesh @charlesyoung Do you know if the hovers deployed on live above are still working? @SamCCSI and I did some initial testing as we plan for new hovers on OLC, and we cannot recreate the hover behavior.

**Comment by man-git007** [comment]
@charlesyoung Will it be OK if we get back to you on 18th Oct? As we are on a festival holiday.

**Comment by charlesyoung** [comment]
@SamCCSI are you happy that we look at the hovers. Doesn't seem to work on the prod site anymore. 10 hours are required from YI.

**Comment by charlesyoung** [comment]
@sriza can you work on this issue?

**Comment by sriza** [comment]
@charlesyoung 
We are currently working on this issue. We will inform you soon once the tasks related to this issue are completed.

Thank you

cc @rumus007

**Comment by sriza** [comment]
@charlesyoung 
The changes related to this issue are deployed to the staging site. Please have a look and let us know if they are ok.

Thank you

cc @man-git007

**Comment by charlesyoung** [comment]
Is below the table where the text is pulled from? Is it a dynamic update or is it done manually when text needs to change? 

https://docs.google.com/spreadsheets/d/1Mn9hlhvqObC6MFOylkqRuN9gYpNfCCTGYnRgiEkWUws/edit#gid=868617927

**Comment by sriza** [comment]
@charlesyoung 
The texts in the hover are taken from the [spreadsheet](https://docs.google.com/spreadsheets/d/1Mn9hlhvqObC6MFOylkqRuN9gYpNfCCTGYnRgiEkWUws/edit#gid=868617927). They aren't updated dynamically but are changed manually in the system.

cc @man-git007

**Comment by charlesyoung** [comment]
Couple points. 

1. Just checking that where relevant this is also applied to OLC?
2. I did text updates in the xls so please update where required
3. I don't see some of the hover text, like for clipping, in the xls on the site
4. The box size should fit the text 
![image](https://user-images.githubusercontent.com/13888372/141967031-ac2dd0fb-57f2-4e64-90c1-5a3e39d10c7b.png)
5. Some of the text is cut off
![image](https://user-images.githubusercontent.com/13888372/141968072-afe8bd43-f29f-4d72-b20e-2baf18d96264.png)

cc @SamCCSI

**Comment by charlesyoung** [comment]
@sweta-shrestha just confirming that you are looking at this issue?

**Comment by charlesyoung** [comment]
@sweta-shrestha just confirming that you are looking at this issue?

**Comment by sriza** [comment]
@charlesyoung 
We have updated the hover text as per the excel sheet and the changes are also applied to the OLC site. These changes are now deployed at the RC and OLC staging sites. Please have a look and let us know if they are ok.

Thank you

cc @man-git007

**Comment by charlesyoung** [comment]
Thanks, please move to Prod.

**Comment by sriza** [comment]
@charlesyoung 
The changes related to this issue have been deployed to the production site. Please verify.

Thank you

cc @man-git007

**Comment by charlesyoung** [comment]
Thanks

**Comment by SamCCSI** [comment]
I'm still not seeing hovers on OLC -- should they be live now? I tried in an incognito window in case it was a caching issue.

**Comment by SamCCSI** [comment]
Update; they are visible now. Many thanks
