### ISSUE TITLE
Cannot review contract text

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#222]
![cannot review contract text - is this related to fact that text is structured](https://cloud.githubusercontent.com/assets/1101585/9496231/50550590-4bdd-11e5-9b71-6d7d9c35b556.JPG)

**Comment by anderspeders** [comment]
Now checked a few contracts. None seems accessible.

**Comment by anjesh** [comment]
Correct, it was disabled for a while. The review-text interface is now updated to reflect that of annotate interface. The review-text link is now working, but there's some bug in there which injects some extra line breaks while rendering.

**Comment by anjesh** [comment]
There's still minor bug while saving. It injects extra line breaks. Moving to Sprint 8.

**Comment by anjesh** [comment]
This has been fixed, now new UI will be placed.
