### ISSUE TITLE
Annotation numbering

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#225]
How does the annotation numbering work? Nr. 1 is for 'Fundamental provisions' while there are annotation items above it. 'Summary of terms' has a 'II' leading the text. 

![image](https://cloud.githubusercontent.com/assets/13888372/9546690/1e5aa48c-4d95-11e5-93dd-4cc589c4b2b2.png)

**Comment by anjesh** [comment]
This is the numbers as provided in the list. If needed we can discuss https://github.com/NRGI/resourcecontracts.org/issues/565
