### ISSUE TITLE
Some letters not recognized in Mech Turk

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#227]
![letters in mech turk](https://cloud.githubusercontent.com/assets/1101585/9580198/fed6b01e-4fc5-11e5-9c79-5f654947218f.JPG)

**Comment by anjesh** [comment]
This seems to be problem with MTurk. When i downloaded the assignment from the Mturk, it shows 

![image](https://cloud.githubusercontent.com/assets/120488/9759744/18218dd2-570f-11e5-976d-3c8a6fb8bb22.png)

@byndcivilization it appears that this is unicode problem, and MTurk should have handled that. Thoughts?

**Comment by anjesh** [comment]
@manishgs lets see if there's to do anything with utf-8 in the form itself, or while sending to Mturk for saving.

**Comment by anjesh** [comment]
We have enabled utf-8 in the task form, hopefully such problem shouldn't appear if that's the utf-8 problem. We can't do anything with the text we have received from Mturk, will have to fix those letters manually.
