### ISSUE TITLE
Create glossary feed list

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#23]
Solution: Create a glossary list, which can serve as explainers for the tags/annotation fields which are considered common and important: 
- https://www.documentcloud.org/documents/563543-guide-to-contract-terminology-oil-amp-gas.html
- https://www.documentcloud.org/documents/563542-guide-to-contract-terminology-mining.html

**Comment by anderspeders** [comment]
revising this issue:  

The user story: 
When a user glance over a tagged item - a pop-up text will appear explaining the term, for example "a stabilization clause". 

There seems to be two options: 

1) The glossary is assigned to all annotation tags

2) There is also the option that this is simply based on a term appearing in the text - and thus not related to the limited number of annotation tags. This would simply be based on automated text search.

@byndcivilization any thoughts about the implementation?

**Comment by anderspeders** [comment]
We now have a finalised glossary list where several titles represent either a *metadata field* or an *annotation tag*.

https://docs.google.com/spreadsheets/d/12UCQA422r5Dg3wruUmYHL2SCLdDrlesCPcm2tHD8Yu4/edit#gid=495547183

I suggest that we consider how these types of text summaries + source can be included in the front end application and in the annotation view. 

Something to consider for an upcoming sprint.

**Comment by anjesh** [comment]
Closing this as glossary ready. This is linked to #22 for implementation.
