### ISSUE TITLE
Add additional information to contract list

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#230]
![add info to contract list](https://cloud.githubusercontent.com/assets/1101585/9608131/c8a5c25c-509a-11e5-8373-c10739c654e8.JPG)

Add info: 
- the contract has annotations --> add "Annotated"
- Signatory date
- Type of contract 
- Type of commodity

**Comment by anjesh** [comment]
This is how it appears now.
![image](https://cloud.githubusercontent.com/assets/120488/9813523/efa6fc82-58a5-11e5-9169-4368d222e3bf.png)
