### ISSUE TITLE
UI - Is operator - from 1 --> Yes

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#231]
![image](https://cloud.githubusercontent.com/assets/1101585/9608270/9cf888e6-509b-11e5-926f-bd63539b1e2f.png)

Please correct Is operator to: 
- "Yes" if affirmative
- "No" and
- [blank] if no information is available

**Comment by anjesh** [comment]
Now we have checkbox for operator field - which can have either yes or no (no = not available). We won't know whether it's No or Blank with the current setup. 

![image](https://cloud.githubusercontent.com/assets/120488/9677365/c143a082-52f8-11e5-8cae-78a87c06bf51.png)

We need to update this field to include radio-button with 3 options 
* Yes
* No
* Not Available (which is selected by default).

**Comment by anjesh** [comment]
Fixed in admin and also reflected those changes in the API, and subsite.

![image](https://cloud.githubusercontent.com/assets/120488/9876372/73695fd8-5bd5-11e5-92ab-bac6e2654c85.png)
