### ISSUE TITLE
Add data fields to the "Contract Quality Issues" section

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#233]
All metadata fields and annotations categories should essentially be available from the contract quality overview page. An overview using the current format might still work - as it is helpful for direct file export as well.

**Comment by anjesh** [comment]
Need to missing metadata fields (which are not currently captured because they are array). 
Company
Concession
Now Government Entity (Once it becomes array)

The annotations full categories are present, need to add some indentation.

**Comment by anjesh** [comment]
The missing fields (company, concession) are part of the quality list. Full annotation categories also present.
