### ISSUE TITLE
Contract comparison view

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#234]
Contract comparison now excist as a feature, but there is no selection method: 
http://rc-site-stage.elasticbeanstalk.com/rc/public/contract/1006/1006/compare

User story: 
As a user I would like to compare two contracts in **Country=Sierra Leone,Kenya** with **Resource=gold** where the **annotation category=stabilization clauses** is available

**Comment by anjesh** [comment]
@anderspeders I thought of bringing in annotation panel in a different way, rather than having it as a third panel on the left side.

When the user chooses the contracts in the search view and clicks compare, the contracts will be displayed as follows - side by side.

http://easier.cc/view/e731b335
![image](https://cloud.githubusercontent.com/assets/120488/9936996/5e98636a-5d7e-11e5-8dc9-5f43c70b4b07.png)

There's button at the top "compare annotations" - which then opens a new window with the list of annotations categories and annotations for each contract side-by-side. Clicking on the category will then open up the particular page in the contracts. We will ofcourse need to find the proper wording in both pages. 
http://easier.cc/view/a4b1264e
![image](https://cloud.githubusercontent.com/assets/120488/9937048/a706ad50-5d7e-11e5-8d1e-b5c72a4f63ef.png)

cc @anjhero

**Comment by anjesh** [comment]
@anderspeders 
Contract selection for comparison is now put in search results place. The comparison takes to the previous comparison UI for now. 

![image](https://cloud.githubusercontent.com/assets/120488/10018418/45ed3116-6156-11e5-89a3-381610279152.png)

**Comment by anderspeders** [comment]
Thanks, much appreciated

On selected view in **advanced search**: looks ok - I will circulate

On the compare view... will there be options to compare both: 
- content
- annotations

Currently it seems that annotations is the only compare option?

**Comment by anderspeders** [comment]
![image](https://cloud.githubusercontent.com/assets/1101585/10018906/293e2bb8-6108-11e5-9ffb-a6cd41d89ac3.png)

Correct spelling: "Compare contracts - instead of "Contracts Compare"

**Comment by anderspeders** [comment]
Thanks @anjesh for the deployment, 

This looks promising as *a first step* for later iteration. 

For the upcoming OLC launch I would request that we take the feature off the site as it will still need additional work. This will allow us to focus on other key iterations needed. 

Once the comparison feature is de-deployed you can close the ticket and we will review in sprint 10 or later.

**Comment by KaitlinCCSI** [comment]
Comparison function is not supposed to be on OLC when it launches, and should not be deployed until better functionality is built, per comment above. Comparison function is currently still on OLC.

Note that comparison function should not be deployed on OLC until it has been improved - I don't know what that means in terms of workflow, but once OLC is live, putting up early prototypes that need multiple adjustments would be a problem. Would be best to work on it in a way that doesn't affect live OLC site until we've agreed on parameters of this feature and tested it out, perhaps on the alpha Resource Contracts site before RC re-launch.

![screen shot 2015-10-06 at 5 53 11 am](https://cloud.githubusercontent.com/assets/14825437/10306791/ff874a74-6bee-11e5-8ea3-42af99380981.png)

**Comment by KaitlinCCSI** [comment]
@anderspeders @anjesh I don't want to change this to sprint 9, but removing comparison function from OLC should be done now, in sprint 9.

**Comment by anjesh** [comment]
Comparison function checkbox hidden

**Comment by anderspeders** [comment]
What is the status here - can we have a check in on this feature?

**Comment by KaitlinCCSI** [comment]
Also curious about this - haven't seen any further discussion about user needs/user stories and how comparison function will address these.

**Comment by SamCCSI** [comment]
Hi @anderspeders and @anjesh, any updates on the status of this feature?
Thanks,
Sam

**Comment by anjesh** [comment]
Before closing this, can we say that we can use clipping to get somewhat contract comparison feature?

**Comment by jedm** [comment]
This will depend on the UI and UX of the "view" features in Clipping list (as described here: https://github.com/NRGI/resourcecontracts.org/issues/861#issuecomment-211205483)

Clips responses coming in the next 48 hrs.

**Comment by charlesyoung** [comment]
@jedm can this ticket be closed?

**Comment by jedm** [comment]
Yes.
