### ISSUE TITLE
Contract upload failed

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#235]
![image](https://cloud.githubusercontent.com/assets/1101585/9631425/ca38c592-514e-11e5-89de-43fcc1a662cb.png)

**Comment by anjesh** [comment]
This pdf is encrypted so we couldn't do the processing and hence failed. Now we are showing the reason for fail as well.

![image](https://cloud.githubusercontent.com/assets/120488/9878335/d76e617a-5be1-11e5-8073-9d163706c207.png)

The pdf download link doesn't work now, we will see that. 

Here's the original pdf http://www.laohamutuk.org/Oil/PSCs/JPDA03-12.pdf and it asks password when you try to export it.

**Comment by anjesh** [comment]
We can't anything with this pdf, unless we get an unencrypted one. @anderspeders

**Comment by anderspeders** [comment]
Thanks,  

@charlesyoung: We should note in the Admin guide that encrypted PDFs cannot be loaded. 

Closing this ticket.

**Comment by anjesh** [comment]
More encrypted contracts
http://resourcecontracts.elasticbeanstalk.com/contract/960
http://resourcecontracts.elasticbeanstalk.com/contract/959
http://resourcecontracts.elasticbeanstalk.com/contract/1062

cc @anderspeders

**Comment by charlesyoung** [comment]
Encrypted comment added to the admin guide.
