### ISSUE TITLE
Pinning - not fully implemented

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#236]
As a user it is unclear how I can use pinning. It does not appear to be implemented.

![image](https://cloud.githubusercontent.com/assets/1101585/9632252/20167a36-5154-11e5-8807-b605cfaf1ac1.png)

**Comment by anjesh** [comment]
Lets disable/hide pinning for the time being until the contract view UI is fully complete and stable.

**Comment by KaitlinCCSI** [comment]
Agree with hiding pinning. Would not turn to it until at least sprint 10.

**Comment by anjesh** [comment]
Pinning will be addressed in this issue https://github.com/NRGI/resourcecontracts.org/issues/116
Duplicate.
