### ISSUE TITLE
Contract primary view is contract page - not summary page

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#238]

**Comment by anjesh** [comment]
Can you explain a bit here?

**Comment by anderspeders** [comment]
As a user I would like to get to the contract view (not the summary page) when I leave the contract list to look at a contract: 

![moving from contract list](https://cloud.githubusercontent.com/assets/1101585/9656252/ea938d0c-5204-11e5-9c00-bed1326cfb2c.JPG)

**Comment by anjesh** [comment]
The contract list page takes the contract to contract-view with pdf default.
