### ISSUE TITLE
Develop database structure

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#24]
The database structure will have the following tables. These are the primary tables and primary fields. We are using PostgreSql Json datatype to store the metadata of the contract and the annotations. The database will change as we get more requirements. The use of json datatype will minimise the risk of changing database.

Table: *contract*

Field Name | Data Type | Remarks
--------------- | -------------- | -------------
id | INT | 
metadata | JSON | Need to define the json content see #25 
file | TEXT | link to the pdf file in the S3
filehash | VARCHAR (100) | SHA1 of the pdf file 
created_datetime | DATETIME | 
last_updated_datetime | DATETIME | 
user_id | INT |  created_by user

Table: *contract_pages*

When the contract pdf document is processed, it's split into individual pages and named according to the page number. We can easily access the page file based on the page number. 

Field Name | Data Type | Remarks
--------------- | -------------- | -------------
id | INT | 
contract_id | INT | 
page_no | INT | Page number of the page (starts with 1 to the total number of pages)
text | TEXT | text/html content of the pdf page
created_datetime | DATETIME | 
last_updated_datetime | DATETIME | 

Table: *annotations* 

Field Name | Data Type | Remarks
--------------- | -------------- | -------------
id | INT | 
contract_id | INT | 
annotation | JSON | Details of the annotation (containing the position, and other details) http://docs.annotatorjs.org/en/v1.2.x/annotation-format.html
created_datetime | DATETIME | 
last_updated_datetime | DATETIME | 
user_id | INT | created_by user

**Comment by anjesh** [comment]
@byndcivilization your view?

**Comment by byndcivilization** [comment]
Hi yeah sounds good, just want to make sure you're doing some sort of light schema work on the JSON type. With mongo this would be with Mongoose models. I know there is a similar methodology in Postgres but from what I remember it takes a bit more work to get it right.

**Comment by anderspeders** [comment]
This has completed. We expect iterations during sprint 2 based on user feedback.
