### ISSUE TITLE
Introduce "Publish all button" - for metadata, PDF text and annotation

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#240]
Currently the publication of metadata and contract text involves several steps: [draft], [complete] and [publish]. 

Options: 
A) Remove [draft] level
B) Enable a Publish all button - for each contract covering metadata, PDF and annotation

**Comment by anjesh** [comment]
We will have "Publish all" on top of the existing workflow. 

The existing workflow will remain as it is and will be followed whenever needed.

**Comment by anderspeders** [comment]
Sounds like a great solution. Please push this through asap.

**Comment by anjesh** [comment]
Right now we have put the button "Publish all". Please understand the UI for admin still needs to be updated.

![image](https://cloud.githubusercontent.com/assets/120488/9809822/52da99b4-588b-11e5-9818-df765824ae4b.png)
