### ISSUE TITLE
Add proper AMLA field in contract summary page

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#242]
![image](https://cloud.githubusercontent.com/assets/1101585/9642706/bfe6e154-518b-11e5-85bf-d7bdd0260ad4.png)
 
African Mining Legislation Atlas
"Legislation for "[Country] in African Mining Legislation Atlas"

**Comment by anderspeders** [comment]
The current overview is not intuitive

**Comment by anjesh** [comment]
Lets put the following text below the Country name "See <link to amla>Legislation</a> in African Mining Legislation Atlas"

**Comment by anderspeders** [comment]
Sounds excellent, 

Can we disable this for OLC and for non-african countries in RC?

**Comment by anjesh** [comment]
This is how it appears in RC 
![image](https://cloud.githubusercontent.com/assets/120488/10041753/47ab113e-6206-11e5-9f54-1451a3fa3e3b.png)

And It doesn't show in OLC.
