### ISSUE TITLE
Add disclaimer on OCR-processed text

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#244]
![image](https://cloud.githubusercontent.com/assets/1101585/9645917/eebdd1de-519c-11e5-9a3e-4fc4c5d5648e.png)

Suggested text: 
"This text was generated from the PDF-contract through optical character recognition. We can therefore not guarentee that spelling and text formats will be fully consistent with the original PDF-version."

**Comment by anderspeders** [comment]
If you are not close to completing this - I would suggest a new location: 
![image](https://cloud.githubusercontent.com/assets/1101585/10022314/2e934014-611a-11e5-99c9-79bf7867d0ad.png)

**Comment by anderspeders** [comment]
I am still to provide text for this.

**Comment by KaitlinCCSI** [comment]
The OCR disclaimer text that appears underneath the document when text view is selected (per Anders's screenshot) should say: 

![image](https://cloud.githubusercontent.com/assets/14825437/10114805/1a1116c0-63bd-11e5-9904-a54da27a599f.png)

"Learn more ..." and "Apprendre plus ..." should both be hyperlinked to the part of the FAQs page that explains the OCR text. Is this type of anchor link possible?

We know that it is not ideal to include this in both English and French, but because the French versions of the OCR text are particularly problematic, we think it's important to have this short disclaimer also available in French. The longer description in the FAQ will only be in English. It will say:

![image](https://cloud.githubusercontent.com/assets/14825437/10114815/75d8615c-63bd-11e5-9a66-530b505ee0d0.png)

cc @jedm @samccsi

**Comment by jedm** [comment]
Would advise only English disclaimer with Learn more and Apprendre messages at end, to indicate that les Francophones auront plus des nouvelles après. 

Then we could revisit after the internationalization features are in place.

**Comment by KaitlinCCSI** [comment]
Okay, so the following?

This contract's text was created automatically and may contain errors and
differences from the contract's original PDF file. Learn more … *Le texte
de ce contrat a été créé automatiquement et peut contenir des erreurs et
des différences en relation à l'original PDF du contrat. *

On Fri, Sep 25, 2015 at 7:46 PM, jedm <notifications@github.com> wrote:

> Would advise only English disclaimer with Learn more and Apprendre
> messages at end, to indicate that les Francophones auront plus des
> nouvelles après.
>
> Then we could revisit after the internationalization features are in
> place.
>
>
>
> > On Sep 25, 2015, at 5:42 PM, KaitlinCCSI <notifications@github.com>
> wrote:
> >
> > The OCR disclaimer text that appears underneath the document when text
> view is selected (per Anders's screenshot) should say:
> >
> >
> >
> > "Learn more ..." and "Apprendre plus ..." should both be hyperlinked to
> the part of the FAQs page that explains the OCR text. Is this type of
> anchor link possible?
> >
> > We know that it is not ideal to include this in both English and French,
> but because the French versions of the OCR text are particularly
> problematic, we think it's important to have this short disclaimer also
> available in French. The longer description in the FAQ will only be in
> English. It will say:
> >
> >
> >
> > cc @jedm @samccsi
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/244#issuecomment-143385007>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PlAK95h&m=b845c3568c64&t=20150925&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PlAK95h&m=b845c3568c64&t=20150925&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01PlAK95h&m=b845c3568c64&t=20150925&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by jedm** [comment]
No. 

This contract's text was created automatically and may contain errors and differences from the contract's original PDF file. Learn more … *Apprendre plus ...*

**Comment by jedm** [comment]
Or 

This contract's text was created automatically and may contain errors and differences from the contract's original PDF file. Learn more … *[French word for 'note' or 'warning'] en français ...*

**Comment by KaitlinCCSI** [comment]
Oh, okay. First suggestion doesn't make sense to me -- ideally French disclaimer should be next to the French OCR. If not, I don't think it helps to have "Apprendre plus ..." only in French, with it linking to an English explanation. 

For your second suggestion, do you mean: This contract's text was created automatically and may contain errors and differences from the contract's original PDF file. Learn more … *Attention!* ? That also seems a bit strange, particularly b/c "warning" in French just reads as "attention" in English. 

If this is too complicated, let's just drop the French translation, given other more pressing concerns. I'm just a bit concerned that Francophone users of the site might come across these documents in French without the warning -- particularly given that our MT translations can't handle French accents, replacing them with symbols, so there are numerous errors in each French text. But not worth scratching our heads over too long in this sprint.

**Comment by anjesh** [comment]
I have included the disclaimer in the top of the text, which can be closed by the user. For the text, i have used "This contract's text was created automatically and may contain errors and differences from the contract's original PDF file. Learn more" for now. This can be changed later once we are decided. 

![image](https://cloud.githubusercontent.com/assets/120488/10133810/2edc8df6-6600-11e5-88a1-c40ed54566f0.png)

**Comment by KaitlinCCSI** [comment]
Thanks. I prefer this placement at the top to placement at the bottom as we had described, at least for the near future. @jedm - Are you okay with this?

**Comment by jedm** [comment]
A couple of adjustments:

- The most recent request was for this warning to appear when user hovers on the TEXT switcher in top bar, not as a permanent text block. However if others are fine with it here then I am too. 

- Now that I see it, we should remove the word "contract's" and just say "The text below was created ... etc" This will help avoid the promise that the text below IS the contract text. 

- Why is the box pink? I understand the need to highlight the warning, but the page does not seem to have a consistent color palette. Is there a design template with a set color scheme that we are working from?

**Comment by KaitlinCCSI** [comment]
- I'm fine with this box being here rather than as a hover, particularly since it can be closed by the user if they don't want to see it. And I think it seems less messy to have fewer hovers.

- Agree that we should delete "contract's" and just say "The text below was ..."

**Comment by anderspeders** [comment]
@anjesh, 

To summarize: Please replace the current text with the following: 
"The text below was created automatically and may contain errors and differences from the contract's original PDF file. Learn more."

**Comment by SamCCSI** [comment]
Please replace the disclaimer with the following text:

**While such text will be of use to some users – for example, those who seek to search within contract text – the text may contain errors and differences from the contract’s original PDF file. Learn More.**

"Learn more" should link to http://www.openlandcontracts.org/faqs or to an appropriate anchor link if that is implemented, as per @KaitlinCCSI 's recent request.

**Comment by SamCCSI** [comment]
Previous entry updated to include RC and OLC links

**Comment by anderspeders** [comment]
Assigning to sprint 13.

**Comment by SamCCSI** [comment]
Apologies -- I have again updated the above wording of the disclaimer in my second last previous entry.

**Comment by KaitlinCCSI** [comment]
(Anchor link requested here: https://github.com/NRGI/resourcecontracts.org/issues/638)

**Comment by sadhakbj** [comment]
Related to https://github.com/NRGI/resourcecontracts.org/issues/638
