### ISSUE TITLE
Setup centralized monitoring of different services 

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#247]
There are various components and services that need to be checked for the proper working of the NRGI system, API, it's subsites. We will setup a centralized service monitoring of the system so that any system outage could be notified for quick action. 

The following services will be monitored. 

NRGI System
* PostgreSQL
* Apache
* Supervisord
* Beanstalkd
* 6 queues at various stages (these queues are developed to free the main app from waiting) 
 * Pdf Processing queue
 * Elasticsearch Index queue
 * Email queue
 * MTurk HIT creation queue
 * Open Oil CSV import queue
 * Open Oil Contract Insert queue
* Monitor the following external services if they are up or not (though we can't do anything if they goes down)
 * Abbyy
 * S3
 * Mturk

Supervisord will be configured to monitor all other services, so that it will restart if one of these goes down. 

Elasticsearch System
* Supervisord
* Elasticsearch
* Apache for API

Subsites
* Apache
* These subsites will display appropriate error message if the API stops working for some reason (like crashing of ES) to inform users to notify admin if they saw such outages before we handle them. 

Useful links
https://github.com/mlazarov/supervisord-monitor

**Comment by byndcivilization** [comment]
can we just use new relic for this?

There are also some AWS services to handle this.

**Comment by anjesh** [comment]
I want to ensure that all the required services are running without a hitch, we setup supervisord to monitor the services/queues and we can quickly see the status of the running services from this page. 

![image](https://cloud.githubusercontent.com/assets/120488/10093507/006cfa9e-6373-11e5-9538-fbd784a57c62.png)

But the plan is to move to new relic later. I have a new person looking at this, so this will not hamper our other work.

**Comment by anderspeders** [comment]
Moving to sprint 10. 

Not sure how much work is needed on this.

**Comment by anderspeders** [comment]
Is this synched with the work @jerico is working on to monitor the API stability and performance?

**Comment by jerico** [comment]
@anderspeders I used a separate service to monitor just the uptime of PH-EITI server and RC's API server. @anjesh's approached will give better information if something is not going right with the servers.

**Comment by anjesh** [comment]
This will be part of the overall documentation we will develop in sprint 13 #417
