### ISSUE TITLE
UI Metadata fields must be searchable by other types

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#249]
![image](https://cloud.githubusercontent.com/assets/1101585/9682497/215278b4-52d5-11e5-80a8-ec14193c4178.png)

If possible it would be helpful if the summary/metadata page would enable the user to click to other contracts for example by asking for all within a specific <Contract type>, <Resource> or <Corporate Group>.

**Comment by anjesh** [comment]
Selected fields are now linked.
