### ISSUE TITLE
Define contract metadata

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#25]
This issue is different from #24 as the metadata for the contract needs much discussion to finalize. The use of json store will minimise the change in database structure, except for the json schema for the metadata. Split from #19 as discussion for metadata will be different from annotation.

**Comment by anjesh** [comment]
The following fields could be taken for the start. Need further discussion to finalise the additional fields

Language
Country Code
Resource
Type of Mining Title
Signature Date
Signature Year
Contract Term (duration) in Years
Project Title

Other additional fields here https://docs.google.com/spreadsheets/d/1NlGeBxBW37mPyL4zRXveD7RKACCzPvMtvHfzgjS_afA/edit#gid=0

**Comment by byndcivilization** [comment]
Most of these types are probably self evident but some I just want to make sure we're clear on. Resource will be an array. Anders and I will need to check with CCSI but title type may also be.

**Comment by anjesh** [comment]
Lets finalize all the fields that we will be capturing with the codelist for any of these fields if any. 

Language: string (from codelist)
Country Code: string (from codelist) 
Resource: array (from codelist) (e.g. Copper,Gold,Silver,Molybdenum) 
Type of Mining Title: string? (Production Sharing Contract, Profit Sharing Contract) 
Signature Date: datetime 
Contract Term (duration) in Years: integer
Project Title: string

**Comment by anderspeders** [comment]
Have a look here for an updated metadata template: 
https://docs.google.com/spreadsheets/d/12UCQA422r5Dg3wruUmYHL2SCLdDrlesCPcm2tHD8Yu4/edit#gid=1329720090

cc @anjesh

**Comment by anderspeders** [comment]
The metadata templatre for sprint 1 is now confirmed (fields in light blue color):

https://docs.google.com/spreadsheets/d/12UCQA422r5Dg3wruUmYHL2SCLdDrlesCPcm2tHD8Yu4/edit#gid=1329720090

During sprint 2 we will gather user feedback and iterate.

**Comment by anjesh** [comment]
The defined metadata now updated in the form. Will continue this ticket for the sprint 2 metadata changes if any.

**Comment by anderspeders** [comment]
Closing this.
