### ISSUE TITLE
Front page: Left bar - not intuitive. Improve or drop

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#252]
![image](https://cloud.githubusercontent.com/assets/1101585/9683009/df53fc3a-52d9-11e5-8c2d-4b13a416f8cc.png)

I do not have a clear recommendation here but think we need to have a think about how to either improve or remove this.

**Comment by anjesh** [comment]
@anjhero , can we think of something where the main-page gets some shade when the menu is opened on the left.

**Comment by anderspeders** [comment]
What is the plan here?
