### ISSUE TITLE
Advanced search view: Autopopulate, clean up and add search categories

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#253]
![image](https://cloud.githubusercontent.com/assets/1101585/9683048/4efee64e-52da-11e5-90dd-89af67680b2f.png)

We need a much cleaner and intuitive advanced search. 

Search by: 
- Annotation categories
- Corporate group
- Resource
- Contract type

**Comment by LindseyAM** [comment]
Year, country, and resource should be the top 3 search fields in my opinion, with advance search including the annotation categories and other metadata.

**Comment by anjesh** [comment]
Added the new select fields.

![image](https://cloud.githubusercontent.com/assets/120488/9809939/474aa656-588c-11e5-8763-dae06050d56c.png)
