### ISSUE TITLE
UI - Annotations not linked or displayed in PDF

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#255]
![image](https://cloud.githubusercontent.com/assets/1101585/9683226/3641ce9e-52dc-11e5-9e95-72cd9141ab21.png)

At this stage it is difficult to comment as we are still far from having a viable product. Initiatially we will need a clear link between annotation and the actual PDF-page where it is rendered from.

This ticket is high priority.

**Comment by LindseyAM** [comment]
Just to add, the functionality that I am looking for as a user would be to eventually get to the point where I link from the annotation I am interested in (lets say the 'royalty' annotation), to the associated text of the contract i.e. the royalty clause. Eventually, I would want to build a list of royalty clauses (lets say I want to compare royalty clauses in contracts from Guinea and Liberia for a specific resource over a certain period of time). I would then want to be able to print /download my list of royalty clauses that includes the necessary information/metadata to find the contracts those clauses came from.  The first step is to link the annotations with the clause.  From what I understand, the quality of the text version of the contracts do not currently match the image version and this makes it more difficult to link the annotations to the clauses themselves. Ideally, I would at least like a link to the correct pages and then be able to isolate those pages.

**Comment by anjesh** [comment]
Fixed as part of the UI update.
