### ISSUE TITLE
Add full list of annotation categories

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#262]
Not all the upload categories are available on the site - currently only 59and not all 91 annotation categories.

@samCCSI: Could you paste the full list of the 91 annotation catgeories here to make sure we have the correct list?

**Comment by SamCCSI** [comment]
@anderspeders do you want them with their 'cluster category' (not an annotation category) included for ease of organization?

**Comment by SamCCSI** [comment]
Here is the full list, including cluster categories - eg. "General information"

![image](https://cloud.githubusercontent.com/assets/12913915/9691634/a0849716-5311-11e5-9051-c19f94f6b14c.png)

**Comment by SamCCSI** [comment]
Because that copied as an image, here is the link to the current version of the spreadhseet that has all these categories: https://www.dropbox.com/s/ztepuvn1kbj2u5h/NRGI_WB_CCSI_template_and_metadata_v4.5_020915%20%28no%20picklist%29.xlsm?dl=0

**Comment by anjesh** [comment]
The above list is updated in the codelist. The annotation interface lists all the categories maintaining the order.
