### ISSUE TITLE
UI Iteration - big picture

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#264]
https://drive.google.com/file/d/0B0itojFFyvjCZllONUV3Y0FRcVU/view?usp=sharing

**Comment by anjesh** [comment]
Can you have a look at these designs 
https://invis.io/HS450A579
![image](https://cloud.githubusercontent.com/assets/120488/9759806/8786e050-570f-11e5-8ba7-2952d5d40030.png)

https://invis.io/E8450ABUZ
![image](https://cloud.githubusercontent.com/assets/120488/9759801/80d3eb04-570f-11e5-8918-3bd5f124290c.png)

**Comment by anjesh** [comment]
The UI has been in place in the subsite. There are still few more items to be carried out in the UI.

* Print option
* Download pdf option
* Social media option (this will be carried out in different issue, it's not clear how and what to share from this option)
* Related documents links
* Highlight search words

Once these are complete, the same also needs to be implemented in the Admin interface with more functionality like annotating the text/pdf.

**Comment by anjesh** [comment]
The remaining features in this UI will be carried out in sprint 9.

**Comment by byndcivilization** [comment]
duplicate
