### ISSUE TITLE
Social media sharing button

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#265]
Sharing on social media: eg. a specific section or a specific annotation

**Comment by anderspeders** [comment]
Need update on sharing tools.

![image](https://cloud.githubusercontent.com/assets/1101585/9963209/1234d90c-5df8-11e5-8ee6-f6f2a5169474.png)

**Comment by anderspeders** [comment]
Adding this to sprint 9

**Comment by anderspeders** [comment]
This is marked ready. Is it deployed?

**Comment by anjesh** [comment]
No. "Ready" means ready to begin working.

**Comment by jedm** [comment]
If time permits, @anjesh , feel free to post a screenshot or sketch of the planned UI of share tools, in case we can save time and cycles by helping with comments before deployment.

**Comment by sadhakbj** [comment]
We have implemented and deployed the social sharing button on demo sub site. Please check once and give review.
![social_sharing](https://cloud.githubusercontent.com/assets/5828622/12610231/a614eaa4-c50e-11e5-9b83-6db9040c1a48.png)

**Comment by jedm** [comment]
In terms of visuals, would suggest the icons be the same height as the download icon and that they be grouped alongside the download icon for better IA.

Also, will this be implemented on mobile too?

Thanks for the preview. Assuming the tools will be global, it would be good to know where placement will be on other pages/page types.

Non-visual question: Do we definitely want GooglePlus? Maybe LinkedIn a better use of that space?

**Comment by KaitlinCCSI** [comment]
Can you also please provide preview of what will be shared -- A link to page user is viewing? With an image or not? Any default message? Anders' instruction was for sharing a specific section or a specific annotation, and I can't tell from visual how s specific section/annotation would be shared through these buttons, which don't seem to be linked to specific sections/annotations.

No preference on G+/LinkedIn.

**Comment by anjesh** [comment]
The social media button will share the link of the page - could be contract view link or the annotation link and pulls the image from the homepage ( in FB and G+) and meta info (in which we have put the contract title). What else do we need to share through these media?

**Comment by sadhakbj** [comment]
Sharing on facebook:

![fb_share](https://cloud.githubusercontent.com/assets/5828622/12634533/731534d0-c5a2-11e5-8a22-4e808204691f.png)

Sharing on Google Plus:

![google_share](https://cloud.githubusercontent.com/assets/5828622/12634565/d4288862-c5a2-11e5-870c-03c7c7b5f5d1.png)

- Both of the them link to: http://rc-site-demo.elasticbeanstalk.com/olc/public/contract/ocds-591adf-CD8594810060OL/view#/pdf/page/1/annotation/25809 i.e. the specific annotation of the specific page.

**Comment by KaitlinCCSI** [comment]
When I visit that link, I can't tell which specific annotation is being highlighted; it seems like it is just linking to a specific contract view page.

However, I don't have a strong opinion on how this should look, because I don't fully understand the user case here. Maybe @jedm or @anderspeders have further ideas on whether it is necessary or not to share a specific annotation, as opposed to just a specific contract page.

**Comment by anderspeders** [comment]
I do not have further suggestions here. I am happy to implement the above.

**Comment by jedm** [comment]
The icons are no longer showing at the above links from the demo site, but would still be good to see:

- all share/download tools next to each other for better IA
- sample of sharing link placement on other pages (eg Search results)
- sample of what text appears in a Twitter post when you click to tweet
- email option and sample of what the email looks like (eg, great opportunity for a footer message promoting RC/OLC and adding a homepage link)

**Comment by anderspeders** [comment]
This was marked as working on March 16th - @anjesh @manishgs Could you provide an update?

**Comment by manishgs** [comment]
Work has been done but icons are hidden for now.

**Comment by anderspeders** [comment]
Does this mena it has been deployed to demo?

I do not see it

**Comment by manishgs** [comment]
Please review share button. 
- [summary page](http://rc-site-demo.elasticbeanstalk.com/rc/public/contract/ocds-591adf-GE3090186372RC) 
- [contract view page](http://rc-site-demo.elasticbeanstalk.com/rc/public/contract/ocds-591adf-GE3090186372RC/view)
- [search page](http://rc-site-demo.elasticbeanstalk.com/rc/public/search?q=)

**Comment by manishgs** [comment]
closing this issue.

**Comment by jedm** [comment]
Suggest this not be considered done. Social icons are using a large amount of real estate and should be consolidated into one menu (similar to download option in search results). 

Also, where is email option?

Finally, it would be preferable to move these down lower, where they were in the layout provided for this page last year? Is that possible?

Thanks.

**Comment by hello-deepak** [comment]
Review social media sharing button in [demo](http://rc-site-demo.elasticbeanstalk.com/rc/public/) and provide feedback .

**Comment by jedm** [comment]
@hello-deepak Here are some first feedback and questions. More will come.

- Share, download and clip button display on Contract Summary page should be the same as button displays on Contract View page, as requested.

- Add code to include an image with Facebook posts

- Can RC/OLC teams edit the standard text in Tweets? It should include text such as " - from ResourceContracts - @NRGInstitute"

- Same question for email tool - need standard text in template - 1 sentence describing RC/OLC and a link to homepage

- Email popup is different between Summary and View page - should be the same

more to come

**Comment by hello-deepak** [comment]
@jedm 

> Share, download and clip button display on Contract Summary page should be the same as button displays on Contract View page, as requested.
Fixed.

>Add code to include an image with Facebook posts

We have included homepage image in Facebook and Google Plus .

> Can RC/OLC teams edit the standard text in Tweets? It should include text such as " - from ResourceContracts - @NRGInstitute"

Yes, you can edit the text .

> Same question for email tool - need standard text in template - 1 sentence describing RC/OLC and a link to homepage

Can you provide standard text to include in email template.

> Email popup is different between Summary and View page - should be the same

Fixed

**Comment by hello-deepak** [comment]
@jedm 
Can you provide standard text to include in email template .

**Comment by anjesh** [comment]
@charlesyoung can you please have a look at the share-in-email text and let us know the text to be updated.

**Comment by jedm** [comment]
_**Here is recommended text for the share email. @KaitlinCCSI please confirm OK.**_

_SUBJECT LINE:_
Link from ResourceContracts.org - [FIRST TWO WORDS OF DOC TITLE] ...

_BODY:_
Message from [SENDER EMAIL]: 

[BODY OF SENDER MESSAGE]

[URL]

---
This message was sent to you by [SENDER EMAIL] at [SEND TIME (INCLUDING TIME ZONE) AND DATE] via ResourceContracts.org, an annotated directory of petroleum and mineral contracts.

**Comment by KaitlinCCSI** [comment]
Looks great to me, though for OLC, please of course replace "ResourceContracts.org" with "OpenLandContracts.org" in subject line and at bottom, which should say "...via OpenLandContracts.org, a repository of investment contracts for agriculture and forestry projects."

(Also @jedm @anderspeders @SamCCSI , I wonder if you want more consistency with when RC uses "petroleum & mineral" and when it uses "oil, gas, and mining"? Both used on home page; not sure if that's necessary. Didn't notice it until I saw this suggested phrasing and took a closer look at home page.)

**Comment by jedm** [comment]
Good question for @charlesyoung re. consistency of language. @anjesh please go ahead and implement change to email template when appropriate. Thank you!

**Comment by manishgs** [comment]
Email template updated.

**Comment by charlesyoung** [comment]
As discussed I'm reopening the ticket.

**Comment by charlesyoung** [comment]
Also take a look at the Twitter share link. 

![image](https://cloud.githubusercontent.com/assets/13888372/20661095/93d1b272-b555-11e6-93c3-d0481d0df0b1.png)
