### ISSUE TITLE
Front page map: should correspond to countries with published contracts

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#267]
Several users have reported that the map does not correspond to the actual published contracts. Please clarify.

**Comment by anjesh** [comment]
It's a generic world map with some countries somehow selected. It was not intended to be used as a map of the contracts countries. So either we could change the map so as not to give that impression or create a clickable map. And that map is too small for interactivity. We need some good space to play with the map. 

Thoughts?

**Comment by anjesh** [comment]
We have removed the highlighted countries from the map so this shouldn't be a problem now. However later we can think of having a separate interactive country map for browsing contracts.
