### ISSUE TITLE
Metadata: Dealing with multiple companies as owners of contract

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#27]
As per current review of metadata: 
https://docs.google.com/spreadsheets/d/12UCQA422r5Dg3wruUmYHL2SCLdDrlesCPcm2tHD8Yu4/edit#gid=1329720090

How to deal with for example this contract: 
http://www.resourcecontracts.org/#documents?countries=ghana&document=439271-the-shallow-water-tano-contract-area

- where to companies are registered as owners?

I wonder if we can have multiple company entities available for adding?

cc @byndcivilization

**Comment by anjesh** [comment]
example?

**Comment by anderspeders** [comment]
http://www.resourcecontracts.org/#documents?countries=ghana&document=439271-the-shallow-water-tano-contract-area

"Tullow Ghana Limited, a Jersey company, and Sabre Oiland Gas Limited, a UK company (jointly referred to as "Contractor")"

**Comment by anderspeders** [comment]
Any thoughts @byndcivilization ?

**Comment by anderspeders** [comment]
@anjesh another example: http://repository.openoil.net/wiki/Iraqi_Kurdistan

In general quite commons that multiple companies appear on one contract.

**Comment by byndcivilization** [comment]
You should just be able to store that field as an array instead of a discrete value right? Similar to the way we're handling resource type.

**Comment by anderspeders** [comment]
But each company will need to have multiple metadata fields assigned right?

Company identifier, etc... (about 7 fields in total for each company name). 

Would that still work?

**Comment by anjesh** [comment]
Currently the company is stored as an array field, just need to add the "Add more" functionality in the form.

**Comment by anderspeders** [comment]
Great, let us include: 

**"Add another company"**
