### ISSUE TITLE
Compare contracts from advanced search

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#273]
![image](https://cloud.githubusercontent.com/assets/1101585/9717875/77ce72e4-5544-11e5-9220-cec69c78e76c.png)

**Comment by anderspeders** [comment]
![image](https://cloud.githubusercontent.com/assets/1101585/9762807/cb0c434c-56d3-11e5-992a-fbf236532cda.png)

Can we have a search result from the **searched annotation category** appear underneath the title of the contract?

**Comment by anjesh** [comment]
The search from annotation category is now included in the search results. The comparison feature will be implemented in this https://github.com/NRGI/resourcecontracts.org/issues/234
