### ISSUE TITLE
Associated Documents

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#274]
Can the list of associated parent and supporting documents be listed alphabetically.

**Comment by anjesh** [comment]
Makes sense.

**Comment by anjesh** [comment]
Done.

**Comment by charlesyoung** [comment]
This doesn't seem to have been done yet.

**Comment by anjesh** [comment]
Thought the listing of the contracts in the contract view page. The list is also sorted in the contract add page.
