### ISSUE TITLE
Mechanical Turk Completed/Pending/Approved

### ISSUE THREAD

**Issue by byndcivilization** [NRGI/resourcecontracts.org#277]
This terminology is a bit confusing since HITS are couted as completed before being approved and as pending before being submitted.

Bigger problem is that HITS completed count seems to be broken. "Mauritania Contrat de Partage de Production Entre La Republique Islamique de Mauritanie et International Petroleum Grouping (Block 11)" shows 0 completed on main paige but 7 completed and waiting for approval on detail page.

**Comment by anjesh** [comment]
https://github.com/NRGI/resourcecontracts.org/issues/632 address the above issue as well. The difference is due to the api calls made when the page is viewed. Now the API call is made once every day and email is sent to notify the users of the current status of the Mturk tasks.
