### ISSUE TITLE
UI for small tablets / mobile?

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#278]
Do we know how response the site will be for smaller devices?

**Comment by anjesh** [comment]
Most of the pages are now responsive, they don't break and re-structure the information/data accordingly, except for the contract-view page, which has too many information/blocks. Need to work on that page. 
Try resizing the browser in different pages to see.

**Comment by anjesh** [comment]
The response for the pdf-text view page needs to be fixed - there are related issues https://github.com/NRGI/resourcecontracts.org/issues/278 
Closing this as the rest of the pages are responsive.
