### ISSUE TITLE
ISO 3166-2 or ISO 3166-3

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#28]
Suggestion from Chris Taggart: 

"Suggest changing to "jurisdiction of incorporation" for clarity. Also by ISO 3166-2 / 3 do you mean 3166-2 Alpha 3. The trend we've seen is on standardising to 3166-2 Alpha 2, which has the advantage of mapping closely to top level domains, and also makes linking with OpenCorporates easier ;-)"

Thoughts @byndcivilization

**Comment by anderspeders** [comment]
Another vote for 3166-2 from Tim: 
"ISO-2 would be my preference (used by open corporates, OCDS, IATI etc...)"

**Comment by byndcivilization** [comment]
i like both. ISO3 is easier to read but you should really not need to read it anyways so.. I also take he point on TLD that I hadn't considered.

**Comment by anderspeders** [comment]
Great, let's go with 3166-2 then.

cc @anjesh

**Comment by anjesh** [comment]
Then we can use the codelist from IATI http://iatistandard.org/201/codelists/Country/ which uses 3166 Alpha-2 codes.

**Comment by anderspeders** [comment]
3166 Alpha-2 is now confirmed for all country fields. This has also now been clarified in the metadata list: 
https://docs.google.com/spreadsheets/d/12UCQA422r5Dg3wruUmYHL2SCLdDrlesCPcm2tHD8Yu4/edit#gid=1329720090

Therefore closing this ticket.
