### ISSUE TITLE
Review OLC link

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#280]
@SamCCSI: As per written feedback can you confirm if you need another logo with text...?

The current logo does include text:  
http://rc-site-stage.elasticbeanstalk.com/rc/public/images/ic-cc.png

**Comment by SamCCSI** [comment]
Is this resolved by the info I sent this afternoon (WB and CCSI logos)?

**Comment by anjesh** [comment]
Can you confirm and send logos if they need updates?

**Comment by SamCCSI** [comment]
@anderspeders I believe I sumbitted this info 6 days ago, but cannot find the issue under which I submitted it. It may have been marked as resolved. Can you please liaise with @anjesh on this?

**Comment by anderspeders** [comment]
@SamCCSI I have tried to search as well and did not locate it. I regret the inconvenience.

The most secure way to avoid misunderstandings will be if you add the logos here with a direct link to the JPEG file.

To clarify the current version is here: http://rc-site-stage.elasticbeanstalk.com/olc/public/

**Comment by SamCCSI** [comment]
Confirming that this info is in issue 203
https://github.com/NRGI/resourcecontracts.org/issues/203

On Tue, Sep 15, 2015 at 10:10 PM, Anders <notifications@github.com> wrote:

> @SamCCSI <https://github.com/SamCCSI> I have tried to search as well and
> did not locate it. I regret the inconvenience.
>
> The most secure way to avoid misunderstandings will be if you add the
> logos here with a direct link to the JPEG file.
>
> To clarify the current version is here:
> http://rc-site-stage.elasticbeanstalk.com/olc/public/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/280#issuecomment-140602528>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by anjesh** [comment]
Thanks. Will be taken care in this issue https://github.com/NRGI/resourcecontracts.org/issues/203

**Comment by SamCCSI** [comment]
Thanks!

On Mon, Sep 21, 2015 at 5:36 AM, Anjesh <notifications@github.com> wrote:

> Thanks. Will be taken care in this issue #203
> <https://github.com/NRGI/resourcecontracts.org/issues/203>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/280#issuecomment-141868054>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>
