### ISSUE TITLE
Mechanical turk review - resotring OCR

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#281]
p. 21 of this OCR is now blank - is there a way to restore the OCR, so that a mechanical turk person can adjust, rather than typing from scratch?

http://resourcecontracts.elasticbeanstalk.com/mturk/1044

**Comment by SamCCSI** [comment]
p. 25 as well.

**Comment by anjesh** [comment]
I think the worker has submitted the blank page for page 21 as can be seen in the Mturk site. As for page 25, the worker has done a paragraph and submitted. I hope they should be available with the worker in their mturk interface. Once rejected, you have to click "reset" to create another HIT task for that particular page. Then the worker (any worker) will be able to work on that task again. 

I see page 22 is also rejected for above contract, which looks fine. I don't think we could revert that action in the mturk, though we could tweak into our system by directly fixing in the database.

**Comment by anjesh** [comment]
Closing this as the further discussion here https://github.com/NRGI/resourcecontracts.org/issues/308
