### ISSUE TITLE
Hyperlinks missing

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#282]
![image](https://cloud.githubusercontent.com/assets/1101585/9747436/889e8110-564b-11e5-99a5-92d64189ba50.png)

**Comment by anjesh** [comment]
Hyperlinks in-place

![image](https://cloud.githubusercontent.com/assets/120488/9809885/d4d158ea-588b-11e5-8727-3a442ce05c3b.png)
