### ISSUE TITLE
Contract quality issues list

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#284]
It will be very useful to expand the contract quality issues page by allowing for the searching and displaying on a country level and not just showing all contract issues in one list. This will be very useful for QC purposes.

**Comment by hello-deepak** [comment]
Some filters are added in quality issue to filter.

![filter](https://cloud.githubusercontent.com/assets/7577697/17211575/f8add198-54e9-11e6-8e4a-fd93950ebc36.png)

Review http://admin.resourcecontracts.org/quality and provide feedback.

**Comment by charlesyoung** [comment]
Thanks @hello-deepak.
