### ISSUE TITLE
UI - Advanced search: Contract Type - entities must be correct and capitalised 

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#285]
![image](https://cloud.githubusercontent.com/assets/1101585/9761555/765a0f44-56cb-11e5-8cd9-9a4c7555d90a.png)

**Comment by anjesh** [comment]
Those were also probably during the indexing process. However there are non-standard types, which were directly imported from the OLC/RC. Those needs to be properly mapped from the admin interface. We are listing all the contract-types that are present in the contracts, but not necessarily in the contract-type-codelist.

**Comment by anjesh** [comment]
This can be closed as the types will be fixed once update we fix this https://github.com/NRGI/resourcecontracts.org/issues/299
