### ISSUE TITLE
UI - Advanced search: No annotation categories

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#286]
![image](https://cloud.githubusercontent.com/assets/1101585/9761825/11ea34ec-56cd-11e5-9728-7c84164ff1d4.png)

As a user I would like to be able to drill through the list of annotation categories and select one or more categories in the search.

**Comment by anjesh** [comment]
It's listed there now. We were indexing the ES and hence the annotations were not appearing before.
