### ISSUE TITLE
Metadata: Add another government entity

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#287]
![image](https://cloud.githubusercontent.com/assets/1101585/9763865/caf7bad4-56d9-11e5-988b-bcee0a45d86a.png)

As an administrator I would like to be able to provide names of multiple government entities - when multiple government entities are signatories to a contract.

**Comment by anjesh** [comment]
That means Government Entity and Government Identifier. Right?

**Comment by anderspeders** [comment]
Correct.

**Comment by anjesh** [comment]
The government meta now contains "Add more", the existing data is also updated to reflect the new data-model (string to array), similarly reflected the change in the API, and subsites.
