### ISSUE TITLE
Review of metadata migration for OLC and RC

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#288]
![image](https://cloud.githubusercontent.com/assets/1101585/9764288/4769f7f6-56dc-11e5-9eb9-b173d1fa989e.png)

As discussed today - let's have a review of the accuracy of the metadata mapping.

**Comment by anjesh** [comment]
Linked with https://github.com/NRGI/resourcecontracts.org/issues/299 
Closing this one.
