### ISSUE TITLE
Migrate contracts plus basic metadata from documentcloud to new platform

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#29]
Not decided yet. 

Link to file: https://www.dropbox.com/sh/d3ouhoa8flfzyj6/AAB6h8Q5sLtuoldoLgEPXTmda?dl=0

Tasks include: 
1) Mapping old metadata to new metadata schema
2) Cleaning up the metadata

**Comment by anjesh** [comment]
Closing this as further discussion here https://github.com/NRGI/resourcecontracts.org/issues/120
