### ISSUE TITLE
Contract uploading

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#290]
Will it be possible to select if the document being uploaded is the 'main contract' or 'supporting document'? This will help filter out main contracts from the associated document list. The current associated document list shows both 'main contract' and 'supporting documents' which is cumbersome.

**Comment by anderspeders** [comment]
@charlesyoung Did this get solved? If not could you flesh out a more detailed recommendation for the metadata form (or the documentation)?

**Comment by charlesyoung** [comment]
Its still not resolved as shown below. 

The most optimal solution will be to allow uploaders the option of selecting if its the main contract or supporting document directly under the 'Contract File' location. If the main contract then the uploader completes capturing the information as per normal but if its supporting documentation then another options needs to be presented allowing for the selection of the relating main contract so that the metadata can be copied to the supporting document metadata. 

![image](https://cloud.githubusercontent.com/assets/13888372/10336326/47fde240-6cf8-11e5-991b-f522cad20650.png)

**Comment by anjesh** [comment]
This is covered here https://github.com/NRGI/resourcecontracts.org/issues/624
