### ISSUE TITLE
Spell check for annotation module

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#291]
As a contributor I would like to have spell check support when I type free text into the annotation module. 

Would this work http://www.javascriptspellcheck.com/jquery-spell-check?

**Comment by SamCCSI** [comment]
Just checking - will this feature be included in the next sprint?

**Comment by anderspeders** [comment]
@anjesh We are good to go on implementation of spell check for the annotation module. 

Group has decided that a spell check plugin is not sufficient.

**Comment by anjesh** [comment]
Right now the editor box shows red underline under misspelled words. 
![image](https://cloud.githubusercontent.com/assets/120488/12385666/7c2997fa-bde6-11e5-87d0-09e959e279d2.png)

The user has to manually correct it or some browser (like chrome, firefox) gives suggestions on right click as shown below. 

![image](https://cloud.githubusercontent.com/assets/120488/12385680/968fcaa6-bde6-11e5-889c-54ba487fbfc1.png)
