### ISSUE TITLE
Editing resource type on OLC

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#292]
These 4 contracts have their resource as "Palm oil", but I want to edit each of them so that the resource is "Oil palm". When I click edit, "oil palm" is not one of the resources I can select, even though it is one of the resources by which I can search.

http://resourcecontracts.elasticbeanstalk.com/contract?year=all&country=all&category=all&resource=Palm+oil

Could you offer any solutions? The contracts were all migrated from the former platform.

**Comment by anjesh** [comment]
Now the list shows three 'palm+oil' in the resource list - the list will be cleared once we update the resource-type in the contracts. Now you could directly edit the contract and update with the new resource-type for those few contracts. We have updated the latest resource-types in the list.

![image](https://cloud.githubusercontent.com/assets/120488/9877142/c0d528ec-5bda-11e5-9d10-385212ec7165.png)

**Comment by SamCCSI** [comment]
When I try to edit each individual contract "palm oils" and "oil palm" are still not on the list of resources I can choose - see screenshot:

![screen shot 2015-09-15 at 9 31 34 am](https://cloud.githubusercontent.com/assets/12913915/9877724/aed85338-5b8c-11e5-847a-1aec600eccd0.png)

**Comment by anjesh** [comment]
Do you need all of them? I thought it's only "Palm oil" as provided in the commodity list https://docs.google.com/spreadsheets/d/1N0rCjS3WPBq-ELAeg8lkviChgI07R-5ak8pfd4lVRfE/edit#gid=0

**Comment by SamCCSI** [comment]
Hi all,

Bringing this conversation to email, as it involves multiple people.

*Anders*: See below github conversation regarding the resource list being
incorrect.

YI were working off this commodities list,
<https://docs.google.com/spreadsheets/d/1N0rCjS3WPBq-ELAeg8lkviChgI07R-5ak8pfd4lVRfE/edit#gid=0>
whereas Kaitlin went through each contract to be migrated on this migration
list
<https://docs.google.com/spreadsheets/d/18xCuXuxQSbxlhxUgufNWLiLO_V22wh3pd7oC0Q8Ts1k/edit?usp=sharing>
to ensure that the resource is correctly expressed in accordance (usually)
with the AGROVOC standard.

Is it possible to ensure that each contract on the migration list has the
resource allocated to it on the migration list, and that each of those
resources are then included on the dropdown for resources on the RC/OLC
backend, so that we can use them for additional annotations and correct
annotations with incorrect resource types?

The example we have been working off is that "palm oil" should not be a
resource category. Instead we have "Palm oils" or "Oil palm".

Many thanks,
Sam



On Tue, Sep 15, 2015 at 9:36 AM, Anjesh <notifications@github.com> wrote:

> Do you need all of them? I thought it's only "Palm oil" as provided in the
> commodity list
> https://docs.google.com/spreadsheets/d/1N0rCjS3WPBq-ELAeg8lkviChgI07R-5ak8pfd4lVRfE/edit#gid=0
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/292#issuecomment-140395379>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>
