### ISSUE TITLE
All contracts searching options

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#294]
Display 'Resource' in the search drop-down just like 'Year', 'Country' and 'Category' are displayed. 

![image](https://cloud.githubusercontent.com/assets/13888372/9783679/8fc42d1c-57a6-11e5-963e-305d08cf3519.png)

**Comment by anjesh** [comment]
It shows "Resource" by default but disappears if you click that "x"
![image](https://cloud.githubusercontent.com/assets/120488/9876257/5d4f13d8-5bd4-11e5-97e6-63ee4fa3ab57.png)
