### ISSUE TITLE
Resource names

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#295]
Weird resource names

![image](https://cloud.githubusercontent.com/assets/13888372/9785082/fb3f0a2c-57af-11e5-8bc4-954c2231c9ad.png)

And this is how its shown on the RC site. 

![image](https://cloud.githubusercontent.com/assets/13888372/9817175/8e70170e-58a1-11e5-8617-6afb570d27a8.png)

**Comment by anjesh** [comment]
These will get fixed once https://github.com/NRGI/resourcecontracts.org/issues/299 is resolved. They are coming from the migration.

**Comment by anjesh** [comment]
This will be taken care once https://github.com/NRGI/resourcecontracts.org/issues/299 is fixed.
