### ISSUE TITLE
General metadata information 

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#296]
Should the 'Resource' and 'Signature Date' fields be displayed even if not filled in? Other fields are shown even if blank but not the 'Resource' and 'Signature Date' fields. 

![image](https://cloud.githubusercontent.com/assets/13888372/9785042/a4f52336-57af-11e5-8820-b79632c69554.png)

**Comment by anderspeders** [comment]
Yes, correct @charlesyoung, 

@anjesh: I recommend that we make it clear in the overview that "Resource" and "Signatory Date" fields also should appear if they are **blank**.

**Comment by anjesh** [comment]
Fixed.
