### ISSUE TITLE
Contract Import / Add

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#297]
Should the Open Oil contract import and new contract add not be distinguished better? 

![image](https://cloud.githubusercontent.com/assets/13888372/9785228/f91cc63e-57b0-11e5-8e27-cad0eade5b7d.png)

**Comment by anjesh** [comment]
Ideally it should. Will think of some good place to put "Import Contract" which should be renamed to "Import Open Oil Contract" as it's specific type.

**Comment by anjesh** [comment]
This will be taken care in this issue https://github.com/NRGI/resourcecontracts.org/issues/339
