### ISSUE TITLE
Automated binning of contracts: structured vs. image files

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#3]
Before the ocr process the contracts must be accessed if they are image based or structured.

This could be something as simple as creating a docker container that acts as a as a service provider that returns a 1 if parseable and a 0 if not. Both of these bins need to maintain page references so that we can bring in old annotations.

**Comment by anderspeders** [comment]
The binning will include two options: 

1) Structured PDFs --> PDF to text

2) Image only PDFs --> ABBYY reader

**Comment by anjesh** [comment]
https://github.com/anjesh/pdf-processor uses pdfinfo and pdftotext to identify whether it's structured or not. Currently the logic is very primitive, it assumes that if the average page text is 50 bytes for all the pages, then the pdf is structured. Need to run this for all the listed pdfs to test the working of the logic.

**Comment by anderspeders** [comment]
This is done. And tested.

**Comment by byndcivilization** [comment]
Does pdftotext retrun a value if there pdf is unstructured? That may be better way to bin.
