### ISSUE TITLE
Resources dropdown list

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#300]
It is clear that the 'Language' and 'Country' have dropdown lists by looking at the arrow on the right but although the 'Resources' has a dropdown list the arrow isn't shown.  Is that because more than one resource can be selected? 

![image](https://cloud.githubusercontent.com/assets/13888372/9812295/a6ec8044-587c-11e5-8154-5771025610c3.png)

**Comment by anjesh** [comment]
Yes. It's the multiple-selection list, and the library we are using to get this doesn't provide the dropdown. Once the user clicks on the list, they will know that it has dropdown options.
