### ISSUE TITLE
Remove teaser text from each teaser annotation from annotation bar

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#302]
![image](https://cloud.githubusercontent.com/assets/1101585/9817789/f9b831a6-5872-11e5-896a-985c6e7be413.png)

**Comment by anjesh** [comment]
Tags and the text is not displayed for now. 

![image](https://cloud.githubusercontent.com/assets/120488/9876175/d05634e8-5bd3-11e5-93b0-6bcf29def530.png)

**Comment by anderspeders** [comment]
Hi @anjesh 

In latest version it appears that the teaser text has remained which is actually fine: http://alpha.openlandcontracts.org/contract/681/view 

Could you clarify and confirm?

**Comment by anjesh** [comment]
There are two kinds of text in annotations in text-based content - one is the text (text1) selected in the content, and the other is the text (text2) written in the box by the annotator.
In PDF based content, there's only text (text2) written in the box as text can't be selected there. In text-based content annotation, there's always text1 (you have to select text to start annotation) and text2 can be missing. In pdf-based content annotation, there can't be text1(you can't select text) and text2 can be missing. 

The image you have pasted shows the case of text 1 and text 2. Now we check for their presence before displaying in the list , and also truncated to save the space as some annotation are very long as you have mentioned in the UI mockup. 

I am not sure if that can be called teaser text. That's the actual annotation and truncated if it contains more than 20 or so words.
