### ISSUE TITLE
Advanced searching

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#304]
Clicking on the text 'Year' removes the top line of text. 

![image](https://cloud.githubusercontent.com/assets/13888372/9818331/4f9a21f8-58a8-11e5-9ac6-d8faa46bb062.png)

![image](https://cloud.githubusercontent.com/assets/13888372/9818294/2200d7e6-58a8-11e5-8b29-ad6ec3676fe9.png)

**Comment by anjesh** [comment]
Not sure if this is fixed, but it's not happening in my browser - chrome. If it's still happening at your end, please mention the browser/version.

**Comment by charlesyoung** [comment]
Cannot replicate so it seems to be fixed. Not sure its because the text was changed from 'Year' to 'Year signed'.

**Comment by anjesh** [comment]
not sure either :)
