### ISSUE TITLE
Annotation boxes all appear on first page during initial load

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#305]
Possible bug with migrated PDFs and their annotation boxes

When you open up a migrated PDF, the first page seems to show every annotation box of the entire contract; when you click to the next page, the annotations all seem to shift to the correct page. 

Then, when you go back to the first page, the boxes no longer appear.

First page initial view:
![image](https://cloud.githubusercontent.com/assets/1101585/9838849/62ef0550-5a35-11e5-8939-e8dfeaeba55d.png)
 
Example of page 4 once you start clicking through:

![image](https://cloud.githubusercontent.com/assets/1101585/9838850/6b2e0da6-5a35-11e5-9af6-a03e337e00d9.png)

Example of first page once you view after having visited other pages (no annotation boxes):
![image](https://cloud.githubusercontent.com/assets/1101585/9838851/77c05006-5a35-11e5-959c-9f945817b071.png)

**Comment by anjesh** [comment]
Fixed in new UI.
