### ISSUE TITLE
MT / OCR - pages missing

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#306]
for some contracts, not all the pages were uploaded. So, MT has processed available pages, but we are missing some. Is there a way to re-upload and submit only the pages that remain untranscribed? See for example S & P energy (missing at least last two pages). http://resourcecontracts.elasticbeanstalk.com/mturk/1039

**Comment by anderspeders** [comment]
I am afraid it will be diffucult to add pages to a contract once it as been loaded to the platform. I would suggest that the only option at the moment is to upload a new full copy of the contract. 

I might be missing something here - so  cc-ing @anjesh

**Comment by SamCCSI** [comment]
Thanks. If we re-upload full contract, is there a way to only submit the
missing pages to MT? and then to harmonize the pages that have already been
transcribed by MT?

On Mon, Sep 14, 2015 at 5:13 PM, Anders <notifications@github.com> wrote:

> I am afraid it will be diffucult to add pages to a contract once it as
> been loaded to the platform. I would suggest that the only option at the
> moment is to upload a new full copy of the contract.
>
> I might be missing something here - so cc-ing @anjesh
> <https://github.com/anjesh>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/306#issuecomment-140207420>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by anjesh** [comment]
That is something that we will have to do manually/directly in the database. I hope such cases are not common so i don't think if we should be putting effort to address this particular case. And this can be tricky to implement as well. 

And you cannot re-upload for the file for the existing contract. That is something we will have to do that manually. 

Are the missing pages the last pages? That would be easy to insert, otherwise we have to reorder all the existing pages in the database and insert in between ensuring the order. If the work has already been transcribed and need to add few more pages for transription, then again manual entry into the database. 

If you could provide the details, then we can have those fixed.

**Comment by SamCCSI** [comment]
It is missing last two pages.

Here is link to full PDF https://www.dropbox.com/s/1pwfzfayae3vjly/SP%20Energy%20%28Indian%20invest%20-%20biofuels%202010%29.pdf?dl=0

**Comment by SamCCSI** [comment]
Hi @anderspeders and @anjesh , on this issue, do you have a solution for this contract that is missing the last two pages?
http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/1039/view

link to full PDF https://www.dropbox.com/s/1pwfzfayae3vjly/SP%20Energy%20%28Indian%20invest%20-%20biofuels%202010%29.pdf?dl=0

I am happy to add it to the re-upload list, but am conscious of the need to minimize the strain on YI staffers involved in the upload. Plus this would also mean losing the 7 mechanical turk pages already done + our intern Charles' hard work in formatting each page.

cc @kaitlinccsi

**Comment by anderspeders** [comment]
@anjesh Can you add page 8, 9 from this document?
https://www.dropbox.com/s/1pwfzfayae3vjly/SP%20Energy%20%28Indian%20invest%20-%20biofuels%202010%29.pdf?dl=0

**Comment by SamCCSI** [comment]
If this is not able to be done before end of this week, we might need to make the contract not published, as both OCR and PDf are missing last two pages cc @KaitlinCCSI

**Comment by anderspeders** [comment]
Thanks @SamCCSI, 

@anjesh: let us know if your data support term member can get this cleared before launch. 

@SamCCSI: If not possible, yes the alternative would be to pull contract.

**Comment by anjesh** [comment]
Ok. We will fix this sprint.

**Comment by anjesh** [comment]
http://alpha.openlandcontracts.org/contract/1039/view is fixed. 2 pages are added and pdf document replaced.

**Comment by SamCCSI** [comment]
Many thanks!

On Wed, Sep 30, 2015 at 12:56 PM, Anjesh <notifications@github.com> wrote:

> Closed #306 <https://github.com/NRGI/resourcecontracts.org/issues/306>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/306#event-422930899>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>
