### ISSUE TITLE
downloading word doc of contract - unstructured

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#307]
the word document download option for some contracts has all the OCR'ed text, but no paragraph lines, so that all text is included in one continuous line. See for example S & P energy. Is there a way to ensure that the word doc is suitably 'structured'? http://resourcecontracts.elasticbeanstalk.com/mturk/1039

**Comment by anjesh** [comment]
The word is now formatted using nl2br (New line to Line break). The existing word files are fixed and the the implementation in place for the new contracts.
