### ISSUE TITLE
Word doc of contract

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#309]
For 12 Ethiopian OLC contracts, we have them in both word doc and pdf form.

Is there a way to use the word doc for the text extraction, rather than using OCR?

That way we don't need to wait for OCR processing or for mechanical turk.

**Comment by anderspeders** [comment]
I don't think it is possible to load them as Word doc. 

I do however think you can print the word doc aas a pdf in a way where the structure will be maintained. In this way the OCR time would be minimal and there would be no need for Mech Turk.

**Comment by anjesh** [comment]
yes, that is the right approach as mentioned by Anders.
