### ISSUE TITLE
User feedback work flow

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#31]
By the end of sprint 1 we will enable "super users" to upload contracts to the basic alpha document workflow. 

In order to collect user feedback efficiently YIPL will assign a developer to receive and track user feedback in Github. 

In most cases users will not be comfortable with Github and feedback will therefore likely be directed as email. The feedback support at YIPL will then track and document the issue in Github and appropriate solutions will be suggested.

**Comment by anjesh** [comment]
What do you suggest to us for the email? nrgi@yipl.com.np or some email with resourcegovernance.org domain. We will put this email in the readme once finalized.

**Comment by anjesh** [comment]
resourcecontracts@yipl.com.np has been setup as a support email for the users to get back for help/support/bugs.

**Comment by anjesh** [comment]
Also updated in [readme](readme.md)
