### ISSUE TITLE
phpunit testing - language for odesk team

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#311]
In order to scale up the bug reporting we will deploy one or two php testers through odesk. 

@anjesh: could you help type up 1-2 paragraphs on the tasks and workflow?

cc @byndcivilization

**Comment by byndcivilization** [comment]
Just to add. We want to hire a couple folks to flesh out phpunit testing and to relieve you guys with some of the bug squashiing and minor feature upgrades. We'll be hiring them through Upwork and assigning specific issue tickets to them. We need a write up of specific frameworks, languages, etc for the job description.

**Comment by anjesh** [comment]
I am not sure if we are still on for the odesk work. I am closing this for now, do open and discuss if we want this again.
