### ISSUE TITLE
Mirrored view - at first load

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#312]
![image](https://cloud.githubusercontent.com/assets/1101585/9891654/e7d58ab8-5bd5-11e5-9de9-d30e2f0ff986.png)

First time I visit PDF pages on the site I will see examples of mirrored pages. Once I click back and forth the page will correct it self. However the first view remains wrong. 

I have double checked with the original contract document - and clearly appear as a bug. 

![image](https://cloud.githubusercontent.com/assets/1101585/9891679/12ab22f2-5bd6-11e5-9f55-ec91bc6671cd.png)

**Comment by anjesh** [comment]
This should have been resolved with the latest deployment. It's working ok at our end.
