### ISSUE TITLE
Mech turk - tasks appear not to be resubmitted resulting in very low completion rates

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#313]
Just checked Mech Turk after the weekend and very few – if any – new HITS have been identified. 

As an example: I submitted this Salala contract several weeks ago. All contributions were submitted right after it was loaded to the site: http://resourcecontracts.elasticbeanstalk.com/mturk/108 

We seem to have identified that the issue is that the HITs needs to get into recirculation. At least it seems that most contracts get an initial spark once submitted – but then if not completed fully – then remaining tasks will stay on for weeks. My sense from looking at the Mech Turk on a near daily basis – it appears to me that HITs are either not resubmitted or not done so until significant wait time.

The result is that very few contracts are actually completed.

Any suggestions here would therefore still be helpful @anjesh and @byndcivilization?

**Comment by anjesh** [comment]
This is very old issue, there doesn't seem to be any issue with submission. In any case https://github.com/NRGI/resourcecontracts.org/issues/632 should take of this issue.
