### ISSUE TITLE
Participation Share

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#317]
How should the participation share info be captured if there are two companies both with a 50% share? When I enter 50 i get a 'please enter a value less than or equal to 1' message. Should it be captured as 0.5? 

![image](https://cloud.githubusercontent.com/assets/13888372/9899840/cf84eb02-5c5c-11e5-99a4-06e535d5adcf.png)

**Comment by anjesh** [comment]
Yes, right now it should be between 0 to 1, so 50% should be 0.5. It needs some instructions there.

**Comment by charlesyoung** [comment]
Why don't we allow for 50 rather than 0.5? Would make more sense to capture 50.

**Comment by anderspeders** [comment]
I suggest that we clarify the current setup in the technical documentation and push potential changes to the future.

**Comment by anderspeders** [comment]
Suggest here that we adjust the guidance text in the metadata form. Is the change below helpful @charlesyoung?

From: "please enter a value less than or equal to 1" 

To: "Please enter the percentage value of the participation share. For example: 32% is 0.32)"

**Comment by charlesyoung** [comment]
Yep the text update looks good. A question though; what is the complexity to allow for full percentage capture?
