### ISSUE TITLE
Contract upload / processing message 

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#318]
Its not clear what is happening in the background when uploading a contract so we should include a message saying that "You will receive an email notification once the contract processing is complete allowing for the text review."

**Comment by anderspeders** [comment]
@hello-deepak We should prioritise backend work within sprint 9. 

Please focus on the many UI fixes and the annotation mapping #348 cc @anjesh

**Comment by anjesh** [comment]
This is a small fix and updated in the system.
