### ISSUE TITLE
Annotation workflow: Create pick list for tags

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#32]
![screenshot 2015-06-10 09 34 45](https://cloud.githubusercontent.com/assets/1101585/8083627/012afcc4-0f54-11e5-9e75-0a31c7ba19e3.png)

We need to have some sort of pick list so that the tags I use as an annotator will become standardized and searchable across contracts. Examples: 
- Capital gains tax
- Stabilization clause 
- etc

**Comment by anjesh** [comment]
I believe this sheet has the tags to be used for annotation https://docs.google.com/spreadsheets/d/12UCQA422r5Dg3wruUmYHL2SCLdDrlesCPcm2tHD8Yu4/edit#gid=836122159
Can we make it easy to read?

**Comment by anderspeders** [comment]
Anders to provide annotation pick list for the tags.

**Comment by anjesh** [comment]
Added the list in the "Annotation category" list. Still need to improve the annotation bit.
