### ISSUE TITLE
OLC: Change page headers

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#321]
- Can you please change "Guides" to "Resources"?
- Could you please add a "Glossary" page?

Based on feedback from @SamCCSI

**Comment by anjesh** [comment]
This is for OLC only right?

**Comment by SamCCSI** [comment]
Thanks for asking - it is for both OLC and RC.

On Thu, Sep 17, 2015 at 12:42 AM, Anjesh <notifications@github.com> wrote:

> This is for OLC only right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/321#issuecomment-140969057>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by anjesh** [comment]
Added pages.
