### ISSUE TITLE
fix for annotations with multiple pages

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#323]
Problem:
annotations with multiple page refs show the full annotation multiple times. Eg. "Other requirements regarding protection… [5]" shows a very lengthy annotation five times in a row, with each of the page numbers heading each iteration of the description. This won't work - it will crowd out the annotations and make them lose value in eye of the user. Is there a way to list all five page refs under just one copy of the annotation, as we could on the previous platform?

Solution:
should appear and function like this 
![image](https://cloud.githubusercontent.com/assets/12913915/9916774/28fe6d1e-5c8c-11e5-9863-3323d045540f.png)

**Comment by SamCCSI** [comment]
@anderspeders make sense?

**Comment by anjesh** [comment]
What if the annotation text under the same category are different? Do we show the first one only?

![image](https://cloud.githubusercontent.com/assets/120488/9925539/7552cb92-5d2c-11e5-9380-4077a742ec54.png)

**Comment by SamCCSI** [comment]
It should never be different - we only ever enter one annotation per
annotation category.

In the example screenshot, "infrastructure" is a different annotation
category from "infrastructure - third party use", so both of them should
appear.

On Thu, Sep 17, 2015 at 1:25 AM, Anjesh <notifications@github.com> wrote:

> What if the annotation text under the same category are different? Do we
> show the first one only?
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/120488/9925539/7552cb92-5d2c-11e5-9380-4077a742ec54.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/323#issuecomment-140972744>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by SamCCSI** [comment]
Hello all, this needs to be marked as a priority for the current sprint.

**Comment by SamCCSI** [comment]
The following contracts have this problem of repeated annotations. Please note I have not listed every repeated category, but have just used one or two categories as examples.

Whitefield
repetition of annotations with multiple page numbers still appear. Eg. Cancellation or termination appears 6 times.

Saber farms
repetition of annotations with multiple page numbers still appear. Eg. Cancellation or termination appears 6 times.
Year of contract signature repeats 3 times

Omo valley
repetition of annotations with multiple page numbers still appear. Eg. Cancellation or termination appears 6 times. One of the six annotations is different from the others

Nile Trading
has some annotations listed under category of ‘general information’ that belong to other annotation categories

Nega Mamay Mihret
repetition of annotations with multiple page numbers still appear. Eg. Cancellation or termination appears 6 times. Eg. ‘Physical security’ appears twice.
has some annotations listed under category of ‘general information’ that belong to other annotation categories

Karuturi
repetition of annotations with multiple page numbers still appear. Eg. Cancellation or termination appears 6 times. Eg. Name of company executing appears twice.
has some annotations listed under category of ‘general information’

KOMOR Enterprise
has some annotations listed under category of ‘general information’ that belong to other annotation categories

JVL Overseas
repetition of annotations with multiple page numbers still appear. Eg. Cancellation or termination appears 6 times. One of the six annotations is different from the others
has some annotations listed under category of ‘general information’ that belong to other annotation categories

Hunan
repetition of annotations with multiple page numbers still appear. Eg. Cancellation or termination appears 7 times. One of the 7 annotations is different from the others
has some annotations listed under category of ‘general information’ that belong to other annotation categories

Getafan
repetition of annotations with multiple page numbers still appear. Eg. Cancellation or termination appears 6 times.


BHO
repetition of annotations with multiple page numbers still appear. Eg. Cancellation or termination appears twice but with different text for each annotation.
has 6 annotations listed under category of ‘general information’ that belong to other annotation categories

Agropeace
repetition of annotations with multiple page numbers still appear. Eg. Cancellation or termination appears 3 times but with different text for 1 annotation.
has 8 annotations listed under category of ‘general information’ that belong to other annotation categories

**Comment by anderspeders** [comment]
Thanks @SamCCSI, we're taking a look at this again! 

cc @byndcivilization

**Comment by SamCCSI** [comment]
Thanks @anderspeders !

Please note that my comment 8 days ago "It should never be different - we only ever enter one annotation per annotation category" has not proved to be entirely true. Some how some of the contracts have multiple instances of annotation categories, eg. termination, some of which are not identical (as set out in the list above). I'm not sure why this is.

**Comment by byndcivilization** [comment]
@anjesh this is the clustering of annotations that I was referring to in #348 and #71. I really think creating some sort of category table is the way to go here. You can store page refs as an array and sort to add lowest pg number as title link. You only have to manage one set of annotation content data instead of keeping track of which in the cluster is the 'live" content data.

**Comment by SamCCSI** [comment]
Was just reminded of this issue again - see example: http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/1170#annotation

@anderspeders I understand the team has huge time pressures - is this issue likely to have some form of solution by the time of the launch?

Many thanks!
Sam

cc @KaitlinCCSI
