### ISSUE TITLE
Displaying French annotation categories for French annotations

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#324]
Problem:
Right now, even French annotations will only have the english language heading of the annotation category.  
Eg. Contracting party's permitted use of public or private land outside concession area 
SEFOCO bénéficie d'une servitude de passage sur les fonds riverains, destinée à favoriser l'accès à sa concession et l'évacuation de sa production. -- Art. 7   
Pg. 2

Solution:
Need to have French language annotation category for French annotations, and ENG annotation category for ENG annotations.

**Comment by anjesh** [comment]
There will be language selection option for ENG and FRE, later. The interface will change including the annotation category, irrespective of the metadata content.

**Comment by SamCCSI** [comment]
Just checking - will this feature be included in the next sprint?

**Comment by anjesh** [comment]
This will be fixed when we have the internalisation enabled in the subsite. Will be carried out in this sprint https://github.com/NRGI/resourcecontracts.org/issues/47
