### ISSUE TITLE
Quick fix for FRE / ENG annotations

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#325]
Right now, even French annotations will only have the english language heading of the annotation category.

Eg.
Contracting party's permitted use of public or private land outside concession area
SEFOCO bénéficie d'une servitude de passage sur les fonds riverains, destinée à favoriser l'accès à sa concession et l'évacuation de sa production. -- Art. 7 
Pg. 2

It will not be possible before the launch of OLC for French annotations to be headed by French annotation categories. We therefore want to make all annotation categories (for French and for English) to have both French and English displayed, like the old platform does.

Eg.
[Category] Contracting party's permitted use of public or private land outside concession area // Autorisation pour utiliser les terres publique ou privées à l'extérieur de la zone de concession
[Annotation text] SEFOCO bénéficie d'une servitude de passage sur les fonds riverains, destinée à favoriser l'accès à sa concession et l'évacuation de sa production. -- Art. 7 
Pg. 2

**Comment by byndcivilization** [comment]
@anjesh and @SamCCSI we don't want to start interspersing french and english though as that will put us back to square one in terms of solid metadata. Maybe a good compromise will be to store category data as either a link to an object (i.e. "{eng: <english title>, fre: <french title>}") or a tipple (i.e. "(<englsh title>, <french title>)") and using the language flag to determine rendering.  If linking is hard, could we store data in column using JSON type?

**Comment by SamCCSI** [comment]
Hi Chris,

This would just be for the annotation categories - not the annotation
entries (nor for the metadata entries).

Does that meet any of your concerns?

The alternative is to have French annotations headed by English
annotations, which makes the annotation pretty inaccessible for all wexcept
those who speak both languages.


On Wed, Sep 16, 2015 at 4:30 PM, Chris Perry <notifications@github.com>
wrote:

> @anjesh <https://github.com/anjesh> and @SamCCSI
> <https://github.com/SamCCSI> we don't want to start interspersing french
> and english though as that will put us back to square one in terms of solid
> metadata. Maybe a good compromise will be to store category data as either
> a link to an object (i.e. "{eng: , fre: }") or a tipple (i.e. "(, )") and
> using the language flag to determine rendering. If linking is hard, could
> we store data in column using JSON type?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/325#issuecomment-140880141>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by byndcivilization** [comment]
The annotation categories are metadata. Especially because we are using them to cluster clauses.

**Comment by anjesh** [comment]
We are using keys/values for annotation category and later plan to have the french and english selection option. For now, the quick fix would be to have both english and french as value as quick fix as mentioned by Sam. 

Later once we have fr/en option, the user will be able to see the categories in the language of their choice.

**Comment by SamCCSI** [comment]
Thanks @anjesh 

For quick fix purposes, the annotation categories are listed in French (Column A) and English (Column B) in this template: https://www.dropbox.com/s/ztepuvn1kbj2u5h/NRGI_WB_CCSI_template_and_metadata_v4.5_020915%20%28no%20picklist%29.xlsm?dl=0

**Comment by anjesh** [comment]
Fr/en annotation categories are now displayed in the annotations listing.

**Comment by SamCCSI** [comment]
Thanks so much!!

On Fri, Sep 18, 2015 at 7:28 AM, Anjesh <notifications@github.com> wrote:

> Closed #325 <https://github.com/NRGI/resourcecontracts.org/issues/325>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/325#event-413125462>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>
