### ISSUE TITLE
Contract page: Back to search option

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#326]
![image](https://cloud.githubusercontent.com/assets/1101585/9917563/4f8edf3c-5c90-11e5-9cb5-b3d60fd404d3.png)

There seems to be no button that can get us back to search view. Would that be normal best practise to have this?

**Comment by anderspeders** [comment]
@anjesh Do you have a proposed fix for this. I am thinking a button in the left corner?

**Comment by jedm** [comment]
Please note that global nav and back buttons are needed in multiple places and it would be good for YI to review the pages mentioned in the current priority list and to design and position a "back" or "previous" button that is in the same place in each location to help teach users where to expect it.

**Comment by KaitlinCCSI** [comment]
Also, it would be useful to keep the OpenLandContracts/Resource Contracts (beta) name (hyperlinked to the home page) in the top left corner on every page. It's on the advanced search page, but not on the contract page. This would help with navigation (though global nav buttons still needed) and also would remind users of what site they're on.

**Comment by anjesh** [comment]
This has been fixed.
