### ISSUE TITLE
OLC: replace image 

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#328]
Replace this image: 

![image](https://cloud.githubusercontent.com/assets/1101585/9942774/ee40f736-5d4a-11e5-9175-34024c6462ca.png)
 
with this: 
https://drive.google.com/file/d/0B0itojFFyvjCY19PMnZQNnVBcjg/view?usp=sharing

cc @SamCCSI

**Comment by anjesh** [comment]
replaced.

**Comment by SamCCSI** [comment]
Thank you, Anjesh!

Is it possible to have some of the sky and some of the soil (50/50) in the
photo showing on the front page? Right now it is just sky.

On Fri, Sep 18, 2015 at 7:24 AM, Anjesh <notifications@github.com> wrote:

> Closed #328 <https://github.com/NRGI/resourcecontracts.org/issues/328>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/328#event-413122972>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>
