### ISSUE TITLE
For Corporate Grouping field - Add: Other - string text field

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#329]

**Comment by anjesh** [comment]
The corporate grouping field takes both from the list or the free-text. Just type the text and enter to save the text. Does instruction help there or you think "other" should be explicitly mentioned?

![image](https://cloud.githubusercontent.com/assets/120488/9951025/383ed95c-5de1-11e5-9b63-d91eda4ecf13.png)

**Comment by anjesh** [comment]
Do you think if we need to have a separate "other" field and popup text-input field to enter that string. Otherwise the users can quickly type the text and enter to create new group if not present in the list.

**Comment by anjesh** [comment]
cc @anderspeders

**Comment by anderspeders** [comment]
Pushing this 10

**Comment by anjesh** [comment]
Fixed. 

![image](https://cloud.githubusercontent.com/assets/120488/11175181/7871bb12-8c57-11e5-9146-23e17a11d1aa.png)
