### ISSUE TITLE
Annotation workflow: Free text search within the contract

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#33]
As a user doing annotations I will need a free text search so that I can navigate a contract of potentially several hundred pages. 

Eg. I need to search for environmental protection.

This user story is for the annotation UI.

**Comment by anjesh** [comment]
When the user is viewing the text/pdf content or during annotation, there will be link to search - which takes to the following interface. For now there will be only basic text-matching. There will be later different operators (if needed like AND, OR, NOT)

![image](https://cloud.githubusercontent.com/assets/120488/8276526/2eef748c-18d7-11e5-8d76-9555a30618c6.png)

The user types text and clicks search, the results will be listed with link to page numbers.

![image](https://cloud.githubusercontent.com/assets/120488/8276529/336ded54-18d7-11e5-8ebb-966068c21afa.png)

Clicking page number takes to the specific page where that text is present. The user should be able to annotate in this page itself. Still need to think about the interface when the user starts to annotate - there will be options to toggle pdf view, annotation list view and search results view. 

![image](https://cloud.githubusercontent.com/assets/120488/8276531/37f991b6-18d7-11e5-8007-9fd550d99055.png)
