### ISSUE TITLE
Contracts marked OLC not displaying on site

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#330]
I have marked the four contracts as OLC, not RC, and they appear as OLC on the backend, but do not appear at http://rc-site-stage.elasticbeanstalk.com/olc/public/ 

 Golden Veroleum (Liberia) Inc. - Liberia, 2010 en	82.25 MB	August 17, 2015
 Maryland Oil Palm Plantation - Liberia, 2011 en	3.12 MB	August 17, 2015
 Sime Darby Plantation (Liberia) Inc. - Liberia, 2009 en	70.51 MB	August 17, 2015
 Firestone Liberia, Inc. - Liberia, 2008 en

**Comment by anderspeders** [comment]
@anjesh could you check this, I have not been able to find any issues?

**Comment by anjesh** [comment]
it appears that the these contracts are not sent for indexing when published and hence they are not appearing in subsite alpha.openlandcontracts.org 
Will look into this. 
Thanks.

**Comment by anjesh** [comment]
These are now re-published and appears in the olc site http://alpha.openlandcontracts.org/search?q=&country%5B%5D=lr
