### ISSUE TITLE
Wrong list of resources used for OLC

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#331]
@anderspeders : See below github conversation regarding the resource list being
incorrect. Recopying here because the issue I pasted it in is closed.

YI were working off this commodities list,
<https://docs.google.com/spreadsheets/d/1N0rCjS3WPBq-ELAeg8lkviChgI07R-5ak8pfd4lVRfE/edit#gid=0>
whereas Kaitlin went through each contract to be migrated on this migration
list
<https://docs.google.com/spreadsheets/d/18xCuXuxQSbxlhxUgufNWLiLO_V22wh3pd7oC0Q8Ts1k/edit?usp=sharing>
to ensure that the resource is correctly expressed in accordance (usually)
with the AGROVOC standard.

Is it possible to ensure that each contract on the migration list has the
resource allocated to it on the migration list, and that each of those
resources are then included on the dropdown for resources on the RC/OLC
backend, so that we can use them for additional annotations and correct
annotations with incorrect resource types?

The example we have been working off is that "palm oil" should not be a
resource category. Instead we have "Palm oils" or "Oil palm".

This will impact the next upload, whose contracts comply with the migration list, not the commodities list.

Many thanks,
Sam
…

On Tue, Sep 15, 2015 at 9:36 AM, Anjesh <notifications@github.com> wrote:
 Do you need all of them? I thought it's only "Palm oil" as provided in the
 commodity list
 https://docs.google.com/spreadsheets/d/1N0rCjS3WPBq-ELAeg8lkviChgI07R-5ak8pfd4lVRfE/edit#gid=0

 —
 Reply to this email directly or view it on GitHub
 <https://github.com/NRGI/resourcecontracts.org/issues/292#issuecomment-140395379>

**Comment by anderspeders** [comment]
@SamCCSI Thanks, 

The challenge here is really that we would like to add the full list of potential OLC resources in one go. I would be glad to get them all added now - to avoid that we need to add them bit by bit later. 

Therefore - would it not be useful to all resources from the Agrovoc standard?

**Comment by SamCCSI** [comment]
Hi Anders,

Unfortunately, the AGROVOC standard has so many different terms that it
would be too unwieldy to add all.

Kaitlin will submit a list of resources to be used by Wednesday (building
off this list, which contains all of the accepted terms for resources in
existing annotations -
https://docs.google.com/spreadsheets/d/18xCuXuxQSbxlhxUgufNWLiLO_V22wh3pd7oC0Q8Ts1k/edit?usp=sharing),
though there is no way that we can be sure that this list will be exclusive
for now.

If you can add a free form 'other' category for now (where we can enter
free form text for new resources), and then we can build in new resources
later into the pick-list, that would be ideal.

Best,
Sam



On Fri, Sep 18, 2015 at 4:55 AM, Anders <notifications@github.com> wrote:

> @SamCCSI <https://github.com/SamCCSI> Thanks,
>
> The challenge here is really that we would like to add the full list of
> potential OLC resources in one go. I would be glad to get them all added
> now - to avoid that we need to add them bit by bit later.
>
> Therefore - would it not be useful to all resources from the Agrovoc
> standard?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/331#issuecomment-141329430>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by anderspeders** [comment]
@anjesh Can we implement a free text "other" field under resources

**Comment by anjesh** [comment]
Created new issue for the free-text in resource https://github.com/NRGI/resourcecontracts.org/issues/358
