### ISSUE TITLE
Advanced search: Reset search button - which removes all the selection criteria

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#333]
o	When you select something, it appears in the search box with an “x” next to the name. This seems like the “x” offers a way to get rid of a choice, but if you want to get rid of the selection, you have to click on “x” and then click search. This does not seem intuitive.  
	For example, if you select “Bauxite” as a resource and then hit “search”, you get 39 contracts. If you want to then see all of the contracts, and not just those limited to Bauxite, you have to click the “x” next to Bauxite and then hit “search” again, even though you’re not searching for anything in particular, but just trying to get out of the original search results. 
	Would ideally automatically refresh every time a selection is “x”ed out of (so you could click the “x” next to Bauxite and then the page would refresh to show you all contracts. Or if you had originally selected Bauxite and Coal, clicking on “x” next to Bauxite would make the page refresh to show you only the coal contracts.)

**Comment by byndcivilization** [comment]
@anjesh I'm guessing this is controlled by the rc.search.js backbone file but cant for the life of me get anything to happen on select change state. @anderspeders can we push this to next sprint?

**Comment by anjesh** [comment]
What @anderspeders is talking about the advanced search page? Not sure how practical would this be, as with every click, the page needs to be refreshed. This might be annoying to users if they are trying to select multiple options and do search. 

![image](https://cloud.githubusercontent.com/assets/120488/10238685/d7504fba-68e2-11e5-86e9-402ff07c7450.png)

**Comment by KaitlinCCSI** [comment]
This is how the old platform works, and seem more intuitive than current
set-up (particularly when it comes to "x"ing out of an option). Though if
refreshing takes an extremely long time, then that could be a concern. If
it's more seamless, like with old platform, then I don't think it's
annoying.

On Fri, Oct 2, 2015 at 5:08 AM, Anjesh <notifications@github.com> wrote:

> What @anderspeders <https://github.com/anderspeders> is talking about the
> advanced search page? Not sure how practical would this be, as with every
> click, the page needs to be refreshed. This might be annoying to users if
> they are trying to select multiple options and do search.
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/120488/10238685/d7504fba-68e2-11e5-86e9-402ff07c7450.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/333#issuecomment-144904536>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01Po382d2&m=21ace5d661c6&t=20151001&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01Po382d2&m=21ace5d661c6&t=20151001&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01Po382d2&m=21ace5d661c6&t=20151001&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by byndcivilization** [comment]
@anjesh where is the js for the advanced search page?

**Comment by anderspeders** [comment]
Are we good here @anjesh?

**Comment by anjesh** [comment]
No we haven't done this. This page doesn't make ajax calls so any 'x'ing means the whole page gets reloaded rather than the search results only. Lets first see it in demo (with the current setup of entire page reloading) and then move to production if that's ok. Will work on this tomorrow.

**Comment by KaitlinCCSI** [comment]
Can you please make sure that when you work on things moving forward, any
testing/demo-ing won't affect OLC live site? Thanks.

On Tue, Oct 6, 2015 at 11:01 AM, Anjesh <notifications@github.com> wrote:

> No we haven't done this. This page doesn't make ajax calls so any 'x'ing
> means the whole page gets reloaded rather than the search results only.
> Lets first see it in demo (with the current setup of entire page reloading)
> and then move to production if that's ok. Will work on this tomorrow.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/333#issuecomment-145910194>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PpQ14xP&m=29f183a04e02&t=20151006&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PpQ14xP&m=29f183a04e02&t=20151006&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01PpQ14xP&m=29f183a04e02&t=20151006&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by anjesh** [comment]
Definitely.

**Comment by anjesh** [comment]
Moving this to Sprint 10. We will ofcourse have this in demo before making change in live site.

**Comment by KaitlinCCSI** [comment]
Thanks, Anjesh.

On Wed, Oct 7, 2015 at 3:18 AM, Anjesh <notifications@github.com> wrote:

> Moving this to Sprint 10. We will ofcourse have this in demo before making
> change in live site.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/333#issuecomment-146110872>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01Pq8hWAE&m=cad1d8745303&t=20151007&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01Pq8hWAE&m=cad1d8745303&t=20151007&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01Pq8hWAE&m=cad1d8745303&t=20151007&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by jedm** [comment]
To clarify @KaitlinCCSI comment from earlier this month, on the old site all results load, so when you click the facets on the left it instantly filtered the results in the center (without new search), and when you clicked the X on your filter/facet, it would add results back (without new search).

If the current system must re-initiate a search any time the user changes parameters, then there should be a color change somewhere or something to prompt you to resubmit.

**Comment by JesseCCSI** [comment]
These issues are somewhat related to the above: 

1. When you search and select an annotation category by pressing "return" on your keyboard, as a user I expect that the next time I press "return", this will actually run the search. Instead, this re-opens the dropdown menu. Is there a way to address this? 

2. I'm not sure whether this is a browser-related issue, but if I want to clear a dropdown category selection, I either have to click on the "X" to remove it, or I have to remove each character of the selection rather than just pressing the "backspace" key once in order to remove the selection. I've tried this using Chrome on a PC and Mac, and have noticed that this doesn't happen each time I run a search (I wasn't having this problem yesterday, but I am again today).

**Comment by KaitlinCCSI** [comment]
Re Jesse's second point - this seems to happen for me when I have clicked
in the dropdown box and then decide I want to delete my selection, but not
when I haven't clicked inside the dropdown box. Seems that it would be more
intuitive if deleting a choice functioned the same regardless of whether
the user has clicked in the dropdown box or not.

On Wed, Nov 4, 2015 at 7:01 PM, JesseCCSI <notifications@github.com> wrote:

> These issues are somewhat related to the above:
>
>    1.
>
>    When you search and select an annotation category by pressing "return"
>    on your keyboard, as a user I expect that the next time I press "return",
>    this will actually run the search. Instead, this re-opens the dropdown
>    menu. Is there a way to address this?
>    2.
>
>    I'm not sure whether this is a browser-related issue, but if I want to
>    clear a dropdown category selection, I either have to click on the "X" to
>    remove it, or I have to remove each character of the selection rather than
>    just pressing the "backspace" key once in order to remove the selection.
>    I've tried this using Chrome on a PC and Mac, and have noticed that this
>    doesn't happen each time I run a search (I wasn't having this problem
>    yesterday, but I am again today).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/333#issuecomment-153919767>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PBB1bq9&m=a94668432309&t=20151104&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PBB1bq9&m=a94668432309&t=20151104&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01PBB1bq9&m=a94668432309&t=20151104&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by JesseCCSI** [comment]
Another related point - is it possible to include a "Clear Search" or "New Search" button beside the existing Search button on the Advanced Search page? Otherwise users that have selected multiple categories from the dropdowns have to clear each one before they can run a different search.

**Comment by jedm** [comment]
This is an excellent suggestion.

**Comment by charlesyoung** [comment]
Just checking that the request by @JesseCCSI regarding adding a "Clear Search" or "New Search" button is still on the radar. I had the same thought today and found it frustrating not having a way of clearing my initial search.

**Comment by sadhakbj** [comment]
![333-fixed](https://cloud.githubusercontent.com/assets/5828622/11391230/f56958c8-9378-11e5-9000-7213f28dd51f.png)
- Done.
