### ISSUE TITLE
Add download option in advanced search for each result

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#334]
![image](https://cloud.githubusercontent.com/assets/1101585/9950340/876dafb2-5d87-11e5-935c-55bab97ade77.png)

**Comment by anjesh** [comment]
You mean both pdf and word docs? Then we can have "pdf | word" with link to the respective documents in the list.

**Comment by anderspeders** [comment]
Sounds good.

**Comment by anjesh** [comment]
@anderspeders please confirm on this one https://github.com/NRGI/resourcecontracts.org/issues/381
Shall we remove the word from the download?
