### ISSUE TITLE
Add sort bar to advanced search results list

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#335]
Contract name | Annotated | Country | Signature date | Resource | Contract Type | Company name   

See this as an example: 
![image](https://cloud.githubusercontent.com/assets/1101585/9950432/80a00846-5d88-11e5-8636-99b39998507f.png)

**Comment by anjesh** [comment]
Added sort 

![image](https://cloud.githubusercontent.com/assets/120488/10537481/db91dc4e-7411-11e5-8b41-fffc2904770a.png)
