### ISSUE TITLE
Upload of OLC contracts - second round

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#336]
Hi Anders,

We may add more contracts to the list before tomorrow COB, but here are the instructions for the next batch upload of contracts.

They are on the same google spreadsheet: https://docs.google.com/spreadsheets/d/13HFzsddfT9OkeAmtHLtwzpl2QP-IHaYxP8wB8adUljg/edit?usp=sharing Under the heading on Row 40 "SECOND BATCH - 18 September 2015"

I have also included contracts/annotations that need to be reuploaded - mistakes corrected. The original contract and annotation will need to be deleted so that we don't end up with duplicates. These start under the second batch at Row 71 "Contracts that need to be re-uploaded (please delete earlier version already uploaded)"

Thanks,
Sam

**Comment by anderspeders** [comment]
Last update from CCSI will be provide tomorrow Tuesday. After then it can be loaded.

**Comment by anderspeders** [comment]
CCSI has requested that this is submitted on Friday 25th. Please keep it on hold until then.

**Comment by KaitlinCCSI** [comment]
Clarification: CCSI will submit this Sunday afternoon (in New York), so that it can be addressed first thing on Monday. We'll update you via this ticket when it's ready; please keep it on hold until then. We will manually add standardised core metadata for 6 columns: C, G, H, J, K, R

**Comment by anjesh** [comment]
Sure we will hold until Monday. But there are annotations as well, we want to ensure that all the annotations categories are also as per the latest annotations codelists, shared by Sam. We are thinking of scrapping all the categories from the excel, find the unique and map to the existing set to ensure that all the annotations could be properly imported into the system. Or if you could confirm that annotations categories are all correct, then we won't be doing this. Is there possibility to have these linked excel files being updated?

**Comment by anjesh** [comment]
@anderspeders @KaitlinCCSI 
We have scrapped the annotations categories from all the excel files and found that there are 157 unique categories used, and we were able to exact-map only 47. There are still 110 which needs to be mapped the annotation codelist (containing 92) that we are provided with. We need to have this mapping as well during the import of the OLC contracts. 
https://docs.google.com/spreadsheets/d/1HkxPnWyb39oJNzkkjaGqfmWfCZe8n-Q8dPpMXKlmYEQ/edit?ts=5604fa1d#gid=0

**Comment by KaitlinCCSI** [comment]
We already mapped a lot of the annotation categories here -- https://docs.google.com/spreadsheets/d/1K0wlloEAPFncrNA_mwBjqvW81A5xRpFlK0qlv-j5ZYo/edit#gid=1612543715 (tab - Annotation Fields Mapping) and also mapped all of the problems with dropdowns here -- https://docs.google.com/spreadsheets/d/18xCuXuxQSbxlhxUgufNWLiLO_V22wh3pd7oC0Q8Ts1k/edit#gid=852958550 (tab - Dropdowns to fix). Were any of these maps used? Which annotation code list were you provided with? It looks like you were given the info in Column A as the code list, but I don't know where that came from? Is that from the annotation template that Anders used to develop clusters?

**Comment by KaitlinCCSI** [comment]
@anjesh @anderspeders We mapped them in Column E per discussion with Anders today. Anders, note that on closer inspection, it looks like Column F is essentially what is missing from Column D - so presumably there is nothing that we have to do for Column F. Please let me know if that is incorrect. Please also let me know if there is anything else that needs to be done at this time for mapping. 

(ALSO, note that because we decided to not make any changes to Column B, there are a few things that are not optimal for OLC or RC. We are okay with this for the OLC launch, but note that things like Cost Oil/Profit Oil might want to be fixed before RC re-launch per the suggestions in the Dropdowns to fix tab of the document I included above; it will otherwise look messy.) @jedm @samccsi

**Comment by anderspeders** [comment]
Referring this to #402 and closing.
