### ISSUE TITLE
Annotation categories should hyperlink

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#338]
![image](https://cloud.githubusercontent.com/assets/1101585/9951364/870073dc-5d93-11e5-8bad-e031a9aed19e.png)

**Comment by anjesh** [comment]
This will hyperlink to the annotations at the bottom of the page.

**Comment by anjesh** [comment]
These are now linked to the annotations at the bottom of the page, scrolls to that particular annotation.
