### ISSUE TITLE
Enable data load with additional metadata categories for load template

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#339]
See email.

**Comment by anjesh** [comment]
Do you mean Open Oil import template?

**Comment by anderspeders** [comment]
Yes, we will expand this to allow for other users to add contracts in a similar way. 

Our use case is a researcher who will collect 50 contracts, add the URL regerence to PDF and provide metadata in the spreadsheet. Doing this in spreadsheet is much faster than through the platform - thus we need to simply expand template to include all or near all metadata categories. 

I assume that as long as the headers are titled precisely *and* correct codelists are applied - this will be a small task?

**Comment by anderspeders** [comment]
Moving this priority to past OLC launch.

**Comment by anjesh** [comment]
There are the fields proposed by @anderspeders  for the import template. Multiple-value fields are to be separated by comma in each column, e.g. resource will have coal,oil. We have excluded the supporting documents and parent documents from the template as it's not possible to link them with the imported contract. Ideally IDs of these contracts would be needed for linkage. Or use of title would be prone to mistakes as we need to make sure that these contracts are available in the system.

* contract_name
* country
* type_of_contract
* resource
* company_name
* corporate_group
* company_address
* company_number
* open_corporate_id
* PDF URL
* signature_date
* language
* disclosure_mode
* date_retrieval
* project_title
* project_identifier
* license_name
* license_identifier
* government_entity
* parent_document (excluded from template)
* supporting_contracts (excluded from template)

**Comment by anjesh** [comment]
The following text to be updated in the import page

![image](https://cloud.githubusercontent.com/assets/120488/10505610/ded46630-732e-11e5-8a63-af8e28cf37a4.png)

Open Oil Contract Import should be "Contract Bulk Import"

Put the following instruction instead of 
> Please make sure that the csv file follows the following format.

New instruction in import page

> Please make sure that the csv file follows the following  &lt; link to file &gt; format. Also ensure that the multi-value fields are separated by || ( &lt;link to http://kb.mailchimp.com/merge-tags/using/where-to-find-the-pipe-key&gt; douple pipe&lt;link&gt; ), for example if the contract has two resources - Coal and Oil, resource column should be "Coal||Oil". 

cc @manishgs

**Comment by anjesh** [comment]
@anderspeders please verify and reopen if any issue.
