### ISSUE TITLE
Create annotation workflow

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#34]
As an administrator I wish to ensure that an annotator (eg graduate student) will be going through all 20 steps of the annotation process (each step being a tag that must be identified in the contract and summarized in text).

**Comment by anjesh** [comment]
can we differentiate "tag" as free-text field and bring in "category" which consists to list of options once this list from #32 is finalized. annotatorjs has categories functionality, still needs to be researched. currently one of the pre-filled strings are auto-suggested during tagging in annotation.

**Comment by anjesh** [comment]
Duplicate of #112
