### ISSUE TITLE
Change annotation header - left bar

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#342]
![image](https://cloud.githubusercontent.com/assets/1101585/9961593/414243d2-5def-11e5-93e7-6fb70502a234.png)

**Comment by anderspeders** [comment]
![image](https://cloud.githubusercontent.com/assets/1101585/9961804/886143ca-5df0-11e5-8752-6e70c2bf8a75.png)

**Comment by anderspeders** [comment]
The annotation header should folow the design on the right bar - eg. for "Country".

**Comment by jedm** [comment]
Please note this has been clarified and spec-ed in a more recent mockup.

**Comment by jedm** [comment]
Please see #373

**Comment by jedm** [comment]
Amended in #389 and #390. Also see #373

**Comment by byndcivilization** [comment]
handled a bunch of this in pull request

**Comment by byndcivilization** [comment]
handled a bunch of this in pull request

**Comment by anjesh** [comment]
Duplicate. Fixed nonetheless.
