### ISSUE TITLE
PDF is not loading - or loading extremely slowly

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#343]
http://alpha.resourcecontracts.org/contract/838/view#/pdf

**Comment by anderspeders** [comment]
cc @byndcivilization

**Comment by anjesh** [comment]
This is because the pdf/text are not published in the admin. Now in such case appropriate message will be displayed "There seems to be problem with the contract text. Please contact administrator with the url."

**Comment by anderspeders** [comment]
Contracts which are published still load slowly - for example: http://alpha.openlandcontracts.org/contract/681/view

**Comment by anderspeders** [comment]
Hi @anjesh, 

Please double check this. We have multiple reports from testers that contracts - whcih have been published - are loading slow or not at all. 

It is correct that *once you browse* the contract pages will appear. However the fact that the first PDF load is incomplete is deal braker and need high priority. 

from slack conversation with @byndcivilization:
a react issue
cperry [4:09 PM]
[Error] TypeError: null is not an object (evaluating 'prevComponentInstance._currentElement')
    perform (react-with-addons.js, line 18419)
    batchedUpdates (react-with-addons.js, line 9669)
    enqueueUpdate (react-with-addons.js, line 16738)
    enqueueUpdate (react-with-addons.js, line 16256)
    enqueueForceUpdate (react-with-addons.js, line 16379)
    forceUpdate (react-with-addons.js, line 6439)
    text (view, line 45)
    (anonymous function) ([native code], line 0)
    e (director.min.js, line 7)
    f (director.min.js, line 7)
    invoke (director.min.js, line 7)
    h (director.min.js, line 7)
    dispatch (director.min.js, line 7)
    handler (director.min.js, line 7)
    d (director.min.js, line 7)

**Comment by anderspeders** [comment]
Hi @anjesh, 

After checking today I have received another report on this for the following contracts below. I published manually their PDF-docs from the backend - but still did not have a result. Can you confirm what the issue is? 

http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/1027/view

http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/1039/view

http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/1022/view

http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/1041/view

http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/1047/view

http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/1042/view

cc @byndcivilization

**Comment by KaitlinCCSI** [comment]
For the message when a contract won't open:

Ideally we could simply say "We're sorry, there is a problem loading the contract. Please click here to let us know." And the "click here" would automatically send a message to the designated person letting us know there is an issue with that specific contract. Is that possible? 

If possible but too time-consuming for this sprint, I suggest that (1) for this sprint, we change the message to "We're sorry, there is a problem loading the contract. Please contact <info@openlandcontracts.org> to let us know, or check back later." and then (2) for next sprint, we build this second better option (allowing the user to click something to report the error) for both OLC and RC. cc @jedm

**Comment by byndcivilization** [comment]
Looks good to me. Closing. If anyone has issue reopen. Thanks!
