### ISSUE TITLE
Add spacing around dots - 

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#344]
![image](https://cloud.githubusercontent.com/assets/1101585/9961834/aefd4c4a-5df0-11e5-89dc-56e8afdb66b4.png)

**Comment by jedm** [comment]
Please note there is an updated version of this specification sent in PDF more recently.

**Comment by jedm** [comment]
I believe this is superseded by #373.

**Comment by byndcivilization** [comment]
@anderspeders means the elipses.

**Comment by jedm** [comment]
Spacing was added in front but not at end of ellipsis. So... technically still wrong grammatically but maybe not the end of the world.

**Comment by byndcivilization** [comment]
splitting will tend to make "..." and "more" show up on different lines

**Comment by jedm** [comment]
Just add a nobr tag to the code.

**Comment by byndcivilization** [comment]
So we have a single line with "... More"? I thought we were worried about space.

**Comment by jedm** [comment]
No need for this level of backy-forthy. Like I said above, probably not the biggest deal but not grammatical use of ...

...
