### ISSUE TITLE
Right bar - contract page

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#345]
![image](https://cloud.githubusercontent.com/assets/1101585/9963032/f1d87b10-5df6-11e5-8edc-74307444adde.png)

**Comment by anderspeders** [comment]
This bar needs to be permanent - not drop down.

**Comment by jedm** [comment]
Please note there is an updated version of the bottom element, the "related docs"

**Comment by anderspeders** [comment]
Thanks @jedm, Could you link to this or upload?

**Comment by jedm** [comment]
Just logged off and won't be back online until noon ET. But you can pull this easily from the most recent PDF we sent!

**Comment by jedm** [comment]
Anders could you upload this one with the instructions? Thanks!

**Comment by anjesh** [comment]
Under related docs, i see there will be three different types.
1. parent/child - here we can list the contracts that are available.
2. By country - here also do we want to list the contracts or link to country-search page where that country is already selected. If show contracts list, how many contracts to show there.
3. by resource - same as by country? How many to show or just link to the search page. 

How many contracts will we be displaying in that related docs list. The contract title could be long as well, we might need to trim the length. Thoughts?

**Comment by jedm** [comment]
Dear Anjesh - we provided this guideline a few days ago. Please take a look and I'm happy to answer any questions about it.

Two questions right away:

- Please confirm that the meaning of parent/child contracts has been explained to YI previously.
- Good question about titles. I think it would be fine to either use 2 lines for long titles OR to limit the titles to X characters followed by a space and three dots (with the full title appearing on hover). YI should do whichever one you think is better.

![right_column](https://cloud.githubusercontent.com/assets/2153664/10078932/2483ec1c-629c-11e5-927a-61231edca741.jpg)

**Comment by anjesh** [comment]
This looks clear.

**Comment by byndcivilization** [comment]
dealt with in pull request
