### ISSUE TITLE
Left bar: Add hyperlink to "see all annotations" at bottom of annotation list

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#346]
![image](https://cloud.githubusercontent.com/assets/1101585/9963175/cf1b05f6-5df7-11e5-9e34-8032cadbcb4e.png)

**Comment by jedm** [comment]
Note that this link should be an "anchor link" to the bottom section of the All-Annotations page. 

Click here for example link behavior:

http://rc-site-stage.elasticbeanstalk.com/rc/public/contract/876#undefined

http://rc-site-stage.elasticbeanstalk.com/rc/public/contract/895#undefined

**Comment by anjesh** [comment]
I see this as "Go to top" of the list. That list does show all the annotations. 

Just to be clear, "See all annotations" to take to the contract summary page, anchored to "Annotations list" as mentioned by Jedm. 

Please confirm.

**Comment by jedm** [comment]
(responding via email so I hope this posts legibly.)

This makes sense to me. And Anjesh you make a very good point about "go to top." That is also a useful control. I would suggest including both, "Back to Top" and "All Annotations"

Two other points to remember:

- please make sure icons and use of fonts, sizes for these controls, etc, matches the style and size and look of the other controls on the page and the site. Users will be much more confused without that consistency in style

- even though the left column /is/ all the annotations, it will never show all the text the way the contract summary page does, so this is potentially very useful to people who want to read more/many at once
