### ISSUE TITLE
Add footer in contract page with disclaimer annotations

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#347]
![image](https://cloud.githubusercontent.com/assets/1101585/9963288/7beb865c-5df8-11e5-9949-00a539065ef7.png)

**Comment by jedm** [comment]
Footer should be in footer location at bottom of web page, not below contract viewer box. See example from [ResourceContracts.org](http://www.resourcecontracts.org/#documents?countries=afghanistan) and in attached screenshot.
![footer_disclaimer](https://cloud.githubusercontent.com/assets/2153664/10026180/2bedfce6-6115-11e5-90dd-706b8a6ee9bd.jpg)

**Comment by byndcivilization** [comment]
Is this pushed @anjesh ?

**Comment by byndcivilization** [comment]
@anjesh is this done?

**Comment by KaitlinCCSI** [comment]
Footer disclaimer should read:

This site provides summaries of contracts and their terms to facilitate
understanding of important provisions in the documents. These summaries are
not interpretations of the documents. Neither the summaries nor the full
contracts are complete accounts of all legal obligations related to the
projects in question. This site also includes document text that was
created automatically; such text may contain errors and differences from
the original PDF files. No warranty is made to the accuracy of any content
on this website.

On Wed, Sep 30, 2015 at 10:34 AM, Chris Perry <notifications@github.com>
wrote:

> @anjesh <https://github.com/anjesh> is this done?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/347#issuecomment-144448293>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PnrynoL&m=bfd1c1f5ce7d&t=20150930&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PnrynoL&m=bfd1c1f5ce7d&t=20150930&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01PnrynoL&m=bfd1c1f5ce7d&t=20150930&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by byndcivilization** [comment]
@KaitlinCCSI and does this work or would you rather with text with no box background?
![unknown](https://cloud.githubusercontent.com/assets/2875950/10225141/52eaaf76-682f-11e5-90d9-a81dab0899b7.png)

**Comment by byndcivilization** [comment]
Anyone? @jedm @SamCCSI @KaitlinCCSI ? Would like to push this and some other changes to @anjesh .

**Comment by jedm** [comment]
I suggest no box background. This way lacks design.

**Comment by KaitlinCCSI** [comment]
Sorry, was stuck in meetings/conference all day. Agree with Jed - no box
background would look better.

Also, I've asked this before, but is there any way to make the
About/FAQs/etc more easily accessible? I had previously suggested putting
in the upper right corner, but another option is to put it at the top of
the left expanding column when you click the icon in the top left. I think
either of those are much more logical places than in the footer
(particularly an issue now given the disclaimer that comes above).

On Thu, Oct 1, 2015 at 7:07 PM, jedm <notifications@github.com> wrote:

> I suggest no box background. This way lacks design.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/347#issuecomment-144788382>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PnR7QGa&m=10bc1daa233c&t=20151001&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PnR7QGa&m=10bc1daa233c&t=20151001&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01PnR7QGa&m=10bc1daa233c&t=20151001&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by byndcivilization** [comment]
addressed in pull request

**Comment by byndcivilization** [comment]
I forgot, do we still want to add the footer to contract/annotation view page? @anderspeders @KaitlinCCSI

**Comment by KaitlinCCSI** [comment]
Global footer should be there. And then the ORC disclaimer is now above the text. Thanks.

**Comment by KaitlinCCSI** [comment]
Don't see the disclaimer on any of the pages

**Comment by byndcivilization** [comment]
@anjesh what happened to he code I pushed last week that had this and the more concise meta data navigation.

**Comment by anjesh** [comment]
We have made minor change in the layout of the footer-text - mad left-aligned the text to adjust for the wide screen.

**Comment by KaitlinCCSI** [comment]
Why wouldn't it just stretch across the entire screen? That would look
better.

On Mon, Oct 5, 2015 at 6:38 AM, Anjesh <notifications@github.com> wrote:

> Closed #347 <https://github.com/NRGI/resourcecontracts.org/issues/347>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/347#event-426679705>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PpnC3yk&m=2bc28f0fa9cd&t=20151005&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PpnC3yk&m=2bc28f0fa9cd&t=20151005&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01PpnC3yk&m=2bc28f0fa9cd&t=20151005&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by byndcivilization** [comment]
@anjesh something happened with the css for the footer note. Also @KaitlinCCSI can you confirm that you wanted footer present on contract annotation view pages. Here for example:
http://alpha.openlandcontracts.org/contract/1162/view

**Comment by KaitlinCCSI** [comment]
Yes, want footer at the bottom of the contract view page. Important to have
disclaimer on this page, but I think it's also useful to have the links to
other pages and the logos here.

On Mon, Oct 5, 2015 at 8:57 AM, Chris Perry <notifications@github.com>
wrote:

> @anjesh <https://github.com/anjesh> something happened with the css for
> the footer note. Also @KaitlinCCSI <https://github.com/KaitlinCCSI> can
> you confirm that you wanted footer present on contract annotation view
> pages. Here for example:
> http://alpha.openlandcontracts.org/contract/1162/view
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/347#issuecomment-145535283>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=02PppVFQy&m=38ba4fe079e8&t=20151005&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=02PppVFQy&m=38ba4fe079e8&t=20151005&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=02PppVFQy&m=38ba4fe079e8&t=20151005&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by anderspeders** [comment]
Excellent, @anjesh can you please push the footer through. 

Additionally, should we add a seperate ticket for the following: "Add the links to
other pages and the logos here."

@anjesh @byndcivilization ?

**Comment by KaitlinCCSI** [comment]
@anders I had mentioned that because the other pages and logos are currently in the footer, so I assumed that including the footer on this page would automatically include the links to other pages and the logos. Makes sense to me to have same footer throughout site. If this is the case, then assume no separate ticket needed.

**Comment by anjesh** [comment]
The footer is now added to the contract view page.

**Comment by KaitlinCCSI** [comment]
Fine to close for now, but for sprint 10 can we try to stretch footer text out across footer? I think it would look better. cc @byndcivilization

**Comment by anjesh** [comment]
The footer text is stretched now.

**Comment by KaitlinCCSI** [comment]
Excellent; thanks.
