### ISSUE TITLE
Map "annotation category" to "annotation cluster"

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#348]
More info coming

**Comment by byndcivilization** [comment]
This is linked to #71 and should be trivial to add if you already have that in place. Annotations consist of a) placement informatino and b) content. We have a many (placements) to one (content) relationship here. That relationship is mapped by the annotation category or cluster. We can use that tow hold the data from the "Annotation cluster category" column in the import document.

**Comment by anderspeders** [comment]
Link to the document here - Cluster category is column D: 
https://docs.google.com/spreadsheets/d/1K0wlloEAPFncrNA_mwBjqvW81A5xRpFlK0qlv-j5ZYo/edit#gid=1612543715

**Comment by anderspeders** [comment]
This issue is critical / high priority to get fixed!

**Comment by byndcivilization** [comment]
Just to be clear:
annotations currently contain location information, text content, an id and a category that doubles as an annotation title. The text and category are duplciated across annotations that are tagged to multiple places.

This is wrong.

Annotation should contain location info, an ID and a category that may or may not double as a title.  Category should link to a table on contract_ID + annotation_category. This table will also include text content and optionally the text little if it's easier. 

You will need to make some changes to your templates but it should make things much easier to maintain.

This catogory id can be mapped from the old system.

**Comment by anderspeders** [comment]
This is a high-priority ticket for this sprint.

**Comment by anderspeders** [comment]
Here is the completed liust with Cluster category in **Column A**

**Comment by anderspeders** [comment]
![image](https://cloud.githubusercontent.com/assets/1101585/10035611/34ba41ea-616a-11e5-84fc-4ea0cf397156.png)

@anjesh Have a look at top of the annotation bar for the suggested UI for the various annotation cluster categories. The functionality could enable the user to add one *or* more cluster categories - which would then appear below (for example in alphabetical order by annotation catgeory). 

To briefly repeat it would be excellent to give this high priority. Please let me know if you encounter any blockers from our end.

**Comment by anderspeders** [comment]
@anjesh Do you have an update here? Could you provide a sketch of the design you intend to implement?

**Comment by jedm** [comment]
Will post an updated visual and further specs here.

**Comment by jedm** [comment]
These instructions have been fixed for clarity and elaborated in #389 and #390

**Comment by anjesh** [comment]
We will create a script to go through all the existing annotations in the system to append cluster information in the annotation data model. The same will be reflected in the API.

**Comment by jedm** [comment]
@anderspeders and @anjesh - For better UI/display, we recommended cluster ("Topic") display names to be General, Environment, Fiscal, Social, Operations, Other. @KaitlinCCSI has also confirmed this is ok for CCSI. Can this be the standard for front-end display of cluster names?

**Comment by anjesh** [comment]
Yes the names and the order will be followed in the front-end display.

**Comment by anjesh** [comment]
The topic order is followed now and also shortened names used.
