### ISSUE TITLE
Pick list for corporate group for metadata form

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#35]
As a document uploader I would like to have a pick list from where I can match the company to a corporate group. 

For example: 
The <company>  Conoco Philips local Australian company is part of the <corporate_group> Conocophilips

Link: 
https://s3.amazonaws.com/s3.documentcloud.org/documents/804727/psc-jpda-03-13.pdf

**Comment by anjesh** [comment]
Duplicate of #132
