### ISSUE TITLE
Bug metadata edits

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#350]
EITI Philippines have encountered issues editing metadata for the following documents:
1. SR Metals, Inc. 
2. Greenstone Resources Corporation
3. Pacific Nickel Philippines, Inc. 

This message appears when they try to open it:
"Whoops, looks like something went wrong."

**Comment by anjesh** [comment]
These were contracted uploaded quite sometime back. With the change in the metadata structure (like making government entity "add more", and intro of new metadata) sometimes break the existing pages. Though we run the script to ensure that all the contracts datamodel are as per new structure, there are some misses. We also put in place proper error catch in different places when new metadata are introduced and some get missed during the process. Thanks for pointing this out, we have fixed for these contracts. I quickly submitted-edit without making any changes and it's working. 

Please confirm and close if it's working at your end.

**Comment by anderspeders** [comment]
Thanks - let's close this. I will reopen if relevant.
