### ISSUE TITLE
Crop image for OpenLandContracts

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#352]
Request from @SamCCSI. 

Can you confirm that you will incorporate our previous request to move the
position of the background photo so that it shows 50% sky, 50% land, rather
than right now, which shows only sky?

(Also the photo seems to load slowly, but I'm not sure if compression is
available without harming the quality of the photo; interested in your
thoughts)

@samCCSI: There are two options here - either CCSI crop it (with your designer? and you are sure you get it right) - or YI spend the time on it (and we risk that we need to adjust again).

I am happy with either but just wanted to flag this.

**Comment by SamCCSI** [comment]
Hi Anders,

Unfortunately our designer's contract has ended for now, so it would be
quite administratively burdensome to have him look at it.

It would be great if YI could attempt (they have designers on staff,
right?). It's a land contract site so we need to have some land showing on
the home page.

If it's still not what we are hoping for, we will ask you for the
dimensions and try cropping ourselves, but I'm reluctant to go straight to
this option, as we don't have a graphic design background.

Sam

On Mon, Sep 21, 2015 at 8:43 PM, Anders <notifications@github.com> wrote:

> Request from @SamCCSI <https://github.com/SamCCSI>.
>
> Can you confirm that you will incorporate our previous request to move the
> position of the background photo so that it shows 50% sky, 50% land, rather
> than right now, which shows only sky?
>
> (Also the photo seems to load slowly, but I'm not sure if compression is
> available without harming the quality of the photo; interested in your
> thoughts)
>
> @samCCSI <https://github.com/samCCSI>: There are two options here -
> either CCSI crop it (with your designer? and you are sure you get it right)
> - or YI spend the time on it (and we risk that we need to adjust again).
>
> I am happy with either but just wanted to flag this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/352>.
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by anjesh** [comment]
No Problem. We will fix this, also the size is pretty big - taking time to load the page, we will also optimize the image without losing the details.

**Comment by SamCCSI** [comment]
Wonderful, thanks Anjesh!



On Sep 22, 2015, at 8:07 AM, Anjesh <notifications@github.com> wrote:

No Problem. We will fix this, also the size is pretty big - taking time to
load the page, we will also optimize the image without losing the details.

—
Reply to this email directly or view it on GitHub
<https://github.com/NRGI/resourcecontracts.org/issues/352#issuecomment-142187974>
.

**Comment by anderspeders** [comment]
Thanks Anjesh.

**Comment by anjesh** [comment]
The image is cropped and now sized at 651KB.
