### ISSUE TITLE
UI tweaks to IE11 version - plus full IE11 review

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#353]
![image](https://cloud.githubusercontent.com/assets/1101585/10002861/75ea8a7e-6077-11e5-9e74-3f52dc4fcbe5.png)

**Comment by byndcivilization** [comment]
@anjesh and @sweetanzell can you tell us where you are on this. I think its a bigger issue than Safari fail.

**Comment by byndcivilization** [comment]
@anderspeders can you look at this. It looks like everything works though im not showing annotations on browsersstack.

**Comment by byndcivilization** [comment]
Looks good to me. Anyone comes across anything you can open it back up. Thanks!
