### ISSUE TITLE
Remove contract from back end

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#354]
This test contract has been removed from backend - but somehow still appear on the site: 
http://alpha.openlandcontracts.org/contract/14/view 

![image](https://cloud.githubusercontent.com/assets/1101585/10003098/c88cb0ee-6078-11e5-9115-96675e7006cd.png)

Please remove this contract

**Comment by anjesh** [comment]
Related to https://github.com/NRGI/resourcecontracts.org/issues/351
