### ISSUE TITLE
UI issue with Safari

### ISSUE THREAD

**Issue by byndcivilization** [NRGI/resourcecontracts.org#355]
Contracts not loadiing. 

Console message:
    [Error] TypeError: undefined is not a function (evaluating '$('select').select2({placeholder: "Select", allowClear: true, theme: "classic"})')
	    (anonymous function) (script.js, line 2)
	    j (jquery.min.js, line 2)
	    fireWith (jquery.min.js, line 2)
	    ready (jquery.min.js, line 2)
	    I (jquery.min.js, line 2)
    [Warning] You are using the in-browser JSX transformer. Be sure to precompile your JSX for production - http://facebook.github.io/react/docs/tooling-integration.html#jsx (JSXTransformer.js, line 314)
    [Error] SyntaxError: Unexpected token '('. Expected a ':' following the property name 'getDefaultProps'.
	    appendChild (view, line 23)
	    run (JSXTransformer.js, line 184)
	    check (JSXTransformer.js, line 238)
	    (anonymous function) (JSXTransformer.js, line 273)
	    onreadystatechange (JSXTransformer.js, line 208)
    [Error] ReferenceError: Can't find variable: Waypoint
	    perform (react-with-addons.js, line 18419)
	    batchedUpdates (react-with-addons.js, line 9669)
	    enqueueUpdate (react-with-addons.js, line 16738)
	    enqueueUpdate (react-with-addons.js, line 16256)
	    enqueueForceUpdate (react-with-addons.js, line 16379)
	    forceUpdate (react-with-addons.js, line 6439)
	    (anonymous function) (view, line 142)
	    triggerEvents (backbone.js, line 353)
	    triggerApi (backbone.js, line 339)
	    eventsApi (backbone.js, line 137)
	    trigger (backbone.js, line 329)
	    reset (backbone.js, line 900)
	    success (backbone.js, line 991)
	    fire (jquery.js, line 1037)
	    fireWith (jquery.js, line 1148)
	    done (jquery.js, line 8074)
	    callback (jquery.js, line 8598)

**Comment by byndcivilization** [comment]
Also pdf and text side by side does not look to be resposive at all. Browser is pretty wide and PDF is showing that it would render below.

**Comment by byndcivilization** [comment]
![unknown](https://cloud.githubusercontent.com/assets/2875950/10003671/a7b16970-607b-11e5-9143-c589e22171d0.png)

**Comment by anjesh** [comment]
Linked to https://github.com/NRGI/resourcecontracts.org/issues/351

**Comment by joy-jingwei** [comment]
I encountered this problem again

**Comment by jedm** [comment]
Me too.

**Comment by byndcivilization** [comment]
working for me

**Comment by jedm** [comment]
I am on Safari 8.0.8 on OSX 10.10.5

**Comment by byndcivilization** [comment]
same

**Comment by jedm** [comment]
Happy to send screen shots if that helps!

**Comment by byndcivilization** [comment]
Can you see if any errors are showing up in the console?

**Comment by jedm** [comment]
will play with it and send any errors I see

**Comment by anjesh** [comment]
Thanks. This will be fixed, we are working mostly on Chrome and Firefox for the recent changes. We will ensure that safari and some new versions of IE are also taken care of once the changes are set.

**Comment by byndcivilization** [comment]
Broke for me now.

**Comment by anderspeders** [comment]
Just adding here that IE is important to cover as gov officials will often be using IE.

**Comment by byndcivilization** [comment]
Seems to work but is slow. Anyone else?

**Comment by jedm** [comment]
Just tried and what I get is:
- page 1 never loads, just continues to display the "Loading page 1..." message
- however, when I click the pagination arrow in top bar, it goes to page 2 and page 2 loads (a little slowly, but loads)
- then when I click the pagination arrow back to page 1, page 1 does load

So it seems to be something about the first load of the PDF view (similar to the prior bug where all the annotations boxes pooled on the first page of pdf maybe?)

Had the same experience with the 2 contracts below - one very small doc, the other bigger:

http://alpha.resourcecontracts.org/contract/840/view
http://alpha.resourcecontracts.org/contract/903/view

**Comment by byndcivilization** [comment]
confirmed that this is remaining issue @anjesh 

This is error message:
[Error] TypeError: undefined is not a function (evaluating '$('select').select2({placeholder: "Select", allowClear: true, theme: "classic"})')
	(anonymous function) (script.js, line 2)
	j (jquery.min.js, line 2)
	fireWith (jquery.min.js, line 2)
	ready (jquery.min.js, line 2)
	I (jquery.min.js, line 2)
[Warning] You are using the in-browser JSX transformer. Be sure to precompile your JSX for production - http://facebook.github.io/react/docs/tooling-integration.html#jsx (JSXTransformer.js, line 314)
[Error] SyntaxError: Unexpected token '('. Expected a ':' following the property name 'getDefaultProps'.
	appendChild (view, line 23)
	run (JSXTransformer.js, line 184)
	check (JSXTransformer.js, line 238)
	(anonymous function) (JSXTransformer.js, line 273)
	onreadystatechange (JSXTransformer.js, line 208)
[Log] sl (view, line 174)
[Error] ReferenceError: Can't find variable: Waypoint
	perform (react-with-addons.js, line 18419)
	batchedUpdates (react-with-addons.js, line 9669)
	enqueueUpdate (react-with-addons.js, line 16738)
	enqueueUpdate (react-with-addons.js, line 16256)
	enqueueForceUpdate (react-with-addons.js, line 16379)
	forceUpdate (react-with-addons.js, line 6439)
	(anonymous function) (view, line 207)
	triggerEvents (backbone.js, line 353)
	triggerApi (backbone.js, line 339)
	eventsApi (backbone.js, line 137)
	trigger (backbone.js, line 329)
	reset (backbone.js, line 900)
	success (backbone.js, line 991)
	fire (jquery.js, line 1037)
	fireWith (jquery.js, line 1148)
	done (jquery.js, line 8074)
	callback (jquery.js, line 8598)
[Error] TypeError: null is not an object (evaluating 'prevComponentInstance._currentElement')
	perform (react-with-addons.js, line 18419)
	batchedUpdates (react-with-addons.js, line 9669)
	enqueueUpdate (react-with-addons.js, line 16738)
	enqueueUpdate (react-with-addons.js, line 16256)
	enqueueForceUpdate (react-with-addons.js, line 16379)
	forceUpdate (react-with-addons.js, line 6439)
	pdf (view, line 84)
	(anonymous function) ([native code], line 0)
	e (director.min.js, line 7)
	f (director.min.js, line 7)
	invoke (director.min.js, line 7)
	h (director.min.js, line 7)
	dispatch (director.min.js, line 7)
	handler (director.min.js, line 7)
	d (director.min.js, line 7)

**Comment by anjesh** [comment]
Please verify. Contract view UI in safari is now working.

**Comment by byndcivilization** [comment]
Working for me. Closing. If anyone has issues reopen. Thanks!

**Comment by jedm** [comment]
This is not working for me on RC (alpha) or OLC (live). Clicking into a specific contract gets a blank page with footer. (Safari 8.0.8, OS X 10.10.5)

http://alpha.resourcecontracts.org/contract/ocds-591adf-MA4899997941RC/view
http://alpha.resourcecontracts.org/contract/ocds-591adf-BI3799217198RC/view
http://www.openlandcontracts.org/contract/ocds-591adf-CD4492231156OL/view
http://www.openlandcontracts.org/contract/ocds-591adf-ET3081396501OL/view

![screen shot 2015-10-24 at 6 42 58 pm](https://cloud.githubusercontent.com/assets/2153664/10713639/f3354d4a-7a7e-11e5-89d2-92f3d85faec8.jpg)

**Comment by anjesh** [comment]
Created new issue https://github.com/NRGI/resourcecontracts.org/issues/591 for safari issue. Closing this.
