### ISSUE TITLE
Zoom in contract view is not intuitive

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#356]
![image](https://cloud.githubusercontent.com/assets/1101585/10003487/b1bbd4d8-607a-11e5-8c08-ec3db46ecd86.png)

- How do I zoom in and out? This does not appear logitical? What is bet practise here?

**Comment by byndcivilization** [comment]
@anjesh moving this to next sprint unless you have a fix ready.

**Comment by anderspeders** [comment]
Zoom function is now updated. Closing this.

**Comment by KaitlinCCSI** [comment]
This still doesn't seem intuitive to me -- intuitive would be the ability
to slide the circle along the bar. (Or at the very least being able to
click on the - / + at the end of the bars.) I just checked on OLC and the
Alpha RC site, and I still can't do that - the only way it works is by
clicking on the 3 little lines or the 3 little circles.

This is fine for now but it should be fixed and made more intuitive in
sprint 11.

On Sun, Oct 18, 2015 at 1:54 PM, Anders <notifications@github.com> wrote:

> Zoom function is now updated. Closing this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/356#issuecomment-149038327>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PuGSgTC&m=9e942a3ad217&t=20151018&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PuGSgTC&m=9e942a3ad217&t=20151018&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01PuGSgTC&m=9e942a3ad217&t=20151018&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by KaitlinCCSI** [comment]
Reopened - zoom still needs to be more intuitive as previously described.

**Comment by charlesyoung** [comment]
The annotation box remains where it is, so when the document is zoomed, the box is misplaced as shown below. 

![image](https://cloud.githubusercontent.com/assets/13888372/11581391/31194e46-9a4a-11e5-9453-deaba4b13093.png)


![image](https://cloud.githubusercontent.com/assets/13888372/11581425/89864110-9a4a-11e5-9a02-a5c3dbf095e4.png)

**Comment by sadhakbj** [comment]
Zoom feature has been improved and has been deployed in demo sub site. Please check it once.

http://rc-site-demo.elasticbeanstalk.com/rc/public/contract/ocds-591adf-NG5057885784RC/view#


![100](https://cloud.githubusercontent.com/assets/5828622/12714107/cb60e868-c8fa-11e5-9665-d363e31b8f8e.png)
![150](https://cloud.githubusercontent.com/assets/5828622/12714106/cabf7b22-c8fa-11e5-963f-6b677853f51d.png)

**Comment by KaitlinCCSI** [comment]
I think this works better than older version; thanks.

On Mon, Feb 1, 2016 at 4:01 AM, Bijaya Prasad Kuikel <
notifications@github.com> wrote:

> Zoom feature has been improved and has been deployed in demo sub site.
> Please check it once.
>
>
> http://rc-site-demo.elasticbeanstalk.com/rc/public/contract/ocds-591adf-NG5057885784RC/view#
>
> [image: 100]
> <https://cloud.githubusercontent.com/assets/5828622/12714107/cb60e868-c8fa-11e5-9665-d363e31b8f8e.png>
> [image: 150]
> <https://cloud.githubusercontent.com/assets/5828622/12714106/cabf7b22-c8fa-11e5-963f-6b677853f51d.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/356#issuecomment-177886363>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01QcW1hQb&m=a7faf47cc882&t=20160201&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01QcW1hQb&m=a7faf47cc882&t=20160201&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01QcW1hQb&m=a7faf47cc882&t=20160201&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by sadhakbj** [comment]
It has been implemented on stage.
