### ISSUE TITLE
Review of OLC - resources list

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#357]

**Comment by anjesh** [comment]
map the existing resource of OLC with the column C of this excel file https://docs.google.com/spreadsheets/d/18xCuXuxQSbxlhxUgufNWLiLO_V22wh3pd7oC0Q8Ts1k/edit#gid=1902348188
And update the resourcelist in the admin with the column C

**Comment by anjesh** [comment]
The resources codelist is fixed, and also the contracts resources are updated as per the new codelist.
