### ISSUE TITLE
Front end: document repository for all contracts - incl. non-OCR'ed

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#36]
As a user I would like an overview of all contracts that RC.org is hosting - including both: 
1) contracts which are waiting to go through the OCR-workflow - thus still in PDF format
2) contracts which have been OCR'ed and approved

Reasoning: 
We have reasons to belive that the OCR-process will in some cases take time for contracts - for example if the manual editing will take significant time. Therefore, in order to ensure that we allow for as full availability as possible, we should ensure that there is a view for all contracts - including those only available as PDF. 

this could be something as a document list searchable by key metadata. 

@byndcivilization any thoughts?

**Comment by anjesh** [comment]
This will taken by by the publishing workflow #75. The admin can choose to publish the contract metadata only, in which case only the metadata will be available for view and search in different subsites, but not the annotation and pdf-text. Nevertheless the full pdf will be available for download.
