### ISSUE TITLE
Need to grant access to "publish all" button to annotators

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#360]
Thanks for creating the "publish all" functionality in the metadata section for reviewers. 

1.
We now want our annotators to have access to the "publish all functionality" - this will greatly speed up our workflow and result in more contracts and metadata will be published more quickly. CCSI will still be reviewing each entry, but want those entering in the metadata to integrate our comments and publish straight away.

2.
In addition a bunch of contracts have been reviewed already but haven't been published yet because the workflow and website were under development. We can ask the uploader to go one by one and publish it all (provided that he gets the right to do so) but it will at the expense of uploading more contracts. Ideally, there would be a way to override the manual process and have an automatic publish all.

**Comment by SamCCSI** [comment]
Hi @anderspeders @anjesh is there an update available on 1 and 2 above?

cc @KaitlinCCSI

**Comment by anjesh** [comment]
Ok. we will have the "publish all" feature to the annotators as well.

**Comment by sadhakbj** [comment]
- Implemented now. Currently I am logged in as Research Associate and i have access to publish.

![publish_all](https://cloud.githubusercontent.com/assets/5828622/13067878/75139178-d49d-11e5-8d84-50380db84cd9.png)
