### ISSUE TITLE
Re-oreder appearence of metadata

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#362]
![image](https://cloud.githubusercontent.com/assets/1101585/10024088/8068408e-6123-11e5-9bc3-56832903d663.png)
 
1) Suggesting the following order to appear in the following order: 

Country | Year | Resource | Contract type

2) Please note that all metadata should have headers - following the current format for Resource and Contract type.

**Comment by anjesh** [comment]
@anjhero please have a look at this. Also need to optimize some white space there.

**Comment by anjesh** [comment]
@anderspeders this is what we are thinking now for the list page.

http://easier.cc/view/b53cd4a2
![image](https://cloud.githubusercontent.com/assets/120488/10095787/14dc5f74-638c-11e5-95c3-e9cf37b9f2a0.png)
