### ISSUE TITLE
Add hyperlinks to metadata in contract view page

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#364]
![image](https://cloud.githubusercontent.com/assets/1101585/10024257/5b4977fe-6124-11e5-81e9-e9e19a3ae40e.png)

**Comment by jedm** [comment]
What do these link to?

**Comment by anjesh** [comment]
Link to the search results page with that selected option ?

**Comment by jedm** [comment]
I would recommend that is unnecessary. Don't we want to drive people to the contract summary with the full metadata for THIS contract?

Standard IA would say if they got all the way to this page they will be more interested in going deeper than in jumping up 2 levels to a general list. I am happy to be overruled on this however. @anderspeders @byndcivilization @samccsi what do you think?

**Comment by anderspeders** [comment]
@jedm: Good point that we do not want to route away from the contract page. 

I suggest that we remove from priority list for this pre-launch sprint and review later if this is something we want. 

@anjesh: I am removing this from the sprint and parking it under blue sky / wish list.

**Comment by SamCCSI** [comment]
Agree having this extra panel is prob not necessary and makes page more busy / confusing for user.

The one advantage I could see is if the hyperlink acts like an annotation and links to the page from which the metadata info was taken. Eg. "Signature year" links to page 2 of that contract, where the date is contained. But most metadata categories are already listed as annotations, so would advise against it.

**Comment by jedm** [comment]
@SamCCSI, thanks. I'd say the right column is still quite necessary as it will be the main location of the metadata on each contract's page. But I very much agree with your point that a link from this column/panel to the full "contract summary" page with all the additional data is important to have (above the scroll) in this right column.

**Comment by anjesh** [comment]
Contract view page has links.
