### ISSUE TITLE
Add subheader to search front page

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#365]
This is a suggestion but pending conversation with CCSI: 

Search for example "environmental impact assessment" [hyperlink: http://alpha.openlandcontracts.org/search?q=%22environmental+impact+assessment%22] or Sugar cane [hyperlink: http://alpha.openlandcontracts.org/search?q=Sugarcane] 

![image](https://cloud.githubusercontent.com/assets/1101585/10024347/ceb59e98-6124-11e5-90d1-192bc4ad2adf.png)

**Comment by anderspeders** [comment]
I am unsure what this relates to. 

@samCCSI @KaitlinCCSI: Do you recall?

**Comment by KaitlinCCSI** [comment]
Anders, I think you had suggested it to provide alternative pathways for people to access interesting groups of contracts (I think you had just used OLC b/c it was launching first). Don't see this as a priority. 

(However, I do see as a high priority providing a clear path to the advanced search page from the home page, which we don't yet do.)

**Comment by anderspeders** [comment]
Thanks @KaitlinCCSI, 

On the issue of a path to advanced search we have: https://github.com/NRGI/resourcecontracts.org/issues/524

I am therefore closing this.
