### ISSUE TITLE
Streamline visual identity of "search" function in contract view to annotation 

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#367]
![image](https://cloud.githubusercontent.com/assets/1101585/10035511/03a82c26-6169-11e5-99ab-86ba49502eab.png)

Could this in visual terms appear a bit more like the annotations - eg. by using the same round dots for each search result.

**Comment by KaitlinCCSI** [comment]
@anderspeders  - not sure what you mean by round dots, but #373 asks for green dots to be removed if they do not serve a function. @jedm, any thoughts?

**Comment by byndcivilization** [comment]
@KaitlinCCSI I think we decided to keep the dots.

**Comment by jedm** [comment]
Dots should be removed. There's too little space available to waste it.

**Comment by byndcivilization** [comment]
We need something to differentiate. Otherwise the text tends to flow together.

**Comment by jedm** [comment]
I suggest a color change to the Annotation Title, so that each new Annotation (or result in Search results) pops out.

(Highlighting the matched word in Search still useful too.)

**Comment by byndcivilization** [comment]
Looks good except there is some inconsistencies in page displays:

![unknown-5](https://cloud.githubusercontent.com/assets/2875950/10174926/45d6688c-66ba-11e5-9216-b5de356ba106.png)

**Comment by SamCCSI** [comment]
I'm coming in late to this one but wanted to point out various errors in
spelling in those annotations - they look as though they are auto-generated
from OCR text that has not been MT'ed?

Eg. Heng YL'E (should be Heng Yue)
Eg. IN7EXNA7IONAL (should be International)

Let me know if I should log as a separate issue

On Tue, Sep 29, 2015 at 2:56 PM, Chris Perry <notifications@github.com>
wrote:

> Looks good except there is some inconsistencies in page displays:
>
> [image: unknown-5]
> <https://cloud.githubusercontent.com/assets/2875950/10174926/45d6688c-66ba-11e5-9216-b5de356ba106.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/367#issuecomment-144156083>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by anderspeders** [comment]
@SamCCSI Thanks for catching. Can you log under #402?

**Comment by SamCCSI** [comment]
I'm thinking this might just have been a mock-up of annotations and that
those typos are annotation text, not category text. If so, this is not an
issue, as the errors are just copied from OCR that hasn't been MT'ed.
@*byndcivilization
<https://github.com/byndcivilization> does that sound right?*

On Tue, Sep 29, 2015 at 3:21 PM, Anders <notifications@github.com> wrote:

> @SamCCSI <https://github.com/SamCCSI> Thanks for catching. Can you log
> under #402 <https://github.com/NRGI/resourcecontracts.org/issues/402>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/367#issuecomment-144161651>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by byndcivilization** [comment]
Annotations aren't OCRed or mturked. I think those search results are on contract text.

**Comment by anderspeders** [comment]
@SamCCSI yes, just looking again at these. The displayed image is search results in the OCR-test and thus these will have errors from time to time.

**Comment by SamCCSI** [comment]
Thanks, I'm in the process of noting all contracts that we will hide text
view (because not yet MTed) so presumably there wont be search results for
those contracts, and hence no chance of ugly pre-MT text?

cc @kaitlinccsi

On Tue, Sep 29, 2015 at 3:38 PM, Anders <notifications@github.com> wrote:

> @SamCCSI <https://github.com/SamCCSI> yes, just looking again at these.
> The displayed image is search results in the OCR-test and thus these will
> have errors from time to time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/367#issuecomment-144166529>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by anjesh** [comment]
The search results will still appear, as we are hiding the text with "Show text" option only. We will fix the search result as well. Thanks for pointing it out.

**Comment by jedm** [comment]
Would be useful to know if the temporary fix involves omitting the raw text from searches on a per-contract basis or using some other method.

(And per a question to Anders a few weeks ago, would be good to have confirmation of what is being searched by default (i.e., Annotation text, Annotation titles, Metadata categories, Clusters) and with what weighting. Explanation of this highly useful but not urgent to launch at all.)

**Comment by anjesh** [comment]
Right now the search in the contract view page is to search the pdf-text only, and clicking will scroll to the particular page. I haven't had any discussion regarding searching annotations and metadata. cc @anderspeders

**Comment by jedm** [comment]
It would be a surprise if Annotation text is not being searched, since it is of especially high value because it's been created via expert review. Please do confirm at your convenience what is searched and what is not. (Also, by pdf-text do you mean OCR text or something else?)

Again, this is important to understand but not time-sensitive.

**Comment by anjesh** [comment]
By pdf-text, i mean OCR text. Lets discuss what else to expose in this search. Taking off Sprint 9.

**Comment by anjesh** [comment]
@anderspeders so we need to have search for annotation as well in the current search box 

![image](https://cloud.githubusercontent.com/assets/120488/10446817/66501466-719e-11e5-8b42-2add672a253c.png)

Currently it searches only OCR text (if available), now with annotations, they will be listed side-by-side differentiated with annotation and text icons besides the results.

**Comment by SamCCSI** [comment]
cc @kaitlinccsi

On Tue, Oct 13, 2015 at 1:50 AM, Anjesh <notifications@github.com> wrote:

> @anderspeders <https://github.com/anderspeders> so we need to have search
> for annotation as well in the current search box
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/120488/10446817/66501466-719e-11e5-8b42-2add672a253c.png>
>
> Currently it searches only OCR text (if available), now with annotations,
> they will be listed side-by-side differentiated with annotation and text
> icons besides the results.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/367#issuecomment-147613110>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by KaitlinCCSI** [comment]
Can you provide a mockup of what this will look like? Unclear to me.

**Comment by anjesh** [comment]
Created new issue to enable searching for both annotation and text in the same left side box.
https://github.com/NRGI/resourcecontracts.org/issues/761
