### ISSUE TITLE
Download the search results in CSV format

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#368]
The search results should be downloadable in open CSV format. The results will contain all the metadata of the resulting contracts. If there are multiple values for the given field, they will be semi-colon separated in the same column e.g. resources will contain "coal, oil" in case of multiple values.

**Comment by KaitlinCCSI** [comment]
Not a priority for this sprint - please move to Sprint #10 if you haven't started

**Comment by anjesh** [comment]
We have put this in place. It contains all the metadata of the contracts and appears in the search result page only. 

![image](https://cloud.githubusercontent.com/assets/120488/10093005/8a23acda-636c-11e5-9150-3bd3288c2a74.png)
