### ISSUE TITLE
Hyperlink for annotation in annotation bar

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#369]
![image](https://cloud.githubusercontent.com/assets/1101585/10041930/252a74ce-61b6-11e5-9447-5690cfcbbfe4.png)

Just like the *annotation header* is hyperlinked the "dot" to the left and the page numer should hyperlink as well to the same location.

**Comment by jedm** [comment]
This is superseded by #373.

**Comment by anjesh** [comment]
covered by #373.
