### ISSUE TITLE
Dealing with multiple languages at annotation level

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#37]
As a French speaking researcher I would like to utilize French language tags and to provide string annotations in French. 

I am not sure how we can unpack challenges around languages @byndcivilization?

**Comment by byndcivilization** [comment]
metadata should be easy as you just include key value pairs with translations. It's the contract and annotation content that will be the difficult part.

**Comment by anjesh** [comment]
This is also part of https://github.com/NRGI/resourcecontracts.org/issues/47
