### ISSUE TITLE
French language mechanical turk?

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#370]
there are some contracts in French where the MT transcribed pages have symbols instead of the letters: these letters are the ones with French accents (e.g. http://resourcecontracts.elasticbeanstalk.com/mturk/1126/823). 

Should we reject those types of pages: is it the transcriber who just used OCR and did not bother changing the accents or is the problem when he/she uploads his/her work and our system does not recognize those accents?

**Comment by anderspeders** [comment]
There are two potential issues here: 
1) if the data coming back fro mech turk is good then its just an encoding issue
2) but there is also the possiblity that this is happening at amazon which will make this hard to change

@anjesh can you check up on this during sprint 10 

@SamCCSI I suggest we address this post OLC-launch

**Comment by anjesh** [comment]
We tested with the unicode chars in the MTurk sandbox and it's working now. We have fixed the encoding to utf-8 in the transcription form. The french chars should be good now.

**Comment by SamCCSI** [comment]
Great news.

I just checked some of the existing MTs of French language contracts and
the symbols are still there. Will your fix apply to past MT'ed contracts as
well?Eg. http://resourcecontracts.elasticbeanstalk.com/mturk/1126



Also, is there a French MT service we could use, so that transcribers know
that we need to keep in the accents. See this example, where the
transcriber has done a great job but has removed all accents, so that e.g.
"é" now becomes "e".
http://resourcecontracts.elasticbeanstalk.com/mturk/36

cc @kaitlinccsi

On Tue, Oct 13, 2015 at 6:50 AM, Anjesh <notifications@github.com> wrote:

> We tested with the unicode chars in the MTurk sandbox and it's working
> now. We have fixed the encoding to utf-8 in the transcription form. The
> french chars should be good now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/370#issuecomment-147680723>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by anjesh** [comment]
The past MTs will not be fixed as those would have been lost even if they had typed correctly. This should only correct the new ones only.

I don't think there could be something like French MT service. It's upto the transcribers to ensure that they type the correct accented chars.

**Comment by KaitlinCCSI** [comment]
Okay, thanks. Can we include that in instructions to transcribers that
accented characters should be fixed?

On Wed, Oct 14, 2015 at 10:04 PM, Anjesh <notifications@github.com> wrote:

> The past MTs will not be fixed as those would have been lost even if they
> had typed correctly. This should only correct the new ones only.
>
> I don't think there could be something like French MT service. It's upto
> the transcribers to ensure that they type the correct accented chars.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/370#issuecomment-148269335>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01Ptf3JOQ&m=0584a3a9aba7&t=20151014&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01Ptf3JOQ&m=0584a3a9aba7&t=20151014&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01Ptf3JOQ&m=0584a3a9aba7&t=20151014&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by SamCCSI** [comment]
For this page, the reviewer seems to have entered in accents but they appear as wingdings - is there a way of checking whether accents are supported on our system, and a way to view the accents? This might be the first MT transcriber who has actually transcribed a French language contract accurately, so very important to resolve this issue. 
http://resourcecontracts.elasticbeanstalk.com/mturk/1156/4856

Thanks,
Sam

**Comment by KaitlinCCSI** [comment]
Re-opening to address Sam's comment.

**Comment by SamCCSI** [comment]
Additional pages where the reviewer seems to have entered in accents but they appear as wingdings: 

http://resourcecontracts.elasticbeanstalk.com/mturk/1234/2587
http://resourcecontracts.elasticbeanstalk.com/mturk/1208/1217

**Comment by SamCCSI** [comment]
Potentially this one two (in Greek): http://resourcecontracts.elasticbeanstalk.com/mturk/1237/2388

**Comment by SamCCSI** [comment]
Two more Greek contracts where the reviewer seems to have entered in accents but they appear as wingdings:
http://resourcecontracts.elasticbeanstalk.com/mturk/1235/
http://resourcecontracts.elasticbeanstalk.com/mturk/1236

**Comment by anjesh** [comment]
Please open a new issue if you are still similar issues.
