### ISSUE TITLE
UI tweaks to annotation left bar

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#373]
![image](https://cloud.githubusercontent.com/assets/1101585/10055566/fbf747ae-6204-11e5-8adf-6210472c9083.png)

Please remove the following: 
- The pen seems to suggest that the user can edit - thus please change to something else
- The count / number (of annotations) should be removed

Please clarify if the dot has a clear functionality - else this should be removed as well.

**Comment by jedm** [comment]
Clarifying the above:

- Because pencil icon traditionally means “edit,” icon should be changed here and also next to Metadata and icon should not be the same for Annotations and Metadata.
- Count of Annotations should not be removed. Needs better formatting and should be placed below title and "Topic subnav."

**Comment by anderspeders** [comment]
Thanks much @jedm

**Comment by jedm** [comment]
For style of each Annotation listed, format should be:

- Annotation Topic (Cluster name) in light color
- Annotation Title (referred to as Category in some places) in bold
- Citation* and Page number in normal text separated by commas 
- Excerpt of Annotation text (maximum 2 lines) in italics, followed by &nbsp; then ellipsis then an icon to indicate more (when user hovers on ellipsis and icon it should say "Read More") 

Mockup previously sent re-attached here.


![annotation_styling](https://cloud.githubusercontent.com/assets/2153664/10057007/f171bdc6-61f2-11e5-9425-6807aab01244.jpg)

**Comment by byndcivilization** [comment]
Okay final proposal:
remove pen
remove dot
split language to two lines
English is highlighted in red
French is highlighted in blue

**Comment by jedm** [comment]
No idea what you mean by the last 3.

**Comment by byndcivilization** [comment]
Titles are currently provided as <ENGLISH>//<FRENCH> which looks crappy and is confusing.
new way to display  = split on "//" and use color coding to differentiate both from each other and from rest of text.

**Comment by jedm** [comment]
Got it. Thanks. Yes per PDF sent this a.m., the “English // French” approach was built by DevSeed to allow language switching and was never meant to be visible to users. Not sure why it remains on new site.

**Comment by jedm** [comment]
However, I would not suggest color use as it will really pop visually and other cues are more important (color use in toggle between By Topic/By Page, and underlines instead of dots). Suggest that both be normal color and that French be in italics as is common in print and other media.

**Comment by byndcivilization** [comment]
Quick fix. until data model YI gets language UI figured out sam and OLC wanted both.

**Comment by byndcivilization** [comment]
I don't think the popping will be an issue as we're not repeating titles across members of a category any more but I differ to rest of group

**Comment by jedm** [comment]
Happy to defer too, but trying to preserve as much simplicity in the visuals so that the things that show functionality DO pop more.

**Comment by byndcivilization** [comment]
I guess its depends on sam. He requested both in a way that said to me that CCSI wanted dual prominence.

**Comment by KaitlinCCSI** [comment]
CCSI's request was simply that we include both English and French annotation titles for now, because some of the annotations on RC and OLC are in English and some of them are in French, so it felt confusing to have a title in one language and the annotation in another. (See, e.g., all of Guinea contracts on the new RC site.) We're fine with both being in the same color and French being in italics as @jedm suggests. cc @samccsi

**Comment by jedm** [comment]
[Example image above](https://github.com/NRGI/resourcecontracts.org/issues/373#issuecomment-142711796) now includes example of italicized Annotation title on second line.

**Comment by KaitlinCCSI** [comment]
That's fine. Just to clarify, every annotation title has a corresponding French title, so each annotation should look like the second of the three in the mockup.

**Comment by jedm** [comment]
As soon as possible these alt. language titles should be deprecated and a localization feature built.

**Comment by byndcivilization** [comment]
Thats the plan

**Comment by jedm** [comment]
Broken link to "All Annotations" at bottom of left column due to missing slash:
http://alpha.resourcecontracts.org/contract/833

**Comment by jedm** [comment]
• Topic names (clusters) are much too prominent in left column. Should be smaller font, lighter color and initial caps instead of all-caps.
• Page numbers are too small, too light and confusing with "#". Should be clearer that it's a page number.

**Comment by jedm** [comment]
All Annotations link at bottom now has the missing slash added but it is still broken. Link ends with:
[...]#annotations

should end with:

[...]#annotation

Or, even better, anames and anchor links in Summary page should be changed to plural, since this is more accurate.

**Comment by byndcivilization** [comment]
will deal with that in a pull shortly

**Comment by jedm** [comment]
Not sure where the hairline between Topic name and each Annotation is coming from, but I would either remove it or move it to BETWEEN the Annotations. Having a separator WITHIN each Annotation makes them harder to read and, per prior comment, puts more emphasis on the topic name than on the Annotation itself.

**Comment by byndcivilization** [comment]
handled a bunch of this in pull request

**Comment by jedm** [comment]
FYI "All Annotations" link still not working for reason noted above. (Maybe still pending like the Countries problem in lower right, so feel free to re-close this Issue.)

**Comment by byndcivilization** [comment]
working for me on live site. @anderspeders ?

**Comment by jedm** [comment]
To check that it's not a cache issue on my end, I just tried a contract I'd never opened in a browser I haven't used. Still an issue (both "All Annotations" link and "From [Country]" link: http://alpha.resourcecontracts.org/contract/734/view

**Comment by anderspeders** [comment]
All annotations work for me, 

Link to [Country] gives me 404.

So for: http://alpha.resourcecontracts.org/contract/734/view I get a 404 on this link:
http://alpha.resourcecontracts.org/countries/Angola

**Comment by jedm** [comment]
@anderspeders Is "All Annotations" taking you to the top of the summary page or to the annotations section at the bottom? It's supposed to do the latter, but for me the link is going to the top of the page only. This is because the code says "#annotations" at the end of the link instead of "#annotation" as noted [above](https://github.com/NRGI/resourcecontracts.org/issues/373#issuecomment-144146199). Do you mind checking which it is doing for you?

**Comment by anderspeders** [comment]
@jedm, you are correct. 

We will implement if time permits.

**Comment by byndcivilization** [comment]
fixed in pull request

**Comment by jedm** [comment]
Sounds good. Country link in lower right now working for me, FYI. "all annotations" still plural and not dropping to anchor.
