### ISSUE TITLE
Inconsistency between front end display and admin - Government Entity/Identifier

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#374]
Backend display the following text: Forestry Development Authority
Front end display the following text: Forestry Development Authority()

Where is this upload error coming from?

This might be a single issue - but the fact that I cannot correct this manually from the backend is concerning to me?

![image](https://cloud.githubusercontent.com/assets/1101585/10062811/b4a88c84-6234-11e5-98b5-86f2afa1a345.png)
 
![image](https://cloud.githubusercontent.com/assets/1101585/10062840/05f0c20a-6235-11e5-8a05-3b96d2da11b5.png)

**Comment by anjesh** [comment]
That's not a bug, we have concatenated the government identifier with the government entity. Gov-id appears inside the bracket if it's present to save space. That bracket shouldn't have appeared when the gov-id is not present. Will fix that. Thanks.

**Comment by anjesh** [comment]
Fixed.
