### ISSUE TITLE
Slow upload speed on the backend

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#376]
The upload pace when administrators add contracts is slow to load. We should consider what can be done to increase the pace.

**Comment by anjesh** [comment]
This is the current process.
The pdf gets uploaded to S3, then goes through the splitting process (which sometimes take some good time (minutes) for large pdfs containing hundreds of pages), and then goes to Abbyy if the document is scanned. To give the smooth experience, we have setup queues for these process. So the user doesn't have to wait for the completion of the contract and start adding metadata. The user gets email after the process is complete. 

Then we upload the split pdf pages to S3 again. The larger the number of pages, the more time it takes for these API calls. And with Abbyy, there's no way to optimize the speed.

Thoughts? @byndcivilization

**Comment by byndcivilization** [comment]
The real bottleneck is probably abbyy right? Are you shipping pages in bulk? I wonder if you shipped pages individually if it would help. Not sure what their stack is but possible its multiple servers behind a load balancer which would mean you could parallelize the process... Other than that not sure what can be done.

**Comment by anderspeders** [comment]
Removing from sprint 10. Let's seek some further specifications on how slow it is.

**Comment by anjesh** [comment]
Please open if you are still having issues with upload.
