### ISSUE TITLE
Delete or hide "Corporate Group" dropdown option from OLC (and RC?) advanced search page

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#378]
This is irrelevant for OLC; please delete or hide from OLC site. Perrine has also suggested deleting it from ResourceContracts because the information is not filled in for majority of contracts, so feels like a not very useful search field at this time.  

![screen shot 2015-09-24 at 4 15 22 pm](https://cloud.githubusercontent.com/assets/14825437/10087140/d8adfc10-62d7-11e5-81d4-f567a2a2adbd.png)

**Comment by KaitlinCCSI** [comment]
@anderspeders I don't know how to add this to Sprint Number 9?

**Comment by anjesh** [comment]
@anderspeders shall we delete this for both RC and OLC, or just OLC?

**Comment by anjesh** [comment]
@KaitlinCCSI you may add to sprint 9 from the milestone on the right, Click on that wheel like icon besides milestone and select sprint.

![image](https://cloud.githubusercontent.com/assets/120488/10092233/e0057060-6363-11e5-96ba-ee190ab518c3.png)

**Comment by KaitlinCCSI** [comment]
Thanks, @anjesh -- I don't think I have the ability to set milestones or add labels. I don't have those options on the right side. Do I need to be given some kind of permission to have this capability?
![screen shot 2015-09-25 at 7 08 21 am](https://cloud.githubusercontent.com/assets/14825437/10100001/5f03da88-6354-11e5-96fe-9cc870edc1cc.png)

**Comment by byndcivilization** [comment]
@anderspeders? I think this is actually pretty key to RC as its a way for users to access say "Shell's" holdings while all the different contracts are assigned to specific subsidiaries. Not sure about OLC as I'm not sure if theres the same beneficial ownership/corporate hierarchy/subsidiary issue.

**Comment by KaitlinCCSI** [comment]
We think it's useful for RC, too; the concern was that a lot of the info
isn't yet available, so it might be better to hide for now and then
implement later once more info has been included for contracts. For OLC
it's simply moot right now -- we haven't put any of that info in -- so it
just looks bad at this point.

On Fri, Sep 25, 2015 at 11:06 AM, Chris Perry <notifications@github.com>
wrote:

> @anderspeders <https://github.com/anderspeders>? I think this is actually
> pretty key to RC as its a way for users to access say "Shell's" holdings
> while all the different contracts are assigned to specific subsidiaries.
> Not sure about OLC as I'm not sure if theres the same beneficial
> ownership/corporate hierarchy/subsidiary issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/378#issuecomment-143262508>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01Pls690z&m=ec291e3b939e&t=20150925&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01Pls690z&m=ec291e3b939e&t=20150925&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01Pls690z&m=ec291e3b939e&t=20150925&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by anderspeders** [comment]
We can remove this from OLC, 

For RC we should keep it on the site: We currently have a graduate student contributing metadata from the backend on corporate group and company information so there is an actual use case that this is satisfying.

**Comment by KaitlinCCSI** [comment]
Sounds good.

On Fri, Sep 25, 2015 at 12:56 PM, Anders <notifications@github.com> wrote:

> We can remove this from OLC,
>
> For RC we should keep it on the site: We currently have a graduate student
> contributing metadata from the backend on corporate group and company
> information so there is an actual use case that this is satisfying.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/378#issuecomment-143305341>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PltTWQk&m=2a03976b2fde&t=20150925&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PltTWQk&m=2a03976b2fde&t=20150925&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01PltTWQk&m=2a03976b2fde&t=20150925&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by anjesh** [comment]
Removed for OLC only.
