### ISSUE TITLE
Possible bug? Many options in dropdowns flash when searching on advanced search page 

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#379]
When I am using the dropdowns on the advanced search page, after I select an option and hit the "Search" button, all of the dropdown boxes briefly flash the first 4 options before the search results are returned. I don't know if this is a bug that can be easily fixed, but flagging in case it can be addressed quickly in sprint 9, as it looks strange. Screenshot attached. Not a priority for this sprint if it can't be fixed quickly. cc @anderspeders 
![screen shot 2015-09-21 at 9 37 14 pm](https://cloud.githubusercontent.com/assets/14825437/10087490/c850ba36-62d9-11e5-9c02-51585ae69900.png)

**Comment by anjesh** [comment]
We fixed this. Now the search area is hidden until the page loads.
