### ISSUE TITLE
Hosting of supporting documents to main contract - for example translated versions of the contract

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#38]
This user story was submitted by the EITI secretariat of the Philippines: 
"We would like to provide access to the contract in local languages along with the original language text. For example all mining contracts in the Philippines are published in the original English language, but will also need to be published in translated versions. The EITI office will take care of the translation it self but the platform need to provide the opportunity for submitting the translated contract as an associated document". 

Feature solution:
Enable supporting documents to be attached / added to the main contract.

**Comment by SamCCSI** [comment]
@anderspeders This sounds great.
Is it possible to have some form of notification to show the user when they are reading translated content, and show them a link to the original document?

**Comment by anderspeders** [comment]
Thanks Sam,

Yes, I think we definitely want to think about how we can make it clear to the user how various documents relate to each other.

On the site of OLC – which other supporting document types can you point out. I recall environmental assessments and possibly one other document type?

Best,
Anders

Anders Pedersen  |  Open Data Program Officer
Natural Resource Governance Institute
(formerly the Revenue Watch Institute - Natural Resource Charter)
1110 Vermont Ave NW #500, Washington, D.C., DC 20005
apedersen@resourcegovernance.org<mailto:apedersen@resourcegovernance.org> | www.resourcegovernance.org<http://www.resourcegovernance.org>
Twitter: @anpe | Skype: anpehej | M: 917.208.7807

**Comment by anjesh** [comment]
selection of "supporting documents" is now enabled in the system.
