### ISSUE TITLE
Making About, FAQs, etc pages easier to find

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#382]
When I look at the site on my laptop, it's hard to find the About, FAQ, contact, and other pages that are listed in the bottom left of the footer. Is it possible to make them easier to find? Either by moving them to the righthand corner of the site in the header, or minimizing the black space above those hyperlinks in the footer? 
![screen shot 2015-09-25 at 10 47 37 am](https://cloud.githubusercontent.com/assets/14825437/10105252/429b16b2-6373-11e5-96a0-6937e205c7e0.png) cc @jedm b/c it's about UI

**Comment by anjesh** [comment]
@anjhero can you think and see how to addreess this visibility of the static pages?

**Comment by anderspeders** [comment]
@anjesh Do we have a status on this one?

**Comment by anjesh** [comment]
We missed this in today's deployment.

**Comment by anjesh** [comment]
This is how it appears now in 404.

![image](https://cloud.githubusercontent.com/assets/120488/10332174/4505d338-6cfb-11e5-8293-ad55061bd132.png)

**Comment by KaitlinCCSI** [comment]
Fine for now - thanks - but I am going to open another ticket for Sprint 11, because I still think it might be useful to make these pages more easy to access, including from other pages (not just 404 page).
