### ISSUE TITLE
Fix annotations that are incorrectly mapped to the following fields

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#384]
1. Fundamental provisions
2. Community and social obligations
3. Developers financial obligations
4. Environmental provisions
5. Operational provisions
6. Miscellaneous provisions

Either we need to: 
- hide them
- remap

Needs to address this in next call with YI

**Comment by KaitlinCCSI** [comment]
See also #385. Need to also hide or remap:

I. General information
II. Summary of terms
III. Document notes

**Comment by anjesh** [comment]
These will be remapped to "other" as per this https://github.com/NRGI/resourcecontracts.org/issues/385

**Comment by anjesh** [comment]
Fixed.
