### ISSUE TITLE
Assigning  all annotation categories to current code list (to other)

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#385]
Once all contracts have been loaded we need to assure that all annotation categories are streamlined to the current annotation codelist. 

This needs to include hiding or remapping of the following errors from the first round of uploads:
New             Current 
Other <-- 1. Fundamental provisions
Other <-- 	2. Community and social obligations
Other <-- 	3. Developers financial obligations
Other <-- 	4. Environmental provisions
Other <-- 	5. Operational provisions
Other <-- 	6. Miscellaneous provisions

**Comment by KaitlinCCSI** [comment]
Please note that we also need to hide or remap these errors as well:

New Current 
Other <-- I. General information
Other <-- II. Summary of terms
Other <-- III. Document notes

**Comment by KaitlinCCSI** [comment]
Also, @anderspeders can you please confirm that Dropdowns will be fixed per mapping that we have provided for Resources, Contract Type, and Annotation Categories? I don't see a ticket for this.

**Comment by anjesh** [comment]
Fixed resources, contract types and annotation types codelist.
