### ISSUE TITLE
Contract doc names need editing

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#387]
Hello, the following two contracts have errors in their names, which require manual editing:

http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/1039/view
"S&amp;P Energy Solutions_Ethiopia" - to be changed to "S&P Energy Solutions, Ethiopia"

http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/1036/view
"Nile Trading &amp; Development_South Sudan" - to be changed to "Nile Trading & Development, South Sudan"

(The "_" is our error, but hoping to change it while also changing the "&amp;" error)

Thanks!

**Comment by anderspeders** [comment]
@anjesh Will this work: http://stackoverflow.com/questions/657643/how-to-remove-html-special-chars

@SamCCSI: How important is this compared to (long) the list of other urgent issues? Asking because this could be changed by your self from the backend using alternative lettering:  "S and P Energy Solutions, Ethiopia"?

**Comment by SamCCSI** [comment]
Hi Anders,

It would be nice to have it sorted, as it is a bit messy, and I assume
(admittedly on no actual knowledge re how the site works) it would not take
up much time?

We need to keep the "&" in the title, as that is the corporate name. If
there is a way for me to do this manually, I am more than happy to do so,
as I know everyone is under a lot of pressure right now.

Sam

On Fri, Sep 25, 2015 at 5:46 PM, Anders <notifications@github.com> wrote:

> @anjesh <https://github.com/anjesh> Will this work:
> http://stackoverflow.com/questions/657643/how-to-remove-html-special-chars
>
> @SamCCSI <https://github.com/SamCCSI>: How important is this compared to
> (long) the list of other urgent issues? Asking because this could be
> changed by your self from the backend using alternative lettering: "S and P
> Energy Solutions, Ethiopia"?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/387#issuecomment-143361424>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by anderspeders** [comment]
![image](https://cloud.githubusercontent.com/assets/1101585/10113145/8b934bbe-63af-11e5-93ee-e3f28df96da2.png)

@anjesh It appears that we will need to run a script to clean this across the database, as there might be numerous examples.

**Comment by SamCCSI** [comment]
This problem also arises with french language contracts using accented lettering.

Eg: "è" becomes "&egrave;" in this contract:
http://alpha.openlandcontracts.org/contract/1126/view

cc @kaitlinccsi

**Comment by anjesh** [comment]
That was due to the reactjs rendering. Should be fixed in today's deployment.

**Comment by anjesh** [comment]
These are fixed now. Please re-open if you find any other such instances.

**Comment by SamCCSI** [comment]
Thank you!

On Mon, Sep 28, 2015 at 6:55 AM, Anjesh <notifications@github.com> wrote:

> These are fixed now. Please re-open if you find any other such instances.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/387#issuecomment-143710610>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>
