### ISSUE TITLE
Fixing core UX/UI of Annotations (Behavior)

### ISSUE THREAD

**Issue by jedm** [NRGI/resourcecontracts.org#389]
Based on agreement today with @anderspeders and @KaitlinCCSI, these are the key behavior and formatting issues to be resolved for use of Annotations in Contract view page—separated by Behavior and [Formatting](https://github.com/NRGI/resourcecontracts.org/issues/390) for sake of clarity and numbered for reference and review.

I. Behavior (clicking, scrolling, hovers and popups, etc.)

1. Annotations and scrolling linked
a) Clicking on Annotation in left column triggers PDF (and text view) to scroll to correct page of Contract
b) Clicking on Annotation popup in PDF triggers scroll to corresponding Annotation in left column. Column scrolls to drop corresponding Annotation at top 

2. Expand and hover displays of full Annotation text linked
a) In PDF view, when user hovers on Annotation box, popup appears showing only Annotation Title(s), Citation, Page and an icon (eg, arrow)
b) When user clicks on this popup in PDF area, left column scrolls to corresponding Annotation (see 1b) AND the Annotation in left column EXPANDS to show full Annotation text (as if user had clicked on the ellipsis)
c) Full text of Annotation should show ONLY in expanded view in left column and NOT in popup over PDF. This will remove double-display and avoid hiding the source material under the popup
d) See image sample below to show hover and expanded view in left column
e) See #391 re. Citations

3. Clustered Annotations - left column
a) Per #348, Annotations are being grouped by topical “clusters”
b) User can toggle left column to view Annotations “By Topic"/cluster name or “By Page"/sequence in contract. (Viewing by Annotation Title (“category”) was never requested.)
c) Toggle should be performed using a button slider at the top of the left column, not a drop-down. (see example of button slider in image below and in [NRGI’s governance index data tool](http://index.resourcegovernance.org/rgi/data-tool#) )
d) When slider is set to “By Topic,” Annotations in left column display grouped by Topic (cluster name) in the following order of Topics: General, Environment, Fiscal, Operations, Social, Other
e) Within the groups described in d), Annotations display in order by sequence, i.e., by the page number they occur in the Contract
f) When slider is set to “By Page,” Annotations display in order by sequence, i.e., by the page number they occur in the Contract
g) Default on page load is for Annotations in left column to display By Page (f)

4. Clustered Annotations - sub-navigation links
a) Per 3d above, When slider is set to “By Topic” topic sub-navigation links appear (see mockup below)
b) Topic sub-navigation displays ONLY when slider is set to “By Topic”. Subnavigation is COMPLETELY HIDDEN when slider is set to “By Page”
c) When user hovers on Topic (cluster) name, description is shown (See #372)
d) Clicking on Topic name scrolls left column to first Annotation in selected Topic. Column scrolls to drop corresponding Annotation at top.
e) In the Topic sub-navigation, selected Topic turns bold and blue (same color as button slider)
f) Delete the words “Sort By” from top of left column

Related Note

5 Per I.1a and I.2b, clicking on Annotation in left column should trigger corresponding Annotation box in PDF view to open the popup (as if user had hovered). In other words, the relationship between selecting an Annotation should be “two-way” between the left column and the PDF area.

![columns](https://cloud.githubusercontent.com/assets/2153664/10113859/df6ee9b2-639d-11e5-9016-7e112d0c96ca.jpg)

![toggle](https://cloud.githubusercontent.com/assets/2153664/10113801/4b15bb92-639d-11e5-9301-f3b61f451653.jpg)

**Comment by anjesh** [comment]
The annotations/contract  UI has been updated to reflect number of features. The design is not final yet (icons, colors are yet to be changed but it follows the structure as you have presented in the issue). 
http://alpha.openlandcontracts.org/contract/1039/view

Some of the things that need to be done in the UI. 

1. The major thing that remains popping up annotation in the pdf-view when clicked on the annotation on the left. That might take more time to hack into the existing annotatorjs that we are using. They don't seem to have easy way to get that functionality. We are exploring on that, but aside from that most other interactions are present. 

2. Including the section information in the annotation list. That is straight forward. We saw that the section info is included in separate column in OLC, which we didn't include in the last upload. We will concatenate the section to the annotation text after --. RC migration does have "-- section" info as a part of the annotation. 

Besides there might be few other minor issues (in terms of functionality) - which should not be much of a problem to fix.

**Comment by KaitlinCCSI** [comment]
Thanks, Anjesh! I have some comments on the UI, which I'll add shortly. But one bigger issue now is that it seems that the cluster categories that are meant to be hyperlinked at the top of the annotations bar are not all properly linked. See for example: http://alpha.openlandcontracts.org/contract/1039/view The only two that are hyperlinked/do anything are "General" and "Other"; clicking on "Environment", "Fiscal", "Operations", and "Social" doesn't do anything. It might be because these words do not exactly match how they were categorized elsewhere? For example, if I look at the same contract but sort annotations by page, I see annotations that are categorized as "Financial", "Operational", and "Environmental".

**Comment by jedm** [comment]
@anjesh It's great to see this progress. Are the formatting and style changes (especially in left column) pending during this sprint? If so, we'll wait before re-posting any formatting requests from #390 .Kaitlin is adding some key notes on the right column shortly.

(Per your Item 1. above, if it turns out that the functions that link the Annotations in the left and center areas are not possible, we should hold a discussion about adding controllers or removing certain options to avoid confusing users.)

**Comment by anjesh** [comment]
Yes there has been a little consistent over the use of cluster names when we followed the shorten names as mentioned by Jedm. Those will be fixed.

**Comment by anjesh** [comment]
Creating followup issues for next sprint. Closing this.
https://github.com/NRGI/resourcecontracts.org/issues/471
https://github.com/NRGI/resourcecontracts.org/issues/473

**Comment by jedm** [comment]
@anjesh - it is really fantastic to see nearly all the functions described above working as requested. With the completion of the [direct-links for Annotations](http://www.resourcecontracts.org/contract/ocds-591adf-YE3941604679RC/view#/pdf/page/31/annotation/13288) it makes for excellent usability and added opportunities for users. Great work!
