### ISSUE TITLE
The metadata form on the old RC platform

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#39]
![image](https://cloud.githubusercontent.com/assets/1101585/8106452/7ed1202a-100f-11e5-9329-c5360058eae3.png)

The previous metadata template/form has worked with a limited set of metadata fields. These will be expanded.

**Comment by anjesh** [comment]
These info are available https://github.com/NRGI/resourcecontracts.org/issues/120. This could be closed.
