### ISSUE TITLE
Fixing core UX/UI of Annotations (Formatting)

### ISSUE THREAD

**Issue by jedm** [NRGI/resourcecontracts.org#390]
Based on agreement today with @anderspeders and @KaitlinCCSI, these are the key behavior and formatting issues to be resolved for use of Annotations in Contract view page—separated by [Behavior](https://github.com/NRGI/resourcecontracts.org/issues/389) and Formatting for sake of clarity and numbered for reference and review.

II. Formatting

1. Left Column
a) For each Annotation in left column, show the following on separate lines: Topic, Title, Alt. Language Title, Citation, Page #, Two Lines of Excerpt (from Annotation text)
b) After text excerpt (inline) include &amp;nbsp; and ellipsis
c) Annotation Title (primary language) and ellipsis should both be hyperlinked and styled with a visible “a” style that includes underline
d) See #373 for [image with style and formatting guidelines](https://github.com/NRGI/resourcecontracts.org/issues/373#issuecomment-142711796)
e) See [recent comment in 373](https://github.com/NRGI/resourcecontracts.org/issues/373#issuecomment-143339021) for note re. change to ENG//FRENCH Annotation Title display 
f) See #391 re Citations

2. Annotations in PDF view (center area)
a) Black boxes used to show Annotation “location” in PDF should be yellow by default (not yellow on hover). Without this change the boxes will look like a view error or clutter and confuse the users.
b) Per I.2a in #389, hovering on Annotation box in PDF displays popup showing only Annotation Title(s), Citation, Page # and an icon
c) Per image sample below, Annotation Title should be bold (Alt. Language Title, if present, should be italic and not bold); Citation and Page # should be normal format
d) Per I.2c #389, full text of Annotation should show ONLY in expanded view in left column and should no longer show in popup over PDF
e) See image sample below to show hover and expanded view in left column

Related Note

3 Per #346, it would be best to have a way to go “back to top” at the bottom of the left column. This is the same place as the All Annotations link, so it is important that there be consistent design, icon usage, colors and formatting in all the ways that boxes are opened or closed, text blocks are expanded/collapsed, etc. etc.

![columns](https://cloud.githubusercontent.com/assets/2153664/10113891/502bde62-639e-11e5-871c-ed3f4dcbbf50.jpg)

**Comment by byndcivilization** [comment]
handled a bunch of this in pull request

**Comment by jedm** [comment]
- Great that YI changed the default outline to yellow for the boxes in the PDFs! (Meant to say that yesterday) 
- The ENG//FRENCH titles in the PDF hovers are confusing - would delete English or sub a < br > for the // globally
- "#6" is a confusing way to indicate Page number in left column

**Comment by byndcivilization** [comment]
addede french as italics under in recent pull

**Comment by jedm** [comment]
Should this "GENERAL" heading and hairline still be here, even if all following Annotations are not in General category?

![screen shot 2015-09-30 at 8 55 23 am](https://cloud.githubusercontent.com/assets/2153664/10198371/9171abee-6750-11e5-80c2-0ec045207c79.png)

**Comment by byndcivilization** [comment]
@anjesh can we re render divs on sort?
