### ISSUE TITLE
Extract Citations / "Article References" from Annotations, add to model

### ISSUE THREAD

**Issue by jedm** [NRGI/resourcecontracts.org#391]
Several GitHub Issues have requested [Citations or “article references”](https://github.com/NRGI/resourcecontracts.org/issues/373#issuecomment-142711796) from within each contract (see #72, #373, e.g.). Citations are included in every Annotation text at the end of the text block after two hyphens. This should make them easy to extract in a one time process and add to the data model.

**Comment by byndcivilization** [comment]
I'm pushing this till after OLC launch

**Comment by anjesh** [comment]
The section info is displayed in the contract view

![image](https://cloud.githubusercontent.com/assets/120488/10507487/7cc8e53a-7340-11e5-9d6e-c5485a68e638.png)

**Comment by jedm** [comment]
That's fantastic, @anjesh! Great work. To save space and create consistency, I would strongly recommend putting section info and page # on same line, separating with a comma, making them both the gray color, and deleting the colon from page reference.

**Comment by SamCCSI** [comment]
For multiple art. refs: judging from Chris's screenshot, they currently
appear with "and" or "et" between each reference. I suggest they be
separated by commas instead, and "Art." be changes to "Arts.".

so "Art 2 and Art 3 and Art 4" becomes "Arts. 2, 3, 4"

On Thu, Oct 15, 2015 at 11:14 AM, jedm <notifications@github.com> wrote:

> That's fantastic, @anjesh <https://github.com/anjesh>! Great work. To
> save space and create consistency, I would strongly recommend putting
> section info and page # on same line, separating with a comma, making them
> both the gray color, and deleting the colon from page reference.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/391#issuecomment-148418232>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by jedm** [comment]
@samccsi bear in mind that this section info is extracted verbatim as one string of text from where reviewers put it in the annotation body. Not sure it can be made "smarter" with a quick revision. 

However, I'd suggest that new formats for these can be defined and observed for all future annotations. 

cc @kaitlinccsi @anderspeders

**Comment by SamCCSI** [comment]
Absolutely: if this is how it originally was entered by our annotators,
then I agree it's not an issue that needs a tech fix.

On Thu, Oct 15, 2015 at 12:21 PM, jedm <notifications@github.com> wrote:

> @samccsi bear in mind that this section info is extracted verbatim as one
> string of text from where reviewers put it in the annotation body. Not sure
> it can be made "smarter" with a quick revision.
>
> However, I'd suggest that new formats for these can be defined and
> observed for all future annotations.
>
> cc @kaitlinccsi @anderspeders
>
> > On Oct 15, 2015, at 8:35 AM, SamCCSI <notifications@github.com> wrote:
> >
> > For multiple art. refs: judging from Chris's screenshot, they currently
> > appear with "and" or "et" between each reference. I suggest they be
> > separated by commas instead, and "Art." be changes to "Arts.".
> >
> > so "Art 2 and Art 3 and Art 4" becomes "Arts. 2, 3, 4"
> >
> > On Thu, Oct 15, 2015 at 11:14 AM, jedm <notifications@github.com> wrote:
> >
> > > That's fantastic, @anjesh <https://github.com/anjesh>! Great work. To
> > > save space and create consistency, I would strongly recommend putting
> > > section info and page # on same line, separating with a comma, making
> them
> > > both the gray color, and deleting the colon from page reference.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/NRGI/resourcecontracts.org/issues/391#issuecomment-148418232
> >
> > > .
> > >
> >
> >
> >
> > --
> >
> >
> >
> > *SAM SZOKE-BURKE*
> > *Legal Researcher**Columbia Center on Sustainable Investment*
> > Columbia Law School - The Earth Institute, Columbia University
> > Level 1, Warren Hall, 410 W116th St. New York, NY 10027
> > | (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
> > | s.burke@columbia.edu
> > | www.ccsi.columbia.edu | @CCSI_Columbia <
> https://twitter.com/CCSI_Columbia>
> > | @samszokeburke <http://twitter.com/samszokeburke>
>
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/391#issuecomment-148443084>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by KaitlinCCSI** [comment]
Agree. Was this screenshot from OLC or RC? We do provide guidance in our Guidance Documents on using the format Sam suggested, but very possible that some slipped through without being standardized.

**Comment by anjesh** [comment]
> That's fantastic, @anjesh! Great work. To save space and create consistency, I would strongly recommend putting section info and page # on same line, separating with a comma, making them both the gray color, and deleting the colon from page reference.

@jedm We did put section info and page # on the same line, but there were couple of instances where the section info is long and where there are quite a number of pages, which broke the line into 2 lines. So we put those in two separate lines, i agree that they need to be consistent and in proximity. Do you still think we put these in a  single line?

**Comment by jedm** [comment]
My opinion is that a line-break is fine, as long as the left margin of the second line is the same as the first. If you can then have no-space comma and a space followed by the Page number, that is what I would do. @byndcivilization what do you think?

**Comment by anjesh** [comment]
This will be taken care of in this issue https://github.com/NRGI/resourcecontracts.org/issues/694 when we do the implementation of parent annotation, we will have the option to mention the section info as well. We will do the auto-filling of this field and later needs to be manually looked into/fixed.
