### ISSUE TITLE
Any category with only 1 associated contract should say "1 contract" and not "1 contracts"

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#392]
On "All Countries" page and "All Resources" page, anything with only 1 contract associated should say "1 contract", not "1 contracts". Should be fixed in sprint 9.
![screen shot 2015-09-25 at 8 29 31 pm](https://cloud.githubusercontent.com/assets/14825437/10115148/b3e4bd18-63c4-11e5-8099-bd62529a5965.png)
![screen shot 2015-09-25 at 8 32 02 pm](https://cloud.githubusercontent.com/assets/14825437/10115149/b6166e60-63c4-11e5-9583-dc0c59189c5e.png)

**Comment by KaitlinCCSI** [comment]
@anderspeders I still don't have ability to assign milestones or labels, so will cc you on all tickets until I do.

**Comment by anjesh** [comment]
Fixed.
