### ISSUE TITLE
Remove sort by "Ascending"/"Descending" from Country & Resource pages of OLC

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#393]
Remove Sort by "Ascending"/"Descending" from Country & Resource pages for OLC. Sprint 9 if possible; otherwise sprint 10.

@byndcivilization @anderspeders @jedm Any preference for RC?

![screen shot 2015-09-25 at 8 36 36 pm](https://cloud.githubusercontent.com/assets/14825437/10115183/78757e56-63c5-11e5-8927-d3e8d4828d0e.png)
![screen shot 2015-09-25 at 8 36 12 pm](https://cloud.githubusercontent.com/assets/14825437/10115184/787fc636-63c5-11e5-88fb-eb13a9ca6da1.png)

**Comment by anjesh** [comment]
Removed for both for now. Doesn't seem to have much use though.
