### ISSUE TITLE
Contract already uploaded, annotation to be uploaded later - can we link these?

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#394]
ADA commercial Inc was uploaded on August 7. It has been sent to MT and is almost completed.
http://resourcecontracts.elasticbeanstalk.com/contract/107/review

We now have metadata and annotations completed for that contract in excel spreadsheet form, which will be batch-uploaded by YI tomorrow.

Can we keep the MT pages, and make sure the uploaded annotations apply to the pre-existing ADA contract, rather than duplicating it by re-uploading the PDF of ADA commercial inc again?

cc @anderspeders @anjesh @kaitlinccsi

**Comment by anjesh** [comment]
Fixed for ADA.

**Comment by anjesh** [comment]
http://alpha.openlandcontracts.org/contract/107/view

**Comment by SamCCSI** [comment]
Many thanks Anjesh.

This contract has one MT page rejected. Can you please 'revert' so that our
intern can finalize it, so that the text is also available for this
contract?



On Thu, Oct 1, 2015 at 1:30 PM, Anjesh <notifications@github.com> wrote:

> http://alpha.openlandcontracts.org/contract/107/view
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/394#issuecomment-144702091>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by KaitlinCCSI** [comment]
Re-opening to address Sam's question above.

**Comment by anjesh** [comment]
Fixed. rejected page is reverted.

**Comment by SamCCSI** [comment]
Thanks - will let Charles know.

On Mon, Oct 5, 2015 at 6:46 AM, Anjesh <notifications@github.com> wrote:

> Closed #394 <https://github.com/NRGI/resourcecontracts.org/issues/394>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/394#event-426643610>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>
