### ISSUE TITLE
Contracts now ready for 2nd batch upload

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#395]
Anders and Anjesh,

We are ready for you to commence the batch upload.

The full list is here: https://docs.google.com/spreadsheets/d/13HFzsddfT9OkeAmtHLtwzpl2QP-IHaYxP8wB8adUljg/edit?usp=sharing

The 34 new contracts to upload start at Row 40.

There are two contracts for re-upload (please delete earlier entries). These start at row 77.

For ADA: please note this Github ticket entry before commencing the upload of that contract: https://github.com/NRGI/resourcecontracts.org/issues/394

Many thanks, and best of luck!

My number if you have any problems: +1 646 630 4123

cc @anderspeders @anjesh @kaitlinccsi

**Comment by anderspeders** [comment]
closing this ticket as we are now assigning data errors in #402
