### ISSUE TITLE
All contracts on OLC advanced search page are the same on pages 1 and 2

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#396]
The advanced search page for OLC says there are 37 contracts, and gives two pages (options at the bottom are "1", "2", "Next", "Last"). There are 25 contracts listed on the first page. When you click on "2", "Next", or "Last", however, the other pages just repeat the same 25 contracts in the exact same order, even though the URL at the top changes. Should be fixed sprint 9. cc @anderspeders 
![screen shot 2015-09-28 at 6 34 07 am](https://cloud.githubusercontent.com/assets/14825437/10134386/00801b08-65ab-11e5-9ed3-8a8d20c4e9bb.png)
![screen shot 2015-09-28 at 6 33 56 am](https://cloud.githubusercontent.com/assets/14825437/10134387/03e8ce98-65ab-11e5-9f7d-c937968f317c.png)

**Comment by byndcivilization** [comment]
I think this is good, right @anjesh ?

**Comment by KaitlinCCSI** [comment]
Seems to be fine now

**Comment by anjesh** [comment]
Fixed.
