### ISSUE TITLE
Remove "Other Sources" from OLC

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#397]
Remove the section: "Other Sources" and reference to AMLA on OLC

![image](https://cloud.githubusercontent.com/assets/1101585/10137452/a3734cba-65c7-11e5-94d9-ad642bd7fc05.png)

Please confirm @SamCCSI @KaitlinCCSI

**Comment by KaitlinCCSI** [comment]
Yes, please remove.

On Monday, September 28, 2015, Anders <notifications@github.com> wrote:

> Remove the section: "Other Sources" and reference to AMLA on OLC
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/1101585/10137452/a3734cba-65c7-11e5-94d9-ad642bd7fc05.png>
>
> Please confirm @SamCCSI <https://github.com/SamCCSI> @KaitlinCCSI
> <https://github.com/KaitlinCCSI>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/397>.
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PmC3Gmq&m=88e98f844d26&t=20150928&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PmC3Gmq&m=88e98f844d26&t=20150928&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01PmC3Gmq&m=88e98f844d26&t=20150928&c=f>
>


-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by KaitlinCCSI** [comment]
And for ResourceContracts, it should say "Legislation" and not
"Legistation".

On Monday, September 28, 2015, Kaitlin Y. Cordes <
kaitlin.cordes@law.columbia.edu> wrote:

> Yes, please remove.
>
> On Monday, September 28, 2015, Anders <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> Remove the section: "Other Sources" and reference to AMLA on OLC
>>
>> [image: image]
>> <https://cloud.githubusercontent.com/assets/1101585/10137452/a3734cba-65c7-11e5-94d9-ad642bd7fc05.png>
>>
>> Please confirm @SamCCSI <https://github.com/SamCCSI> @KaitlinCCSI
>> <https://github.com/KaitlinCCSI>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/NRGI/resourcecontracts.org/issues/397>.
>> ------------------------------
>>
>> Spam
>> <https://antispam.law.columbia.edu/canit/b.php?i=01PmC3Gmq&m=88e98f844d26&t=20150928&c=s>
>> Not spam
>> <https://antispam.law.columbia.edu/canit/b.php?i=01PmC3Gmq&m=88e98f844d26&t=20150928&c=n>
>> Forget previous vote
>> <https://antispam.law.columbia.edu/canit/b.php?i=01PmC3Gmq&m=88e98f844d26&t=20150928&c=f>
>>
>
>
> --
>
>
> *KAITLIN Y. CORDES*
>
> *Head: Land and Agriculture**Columbia Center on Sustainable Investment*
> Columbia Law School - The Earth Institute, Columbia University
> 435 West 116th St. New York, NY 10027
> | +1 (917) 658 5172
> | kaitlin.cordes@law.columbia.edu
> <javascript:_e(%7B%7D,'cvml','kaitlin.cordes@law.columbia.edu');>
> | www.ccsi.columbia.edu | @CCSI_Columbia
> <https://twitter.com/CCSI_Columbia> | @kaitlincordes
> <https://twitter.com/kaitlincordes>
>
>
>

-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>
