### ISSUE TITLE
UI changes to right column

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#398]
Please make the following changes to the right column on the contract view page:
- Right column (metadata) is supposed to be permanent, not expand/collapse, and icon in upper-right must be removed.
- Change order of this column to Country, Signature Year, Resources, Type of Contract, OCID
- OCID should be spelled out
- Length of the right column should be increased to include ALL FIVE main categories (i.e., “Type of Contract” must not be cut off). That will also make the “See more” link unnecessary, which is good because it is confusing when put next to “See summary"
- Under “Resources,” add space after comma between each Resource name 
- In bottom right, change “In [Country]” to “From [Country]" and “In [Resource]” to “For [Resource]". When there are multiple resources, they should be separated by comma followed by space.
- As Anders noted in #397, final section "Other Sources" should be hidden until further notice, though kept for RC.

![screen shot 2015-09-28 at 6 45 20 am](https://cloud.githubusercontent.com/assets/14825437/10136393/e6255cbe-65b9-11e5-8c38-d0a729112813.png)

cc @anderspeders @jedm

**Comment by anderspeders** [comment]
Thanks Kaitlin, 

To add: 
- Making right bar permanent is also referenced in #345
- Change order (Country, Signature Year, Resources, Type of Contract, OCID). Once implemented - this needs to be implemented for "Contract Summary page" and "Advanced search view" for consistency
- OCID should be spelled out: "Open Contracting Identifier"

**Comment by jedm** [comment]
Link to more-from-country is 404-ing. In example below, it looks like the correct link would be to /countries/gn but link goes to /countries/Guinea. Not sure if this is happening for other countries or not.

http://alpha.resourcecontracts.org/contract/852/view

**Comment by byndcivilization** [comment]
dealt with in pull request

**Comment by jedm** [comment]
Still seeing this. Another example - Liberia contract

http://alpha.resourcecontracts.org/contract/833/view

**Comment by byndcivilization** [comment]
Dealt with in pending  pull request
