### ISSUE TITLE
Advanced search page - moving 1 Search Dropdown to second line

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#399]
Can you move the "Company Name" search bar to the second line? Makes it even on OLC, would look fine on RC, and also when the screen is zoomed in, the circle would then not cover part of the "Company Name" text. (Screenshot of what it looks like at 125%).

Fine to wait until sprint 10.

![screen shot 2015-09-28 at 11 57 29 am](https://cloud.githubusercontent.com/assets/14825437/10142594/4bd07b88-65d9-11e5-86de-678dd504d951.png)

**Comment by anderspeders** [comment]
Thanks Kaitlin, 

When I look at the page in normal view = 100% it seems to be fine: 
![image](https://cloud.githubusercontent.com/assets/1101585/10144410/7cc94320-65eb-11e5-8316-96e369030e20.png)

**Comment by KaitlinCCSI** [comment]
Yes, it's fine for me at 100%, but because everything on the site is in such a small font, I think that users may look at it at more than 100% (I've found I almost always have it at 125%, which is what I was using when I took the screenshot) -- if so, it seems like an easy fix to move one bar down to the next line, which would prevent this overlap and would also make OLC's search bars more even.

**Comment by anjesh** [comment]
Added some space to fix that overlap 
![image](https://cloud.githubusercontent.com/assets/120488/10533590/1dc1df5a-73eb-11e5-8bdb-7c497bd5ff2b.png)
