### ISSUE TITLE
OCR ABBYY API workflow

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#4]
@byndcivilization to share API details

**Comment by anderspeders** [comment]
@anjesh Do you have what you need here for API access?

cc @byndcivilization

**Comment by anjesh** [comment]
I don't have Abbyy API yet.

**Comment by anjesh** [comment]
Abbyy access recieved and integrated https://github.com/anjesh/pdf-processor

**Comment by anderspeders** [comment]
Done.
