### ISSUE TITLE
Cluster mapping issues

### ISSUE THREAD

**Issue by byndcivilization** [NRGI/resourcecontracts.org#400]
It looks like some of the cluster mapping is bleeding into UI. I think this is just spelling issues around OTHER vs other.
![unknown-4](https://cloud.githubusercontent.com/assets/2875950/10143840/7ab6dd20-65e8-11e5-9d9e-bcf13455f88c.png)

**Comment by anjesh** [comment]
Fixed. Re-ran the indexing after the fix.
