### ISSUE TITLE
Dropdowns not working on advanced search page

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#403]
Annotations Category and Contract Type Dropdowns seem to be broken; nothing happens when I click in the box.

**Comment by byndcivilization** [comment]
Browser? Working in Safari. @anjesh are these dynamically populated based on applied filters? Maybe an issue of the applied filter attaching to contract without annotatoins or contract type

**Comment by KaitlinCCSI** [comment]
Google chrome

On Tuesday, September 29, 2015, Chris Perry <notifications@github.com>
wrote:

> Browser? Working in Safari. @anjesh <https://github.com/anjesh> are these
> dynamically populated based on applied filters? Maybe an issue of the
> applied filter attaching to contract without annotatoins or contract type
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/403#issuecomment-144128336>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01Pn5qvtu&m=0995c103b5e5&t=20150929&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01Pn5qvtu&m=0995c103b5e5&t=20150929&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01Pn5qvtu&m=0995c103b5e5&t=20150929&c=f>
>


-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by byndcivilization** [comment]
Cant replicate. @anderspeders can you try?

**Comment by KaitlinCCSI** [comment]
Just checked again and now it's fine, so it was just this morning.

On Tue, Sep 29, 2015 at 1:07 PM, Chris Perry <notifications@github.com>
wrote:

> Cant replicate. @anderspeders <https://github.com/anderspeders> can you
> try?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/403#issuecomment-144138477>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01Pn67CNn&m=10c4577721b0&t=20150929&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01Pn67CNn&m=10c4577721b0&t=20150929&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01Pn67CNn&m=10c4577721b0&t=20150929&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by anderspeders** [comment]
Thanks @KaitlinCCSI, closing issue.

**Comment by byndcivilization** [comment]
resolved
