### ISSUE TITLE
Metadata in wrong category on advanced search page

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#404]
Noticed this for 2 contracts. See screenshot example of one of them (other is Socfin contract):
![screen shot 2015-09-29 at 9 48 44 am](https://cloud.githubusercontent.com/assets/14825437/10167764/8baef566-668f-11e5-9f55-a4607d5fa13b.png)

**Comment by byndcivilization** [comment]
@anjesh theres still a missing country code but ive added logic to create blank space if country code doesnt exist

**Comment by anjesh** [comment]
Fixed. Thanks @byndcivilization. We are fixing the missing countries as well.
