### ISSUE TITLE
Advanced search page - country drop down needs to be in alphabetical order

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#405]
Advanced search page - country drop down needs to be in alphabetical order. Currently not so:

![image](https://cloud.githubusercontent.com/assets/12913915/10168941/2aa8039e-66cf-11e5-9979-51c5bbd19298.png)

cc @KaitlinCCSI

**Comment by byndcivilization** [comment]
Sorted by ISO2 in php here:
https://github.com/younginnovations/resourcecontracts-rc-subsite/blob/master/resources/views/layout/partials/search.blade.php

**Comment by anjesh** [comment]
Agree. Need to sort by name.

**Comment by anjesh** [comment]
Fixed.
