### ISSUE TITLE
Remove text for non-tagged documents (ONLY FOR RC) 

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#406]
![image](https://cloud.githubusercontent.com/assets/1101585/10171482/57d3ed8c-66a8-11e5-914c-617c924e76ae.png)

For post OLC launch: To be confirmed.

**Comment by anjesh** [comment]
Lets review how this can work. Maybe have a collapsible annotation list on the right will help and that gets auto-collapsed when there's no annotations. @manishgs

**Comment by anjesh** [comment]
Do we still want to consider this or shall we close this? @anderspeders

**Comment by charlesyoung** [comment]
@anderspeders is this still required?

**Comment by KaitlinCCSI** [comment]
If this is not undertaken and we keep status quo for annotation column, then the message when there are no annotations should change -- please use "document" rather than "contract" (ie "There are no annotations associated with this document."), as not all documents are contracts. See screenshot.
![screen shot 2017-01-13 at 3 20 01 pm](https://cloud.githubusercontent.com/assets/14825437/21946021/198e7cca-d9a4-11e6-9d3a-67c73fbb9ef7.png)

**Comment by man-git007** [comment]
@charlesyoung Are you suggesting like this in the screenshot?

![Screenshot from 2021-04-01 21-34-28](https://user-images.githubusercontent.com/23434972/113320347-24347e80-9332-11eb-9ef4-e939d07e81c8.png)

We might need to add no annotation added yet in the document label something like that. Also, Is it both for RC and OLC?

cc @SamCCSI

**Comment by charlesyoung** [comment]
@man-git007 I will get more info to you on this ticket.

**Comment by charlesyoung** [comment]
@man-git007 how much time will it take to develop an automatic routine to remove below text (including the scroll arows on the right) for all docs that have not yet been annotated. 

![image](https://user-images.githubusercontent.com/13888372/113985640-ad751500-984c-11eb-87be-4d0ac5026262.png)

_Note that this only applies to RC and not OLC._

**Comment by man-git007** [comment]
@charlesyoung Are you suggesting to update the text or removing the entire left side section

**Comment by charlesyoung** [comment]
Just removing the text for non-annotated docs. So keep the panel but just remove the text and scrollbar.

**Comment by charlesyoung** [comment]
Will it be possible to send through the time required by tomorrow?

**Comment by man-git007** [comment]
@charlesyoung The page would look like this
![Screenshot from 2021-04-09 09-43-53](https://user-images.githubusercontent.com/23434972/114126519-4cb30e80-9918-11eb-8119-d09ce087ec8f.png)

If this is the case, it would take about 1hr

cc @sweta-shrestha

**Comment by charlesyoung** [comment]
Thanks @man-git007 

So to confirm, it will take 1 hour to implement a routine that will remove all of the text in the left panel for **non-annotated** docs.

**Comment by man-git007** [comment]
@charlesyoung Yes, it's a tentative time estimate.

**Comment by charlesyoung** [comment]
@man-git007 How much time will be required to add the below text to the left panel for all docs that haven't yet been annotated? 

![image](https://user-images.githubusercontent.com/13888372/114507204-14bb0c80-9c33-11eb-96f8-b02c5426c416.png)

**Comment by charlesyoung** [comment]
@man-git007 just checking if this will be possible.

**Comment by charlesyoung** [comment]
@man-git007 ??

**Comment by man-git007** [comment]
@charlesyoung Yes, it can be done. We would be needing the text in Eng, Fr, and Ar. Also, I see a  link in that text. Please provide us the link as well.

cc @sweta-shrestha

**Comment by charlesyoung** [comment]
Minor update to the etxt. Only add 'This document has not yet been tagged'.

**Comment by adhikari-anish** [comment]
@charlesyoung The text has been updated to 'This document has not yet been tagged' in all 3 languages, the annotation title, and the scroll bar have been removed for RC site only. 
![image](https://user-images.githubusercontent.com/35035442/115428232-e8e6ea80-a221-11eb-9c9e-4ff4e7a2af13.png)
cc @man-git007 @sweta-shrestha

**Comment by charlesyoung** [comment]
Thanks @adhikari-anish, looks good. 

I'm hoping to get the translations to you as soon as possible so that this can be deployed on the Prod site.

**Comment by adhikari-anish** [comment]
@charlesyoung The translations have been done and are deployed in staging. According to the translation given, "**The document has not yet been tagged.**" translates to "**This document has not been flagged.**" in Arabic. Please verify once.
cc @man-git007

**Comment by charlesyoung** [comment]
Thanks @adhikari-anish 

Just confirming that you took the text from below Google sheet. 

https://docs.google.com/spreadsheets/d/1kQg8wJcW1nP6EywMs35PGco9-i0C7xiYlhIZ2ygdZis/edit#gid=0

**Comment by adhikari-anish** [comment]
@charlesyoung Yes, I took the text from that spreadsheet for French and Arabian. Also, for English, should I put "This document has not yet been tagged." from the above comment picture or "This document has not been tagged." from the google sheet.

**Comment by charlesyoung** [comment]
Thanks @adhikari-anish 

Sorry, I think we did a change to the English text so please use 'This document has not been tagged.'

You can do the updates on the Prod site.

**Comment by adhikari-anish** [comment]
@charlesyoung The changes are pushed to the production sites [RC](https://www.resourcecontracts.org/contract/ocds-591adf-2716478550/view#/pdf), [OLC](https://openlandcontracts.org/contract/ocds-591adf-1281238394/view#/pdf). Please verify and close the issue if it's okay. 
cc @man-git007 @sweta-shrestha

**Comment by charlesyoung** [comment]
Thanks. Please however note that its only for RC and not OLC.

**Comment by charlesyoung** [comment]
For RC please update the Prod site to what is shown on the Staging site i.e. 0 KEY CLAUSES should be removed.

**Comment by charlesyoung** [comment]
@adhikari-anish can we implement this on the Prod site? Staging is done but not yet Prod.

**Comment by adhikari-anish** [comment]
@charlesyoung Yes, the changes are only made for RC and not OLC. The changes have already been pushed to production also. Can you please clear the cache and try? 

![image](https://user-images.githubusercontent.com/35035442/117623469-91d69480-b193-11eb-82c2-ebbc811f9488.png)
![image](https://user-images.githubusercontent.com/35035442/117623492-98650c00-b193-11eb-913f-27bf9c7db185.png)

cc @SamCCSI @man-git007 @sweta-shrestha

**Comment by charlesyoung** [comment]
Yep, caching issue.

**Comment by charlesyoung** [comment]
@adhikari-anish will it be possible to look at this?

**Comment by adhikari-anish** [comment]
@charlesyoung 
The French text has been updated and is pushed to the production site. Please check it. Thank you.

![image](https://user-images.githubusercontent.com/35035442/121126041-3d344100-c847-11eb-9070-d828b584ff38.png)

@man-git007

**Comment by charlesyoung** [comment]
Many thanks @adhikari-anish
