### ISSUE TITLE
Order of contracts on advanced search page

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#407]
Are these ordered by upload date, or another way? It doesn't seem to be year, resource, name, country, or contract type. Can we please order them in any way except upload date, so that a user looking at the full list of contracts would have some sense of how the contracts are organized? My preference is either by signature year (and then alphabetically within year) or simply alphabetically by name.
![screen shot 2015-09-29 at 1 45 04 pm](https://cloud.githubusercontent.com/assets/14825437/10174615/56599580-66b0-11e5-9a9c-f8a252788a26.png)

**Comment by anjesh** [comment]
For now, the list is ordered by year. later we will have sort option for each header column in different issue.

**Comment by KaitlinCCSI** [comment]
Thanks. Could you please order by year descending? (So most recent
contracts show up first?)

On Wed, Sep 30, 2015 at 5:59 AM, Anjesh <notifications@github.com> wrote:

> For now, the list is ordered by year. later we will have sort option for
> each header column in different issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/407#issuecomment-144361052>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PnmX4VT&m=37768a52539b&t=20150930&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PnmX4VT&m=37768a52539b&t=20150930&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01PnmX4VT&m=37768a52539b&t=20150930&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by KaitlinCCSI** [comment]
Please order so that most recent contracts show up first.

**Comment by anjesh** [comment]
Contracts descending ordered by signature-year
