### ISSUE TITLE
Hide "contract text" from "contract view page" when type=metadata&status=rejected

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#408]
For "contract text" which has been evaluated as "Rejected" by an uploader, the text shall not be displayed next to the PDF-document.  

Can we implement this? eg. using the elastic search to filter the view:
http://resourcecontracts.elasticbeanstalk.com/contract?type=metadata&status=rejected

Question is if we can find a method with the current metadata to:
display PDF while we hide the OCR content

If this can be implemented we can avoid manual edits.

**Comment by anjesh** [comment]
"Reject" is a part of the workflow and could be used, but we need a mechanism to ensure that "reject" status is also published when the contract is published. Introduction of new field (Show Text: yes/no) will solve the problem.
