### ISSUE TITLE
Return carachters input missing from ascii?

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#41]
http://ebproject-dev.elasticbeanstalk.com/contract/7/pages#1

It appears as if the "return carachters" and anything else except a single space is stripped form the OCR docsplit. 

Could you clarify @anjesh ?

**Comment by anjesh** [comment]
This will be fixed in the next pdf processing module. The pdf-to-text functionality gives new-line, which didn't get translated to line-breaks when displayed in the html page. This is fixed in next deployment and also we will not be using docsplit now.

**Comment by anjesh** [comment]
Fixed. All the text files content generated via pdftotext/abbyy are converted using nl2br.
