### ISSUE TITLE
Duplicate contract - Salala 

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#410]
We have a duplicate contract (apologies if I have logged this one already)

Need to keep MT'ed text from this version (18 / 20 pages completed):http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/108/view

and apply it to the annotated version of the same contract: http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/1176/view#/pdf

**Comment by anjesh** [comment]
So after moving MT text to : http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/1176/view
we can delete this http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/108/view? 

1176 has 18 pages and 108 has 20 pages. I saw one duplicate page (page 17) in 108.

**Comment by SamCCSI** [comment]
Thanks Anjesh.

That is correct, except that MT has not processed all pages yet (still
waiting on pages 13 and 19).

Can we just keep all the MT processed pages that we have now and move them
to #1176 now? We can then ask our intern to manually transcribe page 13 for
us, rather than waiting for MT.

108 has two duplicate pages which should be deleted: please delete PDF
pages 12 and 19.

Let me know if anything is unclear.

Sam
cc @kaitlinccsi

On Thu, Oct 1, 2015 at 6:10 AM, Anjesh <notifications@github.com> wrote:

> So after moving MT text to :
> http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/1176/view
> we can delete this
> http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/108/view?
>
> 1176 has 18 pages and 108 has 20 pages. I saw one duplicate page (page 17)
> in 108.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/410#issuecomment-144614700>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by anjesh** [comment]
http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/108/view shows annotations. Still need to delete the pages, but i am afraid there might be some mismatch with the annotations pages and the linked pages. Please confirm the pages so that annotations links are not lost.

**Comment by SamCCSI** [comment]
Wonderful, thank you Anjesh!

Pages 12 and page 19 (of the PDF file) can be deleted.

For the annotations on current p. 12: can these be moved to p. 13 (new p.
12), so that they are not lost?

Once these two pages are deleted, all annotations will then be linked to
the correct page - currently they are incorrect because of those two
duplicates.

If you let me know when done, I can double check.

On Thu, Oct 1, 2015 at 1:44 PM, Anjesh <notifications@github.com> wrote:

> http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/108/view
> shows annotations. Still need to delete the pages, but i am afraid there
> might be some mismatch with the annotations pages and the linked pages.
> Please confirm the pages so that annotations links are not lost.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/410#issuecomment-144704361>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by anjesh** [comment]
Please have a look http://alpha.openlandcontracts.org/contract/108/view

**Comment by SamCCSI** [comment]
Page refs are perfect. This issue can be closed. Thank you @anjesh !!

On Fri, Oct 2, 2015 at 2:21 PM, Anjesh <notifications@github.com> wrote:

> Please have a look http://alpha.openlandcontracts.org/contract/108/view
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/410#issuecomment-145001597>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>
