### ISSUE TITLE
Annotation category headings on the Summary page 

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#413]
When I scroll down the "Summary" pages of all contracts, the Annotation Category Headings (General; Environment; Social; Fiscal; etc.) are not all in the same order, e.g... 

in the Thunder Bird International_Liberia contract http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/1046#annotations 
 they are ordered as: ALL; OTHER; GENERAL; SOCIAL; OPERATIONS; FISCAL; ENVIRONMENT 

whereas in the Green Valley_Ethiopia contract http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/1027#annotations 

they are ordered as: ALL; ENVIRONMENT; OTHER; GENERAL; OPERATIONS; FISCAL; SOCIAL

Need to have them appear in the same order on each Summary page - thank you!

@KaitlinCCSI @SamCCSI @anderspeders

**Comment by anjesh** [comment]
The clusters will be ordered as  
General, Environment, Fiscal, Social, Operations, Other.

See https://github.com/NRGI/resourcecontracts.org/issues/348#issuecomment-143639595

**Comment by anjesh** [comment]
Fixed now. Do verify.
