### ISSUE TITLE
Date contract annotation fields listing month before day (mm/dd/yy) rather than dd/mm/yyyy

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#414]
The contract annotations below are showing the date in the mm/dd/yy format rather than dd/mm/yyyy

Liberia, Sun Yeun Corporation, Timber Sale Contract, TSC Area A-16, 21 July 201	
http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/1177/view#/pdf/page/2/annotation/24491	
Date listed as 07-21-10, should be 21-07-2010

Heng Yue_Cambodia	
http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/1028/view#/pdf/page/1/annotation/23356	
Date listed as 11/08/2011, should be 08-11-2011

Sun Yeun Corporation A-15_Liberia	
http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/1044/view#/pdf/page/2/annotation/24960	
Date listed as 07-21-10, should be 21-07-2010

DRC, Maison NBK Service, Contrat de concession forestière N. 049, 25 avril 2011	
http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/1160/view#/pdf/page/11/annotation/23137	
Date listed as 04-25-11, should be 25-04-2011

Liberia, Alpha Logging & Processing Incorporated, Forest Management Contract, 6 October 2014	
http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/1162/view	
Date listed as 06-oct, should be 06-10-2006

@KaitlinCCSI @SamCCSI @anderspeders

**Comment by anderspeders** [comment]
Hi @JesseCCSI, 

These issues stem from the uploaded annotation texts from CCSI. The annotation text it self is uploaded as text without a format. There is therefore no opportunity to fix this for the annotations already uploaded in bulk. 

For future content created by CCSI using the administrator interface it will be easy to change and adjust content within each annotation.

**Comment by KaitlinCCSI** [comment]
Hi Anders, we had specifically discussed this earlier, because one of the
templates (can't remember which one - am working off of one hour of sleep)
was switching the date format and we couldn't do anything about it. You
said we could address once the contracts were uploaded; I had a note to
myself to specifically look at this issue based on our conversation.

On Wed, Sep 30, 2015 at 1:23 PM, Anders <notifications@github.com> wrote:

> Hi @JesseCCSI <https://github.com/JesseCCSI>,
>
> These issues stem from the uploaded annotation texts from CCSI. The
> annotation text it self is uploaded as text without a format. There is
> therefore no opportunity to fix this for the annotations already uploaded
> in bulk.
>
> For future content created by CCSI using the administrator interface it
> will be easy to change and adjust content within each annotation.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/414#issuecomment-144498392>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PnunclP&m=d7cfb1ff45e4&t=20150930&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PnunclP&m=d7cfb1ff45e4&t=20150930&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01PnunclP&m=d7cfb1ff45e4&t=20150930&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by byndcivilization** [comment]
@anjesh theres also an issue with editing and or annotating on anything past page 2 of a contract. see:
http://resourcecontracts.elasticbeanstalk.com/contract/1162/annotate
Im getting the following error:
[Error] Refused to get unsafe header "Accept-Ranges"
[Error] TypeError: undefined is not an object (evaluating 'shape.type')
	(anonymous function) (annotator.plugin.annotorious.js, line 19664)
	findIndex (annotator.plugin.annotorious.js, line 4758)
	find (annotator.plugin.annotorious.js, line 4738)
	_draw (annotator.plugin.annotorious.js, line 19663)
	(anonymous function) (annotator.plugin.annotorious.js, line 19681)
	forEach ([native code], line 0)
	(anonymous function) (annotator.plugin.annotorious.js, line 4473)
	_redraw (annotator.plugin.annotorious.js, line 19680)
	removeAnnotation (annotator.plugin.annotorious.js, line 19553)
	(anonymous function) (annotator.plugin.annotorious.js, line 19938)
	forEach ([native code], line 0)
	(anonymous function) (annotator.plugin.annotorious.js, line 4473)
	(anonymous function) (annotator.plugin.annotorious.js, line 19937)
	closure (annotator-full.min.js, line 436)
	dispatch (jquery.js, line 4670)
	handle (jquery.js, line 4338)
	trigger (jquery.js, line 4579)
	triggerHandler (jquery.js, line 5295)
	publish (annotator-full.min.js, line 429)
	(anonymous function) (annotator-full.min.js, line 1111)
	loadAnnotations (annotator-full.min.js, line 1116)
	_onLoadAnnotations (annotator-full.min.js, line 2328)
	(anonymous function) (annotator-full.min.js, line 17)
	_onLoadAnnotationsFromSearch (annotator-full.min.js, line 2339)
	(anonymous function) (annotator-full.min.js, line 17)
	fire (jquery.js, line 3148)
	fireWith (jquery.js, line 3260)
	done (jquery.js, line 9314)
	callback (jquery.js, line 9718)

**Comment by anderspeders** [comment]
Hi @KaitlinCCSI, 

That must have been a misunderstanding. 

I recall discussing that YI would assist harmonizing the date fields in the *metadata* but not for annotation content that include information on dates (as these two tasks are very different in scope).  

To address the issue at hand - the best option will be to fix the errors currently blocking CCSI from conducting these edits manually from the administrator backend. There is simply not resources or time available to have YI going through the annotation data making these edits manually. 

I have created issue #421 for this.

**Comment by KaitlinCCSI** [comment]
Okay. I was definitely talking about annotations, because it was the newer
excel template that was the problem. Thanks for trying to find a way for us
to fix this ourselves.

On Thu, Oct 1, 2015 at 12:26 AM, Anders <notifications@github.com> wrote:

> Hi @KaitlinCCSI <https://github.com/KaitlinCCSI>,
>
> That must have been a misunderstanding.
>
> I recall discussing that YI would assist harmonizing the date fields in
> the *metadata* but not for annotation content that include information on
> dates (as these two tasks are very different in scope).
>
> To address the issue at hand - the best option will be to fix the errors
> currently blocking CCSI from conducting these edits manually from the
> administrator backend. There is simply not resources or time available to
> have YI going through the annotation data making these edits manually.
>
> I have created issue #421
> <https://github.com/NRGI/resourcecontracts.org/issues/421> for this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/414#issuecomment-144562073>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PnyqCnf&m=52c37b6aeb4f&t=20150930&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PnyqCnf&m=52c37b6aeb4f&t=20150930&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01PnyqCnf&m=52c37b6aeb4f&t=20150930&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>
