### ISSUE TITLE
Dropdowns on search page > can't click on certain dropdowns 

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#415]
I can't click on the Contract Type and Annotation Category dropdowns on the search page (had the same issue yesterday). The other four are working correctly (year, country, resource, company name). 

Apologies if this is due to work being done on these at the moment. 

@KaitlinCCSI @SamCCSI @anderspeders

**Comment by anjesh** [comment]
@JesseCCSI Are you still getting this problem? I tried in different screen sizes and seems to be working ok here.

**Comment by JesseCCSI** [comment]
Thanks for following up @anjesh - just checked different browsers on PC and Mac and this seems to be fixed now.
