### ISSUE TITLE
Mapping dropdowns - Contract Type

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#416]
For contract type dropdowns:

Amended and Restated Land Concession Agreement should have been mapped to Concession Agreement per the mapping document. https://docs.google.com/spreadsheets/d/18xCuXuxQSbxlhxUgufNWLiLO_V22wh3pd7oC0Q8Ts1k/edit#gid=852958550

Contrat de Concession forestière should be mapped to Contrat de Concession Forestière

@anderspeders

**Comment by anjesh** [comment]
Fixed.
