### ISSUE TITLE
Deployment documentation

### ISSUE THREAD

**Issue by byndcivilization** [NRGI/resourcecontracts.org#417]
We need good documentation of stack deployment going forward.

**Comment by anjesh** [comment]
The installation guides are maintained in each repository of the components. 

The main RC system 
https://github.com/NRGI/resourcecontracts.org/blob/master/readme.md

We are using Amazon Elasticsearch service to index the contracts.

The following API reads the data from Elasticsearch
https://github.com/younginnovations/resourcecontracts-api/blob/master/readme.md

The subsite reads the data from the API.
https://github.com/younginnovations/resourcecontracts-rc-subsite

**Comment by anjesh** [comment]
Also maintained here https://github.com/NRGI/resourcecontracts.org/wiki/Deployment-Documentation , which will be expanded slowly
