### ISSUE TITLE
8 contracts missing annotations 

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#420]
The following contracts are missing annotations: the message "There are no annotations associated with this contract" appears in the annotations sidebar. 

South Sudan, Nile Trading & Development, Lease Agreement, 11 March 2008	http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/1180/view

DRC, Compagine Des Bois, Contrat de concession forestière, 2011	http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/1128/view

Cameroun, SOSUCAM, Bail Emphytéotique et Décret d’Autorisation N. 2006/087, 2006	http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/1131/view

Mali, CLETC, Convention de Cession et de Bail, 2009	http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/1132/view

DRC, SODEFOR, Contrat de Concession Forestière, N. 060/14, 2014	http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/1133/view

DRC, Bakri-Bois, Contrat de concession forestière et avenant N. 1 au contrat, 2011	http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/1126/view

DRC, Bego Congo, Contrat de concession forestière et avenant N. 1 au contrat, 2011	http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/1127/view

DRC, SODEFOR, Contrat de Concession Forestière, N. 061/14, 2014	http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/1134/view

@KaitlinCCSI @SamCCSI @anderspeders

**Comment by anjesh** [comment]
Fixed for South Sudan, Nile Trading & Development, Lease Agreement, 11 March 2008 http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/1180/view (from OLC Migratation)

The following two are present in the system so the migration didn't happen for them. We will fix annotations for these. See https://github.com/NRGI/resourcecontracts.org/issues/424
DRC, Compagine Des Bois, Contrat de concession forestière, 2011 http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/1128/view

DRC, Bakri-Bois, Contrat de concession forestière et avenant N. 1 au contrat, 2011 http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/1126/view

For the remainings, they are entered manually so need annotations for the remanings. 
cc @anderspeders

**Comment by SamCCSI** [comment]
Thanks Anjesh,

Bego Congo *has* been annotated -
https://www.dropbox.com/s/ff37wxi0x0vy2tu/bego%20congo_drc.xlsx

and listed in row 47 of the migration list (batch 2):
https://docs.google.com/spreadsheets/d/13HFzsddfT9OkeAmtHLtwzpl2QP-IHaYxP8wB8adUljg/edit?usp=sharing

cc @kaitlinccsi @jesseccsi



On Thu, Oct 1, 2015 at 1:25 PM, Anjesh <notifications@github.com> wrote:

> Fixed for South Sudan, Nile Trading & Development, Lease Agreement, 11
> March 2008
> http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/1180/view
> (from OLC Migratation)
>
> The following two are present in the system so the migration didn't happen
> for them. We will fix annotations for these. See #424
> <https://github.com/NRGI/resourcecontracts.org/issues/424>
> DRC, Compagine Des Bois, Contrat de concession forestière, 2011
> http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/1128/view
>
> DRC, Bakri-Bois, Contrat de concession forestière et avenant N. 1 au
> contrat, 2011
> http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/1126/view
>
> For the remainings, they are entered manually so need annotations for the
> remanings.
> cc @anderspeders <https://github.com/anderspeders>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/420#issuecomment-144701407>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by SamCCSI** [comment]
@anjesh is it possible 'unpublish' the following unannotated contracts, so
that they stay in the system but are not yet live and publicly available? I
tried but couldn't figure out how.

http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/1131/view
http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/1132/view
http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/1133/view
http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/1134/view

@KaitlinCCSI <https://github.com/KaitlinCCSI> @jesseccsi

On Thu, Oct 1, 2015 at 3:20 PM, Sam Szoke-Burke <s.burke@columbia.edu>
wrote:

> Thanks Anjesh,
>
> Bego Congo *has* been annotated -
> https://www.dropbox.com/s/ff37wxi0x0vy2tu/bego%20congo_drc.xlsx
>
> and listed in row 47 of the migration list (batch 2):
> https://docs.google.com/spreadsheets/d/13HFzsddfT9OkeAmtHLtwzpl2QP-IHaYxP8wB8adUljg/edit?usp=sharing
>
> cc @kaitlinccsi @jesseccsi
>
>
>
> On Thu, Oct 1, 2015 at 1:25 PM, Anjesh <notifications@github.com> wrote:
>
>> Fixed for South Sudan, Nile Trading & Development, Lease Agreement, 11
>> March 2008
>> http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/1180/view
>> (from OLC Migratation)
>>
>> The following two are present in the system so the migration didn't
>> happen for them. We will fix annotations for these. See #424
>> <https://github.com/NRGI/resourcecontracts.org/issues/424>
>> DRC, Compagine Des Bois, Contrat de concession forestière, 2011
>> http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/1128/view
>>
>> DRC, Bakri-Bois, Contrat de concession forestière et avenant N. 1 au
>> contrat, 2011
>> http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/1126/view
>>
>> For the remainings, they are entered manually so need annotations for the
>> remanings.
>> cc @anderspeders <https://github.com/anderspeders>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/NRGI/resourcecontracts.org/issues/420#issuecomment-144701407>
>> .
>>
>
>
>
> --
>
>
>
> *SAM SZOKE-BURKE*
> *Legal Researcher**Columbia Center on Sustainable Investment*
> Columbia Law School - The Earth Institute, Columbia University
> Level 1, Warren Hall, 410 W116th St. New York, NY 10027
> | (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
> | s.burke@columbia.edu
> | www.ccsi.columbia.edu | @CCSI_Columbia
> <https://twitter.com/CCSI_Columbia> | @samszokeburke
> <http://twitter.com/samszokeburke>
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by anjesh** [comment]
We are adding "Unpublish" button in the contract page now, admin should be able to do the unpublish now.

**Comment by anjesh** [comment]
Added unpublish button now in contract view page in admin. And unpublished above 4 contracts. 

![image](https://cloud.githubusercontent.com/assets/120488/10279079/55eaa4be-6b82-11e5-9541-c1998e48bb9c.png)

**Comment by SamCCSI** [comment]
Thanks very much Anjesh.

All 8 have been taken care of in one way or another so this issue can be
closed.

On Mon, Oct 5, 2015 at 7:14 AM, Anjesh <notifications@github.com> wrote:

> Added unpublish button now in contract view page in admin. And unpublished
> above 4 contracts.
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/120488/10279079/55eaa4be-6b82-11e5-9541-c1998e48bb9c.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/420#issuecomment-145498265>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>
