### ISSUE TITLE
Backend not working for correcting and editing PDF annotations

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#421]
![image](https://cloud.githubusercontent.com/assets/1101585/10208137/260bcb42-679f-11e5-8194-c6d2713da46f.png)

Related to issue #414

**Comment by byndcivilization** [comment]
@anjesh see:
http://resourcecontracts.elasticbeanstalk.com/contract/1162/annotate

Im getting the following error:
[Error] Refused to get unsafe header "Accept-Ranges"
[Error] TypeError: undefined is not an object (evaluating 'shape.type')
(anonymous function) (annotator.plugin.annotorious.js, line 19664)
findIndex (annotator.plugin.annotorious.js, line 4758)
find (annotator.plugin.annotorious.js, line 4738)
_draw (annotator.plugin.annotorious.js, line 19663)
(anonymous function) (annotator.plugin.annotorious.js, line 19681)
forEach ([native code], line 0)
(anonymous function) (annotator.plugin.annotorious.js, line 4473)
_redraw (annotator.plugin.annotorious.js, line 19680)
removeAnnotation (annotator.plugin.annotorious.js, line 19553)
(anonymous function) (annotator.plugin.annotorious.js, line 19938)
forEach ([native code], line 0)
(anonymous function) (annotator.plugin.annotorious.js, line 4473)
(anonymous function) (annotator.plugin.annotorious.js, line 19937)
closure (annotator-full.min.js, line 436)
dispatch (jquery.js, line 4670)
handle (jquery.js, line 4338)
trigger (jquery.js, line 4579)
triggerHandler (jquery.js, line 5295)
publish (annotator-full.min.js, line 429)
(anonymous function) (annotator-full.min.js, line 1111)
loadAnnotations (annotator-full.min.js, line 1116)
_onLoadAnnotations (annotator-full.min.js, line 2328)
(anonymous function) (annotator-full.min.js, line 17)
_onLoadAnnotationsFromSearch (annotator-full.min.js, line 2339)
(anonymous function) (annotator-full.min.js, line 17)
fire (jquery.js, line 3148)
fireWith (jquery.js, line 3260)
done (jquery.js, line 9314)
callback (jquery.js, line 9718)

**Comment by anjesh** [comment]
We have updated the annotation UI in admin. Please have a look, this should fix previous issues here and there. It follows the subsite annotation UI.

**Comment by SamCCSI** [comment]
Sorry, not following this - Is the 'edit annotation' functionality ready
for testing by CCSI?

cc @kaitlinccsi

On Tue, Oct 13, 2015 at 6:54 AM, Anjesh <notifications@github.com> wrote:

> We have updated the annotation UI in admin. Please have a look, this
> should fix previous issues here and there. It follows the subsite
> annotation UI.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/421#issuecomment-147682277>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by anderspeders** [comment]
@SamCCSI @KaitlinCCSI, 

Yes, editing of PDF-annotations is now available as a feature from the backend. Please, as always, file detailed issue reports for things that are not working. 

Once you have issues to report we will reopen this ticket. 

![Uploading image.png…]()

**Comment by anjesh** [comment]
We also created this interface in the metadata edits for quick edits/deletes of the annotations https://github.com/NRGI/resourcecontracts.org/issues/520#issuecomment-148588058 though you have to go to annotation ui for adding new ones.
