### ISSUE TITLE
Metadata - Type of Contract 

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#422]
The following 3 contracts have the incorrect 'Type of Contract' listed in this metadata field: 

Firestone Liberia, Inc. - Liberia, 2008	http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/681/view	"Type of Contract" reads "Amended and Restated Concession Agreement" whereas it should read "Concession Agreement" 

DRC, Compagine Des Bois, Contrat de concession forestière, 2011	http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/1128/view	
"Type of Contract" reads "Contrat de concession forestière" whereas it should read "Contrat de Concession Forestière"

Mali, CLETC, Convention de Cession et de Bail, 2009	http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/1132/view	
"Type of contract" field in metadata should read "Contrat de Concession Agricole" - this contract type also appears to be missing from the Contract Type dropdown (listed under 'Please also add the following new fields for the Contract Type Dropdown Menu:' in this google doc https://docs.google.com/spreadsheets/d/18xCuXuxQSbxlhxUgufNWLiLO_V22wh3pd7oC0Q8Ts1k/edit#gid=852958550 ) 

@KaitlinCCSI @SamCCSI @anderspeders

**Comment by anjesh** [comment]
Fixed.
