### ISSUE TITLE
Associated Documents

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#423]
Minor formatting issue as noted below. 

However do we need to show the parent contract because its not an associated document and it is the same as the contract opened by the user. 

![image](https://cloud.githubusercontent.com/assets/13888372/10216171/552ae042-6827-11e5-8eea-3ae4e048be95.png)

**Comment by byndcivilization** [comment]
@anderspeders are we addressing associated docs this sprint or can we move it until 10

**Comment by anjesh** [comment]
This particular UI bug is fixed.
