### ISSUE TITLE
More duplicate contracts from OLC Migration

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#424]
We found that there are 4 contracts which are already present in the system and hence couldn't be migrated from the excel. See the links to the contracts already present in our system.

DRC, Bakri Bois Corporation, Contrat de concession forestière et avenant N. 1, 8 avril 2011
http://resourcecontracts.elasticbeanstalk.com/contract/1126

DRC, Compagnie des Bois, Contrat de concession forestière, 24 octobre 2011 
http://resourcecontracts.elasticbeanstalk.com/contract/1128

DRC, Megabois, Contrat de concession forestière, 13 decembre 2011
http://resourcecontracts.elasticbeanstalk.com/contract/36

Ethiopia, CLC Industries PLC, Land Lease Agreement, 26 December 2009
http://resourcecontracts.elasticbeanstalk.com/contract/1023

We will need to delete these and run migration for these contracts only. 

@anderspeders

**Comment by SamCCSI** [comment]
I am just on my phone right now so can't check. But I suspect these have
been submitted to mechanical Turk.

If so this is the same issue as the other contract where one. Erosion has
no annotations but has MT in process. The other has annotations but no MT.

Is it possible to combine the MT with the annotations for these 4 as well?

Cc @kaitlinccsi @jesseccsi



On Oct 1, 2015, at 10:37 AM, Anjesh <notifications@github.com> wrote:

We found that there are 4 contracts which are already present in the system
and hence couldn't be migrated from the excel. See the links to the
contracts already present in our system.

DRC, Bakri Bois Corporation, Contrat de concession forestière et avenant N.
1, 8 avril 2011
http://resourcecontracts.elasticbeanstalk.com/contract/1126

DRC, Compagnie des Bois, Contrat de concession forestière, 24 octobre 2011
http://resourcecontracts.elasticbeanstalk.com/contract/1128

DRC, Megabois, Contrat de concession forestière, 13 decembre 2011
http://resourcecontracts.elasticbeanstalk.com/contract/36

Ethiopia, CLC Industries PLC, Land Lease Agreement, 26 December 2009
http://resourcecontracts.elasticbeanstalk.com/contract/1023

We will need to delete these and run migration for these contracts only.

@anderspeders <https://github.com/anderspeders>

—
Reply to this email directly or view it on GitHub
<https://github.com/NRGI/resourcecontracts.org/issues/424>.

**Comment by anjesh** [comment]
Yes Correct. We can move the annotations to these contracts without creating the new ones. 

All MT pages for these 2 are received but yet to be approved.
http://resourcecontracts.elasticbeanstalk.com/mturk/1126
http://resourcecontracts.elasticbeanstalk.com/mturk/1128

This is MT complete.
http://resourcecontracts.elasticbeanstalk.com/contract/1023

This is yet to send to MT. 
http://resourcecontracts.elasticbeanstalk.com/contract/36

**Comment by SamCCSI** [comment]
Hi Anjesh,

Is there a way to check whether this contract was previously submitted to
MT? There is no record of it now, but our intern charles is relatively
certain that he submitted a Megabois contract to MT, and now cannot find it.

http://resourcecontracts.elasticbeanstalk.com/contract/36

Charles says:
*This is the one titled "Test Megabois DRC".  I thought this was just a
contract uploaded to test the system...  There was one page that the system
would not let me "Accept" and now I don't see the contract on the
Mechanical Turk....*


On Thu, Oct 1, 2015 at 10:37 AM, Anjesh <notifications@github.com> wrote:

> We found that there are 4 contracts which are already present in the
> system and hence couldn't be migrated from the excel. See the links to the
> contracts already present in our system.
>
> DRC, Bakri Bois Corporation, Contrat de concession forestière et avenant
> N. 1, 8 avril 2011
> http://resourcecontracts.elasticbeanstalk.com/contract/1126
>
> DRC, Compagnie des Bois, Contrat de concession forestière, 24 octobre 2011
> http://resourcecontracts.elasticbeanstalk.com/contract/1128
>
> DRC, Megabois, Contrat de concession forestière, 13 decembre 2011
> http://resourcecontracts.elasticbeanstalk.com/contract/36
>
> Ethiopia, CLC Industries PLC, Land Lease Agreement, 26 December 2009
> http://resourcecontracts.elasticbeanstalk.com/contract/1023
>
> We will need to delete these and run migration for these contracts only.
>
> @anderspeders <https://github.com/anderspeders>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/424>.
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by anjesh** [comment]
There's any log on the submission of contract 36 to Mturk as can be seen here.

Otherwise there should be entry on Mturk in the activity log

![image](https://cloud.githubusercontent.com/assets/120488/10278691/07663fb8-6b7f-11e5-9447-f33378684028.png)

**Comment by anjesh** [comment]
Here's the activity log http://resourcecontracts.elasticbeanstalk.com/activities?contract=36 which doesn't have entry on Mturk.

**Comment by SamCCSI** [comment]
Thanks.

Ok, I have 'unpublished' the contract, and then re-published metadata and annotations. But the PDF does not display.

![screen shot 2015-10-05 at 9 26 21 am](https://cloud.githubusercontent.com/assets/12913915/10281549/3419f158-6b43-11e5-8c26-38b19dd181c1.png)


How do I republish the PDF itself, without also displaying the PDF text (that needs to be MT'ed first)?

![screen shot 2015-10-05 at 9 26 31 am](https://cloud.githubusercontent.com/assets/12913915/10281553/395b0166-6b43-11e5-83b4-675ad6359158.png)

**Comment by anjesh** [comment]
You also have to publish PDF text for pdf to make it appear. OCR Text view is controlled by "Show Pdf text" option - which is currently set to "No". I just republished all and pdf is now showing, but not the text.

**Comment by SamCCSI** [comment]
Thanks for clarifying, Anjesh. Much appreciated.

On Mon, Oct 5, 2015 at 10:16 AM, Anjesh <notifications@github.com> wrote:

> You also have to publish PDF text for pdf to make it appear. OCR Text view
> is controlled by "Show Pdf text" option - which is currently set to "No". I
> just republished all and pdf is now showing, but not the text.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/424#issuecomment-145542753>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>
