### ISSUE TITLE
Unpublished Associated Documents shown in contract page?

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#425]
Why is the associated document 'Basic Agreement between SC6 and SC14' shown on RC although it hasn't yet been published? It is also only shown on the high-level page on not the summary page. 

![image](https://cloud.githubusercontent.com/assets/13888372/10216555/41f881e8-682a-11e5-9450-8a9d227d4e12.png)

![image](https://cloud.githubusercontent.com/assets/13888372/10216530/14b9054a-682a-11e5-940e-080c879db3aa.png)

**Comment by anjesh** [comment]
For which contract is this?

**Comment by anjesh** [comment]
Please share the RC link for this contract.

**Comment by charlesyoung** [comment]
The Philodrill Corporation - SC No. 14

http://alpha.resourcecontracts.org/contract/1120/view

**Comment by charlesyoung** [comment]
The Philodrill Corporation - SC No. 14

http://alpha.resourcecontracts.org/contract/1120/view

**Comment by anjesh** [comment]
The idea is to show the unpublished supporting contracts but without the link in the subsites (the link you are seeing will be disabled). Both the summary and contract view page should show all the supporting contracts but hide the link for the unpublished ones. 

@anderspeders thoughts?

**Comment by charlesyoung** [comment]
I think that this will be confusing to the public. Why are we changing the model of only showing what has been published?

**Comment by anjesh** [comment]
cc @byndcivilization @anderspeders

**Comment by anderspeders** [comment]
Agree with @charlesyoung here, 

Either contract (or associated contract) should appear with link or it should not appear at all. 

@anjesh: This possibly addresses the issue that there is no use case for having contract with only published metadata but no published contract in PDF or text.

**Comment by anderspeders** [comment]
Pushing this to sprint 10, 

@anjesh Do make sure you have ask if any of this is unclear.

**Comment by anjesh** [comment]
Fixed. Only published suppporting/parent documents are listed.
