### ISSUE TITLE
Text processing

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#426]
I experienced this also during my demo last week. I receive an email saying that the text processing has been completed but when I review the text there is nothing. 

![image](https://cloud.githubusercontent.com/assets/13888372/10219724/9724b8dc-6841-11e5-80c4-392e23fa75d5.png)

**Comment by anjesh** [comment]
There has been change in the auth-config for the OCR processing during deployment yesterday. It probably happened last time as well. We just fixed it now. Is working now.

**Comment by anjesh** [comment]
Will find a mechanism to ensure that the config are intact during deployment.
