### ISSUE TITLE
Reupload PDF doc

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#427]
Will it be possible to reupload a PDF doc in cases where an incorrect contract was uploaded, etc and not have to delete the contract with all the captured metadata and annotations? 

The request comes from Abigail Ocate from the PH-EITI Secretariat.

**Comment by anderspeders** [comment]
Worth considering for sprint 10.

**Comment by anjesh** [comment]
When the contract is uploaded, the pdf goes through processing - splitting pdf pages, OCR those pages (through pdftotext cmd or abby) and saves to the database. So we have deliberately not allowed re-upload pdf. Reuploading means first deleting three sets of data - whole pdf file, split pdf pages, and text content. That means if annotations are already added, then there might be problems with annotations linkage if the reuploaded file is different or has different number of pages.

**Comment by anjesh** [comment]
Reupload is now included in edit functionality. User can re-upload file by clicking "change" link

![image](https://cloud.githubusercontent.com/assets/120488/10539964/81c42d0e-7423-11e5-9266-5e2f40093255.png)

**Comment by SamCCSI** [comment]
can you please change the wording from "Change" to "Replace file"?

That is more clear and is what is used by, eg, Soundcloud: [image: Inline
image 1]

On Fri, Oct 16, 2015 at 6:48 AM, Anjesh <notifications@github.com> wrote:

> Closed #427 <https://github.com/NRGI/resourcecontracts.org/issues/427>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/427#event-437402971>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by SamCCSI** [comment]
![image](https://cloud.githubusercontent.com/assets/12913915/10541693/03c10752-73e1-11e5-9c9a-989eab6255f5.png)
