### ISSUE TITLE
Alpha and PH-EITI DB's

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#428]
The PH-EITI DB is for some reason different from the Alpha site. 

Contracts uploaded by PH-EITI are going to the ph-eiti.jericoaragon.com site but not to the Alpha site. 

The two should point to the same DB right?

**Comment by anderspeders** [comment]
Can you link to examples on the PH-EITI site which are not represented in the RC backend?

**Comment by charlesyoung** [comment]
Searching for Philippines on the PH-EITI site results in 41 contracts while doing the same search on the Alpha site results in 13 contracts.

**Comment by anderspeders** [comment]
My guess is that PH-EITI is fetching contracts incl. unpublished. 

While RC.org is publishing only *published* contracts. 

@byndcivilization might know more.

**Comment by byndcivilization** [comment]
I think so but check with @anjesh on api. I havent seen the admin implementation that PH is using. Is it different than the main CCSI/RC.org contract admin site?

**Comment by charlesyoung** [comment]
'Taganito Mining Corporation - MPSA No. 266-2008-XIII (SMR)' has been published but isn't showing on the Alpha site while showing on http://ph-eiti.jericoaragon.com/search?q=Taganito

**Comment by anderspeders** [comment]
Yes, the bakend link here: http://resourcecontracts.elasticbeanstalk.com/contract/85

@anjesh @byndcivilization Any idea why this is not showing on RC front end?

**Comment by anjesh** [comment]
It doesn't have category (OLC or RC). Infact today we have pulled a list of contracts without category mentioned. I will share them shortly.

**Comment by anjesh** [comment]
"My guess is that PH-EITI is fetching contracts incl. unpublished."  Incorrect.

API will only provide the published contracts. The RC and OLC site pulls the contracts with those categories mentioned as the category is hard-coded in the used API. With country subsite, they pull contracts belonging to the country but from either rc or olc or even if it is not mentioned.

**Comment by anderspeders** [comment]
thanks for clarifying
