### ISSUE TITLE
Text still showing for 3 contracts listed in issue #386 & 1 contract is showing as page not found

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#429]
Please apply the same message as the others listed in #386 - many thanks! 

Horizon Plantations PLC_Ethiopia
http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/1029/view#/text

Heng Yue_Cambodia
http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/1028/view#/text 

Liberia, Liberia Forest Products Incorporated, Investment Agreement, 21 December 2007
http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/1172/view#/text 

Also, I'm getting an error when I click on this contract link: http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/1176/view#/text
Error 404: the page you’re looking for doesn’t exist 

cc @KaitlinCCSI @SamCCSI @anderspeders @anjesh

**Comment by anjesh** [comment]
Jesse you may do that from the admin. After updating the option for "Show Text" to "No", you have to publish the metadata and then subsite will show the message. I have re-published the above 3 contracts.

And http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/1176/view#/text one is deleted and its annotations moved to http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/108/view#/text. It's duplicate one of 108. See https://github.com/NRGI/resourcecontracts.org/issues/410

**Comment by JesseCCSI** [comment]
Many thanks, @anjesh !
