### ISSUE TITLE
Improve faceted search

### ISSUE THREAD

**Issue by jedm** [NRGI/resourcecontracts.org#43]
As a user, I want to refine my search results by changing the order in which they display and by narrowing down the results from my initial search, so that I can more easily find the contracts or clauses most relevant to my interest.

eg:

a) Search "environmental monitoring and enforcement" for oil contracts, then sort results to display by year or by country name

b) Search "arbitration,"  then exclude some results based on company, or year of signature

**Comment by anderspeders** [comment]
All published files will be included in the elastic search

**Comment by jedm** [comment]
OK and that means all files as well as all clauses, metadata and annotation content too, yes? 

Here's an example of comparison in Elasticsearch with 4 results pinned: http://goo.gl/sqzttz. 

In the example you can pin the original item (ie, contract), but not contents within the item, so one question is what counts as the smallest "node" that's a compare-able result, an entire file or a single clause/annotation?

In the raw results (before select/pin/compare), also need to decide — re UI— if ALL facets display or only some - otherwise will be overwhelming to many users.

**Comment by anderspeders** [comment]
Refining user story: 

Faceted search: As a user want to find contracts from: Sierra Leone (metadata) *and* stabilization clause (annotation tag) 

Result: Display of 5 contracts with these features

**Comment by anjesh** [comment]
By default, all the contracts will be listed. There will be options to do free-text search or filter by country or year of signature. These are currently covered in sprint 2. 
![image](https://cloud.githubusercontent.com/assets/120488/8429794/ac047a8e-1f4a-11e5-8c58-4646bf2a8751.png)

---- 

The free-text search searches for the given word, say 'stabilization'. The contracts are tagged as annotation, metadata, text based on where the word is found. Also the country and year are filled in the select-box, which the found contracts have. 

![image](https://cloud.githubusercontent.com/assets/120488/8429796/b20812ba-1f4a-11e5-9448-672559dc42f6.png)

---- 

The user may remove country (say benin) or year, then the results are updated. 

![image](https://cloud.githubusercontent.com/assets/120488/8429798/b5ecb2aa-1f4a-11e5-9b94-bf8ed942a412.png)

---- 

The user may also decide to uncheck one of the annotation, text or metadata and the results are updated accordingly. 

![image](https://cloud.githubusercontent.com/assets/120488/8429807/d5542bf0-1f4a-11e5-8a84-8cced0c15b76.png)

Thoughts, comments? @anderspeders

**Comment by anderspeders** [comment]
Looks good, 

I would also suggest a search field for <annotation tags> eg. **stabilization clause** or **environmental protection clause**.

@SamCCSI any initial feedback on this? Note that this is still be an early version.

**Comment by anjesh** [comment]
Faceted search in place in subsite. Still improvements to be done like the one suggested by Anders. Need more discussion, in new issue #118
