### ISSUE TITLE
Annotation boxes in right-hand corner - make more consistent

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#430]
The structure of annotation boxes in righthand corner is haphazard: the annotation fields listed in the box appear to be random, and some are only in one column list, while others have more than one field in the same row. See screenshots. Fixing consistency is not crucial for sprint 9, but should be addressed in sprint 10. 

![screen shot 2015-10-01 at 6 00 42 pm](https://cloud.githubusercontent.com/assets/14825437/10226304/eb9b33d0-6866-11e5-82d9-955e94656a9f.png)
![screen shot 2015-10-01 at 6 01 05 pm](https://cloud.githubusercontent.com/assets/14825437/10226308/ef48e41e-6866-11e5-8fe8-3a89474a9665.png)

cc @jedm

**Comment by byndcivilization** [comment]
@anjesh is that just a function of sizing? i.e. they appear in a column because the annotation category titles are too big to allwo for multiple categories on a single page? Maybe if we sort those by english name on load that would help. Another option would be to shorten the length of text displayed.

**Comment by anjesh** [comment]
Yes we are truncating the length of the annotation to certain number of characters before ellipsis. Right now the annotations categories are pulled without applying any sort. Shall we just sort and show the first five annotations, one per line?

**Comment by KaitlinCCSI** [comment]
That sounds fine to me, Anjesh.

On Thu, Oct 1, 2015 at 6:28 PM, Anjesh <notifications@github.com> wrote:

> Yes we are truncating the length of the annotation to certain number of
> characters before ellipsis. Right now the annotations categories are pulled
> without applying any sort. Shall we just sort and show the first five
> annotations, one per line?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/430#issuecomment-144779775>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PnQsEhD&m=a9ff463abe4c&t=20151001&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PnQsEhD&m=a9ff463abe4c&t=20151001&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01PnQsEhD&m=a9ff463abe4c&t=20151001&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by anjesh** [comment]
This is how it appears now for all the contract

![image](https://cloud.githubusercontent.com/assets/120488/10299554/1156625a-6c0b-11e5-861f-1e8da3ecd9b1.png)

**Comment by jedm** [comment]
Please change icon from pencil to speech balloon so it matches the icon recently selected for Annotations in the Contract view page.

**Comment by anderspeders** [comment]
Agree @jedm, 

@anjesh would be great if this could be done before launch.

**Comment by anjesh** [comment]
Sure. cc @hello-deepak

**Comment by anjesh** [comment]
Fixed annotation icon in contract summary page.
