### ISSUE TITLE
Contracts with missing category - RC/OLC

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#431]
Here are the list of contracts which doesn't have category mentioned, hence they will not appear in the RC or OLC subsite. 

To quickly add category to these contracts, simply use the contract-id from the excel and put it in this url http://resourcecontracts.elasticbeanstalk.com/contract/[contract-id-here]
Republish these contracts to make them appear in the RC/OLC subsite.

https://docs.google.com/spreadsheets/d/1a68lxZjDacxwQoeABkqmqZCVj67wqW5nWz7YNXFXMRQ/edit?ts=560d0246#gid=0

cc @anderspeders @charlesyoung

**Comment by anderspeders** [comment]
@charlesyoung I think many of these are indeed from the Philippines. 

Could you ask the team at PH-EITI to make these edits (by adding the category to be ResourceContracts)?

**Comment by charlesyoung** [comment]
I looked at one contract http://resourcecontracts.elasticbeanstalk.com/contract/76 which seemed to not have the category noted but it was actually clicked but not showing. Am I missing something here? 

![image](https://cloud.githubusercontent.com/assets/13888372/10244523/45d087ee-6900-11e5-882c-d10f5b702ce5.png)

![image](https://cloud.githubusercontent.com/assets/13888372/10244539/53c4fbaa-6900-11e5-9b3d-0a6b66c53ef1.png)

**Comment by anderspeders** [comment]
Yes, agree @charlesyoung, 

It looks like an non-manual error.

**Comment by charlesyoung** [comment]
Any ideas? I have a call with Philippines on Tuesday.

**Comment by anjesh** [comment]
That's correct. Before it was checkbox because we thought contract could belong to both. Later we changed to radio-button so one option is ticked (RC by default) when contract is added (edited even if category is missing), so such missing category wouldn't happen for new contracts from now on. For the above missing ones, one has to go in the contract edit and save to insert the category into the database.

**Comment by charlesyoung** [comment]
Thanks @anjesh. Can I please ask you to recreate the list of contracts which don't have a category noted but add a column for country.

**Comment by anjesh** [comment]
All the contracts have now category mentioned. 

![image](https://cloud.githubusercontent.com/assets/120488/10507896/93402906-7343-11e5-8fc2-168a480f60e5.png)
