### ISSUE TITLE
RC: Data cleaning and harmonization of metadata

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#432]
Pull data fields for the following:

- Company Name
- Resource 
- Contract type

- Annotation category

These will all require mapping to current codelists.

@anjesh Can you provide an expot so that we can begin the data mapping?

**Comment by anjesh** [comment]
Here are the spreadsheets for the different unmapped codelist

* [Company names](https://docs.google.com/spreadsheets/d/1Ytw6N6AvJCUnTEiCl7TMipP_afpRAgVV6-9lpN9Xc_w/edit?ts=5615fad5#gid=0)
* [Resources] (https://docs.google.com/spreadsheets/d/1Ytw6N6AvJCUnTEiCl7TMipP_afpRAgVV6-9lpN9Xc_w/edit?ts=5615fad5#gid=767430250)
* [Contract Types] (https://docs.google.com/spreadsheets/d/1Ytw6N6AvJCUnTEiCl7TMipP_afpRAgVV6-9lpN9Xc_w/edit?ts=5615fad5#gid=748511877)
* [Annotations Categories](https://docs.google.com/spreadsheets/d/1CQJsDOXoSKnv3abSDfFA-J6r_Tmn2Nxzk0A6mYyMrRI/edit?ts=56135030#gid=0)

Annotation Categories spreadsheet moved from https://github.com/NRGI/resourcecontracts.org/issues/450#issuecomment-145744048

**Comment by anderspeders** [comment]
OK, the following categories are now mapped: 
Company names
Resources
Contract Types 

in this spreadsheet: Green columns are mapped and ready for import: 
https://docs.google.com/spreadsheets/d/1Ytw6N6AvJCUnTEiCl7TMipP_afpRAgVV6-9lpN9Xc_w/edit?ts=5615fad5#gid=1593729422

I will create a separate ticket for mapping of annotation categories.

**Comment by anjesh** [comment]
There are few contract type that is not present in the codelist. Please see red-highlighted types. https://docs.google.com/spreadsheets/d/1Ytw6N6AvJCUnTEiCl7TMipP_afpRAgVV6-9lpN9Xc_w/edit?ts=5615fad5#gid=748511877

**Comment by anjesh** [comment]
Fixed in admin, need to republish all contracts to reflect in subsite.

**Comment by anjesh** [comment]
Following from https://github.com/NRGI/resourcecontracts.org/issues/506#issuecomment-148533120

I think that happened because the spellings are correct except for the case. As you may see here http://alpha.resourcecontracts.org/resources. They could be corrected directly from the admin. Will correct those. cc @sadhakbj 

![image](https://cloud.githubusercontent.com/assets/120488/10532827/2ad0901e-73e2-11e5-9f82-2a630791ebaa.png)

**Comment by anjesh** [comment]
fixed for resources. 
Please change the contract type for this http://resourcecontracts.elasticbeanstalk.com/contract/871 we don't seem to have mapping for this. And publish it to reflect in subsite.

**Comment by anderspeders** [comment]
Done, closing. Will reopen new ticket if more issues are found.
