### ISSUE TITLE
Create loose link between open corporates and company group

### ISSUE THREAD

**Issue by byndcivilization** [NRGI/resourcecontracts.org#433]
We need to better implement the company grouping data model. Currently it is a free text field. It should piggy back on Open Corporates existing corporate grouping model:
https://opencorporates.com/corporate_groupings/royal%20dutch%20shell
When a user is uplaoding metadata, the admin site should let the user select from a list of existing OC corporate groupings. This can be don via Open Corporates public API.

**Comment by byndcivilization** [comment]
Ideally this can be used to also help get better metadata in relation to company name.

**Comment by anderspeders** [comment]
Same lookup against OC should be enabled for the metadata field "Company name".

**Comment by anjesh** [comment]
Company group is not free text. It shows the list from open corporates. See https://github.com/NRGI/resourcecontracts.org/issues/179#issuecomment-139477406

There is a problem with the OC public API, last time we made 10 calls, then I think we are barred from making further calls on that day. So our script pulls the data once every day (one call allows only 100 rows, so need to make 8 calls to get company-groups close to 800) and serves to the app from our cached OC data.

**Comment by byndcivilization** [comment]
Yeah i sort of thought this was taken care of. @anderspeders do you think we can get Chris to lift the throttle?

**Comment by anjesh** [comment]
Any updates on this?

**Comment by byndcivilization** [comment]
@anderspeders ?

**Comment by charlesyoung** [comment]
@anderspeders is this still required?
