### ISSUE TITLE
Entity extraction to enhance metadata quality

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#435]
For the limited amount of contracts hosted for-profit API services could be considered: 

1) http://saplo.com/api 
2) http://nerd.eurecom.fr/
3) Overview / open calais?

the folowing metadata fields could benefit for suggestions from entity extraction: 
- Company name
- Company address
- Resource
  (- Directors / signatories)

**Comment by charlesyoung** [comment]
@anderspeders is this still required?
