### ISSUE TITLE
Problems adding and editing text in content editing modules (About, FAQs, etc)

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#436]
Hi @anderspeders 

I'm having the following issues re the above: 

1. I added text to the About page, and then clicked the blue tick button to save. This looked like it worked, but when I later logged back in, the text was gone and had reverted to what was there before. 
2.  I can't select text and change the text size, or change the paragraph settings etc. When I click on the relevant editing button, no options show up (e.g. no different text sizes). 

I've tried editing on both a PC and Mac and am having the same issues. 

Many thanks!
Jesse 

cc @KaitlinCCSI @SamCCSI

**Comment by anderspeders** [comment]
@manishgs @anjesh Adding a priority label here, as text editing is important to fix.

**Comment by anjesh** [comment]
@JesseCCSI can you try now? The problem was the button was small and sometimes it tends to miss the click event while saving. We have enlarged the save button now. Reopen this if you still get difficulty saving the content.

**Comment by JesseCCSI** [comment]
Thanks @anjesh - unfortunately I just tried and am having the same problem. I add text, click the blue button, it looks like it saves after that (see second screenshot below), but when I return to the page later the changes have disappeared (third screenshot). 

![screen shot 2015-10-02 at 08 22 13](https://cloud.githubusercontent.com/assets/14910764/10246419/15d55112-68df-11e5-8624-7481c4dfa443.png)
![screen shot 2015-10-02 at 08 22 22](https://cloud.githubusercontent.com/assets/14910764/10246421/15d90cee-68df-11e5-83e7-acb6c43ea62d.png)
![screen shot 2015-10-02 at 08 22 39](https://cloud.githubusercontent.com/assets/14910764/10246420/15d580ce-68df-11e5-9da2-0fe8d343789e.png)
