### ISSUE TITLE
Change photo in top of expandable left column for OLC

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#437]
This is an extractives photo; please swap out with photo of land/ag. Screen shot attached, as well as suggested photo.
![screen shot 2015-10-02 at 6 49 37 am](https://cloud.githubusercontent.com/assets/14825437/10239711/13fc6040-68d2-11e5-9c14-cab00ecff995.png)
![moz photo](https://cloud.githubusercontent.com/assets/14825437/10239713/1d647082-68d2-11e5-9174-d2c49d86020a.jpg)

**Comment by KaitlinCCSI** [comment]
@jesseccsi

**Comment by anjesh** [comment]
You might have to hard-refresh to see the change in image.

**Comment by KaitlinCCSI** [comment]
Thank you!

On Mon, Oct 5, 2015 at 6:46 AM, Anjesh <notifications@github.com> wrote:

> Closed #437 <https://github.com/NRGI/resourcecontracts.org/issues/437>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/437#event-426685060>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=02PpnKtPK&m=f28096059e84&t=20151005&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=02PpnKtPK&m=f28096059e84&t=20151005&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=02PpnKtPK&m=f28096059e84&t=20151005&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>
