### ISSUE TITLE
Google analytics for OLC

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#438]
Has google analytics been set up for the new OLC site? We need to be able to track users from day 1 for funding purposes.

@byndcivilization @anderspeders @KaitlinCCSI

**Comment by byndcivilization** [comment]
@anjesh this is in there right? I think you just need the correct GA code. Has anyone at ccsi set up the GA acct?

**Comment by anjesh** [comment]
Yes it's in place https://github.com/NRGI/resourcecontracts.org/issues/176
I have just shared with Chris with admin privilege, couldn't add yours. Need google account to add the users.

**Comment by SamCCSI** [comment]
Thanks @byndcivilization - can you please add my google account to this as an admin, so I can add Kaitlin and Jesse: samszokeburke@gmail.com

And thanks @anjesh for already having it in place!

**Comment by byndcivilization** [comment]
done

**Comment by SamCCSI** [comment]
Thanks everyone, GA is working for me and I've added other CCSI users to
the account.

On Fri, Oct 2, 2015 at 7:28 PM, Chris Perry <notifications@github.com>
wrote:

> done
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/438#issuecomment-145092403>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by anjesh** [comment]
Resolved through email comms.
