### ISSUE TITLE
Pre-launch landing page for OLC

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#439]
Can we please place a landing page on openlandcontracts.org that has the same background photo as the new site's home page and says the following (centered text):

Open Land Contracts

A New Global Repository of Large-Scale Land, Agriculture and Forestry Contracts

Site Launching October 7, 2015

Attend the launch of OpenLandContracts.org in New York [Hyperlink this line with the following: http://ccsi.columbia.edu/2015/10/07/openlandcontracts-org-launch/]

cc @KaitlinCCSI

**Comment by anderspeders** [comment]
@SamCCSI I will check with @anjesh about the time requirements for this as we have not initially  planned this for the pre-launch sprint.

**Comment by anderspeders** [comment]
@SamCCSI With several other pending tickets there will not be time to do this. Closing this ticket.
