### ISSUE TITLE
For RC: Add: "Become a contract publisher" as an additional page

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#440]
1-2 page of text about how a gov agency or an EITI office can become a contract publisher using RC.org.

**Comment by charlesyoung** [comment]
Sure, can I get to you at the end of next week? Lot's going on with Philippines and I still need to work on the Pretoria workshop report and way forward. I'm going to note this in my report because it was raised at the workshop; must it be a Gov or EITI agency or can it also be a NGO who can become a contract publisher?

**Comment by KaitlinCCSI** [comment]
Can we have that page for OLC too? We'll create the text soon; would be
great if we could have it before launch date if possible? If not, we'll
update whenever page is available.


On Friday, October 2, 2015, Charles Young <notifications@github.com> wrote:

> Sure, can I get to you at the end of next week? Lot's going on with
> Philippines and I still need to work on the Pretoria workshop report and
> way forward. I'm going to note this in my report because it was raised at
> the workshop; must it be a Gov or EITI agency or can it also be a NGO who
> can become a contract publisher?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/440#issuecomment-144987656>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PoaDk7i&m=d50f8981a8d8&t=20151002&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PoaDk7i&m=d50f8981a8d8&t=20151002&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01PoaDk7i&m=d50f8981a8d8&t=20151002&c=f>
>


-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by KaitlinCCSI** [comment]
Is this page available for us to populate now? Don't see it on the backend, and don't think we have the ability to create pages ourselves?

**Comment by anjesh** [comment]
You can't create these pages from the backend. The frontend sites are independent from the backend system. We will create the page and you will be able to edit just like any other pages.

Is this page going to linked at the bottom besides the existing links? is "Become a contract publisher" the page title?

**Comment by charlesyoung** [comment]
Just want to make sure what type of doc is required @KaitlinCCSI @anderspeders. Take a look at the country implementation doc that I'm working on (especially sections 1 - 3) and let me know if this is what you are looking for. If not then please elaborate on the details. Tx

https://docs.google.com/document/d/1V2u1_Q3Y9bJ7eDJwZsqskb5ZgLN06RHXJYyUF89PekA/edit?usp=sharing

**Comment by KaitlinCCSI** [comment]
@anjesh Can you call the page "Publish Contracts", and make it appear in between "Glossary" and "Contact"?

@charlesyoung I'm not sure what Anders wants for RC. For OLC we are going to use something much shorter. Will hopefully be on site soon so you can take a look.

**Comment by KaitlinCCSI** [comment]
@anjesh Can you let us know when this page is created so that we can add content to it? Thanks! 

cc @jesseccsi

**Comment by anjesh** [comment]
@jesseccsi http://www.openlandcontracts.org/publish-contracts created
