### ISSUE TITLE
Contract disclosure overview page

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#441]
Create an easy overview country by country on how contract disclosure - by government or by companies.

Example: 
https://docs.google.com/spreadsheets/d/1qu_UkuDY3XiQfh1Mjlq1HOVToErlEcPqHqaCeKw8zAQ/edit#gid=0

**Comment by jedm** [comment]
This is a fantastic idea! Would advise this page -- and other new pages -- be considered in the context of a plan to create real Navigation UX. Footer is already getting crowded. :)

**Comment by upasna01** [comment]
Disclosure mode is included in menu, please preview changes and provide your feedback.
![441](https://cloud.githubusercontent.com/assets/11477899/17056869/2a1353a6-5036-11e6-951e-603b2a2443d3.png)

**Comment by manishgs** [comment]
@anderspeders @jedm Please review the page and let us know your feedback.
