### ISSUE TITLE
Problems adding and editing text - ongoing (related to issue #436)

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#442]
Thanks @anjesh - unfortunately I just tried and am having the same problem (#436). I add text, click the blue button, it looks like it saves after that (see second screenshot below), but when I return to the page later the changes have disappeared (third screenshot). I also still can't edit the format of the text (change size, change paragraph format, etc.). 

![screen shot 2015-10-02 at 08 22 13](https://cloud.githubusercontent.com/assets/14910764/10246419/15d55112-68df-11e5-8624-7481c4dfa443.png)
![screen shot 2015-10-02 at 08 22 22](https://cloud.githubusercontent.com/assets/14910764/10246421/15d90cee-68df-11e5-83e7-acb6c43ea62d.png)
![screen shot 2015-10-02 at 08 22 39](https://cloud.githubusercontent.com/assets/14910764/10246420/15d580ce-68df-11e5-9da2-0fe8d343789e.png)

**Comment by JesseCCSI** [comment]
Looks like I can save text on the FAQ page, but not on the About or Contact Us pages. The formatting problem remains on all three pages. 

@anjesh

**Comment by anjesh** [comment]
Yes i just realized that as well. About page was getting saved into contact page. Made temporary fix. You should be able to save now

**Comment by JesseCCSI** [comment]
Many thanks @anjesh - do you think the text formatting issues might be resolved today?

**Comment by anjesh** [comment]
Text-formatting enabled now. Please check.

**Comment by JesseCCSI** [comment]
Many thanks @anjesh this is working now
