### ISSUE TITLE
Auto-scrolling of annotations bar sometimes a bit off

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#443]
cc @KaitlinCCSI @jesseccsi

When I am looking at annotations:
![screen shot 2015-10-02 at 4 36 19 pm](https://cloud.githubusercontent.com/assets/12913915/10249114/db8fad5a-6923-11e5-895b-93b2f33d7124.png)

And I want to click on, eg. "Cancellation or termination", it takes the PDF to the correct spot, but the left column scrolls too far down, cutting off the first half of the annotation:
![screen shot 2015-10-02 at 4 36 26 pm](https://cloud.githubusercontent.com/assets/12913915/10249170/2576fb08-6924-11e5-8cba-b3a3daa1c03a.png)

So I then have to manually scroll up on the left side to discover the first half of the annotation for "Cancellation or termination"
![screen shot 2015-10-02 at 4 36 33 pm](https://cloud.githubusercontent.com/assets/12913915/10249187/3fee876c-6924-11e5-9493-e49256e79774.png)

**Comment by anjesh** [comment]
It was due to the auto-expansion and shortening of the annotation-text when that particular annotation is clicked. That off position happened because one of the longer text is now shortened, taking the lower annotations to the top during render. Will try to see the fix.

**Comment by SamCCSI** [comment]
Any updates on this one? Still experiencing this occasionally.
Thanks,
Sam

**Comment by sadhakbj** [comment]
It's fixed now:

![iiuse443-annotatin-scrolling fixed](https://cloud.githubusercontent.com/assets/5828622/13067742/ed04edd2-d49b-11e5-9b25-bb20699724a1.png)
