### ISSUE TITLE
Annotation category incorrect

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#444]
http://resourcecontracts.elasticbeanstalk.com/mturk/108

Annotation listed as "Other"; should be listed as "Other - financial/fiscal", as set out in row 90 of the excel file: https://www.dropbox.com/s/gkszrat9ior882b/Salala_Liberia.xlsx?dl=0

![screen shot 2015-10-02 at 4 42 37 pm](https://cloud.githubusercontent.com/assets/12913915/10249319/f652aeac-6924-11e5-9152-0aa29c821511.png)

**Comment by anjesh** [comment]
Fixed for 108.

**Comment by SamCCSI** [comment]
Another annotation is still nestled under "Other". This should be re-assigned to "Other - operational".

Apologies for not pointing this out last time.

![screen shot 2015-10-06 at 8 36 00 am](https://cloud.githubusercontent.com/assets/12913915/10308662/5a893818-6c05-11e5-82eb-a54f0bb29a3e.png)

**Comment by SamCCSI** [comment]
(same contract)

**Comment by anjesh** [comment]
Got it.
 cc @mojbenzcar

**Comment by anjesh** [comment]
Fixed this particular annotation.
