### ISSUE TITLE
Adding media (other than jpeg images) to posts 

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#445]
Hi @anderspeders , 

I'm trying to include an option for users to download a PDF and Excel file (our Guidance Note for annotating contracts and Excel Annotation Template) from the FAQ page. While there is an 'add image' option, I don't see an option to add other forms of media. I'd like to include them in a similar format to resourcecontracts.org (screenshot below). 

Many thanks in advance for your help.
cc @KaitlinCCSI @SamCCSI

![screen shot 2015-10-02 at 12 43 25](https://cloud.githubusercontent.com/assets/14910764/10252151/a32254e2-6903-11e5-9b44-97e616ffacde.png)

**Comment by KaitlinCCSI** [comment]
Will this and text editing (issue #442 - ability to format, etc) be resolved before OLC launch? Both are important for how the site is perceived at launch, and we have been noting that the site will provide guides to contracts, etc, so our ability to upload these guides is important. 

@anjesh

**Comment by KaitlinCCSI** [comment]
Ideally we would also be able to have anchor tags on these pages. Is this possible?

**Comment by anderspeders** [comment]
@anjesh Could you confirm what our options are here with regards to links from the content pages?

**Comment by KaitlinCCSI** [comment]
Being able to upload documents is a high priority before OLC launch, as we have Guidance Documents for understanding contracts that are meant to be on the site. Please confirm whether we can do this.

**Comment by anjesh** [comment]
Guidance and other documents that are to be linked with the page should be in Amazon s3 like our existing contracts, or it could be in some other external servers (like dropbox). 
For now putting these documents in dropbox and providing the direct download link to dropbox would be quick option.

**Comment by anderspeders** [comment]
@KaitlinCCSI: Am I correct that this has been fixed for now with links to the relevant PDF-documents?

If that is the case we can close this.

**Comment by KaitlinCCSI** [comment]
Yes, we have uploaded using Amazon s3 link. Not sure if that's a long term
solution or not (?), but can close this ticket.

On Wed, Oct 7, 2015 at 5:47 AM, Anders <notifications@github.com> wrote:

> @KaitlinCCSI <https://github.com/KaitlinCCSI>: Am I correct that this has
> been fixed for now with links to the relevant PDF-documents?
>
> If that is the case we can close this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/445#issuecomment-146153633>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PqaLNQT&m=14e911074ea4&t=20151007&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PqaLNQT&m=14e911074ea4&t=20151007&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01PqaLNQT&m=14e911074ea4&t=20151007&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>
