### ISSUE TITLE
Annexes missing from copy & Pages missing from copy shouldn't be in annotations category dropdown

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#449]
Per discussions from earlier around mapping, "Annexes missing from copy" and "Pages missing from copy" should ideally be metadata rather than annotations category, and at the very least should not show up in the Annotations Category dropdown menu.
![screen shot 2015-10-03 at 12 00 22 pm](https://cloud.githubusercontent.com/assets/14825437/10264011/bc503574-69c6-11e5-99d7-19f67460186b.png)
![screen shot 2015-10-03 at 12 03 39 pm](https://cloud.githubusercontent.com/assets/14825437/10264015/d5b3e0f6-69c6-11e5-8944-5170806a18b8.png)

cc @anderspeders

**Comment by anjesh** [comment]
Are now removed from the dropdown.
