### ISSUE TITLE
Comparison of contract and sharing of results

### ISSUE THREAD

**Issue by jedm** [NRGI/resourcecontracts.org#45]
As a user, I want to select individual contracts or clauses within contracts and display them for comparison on the screen in real time, so that I can read multiple contracts or clauses alongside each other and make effective comparisons. 

These contracts or clause comparisons should also be possible to store for later in a temporary file or as a smart URL, and to save or export to excel or PDF as a report.

**Comment by anderspeders** [comment]
![contract comparison](https://cloud.githubusercontent.com/assets/1101585/8185086/0f7e0710-1410-11e5-8bc6-99f6c2d654dc.png)

@jedm @byndcivilization Any thoughts of this outline for the key contract-to-contract comparison UI?

**Comment by byndcivilization** [comment]
UI feedback: It would be nice if the comparison text was highlighted in some way. Could be as simple as a css transition to grey out non-clause text.

**Comment by jedm** [comment]
Few questions on this feature:

- For each contract and clause, Title and key metadata (eg, Country, Year of Sig, location of clause) should display over/next to each item, not just tags
- There should also be clicks available back to the source contract and back to individual location in the PDF
- How many contracts and/or clauses can be included in the capture (I assume unlimited)?
- How many contracts and/or clauses can be displayed in a single stream (should be more than 2 -- probably minimum 4 in a single screen, then a pagination or "scroll" feature)

Lower priority, but features would presumably include Save Comparison, Share Comparison, Print, etc., so the UI would need to account for those, along with the minimum-per-screen mentioned above.

**Comment by anderspeders** [comment]
Thanks Jed, 

Some of this should possibly be broken into specific tasks. All good ideas.

**Comment by anderspeders** [comment]
Based on sprint call today I am adding this to sprint 3.

**Comment by anderspeders** [comment]
Review examples from the Constitute project: 
https://www.constituteproject.org/search?lang=en&compare=Afghanistan_2004&compare=Albania_2012

**Comment by anjesh** [comment]
This issue also talks about pinning - which is covered in #70 

We will have 2 contracts comparison feature in this issue - pinning could also be part of this, but pinning will be covered for individual contract only for now. 

Only two contracts could be compared at a time. There will be option to select two contracts based on the search results. 

![image](https://cloud.githubusercontent.com/assets/120488/8450716/20a6a490-1ffd-11e5-9c09-6981d6bbd44a.png)

User can click Annotation button to see the annotations for that particular contract.

![image](https://cloud.githubusercontent.com/assets/120488/8450724/2e43a2c4-1ffd-11e5-8f58-f16151fc2c0a.png)

Similarly user can click metadata to see the metadata for that contract.

![image](https://cloud.githubusercontent.com/assets/120488/8450729/3ac3f47c-1ffd-11e5-80b2-3a67b46411f0.png)

User may also do the search, which searches in both the contracts and shows results accordingly.

![image](https://cloud.githubusercontent.com/assets/120488/8450736/4a595e9a-1ffd-11e5-98ea-81a4f71b05ed.png)

The results for both the contracts will be listed. User may click on the link to go to the specific page of those contracts. 
![image](https://cloud.githubusercontent.com/assets/120488/8450739/4d6b87f2-1ffd-11e5-8248-b4e0c6cb1b13.png)

**Comment by anderspeders** [comment]
Looks good. Please go ahead!

**Comment by jedm** [comment]
A huge step to have this option! Given the expectations about comparisons, it will be important to create prose and wireframe specs for comparisons that offer flexibility above 1-to-1 comparisons and offer shareability (pinning), and then to issue a timeline for those expected features.

**Comment by byndcivilization** [comment]
This was brought up again today in review. Specifically on the ability to share a link of contract to contract comparison for portability.

**Comment by anjesh** [comment]
The basic comparison is in place in the subsite where the users can do the search, browse through pages, see metadata, annotations for two contracts at a time. A new issue will be created to improve the comparison feature #117. All improvement discussions in new issue.
