### ISSUE TITLE
Incorrect mapping of annotations to "other" category

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#450]
See Liberia Tree & Trading Company (http://alpha.openlandcontracts.org/contract/1173/view) as an example of a number of important annotations that have been grouped under "Other" instead of allocated to proper category. If we note all of these following OLC launch, can they be fixed during Sprint 10? In the meantime, is it possible to at least fix this contract?

Sorting out how to fix annotations mapped to incorrect fields is very important for making the site credible and useful.

![screen shot 2015-10-03 at 12 12 41 pm](https://cloud.githubusercontent.com/assets/14825437/10264136/59fd8798-69c9-11e5-8a3b-d5d7a7328190.png)

cc @anderspeders @jedm @samccsi

**Comment by SamCCSI** [comment]
sam issue as https://github.com/NRGI/resourcecontracts.org/issues/444

**Comment by SamCCSI** [comment]
*same

**Comment by KaitlinCCSI** [comment]
Sorry, my third arrow should have said "Sacred, cultural, or historical sites" rather than "Environmental protections".  

Note that I just checked the original excel sheet that CCSI provided and the information was correctly mapped in our spreadsheet, so I don't know why these are appearing under "Other."

**Comment by anjesh** [comment]
When we first migrated the annotations, every mis-matched category goes to "other" and some were missed after mapping was done. We have fixed those mis-matched now. Please verify.

**Comment by SamCCSI** [comment]
THose changes look good on this document, thanks @anjesh 

I found two other problems though:

1. This contract's OCR text is very low quality and so it needs to be removed from public view. I changed the "show PDF text" field to "no", and now it says the Metadata is in draft form but the text is still published. And I can't see how to submit this contract to mechanical turk.

![image](https://cloud.githubusercontent.com/assets/12913915/10280121/c915d962-6b38-11e5-9017-da3351d0be66.png)


2. 27 other contracts show up when I do a search for the "Other" annotation category. Presumably these all need to be fixed in Sprint 10: 
http://rc-site-stage.elasticbeanstalk.com/olc/public/search?q=&annotation_category%5B%5D=Other


@KaitlinCCSI

**Comment by KaitlinCCSI** [comment]
Hi @anjesh - do you need us to provide more information to fix the "Other" mapping in the 27 contracts that Sam identified? If so, please let us know what information you need.

**Comment by anjesh** [comment]
> "This contract's OCR text is very low quality and so it needs to be removed from public view. I changed the "show PDF text" field to "no", and now it says the Metadata is in draft form but the text is still published. And I can't see how to submit this contract to mechanical turk."

"Show PDF Text" is part of the metadata, so any change in metadata requires re-publishing of metadata to be reflected in the subsite, then text will not appear. To submit to MTurk, you have to choose "Text Type" to "Need Full transcription".

I understand that the options that are being added have created some confusion, but to ease the process of publishing/unpublishing contracts and its components, we have added these options as we felt necessary in line with the past few weeks issues. We need to revisit these options and make it easy to follow. 

@KaitlinCCSI there are still number of non-matched category that are placed in "Other". We will go through the list once more and share with you. There are mis-matched categories from RC as well, when we went through the entire database - both RC and OLC.

**Comment by SamCCSI** [comment]
Re: display of OCR text: Thanks Anjesh. I understand now and have made it so text is not public but everything else is.

**Comment by KaitlinCCSI** [comment]
Okay, thanks @anjesh. We'll take a look at the list once it's available.

On Mon, Oct 5, 2015 at 9:26 AM, Anjesh <notifications@github.com> wrote:

> "This contract's OCR text is very low quality and so it needs to be
> removed from public view. I changed the "show PDF text" field to "no", and
> now it says the Metadata is in draft form but the text is still published.
> And I can't see how to submit this contract to mechanical turk."
>
> "Show PDF Text" is part of the metadata, so any change in metadata
> requires re-publishing of metadata to be reflected in the subsite, then
> text will not appear. To submit to MTurk, you have to choose "Text Type" to
> "Need Full transcription".
>
> I understand that the options that are being added have created some
> confusion, but to ease the process of publishing/unpublishing contracts and
> its components, we have added these options as we felt necessary in line
> with the past few weeks issues. We need to revisit these options and make
> it easy to follow.
>
> @KaitlinCCSI <https://github.com/KaitlinCCSI> there are still number of
> non-matched category that are placed in "Other". We will go through the
> list once more and share with you. There are mis-matched categories from RC
> as well, when we went through the entire database - both RC and OLC.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/450#issuecomment-145545592>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01Ppqqg2L&m=9b6e83a72665&t=20151005&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01Ppqqg2L&m=9b6e83a72665&t=20151005&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01Ppqqg2L&m=9b6e83a72665&t=20151005&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by anjesh** [comment]
We have found the following categories which are tagged as "Other" in the database. I think most of the these are migrated from RC as well. We might have missed few misses from the mapping you have done. Sometimes it gets hard to keep up with the changes. I hope once this is fixed, we shouldn't have any mis-mapped category appearing in the site. 

https://docs.google.com/spreadsheets/d/1CQJsDOXoSKnv3abSDfFA-J6r_Tmn2Nxzk0A6mYyMrRI/edit?ts=56135030#gid=0

**Comment by KaitlinCCSI** [comment]
Okay, do you need us to map this list to the code list?

And are you sure that these are the only things mapping to "Other"? In the
example with the screenshot that I gave at the start of this ticket, the
annotation content for correct annotation fields (ie ones that are included
in code list) had been placed in the "Other" category, so the issue wasn't
that the annotation fields in the excel sheet were missing from the code
list, it was that annotation content for fields in the code list was being
mapped to "Other" mistakenly. These annotation fields that you've put in
the document are not in the code list (they are almost all "other"
categories that annotators added months or years before we realized we
needed to standardize), so I understand why they need to be mapped, but
this seems to be a different issue from the poor mapping in the example at
the top of this ticket.

On Tue, Oct 6, 2015 at 12:18 AM, Anjesh <notifications@github.com> wrote:

> We have found the following categories which are tagged as "Other" in the
> database. I think most of the these are migrated from RC as well. We might
> have missed few misses from the mapping you have done. Sometimes it gets
> hard to keep up with the changes. I hope once this is fixed, we shouldn't
> have any mis-mapped category appearing in the site.
>
>
> https://docs.google.com/spreadsheets/d/1CQJsDOXoSKnv3abSDfFA-J6r_Tmn2Nxzk0A6mYyMrRI/edit?ts=56135030#gid=0
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/450#issuecomment-145744048>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PpFhVb5&m=8eecf77eda7b&t=20151006&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PpFhVb5&m=8eecf77eda7b&t=20151006&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01PpFhVb5&m=8eecf77eda7b&t=20151006&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by anjesh** [comment]
Yes these are the only remainings. Once mapped and fixed, should solve all the possible mis-mapped other category issues.

**Comment by anjesh** [comment]
Will be handling this in data cleanup for RC https://github.com/NRGI/resourcecontracts.org/issues/432#issuecomment-146490346
