### ISSUE TITLE
Resource dropdown on OLC needs to be fixed

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#451]
Dropdown seems to be alphabetized except for "Rice products", which appears first on the list, but should instead appear under "Rice".
![screen shot 2015-10-03 at 8 19 48 pm](https://cloud.githubusercontent.com/assets/14825437/10265979/6879b7cc-6a0c-11e5-8611-302b2c08e5d0.png)

**Comment by KaitlinCCSI** [comment]
In addition, "Other crops" and "other crops" should be merged.
![screen shot 2015-10-03 at 8 22 58 pm](https://cloud.githubusercontent.com/assets/14825437/10265989/b110a19e-6a0c-11e5-8495-2ab1c872cfd4.png)

**Comment by anjesh** [comment]
Fixed. Was due to space inserted before "Rice Products" when inserted as free text. Will also ensure that the spaces are trimmed while saving the contract metadata.
