### ISSUE TITLE
PDF contract is zoomed in so much that it looks like a blank page

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#452]
PDF for this contract is zoomed in too much, so when you load the page it just looks like a blank screen.
http://alpha.openlandcontracts.org/contract/1179/view

What it looks like when you open page:
![screen shot 2015-10-04 at 8 43 06 am](https://cloud.githubusercontent.com/assets/14825437/10268121/5dbbc9fc-6a74-11e5-8127-2f4aa1dd5fcf.png)

What it looks like when you scroll to the side, which is not intuitive at all:
![screen shot 2015-10-04 at 8 45 11 am](https://cloud.githubusercontent.com/assets/14825437/10268122/64719d12-6a74-11e5-9110-e1a1bbbbd6b4.png)

**Comment by anjesh** [comment]
Fixed scaling for the pdf whose pages are larger than the normal pdfs. 
http://alpha.openlandcontracts.org/contract/1179/view
