### ISSUE TITLE
"Name of company executing document" repeats in annotations sidebar

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#453]
I just opened up 5 contracts to check; 3 out of 5 have the name repeating:
http://alpha.openlandcontracts.org/contract/683/view
http://alpha.openlandcontracts.org/contract/1034/view
http://alpha.openlandcontracts.org/contract/1179/view

Assume that many other annotations have this issue as well. Do we need to go through every single contract to note which ones have this problem?

See examples in screenshots:

![screen shot 2015-10-04 at 8 48 01 am](https://cloud.githubusercontent.com/assets/14825437/10268148/52446ce0-6a75-11e5-9304-43d2658b3bb4.png)
![screen shot 2015-10-04 at 8 53 49 am](https://cloud.githubusercontent.com/assets/14825437/10268165/f285bfc4-6a75-11e5-9391-9e8f5a493a5f.png)

**Comment by anderspeders** [comment]
Hi @KaitlinCCSI, the text you are requesting to be removed is "annotation content" not actual annotation categories. This means that these as text pices are very difficult to remove aotumatically from the display. They would need manual removal. YI is working on enabling the editing module on the backend so that you can make these edits in the annotation content.  

In the effort of providing a clear guidance of the various types of content we have within the annotations I have drafted this section within the Administrator guide: 

https://docs.google.com/document/d/1lawSuSak4sAHitaCtbPs3nhNEM5aR20tdMMj_c_JKtk/edit#heading=h.376nkf33g226

Please have a look and add.

**Comment by KaitlinCCSI** [comment]
I assume this is the same or a similar problem to the one we had with
annotation content being repeated on the summary page, which was not due to
errors from CCSI but to the fact that some annotations list more than one
page reference.

I don't know what you want me to do with the guide - these repeats are not
errors on our part, but errors introduced through the uploading process.

Enabling the editing module on the backend should be of the highest
priority in sprint 10 if there is otherwise no way to fix the multiple
problems with annotations that we have found that were introduced during
the uploads.

On Sun, Oct 4, 2015 at 4:23 PM, Anders <notifications@github.com> wrote:

> Hi @KaitlinCCSI <https://github.com/KaitlinCCSI>, the text you are
> requesting to be removed is "annotation content" not actual annotation
> categories. This means that these as text pices are very difficult to
> remove aotumatically from the display. They would need manual removal. YI
> is working on enabling the editing module on the backend so that you can
> make these edits in the annotation content.
>
> In the effort of providing a clear guidance of the various types of
> content we have within the annotations I have drafted this section within
> the Administrator guide:
>
>
> https://docs.google.com/document/d/1lawSuSak4sAHitaCtbPs3nhNEM5aR20tdMMj_c_JKtk/edit#heading=h.376nkf33g226
>
> Please have a look and add.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/453#issuecomment-145353965>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01Pp2nDsT&m=ca0b117dd310&t=20151004&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01Pp2nDsT&m=ca0b117dd310&t=20151004&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01Pp2nDsT&m=ca0b117dd310&t=20151004&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by anderspeders** [comment]
Annotation content is added in the left bar and given that the company names are leaded as content not metadata it will display in the left column. 

As for the guide: I expect that CCSI supports maintaining and updating the guide as we add features and document data entry practises.   
 
I agree that this important. I however also need to note that sprint 10 will have as core priority to *make RC.org launch ready*. This will include a lot of the data cleaning exercises which have already been done for OLC. Ideally we have time to prioritize this ticket as well.

**Comment by KaitlinCCSI** [comment]
Yes, I understand that it is annotation content. I meant that I thought it was the same problem, or a related problem, to the repeated annotation content that we see on the summary page, for which I thought we had agreed on a solution, and which I logged again here (https://github.com/NRGI/resourcecontracts.org/issues/457) when I realized that this problem has not yet been fixed and annotation content is still repeating.

For the guide - we are happy to help update the guide, but I simply don't understand what you want me to add here. This doesn't seem to be an error related to data entry, so what would you like me to say?

Of course data cleaning exercises for RC should take precedent for sprint 10. I very much hope that this can be prioritized over other things, however, since this affects the presentability of both OLC and RC. If we want RC to be a useful and credible resource, then our ability to go in and fix errors is paramount.

**Comment by anderspeders** [comment]
Fully agree that we want the backend to enable these types of fixes and that we should prioritize this in sprint 10.

**Comment by anjesh** [comment]
This will be fixed when we have annotation linking to multiple pages (https://github.com/NRGI/resourcecontracts.org/issues/694) is completed. And we will need to do manual fixing of these annotations and select the proper parent annotation.
