### ISSUE TITLE
Navigation buttons not intuitive: Back arrow button in left corner not intuitive, and it's also missing on summary page

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#454]
ON THE CONTRACT VIEW PAGE: I had assumed the back arrow button in the top left corner was a "back" button that would take you to the previous page you were on, but instead it takes you to the home page. This does not seem intuitive to me. It means that after you do a search on the advanced search page and click on a contract to view it, if you want to go back to the advanced search page to see your other results, there is no way to do so internally from the site (you could only use your browser buttons to do this).

A more intuitive approach would be to have the back arrow go to the previous page, and then to have the name of the site included on every page in the top left corner (like it is on the advanced search page), which would be hyperlinked to the home page (and which I have suggested previously).

ON THE SUMMARY PAGE: There is no back arrow at all, just the site name hyperlinked to the home page, and then a hyperlinked "trail" (I don't know the technical term") that shows hyperlinks to go to the home page or the contracts page). This means that there is no way internally to go back to the contract view page from the summary page (you could only use your browser buttons to do this).

cc @jedm 

Contract view page example:
![screen shot 2015-10-04 at 8 54 32 am](https://cloud.githubusercontent.com/assets/14825437/10268176/575c4080-6a76-11e5-8236-501f8522c27f.png)

Summary page example:
![screen shot 2015-10-04 at 9 03 02 am](https://cloud.githubusercontent.com/assets/14825437/10268211/5da0f322-6a77-11e5-99f1-6906a3f82901.png)

**Comment by anderspeders** [comment]
Thanks Kaitlin, 

Summarising: 
- Fix back button on Contract page 
- Add back button on Summary page that will take you to Contract page. (Here we already have Document view button - but agree that a back button would likely be intuitive to have as well)

**Comment by jedm** [comment]
Similar issues exist in other paths. If I [search "bauxite Africa"](http://alpha.resourcecontracts.org/search?q=bauxite+africa&country%5B%5D=gn) for instance, I get 93 results, but if I click and go to [one of the listed Contracts](http://alpha.resourcecontracts.org/contract/928/view), there is no way to return to my results list. Plus, as Kaitlin noted, the icon in upper left (an arrow, which is traditionally used as an icon for "Back") sends me to the Home page.

In a single contract, if use the "More" docs list [in lower right](http://alpha.resourcecontracts.org/contract/917/view) to click on [a list of all bauxite](http://alpha.resourcecontracts.org/resource/Bauxite) or all Guinea contracts, there is no way to get back to the specific contract I was just in.

So, as noted [in an older comment in Issue 326](https://github.com/NRGI/resourcecontracts.org/issues/326#issuecomment-142983594), the fix needs to be something that sets functionality and visual rules for "Back" that are consistent across site (so they can be more predictable for users) and use intuitive icons.

**Comment by anjesh** [comment]
Back link enabled for both contract view and contract summary page. In contract summary page, "View Document" link changes to "Back to Document" when clicked from contract view page.

**Comment by SamCCSI** [comment]
One additional point in Kaitlin's original post on this issue that was not summarized in Anders' bullet points:
"have the name of the site included on every page in the top left corner (like it is on the advanced search page), which would be hyperlinked to the home page (and which I have suggested previously)"

This would mean having the OLC button (below) on top left corner somewhere, and having it hyperlinked to home page:

![image](https://cloud.githubusercontent.com/assets/12913915/10308562/7eb3a83c-6c04-11e5-9d74-cee00d0970bf.png)

cc @KaitlinCCSI @jedm

**Comment by anjesh** [comment]
The space is expensive in this view and esp in that top bar. We will see how it could fit there without hurting the available space. 
cc @sweetanzell @anjhero

**Comment by anjesh** [comment]
Added home link

![image](https://cloud.githubusercontent.com/assets/120488/10331980/74607180-6cf9-11e5-8ee7-cbc771328c2c.png)

**Comment by KaitlinCCSI** [comment]
Thanks. I think it might be useful for summary page to have the same back button in same place as other page (rather than a "Back to document" button on right side). Can we address in sprint 10?

**Comment by anjesh** [comment]
Moving to 10 for this fix.

**Comment by anjesh** [comment]
Back button in place in summary page.
![image](https://cloud.githubusercontent.com/assets/120488/10533371/f9c60eee-73e7-11e5-9d7a-a0b6a8af6309.png)
