### ISSUE TITLE
extra space between government entities and separating commas

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#455]
On Summary page, there is an extra space between the names of government entities and the commas separating the names - there should not be a space between the name and the following comma, only a space between a comma and the subsequent name.

For example, it should be "Ministry of Agriculture, Ministry of Finance, National Investment Commission"  and not "Ministry of Agriculture , Ministry of Finance , National Investment Commission"

Examples:
![screen shot 2015-10-04 at 9 12 43 am](https://cloud.githubusercontent.com/assets/14825437/10268264/9bb9ff2c-6a78-11e5-9742-10aab47bbfde.png)
![screen shot 2015-10-04 at 9 14 25 am](https://cloud.githubusercontent.com/assets/14825437/10268265/9ffb3d26-6a78-11e5-915d-3e88f52fb5fb.png)

**Comment by anderspeders** [comment]
Good catch @KaitlinCCSI 

@anjesh It seems that with correct data entry of *multiple government entities* the display on the summary page will need correction.

**Comment by anjesh** [comment]
Removed comma and enabled bullets for the government entities.

![image](https://cloud.githubusercontent.com/assets/120488/10304541/9155e3d4-6c3a-11e5-85e6-830b40bb6cdf.png)
