### ISSUE TITLE
When there are 0 documents returned, should say "0 Contracts"

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#456]
When there are 0 documents returned, should say "0 Contracts" and not "0 Contract"
![screen shot 2015-10-04 at 6 10 02 pm](https://cloud.githubusercontent.com/assets/14825437/10270806/4fde2d62-6ac3-11e5-9504-b780fc225c9b.png)

**Comment by anjesh** [comment]
Fixed the wording.
