### ISSUE TITLE
Repeated annotations on summary page

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#457]
There are still repeated annotations on the summary pages. I thought we had developed a fix for this? See screenshot example pulled from http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/1046#annotations
![screen shot 2015-10-04 at 8 19 03 pm](https://cloud.githubusercontent.com/assets/14825437/10271463/41a495da-6ad5-11e5-9edf-ee9bb32a0ba2.png)

cc @anderspeders @jedm @samccsi

**Comment by anjesh** [comment]
This is how it appears now http://alpha.openlandcontracts.org/contract/1046

![image](https://cloud.githubusercontent.com/assets/120488/10299509/9ff93e52-6c0a-11e5-9e43-5f2940821c61.png)

**Comment by KaitlinCCSI** [comment]
Great, thanks. This was fixed for all contracts, right, and not just this
specific contract?

On Mon, Oct 5, 2015 at 10:29 PM, Anjesh <notifications@github.com> wrote:

> This is how it appears now
> http://alpha.openlandcontracts.org/contract/1046
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/120488/10299509/9ff93e52-6c0a-11e5-9e43-5f2940821c61.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/457#issuecomment-145732286>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PpDtC0N&m=e4cbe307a1ee&t=20151005&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PpDtC0N&m=e4cbe307a1ee&t=20151005&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01PpDtC0N&m=e4cbe307a1ee&t=20151005&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by anjesh** [comment]
Yes.
