### ISSUE TITLE
Philippines subsite

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#459]
@jerico I know the subsite is a work in progress but below are two points to note. The inclusion of a % sign in the search results and the alignment of the metadata. 

![image](https://cloud.githubusercontent.com/assets/13888372/10279446/16b8550a-6b66-11e5-954f-7293f04dc7bc.png)

**Comment by anderspeders** [comment]
@byndcivilization @jerico Would it make sense to have a repo for handling PH-EITI country site issue tickets? Or do we already have this?

**Comment by anjesh** [comment]
Yes i think it would be better to have separate repo for PH-EITI to avoid confusion with the issues we have here.

**Comment by jerico** [comment]
Hi @anjesh @anderspeders @charlesyoung 

I created a repo for PH-EITI codebase: https://github.com/jerico/ph-eiti-contracts-portal

I'll this issue there and address it. Thanks!
