### ISSUE TITLE
Date of signature displayed on search page different from metadata and annotations

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#460]
The first two contracts are listed with incorrect dates, yet when I check the back-end, their metadata and annotations list the correct signature dates and years.

![screen shot 2015-10-05 at 7 53 48 am](https://cloud.githubusercontent.com/assets/12913915/10279809/a230c944-6b36-11e5-91b4-68b0e9a9c314.png)

Metadata displays incorrectly on live site 
![screen shot 2015-10-05 at 7 57 04 am](https://cloud.githubusercontent.com/assets/12913915/10279858/f6b6c946-6b36-11e5-8424-67d82b44408a.png)

But it is entered correctly on the metadata back end:

![screen shot 2015-10-05 at 7 57 30 am](https://cloud.githubusercontent.com/assets/12913915/10279855/f1b41886-6b36-11e5-87fa-21bd0a3f6069.png)
cc @KaitlinCCSI

**Comment by anderspeders** [comment]
Hi @SamCCSI, @KaitlinCCSI, 

This is a format issue. Even if you type in the year "2009", the platform will not read it until you provide a fully standardized date field: YYYY-MM-DD (I don't know why - and agree this is unfortunate) 

I have now changed the date to: 2009-01-01 and the display has changed on the front end. 

![image](https://cloud.githubusercontent.com/assets/1101585/10281643/e92b235a-6b43-11e5-8b9e-cbc0dd5dbf8b.png)

**Comment by SamCCSI** [comment]
Thanks for explanation Anders! I have made same change to the other incorrect contract and it all looks good now.

**Comment by anjesh** [comment]
Thanks Anders. Datepicker should appear when you click in that input field, and the date format is clear. Just wondering if it's not appearing in your browser. Let me know if that's the case. 

In any case we will add the format-help-text besides the label to avoid confusion. https://github.com/NRGI/resourcecontracts.org/issues/462

![image](https://cloud.githubusercontent.com/assets/120488/10283076/a90ca492-6b9d-11e5-9957-d3d3df130bc1.png)

**Comment by SamCCSI** [comment]
date picker appeared for me

On Mon, Oct 5, 2015 at 10:32 AM, Anjesh <notifications@github.com> wrote:

> Thanks Anders. Datepicker should appear when you click in that input
> field, and the date format is clear. Just wondering if it's not appearing
> in your browser. Let me know if that's the case.
>
> In any case we will add the format-help-text besides the label to avoid
> confusion. #462 <https://github.com/NRGI/resourcecontracts.org/issues/462>
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/120488/10283076/a90ca492-6b9d-11e5-9957-d3d3df130bc1.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/460#issuecomment-145547180>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>
