### ISSUE TITLE
Redirect alpha.openlandcontracts.org to openlandcontracts.org

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#463]
Scheduled for Tuesday.

**Comment by anjesh** [comment]
@byndcivilization could you do point the openlandcontracts.org to the same CNAME as for alpha

**Comment by anjesh** [comment]
http://www.openlandcontracts.org/ up and running cc @JesseCCSI

**Comment by JesseCCSI** [comment]
Many thanks @anjesh !
