### ISSUE TITLE
Back-end and front end are showing contradictory statuses

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#464]
For contract 1150, the back-end says there is no text or annotations.

![screen shot 2015-10-05 at 1 28 39 pm 2](https://cloud.githubusercontent.com/assets/12913915/10288167/337fd984-6b65-11e5-8652-6c5d089306a3.png)

Yet the front-end is showing the contract with metadata and annotations.

![screen shot 2015-10-05 at 1 27 04 pm 2](https://cloud.githubusercontent.com/assets/12913915/10288097/d72dd0c8-6b64-11e5-8c43-df67696d5e44.png)

Letting you know in case it reveals a larger (more damaging) bug

**Comment by SamCCSI** [comment]
I edited this to show you the correct screenshot

**Comment by anderspeders** [comment]
Yes, agree this looks weird. 

Correct link to front end (with annotation) should be: http://alpha.openlandcontracts.org/contract/1150/view#/pdf

Suggest that we slate for sprint 10 to ensure that backend and front end are alligned across.

**Comment by SamCCSI** [comment]
another example:
![screen shot 2015-10-05 at 5 14 24 pm](https://cloud.githubusercontent.com/assets/12913915/10293830/bb79dd02-6b84-11e5-9b3b-ca0534602edb.png)
![screen shot 2015-10-05 at 5 14 14 pm](https://cloud.githubusercontent.com/assets/12913915/10293829/bb79c56a-6b84-11e5-8ff2-61466d6da23a.png)

**Comment by SamCCSI** [comment]
On the above second example: Annotations are displayed on front-end, but back-end has them in draft status

**Comment by SamCCSI** [comment]
Link for 2nd example: http://resourcecontracts.elasticbeanstalk.com/contract/1036

**Comment by anjesh** [comment]
For the first case we will look into the issue.

For the second case, that's possible. The subsite is independent from the backend. Once you publish any of the three (metadata/published/draft), they will appear in the subsite. But once you edit any one of them, the edits will not reflected in the subsite unless you re-publish the changed set again. The idea is any mistake you make in the backend will not be reflected in the subsite until you manually publish them.

**Comment by SamCCSI** [comment]
Ok, thank you for that clarification. Good to know.

cc @kaitlinccsi

On Mon, Oct 5, 2015 at 11:10 PM, Anjesh <notifications@github.com> wrote:

> For the first case we will look into the issue.
>
> For the second case, that's possible. The subsite is independent from the
> backend. Once you publish any of the three (metadata/published/draft), they
> will appear in the subsite. But once you edit any one of them, the edits
> will not reflected in the subsite unless you re-publish the changed set
> again. The idea is any mistake you make in the backend will not be
> reflected in the subsite until you manually publish them.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/464#issuecomment-145730262>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by anjesh** [comment]
And for the first case, the pdf-processing started and some how processing crashed with few pages left, so that status for annotation/pdf-text shows nothing though it has data. We re-ran the processing and it's fine now.

**Comment by SamCCSI** [comment]
Thanks @anjesh for clearing this up!

I have just submitted the text to MT.
