### ISSUE TITLE
Countries page not up to date

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#466]
I just updated a contract's metadata to set its country as Timor-Leste (this had previously been omitted). 
But the country page still doesn't show it as a country for which we have contracts:
http://alpha.openlandcontracts.org/countries

![image](https://cloud.githubusercontent.com/assets/12913915/10290034/bfccfcf0-6b6f-11e5-9716-60f1d2bc53dc.png)

**Comment by SamCCSI** [comment]
Here's the TImor-Leste contract: http://alpha.openlandcontracts.org/contract/1032/view

**Comment by SamCCSI** [comment]
Timor does show up when filtering by specific resources:
![screen shot 2015-10-05 at 2 56 03 pm](https://cloud.githubusercontent.com/assets/12913915/10290294/4c94ee6c-6b71-11e5-8d1a-5f9c0045dbec.png)

**Comment by anderspeders** [comment]
Just checked it in my browser where it looks good (below). I assume that this is a cache issue. Can you check in another browser or clear cache and test again?   

![image](https://cloud.githubusercontent.com/assets/1101585/10291163/49481158-6b76-11e5-96b7-0fe55494ad60.png)

**Comment by SamCCSI** [comment]
Working on mine now, thanks

**Comment by anjesh** [comment]
That's correct. We are caching the result for 5 minutes in this country page to minimize the server calls especially when clicking filter-options quickly, for smooth results.

**Comment by SamCCSI** [comment]
No worries. Thanks all!

On Mon, Oct 5, 2015 at 10:52 PM, Anjesh <notifications@github.com> wrote:

> That's correct. We are caching the result for 5 minutes in this country
> page to minimize the server calls especially when clicking filter-options
> quickly, for smooth results.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/466#issuecomment-145728740>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>
