### ISSUE TITLE
RC/OLC - should source URL be auto-hyperlinked?

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#467]
Should the source URL be automatically hyperlinked? Or is there a reason we have not made it so?

![screen shot 2015-10-05 at 4 20 53 pm](https://cloud.githubusercontent.com/assets/12913915/10292410/2146ee20-6b7d-11e5-9d65-f078feb9508d.png)

**Comment by anjesh** [comment]
It must have been missed - it will be hyperlinked.

**Comment by anjesh** [comment]
Fixed.
