### ISSUE TITLE
Poorly OCR'ed text visible in free text searches

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#468]
For contracts that have not been MT'ed: even when PDF text is not published, the search results for free text searches display poorly OCRed text:
![image](https://cloud.githubusercontent.com/assets/12913915/10293059/81646f14-6b80-11e5-9e6a-283117ab4be2.png)

cc @KaitlinCCSI

**Comment by SamCCSI** [comment]
touched on peripherally in this issue: https://github.com/NRGI/resourcecontracts.org/issues/367

**Comment by anjesh** [comment]
Thanks for pointing this out. Will look into this. 

The reason for this result is "Contract Text" can't be published independently from "Contract Pdf pages" - the way we have designed this component, so we introduced "Show Text" option to hide the text only.

**Comment by anjesh** [comment]
Fixed. Now if the "Show text" option is set to Off in metadata, then those texts are not indexed in ES and the search results shouldn't list those results.
