### ISSUE TITLE
Sidebar menu > missing 'View All' under country list

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#469]
When I click on the the sidebar, the 'View All' option that is available under the resource list is not available under the Country list (see screenshot below).  Is it possible to have this option for all three lists in the sidebar (Country, Resource, Year)? 

![image](https://cloud.githubusercontent.com/assets/14910764/10293894/1a62ae52-6b85-11e5-9be4-897ed6270d81.png)

![image](https://cloud.githubusercontent.com/assets/14910764/10293920/39bc4fc4-6b85-11e5-956d-a573e9fd7306.png)

When I click on 'View All' under the resource list, it leads to this... 
![image](https://cloud.githubusercontent.com/assets/14910764/10293978/7bf9f1f2-6b85-11e5-8950-42479342ae97.png)

cc @KaitlinCCSI

**Comment by KaitlinCCSI** [comment]
As clarification - this is so there is another way to visit country and resource lists, aside from only from the bottom of the home page. Not pressing, though, so have moved to sprint 11.

**Comment by anjesh** [comment]
The idea is the list shows 10 items, if more than 10, then "View all" link is enabled like in case of "Resources". But once you are in any country page, there's link to "Countries" page in the breadcrumb.

**Comment by KaitlinCCSI** [comment]
Let's close for now and re-assess later. I understand why View All is only
enabled for longer lists, but also see value in being able to access
countries page from more than just the bottom of the home page. Don't think
this is a priority though.

On Mon, Oct 5, 2015 at 10:16 PM, Anjesh <notifications@github.com> wrote:

> The idea is the list shows 10 items, if more than 10, then "View all" link
> is enabled like in case of "Resources". But once you are in any country
> page, there's link to "Countries" page in the breadcrumb.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/469#issuecomment-145730791>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PpDgmXq&m=1b6584ac6c4c&t=20151005&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PpDgmXq&m=1b6584ac6c4c&t=20151005&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01PpDgmXq&m=1b6584ac6c4c&t=20151005&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by sadhakbj** [comment]
- Done
![view_all](https://cloud.githubusercontent.com/assets/5828622/12261656/94eb7cc2-b94a-11e5-93dd-f8af3eaa052f.png)
