### ISSUE TITLE
Internationalization - Fr

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#47]
As a user I need to experience a single language user experience across three supported languages: English, French and Spanish. Eg. automatic language detection based on Accept-Language (set in user’s browser).

**Comment by sadhakbj** [comment]
We have generated the google sheet which contains the code list to be translated. Please check it [here](https://docs.google.com/spreadsheets/d/1aLnUIKyi6uHb0Ai8Zl3S21wn2ekOapciMUguTCjddig/edit#gid=1810864825) and update the contents for french accordingly..

**Comment by anjesh** [comment]
@anderspeders @KaitlinCCSI @SamCCSI 
Please note that we have started the localisation of the site parallelly and almost ready once we get the french text for the given codelist shared by @sadhakbj. You will see multiple sheets in this [google docs](https://docs.google.com/spreadsheets/d/1aLnUIKyi6uHb0Ai8Zl3S21wn2ekOapciMUguTCjddig/edit#gid=1810864825) all of which needs to be translated.

**Comment by charlesyoung** [comment]
French translations Google sheet completed. 

https://docs.google.com/spreadsheets/d/11RO8DtlwmICXM2qQ7vY2tFALAYpUnBfSMLssr9FE7pA/edit?usp=sharing

**Comment by anjesh** [comment]
This is the translation for the backend linked in this [issue](https://github.com/NRGI/resourcecontracts.org/issues/897). we need the one for subsite in this spreadsheet https://docs.google.com/spreadsheets/d/1aLnUIKyi6uHb0Ai8Zl3S21wn2ekOapciMUguTCjddig/edit#gid=0

**Comment by charlesyoung** [comment]
Global site translations in below Google sheet. 

https://docs.google.com/spreadsheets/d/1wVq4-6SX6W8Pk8Tyo87KuqZDhoxosCHzdtCvQkOWaQc/edit?usp=sharing

**Comment by charlesyoung** [comment]
Couple updates on the French Global site below. 

1. The text is in English and 'More' should be 'Plus'.

![image](https://cloud.githubusercontent.com/assets/13888372/15824747/fdc45f6a-2c00-11e6-9592-8645b5fa1e84.png)

2. Below is still in English 

![image](https://cloud.githubusercontent.com/assets/13888372/15824885/ac78c686-2c01-11e6-8cb8-97df38b01cc4.png)

3. Resource should be Ressource and African Mining ..... is still in English

![image](https://cloud.githubusercontent.com/assets/13888372/15824978/2679f43c-2c02-11e6-9a23-af32e6e282d2.png)

4. Issue below. 

![image](https://cloud.githubusercontent.com/assets/13888372/15825178/fd4d9bb2-2c02-11e6-9111-661dc5d6b469.png)

5. Resource and drop-down list in English. Select also in English. 

![image](https://cloud.githubusercontent.com/assets/13888372/15825233/374e255c-2c03-11e6-9986-1b586f528657.png)

6. Reset and Resource in English. 

![image](https://cloud.githubusercontent.com/assets/13888372/15825355/a86fb0e8-2c03-11e6-97de-1527d4bbd5b0.png)

**Comment by charlesyoung** [comment]
1. Some of the drop down lists like 'Ressource' are in English

2. The 'download search results' downloads all the contracts and not only for the DRC

3. Why cannot I find below companies, of a newly added contract, on the DRC or Global RC sites? 

![image](https://cloud.githubusercontent.com/assets/13888372/15898177/75389eb6-2d97-11e6-9dd3-ad9158417ba9.png)

4. Should the page numbers not be hyperlinked? 

![image](https://cloud.githubusercontent.com/assets/13888372/15898278/ecb6bb62-2d97-11e6-955b-e63ac38b4236.png)

**Comment by charlesyoung** [comment]
@anjesh is someone looking at these issues?

**Comment by manishgs** [comment]
> Should the page numbers not be hyperlinked?

If article reference is not given then page number is hyperlinked else page number is link. Please check [here](http://rc-site-demo.elasticbeanstalk.com/drc/public/contract/ocds-591adf-CD6818431592RC)

**Comment by charlesyoung** [comment]
English text in the public French interface.

![image](https://cloud.githubusercontent.com/assets/13888372/16115598/5baf3356-33c8-11e6-844b-3f24909caf5f.png)

**Comment by charlesyoung** [comment]
As above image the resource is correct (French) but in the metadata summary as below its wrong. 

![image](https://cloud.githubusercontent.com/assets/13888372/16115786/98ea4cb4-33c9-11e6-98fe-33d8d82eb4ff.png)

**Comment by charlesyoung** [comment]
@upasna01 one more issue noted. The disclosure mode is correctly translated on the summary page but not below. 

![image](https://cloud.githubusercontent.com/assets/13888372/16611097/9a5ad780-435f-11e6-8cc7-2f4013bd6557.png)

**Comment by anjesh** [comment]
We are ready in terms of functionality for French. There might be issues with translated text - please report such issues here https://github.com/NRGI/resourcecontracts.org/issues/963
