### ISSUE TITLE
More from [Country] & More for [Resource] has disappeared

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#470]
Links used to be in bottom right corner. They've disappeared. Have checked a few different contracts; none of them have this anymore.

What it used to look like: 
![image](https://cloud.githubusercontent.com/assets/14825437/10298495/6be1617c-6ba5-11e5-8bd2-314541504702.png)

Currently:
![screen shot 2015-10-05 at 9 07 27 pm](https://cloud.githubusercontent.com/assets/14825437/10298497/72f71f06-6ba5-11e5-9cc4-6325aa0c7ca9.png)

cc @jedm

**Comment by anjesh** [comment]
I see that @byndcivilization has hidden the code to display these more documents block in one of hit PR https://github.com/younginnovations/resourcecontracts-rc-subsite/pull/4/files#diff-4d6821d723a5c3e12768bbf7b619a1f1L258

@byndcivilization ?

**Comment by byndcivilization** [comment]
Anders wanted to move all of that up into the main metadata block. Made sense since we're double listing things. Idea was to just put the links directly in metadata.

**Comment by jedm** [comment]
When this was proposed was it understood that it would hide the "more docs" from their place in the lower right?

Not sure I see the logic of call this metadata because it's not about the doc it's about /other/ docs and is driven by metadata. 

However, if that is the recommendation from NRGI team then it definitely requires a change to the template so that this related material from our site and other places is permanently visible in contract view. 

Otherwise it's buried.

**Comment by anderspeders** [comment]
@jedm the hyperlinks serve essentially the same function as the "more docs" section while making the right bar cleaner. 

It will also additionally free up space in the bar which will enable us to add other relevant sections if we decide to do so at a later stage - for example: associated documents...

**Comment by jedm** [comment]
@anderspeders and @byndcivilization

In terms of UX, that's a mistake if we seek to help users easily understand their options and more clearly promote the depth of content on the site. Also, see @anderspeders note from 12 days ago that [we do not want to link people immediately away from the Contract page](https://github.com/NRGI/resourcecontracts.org/issues/364#issuecomment-142983675)

Also can you fix the visual inconsistency in placement of "see summary" alongside Metada column header while the left column "more" links are at bottom left. Should be consistent so users learn where to expect things on the site. (Also check that capitalization of these orange "more" links be made consistent between left and right columns.)

From a process, standpoint, confused why the layout recommended and spec-ed by @KaitlinCCSI and me over many hours in September was reversed without notice of the change or a quick check-in to discuss options that might address all concerns! cc @KaitlinCCSI @jimc33 @samccsi

**Comment by anderspeders** [comment]
In my opinion the current design carries forward the requested functionalities of the right bar as discussed before - just in a cleaner way. And clean design is important when we already have a crowded page.

**Comment by jedm** [comment]
Fewer things is always cleaner but it's certainly not as discussed before.

**Comment by KaitlinCCSI** [comment]
As Jed mentioned, I thought we had decided that we didn't want to divert
people from the contract with these types of hyperlinks in the metadata.
Also, as a user, these links seem a bit confusing, because the hyperlinks
in left column take you to the place in contract where information is
found, but the hyperlinks in right column take you to a separate page and
completely away from the contract. Hyperlinks look the same, though, so
presumably user would think they served similar purposes.

Jed and I spent a very long time trying to distill different suggestions
into concrete suggested layout, and I'd appreciate a query about potential
changes of this nature before they are implemented. Can we continue this
discussion in sprint 10?


On Tue, Oct 6, 2015 at 11:42 AM, jedm <notifications@github.com> wrote:

> Fewer things is always cleaner but it's certainly not as discussed before.
>
> > On Oct 6, 2015, at 12:39 PM, Anders <notifications@github.com> wrote:
> >
> > In my opinion the current design carries forward the requested
> functionalities of the right bar as discussed before - just in a cleaner
> way. And clean design is important when we already have a crowded page.
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/470#issuecomment-145922938>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PpQG2TS&m=7ccc43aec2ff&t=20151006&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PpQG2TS&m=7ccc43aec2ff&t=20151006&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01PpQG2TS&m=7ccc43aec2ff&t=20151006&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by anderspeders** [comment]
Sounds good, 
Let's review in sprint 10.

**Comment by KaitlinCCSI** [comment]
Flagging this for follow-up per agreement above.

**Comment by anjesh** [comment]
Shall we decide on this particular issue - whether we are to do this or not?

**Comment by byndcivilization** [comment]
I would still rather a cleaner interface.

**Comment by jedm** [comment]
@byndcivilization In this case I think the utility of including the two lines considerably outweighs any relative clutter of this bit. Plus it's what we put forth as the recommendation - per above - but I'll defer to the group.

**Comment by byndcivilization** [comment]
I still dont see the utility of segregating hyperlinks. If anything its an inefficient use of space that underestimates users ability to navigate.

**Comment by jedm** [comment]
Let's see what others think, Chris.

**Comment by KaitlinCCSI** [comment]
Discussed internally. See pros/cons of both approaches, but still have preference for sticking with recommendation in specs so long as we can keep these lines short ("More in [Country]" on one line; "More in [Resources]" ideally on one line as well: e.g., "More for Cobalt | Copper").

**Comment by anderspeders** [comment]
Thanks @KaitlinCCSI, 

So just to summarize these would appear: 
- "More in [Country]"
- "More in [Resource] | [Resource II]"

Regarding keeping it on one line. As you see below this might be difficult once multiple resources are listed. I do not have a suggestion for this but wanted to flag it might be difficult to keep on oneline: 
![image](https://cloud.githubusercontent.com/assets/1101585/13118744/ad24ad46-d573-11e5-947d-69f0ef0d87c9.png)

**Comment by jedm** [comment]
As long as YI can make sure to keep a "hanging indent" if the multiple resources extend to muiltiple lines, I think this will be ok.

**Comment by KaitlinCCSI** [comment]
Sounds okay to me. Just to clarify, this is only for country and resource -
so none of the other categories will appear in this list nor will they be
hyperlinked (eg, year, type of contract will no longer be hyperlinked).

On Wednesday, February 17, 2016, jedm <notifications@github.com> wrote:

> As long as YI can make sure to keep a "hanging indent" if the multiple
> resources extend to muiltiple lines, I think this will be ok.
>
> > On Feb 17, 2016, at 9:42 AM, Anders <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > Thanks @KaitlinCCSI <https://github.com/KaitlinCCSI>,
> >
> > So just to summarize these would appear:
> >
> > "More in [Country]"
> > "More in [Resource] | [Resource II]"
> > Regarding keeping it on one line. As you see below this might be
> difficult once multiple resources are listed. I do not have a suggestion
> for this but wanted to flag it might be difficult to keep on oneline:
> > <
> https://cloud.githubusercontent.com/assets/1101585/13118744/ad24ad46-d573-11e5-947d-69f0ef0d87c9.png
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/NRGI/resourcecontracts.org/issues/470#issuecomment-185320844
> >.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/470#issuecomment-185330854>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01QjueDv4&m=7bb8c628b9cd&t=20160217&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01QjueDv4&m=7bb8c628b9cd&t=20160217&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01QjueDv4&m=7bb8c628b9cd&t=20160217&c=f>
>


-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by anderspeders** [comment]
Thanks @KaitlinCCSI, 

@anjesh: This is now ready to implement.

**Comment by jedm** [comment]
@anderspeders and @anjesh Did this make it into one of the last 2 sprints?

**Comment by manishgs** [comment]
added to sprint #15

**Comment by KaitlinCCSI** [comment]
Moving this to sprint 16

**Comment by upasna01** [comment]
@KaitlinCCSI  underlined links are link to more country and more resources, please verify and provide your feedback.

Here is the link to contract .
http://www.resourcecontracts.org/contract/ocds-591adf-PH6493643447RC/view#
![more](https://cloud.githubusercontent.com/assets/11477899/15773006/4cd0cbe4-2994-11e6-8974-2606bc9a66f1.png)

**Comment by jedm** [comment]
@upasna01 and @anjesh - Apologies if there are any mixed instructions above. 

The 2016 comments are regarding appearance of metadata, _not_ hyperlinks within metadata. It was agreed previously (see [here](https://github.com/NRGI/resourcecontracts.org/issues/364#issuecomment-142983675), [here](https://github.com/NRGI/resourcecontracts.org/issues/470#issuecomment-185320844) and [here](https://github.com/NRGI/resourcecontracts.org/issues/470#issuecomment-185357755)) that metadata at the Contract level does not link to all-[Resource] or all-[Country]. Per the title of this Issue, the question was about having those links at the bottom of the column (or perhaps on the Contract Summary page not the Contract View page).

The group may want to change its mind and have the metadata at top of the column drive people away from the individual Contract, but we should confirm if we want to change the previous decision.

**Comment by KaitlinCCSI** [comment]
Confirming @jedm's explanation -- we had agreed to a different approach than what we currently have, per discussion above. However, given other priorities, we are fine just keeping as is.

**Comment by manishgs** [comment]
@jedm  @KaitlinCCSI
Metadata view has been updated. Please review and let us know your feedback.

**Comment by SamCCSI** [comment]
The wording has changed. 
![image](https://cloud.githubusercontent.com/assets/12913915/18349433/7370ca4a-759f-11e6-9887-ead35e61b140.png)

Unless others have different ideas, I suggest changing to the original structure: 
**More 
From [Country] 
For [Resource]**  

Old example: 
![image](https://cloud.githubusercontent.com/assets/12913915/18349486/b96347ee-759f-11e6-83b2-511cf05e428a.png)

**Comment by jedm** [comment]
Original structure had the word "More " repeated on both line, which will be less confusing.

**Comment by SamCCSI** [comment]
@jedm can you confirm this is the intended structure?

**More from [Country] 
More for [Resource]**

**Comment by jedm** [comment]
Confirmed.

**Comment by manishgs** [comment]
Text updated. 

![screenshot-www resourcecontracts org 2016-09-16 17-37-35](https://cloud.githubusercontent.com/assets/3942999/18585046/55938db4-7c34-11e6-87bb-cc697fd4084d.png)
