### ISSUE TITLE
Capitalization on Contract View page

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#472]
"see summary" should be capitalized ---> "See Summary"

"year" in "Signature year" should be capitalized --->
![screen shot 2015-10-06 at 6 02 43 am](https://cloud.githubusercontent.com/assets/14825437/10306934/247edb66-6bf0-11e5-9ea3-4b8132b90dbf.png)
 "Signature Year"

**Comment by anderspeders** [comment]
Thanks for noting this and for added screen shot @KaitlinCCSI
