### ISSUE TITLE
OCR process

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#474]
What happens to graphics like organisational charts during the OCR process?

[A question from the Pretoria Workshop]

**Comment by anderspeders** [comment]
Graphics are not transcribed in the current OCR process. The charts will for the time being only be available from the PDF-version of the contract. 

[Can you add the above to a google doc with FAQ for the site?]

**Comment by charlesyoung** [comment]
Yep that was my reply as well at the workshop. Added to the admin guide.
