### ISSUE TITLE
Mobile devices

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#475]
The RC site doesn't seem to be working optimally on mobile devices. 

[A question from the Pretoria Workshop]

**Comment by KaitlinCCSI** [comment]
Have also flagged this as serious concern. Mobile use was key part of what
we had originally wanted for new platforms. Another example of group wish
not making it into priorities - or even discussion - during
process. Strongly suggest revisiting post launches.

On Tuesday, October 6, 2015, Charles Young <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> The RC site doesn't seem to be working optimally on mobile devices.
>
> [A question from the Pretoria Workshop]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/475>.
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PpNrQQq&m=7ebfa61fd6d5&t=20151006&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PpNrQQq&m=7ebfa61fd6d5&t=20151006&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01PpNrQQq&m=7ebfa61fd6d5&t=20151006&c=f>
>


-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by anjesh** [comment]
I did have some discussion with Anders on this. Except for the contract view page, the site is responsive. We do have plans to fix this page as soon as it gets stable. In sprint 10, we will take care of contract view page.

**Comment by KaitlinCCSI** [comment]
Thanks, Anjesh.

On Tuesday, October 6, 2015, Anjesh <notifications@github.com> wrote:

> I did have some discussion with Anders on this. Except for the contract
> view page, the site is responsive. We do have plans to fix this page as
> soon as it gets stable. In sprint 10, we will take care of contract view
> page.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/475#issuecomment-145908436>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PpPTbvf&m=c947001c0617&t=20151006&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PpPTbvf&m=c947001c0617&t=20151006&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01PpPTbvf&m=c947001c0617&t=20151006&c=f>
>


-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by anderspeders** [comment]
Thanks all, 

Let's assign this for sprint 10 tentatively. I am aware that we are aggregating a long issue list for the coming sprint, so we might need to push this forward.

**Comment by anderspeders** [comment]
We will improve the mobile responsiveness of the *contract view page*. This will be done in sprint 10.

**Comment by anjesh** [comment]
Try resizing contract view page. Though there might be few other improvements in that small view, the page doesn't get distorted when viewed in small screens.

![image](https://cloud.githubusercontent.com/assets/120488/10533411/79e6dd06-73e8-11e5-8e9f-ea542fae0e16.png)

**Comment by charlesyoung** [comment]
Just checking that by closing this case you are implying that the RC public site is fully operational. Still some funnies as shown below. 

![image](https://cloud.githubusercontent.com/assets/13888372/10538259/9cb36a48-73f7-11e5-9377-e2420c1fb859.png)

![image](https://cloud.githubusercontent.com/assets/13888372/10538248/87969fcc-73f7-11e5-9a7f-42eb1791652e.png)

**Comment by anjesh** [comment]
By closing i am implying it should be working in smaller screens. There might be few issues here and there, but the page shouldn't get distorted. Do open up issues if you find any specific issue. Thanks.

**Comment by KaitlinCCSI** [comment]
As noted in #546, I now can't open any of the contract view pages at all
from a mobile device.

On Fri, Oct 16, 2015 at 4:27 AM, Anjesh <notifications@github.com> wrote:

> By closing i am implying it should be working in smaller screens. There
> might be few issues here and there, but the page shouldn't get distorted.
> Do open up issues if you find any specific issue. Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/475#issuecomment-148665003>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PtJrg6q&m=807fdeb29c4f&t=20151016&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PtJrg6q&m=807fdeb29c4f&t=20151016&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01PtJrg6q&m=807fdeb29c4f&t=20151016&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>
