### ISSUE TITLE
Separate and and resources portals 

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#476]
Why are there two separate portals (land and resources) as it would make more sense to incorporate the sites? 

[A question from the Pretoria Workshop]

**Comment by KaitlinCCSI** [comment]
One big site was original idea, but NRGI didn't have land within scope of
what org would work on, so we needed a separate site. We had spoken in the
past about ways to ensure better linkages between sites - at very least
prominent hyperlinks, but we had other ideas about stronger integration too
- but those seem to have been lost along with other institutional memory
and joint decisions/priorities. Suggest revisiting post launches.

On Tuesday, October 6, 2015, Charles Young <notifications@github.com> wrote:

> Why are there two separate portals (land and resources) as it would make
> more sense to incorporate the sites?
>
> [A question from the Pretoria Workshop]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/476>.
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PpNtuQW&m=5f6947fdd4a4&t=20151006&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PpNtuQW&m=5f6947fdd4a4&t=20151006&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01PpNtuQW&m=5f6947fdd4a4&t=20151006&c=f>
>


-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>
