### ISSUE TITLE
Contract uploaded with wrong annotations

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#480]
http://resourcecontracts.elasticbeanstalk.com/contract/1036

Contract is from Sudan, and has been erroneously paired with annotations from a South Sudanese contract (this one - http://www.openlandcontracts.org/contract/1180/view)

We want to keep contract 1036 because it has already been through MT.

Will it be possible to just delete all annotations, so that we can enter them onto site once manual annotation functionality is created?

CC: @KaitlinCCSI

**Comment by anderspeders** [comment]
Post-launch: We want to  enable editing of annotations from the backend - so yes this should become possible - hopefully in sprint 10.  

Pre-launch: You could publish PDF/text and metadata without publishing the annotations to at least get it up, right?

**Comment by SamCCSI** [comment]
Thanks, Anders.

I have unpublished it for now, as we only want to feature contracts with
full annotations.

But great that we can change this post-launch, once the annotation editing
module is live.

On Tue, Oct 6, 2015 at 2:45 PM, Anders <notifications@github.com> wrote:

> Post-launch: We want to enable editing of annotations from the backend -
> so yes this should become possible - hopefully in sprint 10.
>
> Pre-launch: You could publish PDF/text and metadata without publishing the
> annotations to at least get it up, right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/480#issuecomment-145960865>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by SamCCSI** [comment]
This issue can be closed, thanks!
