### ISSUE TITLE
Change front end text in search field

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#481]
Change from: "Type here to search for contracts..."
To: "Search [INSERT RC CONTRACT AMOUNT] contracts"

(for example for RC today: "Search 395 contracts"

![image](https://cloud.githubusercontent.com/assets/1101585/10322161/92fdab26-6c4a-11e5-85bc-99f3e4cb502f.png)

@KaitlinCCSI @samCCSI: please confirm if this would also be useful for OLC as well?

**Comment by anjesh** [comment]
Fixed the text in both olc and rc.
