### ISSUE TITLE
Advanced search page > annotation category boxes 

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#482]
When you select some items from the annotations category dropdown, the grey 'boxes' sometimes spill over (screenshot below gives much better explanation). 

![screen shot 2015-10-06 at 16 53 32](https://cloud.githubusercontent.com/assets/14910764/10322304/221739a8-6c4b-11e5-9ea1-5629772449f6.png)

**Comment by anjesh** [comment]
@JesseCCSI which browser are you using and OS?

**Comment by JesseCCSI** [comment]
@anjesh Mac OS X and Chrome

**Comment by anjesh** [comment]
I am using the same and it appears fine. Haven't seen such in any browser so far. Strange.

**Comment by KaitlinCCSI** [comment]
I just checked the 2 in Jesse's example - Arbitration didn't do it, but local procurement did. Am on a Mac and using Chrome.

![screen shot 2015-10-07 at 7 36 29 am](https://cloud.githubusercontent.com/assets/14825437/10336353/3972fdaa-6cc6-11e5-9833-406ba7f44d26.png)

**Comment by anjesh** [comment]
Thanks @KaitlinCCSI for noticing this one - we had this particular category only out of boundary in our browser as well. Fixed now. Do check.

![image](https://cloud.githubusercontent.com/assets/120488/10533362/d4782c94-73e7-11e5-80f8-c54e64e35142.png)
