### ISSUE TITLE
Making About, FAQ, and other pages easier to find/access

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#486]
When I look at the site on my laptop, it's hard to find the About, FAQ, contact, and other pages that are listed in the bottom left of the footer. Is it possible to make them easier to find? 

(As noted in #382 , for which 404 page was then adjusted, but no other changes made.)

**Comment by anjesh** [comment]
Should be addressed here https://github.com/NRGI/resourcecontracts.org/issues/862 and https://github.com/NRGI/resourcecontracts.org/issues/873
