### ISSUE TITLE
Wrong country for contract in metadata

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#487]
Can this be fixed in next 30 minutes? Should be Sierra Leone; it says Liberia.

Heading to launch now, but wanted to show this page and so would be good to have correct results. @anderspeders @anjesh @byndcivilization 

http://www.openlandcontracts.org/contract/1043/view

![screen shot 2015-10-07 at 9 55 12 am](https://cloud.githubusercontent.com/assets/14825437/10339523/c4fa83d0-6cd9-11e5-9d72-e00d7b800162.png)
![screen shot 2015-10-07 at 9 54 59 am](https://cloud.githubusercontent.com/assets/14825437/10339525/c70aa934-6cd9-11e5-9ad5-f0a4d8e9d4ca.png)

**Comment by anjesh** [comment]
Fixed and re-published.
