### ISSUE TITLE
Linking RC.org to African Mining Legislation Atlas and Landportal data

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#49]
As a user I would like each annotation of each contractual clause to have one click links to the specific legislative provisions that govern the contractual clause I am reading, so that I can see how the contractual obligations operate in the context of the surrounding legal framework. For RC.org this could be links to the African Mining Legislative Atlas or any other website hosting relevant laws. For OLC.org, this could be links to FAOLEX, the Land Portal or any other website hosting  relevant laws. Such a website would need to be hosting past versions of the law to ensure that the link goes to the version of the law that was in force at the date the contract was signed. Ideally the link would take me to the specific page of the law where the relevant provision is located. The advantage of linking to that external website is that I can then explore the legislation more generally.

Link to site: www.a-mla.org

**Comment by upasna01** [comment]
This issue is resolved. Please verify.
![resourcecontracts org london mining company limited sierra leone 2012](https://cloud.githubusercontent.com/assets/11477899/13350150/7d1b0dcc-dca6-11e5-9fe5-0ae5166e8c05.png)
