### ISSUE TITLE
Return from cluster category to top in left bar

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#491]
![image](https://cloud.githubusercontent.com/assets/1101585/10348505/720ce900-6d07-11e5-9e3d-6837df013b8e.png)

**Comment by anjesh** [comment]
Top arrow now appears when you scroll down. 

![image](https://cloud.githubusercontent.com/assets/120488/10505546/3534cd40-732e-11e5-9910-9d961027a996.png)

**Comment by KaitlinCCSI** [comment]
I don't see an arrow? And cluster categories at top now not linking to
place in column where annotations in that category start

On Thu, Oct 15, 2015 at 12:32 AM, Anjesh <notifications@github.com> wrote:

> Closed #491 <https://github.com/NRGI/resourcecontracts.org/issues/491>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/491#event-436013510>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PthvM4r&m=4e1e6c96b8ca&t=20151015&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PthvM4r&m=4e1e6c96b8ca&t=20151015&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01PthvM4r&m=4e1e6c96b8ca&t=20151015&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by anjesh** [comment]
This is fixed now. Please reopen if you still find issue here.
