### ISSUE TITLE
Reconsider cluster category anes: "General", "Other"?

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#492]
Suggestion from Patrick to consider different terms...

**Comment by KaitlinCCSI** [comment]
Think that would be a good idea. Did he have specific suggestions?

On Wednesday, October 7, 2015, Anders <notifications@github.com> wrote:

> Suggestion from Patrick to consider different terms...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/492>.
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PqjqMxG&m=558eadadc907&t=20151007&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PqjqMxG&m=558eadadc907&t=20151007&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01PqjqMxG&m=558eadadc907&t=20151007&c=f>
>


-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by anjesh** [comment]
This could be discussed in the general annotation category fix issue https://github.com/NRGI/resourcecontracts.org/issues/565
