### ISSUE TITLE
Add annotation content to annotation category search results

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#493]
As a user when I search for annotation categories - eg. bonuses - I want the annotation text to appear in the search result in *a seperate column* (instead of underneath the contract name):

![image](https://cloud.githubusercontent.com/assets/1101585/10349599/4d612908-6d0d-11e5-81ba-43beec133370.png)

1) Suggesting the following order on the site:
Contract name | Annotation category | Annotation content (in full) | Country | Year ...

2) Enable download of the search result - including the column with annotation content

**Comment by anjesh** [comment]
From the UI perspective it mightn't look good. First of all annotation category can get very long, then annotation text is also long. And when there are multiple categories selected, it gets even difficult to manage the space.

**Comment by KaitlinCCSI** [comment]
Agree this should be thought through carefully; would be nice to get this
info more quickly, but think this could look fairly overwhelming and messy.
Perhaps @jedm might have some ideas on this?

On Wednesday, October 7, 2015, Anjesh <notifications@github.com> wrote:

> From the UI perspective it mightn't look good. First of all annotation
> category can get very long, then annotation text is also long. And when
> there are multiple categories selected, it gets even difficult to manage
> the space.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/493#issuecomment-146404511>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01Pqr5gp7&m=2925d42eff36&t=20151007&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01Pqr5gp7&m=2925d42eff36&t=20151007&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01Pqr5gp7&m=2925d42eff36&t=20151007&c=f>
>


-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by jedm** [comment]
@KaitlinCCSI and @anderspeders - I agree with @anjesh 

Suggestion attached for adding Annotation category and Section/Reference/Page next to excerpt. This avoids adding a column. Also suggest adding ellipses around each excerpt.

And recommend deleting "Found in" just like we deleted "Sort by" in Contract page. The "Text/Annotation/Metadata" sprites are clear without the extra words on page.

![rcolc_ui_search_pg_1](https://cloud.githubusercontent.com/assets/2153664/10364016/08f49646-6d86-11e5-9a7a-cde8053adab4.jpg)

**Comment by jedm** [comment]
@anjesh and @byndcivilization Is there a way to include number of matches per document in Search results? When I go to a result and search the same word again, there are many more matches than just two, which could be confusing.

**Comment by jedm** [comment]
Attached PDF includes above fixes and a half-dozen other fixes and recommendations for consistency and clearer UX in Search page.

[RCOLC_UI_search_pg.pdf](https://github.com/NRGI/resourcecontracts.org/files/9979/RCOLC_UI_search_pg.pdf)

**Comment by anjesh** [comment]
My understanding here is 

When you do free-text search, say searching for convention, then it just shows the text where it finds in the index. To make the search fast and less cumbersome, we have concatenated all the OCR text as one, and all annotations as one. So we just need to make one query to see if the query-text is present or not. 

![image](https://cloud.githubusercontent.com/assets/120488/10447200/4ac345f2-71a2-11e5-86ca-0d5379417f4c.png)

After getting the search results, now if you want to see what certain annotations categories contains, then you select them from the categories list and they are just displayed in the results itself. And that's where we can now show the section/reference info and page no. Right now only page-no is shown. 

![image](https://cloud.githubusercontent.com/assets/120488/10446860/dddf91a0-719e-11e5-9add-a84ef426a668.png)

As I had quick chat with Anders, this can somehow serve as annotation comparison as the user will be able to download the results along with the selected annotations contents in csv. 

cc @anderspeders @byndcivilization @jedm

**Comment by SamCCSI** [comment]
cc @kaitlinccsi

On Tue, Oct 13, 2015 at 2:22 AM, Anjesh <notifications@github.com> wrote:

> My understanding here is
>
> When you do free-text search, say searching for convention, then it just
> shows the text where it finds in the index. To make the search fast and
> less cumbersome, we have concatenated all the OCR text as one, and all
> annotations as one. So we just need to make one query to see if the
> query-text is present or not.
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/120488/10447200/4ac345f2-71a2-11e5-86ca-0d5379417f4c.png>
>
> After getting the search results, now if you want to see what certain
> annotations categories contains, then you select them from the categories
> list and they are just displayed in the results itself. And that's where we
> can now show the section/reference info and page no. Right now only page-no
> is shown.
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/120488/10446860/dddf91a0-719e-11e5-9add-a84ef426a668.png>
>
> As I had quick chat with Anders, this can somehow serve as annotation
> comparison as the user will be able to download the results along with the
> selected annotations contents in csv.
>
> cc @anderspeders <https://github.com/anderspeders> @byndcivilization
> <https://github.com/byndcivilization> @jedm <https://github.com/jedm>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/493#issuecomment-147617045>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by KaitlinCCSI** [comment]
I don't think this solution makes sense for a user. I would never intuitively think to do a free text search, see the results, and then do another search using the dropdowns to narrow my previous search results further. I would have assumed that I should do a free text search OR use the dropdowns to search, but not that I should layer the searches in this way.

While it would be very nice to have the annotations comparable, I think that this should be clearly done in a COMPARISON function rather than through the search function.

**Comment by jedm** [comment]
@anjesh please note the direct connection between Clippings functions/path and use of Annotations in Search results.

Because Clippings function also requires disaggregation of individual annotations and display of annotation text, the display of annotations in Search results and the display of annotations in Clipping select/deselect should be very similar or identical and the design, UI and functionality will need to be consistent. 

(Also related to #705)

**Comment by upasna01** [comment]
The issue is related to issue [610](https://github.com/NRGI/resourcecontracts.org/issues/610l) . Further discussion will be done in there.
