### ISSUE TITLE
RC public site country list

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#494]
How is the RC public site country list generated? I noticed that Albania isn't in the list although there are 13 contracts uploaded. 

![image](https://cloud.githubusercontent.com/assets/13888372/10359058/fdf3d5ae-6d94-11e5-95a6-c45ba31febb1.png)

**Comment by anjesh** [comment]
I just published one AL contract and Albania is appearing now.  http://alpha.resourcecontracts.org/countries/al

**Comment by charlesyoung** [comment]
Thanks but this isn't just about Albania but how countries are generally displayed on the RC public site. Argentina also isn't shown RC public site while 1 contract has been published.

**Comment by anjesh** [comment]
I just re-published Argentina contract again and it's showing up now http://alpha.resourcecontracts.org/search?q=&country%5B%5D=ar 
Though you might have seen that it's published in the contract view, it's not published. It's pretty early uploaded contract in Jul. It must have been published before and we have re-indexed OLC contracts several times and must have been somehow missed.

**Comment by anjesh** [comment]
In any case, we will be republishing every RC contracts soon and everything should appear in alpha.resourcecontracts.org

**Comment by charlesyoung** [comment]
Great, thanks.
