### ISSUE TITLE
Data cleanup

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#495]
Will there be a data cleanup exercise before the launch? 

![image](https://cloud.githubusercontent.com/assets/13888372/10359150/ebc70b98-6d95-11e5-92c9-a71447b4c789.png)

**Comment by anjesh** [comment]
We will do the RC contracts cleanup. Follow this issue https://github.com/NRGI/resourcecontracts.org/issues/432
