### ISSUE TITLE
Post-OCR review and approval process

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#5]
As an administrator I need to be able to review the OCR-ed content and be able to either: 
- approve it as processed or
- assign it review by human pair of eyes
- fully discard if OCR is completely incomplete

**Comment by anderspeders** [comment]
User story: As a contributor I need to be able to correct OCR-ed contracts, assuming that these will have spelling mistakes etc. I would like to be able to correct the contract language in a front end, possibly with the original PDF contract appearing in a split screen for comparison. The final text will be pushed to a final human review.

**Comment by anjesh** [comment]
There will be an option called "Text type" in the contract view page, with 3 options and appropriate color coded 
* Acceptable - green
* Needs editing - yellow 
* Needs full transcription - red
@manish707

**Comment by anderspeders** [comment]
This is done.
