### ISSUE TITLE
Metadata: Other document types

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#50]
As an administrator, I need to be able to upload annotated versions of documents other than contracts, such as AIM summaries of contracts that are not public. But these documents also have to be clearly identified as different from a contract itself.

Suggested solution: define the "document type" metadata field to include/define types which are not contracts.

**Comment by anjesh** [comment]
Currently there are 3 document type options defined as per [excel file](https://docs.google.com/spreadsheets/d/12UCQA422r5Dg3wruUmYHL2SCLdDrlesCPcm2tHD8Yu4/edit#gid=1329720090)

* Contract
* Model Contract
* Translated Contract

![image](https://cloud.githubusercontent.com/assets/120488/8592330/2928337a-264e-11e5-86ce-ea820286a84a.png)

Shall close this?
