### ISSUE TITLE
OCR Text with issues, need process for publishing

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#500]
Are Uploaders sufficiently trained to vet and approve the PDF text? Below example needed editing before being published. This will become more critical when Uploaders are using the OCR text to create the annotations. 

![image](https://cloud.githubusercontent.com/assets/13888372/10365567/a6c4a8e6-6dc4-11e5-936f-3880c9c2b60c.png)

**Comment by charlesyoung** [comment]
Not sure if this is part of the data QC exercise but I checked more OCR'ed contracts that have been published but still need text editing making it not ready for public consumption.

**Comment by anjesh** [comment]
@charlesyoung are you still finding similar issue? Please reopen if you think we need further discussion.
