### ISSUE TITLE
Annotation list

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#502]
It's not that obvious how a user can return to the annotation list once a search has been performed. The way back is to click on the text / PDF icons but its not that obvious. 

![image](https://cloud.githubusercontent.com/assets/13888372/10367318/01838e0e-6dd0-11e5-829a-bf867a48dfc5.png)

**Comment by jedm** [comment]
I cannot reproduce the above view, so it may be from an older staged site, but if this view is possible then I agree it's not ideal UI. Does this also connect to #406 ?

**Comment by charlesyoung** [comment]
I also now cannot reproduce the issue. On a side, I've added 5 annotations to a test contract but can only click on the 'Resource' and 'Project Title'. 

http://resourcecontracts.elasticbeanstalk.com/contract/1203/annotate

**Comment by anjesh** [comment]
We are re-doing this UI in admin. Will be deployed today, it will reflect the UI as of subsite.
