### ISSUE TITLE
English - French translation

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#503]
Working document: 
https://docs.google.com/spreadsheets/d/1GjnhV9fLFl_-9EHyQdpPO9X7yYysIJJkAhakWXEnOT0/edit#gid=0

1) YI will prepare list of string text that needs translation
2) Anders will follow up with @samCCSI @KaitlinCCSI on translation to French
3) YI will implement

**Comment by anderspeders** [comment]
Postponing this for now - based on prioritization.

**Comment by anjesh** [comment]
Duplicate of https://github.com/NRGI/resourcecontracts.org/issues/47#issuecomment-196803183
