### ISSUE TITLE
Automatic reset of not-submitted tasks in Mechnical turk after 10 days

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#504]
This is addressing an old issue we have wanted to fix for a while.

**Comment by anjesh** [comment]
We have functionality in place now. We deleted the tasks old than 10 days and when tried to create, couldn't create new HIT tasks in Mturk as insufficient fund in Mturk https://github.com/NRGI/resourcecontracts.org/issues/538

**Comment by anjesh** [comment]
Addressed here https://github.com/NRGI/resourcecontracts.org/issues/632
