### ISSUE TITLE
Draft Mechanical Turk workflow

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#505]

**Comment by anjesh** [comment]
@anderspeders @byndcivilization 
I have drafted the workflow for MTurk here https://github.com/NRGI/resourcecontracts.org/wiki/Mechanical-Turk-Workflow

**Comment by anderspeders** [comment]
thanks - looks good to me.

**Comment by anjesh** [comment]
Completed. Created new issue for the implementation here https://github.com/NRGI/resourcecontracts.org/issues/632
