### ISSUE TITLE
RC: Mapping and harmonization of annotation categories

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#506]
This sheet was prepared for ticket #432 but is incomplete as it only covers annotation mapping errors under "Others": 
https://docs.google.com/spreadsheets/d/1CQJsDOXoSKnv3abSDfFA-J6r_Tmn2Nxzk0A6mYyMrRI/edit?ts=56135030#gid=0

Please provide a full list of all annotation categories in RC.org which are non-compatible with the current annotation code list.

**Comment by anjesh** [comment]
This is the full list of categories in the database. Other categories are mapped during OLC data cleanup.

**Comment by anjesh** [comment]
Fixed these in database in admin. Need to republish to reflect them in subsites.

**Comment by anderspeders** [comment]
![image](https://cloud.githubusercontent.com/assets/1101585/10528711/d477a076-7365-11e5-9ea8-5f73e2ef0fc7.png)

We seem to still be short of harmonized metadata on RC.org?

**Comment by anjesh** [comment]
Following in the relevant issue https://github.com/NRGI/resourcecontracts.org/issues/432#issuecomment-148584423

**Comment by anjesh** [comment]
Have fixed this. Please reopen if you find any issue with the annotation category.
