### ISSUE TITLE
New site available publicly

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#508]
Not sure this is intentional but the beta site is available publicly.  

![image](https://cloud.githubusercontent.com/assets/13888372/10389818/7d4140be-6e74-11e5-9eba-d6822c5198bc.png)

**Comment by anjesh** [comment]
We create rc.yipl.com.np to test first (though it points to openlandcontracts.org), we will remove that, and the google should clear that from their index sometimes later.

**Comment by anjesh** [comment]
I meant alpha.resourcecontracts.org
