### ISSUE TITLE
Map on the front page in confusing - does not represent actual contract availability

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#511]
An updated world map with country coverage- some countries aren't shaeded that perhaps should be e.g. Sierra Leone.

**Comment by anjesh** [comment]
That map was not intended to be the coverage map of the contracts and it's small for that. We will replace the map without intended selected countries. But we will have interactive coverage map later.

**Comment by anjesh** [comment]
Replaced the existing map now 
![image](https://cloud.githubusercontent.com/assets/120488/10533338/8c5bccc2-73e7-11e5-9d07-7feab67d48ec.png)

Later we will have interactive and dynamic map
