### ISSUE TITLE
"Text Type" needs renaming in Admin Interface?

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#514]
I don't think that the wording 'Text Type' is descriptive enough. 

Also can we not force the selection of one of the three text types before publishing the PDF text? Below is an example of published PDF text without a selected text type. 

![image](https://cloud.githubusercontent.com/assets/13888372/10392954/e41d0da6-6e8b-11e5-9178-5bc86b5fc767.png)

**Comment by anderspeders** [comment]
Thanks @charlesyoung for flagging this, 

In principle I agree that this is a good idea. 

I think however that one very concrete problem might be that it can take a few minutes or longer for the OCR process to complete. Requiring this as mandatory fields might therefore cause delay in uploading of contracts.

@samCCSI: Can you check with Perrine and CCSI team if there would be any barriers for adding OCR review as a mandatory field?

**Comment by charlesyoung** [comment]
@anderspeders I agree that it will add time to the OCR process but the current method has resulted in over 400 'not available' text type OCR'ed contracts.

**Comment by charlesyoung** [comment]
@samCCSI just confirming that you managed to discuss this case with Perrine and co.

**Comment by SamCCSI** [comment]
Apologies all -- we will be in touch about this shortly.

**Comment by anderspeders** [comment]
So to clarify I think the challenge here is the following: 

The actual OCR processing might take anything from a few seconds to several minutes for larger size contracts. So I suspect that there might be technical issues with making it a required field. 

A possible **work flow* solution could be that CCSI as part of the contract load review that each contract is reviewed for this field.

**Comment by charlesyoung** [comment]
@anderspeders we also need to take into account country sites where CCSI won't be loading the contracts.

**Comment by charlesyoung** [comment]
@samCCSI any feedback?

**Comment by SamCCSI** [comment]
Apologies for the delay. From our researchers:

_For the shorter contracts the OCR process takes about 15 minutes or less, however it takes enough time for me to move on to next contract without reviewing the OCR. For the bigger contracts this could take more than 30 minutes to be OCR processed. My approach is to upload all the metadata of the contract and afterwards return and review the OCR. 

I do not think it would be efficient to rate the quality of the OCR as we enter the metadata. We would waste time waiting until the contracts are OCR processed._

**Comment by anjesh** [comment]
Further discussion if any here https://github.com/NRGI/resourcecontracts.org/issues/778 in the publishing workflow.
