### ISSUE TITLE
Activity log - possible to hyperlink?

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#515]
Request from our metadata uploaders:

Can we make the contracts listed on the activity log hyperlinked? Will aid everyone's ability to see docs quickly.

http://resourcecontracts.elasticbeanstalk.com/activities

**Comment by anjesh** [comment]
That sounds good.

**Comment by sadhakbj** [comment]
![515](https://cloud.githubusercontent.com/assets/5828622/10966115/8ad3e856-83d9-11e5-8eef-45ed006a1d85.png)
Done
