### ISSUE TITLE
Glitch re corporate grouping field

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#516]
From an uploader:

For a small number of contracts, where no corporate grouping is entered in respect of a company, the database reads the blank field (which says “Select”) as a corporate grouping called “Select”. Eg
http://alpha.resourcecontracts.org/contract/1200
http://alpha.resourcecontracts.org/contract/1201

**Comment by anjesh** [comment]
"Select" also appeared at one of the items in the list - that have been scrapped from the opencorporates. Need to remove from the list and fix the "Select" selected contracts metadata. http://alpha.resourcecontracts.org/search?corporate_group=Select
cc @sadhakbj

**Comment by anjesh** [comment]
"Select" item removed from the list in the admin and fixed for the contracts. But now there are few other contracts that have "Select" as Corporate Group. http://alpha.resourcecontracts.org/search?corporate_group=Select 
Now they could be easily removed from the admin and re-published and will be fixed.
