### ISSUE TITLE
Setup ES in https://aws.amazon.com/elasticsearch-service/

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#517]
Current ES instance in AWS is having some problems with high usage. Need to setup https://aws.amazon.com/elasticsearch-service/ 

Reported at https://github.com/younginnovations/resourcecontracts-api/issues/4#issuecomment-147181169

**Comment by byndcivilization** [comment]
In addition, there seems to be only limited ES functionality exposed. For instance:
```curl  -XGET "http://54.173.9.19/api/_mapping/"```

gets you this:
```<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">```
```<html><head>```
```<title>301 Moved Permanently</title>```
```</head><body>```
```<h1>Moved Permanently</h1>```
```<p>The document has moved <a href="http://54.173.9.19/_mapping">here</a>.</p>```
```</body></html>```

**Comment by anjesh** [comment]
54.173.9.19 IP is the http one, which exposes the limited API only. It's not ES.

**Comment by byndcivilization** [comment]
Do we have a way to expose the full es api? Will need this for analytics at some point. Maybe oauth?

**Comment by anjesh** [comment]
We will have a way to expose full ES api. Right now, we are just replacing the existing ES with Amazon ES service

**Comment by anjesh** [comment]
https://aws.amazon.com/elasticsearch-service/ in place and new endpoint for API is now http://rc-elasticsearch-api.elasticbeanstalk.com/api

**Comment by anjesh** [comment]
Draft docu https://github.com/NRGI/resourcecontracts.org/wiki/Elasticsearch-and-API
