### ISSUE TITLE
Validation / approval workflow for annotations

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#52]
There should be a validation/approval process where an admin or supervisor signs off when annotation has been done by a research assistant or graduate student.

**Comment by anjesh** [comment]
Annotations workflow is little tricky. There will be multiple annotations for a given contract. The following explains the annotation approval process.

There will be a page where the researcher can see the annotations and the text side by side. She can then add annotation, which will be reflected on the right-side.

![image](https://cloud.githubusercontent.com/assets/120488/8206787/41460556-151c-11e5-8450-4e635d8f961d.png)

When she is done with the annotations, she will "Done" - basically saying that the annotation is completed and is now ready for the verification/publishing by the admin. She can still make edits, after which the annotation will change to draft state and has to click "Done" again. 

![image](https://cloud.githubusercontent.com/assets/120488/8206882/ec0dc32a-151c-11e5-8052-efdae87f42b4.png)

Now when the admin goes the annotation page, admin will see that the annotations are completed and now ready to publish one by one or in bulk.

![annotation-workflow](https://cloud.githubusercontent.com/assets/120488/8206994/e302a538-151d-11e5-95c0-879ade04f69d.png)

The admin will publish all the annotations.

![image](https://cloud.githubusercontent.com/assets/120488/8206997/eab3e382-151d-11e5-99a6-5e1b93efbb58.png)

The researcher can still add/edit annotations, after which the flow goes back to beginning.

**Comment by anderspeders** [comment]
Thanks @anjesh, 

@samCCSI I would welcome your early questions and comments.

**Comment by SamCCSI** [comment]
Does "The researcher can still add/edit annotations, after which the flow goes back to beginning." mean that the admin can offer suggestions for amendment before publication?

Also how does the admin offer such suggestions? In the current practice, there is a column entitled 'notes' for the annotator to offer any suggestions / queries to the researcher to answer.

**Comment by anderspeders** [comment]
Thanks @SamCCSI for pointing this out, 

Can I ask that you create a new issue that describes this need - for the researcher and reviewer. That way we will make sure that this issue is addressed.

**Comment by anjesh** [comment]
I agree - there needs to be a mechanism for getting the "comments" from the admin. There are two ways of getting the feedbacks from the admin - for each annotation or for all annotations as a whole. Our focus for this sprint would be to get feedbacks as a whole and later if needed, we will have option to get feedback for each annotation. The process would basically follow https://github.com/NRGI/resourcecontracts.org/issues/75#issuecomment-113051468 flow, where the admin will reject or "change suggestion" to the researcher.

Thoughts? @anderspeders @SamCCSI

**Comment by anjesh** [comment]
Admin can now offer comments to the researcher's annotations in bulk for feedbacks and comments. #101 has Sam's suggestion for annotation wise comments for future enhancement.
