### ISSUE TITLE
Contract Annotations Edit/Delete functionality

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#520]
Now once the annotations are created, they can only be edited/deleted in the annotation UI only. This can be little inconvenient when we want to make quick change. We will have the functionality to make quick edits on annotation text and change annotation category in the annotation listing page itself. These edits will be inline in this interface. 

![image](https://cloud.githubusercontent.com/assets/120488/10474912/b466c794-725c-11e5-9291-59c2aa4c9c67.png)

**Comment by SamCCSI** [comment]
Again, we are happy to test this functionality - let us know when it's
ready.

cc @kaitlinccsi

On Wed, Oct 14, 2015 at 12:32 AM, Anjesh <notifications@github.com> wrote:

> Now once the annotations are created, they can only be edited/deleted in
> the annotation UI only. This can be little inconvenient when we want to
> make quick change. We will have the functionality to make quick edits on
> annotation text and change annotation category in the annotation listing
> page itself. These edits will be inline in this interface.
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/120488/10474912/b466c794-725c-11e5-9291-59c2aa4c9c67.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/520>.
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by anjesh** [comment]
Yes it's ready. This interface is designed to make easy edits (resource and annotation text in case of simple spellings mistakes) without going into the annotation interface. Double click on the category or the text and you will be able to save edits. You will need to go to annotation interface to create annotations though. 

![image](https://cloud.githubusercontent.com/assets/120488/10533019/093696b8-73e4-11e5-9004-45058c481612.png)

![image](https://cloud.githubusercontent.com/assets/120488/10533032/303c4a1e-73e4-11e5-81d6-fcebfcc1eb91.png)

You may also delete the annotation directly from this interface if you think that they are there by mistake. 

![image](https://cloud.githubusercontent.com/assets/120488/10533045/50301b52-73e4-11e5-827c-67e879808d3e.png)

@mojbenzcar need to sort the annotations list by annotation category.

**Comment by anjesh** [comment]
The annotations are now sorted. This is working now.
