### ISSUE TITLE
Make particiation share appear as percentage

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#521]
Metadata entry for the field "participation share" is numerical. 

For the front end display - please project the participation share as percentage. 

For example: 
.4 --> 40%

**Comment by charlesyoung** [comment]
Yep so 1 below should be 100%

![image](https://cloud.githubusercontent.com/assets/13888372/10485438/6756f48c-728a-11e5-92ec-cb7aa15a784c.png)

**Comment by anjesh** [comment]
Fixed.
