### ISSUE TITLE
Need clear way to get to advanced search page

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#524]
As far as I can tell, the only way to get to the advanced search page is to click on the "Search contracts" button on the home page. It is not at all intuitive that clicking on this button without typing into the search bar would bring you to this search page, so it seems like the only option for searching is to type into the search bar. Yet many users might prefer having easy access to the dropdown search menus rather than having to do a free text search. Need a clear way of finding advanced search page from home page, and ideally from other pages as well.

**Comment by anjesh** [comment]
cc @anjhero

**Comment by anderspeders** [comment]
Yes. Agree on this. I am not sure wht is best practise - but would be keen to see @anjhero share a proposal. 

There seems to be two issues: 
- getting to advanced search from home page
- getting to advanced search from other pages

**Comment by jedm** [comment]
Does this request mean the same thing as "Search all contracts?" Can't we put the same search bar already at the top of the Summary page also at the top of the View page?

![top_bar_glob_search](https://cloud.githubusercontent.com/assets/2153664/10567352/918d63ba-75b6-11e5-80ec-a33c678ec3fc.png)

**Comment by KaitlinCCSI** [comment]
I see a difference between the search bar and the search dropdowns available on the advanced search page (in screenshot). I just realized that when you click on the search bar, it drops down the search dropdown categories, but I don't think that's intuitive - I would have assumed that this search bar is just a place to type in free text search. (The dropdowns also don't appear when you click on the bar on the home page.)

![screen shot 2015-10-18 at 7 42 55 pm](https://cloud.githubusercontent.com/assets/14825437/10567684/701ad040-75d0-11e5-8748-8f6a430a4080.png)

**Comment by JesseCCSI** [comment]
Hi @anjesh would be great to see some suggestions re how to resolve this issue. Many thanks.

**Comment by anderspeders** [comment]
@anjesh @anjhero Can we pick up on this ticket to see what can be done here?

**Comment by KaitlinCCSI** [comment]
Do we have a time frame for addressing this?

**Comment by anderspeders** [comment]
Could we get 1-2 suggestions on how users can be guided from the front page to the advanced search page?

**Comment by anjhero** [comment]
Advanced search menu is incorporated in homepage: #873

**Comment by upasna01** [comment]
I think the issue is safe to close now, as further discussion can be continued [#873](https://github.com/NRGI/resourcecontracts.org/issues/873)
