### ISSUE TITLE
Create api.resourcecontracts.org and map to CNAME

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#526]
@byndcivilization could you please create subdomain api.resourcecontracts.org and CNAME to  http://rc-elasticsearch-api.elasticbeanstalk.com

Then we will have stable url for the API as well.

**Comment by byndcivilization** [comment]
Set

**Comment by byndcivilization** [comment]
Actually http://rc-elasticsearch-api.elasticbeanstalk.com is giving me a 403.

**Comment by byndcivilization** [comment]
oh yeah that probably due to the vhost. Let DNS flush to make sure everything is good.

**Comment by byndcivilization** [comment]
okay api.resourcegovernance.org is giving me a 403 now also.

**Comment by byndcivilization** [comment]
ahh i see, the api directive is at http://api.resourcecontracts.org/api

**Comment by anjesh** [comment]
Thanks @byndcivilization we need to create the vhost entry for api.rc. Will do that @hello-deepak

**Comment by anjesh** [comment]
Mixed in Vhost. Updated in https://github.com/NRGI/resourcecontracts.org/wiki/API
