### ISSUE TITLE
Description of index/mapping for elastic search

### ISSUE THREAD

**Issue by giorgiacek** [NRGI/resourcecontracts.org#527]
(I know this is not an issue, but rather a question)
I am trying to run some searches in R/elasticsearch (but I am new in this), can I have the description of the index?
So the index is "nrgi" and what is the doc_type of the contracts? 
Is it pdf_text?

**Comment by anjesh** [comment]
Index: rc_nrgi
Doc types: metadata, annotations and pdf_text

I will share the url separately. It's not protected yet.
