### ISSUE TITLE
Annotation presentation

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#528]
![image](https://cloud.githubusercontent.com/assets/13888372/10511718/94e8216c-733b-11e5-86a3-6b8b4dda8880.png)

**Comment by jedm** [comment]
Regarding the confusing two slashes (which, per earlier Issue) were not public-facing in our original site, can a fix be done either to hide or demote the second language as was done in left column of Contract view? @byndcivilization

**Comment by anjesh** [comment]
The annotations box height is fixed now. The // will be taken care of in the localisation we are working on now.
