### ISSUE TITLE
Increasing font size and ensuring that line doesn't cut through "See Summary" when site zoomed in

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#529]
When site is zoomed in (which I always do because font is so small), the line under Metadata goes through "See Summary". 
1. Can this be fixed so that when site is zoomed in to 125%, this isn't an issue?
2. Can we make the font size slightly bigger for annotations and metadata? I know that we are trying to squeeze in a lot of information, but I think the current size is just too small to read comfortably.
![screen shot 2015-10-15 at 7 21 14 am](https://cloud.githubusercontent.com/assets/14825437/10513529/dcb869bc-730d-11e5-9a51-1ee7a625bfec.pn

**Comment by anjesh** [comment]
Sure. Sounds good.
