### ISSUE TITLE
Clicking on annotation cluster category doesn't do anything

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#530]
When I click any of the annotation cluster categories at the top of the annotation bar, nothing happens. I just checked the first 4 contracts listed on OLC and this is broken on all of them:

http://www.openlandcontracts.org/contract/ocds-591adf-CD4492231156OL/view
http://www.openlandcontracts.org/contract/ocds-591adf-CD0848066778OL/view
http://www.openlandcontracts.org/contract/ocds-591adf-ET4854285702OL/view
http://www.openlandcontracts.org/contract/ocds-591adf-ET3081396501OL/view

I also checked two on RC alpha site and also doesn't work here:
http://alpha.resourcecontracts.org/contract/ocds-591adf-BI3799217198RC/view
http://alpha.resourcecontracts.org/contract/ocds-591adf-MA4899997941RC/view

Needs to be fixed immediately

![screen shot 2015-10-15 at 7 28 10 am](https://cloud.githubusercontent.com/assets/14825437/10513610/6dee8b6e-730e-11e5-945f-8d295183f697.png)

**Comment by charlesyoung** [comment]
Linked to Annotation module #519

**Comment by anjesh** [comment]
Fixed.
