### ISSUE TITLE
Add open source license terms to readme

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#531]
@byndcivilization We use MIT right?

Add to readme.

**Comment by byndcivilization** [comment]
I've been using GPL. I kind of forget at this point why, but if I remember correctly it says that modified versions must also remain open and non-commercial.

**Comment by anjesh** [comment]
What shall we use? I am up for MIT as well.

**Comment by anjesh** [comment]
@byndcivilization can you confirm which one to use?

**Comment by byndcivilization** [comment]
MIT

**Comment by anderspeders** [comment]
This is not urgent. Leaving for next sprint.

**Comment by anjesh** [comment]
But it's just a matter of updating readme file, and it's already done.

**Comment by anderspeders** [comment]
OK, did not catch that. Closing.
