### ISSUE TITLE
Annotation summary info

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#532]
Missing annotation summary info. 

http://alpha.resourcecontracts.org/contract/ocds-591adf-PH4623081838RC#annotations

![image](https://cloud.githubusercontent.com/assets/13888372/10514248/fad9566a-734c-11e5-8b91-98f431ecb59f.png)

![image](https://cloud.githubusercontent.com/assets/13888372/10514484/3ae0a744-734e-11e5-9544-89ffdc09b353.png)

**Comment by anjesh** [comment]
I think that is because it's text based annotation. The annotator didn't type anything in the box and just selected the text in the text-view. Will fix that. Thanks for noting.

**Comment by anjesh** [comment]
Now annotations quote part (selected text) is now displayed.

**Comment by charlesyoung** [comment]
Why are there still two page numbers shown? 

![image](https://cloud.githubusercontent.com/assets/13888372/10539880/5b287f8a-7403-11e5-8759-22f2fee9d325.png)
