### ISSUE TITLE
Have all Mechanical Turk notifications sent to the following people

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#533]
Whenever the system auto-generates an email notifying us of a completed mechanical turk document, can it please be sent to the following people (in addition to the person who submitted the MT task):

For OLC: Sam (s.burke@columbia.edu) and Rashida Williams (rkw2119@columbia.edu)

For RC: Sam (s.burke@columbia.edu) and Charles Nkurunziza (charles.nkurunziza@columbia.edu)

@KaitlinCCSI

**Comment by anderspeders** [comment]
Has this been implemented?

**Comment by anjesh** [comment]
Yes the notifications are now sent to those mentioned emails.

**Comment by SamCCSI** [comment]
Thanks, Anjesh.

Can we please alter this so that the MT notifications are NOT sent to the person who submitted them?

Only to the following people:

For OLC: Sam (s.burke@columbia.edu) and Rashida Williams (rkw2119@columbia.edu)

For RC: Sam (s.burke@columbia.edu) and Charles Nkurunziza (charles.nkurunziza@columbia.edu)

**Comment by SamCCSI** [comment]
I just received a notification for an OLC contract that was only addressed to me, whereas it should have also been addressed to Rashida.

Can you check whether the system is sending each notification for OLC contracts to both of us as per my previous comment?

Many thanks,
Sam

**Comment by SamCCSI** [comment]
Rashida Williams (rkw2119@columbia.edu) is the primary MT manager for OLC and has not been receiving email notifications in recent days. Can you please ensure that they are sent to the following people (as set out above):

For OLC: Sam (s.burke@columbia.edu) and Rashida Williams (rkw2119@columbia.edu)

For RC: Sam (s.burke@columbia.edu) and Charles Nkurunziza (charles.nkurunziza@columbia.edu)

**Comment by SamCCSI** [comment]
cc @anderspeders @KaitlinCCSI

**Comment by SamCCSI** [comment]
Last email received by Rashida was on Thurs November 5.
