### ISSUE TITLE
Please 'revert' previously rejected MT page

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#534]
Please 'revert' previously rejected MT pages of these two contracts so that we can keep the changes the annotator made and amend it to make it publishable.

http://resourcecontracts.elasticbeanstalk.com/mturk/1025
http://resourcecontracts.elasticbeanstalk.com/mturk/1044

Can you please notify us when done?
Thanks,
Sam

**Comment by anjesh** [comment]
Done.
