### ISSUE TITLE
Insert Category (RC or OLC) on Mechanical Turk Page

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#535]
http://resourcecontracts.elasticbeanstalk.com/mturk

This page does not list whether a contract's category is RC or OLC. Right now the only solution is to search for each contract in the main database, which takes a lot of time.

We have different staff members working on MT for OLC and RC, so we need them to be able to quickly determine which contracts are within their purview.

Proposed solution: Insert Category (RC or OLC) on Mechanical Turk Page

![image](https://cloud.githubusercontent.com/assets/12913915/10521982/b0e59188-7340-11e5-91dd-0f675d877965.png)

**Comment by anjesh** [comment]
Sounds good. We will be revisiting the MTurk flow and interface as well in next sprint. I have documented some change concepts here https://github.com/NRGI/resourcecontracts.org/wiki/Mechanical-Turk-Workflow 
Will add this one as well.

**Comment by SamCCSI** [comment]
Thank you, Anjesh.

On Thu, Oct 15, 2015 at 11:23 PM, Anjesh <notifications@github.com> wrote:

> Sounds good. We will be revisiting the MTurk flow and interface as well in
> next sprint. I have documented some change concepts here
> https://github.com/NRGI/resourcecontracts.org/wiki/Mechanical-Turk-Workflow
> Will add this one as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/535#issuecomment-148588793>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by anjesh** [comment]
Addressed here https://github.com/NRGI/resourcecontracts.org/issues/632
