### ISSUE TITLE
Wrong associated documents (coming from RC) are now on live OLC site

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#536]
See example in screenshot - two RC contracts have been added as an associated document for an Ethiopian ag contract on OLC. This is highly problematic and needs to be fixed ASAP - at least as of now, NO documents from RC should be associated to documents on OLC, or vice versa. 

![screen shot 2015-10-15 at 12 35 34 pm](https://cloud.githubusercontent.com/assets/14825437/10522186/7e72f846-7339-11e5-8fd9-894fc4d68694.png)

http://www.openlandcontracts.org/contract/ocds-591adf-ET4854285702OL/view#/pdf/page/3/annotation/23329

**Comment by anderspeders** [comment]
Hi @KaitlinCCSI, 

If I understand the issue reported this is a data entry error which can be fixed from the backend (see below). Can I ask that for future data errors you encounter that you first check if you can do the corrections in the administrator backend before reporting them. 

Issue is now corrected.

![image](https://cloud.githubusercontent.com/assets/1101585/10522616/198816b8-7344-11e5-969b-b83b512add55.png)

**Comment by KaitlinCCSI** [comment]
Thank you for fixing. How did this happen, though - why would this be a
data entry error if no new data is being entered to OLC for this sprint? Do
we have to assume that data being entered for RC is erroneously being added
to OLC, and do we thus have to go through every contract on OLC to make
sure that it hasn't happened for other contracts?

In terms of what we can fix on the backend: can you please clarify whether
we have the ability to fix annotations on the backend, or for now are we
only able to fix metadata and associated documents?

On Thu, Oct 15, 2015 at 12:59 PM, Anders <notifications@github.com> wrote:

> Hi @KaitlinCCSI <https://github.com/KaitlinCCSI>,
>
> If I understand the issue reported this is a data entry error which can be
> fixed from the backend (see below). Can I ask that for future data errors
> you encounter that you first check if you can do the corrections in the
> administrator backend before reporting them.
>
> Issue is now corrected.
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/1101585/10522616/198816b8-7344-11e5-969b-b83b512add55.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/536#issuecomment-148473423>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PttXtpm&m=ccab9fde4d4d&t=20151015&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PttXtpm&m=ccab9fde4d4d&t=20151015&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01PttXtpm&m=ccab9fde4d4d&t=20151015&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>
