### ISSUE TITLE
Editing annotations

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#537]
Thank you for adding this feature!

Do we need to click "Publish all" after editing an annotation?

For this contract: http://resourcecontracts.elasticbeanstalk.com/contract/1025

I edited the resource type (annotation). The public site did not auto-update so I clicked publish all. Then there were two entries for resource type that were identical except one said p. 1 and one p. 3. I clicked publish all again, and now there is only one entry again.

**Comment by anjesh** [comment]
Yes Sam. You need to re-publish after every edits - metadata, annotation or OCR text. You could just follow the process "complete and publish" for each component or do "publish all" to re-publish all 3. 
Do you mean that you edited one resource in page 3 and it appeared for page 1 as well? I see there are 2 entries for "Resource" and they appeared under one annotation as both annotations have the same text. 

You may quickly do edits/deletion of annotations from this interface as well now (that interface was designed to make easy edits/deletes quickly) https://github.com/NRGI/resourcecontracts.org/issues/520#issuecomment-148588058

**Comment by anjesh** [comment]
Closing this. Please reopen if you find any issue here.

**Comment by SamCCSI** [comment]
Thanks @anjesh. We will report any bugs as we start to use this.

On Thu, Oct 15, 2015 at 11:18 PM, Anjesh <notifications@github.com> wrote:

> Yes Sam. You need to re-publish after every edits - metadata, annotation
> or OCR text. You could just follow the process "complete and publish" for
> each component or do "publish all" to re-publish all 3.
> Do you mean that you edited one resource in page 3 and it appeared for
> page 1 as well? I see there are 2 entries for "Resource" and they appeared
> under one annotation as both annotations have the same text.
>
> You may quickly do edits/deletion of annotations from this interface as
> well now (that interface was designed to make easy edits/deletes quickly) #520
> (comment)
> <https://github.com/NRGI/resourcecontracts.org/issues/520#issuecomment-148588058>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/537#issuecomment-148588246>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>
