### ISSUE TITLE
Insufficient fund in Mturk

### ISSUE THREAD

**Issue by manishgs** [NRGI/resourcecontracts.org#538]
While creating new Mturk HIT got following error message. We need to add fund on mturk site in order to create new mturk tasks.

[Code] => AWS.MechanicalTurk.InsufficientFunds
[Message] => This Requester has insufficient funds in their account to complete this transaction. (1444988036599)

**Comment by anjesh** [comment]
For your action @anderspeders @byndcivilization

**Comment by byndcivilization** [comment]
Added money. Is there an api method to check balance? Might be useful to display balance somewhere on the admin site or at least to fire off a notification to check when we're getting low.

**Comment by anderspeders** [comment]
Closing this. Reopening ticket regarding notifications on balance.
