### ISSUE TITLE
Mobile devices - search page with some issue

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#539]
Still some funnies on a mobile device as shown below. 

Public RC site from a PC:
![image](https://cloud.githubusercontent.com/assets/13888372/10538259/9cb36a48-73f7-11e5-9377-e2420c1fb859.png)

Public RC site from a mobile device: (missing tab)
![image](https://cloud.githubusercontent.com/assets/13888372/10538248/87969fcc-73f7-11e5-9a7f-42eb1791652e.png)

**Comment by anjesh** [comment]
Can you verify it once more? should appear like this

![image](https://cloud.githubusercontent.com/assets/120488/10540387/3466919c-7427-11e5-8fc7-1e25c45c212f.png)

**Comment by charlesyoung** [comment]
I was mainly pointing out, sorry I wasn't that clear, that the public RC site (from a PC) shows the text tab while that's not shown on the mobile version.

**Comment by anjesh** [comment]
That should be showing now. 

![image](https://cloud.githubusercontent.com/assets/120488/10540879/ea0b29a0-742b-11e5-8536-74096f1875a0.png)

**Comment by anderspeders** [comment]
Great thanks

**Comment by KaitlinCCSI** [comment]
Anjesh, the contracts info on the search page looks good on mobile device, but the circle with the number of contracts covers up part of "results", as well as the search bar. Can this be addressed?
![img_1616](https://cloud.githubusercontent.com/assets/14825437/10542332/1e304e08-73dd-11e5-8fef-072b588cd86a.PNG)

**Comment by anjesh** [comment]
@sweetanzell @anjhero need to fix this overlapp for the mobile devices.

**Comment by JesseCCSI** [comment]
Hi @anjesh - we also noticed that the end of the word "Select" appears cut off, as in Kaitlin's screenshot above. Would be great if this could also be addressed. Many thanks.

**Comment by sadhakbj** [comment]
![539](https://cloud.githubusercontent.com/assets/5828622/11053956/0594c4b8-878e-11e5-91fe-568f4501be93.png) - done

**Comment by KaitlinCCSI** [comment]
"Select" still cut off when I open on phone.
![img_1706](https://cloud.githubusercontent.com/assets/14825437/11158170/fd25a5b4-8a1b-11e5-807d-95ab1608f0ee.PNG)

**Comment by anjesh** [comment]
Fixed now.
