### ISSUE TITLE
Setup localisation for further development

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#54]
The system should be ready to handle the content for different languages - en and fr for the start. The codelist (country, language, resources and so on) should be maintained in different languages. Similarly contract view and edit page should also follow this. Further development will follow the localisation process. @manish707 @hello-deepak

**Comment by anjesh** [comment]
userstory #47

**Comment by anderspeders** [comment]
Can we close this?

**Comment by anjesh** [comment]
The admin interface is now set for localisation. Further development follows the localisation process.

**Comment by anderspeders** [comment]
Do we have a roll out plan for localization of the front end?

French would be first priority. 

Localization of:
- annotation headers (using the annotation id as common identfier)
- various features across the site
