### ISSUE TITLE
Displaying metadata first 

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#540]
Would it not make more sense to first display the metadata info than the actual doc when clicking on the contract name link? I would like to first get general info of the contract before actually opening it. 

@anderspeders thoughts?

**Comment by SamCCSI** [comment]
I think this issue has already been through significant discussion with the developers and UI team, with the conclusion being that contract view should appear, not metadata summary.

CC @jedm @KaitlinCCSI

**Comment by anderspeders** [comment]
Yes agree.
