### ISSUE TITLE
Loading PDF page is still very slow

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#541]
Actually not sure if its working because just noted 'Loading pdf page 1'

**Comment by anjesh** [comment]
We realize this. We were compressing  js files and there's some minor issue. Fixing this.

**Comment by anjesh** [comment]
Fixed now.

**Comment by anderspeders** [comment]
Thanks - these improvements to backend are important.

Charles: please reopen if load speed gets slow again so that we can follow up.
