### ISSUE TITLE
Contract title text

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#542]
Where is below text generated from? 

![image](https://cloud.githubusercontent.com/assets/13888372/10539329/1ff6487e-73ff-11e5-9887-eefc5de422e6.png)

**Comment by anderspeders** [comment]
As I understand this is where the search term "Philippines" has been found.

This would actually be a good screen shot to add to the admin guide and maybe the FAW section as well. 

Could you add @charlesyoung?

**Comment by anjesh** [comment]
That para is from the OCR text.
