### ISSUE TITLE
Annotation heading and text distinction 

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#543]
Will it be possible to highlight the annotation headings (e.g. name of company executing document) in a different colour or make it bold so that there is a distinction between the headings and text. 

Also should the order not rather be annotation heading, text and page number than annotation heading, page number and text? 

![image](https://cloud.githubusercontent.com/assets/13888372/10539903/812812ea-7403-11e5-87d3-7725fb19d73c.png)

**Comment by jedm** [comment]
Suggest that search results have a UI more similar to annotation column for consistency.

**Comment by anjesh** [comment]
Will be taken care of when parent annotation is introduced - https://github.com/NRGI/resourcecontracts.org/issues/694
