### ISSUE TITLE
OpenLandContracts.org is DOWN

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#544]
when you try to open OpenLandContracts.org, it says "Service Temporarily Unavailable"
![screen shot 2015-10-16 at 7 18 33 am](https://cloud.githubusercontent.com/assets/14825437/10541392/44da918c-73d6-11e5-9982-262700e429f9.png)

cc @anderspeders @anjesh @byndcivilization

**Comment by anderspeders** [comment]
Anjesh - can you check?

**Comment by anjesh** [comment]
Yes. We are fixing the API now.

**Comment by anjesh** [comment]
Please check. Is working now.

**Comment by KaitlinCCSI** [comment]
Thanks; working now

On Fri, Oct 16, 2015 at 7:41 AM, Anjesh <notifications@github.com> wrote:

> Closed #544 <https://github.com/NRGI/resourcecontracts.org/issues/544>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/544#event-437487470>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PtMFHKh&m=fdbf0692a2a6&t=20151016&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PtMFHKh&m=fdbf0692a2a6&t=20151016&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01PtMFHKh&m=fdbf0692a2a6&t=20151016&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>
