### ISSUE TITLE
home pages of RC and OLC for mobile devices - change font size

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#545]
When you open the sites on a mobile device, the main words on the home page are too big for the lines, so the words are broken up oddly. Can you either make the font smaller or somehow squeeze the words together more for the mobile site ONLY? (Without changing font size for home page when looking on computer?)
![img_1618](https://cloud.githubusercontent.com/assets/14825437/10542413/9ed0416c-73dd-11e5-9443-af1ad9d67dd2.PNG)
![img_1617](https://cloud.githubusercontent.com/assets/14825437/10542414/9ed0b818-73dd-11e5-98f1-ed36d87250ca.PNG)

**Comment by sadhakbj** [comment]
![545](https://cloud.githubusercontent.com/assets/5828622/10964514/a4552420-83cf-11e5-88e3-fd69891914ec.png)
![545_rc](https://cloud.githubusercontent.com/assets/5828622/10964565/ff328464-83cf-11e5-8dbb-52394ba19002.png) Done
