### ISSUE TITLE
Change message when site is down

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#547]
Can you please change the message that appears when the site is down? My suggestion, but interested in @jedm input:

- For OLC: 
First line: OpenLandContracts.org is temporarily unavailable
Second line: We are working to fix this. Please contact resourcecontracts@yipl.com.np if the problem persists.

- For RC: 
First line: ResourceContracts.org is temporarily unavailable
Second line: We are working to fix this. Please contact resourcecontracts@yipl.com.np if the problem persists.

**Comment by anderspeders** [comment]
Will push this for sprint 11.

**Comment by jedm** [comment]
- Doesn't it make sense to have NRGI and CCSI as the contact, not YI? Unless they have an established CS function...?

- Period missing after first line of each message.

- I'd add a final line, "We apologize for any inconvenience."

**Comment by anjesh** [comment]
That email is temporary only. Do provide the email address to replace that one.

**Comment by KaitlinCCSI** [comment]
For OLC, email address should be "info@openlandcontracts.org". Different email needed for RC.

**Comment by anjesh** [comment]
Need email address for RC.

**Comment by anderspeders** [comment]
This is the email for RC: info-resourcecontracts@resourcegovernance.org   

Please implement

**Comment by anjesh** [comment]
The following message will be displayed in case of the system down. The message will be center aligned in the page. 

OLC
```
OpenLandContracts.org is temporarily unavailable.
We are working to fix this. Please contact info@openlandcontracts.org if the problem persists.
We apologize for any inconvenience.
```

RC
```
ResourceContracts.org is temporarily unavailable.
We are working to fix this. Please contact info-resourcecontracts@resourcegovernance.org if the problem persists.
We apologize for any inconvenience.
```
