### ISSUE TITLE
Same PDF referring to mulitple contracts

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#548]
The issue below highlights that one PDF can refer to multiple PDFs. 

Parked until a suitable solution is found. 

There are 5 documents which contains the same pdf (content wise) as 1385899-kosmos-energy-suriname-block-45-2011.json https://s3.amazonaws.com/s3.documentcloud.org/documents/1385899/kosmos-energy-suriname-block-45-2011.pdf

1509885-kosmos-energy-block-c8-mauritania-2012.json https://s3.amazonaws.com/s3.documentcloud.org/documents/1509885/kosmos-energy-block-c8-mauritania-2012.pdf
509888-kosmos-energy-block-c12-mauritania-2012.json https://s3.amazonaws.com/s3.documentcloud.org/documents/1509888/kosmos-energy-block-c12-mauritania-2012.pdf
1509890-kosmos-energy-block-c13-mauritania-2012.json https://s3.amazonaws.com/s3.documentcloud.org/documents/1509890/kosmos-energy-block-c13-mauritania-2012.pdf
1710314-petroleum-agreement-kosmos-cap-boujdour-see.json https://s3.amazonaws.com/s3.documentcloud.org/documents/1710314/petroleum-agreement-kosmos-cap-boujdour-see.pdf
1710318-kosmos-morocco-2013-tarhazoute.json https://s3.amazonaws.com/s3.documentcloud.org/documents/1710318/kosmos-morocco-2013-tarhazoute.pdf

**Comment by jpmckinney** [comment]
Not sure why this is a metadata issue. Perhaps when linking to the source document, the metadata should also provide a page range to refer to the relevant pages?

**Comment by anderspeders** [comment]
Closing
