### ISSUE TITLE
Agree on Language Codelist

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#55]
It's suggested to use ISO 639-2 as [discussed here](https://docs.google.com/spreadsheets/d/12UCQA422r5Dg3wruUmYHL2SCLdDrlesCPcm2tHD8Yu4/edit#gid=1329720090)

There are [506 languages] (https://docs.google.com/spreadsheets/d/12UCQA422r5Dg3wruUmYHL2SCLdDrlesCPcm2tHD8Yu4/edit#gid=279344432) in ISO 639-2 - see  whereas IATI uses around [181 languages](http://iatistandard.org/201/codelists/Language/).

There will be select options (using https://select2.github.io/examples.html), still wondering if 506 languages are to be populated. 
@byndcivilization @anderspeders

**Comment by byndcivilization** [comment]
@anderspeders? I would just add a subset but make it flexible to add more from iso list if necessary. Start with what we have and expand if we need.

**Comment by anderspeders** [comment]
Agree @byndcivilization, 

@anjesh: please go ahead

**Comment by anjesh** [comment]
By subset, do you mean IATI codelist or only those languages in which we have our contracts. What would be those languages?

**Comment by anderspeders** [comment]
We currently have contracts in: 
- English
- French 
- Spanish

If we create an "other" field, can we enable selection from a structured list, rather than just ending up with string text?

Not sure what the best approach is here, but agree that having a very long pick list from the start is not ideal.

**Comment by anjesh** [comment]
Closing this as new issue #119 being added to fix this.
