### ISSUE TITLE
Can't identify specific MT HIT

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#551]
Hi Anders and Anjesh,
 
Are you able to help us with Charles' query below?
 
Sam
 
---------- Forwarded message ----------
From: Charles Nkurunziza <charles.nkurunziza@columbia.edu>
Date: Sat, Oct 17, 2015 at 4:53 PM
Subject: Re: Regarding Amazon Mechanical Turk HIT 3VGET1QSZ0NC15QDA9NC6BJ08QXW72
To: Sam Szoke-Burke <s.burke@columbia.edu>

Hi Sam,
 
I could not find this HIT in the MT: I checked every contract in the MT (including those already sent to RC) and used the "ctrl+find" function to look for 3VGET1QSZ0NC15QDA9NC6BJ08QXW72 but did not find the HIT on any of them.
I am not sure how else to proceed.  Do the developers have access to a list of the different HITs and the respective contract pages associated to them?
 
Thanks
 
Charles
 
On Sat, Oct 17, 2015 at 1:05 PM, Sam Szoke-Burke <s.burke@columbia.edu> wrote:
Hi Charles,
 
Could you try seeing which contract they are referring to?
 
Thanks,
Sam
---------- Forwarded message ----------
From: RC Turk <rc-turk@resourcegovernance.org>
Date: Sat, Oct 17, 2015 at 9:33 AM
Subject: Fwd: Regarding Amazon Mechanical Turk HIT 3VGET1QSZ0NC15QDA9NC6BJ08QXW72
To: "s.burke@columbia.edu" <s.burke@columbia.edu>, Anders Pedersen <apedersen@resourcegovernance.org>

Sent from my iPhone

Begin forwarded message:

From: Anna Chester <mturk-noreply@amazon.com>
Date: October 17, 2015 at 8:52:26 AM EDT
To: "RC.org Mechanical Turk" <rc-turk@resourcegovernance.org>
Subject: Regarding Amazon Mechanical Turk HIT 3VGET1QSZ0NC15QDA9NC6BJ08QXW72
Reply-To: Anna Chester <anna@wtxchesters.com>

Message from Anna Chester (anna@wtxchesters.com)
---------------------------------
Customer ID: A22WGRWGSGRS18
This HIT was completed on 9/23 and is still listed as "pending".  Could you please assist?
---------------------------------

Greetings from Amazon Mechanical Turk,

The message above was sent by an Amazon Mechanical Turk user.
Please review the message and respond to it as you see fit.

Sincerely,
Amazon Mechanical Turk
https://requester.mturk.com

**Comment by anjesh** [comment]
I couldn't find this task either. However the workers file is downloadable and was able to find this particular worker id

Customer ID: A22WGRWGSGRS18

![image](https://cloud.githubusercontent.com/assets/120488/10607598/5505e25a-775a-11e5-91c1-6017ffb2181d.png)

The work has neither been approved or rejected. Strange. Maybe we should ask the worker to send the screenshot of the HIT page with the pdf and the transcribed text.

**Comment by SamCCSI** [comment]
Ok, @anderspeders could you please arrange for contact to be made with the MT operator as Anjesh suggests?

**Comment by anjesh** [comment]
Not sure if this still is valid. Created new issue to help this particular issue https://github.com/NRGI/resourcecontracts.org/issues/760
