### ISSUE TITLE
Consistency in reference to page #, section info and the word Resources

### ISSUE THREAD

**Issue by jedm** [NRGI/resourcecontracts.org#554]
@anderspeders and @byndcivilization, can we fix the varied formats and styling of page numbers and the widely variant use of the "Resource" category in the UI?

For the first, see these three screenshots. Should it be "Page" or "Pg" or "p?" Should the section info and page number be same or different color, use the colon or not? Though a small percentage of this is an artifact of the review process, much of it is not. Can someone at NRGI make a style call for what proper color formatting and terminology should be so these are fully consistent?

![section_info1](https://cloud.githubusercontent.com/assets/2153664/10598975/00a2261c-76b3-11e5-84ed-b4ae5b2f1bca.jpg)
![section_info3](https://cloud.githubusercontent.com/assets/2153664/10598977/00bff23c-76b3-11e5-90fa-26a88578dd6a.jpg)
![section_info2](https://cloud.githubusercontent.com/assets/2153664/10598976/00bfb934-76b3-11e5-939b-3cd3ad84cc21.jpg)

For the second, if the category "Resource" is referred to as "Resource" then we need to remove use of the phrases "Resources" "Resource Type" and "Resource name" as they all mean the same thing and this will really confuse people. See two screenshots.

![resource_2](https://cloud.githubusercontent.com/assets/2153664/10599000/34993f8c-76b3-11e5-8872-720ffb45b69d.jpg)
![resource_1](https://cloud.githubusercontent.com/assets/2153664/10599004/3d5b5222-76b3-11e5-817d-98af677f950f.jpg)

Some of this relates to the consistency and formatting recommendations made in [Issue 493](https://github.com/NRGI/resourcecontracts.org/issues/493#issuecomment-146489996). See the PDF file there from two weeks ago. Hopefully you have had a chance to look at that. Thanks!

**Comment by jedm** [comment]
Also, in the final screenshot above, note the two incorrect and also inconsistent search phrases. In the search box is says "Find a contract Hydrocarbons." I assume it should have a colon or add the word "in" or something. Please advise. 

Then, below, the H2 says "Contracts of Hydrocarbons" (which sounds like a 1970s vinyl title or something). Maybe say "Contracts for Hydrocarbons" — which would be consistent with the syntax of the "More" line in the lower right of Contract view.

**Comment by anderspeders** [comment]
Thanks for flagging these, 

I suggest the following streamlining. Let me know if I've missed something: 
- Change: "Resource Type" --> "Resource"
- Change: "Contract with" --> "Contracts for"
- Change: "P" and "Pg" --> "Page"
- Change: "Find a contract [Resource]" --> "Find a contract in [Resource]"

As for "Contracts for Hydrocarbons" - I wonder if the best way would be to remove this sentence entirely as the search information is already available in the search bar...

**Comment by anjesh** [comment]
Consistent use of the words as mentioned above. Need to some styling in the annotations list page in contract summary page.

**Comment by jedm** [comment]
Looks like one of my messages didn't come through. I posted it by email which may have been the problem:

* On that last point, I think that the repetition is unfortunate but that the big empty white space would look worse. So I advise keeping it. 

* Perhaps the gray text inside the search bar could be changed to only the search term, which is something that is pretty standard on other sites: displaying the term(s) searched and nothing else

* The H2 text should use the same preposition as in the lower right corner of the Contract view page.

**Comment by anjesh** [comment]
Are you talking about this page only http://www.openlandcontracts.org/resource/Agroindustry? Sorry I am confused over those points.

**Comment by jedm** [comment]
@anjesh, my apologies. I did not understand that in this scenario the search box is a search on results (a filter on a filter, sort of). In this case, the prompt next to the magnifying glass should say "Search within [TAG] contracts"

**Comment by anjesh** [comment]
Fixed the following 3
Change: "Resource Type" --> "Resource"
Change: "Contract with" --> "Contracts for"
Change: "P" and "Pg" --> "Page"

Need to replace "Find contracts in Aluminium" with "Search within Aluminium contracts" in the following page

![image](https://cloud.githubusercontent.com/assets/120488/12383906/f71e0184-bdd3-11e5-9ed6-342e7ec4aa83.png)

**Comment by sadhakbj** [comment]
- Replaced the message to "Search within tag contracts"
![554](https://cloud.githubusercontent.com/assets/5828622/12442424/f24fff7c-bf77-11e5-999c-c6f68928506e.png)
