### ISSUE TITLE
Re-think metadata category - documents

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#555]
Need more thinking about how to explain distinction between "Document Type" and "Type of Contract", which is confusing for users. Any proposal from NRGI?

![screen shot 2015-10-20 at 9 31 18 am](https://cloud.githubusercontent.com/assets/14825437/10610906/70ba3348-770f-11e5-95ce-56d98c8ffabf.png)

**Comment by jpmckinney** [comment]
Perhaps the different forms adds to the confusion. If the labels were "Document Type" and "Contract Type" (and "Type of Document" and "Type of Contract"), it'd be easier to see what the relevant difference is (i.e. a Contract is a type of Document, which can itself be categorized by type).

I think this is just a UI issue. The UI issue can perhaps be resolved by instead displaying a single "Document Type" field whose value is a concatenation of the document and contract types, e.g. "Contract – Contrat de Concession Forestière".

**Comment by anjesh** [comment]
There's a number of issues regarding the contract-type and document-type codelist. 
https://github.com/NRGI/resourcecontracts.org/issues/706#issuecomment-180989726
https://github.com/NRGI/resourcecontracts.org/issues/721
https://github.com/NRGI/resourcecontracts.org/issues/720
https://github.com/NRGI/resourcecontracts.org/issues/745 
Needs addressing all these soon and first need to finalize these 2 codelists.

**Comment by anderspeders** [comment]
Suggest we go with the following for harmonization: 
- Document type
- Contract type

**Comment by upasna01** [comment]
The issue have already been resolved, so I think this issue can be closed for now.
