### ISSUE TITLE
Bug has returned - reverse / upside down PDFs

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#556]
It didn't happen on these pages at first, but after typing in page number 23, and then typing number 3, when I hit enter it went to this back to front, upside down version:

![image](https://cloud.githubusercontent.com/assets/12913915/10626759/1d008f56-7780-11e5-826f-3fdfba51c4c2.png)

**Comment by SamCCSI** [comment]
![image](https://cloud.githubusercontent.com/assets/12913915/10626765/26480530-7780-11e5-8044-2a4a2c54cc65.png)

**Comment by SamCCSI** [comment]
This contract has the bug too. Again it happens when I type to, eg, the last page in contract, then click back to earlier pages: http://resourcecontracts.elasticbeanstalk.com/contract/1249/review

![image](https://cloud.githubusercontent.com/assets/12913915/10626945/f6fd0f6c-7781-11e5-9c2f-1ae4e678f769.png)

**Comment by anderspeders** [comment]
@anjesh Any idea how this has reappeared as an issue?

**Comment by KaitlinCCSI** [comment]
Please fix as soon as possible

**Comment by anjesh** [comment]
Page upside down is caused when the the pdfjs (library we used to render pdf) attempts to render the multiple pdf pages at the same time. We had fixed this by cancelling the pdf load (hence cancelling the pdf render) if the next page is clicked. However sometimes when the pdf is already loaded but not rendered yet, it can't be cancelled, and that might have caused the upside down render. I haven't come across this recently though. 

@SamCCSI are you getting this everytime or on random? 

Will try to see to see if https://github.com/mozilla/pdf.js/issues/2923 helps.

**Comment by SamCCSI** [comment]
Radnom - Couldn't replicate it today

On Fri, Oct 23, 2015 at 12:00 AM, Anjesh <notifications@github.com> wrote:

> Page upside down is caused when the the pdfjs (library we used to render
> pdf) attempts to render the multiple pdf pages at the same time. We had
> fixed this by cancelling the pdf load (hence cancelling the pdf render) if
> the next page is clicked. However sometimes when the pdf is already loaded
> but not rendered yet, it can't be cancelled, and that might have caused the
> upside down render. I haven't come across this recently though.
>
> @SamCCSI <https://github.com/SamCCSI> are you getting this everytime or
> on random?
>
> Will try to see to see if mozilla/pdf.js#2923 helps.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/556#issuecomment-150457953>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by SamCCSI** [comment]
*Random

On Fri, Oct 23, 2015 at 8:57 AM, Sam Szoke-Burke <s.burke@columbia.edu>
wrote:

> Radnom - Couldn't replicate it today
>
> On Fri, Oct 23, 2015 at 12:00 AM, Anjesh <notifications@github.com> wrote:
>
>> Page upside down is caused when the the pdfjs (library we used to render
>> pdf) attempts to render the multiple pdf pages at the same time. We had
>> fixed this by cancelling the pdf load (hence cancelling the pdf render) if
>> the next page is clicked. However sometimes when the pdf is already loaded
>> but not rendered yet, it can't be cancelled, and that might have caused the
>> upside down render. I haven't come across this recently though.
>>
>> @SamCCSI <https://github.com/SamCCSI> are you getting this everytime or
>> on random?
>>
>> Will try to see to see if mozilla/pdf.js#2923 helps.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/NRGI/resourcecontracts.org/issues/556#issuecomment-150457953>
>> .
>>
>
>
>
> --
>
>
>
> *SAM SZOKE-BURKE*
> *Legal Researcher**Columbia Center on Sustainable Investment*
> Columbia Law School - The Earth Institute, Columbia University
> Level 1, Warren Hall, 410 W116th St. New York, NY 10027
> | (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
> | s.burke@columbia.edu
> | www.ccsi.columbia.edu | @CCSI_Columbia
> <https://twitter.com/CCSI_Columbia> | @samszokeburke
> <http://twitter.com/samszokeburke>
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by SamCCSI** [comment]
Another example - when reviewing (from the backend) a doc just uploaded. I just clicked forward and it happened on p. 2 and 8
http://resourcecontracts.elasticbeanstalk.com/contract/1345/review
![screen shot 2015-10-27 at 9 35 30 am](https://cloud.githubusercontent.com/assets/12913915/10759546/39bc1bb6-7c8e-11e5-92b4-7af456e879c8.png)

**Comment by anjesh** [comment]
This is still random and haven't come across at our end. Just in case, i am moving to next sprint.

**Comment by anjesh** [comment]
Closing this, please reopen if you are still getting this issue.

**Comment by pcperini** [comment]
Running into this issue reliably. Is there a canonical way to cleanly cancel a render operation?

**Comment by charlesyoung** [comment]
Linked to 'Upside down PDF bug' #879
