### ISSUE TITLE
Elastic search filtered query returning no hits

### ISSUE THREAD

**Issue by giorgiacek** [NRGI/resourcecontracts.org#557]
Not very experienced with elastic search, but trying to run a filtered query, and I get no hits, but yesterday morning it used to work, how is that possible? 
 
    '{
    "query": {
    "filtered": {
    "query": {"term": { "signature_year": "2000"}},
    "filter": {
    "term": { "language": "english"}
    }
    }
    }
   }'

(sorry for bad styling)

**Comment by anjesh** [comment]
You have to use code for language. I tried this and it worked

```json
{
    "query": {
        "filtered": {
            "query": 
                { "term": { "signature_year": "2000"}
            },
            "filter": {
                "term": { "language": "en"}
            }
        }
    }
}
```

I find this easy to follow - gives the same results
```json
{
   "query" : {
             "bool" : { 
                         "must" : [
                                  {"match":{"signature_year":2000}},
                                  {"match":{"language":"en"}}
                                  ]
                       }
             }
}
```

**Comment by anjesh** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-bool-query.html

**Comment by giorgiacek** [comment]
Hi Anjesh, yes eventually I figured that out. The problem that day was just bad timing because I think you were re-indexing or something. Even with that call, I would have empty results. But now it is working.

**Comment by anjesh** [comment]
closing this now.
