### ISSUE TITLE
Source > Disclosure Mode 

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#558]
Currently, we have three options from a dropdown under "Disclosure Mode": Government/ Corporate/ Other (first screenshot below). We'd like to make the following changes to give users more info: 

1. Change "Corporate" to "Company"
2. Where we select "Other", please add a free text box to provide further details on the nature of the Source 

Also, can we make the Disclosure Mode field appear on the contract view page in righthand column at bottom of metadata (under OCID) (second screenshot). 

Many thanks.
cc @KaitlinCCSI @samCCSI

![screen shot 2015-10-21 at 17 38 22](https://cloud.githubusercontent.com/assets/14910764/10651034/ff679a34-781a-11e5-9aec-679ec49d5920.png)

![screen shot 2015-10-21 at 17 38 42](https://cloud.githubusercontent.com/assets/14910764/10651037/025dc47a-781b-11e5-8217-3099e509bd5c.png)

**Comment by anderspeders** [comment]
@anjhero Could you help accomodate the UI request here for the Contract view page right bar; 
"Also, can we make the Disclosure Mode field appear on the contract view page in righthand column at bottom of metadata (under OCID) (second screenshot)."

![image](https://cloud.githubusercontent.com/assets/1101585/10656043/d266c450-7848-11e5-9bf9-c806e8680246.png)

**Comment by anjesh** [comment]
Fixed in the subsite UI.
