### ISSUE TITLE
Associated documents box in summary view page 

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#559]
Where there are no associated docs, can we change the phrase that appears in the box to "There are currently no publicly available associated documents" rather than the phrase that appears now (highlighted in screenshot) 

cc @KaitlinCCSI @samCCSI 

![screen shot 2015-10-21 at 00 16 33](https://cloud.githubusercontent.com/assets/14910764/10651416/69f252c0-781d-11e5-9418-67199b15cdd8.png)

**Comment by anderspeders** [comment]
Not to be picky, but would ask if we could find a more simplified language than: "There are currently no publicly available associated documents" 

How about simply: "No associated documents available"?

**Comment by JesseCCSI** [comment]
Thanks for the suggestion @anderspeders we'll go with your shortened version ("No associated documents available")

**Comment by anderspeders** [comment]
Sounds good. 

Anjesh please go ahead.

**Comment by anjesh** [comment]
Fixed.
