### ISSUE TITLE
Correction of OCR-ed content

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#56]
As a reviewer of the OCR-ed content. Once I have done my corrections and hit the *Save button* I would like to see a confirmation that the changes have been saved eg. 

"Your corrections / changes have been saved"

**Comment by anjesh** [comment]
When the save button is clicked, the window should also scroll up if the content is long.

**Comment by anjesh** [comment]
@manish707 change the current message "saved" to "Your corrections / changes have been saved"

**Comment by anjesh** [comment]
Fixed.
