### ISSUE TITLE
Annotation module - Clicking on annotation category takes me to the page, but not to the highlighted part of the page.

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#561]
Clicking on annotation category takes me to the page, but not to the relevant part of the page.

**Comment by anderspeders** [comment]
this seems to be the same issue as for the front page.

**Comment by sadhakbj** [comment]
- Fixed now. Clicking on the specific annotation on sidebar now takes to specific annotation.
![561](https://cloud.githubusercontent.com/assets/5828622/12442343/420ed21e-bf77-11e5-95a4-3a119d520fcf.png)

**Comment by sadhakbj** [comment]
Fixed now.

![561](https://cloud.githubusercontent.com/assets/5828622/12442378/8ff44856-bf77-11e5-8f28-2477079d2f62.png)
