### ISSUE TITLE
Annotation module - all annotations are listed as appearing on Page 1

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#564]
On back-end and front-end, all annotations are listed as appearing on Page 1, which is wrong.
This doesn’t appear to happen when you annotate the PDF rather than the OCR text. 

![screen shot 2015-10-20 at 2 03 19 pm](https://cloud.githubusercontent.com/assets/12913915/10654926/f8e0e56c-783d-11e5-90bc-0f97a90e810c.png)

**Comment by anderspeders** [comment]
@anjesh do we know what happened here?

**Comment by anjesh** [comment]
Can you also post the link when you are adding the screenshot from next time? It's difficult to get to the exact document from the screenshot only.

**Comment by anjesh** [comment]
i can't this contract. Please share link.

**Comment by SamCCSI** [comment]
Apologies - http://resourcecontracts.elasticbeanstalk.com/contract/1134/annotate

**Comment by JesseCCSI** [comment]
Hi @anjesh is there an update on why this might be happening, and when it will be fixed? Many thanks.

**Comment by anjesh** [comment]
This is fixed now.
