### ISSUE TITLE
Annotation module - annotation categories are different from our approved list

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#565]
Some of the annotation categories are different from those on OLC’s front end - e.g. “3. Developers financial obligations” is not an annotation category. If it was one it should not have a “3. ” at the beginning and needs an apostrophe inserted so that it reads “developer’s”.

![screen shot 2015-10-20 at 2 33 19 pm copy](https://cloud.githubusercontent.com/assets/12913915/10654968/45fbdf14-783e-11e5-9399-9541dbf5fcbd.png)

**Comment by JesseCCSI** [comment]
It also looks like some annotation categories are included in the wrong cluster categories . For example "Size of concession area" is included under "Other", whereas it should be under "General"

**Comment by KaitlinCCSI** [comment]
Moving this to sprint 11b, but @SamCCSI @JesseCCSI could you please provide explicit list of all errors you've noticed that need to be changed? (In other words, any other issues aside from the 2 noted here.)

**Comment by anderspeders** [comment]
This is the current code list for "annotation categories": 
https://docs.google.com/spreadsheets/d/1tRRcib0VNynipkk83m4Be1vRaSslCKHzoIxmmC1oPLQ/edit#gid=432371003&vpid=A1

**Comment by anjesh** [comment]
I am listing all the comments that we collected from the ["annotation categories" codelist](https://docs.google.com/spreadsheets/d/1tRRcib0VNynipkk83m4Be1vRaSslCKHzoIxmmC1oPLQ/edit#gid=432371003) 

The followings should appear under "Organizational cluster", currently appear under "Other cluster". These should not actually function as an annotation category itself, hence shouldn't be allowed to select during annotation process.

* "I. General information". 
* "II. Summary of terms"
* "1. Fundamental provisions"
* "2. Community and social obligations"
* "3. Developers financial obligations" ``` -rename to-> ``` "3. Developer's financial obligations" with apostrophe
* "4. Environmental provisions"
* "5. Operational provisions"
* "6. Miscellaneous provisions"
* "III. Document notes"

There are some annotations associated with the following header annotation categories. Hence we need the mapping for the annotations for which the following are selected and we need to fix these in the database. 
* "I. General information".  - 15 annotations
* "II. Summary of terms"
* "1. Fundamental provisions"
* "2. Community and social obligations"
* "3. Developers financial obligations" ``` - 1 annotation
* "4. Environmental provisions" - 3 annotations
* "5. Operational provisions"
* "6. Miscellaneous provisions"
* "III. Document notes"

Other changes
* "Size of concession area" ```This should appear under the 'General' cluster, not 'Other'```. There are 92 annotations with this selected.
* Production Share - Cost Oil features  (basis of calculation, limits on cost recovery - e.g. as % of revenue or production, capex uplift, etc.) ```--rename-to-->``` "Production Share - Cost Oil features" (39 annotations)
* Production Share - \"Profit Oil features(triggers for variations in split - IRR, factor, production, etc .) ```--rename-to-->``` "Production Share - Profit Oil features" (40 annotations)

Please confirm these changes. 

How do we go about fixing the annotations where the annotations groups (e.g. I. General information, etc) are selected? Shall we provide you the list of those annotations?

**Comment by SamCCSI** [comment]
1. The project team is currently discussing potential name changes for cluster categories, so please do not finalize this for now.

2. Please send me the annotations where the annotations groups (e.g. I. General information, etc) are selected. CCSI can try to re-allocate these annotations or delete if superfluous.

3. Other comments from the code list are:
--- "Pages missing from  copy" should read "Pages missing from copy" (ie. delete double space between from and copy)
--- "6. Miscellaneous provisions" should read "6. Other" -- but the group may decide to change this name again.

See also this requested feature, which is related: https://github.com/NRGI/resourcecontracts.org/issues/715

**Comment by anjesh** [comment]
This [spreadsheet](https://docs.google.com/spreadsheets/d/15k-7NCkgu1p2eKgWGZnykASLQoa4gR6fOLskV8mdOhY/edit?ts=566690b1#gid=509295652) contains the changes that need to be done in the annotations categories.

There are few annotations for which the annotation header is selected and these needs to be mapped. The [spreadsheet is here](https://docs.google.com/spreadsheets/d/15k-7NCkgu1p2eKgWGZnykASLQoa4gR6fOLskV8mdOhY/edit?ts=566690b1#gid=2116919420)

**Comment by charlesyoung** [comment]
We will need further discussion on the Philippines EITI annotations request.

**Comment by anderspeders** [comment]
All change requests in this thread should be tracked in this google doc: https://docs.google.com/spreadsheets/d/15k-7NCkgu1p2eKgWGZnykASLQoa4gR6fOLskV8mdOhY/edit#gid=509295652

**Comment by anjesh** [comment]
Please create new issue if you find issues with the annotation categoroes
