### ISSUE TITLE
Annotation module - Other issues with current annotation workflow

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#566]
Other issues with current annotation workflow (that didn’t exist with our previous workflow):
1. No spell check feature - is this slated for inclusion?
2. Reviewers can only comment in one place for all annotations, as opposed to being able to comment on an individual annotation. Are you planning on building in the ability of reviewers to comment on individual annotations?
3. Is there a way to check how annotations appear to the public without publishing and then unpublishing? Might be useful for both annotators and reviewers.

**Comment by anderspeders** [comment]
1. I have checked this - and there is no pre-developed module available for spell check. Not currently in pipeline. 

2. YI will be working on a basic commenting feature for annotations. 

3. No. The best way will be to publish and review, then republish.

**Comment by KaitlinCCSI** [comment]
Spellcheck is important. Please look into whether adding this is possible. Without spellcheck, it is very easy for small mistakes to slip in that make site seem less reliable. Mistakes also affect searchability/comparability functionality of site.

Doesn't make sense to publish just to check how something looks when annotations haven't been finalized. Are we sure a simple "preview" option isn't available, like what is available with Wordpress?

cc @anjesh

**Comment by JesseCCSI** [comment]
Hi @anderspeders @anjesh this is also relevant for editing text pages (About/ FAQ/ etc). Including a "Preview Changes" button in both cases (as on wordpress sites) seems to make more sense rather than having to Publish, check changes, unpublish if changes are incorrect, and then go through the entire process again. 

cc @KaitlinCCSI

**Comment by SamCCSI** [comment]
As a reviewer, I would like to have the ability to comment on individual metadata entries, or annotations, so that the annotator can quickly review my comments and amend their original entry.

It is key that this function involve as few 'clicks' for both the annotator and the reviewer as possible. Having an individual page for each entry and its corresponding comment (if any) by a reviewer is therefore undesirable, as it will involve too many clicks to navigate this.

As added context, currently reviewers will either: (1) include individual comments in the 'comments' column on the excel spreadsheet containing the annotations, or (2) send an email that lists all comments and their corresponding categories or row numbers. Any improvements to commenting on the backend of the new system need to be as or more efficient than these currently used methods.

The backend for the comments function should look exactly the same for annotator and reviewer, as set out in the mock-up below (the comments should not be visible on the site's front end - they are not for publication). The reviewer should be able to enter a comment by simply clicking in the relevant comment box. After it is entered it should appear along side the metadata or annotation entries for the annotator so they can alter their annotation. The comment boxes will need to be longer than they are in the mock up so that text is easily displayed and readable.

The annotator should then be able to (i) click 'resolved'; (ii) add their own comments in the same box for the annotator to respond to.

There needs to be an email generated which: (i) alerts annotator or reviewer that the revieer or annotator has inserted comments or resolved issues; (ii) (if possible / easy to implement) includes the content of the comments in a structured email the way Github does for new entries.

![screen shot 2015-11-13 at 5 13 52 pm 2](https://cloud.githubusercontent.com/assets/12913915/11159208/b5f0dbd6-8a2b-11e5-8330-c840f5134be0.png)

![screen shot 2015-11-13 at 5 24 26 pm 2](https://cloud.githubusercontent.com/assets/12913915/11159210/bada1a22-8a2b-11e5-9d7d-9e21db3cc7de.png)

cc @KaitlinCCSI @JesseCCSI @jedm

**Comment by anderspeders** [comment]
Thanks @SamCCSI, 

@anjesh please include in the planning spreadsheet for sprint 11 if and how this can be done. Please do include estimates on time costs for this.

**Comment by SamCCSI** [comment]
I see the comment feature has been added.

Just reiterating that it would be really useful for comments to appear in a window / textbox, rather than having a button that you have to click on to open the comment in a pop up window, as it is currently (see screenshot below). 

This is because users need to type / make amendments to the metadata entry or annotation while reading the comment -- clicking back and forth will take time and disrupt workflows.

![image](https://cloud.githubusercontent.com/assets/12913915/11401456/a840b0d6-9360-11e5-9fcb-261019c56ef2.png)

**Comment by anjesh** [comment]
Spell check is enabled in the annotation edit. It highlights the mis-spelled words e.g. 
![image](https://cloud.githubusercontent.com/assets/120488/12383738/911a0614-bdd1-11e5-966f-d76dd6cabd65.png)

As for the comments, we can now comment in individual annotation category 

![image](https://cloud.githubusercontent.com/assets/120488/12383748/afeedc04-bdd1-11e5-97a2-2e59e144b7b7.png)
