### ISSUE TITLE
Annotation module -  selected OCR text shows beside the Article number

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#567]
When I publish annotations, the selected OCR text (that has been selected for the purpose of adding the corresponding annotation) shows beside the Article number.  

This is very messy and takes up valuable space.

Is this feature intended? Our preference is to not have the selected text appear in the left column.

cc @jesseccsi

**Comment by anderspeders** [comment]
Thanks Sam, 

Could you add a screen shot here off the text in question - to make sure we remove the right part?

**Comment by JesseCCSI** [comment]
Hi @anderspeders 

Please see screenshot below. The text we'd like to remove is the text that comes after the article number (in this case Art. 5, starting with "Clause (5) - The Republic of Sudan..."). What seems to happen is that, after the article number, the highlighted OCR text is repeated. 

The screenshot also shows that, despite having highlighted text over two pages, only one page appears in the lefthand annotation column (Page 1). 

![screen shot 2015-10-20 at 23 37 54](https://cloud.githubusercontent.com/assets/14910764/10664611/d825f2fe-7892-11e5-8bdd-650e06c267e2.png)


Many thanks.

**Comment by anjesh** [comment]
>The text we'd like to remove is the text that comes after the article number (in this case Art. 5, starting with "Clause (5) - The Republic of Sudan..."). What seems to happen is that, after the article number, the highlighted OCR text is repeated.

We added the selected text as well because there were few annotations (probably test ones) which doesn't have any annotation text. So we thought there might be just selected-text only and the category, and annotation text could be omitted.

> The screenshot also shows that, despite having highlighted text over two pages, only one page appears in the lefthand annotation column (Page 1).

It only shows page 1, because it's the continuation of the annotation from page 1. Adding page 2 to that annotation means there will be two entries of annotation in the database (following the annotation model we are using from annotatorjs), but only one annotation will be shown in the left bar.

**Comment by KaitlinCCSI** [comment]
Re adding selected OCR text - OCR text should never be included in the left-hand annotations column. If there are no annotations for a contract, the left column should just not include anything. Annotations are summaries of contract text, but they are not the contract text themselves, so auto-populating the annotation column with contract text does not make sense.

**Comment by anjesh** [comment]
Ok. Will fix that.

**Comment by sadhakbj** [comment]
- Fixed.
