### ISSUE TITLE
Annotation module - annotation box isn’t easily moved around the page

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#568]
The annotation module box isn’t easily moved around the page - e.g. if you’re annotating something at the top of a page, the top of the box tends to be cut off. When you try to move the annotation box, it tends to jump around the page. See screenshot below. 

![image](https://cloud.githubusercontent.com/assets/12913915/10655058/2ed038b6-783f-11e5-939c-32c6c7d69d5f.png)

**Comment by SamCCSI** [comment]
cc @jesseccsi

**Comment by anjesh** [comment]
This shouldn't be a problem now, the annotation-edit-box appears in such a way that it doesn't get cut off. 

![image](https://cloud.githubusercontent.com/assets/120488/12383621/3fd459fe-bdd0-11e5-8054-5811aa9b033d.png)
