### ISSUE TITLE
Editing existing annotation page numbers

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#573]
Is it possible to change the page numbers to which existing annotations are mapping? Several annotations map to incorrect page numbers. Would be useful to have the ability to edit page numbers through the "annotation box", e.g. see screenshot. 
![screen shot 2015-10-22 at 12 25 02](https://cloud.githubusercontent.com/assets/14910764/10671332/10fe9b74-78b8-11e5-9581-b3477e95a805.png)

cc @samCCSI

**Comment by anjesh** [comment]
Currently you cant' do that. You will have to delete and create new one in new page. 
The specific reason being the position of the annotation in the pdf. We could have this but the position will remain the same in the new page. We are thinking of adding the feature to move the annotation box (yellow rectangle) within the page - but that will take time to do. 

cc @anderspeders

**Comment by KaitlinCCSI** [comment]
Being able to move the annotation box within the page would be extremely useful.

**Comment by JesseCCSI** [comment]
Thanks @anjesh - just to confirm - when we want to change the PDF page, we need to delete the annotation and create a new one on the correct page?

I'll defer to @KaitlinCCSI but one solution could be having both options that you mentioned and using them together, i.e. (i) having the option to change the PDF page with the position of the yellow rectangle remaining the same, and (ii) subsequently using the option to move the yellow rectangle within the same page to accurately place it beside the relevant contract provision. Using these two features together would give us much more flexibility and help to ensure that the annotation boxes are as accurately placed as possible. 

cc @samCCSI

**Comment by KaitlinCCSI** [comment]
I think finding some way to ensure that we can place annotation boxes
accurately is important; if Jesse's proposal is the only viable one, then I
would agree with it, though if there is a more simple way to do this, that
would obviously be preferable. Being able to change the annotation box
location is important for the reasons I mentioned in #571 - annotations are
valuable, and part of their value is in being able to link directly to
original contract language. That aspect of their value is lost when the
annotation boxes are not placed in the correct location.

On Fri, Oct 23, 2015 at 7:14 AM, JesseCCSI <notifications@github.com> wrote:

> Thanks @anjesh <https://github.com/anjesh> - just to confirm - when we
> want to change the PDF page, we need to delete the annotation and create a
> new one on the correct page?
>
> I'll defer to @KaitlinCCSI <https://github.com/KaitlinCCSI> but one
> solution could be having both options that you mentioned and using them
> together, i.e. (i) having the option to change the PDF page with the
> position of the yellow rectangle remaining the same, and (ii) subsequently
> using the option to move the yellow rectangle within the same page to
> accurately place it beside the relevant contract provision. Using these two
> features together would give us much more flexibility and help to ensure
> that the annotation boxes are as accurately placed as possible.
>
> cc @samCCSI <https://github.com/samCCSI>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/573#issuecomment-150556531>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PwAevFo&m=df1e4b7bd9c4&t=20151023&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PwAevFo&m=df1e4b7bd9c4&t=20151023&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01PwAevFo&m=df1e4b7bd9c4&t=20151023&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by anjesh** [comment]
I get that. This might take some time to implement but i will try to see if this could be done in Sprint 11 - atleast research or mock implementation will be done in sprint 11 if it appears to take time. Will keep you updated.

**Comment by KaitlinCCSI** [comment]
Great, thank you!

On Friday, October 23, 2015, Anjesh <notifications@github.com> wrote:

> I get that. This might take some time to implement but i will try to see
> if this could be done in Sprint 11 - atleast research or mock
> implementation will be done in sprint 11 if it appears to take time. Will
> keep you updated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/573#issuecomment-150561452>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PwAL4Nm&m=cca5fa150269&t=20151023&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PwAL4Nm&m=cca5fa150269&t=20151023&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01PwAL4Nm&m=cca5fa150269&t=20151023&c=f>
>


-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by sadhakbj** [comment]
This is fixed now. Annotation page editing is available for PDF annotations only in the contract summary page.

![573](https://cloud.githubusercontent.com/assets/5828622/13067837/eee69fbe-d49c-11e5-9606-fde30ea81a84.png)
