### ISSUE TITLE
Time sensitive: replacing PDF file on already published contract

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#574]
http://resourcecontracts.elasticbeanstalk.com/contract/1154
http://www.openlandcontracts.org/contract/ocds-591adf-CD7865236004OL/view

The PDF file for this contract had a repeated page, which meant that all annotation page references were inaccurate.

We just clicked on "change" and uploaded a new PDF file. Initially after doing this, all metadata and annotations disappeared:

![image](https://cloud.githubusercontent.com/assets/12913915/10674494/2d0cfafc-78c9-11e5-9b07-005307f2764f.png)

But now they have reappeared:
![screen shot 2015-10-22 at 2 28 51 pm](https://cloud.githubusercontent.com/assets/12913915/10674510/4488c1b6-78c9-11e5-95e4-e90c56ebdcca.png)

Can @anderspeders or @anjesh please confirm whether it is safe for us to now click on "Publish all"? We wanted to check with you to make sure there is no risk that in doing so the annotations and metadata will be lost.

This query was initially urgent because the PDF and text of the contract was missing from the public site, though the metadata and annotations were still present.

However, I have just refreshed the page, and now the PDF and text of the contract is now also showing. 

Many thanks,
Sam 

cc @jesseccsi @KaitlinCCSI

**Comment by anderspeders** [comment]
I cannot tell but refer to Anjesh.

**Comment by anjesh** [comment]
Replacing the pdf will not alter metadata and annotations. It just replaces the existing pages. When the pdf is uploaded, it deletes the existing text content as well and for the time being annotations will not appear because there are no references to these annotations - as the pages are missing. Once the pdf processing is complete, annotations will also appear. 
It's safe to re-publish the contract. 

However without publishing, there should not be any change in the public subsite. It should show the old content. Hope this clears the process.

**Comment by JesseCCSI** [comment]
Thanks @anjesh - when we replaced a contract yesterday, it took a couple of minutes but eventually the PDF was replaced with the new uploaded file without us clicking publish. The relevant contract (http://www.openlandcontracts.org/contract/ocds-591adf-CD7865236004OL/view#/pdf/page/1/annotation/22843) was already published before we changed the file - maybe that explains why the PDF was automatically replaced without us having to publish? In the future, should we unpublish everything before changing the file, and then republish?

**Comment by anjesh** [comment]
Ok I get you now. There's only one copy of pdf files in S3 server. If you change the pdf, then those pdf pages will change in both admin and subsite, as we are using pdf urls - which in this case is already published when text is published. Beside that,  text, annotations, metadata shouldn't get updated without re-publishing.

**Comment by JesseCCSI** [comment]
Thanks for clarifying @anjesh so when we hit "Publish all" on this contract, the annotations and metadata that existed before will be retained, in addition to the new PDF? Want to make sure that the annotations and metadata don't disappear when we click publish. 

http://resourcecontracts.elasticbeanstalk.com/contract/1154 

![screen shot 2015-10-23 at 10 01 25](https://cloud.githubusercontent.com/assets/14910764/10694592/124e30f6-796d-11e5-945e-62490a22091a.png)

**Comment by anjesh** [comment]
Annotations and metadata don't disappear when you click publish. Make sure that the pdf is processed before you do the re-publishing just to ensure that there are no sideeffects.

**Comment by JesseCCSI** [comment]
Great thanks for clarifying @anjesh
