### ISSUE TITLE
search terms that contain "/" result in error

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#575]
I searched for jeb/2008 to try and find a DRC contract. it resulted in an error message.

![screen shot 2015-10-23 at 8 51 25 am](https://cloud.githubusercontent.com/assets/12913915/10693016/6702d3f4-7963-11e5-8d06-8079818374d4.png)
![screen shot 2015-10-23 at 8 51 33 am](https://cloud.githubusercontent.com/assets/12913915/10693017/68e3f216-7963-11e5-8b6a-b9b9a71b87c9.png)

**Comment by anderspeders** [comment]
To understand where the error is: Can you point to a published OCR text or annottion where " jeb/2008" should be found?

I noticed that this DRC contract - for example - has not been published as text: http://www.openlandcontracts.org/contract/ocds-591adf-CD0848066778OL/view#/text

**Comment by SamCCSI** [comment]
There may not be a contract containing that text yet, so no I can't.

I just wanted to bring to your attention that searches like that can
produce error pages, instead of the page that explains that there is no
contract that contains that search term. And surely if there is no contract
featuring the search term, that error page is not what we want users to be
presented with.

On Fri, Oct 23, 2015 at 9:14 AM, Anders <notifications@github.com> wrote:

> To understand where the error is: Can you point to a published OCR text or
> annottion where " jeb/2008" should be found?
>
> I noticed that this DRC contract - for example - has not been published as
> text:
> http://www.openlandcontracts.org/contract/ocds-591adf-CD0848066778OL/view#/text
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/575#issuecomment-150567821>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by anderspeders** [comment]
Ok, got it.

**Comment by sadhakbj** [comment]
![575](https://cloud.githubusercontent.com/assets/5828622/10966023/e54da55c-83d8-11e5-84a9-234de4f71a34.png) done

**Comment by KaitlinCCSI** [comment]
@jedm Can you suggest replacement language for message when 0 results returned? The current "Search result not found." in tiny letters seems like a missed opportunity.
![screen shot 2015-11-05 at 4 38 20 am](https://cloud.githubusercontent.com/assets/14825437/10966201/93b2d750-8377-11e5-99e1-4c66280e287f.png)

**Comment by jedm** [comment]
_Would suggest something like this:_

Your search has 0 results. To start a new search, enter your text in the search bar above. You can also [browse a full list of available contracts](http://www.openlandcontracts.org/contracts).

**Comment by KaitlinCCSI** [comment]
@sadhakbj Please replace the current text with Jed's suggested text. If you can increase the font size, please also do that.

Note that RC and OLC should have their respective "All Contracts" page hyperlinked.

**Comment by sadhakbj** [comment]
![575_done](https://cloud.githubusercontent.com/assets/5828622/11059455/f1db0430-87c1-11e5-92cd-3a0debd5de04.png) - Done
