### ISSUE TITLE
Mechanical turk page not auto-refreshing

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#576]
I submitted 4 or 5 more contracts to MT yesterday evening, but these are still not displaying on the page of contracts submitted to MT:
http://resourcecontracts.elasticbeanstalk.com/mturk

This makes it very hard for us to keep track. Is there a way this could be improved?

**Comment by anjesh** [comment]
Can you list those contracts here? I will have a look and try to send to Mturk. I am not sure how that is happening.

**Comment by SamCCSI** [comment]
Hi Anjesh,

I'm not sure if you did anything at your end, but I think the page is
displaying them now. (alternatively, I might just have been confused
because the contracts are not ordered by date submitted, or alphabetically).

One example is: Liberia, Sun Yeun Corporation, Timber Sale Contract, TSC
Area A-16, 21 July 2010
<http://resourcecontracts.elasticbeanstalk.com/mturk/1177> which I
submitted just then to test, and which appeared automatically.

So I think this issue can be closed for now. Apologies and thanks again.

Sam

On Fri, Oct 23, 2015 at 10:28 AM, Anjesh <notifications@github.com> wrote:

> Can you list those contracts here? I will have a look and try to send to
> Mturk. I am not sure how that is happening.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/576#issuecomment-150589854>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by anjesh** [comment]
I haven't done anything. I was also thinking if it's the sorting order. Will have sort functionality when we have the new interface for Mturk.
