### ISSUE TITLE
PDF page and OCR text page not automatically linked.

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#577]
As a reader of the site, I want to be able to visit a PDF page and then click 'text' and be automatically taken to the same numbered page of the text file.

Right now if I am on, e.g. page 12 of PDF and then click to Text view, it takes me to p. 1. I want it to automatically take me to p. 12.

Experience taken from navigating this contract:
http://www.openlandcontracts.org/contract/ocds-591adf-CD4479348432OL/view#/pdf

**Comment by jedm** [comment]
@anjesh and @anderspeders I should have noted this in #389 (and your follow-up thread #471). If user tries to switch between TXT and PDF and loses his/her place, that's going to confuse them significantly. It's especially rough UX because the left column does _not_ drop back to top even thought the center pane does. Until this can be fixed, it may be good to flash message in same style as disclaimer that says "Returning to top" or something. 

And if the left column can be adjusted to drop back to beginning when the center pane does, that'd be better, I think. What do others think? @byndcivilization @KaitlinCCSI

**Comment by KaitlinCCSI** [comment]
Ideally, user would not lose place when switching between PDF and OCR, and there would be no need for left column to drop back to beginning.

Until that can happen, I agree that message explaining "Returning to beginning of contract" would be useful IF each time you switch to OCR text you are actually taken to the beginning of the contract. I just checked, and it seems that switching between PDF and OCR text takes you to the page that was last opened in other mode. So the first time you switch from PDF (default view) to OCR, it takes you to page 1. But if you scroll to another page and then switch to PDF, it takes you to the last PDF page you were on. And then if you switch back to OCR text, it takes you to the place in the OCR text where you were previously.

In light of this, I'm not sure that adjusting the left column to the top would make things less confusing. It might also be annoying to lose the annotation you were looking at in the left column.

**Comment by anderspeders** [comment]
*Scoping* of a viable implementation plan and time costs should be done within this sprint.

**Comment by jedm** [comment]
Clarifying points based on group call on 3 December:

• Best case remains linked locations, "parallel motion" between left column, PDF view and OCR view. (We need further research/documentation on the barriers to that.)

• If parallel motion is not possible, the basic UI needs to change: Currently the PDF/TXT buttons look like you are "toggling" between 2 views of same thing. If location is LOST, then it is NOT A TOGGLE, so some UI change is needed to indicate "START AGAIN"   

• If PDF and OCR annotations are created in separate tools (on back end), Annotators need a single screen with UI that allows them to a) enter the annotation only ONCE, b) select location in PDF, c) select text block in OCR and d) SUBMIT.

**Comment by KaitlinCCSI** [comment]
Jed's third bullet is described in https://github.com/NRGI/resourcecontracts.org/issues/708

**Comment by SamCCSI** [comment]
Another instance of PDF and text not properly linked.

1. I am in page 3 of the PDF view.
2. I search for "operator".
3. Search results take me to p. 14 of text version.
4. I click PDF (wanting to see the PDF p. 14).
5. The system shows me page 3 of the PDF but says that it is page 14.

![image](https://cloud.githubusercontent.com/assets/12913915/13303006/cfe0dd6c-db1a-11e5-9829-7bf423893b49.png)


Here is what p. 14 actually looks like
![image](https://cloud.githubusercontent.com/assets/12913915/13303029/e58fecac-db1a-11e5-9243-bad72bc34ae3.png)

cc @anderspeders

**Comment by upasna01** [comment]
Annotation is not present in the contract above. When this issue was tested, it seems PDF and text are properly linked, the search link takes you to the desired Text and PDF (as shown below).
Please verify and provide your comments.
![resourcecontracts org septa energy nigeria limited nigeria 2010-00](https://cloud.githubusercontent.com/assets/11477899/13346512/f1130b66-dc8e-11e5-865e-dbe58a6f6e6a.png)
![resourcecontracts org septa energy nigeria limited nigeria 2010](https://cloud.githubusercontent.com/assets/11477899/13346515/f2c0d222-dc8e-11e5-8d79-ecd212a2914c.png)

**Comment by SamCCSI** [comment]
Thanks @upasna01 

This was an example of text search, not annotation search.

The problem still persists for this contract -- I just followed my above steps again and had the same problem.
http://www.resourcecontracts.org/contract/ocds-591adf-IQ2330277046RC/view#/pdf

**Comment by jedm** [comment]
@anjesh, we would like to add a visual indicator for a selected Annotation when it rolls to the top of the left column. Currently, selecting an Annotation in the left column updates the viewer (center) area to the proper location in the contract and shows the popup/balloon hovering over the yellow box. When you select an Annotation using the viewer (center) area, there is no popup or visual indicator in the left column to highlight the Annotation that rolled to the top. We do not know what would be easy or hard to implement, and we seek your team's suggestions. In addition here are two suggestions to consider:

**Option A - yellow box around Annotation Title text (English), which matches the style of the yellow box in viewer:**
![droptotop2](https://cloud.githubusercontent.com/assets/2153664/13487282/76fd780a-e0cd-11e5-8968-1c8a0c330915.jpg)

**Option B - yellow arrow next to Annotation Title, in same style as left column scroll-arrow:**
![droptotop3](https://cloud.githubusercontent.com/assets/2153664/13487287/7c6f5114-e0cd-11e5-9cff-98a75dfa9d29.jpg)

NOTE: This visual indicator for selected Annotation can be persistent until a different Annotation is selected or it can disappear after scrolling movement or any time user clicks outside the annotation. For example, the blue arrow already in use appears and disappears based on scrolling:

![droptotop4](https://cloud.githubusercontent.com/assets/2153664/13487458/fc820044-e0ce-11e5-8450-5c7fa7d8ecd7.jpg)

**Comment by manishgs** [comment]
This issue has been fixed.
