### ISSUE TITLE
Contract flashes error message before loading

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#578]
http://www.openlandcontracts.org/contract/ocds-591adf-LR9409426421OL/view#/pdf/page/18/annotation/24055

I opened this contract view page 2x; both times, an error message flashed and then the contract loaded. Is there a bug that makes this message appear if a PDF is loading slowly? Should be fixed - either no message, or a message saying that the contract is loading (not that there is an error).

Just opened another one (http://www.openlandcontracts.org/contract/ocds-591adf-CD3629082049OL/view#/pdf/page/3/annotation/25739), and same thing happened, though this time it flashed so quickly that it was hard to read - mostly just saw the red block.

**Comment by KaitlinCCSI** [comment]
Actually it seems that every contract I open on OLC has this. There message is something along the lines of "We're sorry, there is a problem. Please check back later", which obviously is not useful in this situation since the contract then loads.

**Comment by anderspeders** [comment]
@KaitlinCCSI I just checked the two contracts mentioned above. Is this issue still relevant? If not I suggest that we close.
