### ISSUE TITLE
advanced search dropdowns on advanced search page loading very slowly on RC alpha site

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#579]
Contracts themselves seem to load fast, but took a surprisingly long time for the dropdowns to load, and longer than I've noticed on OLC.

**Comment by anderspeders** [comment]
Thanks for flagging!

**Comment by anjesh** [comment]
Shouldn't be a problem now. We have added some compression mechanism in web server. And also in search results page, now we have hidden the search filter block until the page is loaded.
