### ISSUE TITLE
Email alert for when a PDF-document has been processed

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#58]
As an uploader I would like to receive an email alert when the PDF-document has been processed. Given that many documents will have some processing time required (min. to hours), users might want to receive an alert once the PDF-processing has been completed.

**Comment by anderspeders** [comment]
I suggest that we consider including this in sprint 3 - given that we expect this to be an issue.

**Comment by anderspeders** [comment]
@SamCCSI has confirmed that this issue would be of interest to a researcher / contract uploader.

**Comment by anjesh** [comment]
A separate queue is maintained with the tasks to send mail to the uploader. This helps the system to quickly respond to the users and emails will be sent processing through the queues without blocking the UI.

**Comment by anderspeders** [comment]
I think we can close this. Looks good.
