### ISSUE TITLE
Selecting contracts/annotations based on language

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#580]
It would be useful to present a way to find contracts in 1 or more specified languages. As a user, I might only want English-language contracts; French-language contracts; Spanish-language contracts; or some combination.

This could potentially be a dropdown on advanced search page, but presume there are also other ways to provide this filtering option.

**Comment by anderspeders** [comment]
I think this could be done quite easy through the advanced search page.

**Comment by anjesh** [comment]
Shall we put the language option in the advanced search? Please confirm.

**Comment by KaitlinCCSI** [comment]
I think yes. @anderspeders @jedm , any objections?

**Comment by anjesh** [comment]
@anderspeders please assign this issue to Sprint 13 if you are ok with this.

**Comment by anderspeders** [comment]
I think there is agreement to go ahead on this, 

@anjesh: Could you show where you would suggest to place the language search field - before deploying?

**Comment by SamCCSI** [comment]
Remember also our intention to have "Document Type" as another advanced search field: https://github.com/NRGI/resourcecontracts.org/issues/709

**Comment by manishgs** [comment]
done https://github.com/NRGI/resourcecontracts.org/issues/709

**Comment by KaitlinCCSI** [comment]
Thanks, but this doesn't seem to capture docs correctly? I just checked on OLC, and only 4 contracts came up when selecting "French," even though at the very least all of the DRCongo contracts are in French, and there are 14 of them. Re-opening to investigate this.

**Comment by upasna01** [comment]
@KaitlinCCSI  Only four contracts metadata are published with the category of Open Land Contracts, unpublished contracts are not displayed, so not all contracts are shown in search page.

**Comment by KaitlinCCSI** [comment]
The DRC contracts are published. See screenshots: 14 contracts from the DRC (all are in French), but only 4 appear when searching French-language contracts. @upasna01 - do you mean that only 4 contracts have French language selected on the back end?
![screen shot 2016-03-30 at 10 24 07 am](https://cloud.githubusercontent.com/assets/14825437/14147575/ae8e54d4-f661-11e5-997c-da0b1566672d.png)
![screen shot 2016-03-30 at 10 23 52 am](https://cloud.githubusercontent.com/assets/14825437/14147578/b09e24f2-f661-11e5-9c2f-12cee5e33668.png)

**Comment by KaitlinCCSI** [comment]
@upasna01 Sorry, it seems like they were incorrectly tagged on the backend. Closing ticket for now; will re-open if there are other problems. Thanks.
