### ISSUE TITLE
Random error when adding new contracts in the backend

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#582]
http://resourcecontracts.elasticbeanstalk.com/contract/1268 - should have been loaded but is unavailable.

**Comment by anjesh** [comment]
It appeared when edited and saved. However there seems to be some problem when adding new contract. 

```
exception 'ErrorException' with message 'Undefined property: stdClass::$parent_company' 
in /var/app/shared_path/storage/framework/views/1ed2a518c222a9260f711a6aae8f5205:353
```

![image](https://cloud.githubusercontent.com/assets/120488/10713104/ae100a9c-7a75-11e5-961f-4afaf38461ed.png)

**Comment by anjesh** [comment]
This hasn't appeared since.
