### ISSUE TITLE
Update import contracts template

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#585]
The template should include all metadata fields excl.: 
- OCID
- Contract identifier

**Comment by anjesh** [comment]
During upload need to make sure that the date is stored as yyyy-mm-dd. There are instances when the date is stored as mm/dd/yyyy, hence breaking the es-indexing process.

**Comment by anderspeders** [comment]
Yes, we need to provide a guide for data load. 

Additionally on the load template I would suggest that we harmonize the headers to the current headers in the metadata download CSV file that users get from the advanced search page.

**Comment by anjesh** [comment]
The format should match the csv download except for OCID and annotations https://github.com/NRGI/resourcecontracts.org/issues/607. Lets keep contract identifier. We need to redefine the contract identifier as internal identifier with some help text beside contract identifier field in the form later. Lets keep that in the contract upload template as well to maintain consistency. What do you say @anderspeders?

Hence the following order to be maintained in the contract import template

* Category (compulsory)
* Contract Name
* Contract Identifier 
* Language (compulsory)
* Country Name (compulsory)
* Resource (compulsory)
* Contract Type 
* Signature Date
* Document Type
* Government Entity
* Government Identifier
* Company Name
* Jurisdiction of Incorporation
* Registration Agency
* Company Number
* Company Address
* Participation Share
* Corporate Grouping
* Open Corporates Link
* Incorporation Date
* Operator
* Project Title
* Project Identifier
* License Name
* License Identifier
* Source Url
* Disclosure Mode
* Retrieval Date
* Pdf Url

We need to make sure that the date format could be anything and should be mapped to yyyy-mm-dd while importing into the system.

**Comment by anjesh** [comment]
I am closing this as we have already deployed.
