### ISSUE TITLE
Project name lookup against RP.org

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#587]
Create a lookup function in the metadata form to match against "project name" and project aliases in ResourceProjects.org.

**Comment by anjesh** [comment]
By Tim,

The following sparql query searches for projects with a given name (included in the bottom of the query)

```
prefix rp: <http://resourceprojects.org/def/>

SELECT DISTINCT * WHERE {
   ?s a rp:Project.

   # To only look for projects in a given country uncomment the line below and add in the correct country code
   # ?s rp:hasLocation <http://resourceprojects.org/country/AO>.
   
   {
     ?s skos:prefLabel ?label.
     bind(2 as ?score)
   } UNION {
     ?s skos:altLabel ?label.
     bind(1 as ?score)
   } 
   OPTIONAL { ?s rp:hasLocation ?country. ?country a rp:Country. ?country skos:prefLabel ?countryName. }

   #>>> Replace "Block" with the project name, or fragment of name
   
   FILTER regex(?label, "Block","i")
} ORDER BY DESC(?score) (edited)
```

Run this against http://alpha.resourceprojects.org/sparql/

**Comment by anjesh** [comment]
Here's the dev api for the lookup, that gives the following response.

http://84.45.121.135:8081/project.json?country=PE&search=Ani

Here country is optional, but we will use it for the lookup to reduce the number of matches. 

```json
{
"result_count":"",
"projects":[
    {
        "uri": "http://84.45.121.135:8081/project/PE/anim-i4iu8m",
        "identifier":"PE/anim-i4iu8m",
        "name": "Animon",
        "country":"http://84.45.121.135:8081/country/PE"
    }, {
        "uri": "http://84.45.121.135:8081/project/PE/julc-2sxclb",
        "identifier":"PE/julc-2sxclb",
        "name": "Julcani",
        "country":"http://84.45.121.135:8081/country/PE"
    }, {
        "uri": "http://84.45.121.135:8081/project/PE/macu-vfv0o1",
        "identifier":"PE/macu-vfv0o1",
        "name": "Macusani",
        "country":"http://84.45.121.135:8081/country/PE"
    }
]
}
```

@anderspeders shall we disable project-identifier field and only allow the users to retreive from the rp api? The uploaders will have no idea of the identifier as it is generated by RP. Can there also be different id from that or we can say that the id is strictly rp one.

**Comment by charlesyoung** [comment]
@anderspeders is this still required?

**Comment by charlesyoung** [comment]
Duplicated with ticket 'Add *project name* as category to advanced search bar' #986
