### ISSUE TITLE
Government entity lookup against pool party sparql endpoint

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#588]
1) Beate at JDA to provide link
2) YI to implement

Government entity field also need an "Other" field.

**Comment by anjesh** [comment]
The contract metadata form has government entity and identifier. 

![image](https://cloud.githubusercontent.com/assets/120488/10845451/f6916538-7f2d-11e5-82b1-9d73fbe3f090.png)

Using Beata's link, we will lookup for the government entity and auto-fill identifier if it is found. There might be case where government entity is not found, in that case the uploader will be able to add entity but not identifier. Identifier will be read-only and should only come from jda for consistency. We will be storing the id only and generate URI from that id. 

Beata to add more info once available.

**Comment by anderspeders** [comment]
@anjesh looks great,

We should note *how* the autofil appear for users as they will need to select the exact government entity - which often have similar names. 

For example: "Ministry of Mines (Guinea)", "government entity, country" - rather than just government entity"

We should also consider what ordering in the dropdown would be the most useful.

**Comment by anderspeders** [comment]
Can we prepare this within the next sprint or the first coming sprint in January? Are the next steps clear here @anjesh ?

**Comment by jpmckinney** [comment]
Adding links:

http://joinedupdata.org/NRGI/government-identifiers/UUIs.html
http://joinedupdata.org/NRGI/governmentidentifiers.html

Not sure if there's any difference between the two.

**Comment by anjesh** [comment]
API documentation for JDA http://joinedupdata.org/PoolParty/api 
Need to verify that otherwise need to implement sparql http://joinedupdata.org/PoolParty/sparql/NRGI

**Comment by anderspeders** [comment]
Could you share an update on the status here @sadhakbj?

**Comment by sadhakbj** [comment]
Using the API provided we have generated a JSON file which stores all the all the government entities and identifier for the particular country. We will now implement in admin site. API provides the country's name and in our case we need the country code. 
Sample of the json data generated based upon the API provided: 
```
"PY": [
    {
      "identifier": "83447b36-d54e-4f55-be23-b210e5ede4b6",
      "entity": "President Energy Paraguay S.A. (President)"
    }
  ],
  "GN": [
    {
      "identifier": "d449e7c4-290d-452c-b0bb-09ff73d3c5ab",
      "entity": "Ministere des Ressources Naturelles des energies et de l'Environnement, Ministere du Plan et des Finances"
    },
    {
      "identifier": "697f5fa1-c6a1-4070-9cc5-0db240f81e5d",
      "entity": "Minist\u00c3\u00a8re des Ressources Naturelles des \u00c3\u2030nergies et de l'Environnement, Minist\u00c3\u00a8re du Plan et des Finances"
    },
    {
      "identifier": "b8bfe91a-3dee-41e4-916c-3a9bcdc279f8",
      "entity": "Minist\u00c3\u00a8re des Mines et de la G\u00c3\u00a9ologie"
    },
    {
      "identifier": "c3a15f43-ccc3-4c04-9287-32c56ad137b0",
      "entity": "Ministere des Mines et de l'Energie, Ministere a\u00a0 la Presidence charge de l'Economie et des finances"
    }
```

**Comment by manishgs** [comment]
We have created [SpreadSheet](https://docs.google.com/spreadsheets/d/15k-7NCkgu1p2eKgWGZnykASLQoa4gR6fOLskV8mdOhY/edit?ts=566690b1#gid=1708686393) for Government entities lookup against sparql data.

Are we going to replace government identifier with sparql government identifier for matching government Entities?

**Comment by anjesh** [comment]
For those government entities (which are already present in the RC database) and if found match with the jda, we will need to replace the government-id in the RC db.

**Comment by sadhakbj** [comment]
It's implemented.
![588](https://cloud.githubusercontent.com/assets/5828622/13419090/b55c7e82-dfa3-11e5-8373-52506eddb649.png)
