### ISSUE TITLE
Add data field on "Total contract value"

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#589]

**Comment by jedm** [comment]
This is the most desired thing users ask for and (unless there is a big new plan in place to link to governing laws, fiscal regimes, explanations on how to calculate, scenarios re price of resources, maximums/minimums, currency converters) impossible to provide and offering something that can't be delivered. @jimc33

**Comment by jimc33** [comment]
ResourceProjects.org will be the place for project level calculations and scenarios. Contracts themselves don't have a "total value" per se. The best route to this would be a link to the project identifier (on RP.org) from the contract, so people can look deeper into the cashflows from the project.

**Comment by anderspeders** [comment]
Work to link up RP and RC been part of the last two day sprint - so this will be coming up in near future.
