### ISSUE TITLE
Highlight / asterisk required fields in metadata upload form

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#59]
http://ebproject-dev.elasticbeanstalk.com/contract/create

**Comment by anjesh** [comment]
Shall we put the followings fields as mandatory?
* Country
* Year of signature
* Contract Title 
* File

**Comment by anjesh** [comment]
Fixed. Currently these four fields are made mandatory and asterisk added. 
* Contract File
* Contract Name
* Country
* Signature Date

**Comment by charlesyoung** [comment]
Should this not be expanded to include 'Language', 'Resource', 'Type of Contract', 'Company Name', 'Jurisdiction of Incorporation' and 'Disclosure Mode'?

**Comment by anjesh** [comment]
cc @anderspeders

**Comment by KaitlinCCSI** [comment]
I would not include "Jurisdiction of incorporation", as it's possible the contract might not include that data, and so making this a mandatory field could be problematic.

**Comment by charlesyoung** [comment]
Can this please be added in Sprint #11? There are more and more contracts with no 'resource' or 'type of contract', etc allocation. 

Can we agree that the following should be added as required fields?
1. Language
2. Resource
3. Type of Contract
4. Company Name
5. Disclosure Mode

**Comment by KaitlinCCSI** [comment]
Requiring those 5 fields are fine with us.

**Comment by charlesyoung** [comment]
Thanks. 

@anjesh can you please assign to a Sprint? 

cc @anderspeders

**Comment by anderspeders** [comment]
Sounds good, 

I might suggest that we add as well to required field:

6. Government Entity

Yes, let's include this for sprint 11.

**Comment by charlesyoung** [comment]
Yes good idea to include Government Entity.

**Comment by anjesh** [comment]
The following fields will be required and also need to be checked in the import module. 

Contract File
Contract Name
Country
Signature Date
Language
Resource
Type of Contract
Company Name (multiple)
Disclosure Mode
Government Entity (multiple)

**Comment by SamCCSI** [comment]
'Government entity' should not be a required field for Associated Documents. 

Eg. a community-company contract might not refer to a specific government entity.

Can you please change?

**Comment by KaitlinCCSI** [comment]
Would be better to have "Signature Year" rather than "Signature Date" as a
mandatory field. This is because (1) Year rather than Date is the dropdown
search, (2) Year rather than Date is featured in righthand metadata column,
and (3) on very rare occasions, only the year is available.

On Thu, Nov 5, 2015 at 9:57 PM, Anjesh <notifications@github.com> wrote:

> The following fields will be required and also need to be checked in the
> import module.
>
> Contract File
> Contract Name
> Country
> Signature Date
> Language
> Resource
> Type of Contract
> Company Name (multiple)
> Disclosure Mode
> Government Entity (multiple)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/59#issuecomment-154278490>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PC3VGPB&m=f17d13d56845&t=20151105&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PC3VGPB&m=f17d13d56845&t=20151105&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01PC3VGPB&m=f17d13d56845&t=20151105&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by charlesyoung** [comment]
@KaitlinCCSI there is only a 'Signature Date' field in the metadata form and no 'Signature Year' field.

**Comment by KaitlinCCSI** [comment]
Okay, then ignore that point. Didn't realize that year in righthand column
was being pulled from sig date.

On Thu, Nov 12, 2015 at 2:47 AM, Charles Young <notifications@github.com>
wrote:

> @KaitlinCCSI <https://github.com/KaitlinCCSI> there is only a 'Signature
> Date' field in the metadata form and no 'Signature Year' field.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/59#issuecomment-156035569>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PEwLtCj&m=ef8fc7d5e428&t=20151112&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PEwLtCj&m=ef8fc7d5e428&t=20151112&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01PEwLtCj&m=ef8fc7d5e428&t=20151112&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by charlesyoung** [comment]
Should we also include 'Category' as a required field? The current setup is that RC is checked by default which isn't ideal. Could be better to have 'Category' as a required field and then allow the Uploader to select RC or OLC.

**Comment by SamCCSI** [comment]
Apologies for coming to this issue late. 

The following should not be asterisked for both RC and OLC:

- Disclosure mode - this will usually be inputted, but there are instances where the answer is not known to the individual uploader / annotator, and finding it out from colleagues can slow the upload process down.
- Government entity (for associated documents) - associated document might not always refer to a government entity.

cc @KaitlinCCSI

**Comment by anjesh** [comment]
Please confirm if you want these two fields (disclosure mode and government entity) to be made optional. 

cc @anderspeders

**Comment by charlesyoung** [comment]
Also Category?

**Comment by anjesh** [comment]
The followings fields are now compulsory

Contract name
Language
Country
Resource
Government Entity
Type of Contract
Signature date
Company name
Category

**Comment by SamCCSI** [comment]
Hi all,

There are various undated contracts on RC. We therefore request that Signature date or Signature year not be a mandatory category -- otherwise bad / incorrect data will be created.

cc @anderspeders @KaitlinCCSI

**Comment by SamCCSI** [comment]
From our uploader:

For the following five entries, the Signature Dates remain blank: 
DRC, Gécamines, CMD [KMT] - Kolwezi - JVA Amend, 2001
http://resourcecontracts.elasticbeanstalk.com/contract/1384
DRC, Gécamines, Kinross [KCC] - Kamoto - JVA, 2004
http://resourcecontracts.elasticbeanstalk.com/contract/1387
DRC, Gécamines, Cobalt Metals, Ruashi Holding [Ruashi-Mining] - Ruashi - JVA Amend, 2004 
http://resourcecontracts.elasticbeanstalk.com/contract/1351
DRC, Gécamines, Samref [MUMI] - Mutanda - JVA, 2001 
http://resourcecontracts.elasticbeanstalk.com/contract/1355
DRC, Gécamines, CICO [COMIDE] - Mashitu / Safwe - JVA, 2002**
http://resourcecontracts.elasticbeanstalk.com/contract/1386

In these contracts, the date of signature is unclear.  I have followed the Administrator’s Guide by putting an ambiguous big-ended date in the “Contract Identifier” field, but I have deliberately left the “Signature Date” field blank.  The system does not allow an ambiguous “Signature Date” (i.e., a date including “00”), and when I created these entries it was not a mandatory field.  

(**For this entry the "Signature Date” field should be blank, but I tried to update it using an ambiguous big-ended date (20020201) but it defaulted to 2002-02-01 and now it won’t let me undo this.)
