### ISSUE TITLE
Add download option [PDF/Word] for the contract page

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#593]
Offer similar option as for contract summary page. 

Reason: given that this is the main page for using and analyzing the contract a download option to be available. The current option on the summary page seems to add an inconvenient additional step.

**Comment by KaitlinCCSI** [comment]
This was also discussed in ticket #264, which was closed, although I've not seen the print or the download options implemented.

Note that there should not be the option to download or print Word documents from OpenLandContracts. There should be the options to download/print PDFs from the contract summary page on OLC.

**Comment by sadhakbj** [comment]
![593](https://cloud.githubusercontent.com/assets/5828622/10964729/f23191f0-83d0-11e5-9949-a233b757dde2.png) - done

**Comment by anjesh** [comment]
This is about the "Download" option in the contract view page

**Comment by sadhakbj** [comment]
![593](https://cloud.githubusercontent.com/assets/5828622/10965218/9aa3e75a-83d3-11e5-8389-b2e470942d5b.png)

**Comment by sadhakbj** [comment]
![593](https://cloud.githubusercontent.com/assets/5828622/10965685/e86d6e86-83d6-11e5-9d04-6fc03ef5dcf2.png) done

**Comment by KaitlinCCSI** [comment]
The PDF download option needs to be implemented on OLC as well, per comment above. Re-opening.

**Comment by anderspeders** [comment]
To summarize here: 

- For RC: Implement word *and* PDF option. Currently the word doc is the only optin

- For OLC: Implement PDF option only

**Comment by anjesh** [comment]
Created new issue here https://github.com/NRGI/resourcecontracts.org/issues/674 to show the word doc if the show-text option is set to on. Do let us know if OLC is to implement only PDF, even if the OCR text is good and verified.

**Comment by KaitlinCCSI** [comment]
Thanks, Anjesh. For OLC, we only want to provide the option to download PDFs, not word docs.
