### ISSUE TITLE
Contracts footer interupts search results

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#594]
On the contracts page, if you scroll down, the dark grey footer is not rooted to the bottom of the display. Instead it covers some of the search results. Same problem when you click on a resource on the metadata column of any contract view page (see screenshot #2). The problem doesn't occur on the main text search page.
http://www.openlandcontracts.org/countries/et
![screen shot 2015-10-26 at 3 52 30 pm](https://cloud.githubusercontent.com/assets/12913915/10740649/ad00e75e-7bf9-11e5-8e03-f17669ddfcae.png)

http://www.openlandcontracts.org/resource/Oil%20palm%20or%20palm%20oils
![screen shot 2015-10-26 at 3 55 17 pm](https://cloud.githubusercontent.com/assets/12913915/10740713/0bc34ad4-7bfa-11e5-828a-08d29eb3214e.png)

**Comment by anjesh** [comment]
Which browser/version are you using? 
Both these pages are fine in my chrome Version 46.0.2490.80 (64-bit), Safari Version 8.0 (10600.1.25) and firefox 38.0.5.

**Comment by SamCCSI** [comment]
Chrome Version 45.0.2454.101 (64-bit) on Mac

On Mon, Oct 26, 2015 at 4:54 PM, Anjesh <notifications@github.com> wrote:

> Which browser/version are you using?
> Both these pages are fine in my chrome Version 46.0.2490.80 (64-bit),
> Safari Version 8.0 (10600.1.25) and firefox 38.0.5.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/594#issuecomment-151282114>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by sadhakbj** [comment]
![594](https://cloud.githubusercontent.com/assets/5828622/10964456/52c553d2-83cf-11e5-971e-80348a4ef8b2.png) done
