### ISSUE TITLE
Contract missing from batch upload

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#595]
The following contract was included on the google spreadsheet for the Sep 18 batch upload of OLC contracts but does not appear on the site. It appears at row 51. Google spreadsheet is here: https://docs.google.com/spreadsheets/d/13HFzsddfT9OkeAmtHLtwzpl2QP-IHaYxP8wB8adUljg/edit?usp=sharing

The contract:
DRC, Industrie de Transformation de Bois, Contrat de concession forestière N. 006, 4 août 2011	Industrie de Transformation de Bois 	https://www.dropbox.com/s/8brlbx9f3nh8qkm/ITB_Contract%20006_2011.pdf	https://www.dropbox.com/s/zpi6zm60p3r5jjz/Industrie%20de%20Transformation%20des%20Bois_DRC_006.xlsx	

The site:
http://www.openlandcontracts.org/search?q=&company_name%5B%5D=Industrie+de+Transformation+de+Bois

It's possible that it was overlooked because it was preceded by a contract of the same name, but that is contract No. 5, whereas the missing contract is No. 6.

Could you please provide an update for us on this one?

Thanks,
Sam

**Comment by anjesh** [comment]
I see both the contracts here http://resourcecontracts.elasticbeanstalk.com/contract?year=all&country=all&category=all&resource=all&q=DRC%2C+Industrie+de+Transformation+de+Bois
6 one is not published.

**Comment by SamCCSI** [comment]
Many thanks for the quick reply, Anjesh.

Not sure why it wasn't published - I have published it now, bringing our contract tally up to 70.
