### ISSUE TITLE
Mechanical Turk overview page: Add highlighted column for: "Need approval"

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#597]
![image](https://cloud.githubusercontent.com/assets/1101585/10758752/02e50856-7c79-11e5-8484-09798b783bb6.png)

**Comment by anderspeders** [comment]
I am missing the *one column* that can highlight contracts where I need to take an action - approve or reject.

**Comment by anjesh** [comment]
This has been fixed long back

![image](https://cloud.githubusercontent.com/assets/120488/12352062/d9022566-bbaa-11e5-8585-e28be21d3b1b.png)
