### ISSUE TITLE
Change "Related docs" to "Associated Documents" in contract view page

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#599]
Can you please change "Related docs" to "Associated Documents" in contract view page? Both words should have first letter capitalized.

Font needs to be same color (Grey) as other entries on metadata column, rather than black at present.

http://resourcecontracts.elasticbeanstalk.com/contract/1345

I have unpublished it now. The PDF didn't show up only because I didn't publish it.

![image](https://cloud.githubusercontent.com/assets/12913915/10763181/4d7a52f6-7c9f-11e5-8f63-f8d1375a67c2.png)

**Comment by anjesh** [comment]
Label changed.
