### ISSUE TITLE
Database/framework setup

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#6]
This should include version control on github, automated testing through shipable, and deployment through elastic beanstalk.

**Comment by anjesh** [comment]
See #19 and #24 for defining the structure

**Comment by byndcivilization** [comment]
This isn't really about db structure. Rather we're hoping for a continuous deployment model that runs through testing and if possible we'd like to run this as an elastic beanstalk app. That gives us nice low headache infrastructure management as well as autoscaling, etc. Also we're hosting a lot of our db work on compose.io to minimize the admin headaches around db hosting. Ive got a postgres account set up if you want access.

**Comment by anjesh** [comment]
Lets do the db-hosting in compose.io in sprint 2. Do send us the account info.

**Comment by anjesh** [comment]
Shippable, eb-deploy setup. There's some permission issue with the deploy, sysadmin has to manually run one bash script in the server, which couldn't get executed by eb-deploy. 

@byndcivilization Need the AWS account with good spec for the setup and deployment. Currently we are using the low-end/low-cost AWS server for testing. Perhaps also compose.io for next sprint.

**Comment by anjesh** [comment]
Done for the sprint 1 and followup #68 for sprint 2

**Comment by byndcivilization** [comment]
On EB specs, I'd just go with a micro/autoscale instance behind load balancer. Default scales up to 4 server nodes max which should be more than enough for the time being. If we start to getting serious traffic we can think about adding nodes or upping server specs.
