### ISSUE TITLE
Add information fields to post-OCR contract view

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#60]
Add the following fields: 
- OCR status: Processed / not processed
- Created by: [User]
- Last modified by: [User]

Change: 
- **View pages** to **Review processed contract text** (or something similar)
- **Annotate** to **Annotate contract** 

![contract post-ocr status](https://cloud.githubusercontent.com/assets/1101585/8162496/9e2cdb28-134b-11e5-8f06-5a53fde81355.png)

**Comment by anjesh** [comment]
@manish707

**Comment by anjesh** [comment]
"OCR status" will only apply for scanned ones, right? That means for the structured one, we don't need this option. That is system generated one. If the pdf-processing works, then it will get "processed" status. Correct? clarifying.

**Comment by byndcivilization** [comment]
yes.

**Comment by anjesh** [comment]
Updated.
