### ISSUE TITLE
Footer missing from bottom of all contracts page

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#601]
![screen shot 2015-10-27 at 1 55 07 pm](https://cloud.githubusercontent.com/assets/14825437/10769253/0ec77d54-7cb3-11e5-8a90-e8b6d19944fa.png)

**Comment by anjesh** [comment]
I am seeing the footer. Are others also having this problem?

**Comment by KaitlinCCSI** [comment]
Okay, I now see the footer as well. Not sure what changed, as I'm using the
same computer and browser.

On Tue, Oct 27, 2015 at 10:55 PM, Anjesh <notifications@github.com> wrote:

> I am seeing the footer. Are others also having this problem?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/601#issuecomment-151715181>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PyrTsM5&m=f5178f4d7ec3&t=20151027&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PyrTsM5&m=f5178f4d7ec3&t=20151027&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01PyrTsM5&m=f5178f4d7ec3&t=20151027&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>
