### ISSUE TITLE
Search filter on back-end contract page not picking up words that are present

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#602]
See screenshot - searching for a word which is there, but it still says that there are no results.
http://resourcecontracts.elasticbeanstalk.com/contract/132/review#/search/TRITON

Search works fine on the front-end. http://www.resourcecontracts.org/contract/ocds-591adf-GQ6043586295RC/view#/search/triton

This is important for annotators and reviewers of annotations and metadata - allows us to quickly identify the sources of metadata entries and confirm they are accurate.

![screen shot 2015-10-27 at 4 32 48 pm](https://cloud.githubusercontent.com/assets/12913915/10771677/6f958d46-7cc8-11e5-9318-dc008f588dec.png)

**Comment by SamCCSI** [comment]
second  URL above edited - previous one was incorrect

**Comment by hello-deepak** [comment]
Its working fine in resourcecontracts-admin search .

![search](https://cloud.githubusercontent.com/assets/7577697/10989971/1e17f3b8-8476-11e5-8d39-35beaad195c9.png)

**Comment by SamCCSI** [comment]
Working for me now, too. Not sure what changed.
