### ISSUE TITLE
Add / displaying associated documents without having them appear in contract number tally

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#603]
We will be adding some "associated documents" and possibly other documents to OLC that are not contracts, but publicly disclosed relevant documents. 

Set out below is a short term and a long term solution. After that is more information about the types of non-contractual documents we will be adding.

------
Short term solution
------
We need to be able to add associated documents without them being counted in the contract tally.

For now, we propose that the following is built in to enable this:
1 - Uploader identifies on the back-end whether the document is a contract or is an associated document.
2 - Documents identified as not a contract should not be included in the tally (currently 70 contracts) AND should not appear on the all contracts page (http://www.openlandcontracts.org/contracts) but should appear on the advanced search page where there is no search term or filters (http://www.openlandcontracts.org/search?q= )

------
Long term solution
------
We propose that:
1.	We have the option on the backend to say whether a document should be counted as a contract or not 
2.	The advanced search page would list all the documents. The "all documents view" would be sorted so that all contracts listed first, followed by other documents. Spearated  by a horizontal line break that either has no text, or has text indicating that below are associated documents, and not the contracts themselves. (See screenshot) 
3.	There would be 2 tallies: tally of all contracts, and tally of all associated documents (though might have to call this something else if we include AIM summaries here).  
4.	Ideally would include an option to search (i) all contracts, (ii) all associated documents, or (iii) all documents (contracts and non-contracts).  
5.	we would associate with the parent contract as we are already able to do, so a user would see the parent doc listed in the right-hand column; and when looking at the parent doc, would see the associated doc listed in the right-hand column

See screenshot:
![screenshot pink](https://cloud.githubusercontent.com/assets/12913915/10772258/9237aba6-7ccb-11e5-8125-b1991c461948.png)

-----
More information about the types of non-contractual documents we will be adding
-----

For associated documents, we currently have:
•	Forest management plans (not contracts but sometimes have additional contracts embedded within them) 
•	Social agreements (appear to be contracts between the investor and the community) •	Annexes to contracts  
•	Original contracts that are not in French or English (example: Amharic language contracts that have translated into English - we are annotating the non-official English versions) 
•	Amendments to contracts (these will be annotated because they change the contractual agreement itself; we are not annotating other related documents, at least for now).

For other relevant documents, we have:  
•	Summaries of provisions of material contracts filed with London Stock Exchange. These are legally required to be correct summaries. Currently when we publish anything as a document on the site, even as an associated document, it is counted in the contract tally. 

Some of these documents are not contracts, so it is misleading and not accurate.

**Comment by KaitlinCCSI** [comment]
Note that this is also relevant for RC; particularly the ability to identify whether a document is a contract or not. A number of RC contracts may have associated documents, not all of which will be contracts.

**Comment by anderspeders** [comment]
From this we can implement the addition of Type fo Document to the search bar. 

As for the additional bubble in the right side. Is it a good idea to present multiple numbers to the user? I think I would prefer to rephrase the language currently displayed and thus avoid adding another bubble while still projecting factually correct information.

**Comment by jedm** [comment]
Strongly agree with @anderspeders

**Comment by KaitlinCCSI** [comment]
Okay, we are working on rules that would allow us to have an accurate contract tally that would be the sole tally provided, label documents correctly, and not double-count, but it's complicated and taking us a bit of time, particularly since we've been told that we need to do this without having ability to manually adjust when something is counted/not counted for tally. Will send proposal via email when ready. cc @SamCCSI

**Comment by charlesyoung** [comment]
@anderspeders @SamCCSI @KaitlinCCSI what is the latest re this ticket?

**Comment by SamCCSI** [comment]
I think this thread can be closed.
- The original post on this thread has been superseded by our proposal document for contract tallies and associated documents.
- The Doc Type search filter has been added.
- We will only have one circle with one tally, but it should read "Documents," not "Contracts" as mentioned in another thread today.

**Comment by anjesh** [comment]
closing.
