### ISSUE TITLE
FAQ page format 

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#604]
The FAQ page is not easy for the user to navigate (as a lot of info is contained in the page) - can we include something similar to the Land Matrix FAQ page (link and screenshots below), in particular: 
- Tabs on right hand side of page can be clicked on in order to take you directly to the relevant question 
- As you scroll down the questions, the relevant question title is highlighted in orange on the right hand side 
- Text spreads more broadly across page rather than appearing in a narrow column in center of page (this comment is relevant for all 'text' pages - About, Publish Contracts, etc.)
  
  http://www.landmatrix.org/en/about/ 

![screen shot 2015-10-27 at 22 07 03](https://cloud.githubusercontent.com/assets/14910764/10777968/61a7b5fe-7cf7-11e5-97cf-8260292fed80.png)

![screen shot 2015-10-27 at 22 07 14](https://cloud.githubusercontent.com/assets/14910764/10777973/68adb3c6-7cf7-11e5-92f9-c8edfda40398.png)

**Comment by charlesyoung** [comment]
@JesseCCSI is this still required?

**Comment by KaitlinCCSI** [comment]
I think it's preferable. There is so much info packed on the FAQ pages that it's pretty hard for users to find what they need -- http://www.resourcecontracts.org/faqs. (As seen in this exchange, where answer was in FAQs but our own team didn't know! https://github.com/NRGI/resourcecontracts.org/issues/1005)

**Comment by manishgs** [comment]
There are two options to obtain the design of FAQ page as shown in above screenshot, 

**1. Edit on existing text editor**
User have to update text in defined style which means Title should be wrap with `<h2>` tag and description text should wrap with `<div>` tag. Below is the html structure of FAQ page look like:

```
<h2>What is OpenLandContracts.org? </h2>
<div>OpenLandContracts.org serves as the first online, searchable, and user-friendly repository of publicly available contracts for large-scale land, agriculture, and forestry projects. <div>

<h2>Who are the partners contributing to the site? </h2>
<p>OpenLandContracts.org is an initiative of the Columbia Center on Sustainable Investment (CCSI), a joint center of the Earth Institute and Columbia Law School at Columbia University. It is a sister site to ResourceContracts.org, an online repository of oil, gas, and mining contracts created by the Natural Resource Governance Institute, the World Bank, and CCSI. The project is supported by UKaid from the Department for International Development. </p>
```
....

It can be implement on existing functionality and quick to implement. but user have to know basics of html and need to edit text from source code of editor. As the page depend on html tag structure if there is mistake on html tag then page will not show as expected.

**2. CMS for FAQ page**
We'll create new feature to add multiple title and descriptions of FAQ.

Admin can add/update FAQ content easily and implementing design will be easier for us as well but
It will take time to add this functionality

@JesseCCSI @charlesyoung 
Let us know your thoughts?

**Comment by charlesyoung** [comment]
@manishgs we have budgetary constraints so need to implement option 1.

**Comment by manishgs** [comment]
@charlesyoung @JesseCCSI 

Option one has been implemented. Please review on [staging](http://staging.resourcecontracts.org/faqs)

**Note**
To make title appear on the left navigation, Question Title text should be in bold (i.e wrap with <strong> tag).

**Comment by JesseCCSI** [comment]
Thanks @manishgs this looks good - one question regarding the bullet lists - the alignment appears slightly off (see screenshot below). Is there a way to rectify this? Thanks. 

![image](https://cloud.githubusercontent.com/assets/14910764/23365651/cdbd45d2-fcd1-11e6-8c69-b63a8e32c2b5.png)

**Comment by manishgs** [comment]
Numbering is based of the title, if title doesnot contain number then it will not display on the left navigation menu. In OLC site FAQ titles doesn't contain number so it will not display on the nav menu.

Alignment is fixed. Please review FAQs page on [RC](http://staging.resourcecontracts.org/faqs) and [OLC](http://staging.openlandcontracts.org/faqs) and let us know if we are ready to deploy on live

**Comment by JesseCCSI** [comment]
Just reviewed OLC and this is working well, many thanks @manishgs  - also working nicely on mobile. 
Cc'ing @charlesyoung in case you have further comments re RC?

**Comment by JesseCCSI** [comment]
Hi @manishgs @charlesyoung re-opening this ticket as it looks like there are some issues with the FAQ page on the live site: 

1. The table of contents appears different to the version on the staging site, which scrolled and was a more distinct box (grey versus white). 
2. The alignment of the page is different - the FAQ should all be in one column, and not wrap around the FAQ table of contents. 
3. The alignment of the bullets is off. 
4. The questions listed in the OLC FAQ do not highlight when you click on them, nor do the corresponding titles of the FAQs. 

Note that the same issues do not appear on the live RC.org page. 

Thanks for addressing the above.

**Comment by manishgs** [comment]
FAQ page working fine for me. Could you please clear browser cache and retry?
![screenshot-www openlandcontracts org 2017-03-03 10-12-47](https://cloud.githubusercontent.com/assets/3942999/23538250/046a1af8-fffa-11e6-8916-2acfc04a67fa.png)

**Comment by JesseCCSI** [comment]
Many thanks @manishgs cleared my browser cache and this is working now. One small issue I noticed in the scrolling table of contents - there seems to be an extra space between question 25 and 26. Could this be removed? Thanks again. 

![image](https://cloud.githubusercontent.com/assets/14910764/23555770/2db3b4ca-fff8-11e6-9a5b-632316af0b98.png)

**Comment by manishgs** [comment]
fixed.
