### ISSUE TITLE
Space for brief description of document on contract view page

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#605]
Can we include a space for annotators to include a free text description (1-2 lines) of a contract/ associated document on the document view page? E.g. "This is a translated version of Contract X" or "This is a summary filed with the securities exchange". 

Have included a suggestion re placing in screenshot below, but defer to @KaitlinCCSI @SamCCSI who may also have suggestions about the location of the description box. 

If the description is placed above the metadata in the right hand column, we need to ensure that the format of the description is kept distinct (so it doesn't get lost with the rest of the information in that column). 

![screen shot 2015-10-27 at 22 12 05](https://cloud.githubusercontent.com/assets/14910764/10778063/3178d498-7cf8-11e5-9565-e18ac1a22abe.png)

**Comment by anjesh** [comment]
We will have the new metadata field "Note" in the admin, which will be then reflected in the subsite after publishing.

**Comment by anjesh** [comment]
Just in the case the note value gets long, we will show ellipsis for show more.

**Comment by SamCCSI** [comment]
Thanks Anjesh.

Would it be difficult to include the free text field that would appear above the metadata column as indicated in Jesse's mock-up?

I think that's important, as it should be obvious to the user so that they read it before exploring the contract.

Happy to discuss if needed.

Thanks,
Sam

**Comment by KaitlinCCSI** [comment]
Thanks for including this. If possible, can we hide this when there is no data entered?
![screen shot 2015-11-24 at 1 04 40 pm](https://cloud.githubusercontent.com/assets/14825437/11377552/09a9573e-92ac-11e5-843d-f32c7dfc5954.png)
![screen shot 2015-11-24 at 1 02 33 pm](https://cloud.githubusercontent.com/assets/14825437/11377551/09a9604e-92ac-11e5-86c5-17c803d62ea7.png)

**Comment by sadhakbj** [comment]
![605-note](https://cloud.githubusercontent.com/assets/5828622/11392697/76dfd576-9383-11e5-95fe-c8dd579d89db.png)
![605-summary](https://cloud.githubusercontent.com/assets/5828622/11392745/b360c8ac-9383-11e5-8e94-1e7ad2075015.png)
If contract note is present in the metadata the above view will be seen. (Pic: as tested with our local data)
- done

**Comment by anderspeders** [comment]
@anjesh Just to reaffirm that this will be developed so that the schema works with the "description" field in the Open Contracting Data Standard: http://ocds.open-contracting.org/standard/r/1__0__0/en/schema/reference/#contract

@charlesyoung: This also means that we should ensure that the admin guide provides the correct guidance on this.

**Comment by anjesh** [comment]
Also need to use ellipsis (...) in the contract view page if the desc text is more than 3 lines.

**Comment by charlesyoung** [comment]
Can we keep to the site look at feel and make the note text bold. 

![image](https://cloud.githubusercontent.com/assets/13888372/11420122/ab0d015a-9434-11e5-889b-cb0d31c01ce3.png)

![image](https://cloud.githubusercontent.com/assets/13888372/11420151/e7d7aa90-9434-11e5-8230-d3f987b1bc32.png)

**Comment by jpmckinney** [comment]
@anderspeders I don't think the note field matches the semantics of OCDS' description field. The note field is also being used to flag a contract as being incomplete (#143). The semantics of this field are more along the lines of a comment than along the lines of a description.

**Comment by sadhakbj** [comment]
Now the contract view page has a space for Contract Note which appears only if contract note exists for a particular contract. We have added ellipsis (...) in the contract view page.

(Image below: from demo site)

![show_more](https://cloud.githubusercontent.com/assets/5828622/12776094/464be25e-ca7b-11e5-9d18-50b5addaa19e.png)
