### ISSUE TITLE
Land Matrix deal numbers - include on contract view page

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#606]
Can we include a space in the right hand column of the contract view page , underneath the Metadata, for inclusion of Land Matrix deal numbers? Suggestion would be to include a field titled "Land Matrix ID" or "Land Matrix Deal Number", and then annotators could include the number (or perhaps there is a way for this to be auto-populated from the Land Matrix site). 

![screen shot 2015-10-27 at 22 21 29](https://cloud.githubusercontent.com/assets/14910764/10778244/5f3e5338-7cfa-11e5-9990-5b8fff37eabf.png)

![screen shot 2015-10-27 at 22 21 16](https://cloud.githubusercontent.com/assets/14910764/10778274/b0aa592e-7cfa-11e5-9476-b94fb8463f33.png)

![screen shot 2015-10-27 at 22 20 06](https://cloud.githubusercontent.com/assets/14910764/10778276/b430afa8-7cfa-11e5-8f9a-f4c40db07de6.png)

When this is included, if we don't have a deal number to include or want to temporarily hide the number, will it be possible to hide this field from contract view page?

**Comment by KaitlinCCSI** [comment]
This is for OLC only. Deal number should be hyperlinked to specific deal within Land Matrix (example: http://www.landmatrix.org/en/get-the-detail/by-target-country/cambodia/11/).

**Comment by anderspeders** [comment]
This cannot be autopopulated but CCSI staff can add it manually as a metadata field. 

"Link to deal in landmatrix": [INSERT LINK]

**Comment by JesseCCSI** [comment]
Hi @anderspeders - just to clarify, we'll need to include the actual Deal number (e.g. Deal # 13) and hyperlink the deal number to the relevant Land Matrix page.

**Comment by KaitlinCCSI** [comment]
To save space, it could actually be one line on the frontend: "Land Matrix Deal #[X]", with "Deal #[X]" hyperlinked to a link that we manually add.

**Comment by anjesh** [comment]
We will have the Deal Number and Land Matrix Page in the contract page with the instruction that "This is applicable for OLC contracts only".

**Comment by KaitlinCCSI** [comment]
Thanks for this. On the Summary Page, could you please capitalize the "d" in "ID" for the Land Matrix field, so that it matches the spelling on the Contract View page? (Should read "Land Matrix ID").
![screen shot 2015-11-24 at 1 14 46 pm](https://cloud.githubusercontent.com/assets/14825437/11377812/94af98c4-92ad-11e5-9466-863634f0529a.png)

**Comment by sadhakbj** [comment]
Fixed

**Comment by KaitlinCCSI** [comment]
No, the "d" has not been capitalized yet. Summary page needs to have "Land Matrix ID", not "Land Matrix Id"

**Comment by sadhakbj** [comment]
![606_id](https://cloud.githubusercontent.com/assets/5828622/11434265/ce949148-94f1-11e5-85dd-5c7df3996e7b.png)
- Fixed
