### ISSUE TITLE
Hostin of documentation: Read the Docs?

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#61]
https://readthedocs.org/projects/resourcecontracts/

The documentation should be: 
- easy to embed/host on RC.org website
- easy to edit / manage

@byndcivilization let me know what you think?

**Comment by byndcivilization** [comment]
yes on edit manage, probably not so much on embed host on rc.org site. It's pretty common to either host it on something like read the docs or on github itself. And honestly most users won't care terribly much about the software documentation i think.

**Comment by anderspeders** [comment]
Sounds good, 

Github it is.
