### ISSUE TITLE
RC - contracts with no country assigned

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#611]
When you go to the all contracts page and sort contracts by country, there are several that do not have a country entered into their metadata. http://www.resourcecontracts.org/search?q=&order=asc&sortby=country

See screenshot. 

Also when I click on any of these, it takes me to the 404 error page. Not sure why @anjesh ?

@charlesyoung @anderspeders : Country needs to be added and metadata likely needs to be reviewed for these ones - I think they might come from Guinea. 

Thanks all.

![screen shot 2015-10-27 at 4 17 27 pm](https://cloud.githubusercontent.com/assets/12913915/10789041/7df217ea-7d51-11e5-8aec-48834e03e2c5.png)

**Comment by charlesyoung** [comment]
Agreed. This relates to case 'Highlight / asterisk required fields in metadata upload form' #59

Can you pls confirm that the 4 contracts are from Guinea so that I can update accordingly.

**Comment by SamCCSI** [comment]
Thanks Charles.

I've googled the title for each and it comes up as coming from the Guinea country specific site, which aligns with Perrine's suspicions, so I think we can confirm. I can't actually acess the document to check because of the error message.

One note: these appear to be 3 decrees and one mining code amendment, so not technically contracts.

**Comment by charlesyoung** [comment]
Thanks Sam. Should we load these docs into RC if not contracts?

**Comment by KaitlinCCSI** [comment]
Also relates to #603 and #610. I think RC needs a clear policy on what is included, what is not, and, of those included, what is considered a contract for the tally. OLC will do the same.

**Comment by charlesyoung** [comment]
Should I delete the 4 mentioned documents? 

@KaitlinCCSI I agree that we need a policy but I would think that decrees and mining codes shouldn't be uploaded as it presents a misleading picture, like annexes, of the number of actual contracts uploaded.

**Comment by SamCCSI** [comment]
Thanks Charles.

Perrine advises that these are to be marked as Associated Documents for each contract that is subject to each decree / code. This info can be found on the http://www.contratsminiersguinee.org/ site. Apparently it is listed for each contract and would not involve you having to actually read any PDF documents themselves.

@charlesyoung can you see if this info is readily accessible to you on the site? If not, we can find a French speaker to investigate further. Thanks again.

**Comment by charlesyoung** [comment]
@SamCCSI I added the country (Guinea) to the four docs. 

@anderspeders how do we move forward on defining a policy on what documents should be included or not as @KaitlinCCSI mentioned?

**Comment by anderspeders** [comment]
These documents where specific requirements for the pilot site in Guinea. The missing country name must have been an import error.
