### ISSUE TITLE
Add number for each search category in brackets ( )

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#612]
![image](https://cloud.githubusercontent.com/assets/1101585/10793483/b19035aa-7d56-11e5-8eac-3d286fabae0c.png)

**Comment by KaitlinCCSI** [comment]
Is this necessary? What's the user need for this? Think it will look messy, and I'm not sure whom it would help.

**Comment by anjesh** [comment]
Please reopen for discussion if needed.
