### ISSUE TITLE
OCDS review to RC metadata

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#613]
Addition:
initiation.type: 
- classes: CompetetiveProcess, NoncompetitiveProcess

Add: PublishingGroup

**Comment by jpmckinney** [comment]
Are these real suggestions for addition, or just ideas? If just ideas, I would favor closing this issue and just having #614

**Comment by anjesh** [comment]
I agree. Discussion here https://github.com/NRGI/resourcecontracts.org/issues/614
