### ISSUE TITLE
Granular admin module security 

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#615]
How do the current admin module user roles function? 

Can roles be used to restrict users in adding contracts? I would assume that the Philippines RC site managers wouldn't want anyone else adding contracts for the Philippines but themselves and this will be the case going forward with more country site implementations.  

![image](https://cloud.githubusercontent.com/assets/13888372/10819648/e8dd7274-7e51-11e5-937a-840ac764cc96.png)

**Comment by anjesh** [comment]
The country admin is for that purpose. The user with country-admin role only sees the contracts from that country and can add contract to that country only.

**Comment by charlesyoung** [comment]
Perfect, thanks. .
