### ISSUE TITLE
contract view page > "See Summary" button out of place

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#616]
On the contract view page, the "see summary" button is not in line with "metadata" (see screenshot below) in the right hand metadata column. I'm using Chrome on a PC (not having this issue when using Chrome on a Mac) 

![image](https://cloud.githubusercontent.com/assets/14910764/10832985/1c2b80ae-7e65-11e5-94a2-0b76e9c1a9db.png)

**Comment by jedm** [comment]
Best would be to have the See Summary link on right and All Annotations link on left in same place in their respective columns.

**Comment by sadhakbj** [comment]
/home/bijayananda/Desktop/616.png

**Comment by sadhakbj** [comment]
![616](https://cloud.githubusercontent.com/assets/5828622/10964412/1afa001a-83cf-11e5-9b4f-2687bfdb57b8.png) done
