### ISSUE TITLE
Editing text on the About/ FAQ/ etc pages

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#619]
Colors available in editing palette: 
The choice of colors that you can apply to text doesn't include the same green used throughout the site - you can only pick either a lighter or darker green. For consistency, can we please have the option to use the same green?

Editing box, editing tool bar, and save/ cancel buttons: 
When adding, editing, or formatting text, you have to scroll back and forth to the top of the editing box in order to select particular tools or to save the changes you have made (as the entire page scrolls rather than just the text in the editing box). If you accidentally click out of the editing box, you lose the changes. The editing box is also very narrow, making the scrolling back and forth even more time consuming (and also making it easy to accidentally click outside the editing box). [see screenshots below]

Is there a way to:

1. make the editing box wider?;
2. have a floating tool bar (including the save and cancel buttons) that follows you as you scroll to particular parts of the text? Alternative to this option could be to make sure that when you scroll, you just scroll down/ up through the text in the editing box (rather than having the entire page scroll, which is what happens now).

![editing tools](https://cloud.githubusercontent.com/assets/14910764/10856142/f268ec18-7f1b-11e5-9d48-7a94cc6b07ba.png)

![scrolling](https://cloud.githubusercontent.com/assets/14910764/10856155/1a7a9800-7f1c-11e5-8ca1-09783b50d9d6.png)

Editing tools
The available editing tools appear quite limited - for example, the following tools are missing:

1. ability to hyperlink a thumbnail without needing HTML knowledge (related to issue #483)
2. ability to move a thumbnail around the page and easily include alongside text rather than above/ below (related to issue # 483)
3. ability to insert media other than JPEGs (e.g. videos)
4. editing options for tables that we insert
5. option to include different styles of bullet points / lists

Is there a way to build such additional editing tools in?

Many thanks.

**Comment by anjesh** [comment]
We have updated the editor now and also the process of updating the content. 
You will see the list of content pages when you login

![image](https://cloud.githubusercontent.com/assets/120488/11177615/d1b67d7c-8c6e-11e5-8016-38fc949cd375.png)

And edit will show a new editor with more options - which cover all the points you have listed above.

**Comment by JesseCCSI** [comment]
Many thanks @anjesh - the updated editor (incl. the preview function) is very helpful! 

I think the only unresolved issue from above is re the color - it still seems that the green color used throughout the site isn't available in the editor?

**Comment by anjesh** [comment]
We will see if there's some kind of color palette plugin for this editor where you can choose the color by code.
cc @manishgs

**Comment by JesseCCSI** [comment]
Thanks @anjesh - I don't think this is a major priority, but it would be good for consistency.

**Comment by JesseCCSI** [comment]
Hi @anjesh I noticed that the new editor has a spellcheck option under tools, but when I try to use it an error appears ("Spellchecker request error: 404"). 

Re the color palette issue above, no need to spend more time looking for a plugin, as it's not a priority.

**Comment by anjesh** [comment]
Created a new issue for spell check bug https://github.com/NRGI/resourcecontracts.org/issues/691
