### ISSUE TITLE
Search results > Include a "view all" option at end of page

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#621]
Might be useful for those who wish to see the full list of search results rather than have them be split across multiple pages. Could include beside "Next" and "Last" at end of page, in the same format as the Next/ Last buttons. 

![screen shot 2015-10-30 at 15 45 17](https://cloud.githubusercontent.com/assets/14910764/10856320/63e1ee0c-7f1d-11e5-8e8c-13f4ab737e4d.png)

**Comment by anjesh** [comment]
In RC, there are now 888 contracts. Loading of all contracts in a single page will be resource consuming. Need to discuss on this.

**Comment by anderspeders** [comment]
@JesseCCSI Currently a full download option is available, which would address this. 

I suggest that we wait dealing with this until we have fixed some of the core priorities.

**Comment by JesseCCSI** [comment]
Thanks @anderspeders -- I'm not sure that the full download option fully addresses this, but I understand that other priorities are more urgent.

**Comment by hello-deepak** [comment]
View all button is added in  search page pagination.

![openlandcontracts org search contracts](https://cloud.githubusercontent.com/assets/7577697/17433851/bb535e60-5b26-11e6-9c72-8b4a679a5f5a.png)

**Comment by JesseCCSI** [comment]
Great, thank you @hello-deepak
