### ISSUE TITLE
Page count not updated when new PDF is uploaded 

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#622]
Re this contract: http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/1154/view#/pdf/page/13/annotation/22853

We uploaded a new PDF with 13 pages (per issue #574 ) which replaced an incorrect document that had 14 pages.
The new PDF is now displaying on the site, but the page count at the top of the PDF on the contract view page still reads 14 pages. When you go to the 14th page, there is no PDF page, just a message that says "loading".

![screen shot 2015-10-30 at 15 53 45](https://cloud.githubusercontent.com/assets/14910764/10856507/8ec7a0ca-7f1e-11e5-8e21-215f48e5ed60.png)

1. Can the PDF page count please be fixed?
2. How do we avoid this in the future?

We need to replace the PDF for two other contracts (http://rc-site-stage.elasticbeanstalk.com/olc/public/contract/1155/view#/pdf/page/12/annotation/22908 and http://www.openlandcontracts.org/contract/ocds-591adf-LR8570774189OL/view#/pdf/page/97/annotation/23705), so we need to know how to avoid this.

**Comment by anjesh** [comment]
When the pdf gets replaced, pages are replaced with newly uploaded pdf pages. However the page count of the previous pdf page is included in the metadata so it's still showing up the previous page count. You have to re-publish the metadata after uploading the pdf to reflect the page count in the subsite.

**Comment by anjesh** [comment]
We will show the following message when the new pdf is uploaded
"If your newly uploaded pdf has different page count than the existing one, you need to republish to fix the page count in the subsite."

**Comment by JesseCCSI** [comment]
Thanks @anjesh, I'll test this and let you know if we have any problems. 

In the message that you add, it might be useful to include: "Ensure that your newly uploaded PDF is processed before re-publishing the metadata and annotations." (You mentioned this in #574 )

**Comment by anjesh** [comment]
Please re-open if you still have any problem here.
