### ISSUE TITLE
Company website URL as metadata

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#623]
Include the company website URL as a metadata field. 

[Requested by PH-EITI]

**Comment by anderspeders** [comment]
Does this appear in the OCDS @jpmckinney @anjesh ?

**Comment by jpmckinney** [comment]
There's a `url` for the [ContactPoint](http://ocds.open-contracting.org/standard/r/1__0__0/en/schema/reference/#contactpoint), but not for the organization in general.

**Comment by manishgs** [comment]
@charlesyoung 
Can we add website url after Company name?

![screenshot-admin resourcecontracts org 2016-10-20 14-18-19](https://cloud.githubusercontent.com/assets/3942999/19552748/e36e5f4a-96d0-11e6-8ac1-6c5c8785c9f5.png)

Todos :

- [ ] Add new field "website url" after company name

- [ ] update metadata of existing contracts

- [ ] Index all in elastic search

- [ ] update api  (participation->company->website_url)

- [ ] update on frontend

**Comment by charlesyoung** [comment]
@manishgs I've moved this to an unscheduled Sprint because it will first require Group discussion and agreement.
