### ISSUE TITLE
Process for uploading Supporting document 

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#624]
Supporting document needs to be treated separately because it shares several metadata from the parent. We will be following the following process for uploading and handling supporting document in the system. 

Assumption: One document can be supporting document to only one parent. 

There will be "Add Contract" button as it is now. Clicking will show two buttons "Add Main Contract" and "Add Supporting document" as follows.

----
![image](https://cloud.githubusercontent.com/assets/120488/10903903/c3c5ac16-8236-11e5-9a36-24750a7683f1.png)
---

Clicking on the "Main Contract" will open up existing contract create page with blank fields, as it is now. 

Clicking on the "Supporting document" will first show the list of contracts to select the parent contract for this supporting document. All the supporting documents will be hidden from the list (see assumption). 

### Create new supporting document

----
![image](https://cloud.githubusercontent.com/assets/120488/10903922/075ee208-8237-11e5-9c21-b1caddc647a5.png)
---

After selecting parent contract, clicking "Next" will show a form with all the values imported from the parent contract. New field is added here "is supporting document", which is used to remove the supporting document tag from the document, in case of mistake. Also this field is used to associate the already uploaded contract as supporting document. 

----
![image](https://cloud.githubusercontent.com/assets/120488/10903942/44924688-8237-11e5-9288-bc0b08f12b3c.png)
---

Saving here will generate OCID for the supporting document as ```OCID-of-parent-contract + release-id```. Here we will take system generated document-id as release id. See https://github.com/NRGI/resourcecontracts.org/issues/583 

### Change parent contract of supporting document

Edit the particular supporting document and change the parent contract from the drop down. New OCID will be generated for the supporting document as per newly assigned parent contract.

----
![image](https://cloud.githubusercontent.com/assets/120488/10904034/ff646856-8237-11e5-8a60-d7dff99dfe47.png)
---

### Treat supporting document as main contract

Edit the particular supporting document and toggle the "Is supporting document" radio button. New OCID will be generated for this document as per OCID generation rule. This document can now act as main contract and may have supporting documents. 

![image](https://cloud.githubusercontent.com/assets/120488/10904063/37bafd28-8238-11e5-909b-1677402a0b4f.png)

### Parent contract view

In Parent contract view, we can see the list of supporting documents. These supporting documents could be removed from the parent contract by going to individual supporting document page by clicking on that link. The reason to take the individual supporting document page is when the supporting document is removed, we need to generate new OCID for each of these documents. 

![image](https://cloud.githubusercontent.com/assets/120488/10904130/c6047578-8238-11e5-9744-57e834246393.png)

**Comment by anjesh** [comment]
We also need to go through the existing contracts metadata in the database to fix the "Is supporting document" fields for the contracts that are already tagged as supporting document.

**Comment by SamCCSI** [comment]
Thanks Anjesh, this looks great.

1. Can we change “supporting document” to “Associated Document” for consistency?

2. What if we only have the associated document, and don’t have the main contract? We may still want to upload it, but will need to be able to do so without having the main contract already uploaded.

**Comment by jedm** [comment]
Just to confirm - can ANY document be designated as a parent, including new documents and existing ones?

**Comment by anjesh** [comment]
Yes any document can be main, or we can always edit the document to make it main or supporting? To make main document a supporting one, we need to remove all the supporting documents from the parent if associated with the parent. 

With regards to independent associated document, this can be a bit tricky as we are generating OCID for associated document as OCID-of-parent+associated-document-id. We can make the document supporting one and OCID will have only associated-document-id. But from the above process, we won't be able to create associated document without tagging with parent. We can create main document and then tag it as supporting one later. 

Ok will make supporting document = associated document everywhere.

**Comment by SamCCSI** [comment]
Are we now able to add Associated Documents in accordance with the above workflow? Or is it still under development?

**Comment by anjesh** [comment]
Yes we have completed the change as per above workflow. Please let us know if you find any issues there.

**Comment by KaitlinCCSI** [comment]
Thanks, Anjesh. Can you confirm that there is also the ability to note whether an associated document is a contract or not a contract, which will be relevant for the contract tally that appears on home page and advanced search page? (Per #603)

**Comment by anjesh** [comment]
Yes the document is tagged as whether it's associated or not. This needs to be reflected in the homepage though.

**Comment by jedm** [comment]
This may be the same as @KaitlinCCSI question but, when you say it is tagged "as associated" my question can it be tagged as "NOT A CONTRACT"

If non-contract documents can be tagged as NOT A CONTRACT it can help with an accurate count of total contracts. 

We should also confirm (when @anderspeders returns) whether the document total message should be changed to "[Y] DOCUMENTS" (higher number) or stay at "[X] CONTRACTS" (lower number).

**Comment by anjesh** [comment]
As you may see in the process flow above, when the document is uploaded, the user uploads it as main  or associated. We are just differentiating the two right now. I am not aware of whether the associated document could also be a contract - which i am assuming from your text. Is that correct? 

I am thinking of the message as "50 Contracts and 90 Associated documents" as per our flow now. Are you saying that there might be few contract documents within Associated documents as well?

**Comment by jedm** [comment]
@anjesh thanks for your question. 

For this discussion in Github about  associated documents, let's use the terms "Parent" and "Child" instead of "Contract" or "Associated Document."

As already established, any document can be either a parent or a child. Is that correct?

As discussed in #603 and elsewhere the database contains documents that are NOT contracts, therefore they can be tagged as such (and also should not count in the total displayed number of contracts). 

I assume that even if a document is tagged as NOT a contract it can still be a "parent." (This will be unlikely, but should still be possible unless someone has instructed otherwise.) Please confirm. 

Finally, there is the question of how to display the total number of documents. There may be different views here so let's wait for @anderspeders to return before confirming a final decision. My own view is that the homepage should display # of contracts and the search page should display # of documents (in the circle at the top). I do not believe the display should include two totals. 

Please let us know any questions about the above so we can continue to clarify for you, and vice versa!

Thanks much.

**Comment by KaitlinCCSI** [comment]
@jedm Per agreement with @anderspeders I am going to put together a
suggestion on associated docs (where they appear and how tally is counted)
to vet with core group before sending further instructions to YI. So
clarification from @anjesh on Jed's questions will be useful, but please
wait to implement any further changes until more specifics are provided.

On Mon, Nov 16, 2015 at 7:39 AM, jedm <notifications@github.com> wrote:

> @anjesh thanks for your question.
>
> For this discussion in Github about associated documents, let's use the
> terms "Parent" and "Child" instead of "Contract" or "Associated Document."
>
> As already established, any document can be either a parent or a child. Is
> that correct?
>
> As discussed in #603 and elsewhere the database contains documents that
> are NOT contracts, therefore they can be tagged as such (and also should
> not count in the total displayed number of contracts).
>
> I assume that even if a document is tagged as NOT a contract it can still
> be a "parent." (This will be unlikely, but should still be possible unless
> someone has instructed otherwise.) Please confirm.
>
> Finally, there is the question of how to display the total number of
> documents. There may be different views here so let's wait for
> @anderspeders to return before confirming a final decision. My own view is
> that the homepage should display # of contracts and the search page should
> display # of documents (in the circle at the top). I do not believe the
> display should include two totals.
>
> Please let us know any questions about the above so we can continue to
> clarify for you, and vice versa!
>
> Thanks much.
>
> > On Nov 15, 2015, at 11:42 PM, Anjesh <notifications@github.com> wrote:
> >
> > As you may see in the process flow above, when the document is uploaded,
> the user uploads it as main or associated. We are just differentiating the
> two right now. I am not aware of whether the associated document could also
> be a contract - which i am assuming from your text. Is that correct?
> >
> > I am thinking of the message as "50 Contracts and 90 Associated
> documents" as per our flow now. Are you saying that there might be few
> contract documents within Associated documents as well?
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/624#issuecomment-157028778>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PGdDbgO&m=5ca26f0fcb0b&t=20151116&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PGdDbgO&m=5ca26f0fcb0b&t=20151116&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01PGdDbgO&m=5ca26f0fcb0b&t=20151116&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by anjesh** [comment]
Further changes and spec (to display the supporting docs) to be recorded here https://github.com/NRGI/resourcecontracts.org/issues/610

Closing this as the backend process for the supporting document is completed and deployed.
