### ISSUE TITLE
OLC contract view page > page numbers in annotations column appear in different sizes

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#627]
Please see screenshots below. The issue appears across multiple contracts (although I haven't checked each contract). 

![page numbers vary in size](https://cloud.githubusercontent.com/assets/14910764/10927857/491c3dbe-8271-11e5-8b0f-93b6c721e626.png)
![page numbers vary in size 2](https://cloud.githubusercontent.com/assets/14910764/10927856/49196e22-8271-11e5-8fa3-d23a7ab01799.png)

**Comment by upasna01** [comment]
This issue have been fixed. Please review the changes. Here is the snapshot of it.
![olc](https://cloud.githubusercontent.com/assets/11477899/13450288/c0cf6366-e05b-11e5-9464-6b2a69214477.png)

**Comment by JesseCCSI** [comment]
Thanks @upasna01 this looks good - will let you know if we notice any further issues
