### ISSUE TITLE
RC Admin Module: Resource list

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#629]
Capitalize the last 4 resources to allow for the correct sorting. 

![image](https://cloud.githubusercontent.com/assets/13888372/10931848/0d74363c-82d4-11e5-8e32-d5dd19e85742.png)

**Comment by anjesh** [comment]
Need to capitalize and sort the resource list here https://github.com/NRGI/resourcecontracts.org/blob/master/resources/lang/en/codelist/resource.php#L226

**Comment by charlesyoung** [comment]
Is there a difference between hydrocarbons and oil? 

Also what is 3PGM+Au and 6PGM+Au?

**Comment by SamCCSI** [comment]
"Hydrocarbons" covers both oil and associated gas. We tend to use
hydrocarbons as often an oil project will also have provision for
associated gas extraction.

On Wed, Nov 4, 2015 at 3:15 AM, Charles Young <notifications@github.com>
wrote:

> Is there a difference between hydrocarbons and oil?
>
> Also what is 3PGM+Au and 6PGM+Au?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/629#issuecomment-153629929>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by charlesyoung** [comment]
Do we keep 3PGM+Au and 6PGM+Au in the resource list?

**Comment by SamCCSI** [comment]
Charles,

Perrine advises that these should not be included. The first one is
platinum and the second one is gold.

Are there many instances of these and can they be changed as above?

On Fri, Nov 6, 2015 at 4:57 AM, Charles Young <notifications@github.com>
wrote:

> Do we keep 3PGM+Au and 6PGM+Au in the resource list?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/629#issuecomment-154367651>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by SamCCSI** [comment]
Sorry pgm = platinum
Au = gold 

So both are platinum and gold

**Comment by SamCCSI** [comment]
Sorry pgm = platinum
Au = gold

So both are platinum and gold

On Fri, Nov 6, 2015 at 8:42 AM, Sam Szoke-Burke <s.burke@columbia.edu>
wrote:

> Charles,
>
> Perrine advises that these should not be included. The first one is
> platinum and the second one is gold.
>
> Are there many instances of these and can they be changed as above?
>
> On Fri, Nov 6, 2015 at 4:57 AM, Charles Young <notifications@github.com>
> wrote:
>
>> Do we keep 3PGM+Au and 6PGM+Au in the resource list?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/NRGI/resourcecontracts.org/issues/629#issuecomment-154367651>
>> .
>>
>
>
>
> --
>
>
>
> *SAM SZOKE-BURKE*
> *Legal Researcher**Columbia Center on Sustainable Investment*
> Columbia Law School - The Earth Institute, Columbia University
> Level 1, Warren Hall, 410 W116th St. New York, NY 10027
> | (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
> | s.burke@columbia.edu
> | www.ccsi.columbia.edu | @CCSI_Columbia
> <https://twitter.com/CCSI_Columbia> | @samszokeburke
> <http://twitter.com/samszokeburke>
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by charlesyoung** [comment]
@anjesh why are the two resource lists different? 

![image](https://cloud.githubusercontent.com/assets/13888372/11005499/d1e421b4-84c6-11e5-93c4-879bb0d23bdf.png)

![image](https://cloud.githubusercontent.com/assets/13888372/11005508/df695570-84c6-11e5-82da-6eff0cc8cb51.png)

**Comment by charlesyoung** [comment]
From the front-end I don't see any contracts associated with 3PGM+Au and 6PGM+A. @anjesh can you please confirm that this is correct so that we ca delete?

**Comment by anjesh** [comment]
The contracts list in the filter dropdown only lists those resources which has the contract(s). As for 3PGM+Au and 6PGM+A, those are part of the list provided to us in google spreadsheet before.

**Comment by charlesyoung** [comment]
So there are no contracts with 3PGM+Au and 6PGM+A resources.

**Comment by anjesh** [comment]
That's correct.

**Comment by charlesyoung** [comment]
Can you please delete 3PGM+Au and 6PGM+A from the resources list.

**Comment by anjesh** [comment]
Ok, will remove 3PGM+Au and 6PGM+A and will also update this list https://docs.google.com/spreadsheets/d/1tRRcib0VNynipkk83m4Be1vRaSslCKHzoIxmmC1oPLQ/edit#gid=215354368 
cc @anderspeders

**Comment by anjesh** [comment]
Removed and fixed those small caps resources.
