### ISSUE TITLE
Is "contract title" needed as a field?

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#63]
It is fairly clear that we need a **Contract identifier**, but do we also need a string name for the contract - a **Contract name**?

See the Open Oil proposal for a naming convention: http://repository.openoil.net/wiki/Draft_Contract_Filenaming_Convention#Purpose_of_a_File_Naming_Convention

**Comment by anjesh** [comment]
name vs title? What is the difference? #64

**Comment by anjesh** [comment]
Contract name and identifier are both part of the metadata.
