### ISSUE TITLE
RC Admin Module: Contract uploading status 

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#630]
Can the contract uploading status / percentage be more visible than currently displayed? 

![image](https://cloud.githubusercontent.com/assets/13888372/10933991/6d433a20-82e5-11e5-838a-c48fa78febf0.png)

**Comment by anjesh** [comment]
That status is the chrome browser thing, not by us. That could be somehow displayed but will require some change in the way we are currently uploading the file - using ajax.
