### ISSUE TITLE
Mturk Interface and process Improvement

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#632]
This issue follows the process as described in [wiki here](https://github.com/NRGI/resourcecontracts.org/wiki/Mechanical-Turk-Workflow).

### "Contracts Sent to Mturk" page

Now the present contract lists will have two interface. Default is pending contracts - which lists all the contracts for which the tasks are not completed by the workers yet. We can quickly see the contracts which requires action, rather than going through each contract. However the API calls are made once every day so there might not be change at a given instance. However clicking on the given contract will again make API call and updates in the system. Also now the email is sent to the selected users - for the contracts which require action. 

![image](https://cloud.githubusercontent.com/assets/120488/10962936/40c7d3cc-83c4-11e5-8230-0d42c981abe5.png)

```Missing RC|OLC category column in the above interface.```

```Missing Country column in the above interface - could be included after the country name.``` https://github.com/NRGI/resourcecontracts.org/issues/496

Also we can see which contracts have been completed and now merged in the RC system.

![image](https://cloud.githubusercontent.com/assets/120488/10962983/b22aabde-83c4-11e5-9d95-df7afeaee9df.png)

### "Contract Task list" page

We have introduced the "Reset" button for the tasks which are in pending state. Sometimes there might be cases where the worker has accepted the task but hasn't done/submitted the assignment. We can decide to reset the task at any time - in which case that particular HIT gets deleted from Mturk and re-creates new task, open for new workers. This might expedite the process just in case the task gets booked by the workers but haven't been executed yet. Also now there's 10 days limit for each task, after which the 10 days old tasks if not completed by the worker, get deleted and re-created for new workers. 

![image](https://cloud.githubusercontent.com/assets/120488/10963002/e4f890ee-83c4-11e5-93b7-242e8252e3c1.png)

### "All Tasks" page with filter by task status option

This is a new page to see all the tasks of all the contracts in one window. There are different options to see the tasks - the default view is to list the tasks that are completed but that requires action. The user will have to go to respective task page to take action, or the user may also click the contract and take action from there. 

![image](https://cloud.githubusercontent.com/assets/120488/10963053/6217d7f6-83c5-11e5-8457-98f307588e18.png)

**Comment by anderspeders** [comment]
Thanks @anjesh, 

@KaitlinCCSI, @samCCSI: Could you have a look?

**Comment by SamCCSI** [comment]
Thanks all.

Thanks also for adding the RC/OLC category column - very helpful given that we have different staff managing OLC and RC.

1. One step further would be to have the option of only seeing RC contracts or OLC contracts. This would be really useful, given that the number of contracts is now quite large.

2. Will you be incorporating Anders' request for an "Approve all" button so that you can accept all pages of a particular contract after having reviewed some of them and being confident they are of sufficient quality?

**Comment by anjesh** [comment]
OLC/RC filter added.
"Approve all" button added as well.
