### ISSUE TITLE
Tweak to front page text: 

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#634]
From: "Search ____ contracts" 

To: "Search _____ contracts and associated documents"

![image](https://cloud.githubusercontent.com/assets/1101585/10971875/8f21b026-83a4-11e5-805f-2409637a866a.png)

**Comment by KaitlinCCSI** [comment]
For consistency, the "Search Contracts" button on right should simply say
"Search".

On Thu, Nov 5, 2015 at 9:04 AM, Anders <notifications@github.com> wrote:

> From: "Search ____ contracts"
>
> To: "Search _____ contracts and associated documents"
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/1101585/10971875/8f21b026-83a4-11e5-805f-2409637a866a.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/634>.
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PBP4f4T&m=1091047a72bf&t=20151105&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PBP4f4T&m=1091047a72bf&t=20151105&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01PBP4f4T&m=1091047a72bf&t=20151105&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by anderspeders** [comment]
Thanks @KaitlinCCSI

**Comment by sadhakbj** [comment]
![olc_634](https://cloud.githubusercontent.com/assets/5828622/11053882/3d28bebc-878d-11e5-8720-924ee64fb898.png)
![rc_634](https://cloud.githubusercontent.com/assets/5828622/11053883/3d4c9418-878d-11e5-8895-162a9eea868c.png) - Done

**Comment by KaitlinCCSI** [comment]
1. "Associated Documents" should be capitalized for RC (e.g., "Search 714 Contracts and Associated Documents"
2. Please remove "associated documents" from OLC search bar, as our tally only counts contracts and not associated documents (at least as of now) (e.g., "Search 69 Contracts")

**Comment by anjesh** [comment]
This will be taken care when we show the count of contracts and associated documents. If there are no associated documents, then it won't show the label.

**Comment by KaitlinCCSI** [comment]
My first point still should be addressed - "Associated Documents" should be capitalized

**Comment by anjesh** [comment]
Yes. Got that. 
cc @hello-deepak
