### ISSUE TITLE
Correct error message for ResourceContracts.org

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#635]
![image](https://cloud.githubusercontent.com/assets/1101585/10987282/edb84a22-83ff-11e5-84be-9b2bd3742c78.png)

Change email address.

@anderspeders to provide new email

**Comment by KaitlinCCSI** [comment]
Also, error message on both sites should have a period at the end of the
sentence (ie, "check back later.")

On Thursday, November 5, 2015, Anders <notifications@github.com> wrote:

> [image: image]
> <https://cloud.githubusercontent.com/assets/1101585/10987282/edb84a22-83ff-11e5-84be-9b2bd3742c78.png>
>
> Change email address.
>
> @anderspeders <https://github.com/anderspeders> to provide new email
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/635>.
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PC1XBDe&m=a1e35122712b&t=20151105&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PC1XBDe&m=a1e35122712b&t=20151105&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01PC1XBDe&m=a1e35122712b&t=20151105&c=f>
>


-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by anderspeders** [comment]
The email for RC.org should be: info-resourcecontracts@resourcegovernance.org

**Comment by KaitlinCCSI** [comment]
note that hyperlink showing up in message as html for me. 
![screen shot 2015-11-25 at 8 00 47 am](https://cloud.githubusercontent.com/assets/14825437/11399100/ce438dc8-934a-11e5-9914-0946a7832352.png)

**Comment by anjesh** [comment]
Fixed.
