### ISSUE TITLE
Download option not available at country view

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#636]
![image](https://cloud.githubusercontent.com/assets/1101585/11004670/953d0e0e-8487-11e5-8f86-2b26f89f337e.png)

For example here: 
http://www.resourcecontracts.org/countries/bz

**Comment by sadhakbj** [comment]
![636_fixed](https://cloud.githubusercontent.com/assets/5828622/11392818/4ca70440-9384-11e5-9920-72281d379cd0.png)
- done
