### ISSUE TITLE
Add information on OCR extraction method to "Contract view page" - Fix "learn more" link

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#638]
User story (provided by Don Hubert): As a researcher I would like to understand how the text for X contract was extracted *and* how confident the researcher is in the quality. 

Proposed solution: 
For the *contract text view page* - add description on the published data either: 
- "This text was extracted by a machine" when extracted by ABBYY reader
- "This text was transcribed by an assistant"

Read more about the text extraction process here: http://www.resourcecontracts.org/faqs

**Comment by anjesh** [comment]
Currently we are showing this message
![image](https://cloud.githubusercontent.com/assets/120488/12351551/687500a6-bba6-11e5-868d-f4e6ac018e22.png)

learn more links to /faqs
Do we still want the above message you mentioned?

**Comment by KaitlinCCSI** [comment]
@anjesh, is it possible to add in anchor links to the FAQs page, so that the hyperlink on "Learn more" takes you directly to the part of the FAQ page that is relevant? The current utility of the hyperlink is limited as the user then needs to scroll through a lot of text to get supplemental info.

**Comment by jedm** [comment]
Important to include this disclaimer in the MS Word download too, ideally as a footer.

**Comment by anderspeders** [comment]
@anjesh has confirmed that they are working on the anchor link. 

@jedm A disclaimer for the word download documents is already in place at the top of page 1.

**Comment by jedm** [comment]
Anders I meant inside the downloaded file.

**Comment by sadhakbj** [comment]
The disclaimer text has already been added to contract view page and also the downloaded word file.
The Learn More link on the contract text view page or in the downloaded document file anchors to the particular part of the FAQ page. i.e it links to :
 www.resourcecontracts.org/faqs#link_learn_more

**Comment by jedm** [comment]
Possible to make "Learn more" link an anchor to FAQ item 11 instead of just to FAQ? May confuse people.

**Comment by upasna01** [comment]
The issue is fixed, please do verify.

**Comment by jedm** [comment]
Works great on iOS Safari!
