### ISSUE TITLE
Text-based contract page margin adjustment

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#639]
The current margin displace the right metadata bar:

![image](https://cloud.githubusercontent.com/assets/1101585/11016954/068b19b2-855e-11e5-8755-3e77001e7e15.png)

![image](https://cloud.githubusercontent.com/assets/1101585/11016947/f380cfd8-855d-11e5-9592-092b71153d66.png)

**Comment by anjesh** [comment]
fixed. Are you still having this problem? Please re-open if you still getting this issue.
