### ISSUE TITLE
OLC currently offline

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#640]
![image](https://cloud.githubusercontent.com/assets/12913915/11075234/32519c2c-87c2-11e5-8259-53b983194bb0.png)

**Comment by SamCCSI** [comment]
@anderspeders @anjesh @KaitlinCCSI

**Comment by KaitlinCCSI** [comment]
RC is also offline

![screen shot 2015-11-10 at 2 56 17 pm](https://cloud.githubusercontent.com/assets/14825437/11075551/3f337746-87bb-11e5-8306-b3e365626ce9.png)

**Comment by KaitlinCCSI** [comment]
Also Philippines site is buggy/broken. No temporarily unavailable message flashes, but it's not working and site flashes between image of home page, image of footer, and blank white screen. cc @charlesyoung

**Comment by anjesh** [comment]
The site is up now.

**Comment by charlesyoung** [comment]
@anjesh this is pretty serious. How do we ensure that this doesn't happen again?

**Comment by KaitlinCCSI** [comment]
All sites down again. Agree with @charlesyoung that we need to develop a solution so that this does not keep happening.

**Comment by anjesh** [comment]
This was fixed by re-deploying then. Created new issue https://github.com/NRGI/resourcecontracts.org/issues/675 for the notification of such system outage.
