### ISSUE TITLE
Mturk All Tasks

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#642]
I get the following screen when clicking on the 'All Tasks' button in Mturk. 

![image](https://cloud.githubusercontent.com/assets/13888372/11091299/b4706bce-8881-11e5-9701-98c779d92d83.png)

**Comment by anjesh** [comment]
Are you still getting this? The CSS seems to be not loaded properly then. It's working ok at my end.

![image](https://cloud.githubusercontent.com/assets/120488/11178834/78087f4c-8c77-11e5-91bc-85afc0a7785b.png)

**Comment by charlesyoung** [comment]
Works, thanks.
