### ISSUE TITLE
OCR text disclaimer needs proper apostrophe 

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#644]
wrong symbol used
![screen shot 2015-11-11 at 2 10 40 pm](https://cloud.githubusercontent.com/assets/14825437/11101730/36ed2d48-887e-11e5-804c-ac8d05b68883.png)

**Comment by jedm** [comment]
This fix was requested a few weeks ago too.

On Wed, Nov 11, 2015 at 12:12 PM, KaitlinCCSI <notifications@github.com>
wrote:

> wrong symbol used
> [image: screen shot 2015-11-11 at 2 10 40 pm]
> <https://cloud.githubusercontent.com/assets/14825437/11101730/36ed2d48-887e-11e5-804c-ac8d05b68883.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/644>.
>



-- 
Jed Miller | @jedmiller <http://twitter.com/jedmiller>
m +1.917.584.2349 | s @jedbmiller
www.jedmiller.com

**Comment by anjesh** [comment]
Fixed. 
![image](https://cloud.githubusercontent.com/assets/120488/12351506/11cb97c4-bba6-11e5-90ca-fffec806d24c.png)
