### ISSUE TITLE
Libya vs Libyan Arab Jamahiriya: fix the contracts country metadata

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#646]
There are 2 contracts linked Libya and 3 linked to Libyan Arab Jamahiriya (these are not shown on the RC public site). Libyan Arab Jamahiriya was the official name of Libya between 1977-2011 but its called Libya today. 

Can the three contacts linked to Libyan Arab Jamahiriya be transferred to Libya and Libyan Arab Jamahiriya removed from the country drop-down list.

**Comment by anderspeders** [comment]
Could you try renaming them from the backend?

**Comment by charlesyoung** [comment]
No Libya in the list. 

![image](https://cloud.githubusercontent.com/assets/13888372/11118853/e4abd680-894d-11e5-8d05-da3c42a78d3c.png)

**Comment by sadhakbj** [comment]
![646_done](https://cloud.githubusercontent.com/assets/5828622/11295613/d654dc1a-8f94-11e5-9a44-34990a21d834.png)
- Done
