### ISSUE TITLE
Contracts numbers mismatch in the homepage and adv search

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#648]
645 listed on the home page.

![image](https://cloud.githubusercontent.com/assets/13888372/11113831/a0c64b0a-8928-11e5-887e-8de2cdca936a.png)

736 listed when searching for all contracts. 

![image](https://cloud.githubusercontent.com/assets/13888372/11113850/bb6a70ee-8928-11e5-88fc-1fd41eda010f.png)

**Comment by anjesh** [comment]
This was also due to supporting document metadata change when we updated the workflow. This is now fixed.
