### ISSUE TITLE
Verify "Other Minerals" as Resources for cameroon contract

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#650]
Contract resource captured as 'Other minerals'. 

![image](https://cloud.githubusercontent.com/assets/13888372/11114197/7f0f7a7e-892b-11e5-8cbd-a285522115d2.png)

Shown on the public site as 'resources.Other minerals'. 

![image](https://cloud.githubusercontent.com/assets/13888372/11114219/b50f5324-892b-11e5-90cc-315f80b2c789.png)

**Comment by anjesh** [comment]
That is something that might have been imported into the system. The researcher may update the resource and save. The resource field takes free text along with the pre-populated list.

**Comment by sadhakbj** [comment]
![650](https://cloud.githubusercontent.com/assets/5828622/11391343/ffea86cc-9379-11e5-852a-52dbbcb19742.png)
- done
