### ISSUE TITLE
Certain contract download crashed site

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#651]
Downloading some contracts crashes the site. 

For instance 'Iraqi Kurdistan, Genel, Gulf Keystone - Ber Bahr - PSC Amend, 2010'.

**Comment by anjesh** [comment]
Can you put an screenshot of what you get when you say "crashes the site"? Is the browser crashed or just the blank page. Also that crashing link would be useful? Is that repeated as well?

**Comment by charlesyoung** [comment]
![image](https://cloud.githubusercontent.com/assets/13888372/11179360/753adc5e-8c5b-11e5-89f1-af9f376667a3.png)

**Comment by charlesyoung** [comment]
http://www.resourcecontracts.org/contract/ocds-591adf-IQ7988759225RC/view

**Comment by anjesh** [comment]
This was due to problem in ES index when there's change in the supporting documents field. This particular contract and other related contracts with that particular metadata field issue are fixed now.
