### ISSUE TITLE
Contracts needing full transcription downloadable 

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#653]
Why are contracts that are still undergoing transcription allowed to be downloaded from the public site in Word format?

Example: Mali, Gounkoto SA - Gounkoto - Concession, 2012

**Comment by KaitlinCCSI** [comment]
I also noted this in comment here -- shouldn't be downloadable until after
finalized through MT:
https://github.com/NRGI/resourcecontracts.org/issues/645

On Thu, Nov 12, 2015 at 5:23 AM, Charles Young <notifications@github.com>
wrote:

> Why are contracts that are still undergoing transcription allowed to be
> downloaded from the public site in Word format?
>
> Example: Mali, Gounkoto SA - Gounkoto - Concession, 2012
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/653>.
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PEznv1d&m=8a0ea1468dfa&t=20151112&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PEznv1d&m=8a0ea1468dfa&t=20151112&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01PEznv1d&m=8a0ea1468dfa&t=20151112&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by anjesh** [comment]
We will fix this in API and subsite here https://github.com/NRGI/resourcecontracts.org/issues/674

Now there's option for the researcher has to manually set this option to "show pdf text" on and off. We will use this option to hide/show the download word option as well. "show pdf text" => no means the word document also can't be downloaded.

![image](https://cloud.githubusercontent.com/assets/120488/11292784/db39750c-8f7a-11e5-8761-3bc7494d7f4c.png)

**Comment by charlesyoung** [comment]
Will it be set to no by default? Just to understand will there be a "show pdf text" as well as a "show word text" option?
