### ISSUE TITLE
Download csv of search results contains semi-colon

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#654]
Three contracts selected but only 2 exported when selecting the download to CSV. 

http://www.resourcecontracts.org/search?q=&country%5B%5D=ly

Also funnies in the export with the company number in the company address field and the share in the corporate grouping field. 

![image](https://cloud.githubusercontent.com/assets/13888372/11119561/2894cf6e-8953-11e5-95ed-271cdba098fb.png)

**Comment by anjesh** [comment]
; appeared there because there are two companies but company number is not present for both. ; would separate if there two 2 company number. Not sure this is just a convention but we can remove that if you think that makes sense.

cc @anderspeders
