### ISSUE TITLE
Prepare list of contracts with "missing category (RC/OLC)"

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#655]
@anjesh I noticed various contracts missing a category (RC / OLC). Can you please create a list of contracts missing a category?

**Comment by anjesh** [comment]
https://github.com/NRGI/resourcecontracts.org/issues/676 will solve this.

**Comment by anjesh** [comment]
There are only two 
http://resourcecontracts.elasticbeanstalk.com/contract/1051
http://resourcecontracts.elasticbeanstalk.com/contract/1052

@charlesyoung
