### ISSUE TITLE
Terminology 

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#657]
Do we use 'Main Contract' or 'Parent Contract'? 
Do we use 'Associated Document' or Associated Contract'? 

This is currently differently referenced.

**Comment by KaitlinCCSI** [comment]
Use "Associated Document", which can cover a contract or a document that is
not a contract.

On Fri, Nov 13, 2015 at 4:16 AM, Charles Young <notifications@github.com>
wrote:

> Do we use 'Main Contract' or 'Parent Contract'?
> Do we use 'Associated Document' or Associated Contract'?
>
> This is currently differently referenced.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/657>.
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PEWg8fq&m=e942af9f9d63&t=20151113&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PEWg8fq&m=e942af9f9d63&t=20151113&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01PEWg8fq&m=e942af9f9d63&t=20151113&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by anjesh** [comment]
We use "Associated Document" labels in subsites and also fixed the API field names.
