### ISSUE TITLE
Associated document name

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#659]
Don't copy the main contracts name to the associated document name when linking as it will be different. Leave blank to allow the Uploader to populate. 

![image](https://cloud.githubusercontent.com/assets/13888372/11144049/56de9bfc-8a02-11e5-8843-4c0e444a7813.png)

**Comment by sadhakbj** [comment]
![Uploading 659_done.png…]()
![Uploading 659_editing.png…]()
- Done
