### ISSUE TITLE
Remove Beta text from RC only. 

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#660]
Do we keep the 'beta' text? 

![image](https://cloud.githubusercontent.com/assets/13888372/11146127/22e4c2ba-8a14-11e5-9317-f0550da57bef.png)

![image](https://cloud.githubusercontent.com/assets/13888372/11146134/31f1dc0c-8a14-11e5-9ba1-9d15aef9bc4a.png)

**Comment by anjesh** [comment]
@anderspeders I also think we are good to remove beta now? what do you say?

**Comment by KaitlinCCSI** [comment]
Please keep "Beta" on OLC for now. Thanks. Defer to @anderspeders and others on whether to keep for RC.

**Comment by charlesyoung** [comment]
@anjesh we need to remove the 'beta' text from the RC site and start implementing a version numbering system.

**Comment by anjesh** [comment]
Ok. We will remove beta from RC and it will remain as it is in OLC.

**Comment by charlesyoung** [comment]
@anjesh can we then also start implementing a RC version numbering system.

**Comment by anjesh** [comment]
we will remove beta when we introduce new home page for RC but beta will not be removed for OLC. However both the OLC and RC versions will be 1.0 as codebase for both the system are same.

**Comment by manishgs** [comment]
"Beta" text has been removed on RC site.
