### ISSUE TITLE
Contract quality issues list shows all contracts has category when there are with none

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#661]
Not sure how the contract quality issues list is generated but below shows all resource and category captured while there are contracts with no category or resource. 

![image](https://cloud.githubusercontent.com/assets/13888372/11146571/25bb898e-8a18-11e5-8f64-6b4e837c1f2b.png)

Missing category example: Russian Federation PGO Lenaneftegasgeologija OEMV Verchenmurbaisk Area Otradninsk Area JV

Missing resource example: Kazakhstan Falcon O&G Zhakarmy West I Block Exploration Contract

**Comment by anjesh** [comment]
Resolved. You could now verify this with the csv download in the admin.
