### ISSUE TITLE
Associated Documents name/link missing in the contract summary page

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#662]
Associated documents in the admin site. 

![image](https://cloud.githubusercontent.com/assets/13888372/11183058/379d89d8-8c78-11e5-8d23-2bd183a5f0f8.png)

http://resourcecontracts.elasticbeanstalk.com/contract/1334

Not showing on the public site

![image](https://cloud.githubusercontent.com/assets/13888372/11183075/583bdfc8-8c78-11e5-9526-ac489f6e09cb.png)

http://www.resourcecontracts.org/contract/ocds-591adf-CN0254292095RC

**Comment by sadhakbj** [comment]
![662](https://cloud.githubusercontent.com/assets/5828622/11209022/b1862966-8d46-11e5-81b4-d63809229b3b.png)
- done
