### ISSUE TITLE
Fix and alphabetize countries/resources in "filter by countries/resources" lists on Resource/Country page

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#663]
Filter by resources appears to not work on countries page - when I select a box, the page just goes blank.

![screen shot 2015-11-16 at 12 31 22 pm](https://cloud.githubusercontent.com/assets/14825437/11190931/ffccdf64-8c5d-11e5-80b8-77a2ae9c1752.png)

Also, filter by resources (on countries page) and filter by countries (on resources page) should provide alphabetized lists

![screen shot 2015-11-16 at 12 27 59 pm](https://cloud.githubusercontent.com/assets/14825437/11190849/9d7bb952-8c5d-11e5-9dcb-5e692b8f63af.png)
![screen shot 2015-11-16 at 12 25 39 pm](https://cloud.githubusercontent.com/assets/14825437/11190806/61261e5c-8c5d-11e5-81fd-2fce719102e5.png)

**Comment by charlesyoung** [comment]
Linked to case #652

**Comment by sadhakbj** [comment]
![663-filter-by-resource](https://cloud.githubusercontent.com/assets/5828622/11391267/3eb78504-9379-11e5-8679-18ee82799a37.png) 
![663-filter-by-countries](https://cloud.githubusercontent.com/assets/5828622/11391279/64bfa420-9379-11e5-8871-0d4c1c063b80.png)

- done
