### ISSUE TITLE
Error when clicking on metadata summary link

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#665]
Error when clicking on metadata summary link

![image](https://cloud.githubusercontent.com/assets/13888372/11210408/a63c5d7a-8d30-11e5-8ff7-b01958260969.png)

http://www.resourcecontracts.org/contract/ocds-591adf-TZ1121976631RC/view

**Comment by anjesh** [comment]
Some of these issues are with the indexing of the contract when published. There has been a change in metadata, change in mapping. We are figuring out the source of the problem and fixing them. There are couple of issues here with similar problems.

**Comment by anjesh** [comment]
This particular one is due to the "Jurisdiction of Incorporation" field which used to be free-text but now takes the country iso code from the list. We will fix this.

**Comment by anjesh** [comment]
This OCID doesn't exist in the system, this must have been there during the testing of OCID generation. Now there are 5 TZ (tanzania) contracts and don't have this OCID in any one of them.
