### ISSUE TITLE
"Contract View" page needs word download option as well.

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#667]
Is it by design that only PDF's are allowed to be downloaded for the annotation page? 

![image](https://cloud.githubusercontent.com/assets/13888372/11210748/f34ea850-8d32-11e5-8cc1-aaef51450249.png)

**Comment by anjesh** [comment]
We will have both PDF and word download here.

**Comment by jedm** [comment]
This was discussed at length in #318

**Comment by jedm** [comment]
This was discussed at length in #381

**Comment by KaitlinCCSI** [comment]
As a reminder, only for RC -- at this point, Word docs containing text
extracted from PDFs should not be downloadable from OLC.

On Fri, Jan 15, 2016 at 4:29 AM, Anjesh <notifications@github.com> wrote:

> We will have both PDF and word download here.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/667#issuecomment-171927977>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01Q6atuCM&m=621d29bd2fab&t=20160115&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01Q6atuCM&m=621d29bd2fab&t=20160115&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01Q6atuCM&m=621d29bd2fab&t=20160115&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by jedm** [comment]
Do @byndcivilization and @jimc33 still feel that pre-MTurk documents should be available in Word? cc @anderspeders

**Comment by anderspeders** [comment]
For RC; the NRGI position is stil that OCR-ed text (pre-MTurk) should be available as download along with the PDF. We are providing a sufficient disclaimer so there should be no legal liability issues around this.

**Comment by KaitlinCCSI** [comment]
Per this convo https://github.com/NRGI/resourcecontracts.org/issues/653, I thought that NRGI was ok with only providing a Word doc once it has gone through MTurk _IF_ it is slated for MTurk. (In other words, doesn't apply to all docs, but to a subset that have been identified as needing MTurk.)

And per this comment https://github.com/NRGI/resourcecontracts.org/issues/381#issuecomment-144157021, I thought Anders was going to seek consensus from group?

**Comment by sadhakbj** [comment]
Word download feature has been added and deployed in sub site. Word download option appears in RC. Please check it once on demo sub site.
![word_download](https://cloud.githubusercontent.com/assets/5828622/12714194/55415810-c8fb-11e5-9d7a-7111de2d39fa.png)

**Comment by sadhakbj** [comment]
- It's fixed and deployed.

**Comment by anderspeders** [comment]
To summarize from email exchange with RC group, 

1) Word download option will be available if OCR text is rendered: "Acceptable"

This currently would mean that the following contracts should be available as word download: http://resourcecontracts.elasticbeanstalk.com/contract?type=ocr&status=1

2) This means that contracts that are marked either: Needs editing, Not acceptable or are not reviewed will not be available as word download. 

These contracts should only be available as PDF download. 

Adding this to sprint 13. 

@KaitlinCCSI please note if any questions or concerns with this?

**Comment by KaitlinCCSI** [comment]
Anders's instructions are correct. Assume that a document will automatically switch from the second category into the first category once all MTurk pages are approved and published? If not, there should be a clear way for the person approving publication of OCR text from MTurk to note that the Word download can be made available.

**Comment by charlesyoung** [comment]
Should the 'Text Type' ( Acceptable, Needs Editing and Needs Full Transcription) not be required to be selected?

**Comment by anjesh** [comment]
Currently the text-type is just used to select whether the text is good, needs editing or needs to send to Mturk. Besides that the option is not used for any other purpose. We have "Show-pdf-text" to show the text contract view and to download the word. 

For eg. this particular contract can be downloaded as word as it has "show pdf text" to true. 

![image](https://cloud.githubusercontent.com/assets/120488/13343356/ea899a6e-dc73-11e5-93b8-1fb7ca53b3c2.png)

We will do the scoping of the workflow https://github.com/NRGI/resourcecontracts.org/issues/778  that will also address this particular discussion 

For now i think this can be closed. Further discussion on the workflow will be carried out here https://github.com/NRGI/resourcecontracts.org/issues/778
