### ISSUE TITLE
Contract names now cut off on Metadata page

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#668]
Used to be able to see entire contract name, now it's cut off and ellipses are used. Please fix so you can see entire contract name.

New view: 
![screen shot 2015-11-17 at 2 54 27 pm](https://cloud.githubusercontent.com/assets/14825437/11224580/53671396-8d3b-11e5-91f2-d925ed8532a9.png)

Old view:
![screen shot 2015-11-17 at 2 56 48 pm](https://cloud.githubusercontent.com/assets/14825437/11224604/769f2902-8d3b-11e5-89e8-3a2f029a47a6.png)

**Comment by anjesh** [comment]
Trimming was done to save the space since we put the back button - which wasn't there before. Also trimming saves space in the mobile view as well. We will think how to improve this title view. 

cc @anjhero @sweetanzell

**Comment by KaitlinCCSI** [comment]
Okay, would be useful to work on improving it so you can see the entire title, which is important. The original view just wrapped any extra text to the second line, and I don't see why that can't still occur with the back button (although I'm not sure what it means for mobile view).

**Comment by anjesh** [comment]
Mobile view means viewing the site mobile screen and with the long title text, the title will take large amount of screen when you land on the contract view/summary page. That trimming was done to save that space. Will see how to improve upon those.

**Comment by anjesh** [comment]
@anjhero lets discuss on this. I think we need to change the layout/structure of the header section (containing title, back link, breadcrumb, view document) to show the full title.

**Comment by hello-deepak** [comment]
The contract name with larger title are shown on hovering the title.

http://www.resourcecontracts.org/contract/ocds-591adf-IS1796417971RC
