### ISSUE TITLE
Annotations Compare feature: Online side-by-side viewing of annotations content

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#669]
As a user, I want to compare (1) all annotations for stabilization clauses; (2) all annotations for stabilization clauses in set of contracts (i.e., in contracts from X, Y, and Z countries, or in contracts from Year 1 and Year 2); (3) all annotations for stabilization clauses in contracts from one specific country; or (4) all annotations for stabilization clauses in 2 or more specific contracts.

**Comment by anjesh** [comment]
We are thinking of having a separate page for the annotations compare.

The user may select only one annotation category in the compare function. The link to the annotation compare could be included in the search page with some text. Also we could see if the page could be linked from the annotations list page as well, without making the list very crowded. Clicking on that link takes to this annotation compare page with that particular annotation pre-selected. Then the user may apply various filter to trim the contract list. 

Download CSV will be same as that of https://github.com/NRGI/resourcecontracts.org/issues/607  

![image](https://cloud.githubusercontent.com/assets/120488/11233898/bcf2c378-8dea-11e5-8f0e-9d4ae1f302db.png)

**Comment by anderspeders** [comment]
A few comments: 

1) Question: What would the filtering option include?
2) Could there be an option to select the specific contract you wish to compare?
3) For column B we would want these to be hyperlinks for the annotations directly (here stabilization clause)

**Comment by SamCCSI** [comment]
Need to have ability for disclaimer that explains that wording/style of annotations in different contracts might vary when in fact the content of the two contracts on this issue does not differ significantly (exact wording TBD).

**Comment by anjesh** [comment]
@anderspeders 
1. It's similar to that of advanced search, which searches for text in any of the metadata, annotation and text. 
2. Selecting the specific contracts to compare the annotations would be two steps process. We could jump here from the existing advanced search page after selecting the contracts. Then this would be a separate interface where the user will only be able to change the annotations options. Will create a seprate UI for this.
3. Yes we could hyperlink to specific annotations from here. 

Yes we could have the disclaimer at the bottom of the compare page.

**Comment by anjesh** [comment]
When the user clicks the "Compare Annotate", the user will see the interface to search and filter the contract. 

![image](https://cloud.githubusercontent.com/assets/120488/11464784/17e53c2e-975b-11e5-9c24-7c165a63ca3c.png)

In the same interface, the user may also choose the contracts s/he is interested and see the annotations for those specific contracts only. 

![image](https://cloud.githubusercontent.com/assets/120488/11464785/1d3ffc36-975b-11e5-9d96-ba27d76de8b7.png)

The user may reset and go back to the interface to do the search and compare. 

![image](https://cloud.githubusercontent.com/assets/120488/11464817/6e229140-975b-11e5-9ea1-d134fe9e08aa.png)

**Comment by KaitlinCCSI** [comment]
(1) For "filter contracts" bar -- what is process here? A user first selects an annotation through the dropdown at top and then searches in the "filter contracts" bar to further narrow search? Or the user chooses to find annotations either through the dropdown at top or through this "filter contracts" bar? 

I don't see the value of this ability to search via free text through metadata, contract text, and annotations when this page is meant to only provide comparison of annotations. But I could see how this search bar could potentially be useful if a user has already selected the annotation category to compare, and then wants to look for annotations that contain a certain word or phrase. For example, I choose to compare "infrastructure - third party use", and then I want to find annotations that use the word "road" or the word "port".

(2) What is the "Find contracts and compare" button at the bottom? 
![screen shot 2015-12-01 at 4 17 55 pm](https://cloud.githubusercontent.com/assets/14825437/11516367/6408d474-9848-11e5-9b14-ef3fe719767e.png)

**Comment by anjesh** [comment]
> As a user, I want to compare (1) all annotations for stabilization clauses; (2) all annotations for stabilization clauses in set of contracts (i.e., in contracts from X, Y, and Z countries, or in contracts from Year 1 and Year 2); (3) all annotations for stabilization clauses in contracts from one specific country; or (4) all annotations for stabilization clauses in 2 or more specific contracts.

"Filter contracts.. text-box and the options" are to search and  list the contracts under given criteria as above user story and then "annotation to compare" selection will show the annotations for those list of contracts. "Filter contracts" is a free text search query to search for various terms anywhere in the contract like that of advanced search. 

"Find contracts and compare" is the wrong term here, it should have been "submit", which searches the contract as per selected criteria and shows the list of contracts and annotations for the selected annotation category. Clicking that will show this page https://github.com/NRGI/resourcecontracts.org/issues/669#issuecomment-160531347

**Comment by KaitlinCCSI** [comment]
If this feature is only to compare *annotations*, then a free text search query that searches for various terms in the *contract text* or *metadata* seems like it would confuse the results. But if it is only searching the *annotation text*, it makes more sense to me.

**Comment by anderspeders** [comment]
As per agreed @jedm will work on a revised version of this with input from group. 

@anjesh Please stand by until further notice.

**Comment by anjesh** [comment]
@anderspeders is it something that is addressed by clipping features?
