### ISSUE TITLE
PDF and text annotation category lists 

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#671]
The annotation category lists are presented differently for PDF and text documents. 

PDF:

![image](https://cloud.githubusercontent.com/assets/13888372/11237579/7a1a8618-8de9-11e5-8720-7a7058526375.png)

Text:

![image](https://cloud.githubusercontent.com/assets/13888372/11236429/45b55418-8de2-11e5-99d6-5cc2cd105943.png)

**Comment by anjesh** [comment]
This shouldn't happen anymore.
