### ISSUE TITLE
MTurk API calls logging

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#672]
There has been several instances of HIT where the approver couldn't approve or reject the HIT. There are cases where these HITs are approved when pulled from APIs whereas these HITs are shown as deleted in Mturk. We need to have proper logging of all the API calls in Mturk so that we have all the information about what's happening when the API calls are being made. Such logs are not present in MTurk for debugging purpose. 

Related issue https://github.com/NRGI/resourcecontracts.org/issues/626

**Comment by sadhakbj** [comment]
![Uploading log_implemented.png…]()
- Log Implemented.
