### ISSUE TITLE
Hide download option and headers when 0 documents 

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#673]
Currently the header and download option is shown in the search results page when there are no results.

![image](https://cloud.githubusercontent.com/assets/120488/11266127/47a69780-8eca-11e5-89ec-86db7140cb93.png)

**Comment by sadhakbj** [comment]
![673_fixed](https://cloud.githubusercontent.com/assets/5828622/11392870/92ab0d38-9384-11e5-8bc7-000c201faf14.png)
 - Done
