### ISSUE TITLE
Hide "Word" download when the show-text status is off

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#674]
There's show-text option in the admin, which is set to on if the OCR text is good, then the OCR text can be browsed from the subsite and then the word file should be downloadable. If the show-text is set of off, then both the word file download option should be hidden - the OCR text is not shown in this case. 

This might require some minor fix in the API as well. 

https://github.com/NRGI/resourcecontracts.org/issues/653 issue will be taken care after this fix.

@anderspeders @KaitlinCCSI  shall we enable word download in OLC in such cases where the OCR text is good and the show-text option is set to on by the admin? Right now word documents download is disabled for OLC.

**Comment by anjesh** [comment]
PDF and/or Word download should be enabled in listing, country page, resource page, contract view and summary view.

**Comment by KaitlinCCSI** [comment]
Thanks, Anjesh. No word download from OLC even when it has gone through MT.

On Thu, Nov 19, 2015 at 3:34 AM, Anjesh <notifications@github.com> wrote:

> PDF and/or Word download should be enabled in listing, country page,
> resource page, contract view and summary view.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/674#issuecomment-158003054>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PHlyqR6&m=5a5c86c53eeb&t=20151119&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PHlyqR6&m=5a5c86c53eeb&t=20151119&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01PHlyqR6&m=5a5c86c53eeb&t=20151119&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by anjesh** [comment]
Thanks for the confirmation. 
cc @sadhakbj

**Comment by anjesh** [comment]
Implemented.
