### ISSUE TITLE
Enable CSV download option in Admin.

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#676]
Need a csv download option in admin that lists all the metadata values of all the contracts. 

Related https://github.com/NRGI/resourcecontracts.org/issues/655

**Comment by charlesyoung** [comment]
This is good to have in the future but can you not generate a list of contracts missing a category so that I can manually update as these are not showing on the public site?

**Comment by anjesh** [comment]
The following fields are to be exported in csv.

System ID
OCID
Category
Contract Name
Contract Identifier
Language
Country Name
Resource
Contract Type
Signature Date
Document Type
Government Entity
Government Identifier
Company Name
Jurisdiction of Incorporation
Registration Agency
Company Number
Company Address
Participation Share
Corporate Grouping
Open Corporates Link
Incorporation Date
Operator
Project Title
Project Identifier
License Name
License Identifier
Source Url
Disclosure Mode
Retrieval Date
Pdf Url
Pdf Type
Show Pdf Text
Text Type
Metadata Status
Annotation Status
Pdf Text Status
Created by
Created on
Associated Documents (list system ids of the associated documents separated by ,)

**Comment by anjesh** [comment]
Have deployed the csv bulk download in admin. Now we can quickly verify the data in the admin, if there are any issues with the data. It includes all the metadata and the status of pdf/text/annotations. 

![image](https://cloud.githubusercontent.com/assets/120488/11737181/db5941f4-9ffe-11e5-8be7-9c8fcaed1866.png)

@anderspeders @SamCCSI @charlesyoung

**Comment by charlesyoung** [comment]
504 Gateway Time-out error when clicking download contracts.

**Comment by charlesyoung** [comment]
@man-git007 what is the latest with this ticket? I'm on leave from tomorrow.

**Comment by man-git007** [comment]
@charlesyoung We will start working on this from tomorrow

cc @sriza

**Comment by sriza** [comment]
@charlesyoung 
The fixes to the 504 Gateway Time-out error on the download of the contract have been deployed to the staging site. Please have a look and let us know if it is functioning correctly.

Thank you

cc @man-git007

**Comment by sriza** [comment]
@charlesyoung 
Are the changes related to this issue tested on the staging site?
Please let us know if they can be deployed to the production site.

Thank you

cc @man-git007

**Comment by charlesyoung** [comment]
Thanks. Please move to Prod but change the button text to 'Export Metadata'.

**Comment by sriza** [comment]
@charlesyoung 
The changes are now deployed on the production site. Please verify.

Thank you

cc @man-git007

**Comment by charlesyoung** [comment]
Thanks. I however get a '504 Gateway Time-out' error. 

Also, I don't see the 'Text Download' option on the Prod site.

**Comment by sriza** [comment]
@charlesyoung 
We have further optimized the CSV download and deployed it to the production server. Please have a look and let us know if you are still facing the '504 Gateway Time-out' issue.

Regarding the text download option on the production site, the issue is caused by scheduled commands not running on the production server. One of these scheduled commands is responsible for sending the PDF of contracts to the AWS server for text download. Since, there are no downloadable text contracts on the AWS server, the 'Text Download' button is not visible for now.
We have already mailed the cloudEnlight team regarding this issue. 
We will get back to you once the issue is solved.

Thank you

cc @man-git007

**Comment by charlesyoung** [comment]
Thanks
