### ISSUE TITLE
PDF loading message

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#677]
When loading the PDF pages, the loading message only appears occasionally, and not for every page. (I was just looking at this contract: http://www.openlandcontracts.org/contract/ocds-591adf-ET9367327492OL/view#/pdf and the message appeared about 50% of the time.) Is this a bug?

Also, the message should be changed to "Loading PDF page X" rather than "Loading pdf pageX". In other words, PDF should be all caps, and there should be a space between "page" and the number.

**Comment by anderspeders** [comment]
I just checked all pages and it loaded fine for me. Could you confirm if this is still an issue?

**Comment by KaitlinCCSI** [comment]
Not happening today. Checked a second one as well and seems fine now.

Note requested change to message as well. The message should be changed to "Loading PDF page X" rather than "Loading pdf pageX". In other words, PDF should be all caps, and there should be a space between "page" and the number.

**Comment by sadhakbj** [comment]
- Done
![pdf_loading](https://cloud.githubusercontent.com/assets/5828622/12382885/49331cbe-bdc7-11e5-8e3f-1b0618d0c395.png)

**Comment by sadhakbj** [comment]
- Done
![pdf_loading](https://cloud.githubusercontent.com/assets/5828622/12382922/d6f3067c-bdc7-11e5-8940-130d411e620e.png)
