### ISSUE TITLE
Incorrect URL's from the google search

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#678]
I get a '404 error' when clicking on most of below links. 

![image](https://cloud.githubusercontent.com/assets/13888372/11301821/6690437a-8fa2-11e5-974e-b12232f0984d.png)

**Comment by anjesh** [comment]
It appears that the google is indexing the previous rc.org pages.

**Comment by charlesyoung** [comment]
Can this be updated or redirected?

**Comment by anderspeders** [comment]
I believe Google will fix this over time?

@byndcivilization

**Comment by byndcivilization** [comment]
just forced it

**Comment by anjesh** [comment]
Still showing some incorrect links in the google.

**Comment by anjesh** [comment]
duplicate of https://github.com/NRGI/resourcecontracts.org/issues/678
