### ISSUE TITLE
Annotation module > clicking on category title or page number 

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#679]
When you click on a page number or annotation category title in the left hand annotation column (e.g. on the page below), the list of annotations in the left hand column often (but not always) jumps up, so you lose sight of the annotation and have to scroll back up to find it. This makes it difficult for annotators and reviewers to keep track of the annotation they are working on. Is it possible to stabilize this? 

This has happened to me when using chrome on PC and Mac. 

http://resourcecontracts.elasticbeanstalk.com/contract/1382/annotate#/pdf/page/45

**Comment by SamCCSI** [comment]
I reported this issue earlier and have experienced it occasionally as well.

**Comment by SamCCSI** [comment]
This issue needs to have the label "bug" attached to it.

**Comment by upasna01** [comment]
This issue will be fixed on new annotations module.
