### ISSUE TITLE
Use compose.io for the database

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#68]
cc @byndcivilization for the credentials

**Comment by byndcivilization** [comment]
I'm on slack when you have a chance.

**Comment by anderspeders** [comment]
Hi @anjesh Is there a specific reason why we are dropping this sprint 2?

I am asking because it would be great to finalise the deployment so that user can begin making contributions (contract load and metadata).

**Comment by anjesh** [comment]
Received the credentials. Any change in db host in future also would not be much of an issue.
