### ISSUE TITLE
Annotation module > changing annotation category on the back end contract page 

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#680]
At the moment, you can’t change annotation categories on the back end contract page, you have to change them on the back end PDF view page. 

Reviewing and making changes to annotations is easier/ quicker to do on the back end contract page rather than the PDF view page. It would therefore be helpful and save reviewers time if changes could be made to annotation categories on this page (as well as on the PDF view page).

By "changes to annotation categories" I mean, for example, changing "Infrastructure" to "Infrastructure - third party use". 

By "back end contract page", I mean this page: http://resourcecontracts.elasticbeanstalk.com/contract/1382

**Comment by anjesh** [comment]
You may change the category directly from the back end contract page. We have deployed this couple of months back and forget to get back. 

![image](https://cloud.githubusercontent.com/assets/120488/12259210/3458190a-b93c-11e5-89d8-c406653f29d2.png)
