### ISSUE TITLE
Bug with "other" free text in contract type field

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#681]
When we are creating a new upload for the first time on the “Add Contract” page, it is not possible to enter free text when we select “Other//Autre” in the “Type of Contract” field.  However, it is possible to enter free text in this field when we use the “Edit” function to modify an existing upload.  We would like to be able to enter free text when we select “Other//Autre” in the “Type of Contract” for new uploads on the “Add Contract” page for the first time.

**Comment by anderspeders** [comment]
Good point. I think this reflects a bigger and more systemic question for this data field:  

Should the Contract type category cover a set list of main contract categories or should the category cover the specific terminalogy applied in the country (eg. the custom field we have for SL)?

Currently my sense is that we are following something in between the two which seems to capture neither a consistent overlal categorisation (with the generalizations this include) or a free text taxomony which captures the exact description of each contract in its own words.

**Comment by jpmckinney** [comment]
Promoting #720 as the main metadata data modeling issue. Retagging as "Metadata - backend" to fix the "free text for new uploads" issue.

**Comment by anjesh** [comment]
"Contract type" takes multiple values. If you select only "Other", then you will get a text-box to enter value for "Other" only. However if type already has some value than "Other", then the free-text box is not shown. 

Previously we have a box where you may either select the values or type any open-text and later introduced separate text-box for the "other" selection. It's slightly confusing at the moment. What do you suggest here to get the value for "Other"?

**Comment by anjesh** [comment]
Wil there be a case where there are contract-type defined  and also "Other"? That would be conflicting. If you want to enter free-text, then you only have to select "Other" and nothing else. 
Please re-open if there's confusion.
