### ISSUE TITLE
Serious bug on RC and OLC - none of the contracts will load

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#682]
Just tried to open up first 3 contracts on advanced search page of OLC.

First one took me to the error page the first time I opened it; the second time it opened but said there were no annotations. The third time I tried to open it I got an error message again. http://www.openlandcontracts.org/contract/ocds-591adf-LR0574998871OL/view

Second one  took me to the error page three times (each time I tried to open it). http://www.openlandcontracts.org/contract/ocds-591adf-SS5768196941OL/view

Third one also took me to the error page three times (each time I tried to open it).

Also tried to open up first 3 contracts on advanced search page of OLC, and was sent to the error page each time.

cc @anjesh @anderspeders

**Comment by KaitlinCCSI** [comment]
Sorry, I meant *RC* in the last line, not OLC.

**Comment by anjesh** [comment]
Related to https://github.com/NRGI/resourcecontracts.org/issues/683#issuecomment-159276907 
Due to change in the index mapping. These contracts are fixed now. Still few issues left, will be taken care here https://github.com/NRGI/resourcecontracts.org/issues/685#issuecomment-159393464
