### ISSUE TITLE
RC site down?

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#683]
Home pages open, but received message that the site is temp unavailable when I tried to search something on RC. Didn't get the same message when I tried to search on OLC.
![screen shot 2015-11-24 at 7 37 04 am](https://cloud.githubusercontent.com/assets/14825437/11368252/5a28e8a6-927e-11e5-9439-7e5cdc992124.png)

**Comment by KaitlinCCSI** [comment]
cc @anderspeders @anjesh

**Comment by anderspeders** [comment]
As of checking now - the site is up. 

@anjesh Can share an update on how the outage came about.

**Comment by KaitlinCCSI** [comment]
Yes, works for me now too.

On Tue, Nov 24, 2015 at 8:03 AM, Anders <notifications@github.com> wrote:

> As of checking now - the site is up.
>
> @anjesh <https://github.com/anjesh> Can share an update on how the outage
> came about.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/683#issuecomment-159276551>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PJq3kRq&m=c697c6ac9b72&t=20151124&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PJq3kRq&m=c697c6ac9b72&t=20151124&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01PJq3kRq&m=c697c6ac9b72&t=20151124&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by anjesh** [comment]
There are still few issues with certain options in the site like selecting the country crashes the site. Last indexing with new metadata breaks some parts of the API - issue here https://github.com/NRGI/resourcecontracts.org/issues/685#issuecomment-159393464.
