### ISSUE TITLE
Metadata fields to hide/delete from OLC

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#684]
Metadata fields to hide/delete from OLC but not RC:
- Registration Agency
- Participation Share
- Operator
- Project Title
- Project Identifier
- License Name
- License Identifier
(Entire “Concession/License and Project” box should be removed) 

![screen shot 2015-11-24 at 1 06 51 pm](https://cloud.githubusercontent.com/assets/14825437/11377710/f1c8fcea-92ac-11e5-841e-cb8c25c72cc3.png)

cc @anderspeders

**Comment by anderspeders** [comment]
Thanks @KaitlinCCSI 

To clarify these will be removed from the front end but not from the backend database.

**Comment by sadhakbj** [comment]
![684_olc](https://cloud.githubusercontent.com/assets/5828622/11434232/717baa3c-94f1-11e5-83da-57bc3125dd23.png)
![684_rc](https://cloud.githubusercontent.com/assets/5828622/11434252/922e7da4-94f1-11e5-9d86-35500b3522b4.png)
- Done

**Comment by KaitlinCCSI** [comment]
Thanks. There is one extra line of space between Associated Documents box and Source box. Could you please remove so spacing is even on the page?
![screen shot 2015-12-01 at 4 29 35 pm](https://cloud.githubusercontent.com/assets/14825437/11519131/2941b170-985d-11e5-9ee0-5bb7de7821a3.png)

**Comment by anjesh** [comment]
cc @sweetanzell and @sadhakbj
