### ISSUE TITLE
Advanced search crashes site with the country selection

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#685]
Crash when selecting Afghanistan through the advanced search. 

![image](https://cloud.githubusercontent.com/assets/13888372/11379194/b36e1390-92f7-11e5-9c76-55b3a9317c24.png)

![image](https://cloud.githubusercontent.com/assets/13888372/11379214/d0a2660a-92f7-11e5-84d1-5591edb80d8b.png)

More crashes using the advanced search e.g. year signed.

**Comment by anderspeders** [comment]
@anjesh could you follow up here

**Comment by anjesh** [comment]
This is fixed.
