### ISSUE TITLE
Advanced search reset is not working.

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#686]
1. Search for country Angola
2. Click reset
3. Country list cleared
4. Click search again
5. Angola reappears in the country list

**Comment by sadhakbj** [comment]
fixed.

**Comment by anjesh** [comment]
Fixed.

**Comment by charlesyoung** [comment]
Another issue, the reset doesn't remove all the previous search info. 

![image](https://cloud.githubusercontent.com/assets/13888372/11393775/4313db3e-936a-11e5-9202-e96ef78a3050.png)

**Comment by sadhakbj** [comment]
- done

**Comment by charlesyoung** [comment]
Although the search is 'cleared' the text still remains. All text need to be cleared. 

![image](https://cloud.githubusercontent.com/assets/13888372/11397130/b48c69a6-937f-11e5-9c32-e414d9f5114a.png)

**Comment by sadhakbj** [comment]
- fixed .
