### ISSUE TITLE
Annotation sorting by EITI requirement

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#687]
PH-EITI has requested that we not only allow for annotation sorting by page and category but also by EITI requirement. They have undertaken a detailed analysis of which categories are linked to the EITI requirements e.g. royalties category linked to  EITI requirement 4.1. 

![image](https://cloud.githubusercontent.com/assets/13888372/11391268/d4375250-9359-11e5-8d64-ce5cb377518a.png)

**Comment by KaitlinCCSI** [comment]
If this is implemented, it should only be implemented for RC.

On Wed, Nov 25, 2015 at 1:56 AM, Charles Young <notifications@github.com>
wrote:

> PH-EITI has requested that we not only allow for annotation sorting by
> page and category but also by EITI requirement. They have undertaken a
> detailed analysis of which categories are linked to the EITI requirements
> e.g. royalties category linked to EITI requirement 4.1.
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/13888372/11391268/d4375250-9359-11e5-8d64-ce5cb377518a.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/687>.
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PJHUB48&m=2060adac453d&t=20151125&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PJHUB48&m=2060adac453d&t=20151125&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01PJHUB48&m=2060adac453d&t=20151125&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by anderspeders** [comment]
@charlesyoung I think this is an intersting add-on. We will need to understand how this can be implemented but great to see that some concrete steps are taken from EITI Philippines.
