### ISSUE TITLE
Inclusion of additional annotation categories

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#688]
PH-EITI has requested that we add the following annotation categories. 

![image](https://cloud.githubusercontent.com/assets/13888372/11391440/1fd65c96-935b-11e5-992f-1129259cf4a4.png)

**Comment by KaitlinCCSI** [comment]
RC/OLC group needs to discuss process for handling such requests first.
Please don't add these categories until further instruction.

On Wed, Nov 25, 2015 at 2:00 AM, Charles Young <notifications@github.com>
wrote:

> PH-EITI has requested that we add the following annotation categories.
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/13888372/11391440/1fd65c96-935b-11e5-992f-1129259cf4a4.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/688>.
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PJI0x4H&m=7d7e83e7a61d&t=20151125&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PJI0x4H&m=7d7e83e7a61d&t=20151125&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01PJI0x4H&m=7d7e83e7a61d&t=20151125&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>
