### ISSUE TITLE
Mobile friendly contract view page

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#689]
The contract view page doesn't properly render in mobile, when even through it's made responsive. The number of components in the contract view page is high, and displaying all the views in the mobile screen makes the viewing very difficult. We need to come up with the new UI for contract view targetted to mobile and tablets only.

**Comment by anjesh** [comment]
related issues #625, #546, #545, #539, #475, #278 for reference

**Comment by anjesh** [comment]
Here's an initial idea about the mobile and tablet view with the tabs. https://invis.io/9X532LD4G
Clicking on the tabs will open view below. 

![image](https://cloud.githubusercontent.com/assets/120488/11415169/a5ef31f0-9427-11e5-922e-3bd5eeef12fa.png)

cc @anderspeders @KaitlinCCSI

**Comment by anderspeders** [comment]
Thanks @anjesh, can you please scope out the amount of days this will take to implement. We will then discuss for this or a future sprint.

**Comment by anjesh** [comment]
This is fixed.

**Comment by KaitlinCCSI** [comment]
Opened b/c mobile functionality doesn't seem to be fully working. When I open a contract on my phone, it looks like it is defaulting to the PDF view, but the annotations show up on top and the PDF is stuck below the annotations (Number 1 of screenshots below). When I click on the annotations tab, it looks the same except both the annotations tab and the PDF tab are highlighted (N. 2). When I click on the text tab, nothing changes except that the text tab is highlighted and the other ones are not (N 3). The only one that seems to work is the metadata tab -- when I click on it, it scrolls to the metadata information (although the PDF tab is also still highlighted - N. 4). (Note that while my screenshots are for a contract that does not yet have OCR text, I also tried this with a contract that does have OCR text and had the same results.)

Also, ideally the download button would not be located inside the search bar, as it blocks out type you text into the bar.

1 - ![img_2057](https://cloud.githubusercontent.com/assets/14825437/15371779/c3330bd8-1d02-11e6-86d3-ddf47d55bec1.PNG) 

2- ![img_2058](https://cloud.githubusercontent.com/assets/14825437/15371783/c335178e-1d02-11e6-8da0-47cafc41e217.PNG)

3- ![img_2056](https://cloud.githubusercontent.com/assets/14825437/15371780/c333b7e0-1d02-11e6-8bf9-fcd4be4f113a.PNG)

4- ![img_2059](https://cloud.githubusercontent.com/assets/14825437/15371784/c336a194-1d02-11e6-93c7-980a717f9599.PNG)

**Comment by anjesh** [comment]
created new issue to handle the issue with mobile view https://github.com/NRGI/resourcecontracts.org/issues/896
