### ISSUE TITLE
Front end: Basic document repository for all PDF files - also non OCR-ed

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#69]
As a user I want to be able to access all contracts - also those which have not been OCR-ed and approved for language. These PDF contracts will only be search based on metadata.

**Comment by anderspeders** [comment]
This also means that as soon as metadata has been provided to the PDF the user is able to publsih it.

**Comment by anderspeders** [comment]
As an administrator I would like to be able to publish a contract once the basic metadata has been provided.

**Comment by anjesh** [comment]
Covered in #75
