### ISSUE TITLE
Mturk Assignment page instruction in the language of contract

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#690]
The current mturk assignment page shows the instructions in english only. Now the instruction will be shown based on the language of the contract. 

Also the language field should be shown in assignment page whether it's french or english. In case of language in which the instructions are not present, english will be default language. 

The instructions for english and french are here. 
https://docs.google.com/document/d/1Jw6nYGaKs6GSbBum4iKwxRhxUcXM9dfvaVFdYR5kFVM/edit

**Comment by SamCCSI** [comment]
Please note: we need to keep the English there for French, Spanish, etc. pages -- otherwise English speaking MTers might not be able to discern that it's not the right task for them.

**Comment by anjesh** [comment]
For english, HIT appears as https://task-manish707.rhcloud.com/?pdf=https://rc-demo.s3-us-west-2.amazonaws.com/71/1.pdf&assignmentId=123&hitId=123RVWYBAZW00EXAMPLE&turkSubmitTo=https://www.mturk.com/&workerId=AZ3456EXAMPLE&lang=en 

For French, https://task-manish707.rhcloud.com/?pdf=https://rc-demo.s3-us-west-2.amazonaws.com/71/1.pdf&assignmentId=123&hitId=123RVWYBAZW00EXAMPLE&turkSubmitTo=https://www.mturk.com/&workerId=AZ3456EXAMPLE&lang=fr

For any other language than Fr and en, the page will show the instructions in En.

**Comment by SamCCSI** [comment]
For English:
- Dislaimer still refers to French documents. 
- I think we can delete it altogether as every transcriber we have had speaks (writes) English well.
![image](https://cloud.githubusercontent.com/assets/12913915/11551415/f2f62804-9946-11e5-9723-5fad8d2c37a8.png)


For French:
- Can we please make the disclaimer appear in both languages? This makes more sense, as it is actually those who DON'T speak French that we need to understand that they should not complete the task.
DISCLAIMER - IF YOU ARE NOT A FRENCH SPEAKER PLEASE DO NOT COMPLETE TASKS FOR FRENCH LANGUAGE DOCUMENTS. DUE TO ERRORS BY PREVIOUS TRANSCRIBERS, WE ARE NOT IN A POSITION TO PAY FOR TRANSCRIPTIONS OF FRENCH LANGUAGE DOCUMENTS BY NON-FRENCH SPEAKERS.
AVERTISSEMENT - SI VOUS N’ETES PAS FRANCOPHONE, NOUS VOUS PRIONS DE PAS TRAVAILLER SUR DES DOCUMENTS EN LANGUE FRANCAISE. EN RAISON D’ERREURS COMMISES PAR DE PRECEDENTS TRANSCRIPTEURS, NOUS NE SOMMES PAS EN MESURE DE PAYER POUR DES TRANSCRIPTS DE DOCUMENTS EN LANGUE FRANCAISE PAR DES NON FRANCOPHONES.

**Comment by anjesh** [comment]
Right now the text is generic for all the languages. 

Let us know if this is what you are looking for each language.

--

### English Language Contract

In this HIT, you are to transcribe the text in **English** as shown in the scanned pdf on the right. It is possible that your HIT will be rejected if we find that there are number of spelling mistakes or missing text in the transcribed text.

```
-------------------------------
[transcription box] | [pdf box]
-------------------------------
```

Other instructions for transcribers:

1. Original letters and accents should be preserved (for example for French language contracts, the letters / symbols “œ” and “æ” and the following accents should be transcribed: à ç è é ê ö).
1. Original symbols should be transcribed where possible (for example: ° as used in “N°”, or in coordinates like “53°14’477’’).
1. For non-transcribed objects such as maps, photos or illegible signatures, please provide a bracketed entry (for example: [map], [photo] or [signature]).
1. If you can read the handwritten signature, or any other handwriting, please transcribe it
1. Tables should be transcribed with pipes ( | ) as separators (for example: “Royalties | 10% | 12% | 15%”).
1. Please include any typed page numbers or other document references that appear on the page.
1. Please include a single space only between each Article of the contract.

--

### French Language Contract

In this HIT, you are to transcribe the text in **French** as shown in the scanned pdf on the right. It is possible that your HIT will be rejected if we find that there are number of spelling mistakes or missing text in the transcribed text.

**DISCLAIMER** - IF YOU ARE NOT A FRENCH SPEAKER PLEASE DO NOT COMPLETE TASKS FOR FRENCH LANGUAGE DOCUMENTS. DUE TO ERRORS BY PREVIOUS TRANSCRIBERS, WE ARE NOT IN A POSITION TO PAY FOR TRANSCRIPTIONS OF FRENCH LANGUAGE DOCUMENTS BY NON-FRENCH SPEAKERS. 
**AVERTISSEMENT** - SI VOUS N’ETES PAS FRANCOPHONE, NOUS VOUS PRIONS DE PAS TRAVAILLER SUR DES DOCUMENTS EN LANGUE FRANCAISE. EN RAISON D’ERREURS COMMISES PAR DE PRECEDENTS TRANSCRIPTEURS, NOUS NE SOMMES PAS EN MESURE DE PAYER POUR DES TRANSCRIPTS DE DOCUMENTS EN LANGUE FRANCAISE PAR DES NON FRANCOPHONES.

```
-------------------------------
[transcription box] | [pdf box]
-------------------------------
```

Autres instructions pour les transcripteurs:

1. Les lettres et accents originaux doivent être présevrés (par exemple pour les contrats en langue française, les lettres / symboles “œ” et “æ” ainsi que les accents suivants doivent être retranscrits: à ç è é ê ö).
1. Les symboles originaux doivent, dans la mesure du possible, être retranscrits (par exemple: ° utilisé dans “N°”, ou dans des coordonnées comme “53°14’477”).
1. Pour les objets non retranscrits tels les cartes, photos ou des signatures illisibles, nous vous prions de bien vouloir utiliser des crochets (par exemple: [carte], [photo], [signature])
1. Si vous pouvez lire la signature manuscrite, ou toute autre écriture, nous vous prions de la/les retranscrire.
1. Les tableaux doivent être retranscrits avec des tubes ( | ) comme séparateurs (par exemple: “Redevances | 10% | 12% | 15 % “).
1. Nous vous prions d’inclure tout numéro de pages dactylographiés ou autres références à des documents qui apparaissent sur la page
1. Nous vous prions d’utiliser un interligne simple seulement entre les articles du contrat.

--

### Other Language (e.g. Spanish) Contract

In this HIT, you are to transcribe the text in **Spanish** as shown in the scanned pdf on the right. It is possible that your HIT will be rejected if we find that there are number of spelling mistakes or missing text in the transcribed text.

```
-------------------------------
[transcription box] | [pdf box]
-------------------------------
```

Other instructions for transcribers:

1. Original letters and accents should be preserved (for example for French language contracts, the letters / symbols “œ” and “æ” and the following accents should be transcribed: à ç è é ê ö).
1. Original symbols should be transcribed where possible (for example: ° as used in “N°”, or in coordinates like “53°14’477’’).
1. For non-transcribed objects such as maps, photos or illegible signatures, please provide a bracketed entry (for example: [map], [photo] or [signature]).
1. If you can read the handwritten signature, or any other handwriting, please transcribe it
1. Tables should be transcribed with pipes ( | ) as separators (for example: “Royalties | 10% | 12% | 15%”).
1. Please include any typed page numbers or other document references that appear on the page.
1. Please include a single space only between each Article of the contract.

**Comment by SamCCSI** [comment]
This is great. Thank you!

**Comment by anjesh** [comment]
This has been fixed and updated in the task pages.
