### ISSUE TITLE
Spelling checking not working in the CMS editor

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#691]
Followup from https://github.com/NRGI/resourcecontracts.org/issues/619#issuecomment-158557347

**Comment by upasna01** [comment]
Browser spell-check is enabled, as other spell-check plugins were not available free of cost. Please review the change  
![font](https://cloud.githubusercontent.com/assets/11477899/14077779/04c85646-f50f-11e5-8bdc-7663168a3b58.png)
