### ISSUE TITLE
Editing text on the About/ FAQ/ etc pages > changing font size

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#692]
Related to issue #619 I noticed that the module for editing text on the About, etc. pages no longer allows us to change font size. The original editor did have this function - can it be included again in the new editor? Many thanks.

**Comment by anjesh** [comment]
Font size included in the editor
![image](https://cloud.githubusercontent.com/assets/120488/12113277/d0ff09ee-b3c9-11e5-9701-137b5205c7a3.png)

**Comment by JesseCCSI** [comment]
Many thanks @anjesh - just also noticed that it looks like we can't change the font style anymore either. Is this a bug, as with the previous editor we did have the ability to change fonts? I've tried making additions to the FAQs today and they appear in a different style, which I can't change using the editor.

**Comment by KaitlinCCSI** [comment]
Re-opened for Jesse's comment above.

**Comment by upasna01** [comment]
The issue have been fixed. Please review the change.
![font](https://cloud.githubusercontent.com/assets/11477899/14077791/35097682-f50f-11e5-83ef-a26211fa735e.png)

**Comment by JesseCCSI** [comment]
Thanks @upasna01 - however, in adding the font family function, it now seems that we no longer have the font size option? 

We would like to have the ability to change both the font family and the font size. 

cc @KaitlinCCSI

**Comment by KaitlinCCSI** [comment]
re-opening to address Jesse's comment

**Comment by JesseCCSI** [comment]
Just checking when the font size option will be added back in (without removing any existing editing options, e.g. the font format option)? 

Thanks.

**Comment by upasna01** [comment]
The issue is fixed but not deployed yet, will be deployed soon. Thank you for your patience.

**Comment by JesseCCSI** [comment]
Great thanks @upasna01
