### ISSUE TITLE
Annotating top line of contract

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#693]
The annotation category selection box is 'off screen' when annotating the top line of contract.  

![image](https://cloud.githubusercontent.com/assets/13888372/11423149/99619310-944a-11e5-9d3f-66f5233a3f67.png)

**Comment by sadhakbj** [comment]
- It's fixed now.
![annotate_top](https://cloud.githubusercontent.com/assets/5828622/13067679/1c0ae1be-d49b-11e5-9ecb-232b2e42544d.png)
