### ISSUE TITLE
Contract year as metadata category

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#695]
In the old platform, the year of signature was a metadata category. Now it is only an annotation category.

There are times when a contract has a discoverable year, but not a full date.

It would therefore be useful to have "Year of contract signature" as a metadata category.

Examples: the following have discoverable years, but not dates:

DRC, Gécamines, CMD [KMT] - Kolwezi - JVA Amend, 2001
DRC, Gécamines, Kinross [KCC] - Kamoto - JVA, 2004
DRC, Gécamines, Cobalt Metals, Ruashi Holding [Ruashi-Mining] - Ruashi - JVA Amend, 2004 
DRC, Gécamines, Samref [MUMI] - Mutanda - JVA, 2001 
DRC, Gécamines, CICO [COMIDE] - Mashitu / Safwe - JVA, 2002**

**Comment by anderspeders** [comment]
@anjesh Is there an option under the ISO date format to only provide the year as YYYY?

@SamCCSI Currently we extract it from the date field. It would be ideal to avoid an additional data entry category if we can - to avoid confusion. 

cc @byndcivilization

**Comment by SamCCSI** [comment]
Thanks, Anders; understood. 

If there is a way to only enter year in the existing 'date' field that will work perfectly. We are just trying to avoid creating incorrect data by dating contracts as 1 Jan [Year] when we only know the year.

**Comment by anjesh** [comment]
in this case what we could have here is have both signature date and signature year with instruction that "if you don't have signature date, just mention year". Then signature year get automatically filled when the date is entered. And we can then make the signature date optional and signature year mandatory. 

We can't put YYYY in the current existing signature-date (we could if it has been string), it gives error during the indexing process.

**Comment by SamCCSI** [comment]
Anjesh's solution sounds perfect.

**Comment by anderspeders** [comment]
@jpmckinney Do you have any thoughts here for contracts where we only have YYYY but not a full date?

**Comment by jpmckinney** [comment]
I've often just made the date a string (text/char/varchar/etc.) field in the database to allow YYYY, YYYY-MM or YYYY-MM-DD, and added custom validation to ensure you don't get values like `2015-99-99`. However, strings and dates have different indexing and sorting behavior, so there are advantages to storing the date as a date field. Having two fields (one date, one string) sounds like a reasonable compromise. However, if any logic depends on the date (e.g. filtering), it will have to look at both fields - so there is some additional complexity to either solution.

**Comment by anjesh** [comment]
Filtering will only look for one field - year (which will be mandatory). Year is extracted from signature date if present, otherwise the uploader will enter the year manually. Signature date is used for display only, and in its absence, only year will be displayed.

**Comment by anderspeders** [comment]
OK, there seems to be agreement on the way to implement this, please go ahead.

**Comment by sadhakbj** [comment]
- Fixed.
