### ISSUE TITLE
Problem with auto-filter on company dropdown on advanced search page with accented chars

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#696]
When I type "Gé" there is no filtering of company names.

![image](https://cloud.githubusercontent.com/assets/12913915/11482634/ecd74aba-9771-11e5-94ee-e5a01f918f7a.png)

When I type "Géc" it filters it as though I only typed "Gé"

![image](https://cloud.githubusercontent.com/assets/12913915/11482642/f3a69918-9771-11e5-81a7-3dc0ada31b9e.png)

**Comment by anjesh** [comment]
@hello-deepak can you see if e-accent and e are treated as same char in the dropdown module? Is it possible to change that behaviour if that is the case?

**Comment by anjesh** [comment]
@SamCCSI Gé is found in all those companies. Those letters could appear in any position in the word/phrase. E.g. AdvantaGE contains "GE" but not necessarily E with an accent. Need to check that.

**Comment by charlesyoung** [comment]
@SamCCSI can we close this ticket?

**Comment by SamCCSI** [comment]
@charlesyoung no, this issue still exists exactly as described above.

**Comment by SamCCSI** [comment]
Anjesh has explained this -- not a bug, search just works as though 'e' and 'é' are the same, which is the norm
