### ISSUE TITLE
System configuration 

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#697]
Linked to the discussion with the Philippines relating to the limitations in the system when uploading large files. 

Error: 

![image](https://cloud.githubusercontent.com/assets/13888372/11492851/1d5b2bd2-97fb-11e5-9bb0-e5c34cb90ba4.png)

**Comment by charlesyoung** [comment]
@anjesh have you had any time to look at this issue? PH-EITI is keen to finish the supporting docs upload.

**Comment by anjesh** [comment]
We have updated the config in the server and the upload works now.
