### ISSUE TITLE
Back buttons create endless loop

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#698]
I viewed the contract view page and metadata page for two contracts on RC (http://www.resourcecontracts.org/contract/ocds-591adf-BO5865778972RC and http://www.resourcecontracts.org/contract/ocds-591adf-TL0077233259RC) and tried to use the back button to get back to search results page. However, the back buttons just create endless loops, taking you from contract view page to metadata page and back again.

This seems like a bug to me -- should be able to use back button to follow previous trail that got you to the page you are on.

**Comment by anjesh** [comment]
Right now, back button link comes from the last page it is linked from. Will look into this. 
cc @manishgs

**Comment by jedm** [comment]
_Hi, per conversation with @anderspeders, adding questions to existing threads where possible..._

When clicking between results, contract page and contract metadata, Back button changes its function: When you go from Search results to a Contract page, Back goes back to results.

But after you view that contract's Metadata page, when you return to its Contract page, the Back button on goes back to Metadata page instead, so you can never get back to your results. (See attached PDF)

Also, Back button sometimes has text “Go Back” in some places but not in others. Should be consistent.

[back button.pdf](https://github.com/NRGI/resourcecontracts.org/files/123753/back.button.pdf)

**Comment by KaitlinCCSI** [comment]
Still having this problem of an endless loop between contract page and metadata page; would be great to fix it soon.

**Comment by anjesh** [comment]
Can you please check this once again? Please reopen if you still find issue regarding the endless search.

**Comment by KaitlinCCSI** [comment]
Just checked and seems fine for now.
