### ISSUE TITLE
metadata comma problems on Summary Page

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#699]
Comma has re-appeared after "Type of Contract", and there is now an extra space between end of some words and commas. There should be no commas unless they are separating two words/terms, and any commas included should not have a space before the comma.
![screen shot 2015-12-01 at 12 55 39 pm](https://cloud.githubusercontent.com/assets/14825437/11510832/3d50d3c6-982b-11e5-8ce6-c60576af90fb.png)

**Comment by anjesh** [comment]
Fixed.
