### ISSUE TITLE
Basic user access module	

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#7]
Should be role based and include scope for api access

**Comment by anjesh** [comment]
Roles for the users. These are just based on preliminary discussion. 
- Super Administrator (NRGI staff, CCSI - Columbia university)
- Country/national Administrator - National administrator should be able to approve the data uploaded by the research associate. 
- Research associate (graduate student, interns) to upload contract, provide metadata, annotate. Should be able to edit the data entered by others. 
- Citizens to upload the contract and goes to pending approval list (still need discussion)

**Comment by byndcivilization** [comment]
I would split super admin into super admin and admin. super should be for a sys admin and regular admin should really be for things like approving annotations. I don't really want to give every one the ability to delete users or contracts for instance.

**Comment by anjesh** [comment]
For sprint 1, there will be only one user (superadmin), who will have access to everything. In sprint 2, we will have the different roles with permission to different modules/process (approval of contracts, creating other users).

**Comment by anjesh** [comment]
Sprint1 access module in place where there's only superadmin user, with access to everything. 

Continuing the same ticket for sprint 2, there will be two roles for sprint 2. 
* Researcher (who can upload contract, edit contract, annotate)
* Admin (who will approve contract and annotation)

These two roles are required for the workflow of contract and annotation.

**Comment by anjesh** [comment]
@manish707 Need a simple interface to create/modify users with the following metadata. Once the user creates contracts, edits metadata, annotates, text edits, publishes, they can't be deleted but can only be unpublished (active = false) (meaning they can't login to the system)

* Email: (to be used as username)
* Password:
* Organisation:
* Roles: [multiple]
* Created Datetime
* Active

**Comment by anderspeders** [comment]
Looks good.
