### ISSUE TITLE
Words in dropdown menus cut off at line breaks

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#700]
Screenshot shows 4 examples of words in dropdown menus that are cut off in the middle at a line break. Is there a way to make this smarter so that text is either narrowed to fit onto lines, or so that words that would otherwise break halfway through simply start on the next line?
![screen shot 2015-12-01 at 6 59 15 pm](https://cloud.githubusercontent.com/assets/14825437/11519205/d9ba0a66-985d-11e5-8874-c46c2a9ef9f0.png)

**Comment by sadhakbj** [comment]
- Fixed.
![700_issue_fixed](https://cloud.githubusercontent.com/assets/5828622/12166097/7aabe322-b54b-11e5-9f36-1462fd40636a.png)
