### ISSUE TITLE
Contract PDFs - scroll to top when user clicks to next page

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#702]
When reading a contract in contract view page, I need to scroll down to read the bottom part of the page. When I click to the next page in the PDF, I'm taken to the bottom of the next page of the contract, rather than the top of the next page. Assume this is because that's the position I was in on the last page, but intuitively it would make more sense and be easier for the reader to have the subsequent contract page appear with the top of the contract viewable. This would make the flow more normal to a reader.

![screen shot 2015-12-02 at 11 58 40 am](https://cloud.githubusercontent.com/assets/14825437/11539400/723bd74a-98ec-11e5-828f-f8fb58996154.png)

![screen shot 2015-12-02 at 11 58 51 am](https://cloud.githubusercontent.com/assets/14825437/11539399/7239c2a2-98ec-11e5-96a2-5a7cfdfa6a17.png)

![screen shot 2015-12-02 at 11 58 59 am](https://cloud.githubusercontent.com/assets/14825437/11539401/723bfc3e-98ec-11e5-9b3c-8964d8a3ff95.png)

**Comment by sadhakbj** [comment]
- It's fixed now.
![Uploading after_clicking.png…]()
![before_clicking](https://cloud.githubusercontent.com/assets/5828622/12747021/b6212fa6-c9c9-11e5-99ae-30149aaf954c.png)
