### ISSUE TITLE
Contract download crash

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#703]
I get a 404 error when clinking on the download contract icon. Tested on three contracts.

**Comment by anjesh** [comment]
Got that. Download icon here shows code in the url. 

![image](https://cloud.githubusercontent.com/assets/120488/11550980/fbed7b28-999c-11e5-8b4e-c8b7737f7b31.png)

**Comment by anjesh** [comment]
This was caused due to minification of js files. Fixed now.
