### ISSUE TITLE
Search - option to click from search results to place in doc where info is located

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#705]
When search results come from dropdown, there is a way to click directly to the place in doc where those results come from. But when search results come from free text search, there is no way to click to the place in doc where those results come from. Is it possible to add this feature for searches done through free text search bar? Clicking “text” and “annotation” bubbles would be intuitive.

![screen shot 2015-12-03 at 11 33 07 am](https://cloud.githubusercontent.com/assets/14825437/11568531/537856e6-99b2-11e5-8dad-4a550660a8b0.png)

![screen shot 2015-12-03 at 11 33 36 am](https://cloud.githubusercontent.com/assets/14825437/11568530/5374b482-99b2-11e5-96a1-853bf9ba8ab9.png)

**Comment by anderspeders** [comment]
Just to confirm here that the request is focusing on improving deep linking for both **text in the search field** and **annotations**:

**Comment by sadhakbj** [comment]
We have implemented the click functionality in the search results page.
As seen in the image below:
![705](https://cloud.githubusercontent.com/assets/5828622/12969156/73c9f548-d0a4-11e5-976b-5844a7175300.png)

Please check at: http://rc-site-demo.elasticbeanstalk.com/olc/public/search?q=contract

**Comment by sadhakbj** [comment]
We have improved and implemented this feature.
![705_done](https://cloud.githubusercontent.com/assets/5828622/13047684/ed96c0ec-d408-11e5-91e8-674dad415270.png)

**Comment by JesseCCSI** [comment]
We noted the following issues today: 

1. This feature functions differently on different computers. For @SamCCSI, the grey ovals (Text/ Annotation/ Metadata) were hyperlinked, while for @KaitlinCCSI and I they were not. 
2. Similarly, when Sam clicked on the hyperlinked text or ovals that link to the contract view page (first and second links in your screenshot above), this directed him to the Text view of the contract, while Kaitlin and myself were directed to the PDF view. 

Can we please: 

1. Hyperlink the grey ovals in addition to the relevant text, and 
2. Make sure that the links are to the PDF view of the contract, not the Text view

**Comment by KaitlinCCSI** [comment]
Re-opening to address comments above.

**Comment by anderspeders** [comment]
Thanks @KaitlinCCSI, 

@anjesh: Can you check up on this?

**Comment by anjesh** [comment]
@JesseCCSI 
>  Hyperlink the grey ovals in addition to the relevant text, and

This will be taken care of 

>  Make sure that the links are to the PDF view of the contract, not the Text view

With the links in the annotation and text in results, annotation link might point to pdf or text depending upon where the annotation is done. With the text result, it will always be linked to text view and not pdf view, as search is available and possible only in text-view.

**Comment by JesseCCSI** [comment]
Thanks @anjesh 

This seems fine, but re this comment: 

_With the links in the annotation and text in results, annotation link might point to pdf or text depending upon where the annotation is done. _

Kaitlin, Sam and I were getting different results on different computers for the same contract (i.e. Sam was directed to the text view, and Kaitlin and I were directed to the PDF view). Is there a way to make this consistent? 

cc @KaitlinCCSI @SamCCSI

**Comment by upasna01** [comment]
The issue have been fixed. Please review changes. Here is the screenshot for search links.
![search-links](https://cloud.githubusercontent.com/assets/11477899/13417697/62b33516-df96-11e5-9414-10b00fa1d187.png)

**Comment by JesseCCSI** [comment]
Thanks @upasna01 this appears ok, except for the bug highlighted by @KaitlinCCSI regarding the annotation boxes (in issues #801 and #793)
