### ISSUE TITLE
Backend: Move Document type above Contract type

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#706]
Document type should appear before contract type on the backend, as contract type is a sub set of document type (which is a broader group). This is to ensure clarity of process in the mind of the annotator: Step 1 select Doc Type; Step 2 (if applicable) select Contract Type.

![image](https://cloud.githubusercontent.com/assets/12913915/11570324/b04b3c00-99c4-11e5-84fb-82a1e1e09212.png)

As agreed with @anderspeders

**Comment by anjesh** [comment]
Does "Step 2, if  applicable" means Contract type is now optional (remove the *) and Doc type is mandatory. Please confirm. @anderspeders @SamCCSI

**Comment by SamCCSI** [comment]
It has been suggested, but the group has yet to decide on this -- apologies for any confusion.

**Comment by anderspeders** [comment]
It would be great to hear the view of Perrine and team, 

I would tend to vote Document type above Contract type, but do not have a strong opinion.

**Comment by SamCCSI** [comment]
This is to confirm that Document Type should be mandatory.

If it is possible to make contract type mandatory only when document type = contract, that would be ideal. Otherwise, contract type should not be mandatory (and we will stress in guidance that annotators must fill in contract type when document type = contract).

**Comment by anjesh** [comment]
Copying comments from https://github.com/NRGI/resourcecontracts.org/issues/776.

> These two codelist related issues should also be addressed along with this issue https://github.com/NRGI/resourcecontracts.org/issues/721 and https://github.com/NRGI/resourcecontracts.org/issues/720

> Here's the codelists for [contract-type](https://docs.google.com/spreadsheets/d/15k-7NCkgu1p2eKgWGZnykASLQoa4gR6fOLskV8mdOhY/edit?ts=566690b1#gid=0) and [document-type](https://docs.google.com/spreadsheets/d/15k-7NCkgu1p2eKgWGZnykASLQoa4gR6fOLskV8mdOhY/edit?ts=566690b1#gid=1026386158)

**Comment by hello-deepak** [comment]
According to  [Contract-type-codelist](https://docs.google.com/spreadsheets/d/15k-7NCkgu1p2eKgWGZnykASLQoa4gR6fOLskV8mdOhY/edit?ts=566690b1#gid=0) , the contract-type which needs to be deleted contains following contract

Joint Venture Agreement
-> 61 Contracts
		http://admin.resourcecontracts.org/contract/1371
		http://admin.resourcecontracts.org/contract/709
		http://admin.resourcecontracts.org/contract/1358
		http://admin.resourcecontracts.org/contract/1052
		http://admin.resourcecontracts.org/contract/1384
		http://admin.resourcecontracts.org/contract/1388
		http://admin.resourcecontracts.org/contract/1252
		http://admin.resourcecontracts.org/contract/707
		http://admin.resourcecontracts.org/contract/1352
		http://admin.resourcecontracts.org/contract/1367
		http://admin.resourcecontracts.org/contract/873
		http://admin.resourcecontracts.org/contract/1377
		http://admin.resourcecontracts.org/contract/1387
		http://admin.resourcecontracts.org/contract/1375
		http://admin.resourcecontracts.org/contract/871
		http://admin.resourcecontracts.org/contract/1051
		http://admin.resourcecontracts.org/contract/1356
		http://admin.resourcecontracts.org/contract/1379
		http://admin.resourcecontracts.org/contract/1391
		http://admin.resourcecontracts.org/contract/705
		http://admin.resourcecontracts.org/contract/1376
		http://admin.resourcecontracts.org/contract/1274
		http://admin.resourcecontracts.org/contract/1369
		http://admin.resourcecontracts.org/contract/1348
		http://admin.resourcecontracts.org/contract/1363
		http://admin.resourcecontracts.org/contract/1351
		http://admin.resourcecontracts.org/contract/1353
		http://admin.resourcecontracts.org/contract/1200
		http://admin.resourcecontracts.org/contract/706
		http://admin.resourcecontracts.org/contract/1361
		http://admin.resourcecontracts.org/contract/1370
		http://admin.resourcecontracts.org/contract/1386
		http://admin.resourcecontracts.org/contract/1383
		http://admin.resourcecontracts.org/contract/1564
		http://admin.resourcecontracts.org/contract/704
		http://admin.resourcecontracts.org/contract/1349
		http://admin.resourcecontracts.org/contract/1350
		http://admin.resourcecontracts.org/contract/1359
		http://admin.resourcecontracts.org/contract/1360
		http://admin.resourcecontracts.org/contract/1255
		http://admin.resourcecontracts.org/contract/1256
		http://admin.resourcecontracts.org/contract/1357
		http://admin.resourcecontracts.org/contract/1354
		http://admin.resourcecontracts.org/contract/1257
		http://admin.resourcecontracts.org/contract/711
		http://admin.resourcecontracts.org/contract/710
		http://admin.resourcecontracts.org/contract/1254
		http://admin.resourcecontracts.org/contract/1390
		http://admin.resourcecontracts.org/contract/1365
		http://admin.resourcecontracts.org/contract/1380
		http://admin.resourcecontracts.org/contract/1420
		http://admin.resourcecontracts.org/contract/1355
		http://admin.resourcecontracts.org/contract/1372
		http://admin.resourcecontracts.org/contract/1393
		http://admin.resourcecontracts.org/contract/1364
		http://admin.resourcecontracts.org/contract/1373
		http://admin.resourcecontracts.org/contract/1265
		http://admin.resourcecontracts.org/contract/1381
		http://admin.resourcecontracts.org/contract/1201
		http://admin.resourcecontracts.org/contract/870
		http://admin.resourcecontracts.org/contract/708

Land Lease Agreement
-> 22 contracts
		http://admin.resourcecontracts.org/contract/1040
		http://admin.resourcecontracts.org/contract/1180
		http://admin.resourcecontracts.org/contract/1039
		http://admin.resourcecontracts.org/contract/1036
		http://admin.resourcecontracts.org/contract/1021
		http://admin.resourcecontracts.org/contract/1031
		http://admin.resourcecontracts.org/contract/1041
		http://admin.resourcecontracts.org/contract/1030
		http://admin.resourcecontracts.org/contract/1027
		http://admin.resourcecontracts.org/contract/1024
		http://admin.resourcecontracts.org/contract/1020
		http://admin.resourcecontracts.org/contract/1022
		http://admin.resourcecontracts.org/contract/1035
		http://admin.resourcecontracts.org/contract/1037
		http://admin.resourcecontracts.org/contract/1038
		http://admin.resourcecontracts.org/contract/1049
		http://admin.resourcecontracts.org/contract/1048
		http://admin.resourcecontracts.org/contract/1023
		http://admin.resourcecontracts.org/contract/1033
		http://admin.resourcecontracts.org/contract/1029
		http://admin.resourcecontracts.org/contract/1042
		http://admin.resourcecontracts.org/contract/1047


Memorandum of Understanding
-> 4 Contracts
		http://admin.resourcecontracts.org/contract/1032
		http://admin.resourcecontracts.org/contract/1179
		http://admin.resourcecontracts.org/contract/1178
		http://admin.resourcecontracts.org/contract/1026


Similarly for the document type which needs to be deleted according to [document-type-codelist](https://docs.google.com/spreadsheets/d/15k-7NCkgu1p2eKgWGZnykASLQoa4gR6fOLskV8mdOhY/edit?ts=566690b1#gid=1026386158) contains the following contract

Translated Contract
-> 6 Contracts
		http://admin.resourcecontracts.org/contract/1036
		http://admin.resourcecontracts.org/contract/37
		http://admin.resourcecontracts.org/contract/1057
		http://admin.resourcecontracts.org/contract/1058
		http://admin.resourcecontracts.org/contract/1309
		http://admin.resourcecontracts.org/contract/1059

**Comment by anderspeders** [comment]
I suggest that these are all re-categorised from <Translated Contract> to <Contract> under <Document Type>. 

Once <Translated contract> has been added as a field under <Contract Type> we will be able to assign this. 

@SamCCSI @KaitlinCCSI Some of these are OLC contracts - so please confirm.

**Comment by SamCCSI** [comment]
Can you please hold off on progressing this for the moment -- we are still determining exactly how the rules for contract tally will work, and we are not sure if any further changes to the codelist will be needed. We will endeavor to get back to you as soon as possible.

**Comment by anderspeders** [comment]
Sounds good.

**Comment by SamCCSI** [comment]
@hello-deepak those 6 contracts should be categorized as follows:
Document type = Contract.
Contract type = Translated Contract.

cc: @anderspeders

**Comment by sadhakbj** [comment]
@SamCCSI
Contract - [#1036]( http://admin.resourcecontracts.org/contract/1036 ) could'nt be updated because this contract contain any resource which is a mandatory field to edit / create a contract. Please review this particular contract while other 5 contracts have been updated. 

Closing the issue for now.
