### ISSUE TITLE
Automatically mark contracts with no Document Type as "Contract"

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#707]
300 contracts are missing a document type: http://resourcecontracts.elasticbeanstalk.com/contract?type=metadata&word=document_type&issue=missing

1. Can YI please auto-mark all of these so that their Document Type = Contract? 
2. CCSI will then address this in its quality control / cleaning / retrofitting process.
3. To help with this, can YI please provide us with a list of hyperlinks for each contract that has been altered so that we can swiftly review? (It can be in the same form as the above search if easier - we would just need something that indicates which ones have been automatically assigned the Document type of contract)

**Comment by hello-deepak** [comment]
Contracts with empty document type: 

http:/admin.resourcecontracts.org/contract/1333
http:/admin.resourcecontracts.org/contract/1332
http:/admin.resourcecontracts.org/contract/1331
http:/admin.resourcecontracts.org/contract/1330
http:/admin.resourcecontracts.org/contract/1329
http:/admin.resourcecontracts.org/contract/1328
http:/admin.resourcecontracts.org/contract/1327
http:/admin.resourcecontracts.org/contract/1326
http:/admin.resourcecontracts.org/contract/1325
http:/admin.resourcecontracts.org/contract/1324
http:/admin.resourcecontracts.org/contract/1323
http:/admin.resourcecontracts.org/contract/1322
http:/admin.resourcecontracts.org/contract/1321
http:/admin.resourcecontracts.org/contract/1320
http:/admin.resourcecontracts.org/contract/1319
http:/admin.resourcecontracts.org/contract/1318
http:/admin.resourcecontracts.org/contract/1317
http:/admin.resourcecontracts.org/contract/1316
http:/admin.resourcecontracts.org/contract/1312
http:/admin.resourcecontracts.org/contract/1297
http:/admin.resourcecontracts.org/contract/1295
http:/admin.resourcecontracts.org/contract/1293
http:/admin.resourcecontracts.org/contract/1291
http:/admin.resourcecontracts.org/contract/1290
http:/admin.resourcecontracts.org/contract/1287
http:/admin.resourcecontracts.org/contract/1286
http:/admin.resourcecontracts.org/contract/1285
http:/admin.resourcecontracts.org/contract/1284
http:/admin.resourcecontracts.org/contract/1282
http:/admin.resourcecontracts.org/contract/1013
http:/admin.resourcecontracts.org/contract/1007
http:/admin.resourcecontracts.org/contract/1006
http:/admin.resourcecontracts.org/contract/1005
http:/admin.resourcecontracts.org/contract/1004
http:/admin.resourcecontracts.org/contract/1003
http:/admin.resourcecontracts.org/contract/1002
http:/admin.resourcecontracts.org/contract/1001
http:/admin.resourcecontracts.org/contract/1000
http:/admin.resourcecontracts.org/contract/999
http:/admin.resourcecontracts.org/contract/997
http:/admin.resourcecontracts.org/contract/996
http:/admin.resourcecontracts.org/contract/995
http:/admin.resourcecontracts.org/contract/994
http:/admin.resourcecontracts.org/contract/993
http:/admin.resourcecontracts.org/contract/992
http:/admin.resourcecontracts.org/contract/990
http:/admin.resourcecontracts.org/contract/989
http:/admin.resourcecontracts.org/contract/988
http:/admin.resourcecontracts.org/contract/987
http:/admin.resourcecontracts.org/contract/986
http:/admin.resourcecontracts.org/contract/985
http:/admin.resourcecontracts.org/contract/984
http:/admin.resourcecontracts.org/contract/983
http:/admin.resourcecontracts.org/contract/982
http:/admin.resourcecontracts.org/contract/981
http:/admin.resourcecontracts.org/contract/980
http:/admin.resourcecontracts.org/contract/979
http:/admin.resourcecontracts.org/contract/978
http:/admin.resourcecontracts.org/contract/977
http:/admin.resourcecontracts.org/contract/976
http:/admin.resourcecontracts.org/contract/975
http:/admin.resourcecontracts.org/contract/974
http:/admin.resourcecontracts.org/contract/973
http:/admin.resourcecontracts.org/contract/972
http:/admin.resourcecontracts.org/contract/971
http:/admin.resourcecontracts.org/contract/970
http:/admin.resourcecontracts.org/contract/969
http:/admin.resourcecontracts.org/contract/968
http:/admin.resourcecontracts.org/contract/967
http:/admin.resourcecontracts.org/contract/966
http:/admin.resourcecontracts.org/contract/965
http:/admin.resourcecontracts.org/contract/964
http:/admin.resourcecontracts.org/contract/963
http:/admin.resourcecontracts.org/contract/962
http:/admin.resourcecontracts.org/contract/961
http:/admin.resourcecontracts.org/contract/952
http:/admin.resourcecontracts.org/contract/953
http:/admin.resourcecontracts.org/contract/949
http:/admin.resourcecontracts.org/contract/948
http:/admin.resourcecontracts.org/contract/947
http:/admin.resourcecontracts.org/contract/946
http:/admin.resourcecontracts.org/contract/945
http:/admin.resourcecontracts.org/contract/944
http:/admin.resourcecontracts.org/contract/942
http:/admin.resourcecontracts.org/contract/943
http:/admin.resourcecontracts.org/contract/941
http:/admin.resourcecontracts.org/contract/939
http:/admin.resourcecontracts.org/contract/938
http:/admin.resourcecontracts.org/contract/937
http:/admin.resourcecontracts.org/contract/936
http:/admin.resourcecontracts.org/contract/934
http:/admin.resourcecontracts.org/contract/933
http:/admin.resourcecontracts.org/contract/932
http:/admin.resourcecontracts.org/contract/931
http:/admin.resourcecontracts.org/contract/930
http:/admin.resourcecontracts.org/contract/929
http:/admin.resourcecontracts.org/contract/928
http:/admin.resourcecontracts.org/contract/927
http:/admin.resourcecontracts.org/contract/926
http:/admin.resourcecontracts.org/contract/925
http:/admin.resourcecontracts.org/contract/924
http:/admin.resourcecontracts.org/contract/923
http:/admin.resourcecontracts.org/contract/922
http:/admin.resourcecontracts.org/contract/921
http:/admin.resourcecontracts.org/contract/920
http:/admin.resourcecontracts.org/contract/919
http:/admin.resourcecontracts.org/contract/917
http:/admin.resourcecontracts.org/contract/918
http:/admin.resourcecontracts.org/contract/916
http:/admin.resourcecontracts.org/contract/915
http:/admin.resourcecontracts.org/contract/913
http:/admin.resourcecontracts.org/contract/914
http:/admin.resourcecontracts.org/contract/912
http:/admin.resourcecontracts.org/contract/911
http:/admin.resourcecontracts.org/contract/910
http:/admin.resourcecontracts.org/contract/909
http:/admin.resourcecontracts.org/contract/908
http:/admin.resourcecontracts.org/contract/906
http:/admin.resourcecontracts.org/contract/907
http:/admin.resourcecontracts.org/contract/905
http:/admin.resourcecontracts.org/contract/904
http:/admin.resourcecontracts.org/contract/903
http:/admin.resourcecontracts.org/contract/902
http:/admin.resourcecontracts.org/contract/901
http:/admin.resourcecontracts.org/contract/900
http:/admin.resourcecontracts.org/contract/899
http:/admin.resourcecontracts.org/contract/898
http:/admin.resourcecontracts.org/contract/897
http:/admin.resourcecontracts.org/contract/896
http:/admin.resourcecontracts.org/contract/895
http:/admin.resourcecontracts.org/contract/894
http:/admin.resourcecontracts.org/contract/892
http:/admin.resourcecontracts.org/contract/888
http:/admin.resourcecontracts.org/contract/887
http:/admin.resourcecontracts.org/contract/886
http:/admin.resourcecontracts.org/contract/885
http:/admin.resourcecontracts.org/contract/884
http:/admin.resourcecontracts.org/contract/883
http:/admin.resourcecontracts.org/contract/882
http:/admin.resourcecontracts.org/contract/880
http:/admin.resourcecontracts.org/contract/881
http:/admin.resourcecontracts.org/contract/878
http:/admin.resourcecontracts.org/contract/879
http:/admin.resourcecontracts.org/contract/877
http:/admin.resourcecontracts.org/contract/876
http:/admin.resourcecontracts.org/contract/872
http:/admin.resourcecontracts.org/contract/873
http:/admin.resourcecontracts.org/contract/870
http:/admin.resourcecontracts.org/contract/865
http:/admin.resourcecontracts.org/contract/864
http:/admin.resourcecontracts.org/contract/863
http:/admin.resourcecontracts.org/contract/861
http:/admin.resourcecontracts.org/contract/862
http:/admin.resourcecontracts.org/contract/860
http:/admin.resourcecontracts.org/contract/859
http:/admin.resourcecontracts.org/contract/858
http:/admin.resourcecontracts.org/contract/857
http:/admin.resourcecontracts.org/contract/856
http:/admin.resourcecontracts.org/contract/854
http:/admin.resourcecontracts.org/contract/855
http:/admin.resourcecontracts.org/contract/852
http:/admin.resourcecontracts.org/contract/851
http:/admin.resourcecontracts.org/contract/850
http:/admin.resourcecontracts.org/contract/849
http:/admin.resourcecontracts.org/contract/848
http:/admin.resourcecontracts.org/contract/847
http:/admin.resourcecontracts.org/contract/846
http:/admin.resourcecontracts.org/contract/842
http:/admin.resourcecontracts.org/contract/841
http:/admin.resourcecontracts.org/contract/840
http:/admin.resourcecontracts.org/contract/839
http:/admin.resourcecontracts.org/contract/835
http:/admin.resourcecontracts.org/contract/832
http:/admin.resourcecontracts.org/contract/831
http:/admin.resourcecontracts.org/contract/830
http:/admin.resourcecontracts.org/contract/829
http:/admin.resourcecontracts.org/contract/827
http:/admin.resourcecontracts.org/contract/828
http:/admin.resourcecontracts.org/contract/825
http:/admin.resourcecontracts.org/contract/824
http:/admin.resourcecontracts.org/contract/820
http:/admin.resourcecontracts.org/contract/821
http:/admin.resourcecontracts.org/contract/819
http:/admin.resourcecontracts.org/contract/818
http:/admin.resourcecontracts.org/contract/817
http:/admin.resourcecontracts.org/contract/816
http:/admin.resourcecontracts.org/contract/815
http:/admin.resourcecontracts.org/contract/814
http:/admin.resourcecontracts.org/contract/813
http:/admin.resourcecontracts.org/contract/812
http:/admin.resourcecontracts.org/contract/811
http:/admin.resourcecontracts.org/contract/810
http:/admin.resourcecontracts.org/contract/809
http:/admin.resourcecontracts.org/contract/808
http:/admin.resourcecontracts.org/contract/807
http:/admin.resourcecontracts.org/contract/806
http:/admin.resourcecontracts.org/contract/805
http:/admin.resourcecontracts.org/contract/804
http:/admin.resourcecontracts.org/contract/803
http:/admin.resourcecontracts.org/contract/801
http:/admin.resourcecontracts.org/contract/799
http:/admin.resourcecontracts.org/contract/800
http:/admin.resourcecontracts.org/contract/798
http:/admin.resourcecontracts.org/contract/797
http:/admin.resourcecontracts.org/contract/796
http:/admin.resourcecontracts.org/contract/794
http:/admin.resourcecontracts.org/contract/795
http:/admin.resourcecontracts.org/contract/793
http:/admin.resourcecontracts.org/contract/792
http:/admin.resourcecontracts.org/contract/791
http:/admin.resourcecontracts.org/contract/790
http:/admin.resourcecontracts.org/contract/788
http:/admin.resourcecontracts.org/contract/789
http:/admin.resourcecontracts.org/contract/787
http:/admin.resourcecontracts.org/contract/786
http:/admin.resourcecontracts.org/contract/785
http:/admin.resourcecontracts.org/contract/784
http:/admin.resourcecontracts.org/contract/783
http:/admin.resourcecontracts.org/contract/782
http:/admin.resourcecontracts.org/contract/781
http:/admin.resourcecontracts.org/contract/780
http:/admin.resourcecontracts.org/contract/779
http:/admin.resourcecontracts.org/contract/778
http:/admin.resourcecontracts.org/contract/774
http:/admin.resourcecontracts.org/contract/775
http:/admin.resourcecontracts.org/contract/773
http:/admin.resourcecontracts.org/contract/772
http:/admin.resourcecontracts.org/contract/770
http:/admin.resourcecontracts.org/contract/771
http:/admin.resourcecontracts.org/contract/769
http:/admin.resourcecontracts.org/contract/768
http:/admin.resourcecontracts.org/contract/767
http:/admin.resourcecontracts.org/contract/764
http:/admin.resourcecontracts.org/contract/763
http:/admin.resourcecontracts.org/contract/762
http:/admin.resourcecontracts.org/contract/761
http:/admin.resourcecontracts.org/contract/760
http:/admin.resourcecontracts.org/contract/759
http:/admin.resourcecontracts.org/contract/757
http:/admin.resourcecontracts.org/contract/758
http:/admin.resourcecontracts.org/contract/756
http:/admin.resourcecontracts.org/contract/755
http:/admin.resourcecontracts.org/contract/754
http:/admin.resourcecontracts.org/contract/753
http:/admin.resourcecontracts.org/contract/751
http:/admin.resourcecontracts.org/contract/752
http:/admin.resourcecontracts.org/contract/750
http:/admin.resourcecontracts.org/contract/749
http:/admin.resourcecontracts.org/contract/748
http:/admin.resourcecontracts.org/contract/747
http:/admin.resourcecontracts.org/contract/746
http:/admin.resourcecontracts.org/contract/745
http:/admin.resourcecontracts.org/contract/744
http:/admin.resourcecontracts.org/contract/743
http:/admin.resourcecontracts.org/contract/742
http:/admin.resourcecontracts.org/contract/741
http:/admin.resourcecontracts.org/contract/740
http:/admin.resourcecontracts.org/contract/739
http:/admin.resourcecontracts.org/contract/738
http:/admin.resourcecontracts.org/contract/737
http:/admin.resourcecontracts.org/contract/736
http:/admin.resourcecontracts.org/contract/733
http:/admin.resourcecontracts.org/contract/728
http:/admin.resourcecontracts.org/contract/727
http:/admin.resourcecontracts.org/contract/726
http:/admin.resourcecontracts.org/contract/723
http:/admin.resourcecontracts.org/contract/722
http:/admin.resourcecontracts.org/contract/721
http:/admin.resourcecontracts.org/contract/720
http:/admin.resourcecontracts.org/contract/719
http:/admin.resourcecontracts.org/contract/716
http:/admin.resourcecontracts.org/contract/715
http:/admin.resourcecontracts.org/contract/714
http:/admin.resourcecontracts.org/contract/709
http:/admin.resourcecontracts.org/contract/708
http:/admin.resourcecontracts.org/contract/706
http:/admin.resourcecontracts.org/contract/705
http:/admin.resourcecontracts.org/contract/704
http:/admin.resourcecontracts.org/contract/702
http:/admin.resourcecontracts.org/contract/701
http:/admin.resourcecontracts.org/contract/699
http:/admin.resourcecontracts.org/contract/698
http:/admin.resourcecontracts.org/contract/696
http:/admin.resourcecontracts.org/contract/697
http:/admin.resourcecontracts.org/contract/695
http:/admin.resourcecontracts.org/contract/694
http:/admin.resourcecontracts.org/contract/693
http:/admin.resourcecontracts.org/contract/692
http:/admin.resourcecontracts.org/contract/691
http:/admin.resourcecontracts.org/contract/690
http:/admin.resourcecontracts.org/contract/689
http:/admin.resourcecontracts.org/contract/688
http:/admin.resourcecontracts.org/contract/687
http:/admin.resourcecontracts.org/contract/686
http:/admin.resourcecontracts.org/contract/685
http:/admin.resourcecontracts.org/contract/678
http:/admin.resourcecontracts.org/contract/676
http:/admin.resourcecontracts.org/contract/675

**Comment by anjesh** [comment]
All the above listed contracts have been marked with "Document Type" = "Contract. 
Do reopen if you find any issues.

**Comment by SamCCSI** [comment]
This is incredibly helpful. Thank you @anjesh @hello-deepak
