### ISSUE TITLE
Document type should be a filter category on the contract advanced search page

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#709]
Document type should be a filter category on the contract advanced search page (http://www.resourcecontracts.org/search?q=)

![image](https://cloud.githubusercontent.com/assets/12913915/11575421/e85e65a8-99de-11e5-9e95-7e11dddb934b.png)

**Comment by anjesh** [comment]
@anderspeders  please confirm on this one.

**Comment by SamCCSI** [comment]
@anderspeders This is part of our Proposal that covers contract tallies, auto-naming, associated docs, etc.

**Comment by upasna01** [comment]
Please review the sample mock up for the search page and do comment if any changes required. 
![searchh](https://cloud.githubusercontent.com/assets/11477899/13493701/b01539a8-e167-11e5-9eff-55334c399956.png)

**Comment by anderspeders** [comment]
@SamCCSI Any thoughts?

**Comment by SamCCSI** [comment]
This looks great.

Only requested change is for "Year Signed" to be moved two places to the right.

**Comment by anderspeders** [comment]
Sounds good,

Anjesh: please go ahead and implement. This guidance be clear enough so that no mock is required.

**Comment by anderspeders** [comment]
cc @upasna01

**Comment by SamCCSI** [comment]
Not sure what the status is for this ticket — the front-end doesn't seem to reflect the mock-up yet?

**Comment by manishgs** [comment]
We haven't deployed sprint 14 tasks yet. We are waiting reply from @anderspeders for deployment.

**Comment by hello-deepak** [comment]
Language and document type is part of filter.
![1](https://cloud.githubusercontent.com/assets/7577697/14105087/0d1b537e-f5c9-11e5-94bb-3b804d8ee1d1.png)
