### ISSUE TITLE
Linking to annotations - bug in page number listing

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#711]
When I save a hyperlink to a specific annotation that appears on p. 11, the URL takes me to the correct page, but for some reason lists the page number incorrectly.

See example: http://www.resourcecontracts.org/contract/ocds-591adf-LR2709430786RC/view#/pdf/page/11/annotation/13246

Annotation is on p. 11. URL takes me to p. 11, but the site treats it as p. 1, so if I try to click on to the next page it takes me to p. 2 instead of p. 12.

![image](https://cloud.githubusercontent.com/assets/12913915/11590653/9e2b9830-9a5f-11e5-8bb4-f6239e620bfe.png)

**Comment by sadhakbj** [comment]
- Fixed.
![Uploading 711_edited.png…]()
