### ISSUE TITLE
Discrepancy between backend and frontend cluster categories

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#713]
Backend cluster categories are in rows 2, 19, 20, 30, 43, 65, 72, 80, 92 of the Codelist (https://docs.google.com/spreadsheets/d/1tRRcib0VNynipkk83m4Be1vRaSslCKHzoIxmmC1oPLQ/edit?usp=sharing). These are greyed out in annotation module, which helps reminds annotator that they are cluster categories, not annotation categories.
![image](https://cloud.githubusercontent.com/assets/12913915/11599939/9d24a00c-9a97-11e5-9ad7-da7b200ed524.png)

But the frontend uses different cluster categories, as set out in column C of the Codelist. 
![image](https://cloud.githubusercontent.com/assets/12913915/11599884/583d0c40-9a97-11e5-8595-975d1f6dcf14.png)

This is confusing: the frontend cluster categories should be the ones used on the backend. Is that what will happen going forward?

**Comment by KaitlinCCSI** [comment]
Just to clarify: the cluster categories used on the *frontend* are the ones that should be used on the *backend*. In other words, General, Environment, Fiscal, Operations, Social, Other are fine for the frontend (though we may send a proposal for changing "General" or "Other"), but it would be less confusing if these same terms were used on the backend as well.

**Comment by anderspeders** [comment]
This will be addressed with a call based on group approved changes in this document: 
https://docs.google.com/spreadsheets/d/15k-7NCkgu1p2eKgWGZnykASLQoa4gR6fOLskV8mdOhY/edit#gid=1269728352

Once changes are signed off in the document YI will implement.

**Comment by SamCCSI** [comment]
Hi all,

We have made changes to the document based on the following understanding of columns D and E:

1 - "annotation category" means the name of an annotation field. So, we only fill that in if the annotation name is changing -- see eg. Row 8. For the clusters, we leave this column blank, unless the name is changing like in Row 16. I have therefore deleted the entries of all clusters (except Row 16, whose name is changing).

2 - "New cluster" means the type of cluster, which is why all of the backend and frontend cluster categories say "Organizational".

**Comment by SamCCSI** [comment]
Another question that has arisen re "New cluster": 

Right now this column contains new substantive clusters that will be publicly displayed on the site (eg "General"). It also contains the cluster TYPE "organizational", which presumably will not be displayed on the site. Is this correct?

We have never defined cluster TYPEs before, so we want to make sure what the implications of this are before we proceed. It also seems that if the above is correct then this field is mixing two types of entry: (i) the creation of new clusters (such as "General"), and (ii) the description of the Type of entry (eg. organizational cluster).

@anderspeders @anjesh 
CC @KaitlinCCSI

**Comment by upasna01** [comment]
Annotations and cluster categories are used as defined in the following spreadsheet. 
https://docs.google.com/spreadsheets/d/1K0wlloEAPFncrNA_mwBjqvW81A5xRpFlK0qlv-j5ZYo/edit#gid=1612543715
Please review
