### ISSUE TITLE
Alterations / amendments to the annotation codelist

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#714]
https://docs.google.com/spreadsheets/d/1tRRcib0VNynipkk83m4Be1vRaSslCKHzoIxmmC1oPLQ/edit?usp=sharing

We have entered various comments on the annotation codelist for alterations / amendments. I can log them on Github if needed but hopefully the codelist can just be worked off directly.

We are still deliberating on several issues regarding the codelist - if these result in additional requests I will log them on this issue.

**Comment by upasna01** [comment]
We have followed the code list present in the spreadsheet.Thank you for your help.

**Comment by SamCCSI** [comment]
@upasna01 @anjesh would it be possible to move the annotation category "Size of concession area" to under the "General" annotation cluster? (It currently is under the 'Legal rules' category, which makes less sense).

![image](https://cloud.githubusercontent.com/assets/12913915/22038412/11a1a69a-dcc9-11e6-86cc-ec7a626af8c0.png)

cc @charlesyoung

**Comment by charlesyoung** [comment]
Sounds good to me.

**Comment by man-git007** [comment]
@SamCCSI We have updated the annotation category code list and deployed it in the staging server.

**Comment by SamCCSI** [comment]
Hi @man-git007 the below was the requested change. I don't think it has been added to the staging, as "Size of concession area" annotation category still appears under "Legal rules" and not under "General". See this example https://staging.openlandcontracts.org/contract/ocds-591adf-1515482442/view#/pdf This might be because that codelist doc hasn't been updated to include this change? 

> @upasna01 @anjesh would it be possible to move the annotation category "Size of concession area" to under the "General" annotation cluster? (It currently is under the 'Legal rules' category, which makes less sense).
> 
> ![image](https://cloud.githubusercontent.com/assets/12913915/22038412/11a1a69a-dcc9-11e6-86cc-ec7a626af8c0.png)
> 
> cc @charlesyoung

**Comment by man-git007** [comment]
@SamCCSI The code list has been updated in the RC admin side but in the subsite, the category, and cluster is fetched from the elastic search server. So we need to update/ reindex the data in the elastic search as we. This might take some time and we will start working on it and will inform you asap.

**Comment by man-git007** [comment]
@SamCCSI The code list has been updated in elastic search as well and has deployed it in the staging server. Please verify.

**Comment by SamCCSI** [comment]
Thanks @man-git007 looks great - happy for this to be deployed

**Comment by man-git007** [comment]
@SamCCSI This has been deployed in production.

cc @anjesh
