### ISSUE TITLE
Sign-posting missing pages or annexes

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#715]
(1) Please add 2 metadata check boxes: "Pages missing from copy", and "Annexes missing from copy". If either of these is checked, the respective tect should appear on the Metadata column on the Right hand side of the contract view page: 

"Pages missing from copy" Checked --> "Please note: this document has been identified as missing one or more pages and may be incomplete."

"Annexes missing from copy" --> "Please note: this document has been identified as missing one or more annexes and may be incomplete."

(2) Once (1) is complete, please delete the following annotation categories for future contracts: 
"Document notes"; "Pages missing from  copy"; "Annexes missing from copy"; "Other".

**Comment by KaitlinCCSI** [comment]
Suggestion for messages to make more concise:

"Pages missing from copy" Checked --> "This document is missing one or more pages."

"Annexes missing from copy" Checked --> "This document is missing one or more annexes."

**Comment by SamCCSI** [comment]
I agree with Kaitlin's comment.

**Comment by anderspeders** [comment]
There are two required actions involved with this ticket: 

1) [Metadataform] Add metadata fields as part of metadata form: "Yes; No; Unknown":
pages_missing
annexes_missing

2) [UI] If value appears as Yes - place the following text prominently on the contractpage: 
"Pages missing from copy" Checked --> "This document is missing one or more pages."
"Annexes missing from copy" Checked --> "This document is missing one or more annexes."

Final UI placement to be confirmed with CCSI cc @KaitlinCCSI @SamCCSI 

@SamCCSI @KaitlinCCSI: Do we need an affirmative statement in the case where completetion is confirmed?

**Comment by KaitlinCCSI** [comment]
- Don't know what you mean by "completetion is confirmed"? Do you mean if "No" is checked for either of those fields? If that is what you mean, then no, we _only_ want a statement to appear when we have noted (by selecting "Yes") that pages are missing or annexes are missing. If we have selected "No" or "Unknown", no statement should appear.

- For UI placement: perhaps at bottom of metadata column, or between "Type of contract" and "OCID"? Open to other suggestions.

![screen shot 2016-02-03 at 10 42 07 am](https://cloud.githubusercontent.com/assets/14825437/12789396/51d7649e-ca63-11e5-95b5-b001967815f9.png)

**Comment by anderspeders** [comment]
Thanks @KaitlinCCSI, 

1) So to confirm that in UI only "Yes" will appear.

I suggest the following full sentences in case of Yes-values:
"Pages missing from document"
"Annexes missing from document"

@KaitlinCCSI: Could you please confirm or suggest alternative as a full sentence including ""?

 2) Agree that bottom of right bar sounds good. 

@anjesh @manishgs: Please implement this

**Comment by KaitlinCCSI** [comment]
Can we use "Page(s) missing from document" and "Annex(es) missing from document"

**Comment by anderspeders** [comment]
Thanks @KaitlinCCSI 
Yes, that works.

**"Page(s) missing from document"**
**"Annex(es) missing from document"**

@anjesh @manishgs: This is ready for implementation!

**Comment by anjesh** [comment]
Admin form should have the following fields 
"Page(s) missing from document" ( )Yes ( ) No (x) Not Available
"Annex(es) missing from document" ( )Yes ( ) No (x) Not Available

Not Available will be selected by default and gives null value.
Yes -> True
No -> False

```Page(s) missing from document```
```Annex(es) missing from document```
will be shown in contract view page if only "Yes", otherwise the sentence(s) will not be shown.

**Comment by anderspeders** [comment]
Looks good,

@KaitlinCCSI?

**Comment by KaitlinCCSI** [comment]
Looks good; thanks.

On Wed, Feb 10, 2016 at 4:13 PM, Anders <notifications@github.com> wrote:

> Looks good,
>
> @KaitlinCCSI <https://github.com/KaitlinCCSI>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/715#issuecomment-182603009>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01QgKcz0r&m=954744c09073&t=20160210&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01QgKcz0r&m=954744c09073&t=20160210&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01QgKcz0r&m=954744c09073&t=20160210&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by sadhakbj** [comment]
This has been implemented.

Admin site has the following input option:
![715_admin](https://cloud.githubusercontent.com/assets/5828622/13067315/e6fbd360-d496-11e5-8297-8f6d6b35ef2c.png)

And if "Yes" is selected for both the cases then in the sidebar of the contract view page we can see:
![715_subsite](https://cloud.githubusercontent.com/assets/5828622/13067334/1729139a-d497-11e5-9c66-3b64ecb0b84c.png)

**Comment by SamCCSI** [comment]
One correction:

It should read "Annex(es)", not "Annexe(s)".

**Comment by KaitlinCCSI** [comment]
Re-opening b/c "Annexes missing from copy" still appearing in "Annotation Category" Dropdown on both RC and OLC, even though was supposed to have been removed.

![screen shot 2016-12-22 at 2 33 17 pm](https://cloud.githubusercontent.com/assets/14825437/21439512/17fbf3d0-c854-11e6-8d41-2d3f262f25ac.png)

**Comment by manishgs** [comment]
@SamCCSI  @KaitlinCCSI 

Still 7 contracts are using "Annexes missing from copy" category. You can view contracts using below link
http://admin.resourcecontracts.org/contract?type=annotations&word=annexes-missing-from-copy&issue=present

Please change the "Annexes missing from copy" category of these contracts and publish the annotations.

**Comment by SamCCSI** [comment]
All annotations under that category for those contracts have now been deleted.

The annotation publication status stayed as "Published" so I didn't republish them. Does that sound right?

**Comment by SamCCSI** [comment]
(Open land contracts still returns 4 contracts with that annotation category – not sure if this is because the system takes time to update the deletion of the annotation category or not?)

![image](https://cloud.githubusercontent.com/assets/12913915/21709015/971b0bd6-d431-11e6-8cff-8d00ff131b57.png)

**Comment by manishgs** [comment]
@SamCCSI 
You need to re-publish the annotation.
I can see publish button on this contract. http://admin.resourcecontracts.org/contract/2137

I don't see the contracts.
http://admin.resourcecontracts.org/contract?type=annotations&word=annexes-missing-from-copy&issue=present

**Comment by SamCCSI** [comment]
Thanks @manishgs all published now.

Is it possible to speed up the time for the contract to switch from "published" to "completed" whenever we delete an annotation? If it could happen immediately, then it will always be clear that we need to republish. 

cc @anjesh @charlesyoung

**Comment by SamCCSI** [comment]
"Annexes missing from copy" still appears as an annotation category even though it produces zero results:

![image](https://cloud.githubusercontent.com/assets/12913915/21709326/43e2107e-d434-11e6-895e-e533d3e87cf9.png)

**Comment by manishgs** [comment]
Cache is enabled for 5 min so you are seeing the category on dropdown. Now check again it is removed.

**Comment by SamCCSI** [comment]
Thanks @manishgs
