### ISSUE TITLE
Can't see name of contract when opening contract view page from search via annotations category dropdown

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#716]
When you search by the annotation category dropdown, you are able to click directly into a contract view page that shows the relevant annotation you searched. However, when you are taken to this contract view page, the contract name briefly flashes before the entire screen shifts down slightly so that you can no longer see the name of the contract. This isn't necessary to view the annotation, so it appears to be a bug. This should be fixed so you can see the name of the contract at the top of the page.

This screenshot shows the view after the page shifts down slightly -- you see everything except the top bar that has the OpenLandContracts name in the left and the name of the contract in the center.
![screen shot 2015-12-07 at 10 45 51 am](https://cloud.githubusercontent.com/assets/14825437/11633315/3e5c5a02-9cd0-11e5-9cb0-243190e19f52.png)

**Comment by KaitlinCCSI** [comment]
Also, when you toggle between "PDF" and "Text" view, the contract view page scrolls down slightly so that you can no longer see the contract name. This should also be fixed.

**Comment by anjesh** [comment]
Are you still having this issue? I can't replicate this particular shifting of the page when viewing the contract view from the seach list.

**Comment by KaitlinCCSI** [comment]
No longer having this problem.
