### ISSUE TITLE
Documents to include in the RC Resources page

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#719]
Title: Contracts Confidential: Ending Secret Deals in the Extractive Industries 
Description: (2009) A report designed to promote a conversation among industry, governments, investors, banks and civil society organizations about disclosure and confidentiality in extractive industry contracts.
Link: http://www.resourcegovernance.org/sites/default/files/RWI-Contracts-Confidential.pdf

Title: Focus on Contract Monitoring
Description: (2011) A report that examines the monitoring of mining obligations, characterizes the main gaps, identifies policy options and good practices, and proposes practical ways for both government and civil society to improve monitoring and enforcement.
Link: http://www.resourcegovernance.org/sites/default/files/RWI_Enforcing_Rules_full.pdf

Title: Promoting Contract Transparency
Description: (2011) Oil, gas and mining laws and contracts establish the terms of what a country might gain from extraction, which can affect a nation’s ability to derive full benefits from its resources. While parliaments are constitutionally mandated to ratify laws, they generally do not have a role in reviewing contracts. Contracts, even when signed, are rarely disclosed to parliament or the public.
Link: http://www.resourcegovernance.org/sites/default/files/RWI_Parliamentary_Briefing_ContractTransparency.pdf

**Comment by anjesh** [comment]
@anderspeders who will do the editing of the page to add these info the resources page http://www.resourcecontracts.org/page/resources

**Comment by anderspeders** [comment]
Now updated. Closing. 

@charlesyoung: I have shared editing details with you in email.
