### ISSUE TITLE
Fix "Contract Type" codelist

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#720]
As per the comments in the [Contract Type Codelist Spreadsheet](https://docs.google.com/spreadsheets/d/1tRRcib0VNynipkk83m4Be1vRaSslCKHzoIxmmC1oPLQ/edit#gid=0), the following changes are requested

1. "Investment Promotion Agreements" ```--rename-to-->``` "Investment Promotion Agreement" (7 contracts, we need to fix these contracts in the database)
1. "Stabilization Agreements" ```--rename-to-->``` "Stabilization Agreement" (0 contracts)
1. "Investor - State Agreement" ```comes under``` "Concession Agreement" (0 contracts with "Investor - State Agreement"). Does this mean we remove "Investor - State Agreement" from the list?

1. The following are requested to be added 
 * Contract Amendment
 * Contract Annex  (present in [Document-type](https://docs.google.com/spreadsheets/d/1tRRcib0VNynipkk83m4Be1vRaSslCKHzoIxmmC1oPLQ/edit#gid=1105679462) )
 * MOU
 * Sub Contract (present in Document-type)
 * Translated Contract (present in Document-type)

Please confirm the changes to the "Contract Type" codelist? Also adding new "Contract Types" means that we delete those from the "Document Type" if present there?

The following french list to be remained as it is
* Bail Foncier
* Contrat de Concession Agricole
* Protocole d'Accord
* Contrat de Concession Forestière

@anderspeders @KaitlinCCSI @SamCCSI

**Comment by SamCCSI** [comment]
1. Yes
2. Yes
3. Yes - delete "Investor - State Agreement"
4. Yes, but: 
--- it should be "Memorandum of Understanding", not "MOU"
--- it should be "Subcontract" not "Sub Contract" (my apologies for these errors)

We need to delete the following Document Types:
--- Contract Annexe
--- Sub Contract
--- Translated Contract

For French list of terms mentioned above: those terms should all be contract types in French site.

**Comment by anjesh** [comment]
Here's the google docs for ease https://docs.google.com/spreadsheets/d/15k-7NCkgu1p2eKgWGZnykASLQoa4gR6fOLskV8mdOhY/edit?ts=566690b1#gid=0

**Comment by jpmckinney** [comment]
Linking #586 and #681

**Comment by jpmckinney** [comment]
Note that there is no overlap with the [OCDS code list](http://ocds.open-contracting.org/standard/r/1__0__0/en/schema/codelists/#document-type), although there could be greater overlap with some simple renaming. (OCDS doesn't use spaces in its codes.)

See also the [code list that was prepared as part of the draft Extractives extension](https://docs.google.com/spreadsheets/d/1nniKoHvLdpctJq19l8-VYxg7rL4baQjdf-8ZMqT1_kQ/edit#gid=462856172).
