### ISSUE TITLE
Saving OCR text edits

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#722]
There should be a notification when exiting an OCR editing session without saving. 

'Please save your edits before exiting the page'

**Comment by upasna01** [comment]
The issue have been fixed. Please review changes. Here is the snapshot of the change.
![please save](https://cloud.githubusercontent.com/assets/11477899/13419357/70cc8828-dfa5-11e5-821c-74abf0dc797f.png)
