### ISSUE TITLE
Annotation flags on the right hand side of PDF contracts

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#724]
Where annotation flags are placed on the right hand side of PDF contracts, the boxes that appear when you hover over the flags are sometimes cut off. 

So far, I have only noticed this happening when I view contracts on smaller screens. E.g.: 

On a larger screen, the annotation boxes are not cut off: 
![2015 12 11 olc_right annotation boxes_large screen](https://cloud.githubusercontent.com/assets/14910764/11748124/b775d360-9ff4-11e5-9376-3ab36ea8e3a8.jpg)

On a smaller screen (13 inch) they are cut off, even though I am fully zoomed out of the contract: 
![2015 12 11 olc_right annotation boxes_small screen](https://cloud.githubusercontent.com/assets/14910764/11748128/bbe08fbc-9ff4-11e5-934a-f8c861c46db7.jpg)

We just published a contract where all of the annotation flags are on the right hand side of the contract page, resulting in the boxes being cut off when viewing from smaller screens. http://www.openlandcontracts.org/contract/ocds-591adf-LR8579251623OL/view#/pdf/page/27/annotation/26132 

Is this something that can be easily resolved? 

Many thanks. 
cc @KaitlinCCSI @samCCSI

**Comment by anderspeders** [comment]
This is a request towards imported PDFs. 
Could you please check with the current PDF-annotation module to see if we have the same issue. 
My suggestion would be that we focus time on the annotation process for the annotation module rather than the imported PDFs.

**Comment by JesseCCSI** [comment]
Hi @anderspeders 

I'm not sure I understand fully, could you please clarify? 

The contract that I linked to in my comment above was annotated last week using the current PDF annotation module, and published yesterday. This resulted in the same issue as that highlighted in the screenshots (see here: http://www.openlandcontracts.org/contract/ocds-591adf-LR8579251623OL/view )

Would be grateful if you could clarify. Thanks.

**Comment by upasna01** [comment]
The error have been fixed, please verify.
![openlandcontracts org liberia ej j investment corporation forest management contract 6 october 2008](https://cloud.githubusercontent.com/assets/11477899/13348811/c7b6ded2-dc9d-11e5-89bf-873586d155ba.png)

**Comment by JesseCCSI** [comment]
Many thanks @upasna01 just checked and this seems to be fixed -- will let you know if we notice otherwise.
