### ISSUE TITLE
Change "Other" cluster category to "Legal Rules"

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#725]
Please change the "Other" cluster category to "Legal Rules".

![image](https://cloud.githubusercontent.com/assets/12913915/11754040/d49bcdec-a016-11e5-97ac-c9da4350c472.png)

This has been agreed on by the project group.

CC @KaitlinCCSI @anderspeders @jedm

**Comment by anderspeders** [comment]
Just to summarize this thread on cluster categories along with other change requets to annotation categories. 

In order to do this efficiently we need to complete one google sheet with all change requests.

**Comment by SamCCSI** [comment]
I agree - but was not sure where to add this request on the most recent codelist document that has been circulated?

**Comment by anderspeders** [comment]
Thanks @SamCCSI 

Change requests should go here for sign off by RC-group: 
https://docs.google.com/spreadsheets/d/15k-7NCkgu1p2eKgWGZnykASLQoa4gR6fOLskV8mdOhY/edit#gid=509295652

**Comment by SamCCSI** [comment]
Thanks @anderspeders I've added this request to Row 16 of the tab entitled "Annotation category"

**Comment by anjesh** [comment]
Is this confirmed to update in the db?

**Comment by KaitlinCCSI** [comment]
Yes

On Thu, Feb 25, 2016 at 11:35 PM, Anjesh <notifications@github.com> wrote:

> Is this confirmed to update in the db?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/725#issuecomment-189120147>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01QmRzp7A&m=410c225fd72b&t=20160226&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01QmRzp7A&m=410c225fd72b&t=20160226&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01QmRzp7A&m=410c225fd72b&t=20160226&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by SamCCSI** [comment]
@anderspeders can we add this to Sprint 15? It is based on group consensus and has been ready to go for months, and I've just been asked by @jedm to prepare hover explanations for each of the six categories.

cc @KaitlinCCSI

**Comment by manishgs** [comment]
Cluster  "Other"  renamed to "Legal Rules".
