### ISSUE TITLE
What is "resource_raw" and how does it differ from "resource"?

### ISSUE THREAD

**Issue by jpmckinney** [NRGI/resourcecontracts.org#727]
> Anders: I do not know. Anjesh can confirm.

**Comment by hello-deepak** [comment]
"resource_raw" and "resource" are same but with different data type in elasticsearch document  which is used for filtering/aggregation and  should not appear in api part .  We will remove "resource_raw" from metadata api .

**Comment by jpmckinney** [comment]
Thanks - can be merged into #740 if you like.
