### ISSUE TITLE
What do the values of “operator” mean?

### ISSUE THREAD

**Issue by jpmckinney** [NRGI/resourcecontracts.org#728]
The values in the API are: “0”, “1” and “-1”. If it were just "0" or "1" I'd assume boolean. I don't know what "-1" could mean.

> Anders: Again, not sure.

If `operator` is in fact a boolean property, it should possibly be renamed to `is_operator` to match other boolean properties.

**Comment by hello-deepak** [comment]
- 1 => "Not Available",
    0   => "No",
    1   => "Yes",

**Comment by jpmckinney** [comment]
Hmm, what is the use case for "-1 Not available", versus just leaving the field blank?

**Comment by hello-deepak** [comment]
It was implemented in admin part to differentiate between "No" and "Not available"  which got reflected in api part. But it make more sense in leaving the field blank if not available . 

So, we will be renaming the field as "is_operator" to match the boolean properties and leaving the field blank if not available .
