### ISSUE TITLE
Does “supporting_contracts” communicate the correct semantics?

### ISSUE THREAD

**Issue by jpmckinney** [NRGI/resourcecontracts.org#730]
Are all the contracts actually supporting the current document, or is it sometimes just a list of related contracts?

> Anders: Not sure.

**Comment by anjesh** [comment]
My understanding is these supporting_contracts might not be contracts always - they might be annex, some other supporting documents, amendments. During discussion, we have used various terms like  associated documents, associated contracts, supporting documents without really thinking about the semantics. We should get the proper wording and understanding of the supporting documents/contracts, with inputs from others. 
@anderspeders @charlesyoung @KaitlinCCSI

**Comment by SamCCSI** [comment]
I'm not sure what "supporting" means in this context, but hopefully the
following helps?

Associated documents are any document that relates to the same deal /
investment project as the main contract. It can include annexes,
amendments, translations, contract summaries, management plans, impacts
assessments, etc, provided that each of those documents relates to the same
investment project. As Anjesh says, they are not always contracts -- other
documents can be listed as associated documents.

On Wed, Dec 16, 2015 at 8:24 PM, Anjesh <notifications@github.com> wrote:

> My understanding is these supporting_contracts might not be contracts
> always - they might be annex, some other supporting documents, amendments.
> During discussion, we have used various terms like associated documents,
> associated contracts, supporting documents without really thinking about
> the semantics. We should get the proper wording and understanding of the
> supporting documents/contracts, with inputs from others.
> @anderspeders <https://github.com/anderspeders> @charlesyoung
> <https://github.com/charlesyoung> @KaitlinCCSI
> <https://github.com/KaitlinCCSI>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/730#issuecomment-165044556>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School | The Earth Institute, Columbia University
435 W116th St. New York, NY 10027
| (+1)(212) 854-2635 <+1212-854-2635> | (+1)(646) 630-4123 <+1646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by jpmckinney** [comment]
I would recommend renaming to `related_documents` in that case, since they are not always contracts and not always supporting.

**Comment by jpmckinney** [comment]
Why was the term `supporting` chosen in favor of `related`?

**Comment by anjesh** [comment]
"related" sounds fit here and "is_associated_document" can also be changed to "is_related_document"

**Comment by sadhakbj** [comment]
- Done.
