### ISSUE TITLE
Remove obsolete properties from records in API

### ISSUE THREAD

**Issue by jpmckinney** [NRGI/resourcecontracts.org#731]
It looks like some documents in ElasticSearch are using an older schema and have not been updated to the latest. Notably:

- government_identifier: Superseded by government_entity.identifier, but appears 379 times
- participation_share (top-level): Superseded by participation_share (in company), but appears once
- Source_url: Superseded by source_url (all lowercase), but appears on 5 contracts
- comp_id: Superseded by company_number, but appears on 5 contracts
- company_jurisdictions: Superseded by jurisdiction_of_incorporation, but appears 300 times
- opencorporates_id: Superseded by open_corporate_id, but appears 300 times

**Comment by sadhakbj** [comment]
Done.
