### ISSUE TITLE
Improve API data types

### ISSUE THREAD

**Issue by jpmckinney** [NRGI/resourcecontracts.org#733]
RC.org makes its data available as JSON via an API. There are some cases where a different datatype would be more appropriate.

- ~~contract_id: integer (current values are numeric strings)~~
- is_supporting_document: boolean (current values are “0” or “1”)
- show_pdf_text: boolean (current values are “0”, “1” and 1)
- signature_year: integer (current values are either numeric strings, or integers)
- total_pages: integer (current values are numeric strings)
- translation_from_original: integer (current values are “0” or “1”)
- Company.participation_share: number (current values are decimal strings in the range 0 to 1)
- ~~Document.id: integer (current values are numeric strings)~~

**Comment by jpmckinney** [comment]
For compatibility with OCDS, `contract_id` and `Document.id` can remain strings.

**Comment by sadhakbj** [comment]
Done.
Link to the wiki of our API Page:
https://github.com/NRGI/resourcecontracts.org/wiki/Contract-Metadata-API

**Comment by jpmckinney** [comment]
It looks like booleans are still `0` and `1` instead of `true` and `false`.

**Comment by jpmckinney** [comment]
New issues:

* `parent.id` and `supporting.id` should be `integer` like `id`
* `share` is inconsistently a string or a number
* `concession.name` is sometimes `null`, whereas similar properties use the empty string `""`

**Comment by sadhakbj** [comment]
- Fixed.

**Comment by jpmckinney** [comment]
Some `year_signed` are still `""` instead of `null`.
