### ISSUE TITLE
Remove prefixes from property names in API

### ISSUE THREAD

**Issue by jpmckinney** [NRGI/resourcecontracts.org#734]
In general, it’s not recommended to prefix a property name with its class name. For example, the data element for a contract’s identifier should just be “id” not “contract_id”. I explained this in greater depth in [this OpenContracting issue](https://github.com/open-contracting/standard/issues/45), which was fixed.

The properties to rename are:

- contract_id: id
- contract_identifier: identifier
- contract_name: *title* (to align with OCDS)
- contract_note: note
- document_type: type
- parent_document: parent
- license_identifier (under concession): identifier
- license_name (under concession): name
- contract_name (under parent_document and supporting_contracts): name

**Comment by sadhakbj** [comment]
The peoperties are renamed as:
```
contract_id: id
contract_identifier: identifier
contract_name: name
contract_note: note
document_type: type
parent_document: parent
license_identifier (under concession): identifier
license_name (under concession): name
contract_name (under parent_document and supporting_contracts): name
```
The link to the API is: http://rc-api-stage.elasticbeanstalk.com/api/contract/1152/metadata
