### ISSUE TITLE
Collect project properties into new object in API

### ISSUE THREAD

**Issue by jpmckinney** [NRGI/resourcecontracts.org#735]
In general, if you want to describe multiple properties of a related object, it’s best to create an object property and put those properties under that object, that to create prefixed properties on the main object. For example, instead of:

```json
{
  "project_identifier": …,
  "project_title": …,
  …
}
```

You should have:

```json
{
  "project": {
    "identifier": …,
    "name": …
  },
  …
}
```

This way, if at some later date you decide to enrich your Project model, you can just add more properties to that object, instead of having a bigger-and-bigger Contract model with a dozen project-specific properties.

Note that this integrates #712 (changing Project Title to Project Name) for the API.

**Comment by sadhakbj** [comment]
- Done
Check the latest API on the following link:
http://rc-api-stage.elasticbeanstalk.com/api/contract/1152/metadata
