### ISSUE TITLE
Collect file properties into new object in API

### ISSUE THREAD

**Issue by jpmckinney** [NRGI/resourcecontracts.org#736]
As with #735, the `file_*` properties should be collected into a new object, i.e.:

```json
{
  "file": {
    "url": "….pdf",
    "byte_size": 13888217,
  },
 …
}
```

I recommend renaming “size” to “byte_size” (as used by W3C DCAT) to make it unambiguous how the size is measured.

I notice another property “word_file”, which to me suggests a Microsoft Word file, but it is instead a plain text version of the file. In this case, it may be preferable to have a list of files with a “media_type” property (using IANA media types as the code list), e.g.:

```json
{
  "file": [
    {
      "url": "….pdf",
      "byte_size": 13888217,
      "media_type": "application/pdf"
    },
    {
      "url": "….txt",
      "media_type": "text/plain"
    }
  },
  …
}
```

**Comment by jpmckinney** [comment]
`documentcloud_url` should be moved here as another `url` and `media_type` block, with `media_type` of `text/html`.

**Comment by sadhakbj** [comment]
- Done
Check the API on the following link:
http://rc-api-stage.elasticbeanstalk.com/api/contract/1152/metadata
