### ISSUE TITLE
Collect company properties into new object in API

### ISSUE THREAD

**Issue by jpmckinney** [NRGI/resourcecontracts.org#737]
The company property has a confusing model. What we are talking about here aren’t companies directly, but more specifically corporate participation in a contract. To illustrate, a participation share is not a property of a *company* (a company will have different participation shares related to different contracts); participation share is a property of a *company’s participation*. So, the model should look something like this:

```json
{
 "participation": {
   "company": {
     "address": …,
     "founding_date": …,
     "identifier": …,
     "corporate_grouping": …,
     "name": …,
     "opencorporates_id": …,
     "parent_name": …,
     "jurisdiction_of_incorporation": …,
     "registration_agency": …
   },
   "is_operator": …,
   "share": …
 },
 …
}
```

In this way, a company will have a specific participation share, and it may or not be the operator. Those two properties are distinct from its other properties which are the same regardless of the specific contract you’re looking at.

You’ll note that I removed the `company_` and `participation_` prefixes from five properties in all, and that I made the renamings from #738, #739, #741 and #728, and kept only one of `company_identifier` and `company_number` (see #732).

I’ll note that the `registration_agency`, `jurisdiction_of_incorporation` and `identifier` are connected: the agency issues identifiers for a specific jurisdiction. In [W3C ADMS](http://www.w3.org/TR/vocab-adms/), for example, the identifier has multiple properties to represent this relationship. Same in [OCDS](http://ocds.open-contracting.org/standard/r/1__0__0/en/schema/reference/#identifier). So, it should probably look more like:

```json
{
 "participation": {
   "company": {
     "identifier": {
       "id": …,
       "creator": {
         "name": …,
         "spatial": …
       },
     …
   },
   …
 },
 …
}
```

Above, I’m using `spatial` for the geographic jurisdiction since that’s what Dublin Core uses. There are possibly better alternatives.

**Comment by hello-deepak** [comment]
`"participation":[
	{  
	   "company":{  
	      "name":"ConocoPhillips (91-12) Pty Ltd",
	      "address":"West Perth WA 6005",
	      "founding_date":"1994-06-14",
	      "corporate_grouping":"ConocoPhillips",
	      "opencorporates_id":"",
	      "identifier":{  
	         "id":"064 963 346",
	         "creator":{  
	            "name":"",
	            "spatial":"AU"
	         }
	      }
	   },
	   "is_operator":1,
	   "share":""
	},
	{  
	   "company":{  
	      "name":"Santos (JPDA 91-12) Pty Ltd.",
	      "address":"",
	      "founding_date":"1992-09-09",
	      "corporate_grouping":"",
	      "opencorporates_id":"056937752",
	      "identifier":{  
	         "id":"056937752",
	         "creator":{  
	            "name":"",
	            "spatial":"AU"
	         }
	      }
	   },
	   "is_operator":0,
	   "share":""
	}
]``

**Comment by sadhakbj** [comment]
- Done
The new API can be checked on the link: http://rc-api-stage.elasticbeanstalk.com/api/contract/1152/metadata
