### ISSUE TITLE
Rename API properties for external consistency

### ISSUE THREAD

**Issue by jpmckinney** [NRGI/resourcecontracts.org#739]
- Rename `signature_date` to `date_signed` to match OCDS. To be internally consistent, `signature_year` would also become `year_signed`.
- Rename `total_pages` to `number_of_pages` to match [Schema.org](http://schema.org/numberOfPages)
- Rename `corporate_group` to `corporate_grouping` to match OpenCorporates.

**Comment by sadhakbj** [comment]
You can see the last API for metadata here http://rc-api-stage.elasticbeanstalk.com/api/contract/1152/metadata
