### ISSUE TITLE
Confirm contract identifier - link to Open Contracting Data Standard

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#74]
For RC.org we will need a data point, which can enable interoperability with other data publishers using the open contracting data standard. The obvious choice would be to assign a **contract identifier** to each contract.  

See row 32 / 33 in the metadata sheet:
https://docs.google.com/spreadsheets/d/12UCQA422r5Dg3wruUmYHL2SCLdDrlesCPcm2tHD8Yu4/edit#gid=1329720090

Also noting that @jpmckinney has done great pilot research here: 
https://docs.google.com/document/d/1uPXFXTRXXc2zi3vo_arrWm_c_gW6KSPG5aAlD2ri5rw/edit

cc @tmdvs

**Comment by timgdavies** [comment]
The Open Contracting Data Standard make a distinction between:

* Contracting process;
* Individual releases of information - such as a contract data release;

The Contracting Process gets an Open Contracting ID, usually assigned by the institution authoritatively responsible for that process, whereas the release ID can be locally determined.

It strikes me then that the approach here might be to provide a prompt for 'Associated Contracting Process', using an OCID wherever possible.

Happy to explore this more with some worked examples if useful.

**Comment by anderspeders** [comment]
To me the essential challenge seems to be this - correct me if I am wrong: 
That most, most publishers of contracts do not issue OCID's at the moment *and* that the publishing body should be the government agency behind the contracting process. 

I therefore wonder if it is worth parking this until we actually begin to see publication/government publication of OCID's?

**Comment by timgdavies** [comment]
That's correct. 

I think this can wait until we get the first registers of contracting processes for extractives emerging.

**Comment by anderspeders** [comment]
We can leave it in the metadata form as a placeholder.
