### ISSUE TITLE
Remove properties for internal use from API

### ISSUE THREAD

**Issue by jpmckinney** [NRGI/resourcecontracts.org#740]
- Is `show_pdf_text` for internal use only? If so, remove from the API.
- `category` is an unexpected field name considering `rc` and `olc` are the only possible values. Is this field of any external use? If not, remove it from API. If there are external uses, we should consider renaming it.

**Comment by manishgs** [comment]
`show_pdf_text` is used for showing pdf text on subsites. if contract having show_pdf_text = yes  then we show the text else we hide text and display message so we can't remove from the api.

For `category`, we don't need category field on metadata api as we request rc or olc contracts from api parameter.

**Comment by jpmckinney** [comment]
Just to better understand: Why would you not want to show PDF text if it's available?

**Comment by manishgs** [comment]
Please see this issue https://github.com/NRGI/resourcecontracts.org/issues/386.

**Comment by jpmckinney** [comment]
In that case, I think `show_pdf_text` should be renamed to be more descriptive ("what is true?" i.e. "what is the status of the OCR text?") and less procedural ("do this" i.e. "don't show the text").

So, something like `ocr_status` with values of "unreviewed" and "reviewed" (in case there are other possible values), or a boolean property of `is_ocr_reviewed` would achieve that.

**Comment by manishgs** [comment]
There is a option in the admin to choose whether to show pdf text or not so we name the field to `show_pdf_text` if you think `is_ocr_reviewed` more appropriate then we'll rename the field in api.

**Comment by SamCCSI** [comment]
I have no background in this terminology and defer to those who do, but as
someone who uses this field regularly, I find "Show pdf text" helpful,
because it clearly states what will happen if I select yes or no.



On Wed, Dec 16, 2015 at 3:50 PM, Manish Gopal Singh <
notifications@github.com> wrote:

> There is a option in the admin to choose whether to show pdf text or not
> so we name the field to show_pdf_text if you think is_ocr_reviewed more
> appropriate then we'll rename the field in api.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/740#issuecomment-164994964>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School | The Earth Institute, Columbia University
435 W116th St. New York, NY 10027
| (+1)(212) 854-2635 <+1212-854-2635> | (+1)(646) 630-4123 <+1646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by jpmckinney** [comment]
"Show PDF text" is good for the label in the UI - I'm just talking about what is in the API JSON response.

**Comment by jpmckinney** [comment]
I'm thinking `is_ocr_reviewed` should be a property of the `text/plain` entry in the file list described in https://github.com/NRGI/resourcecontracts.org/issues/736 in which case perhaps `is_reviewed` is more reusable.

**Comment by sadhakbj** [comment]
Link to new API: http://rc-api-stage.elasticbeanstalk.com/api/contract/1152/metadata

**Comment by jpmckinney** [comment]
I thought `category` was being removed from the API response, so that it would only exist in the API query string parameters?

**Comment by anjesh** [comment]
It's not clear whether the contract needs to be shown as RC or OLC in the country subsite. If it's not required, then we may remove it from the response.

**Comment by anjesh** [comment]
I don't see any use-case for the use of category in the subsite. So lets remove the category field from the API response. @sadhakbj

**Comment by anderspeders** [comment]
I did not see this and would like to jump in. 

As  I understand NRGI is using the external API for analysis and do indeed need to distinguish if contracts are grouped under rc or olc. So I am not keen to approve that we remove this until I am certain that there are no consequences. 

@jpmckinney: What type of renaming would you suggest?

**Comment by jpmckinney** [comment]
I don't know - maybe create an object named `__internal__` and then store any key-value pairs you like in there (you can keep the `category` name if you want). This property is not "about" the contract, so it shouldn't be confused for data, so flagging it as really outside the data under an `__internal__` object will avoid any confusion by downstream users.

**Comment by anderspeders** [comment]
ok, I will check on this. Let's wait now on how we implement this.

**Comment by hello-deepak** [comment]
@anderspeders 

Any update?

**Comment by hello-deepak** [comment]
What field should be included in __internal__ object?

**Comment by charlesyoung** [comment]
@anderspeders is this still required?
