### ISSUE TITLE
Rename API properties for clarity and typos

### ISSUE THREAD

**Issue by jpmckinney** [NRGI/resourcecontracts.org#741]
- `open_corporate_id` should be `opencorporates_id` (with an `s`). I removed the underscore in `open_corporates` to be consistent with `documentcloud_url`.
- Rename `parent_company` to `parent_name`. `parent_company` suggests the value is a Company object, but it’s just the name of the parent company. If we wanted to track more properties about the parent, we can collect them under a new `parent` object property.
- `disclosure_mode` seems like an unusual term for describing the type of the publisher. Why not rename to `publisher_type`? If we might have more properties about the publisher, we can collect them under a new `publisher` object property.
- `status` is an unusual name if the only possible values are `published` or `unpublished`. A boolean property like `is_published` would be more appropriate.

**Comment by sadhakbj** [comment]
The new API can be viewed on the following link: http://rc-api-stage.elasticbeanstalk.com/api/contract/1152/metadata
