### ISSUE TITLE
RC home page

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#742]
Can we update the RC home page?

1. The background logo to something more clearer (the pipes look like tree logs)
2. Change 'A directory of' to 'An online repository of'
3. Should we change 'Petroleum & Mineral Contracts' to 'Open Resource Contracts'?

The OLC home page looks much better than the RC home page.

**Comment by jedm** [comment]
In concert with these suggestions from @charlesyoung would advise a fuller rethink of the UI and UX of homepage, to make sure key paths and good "how to" is being considered.

**Comment by anjesh** [comment]
Should be addressed in new design https://github.com/NRGI/resourcecontracts.org/issues/873. If anything further discussion in that issue
