### ISSUE TITLE
Non-recognition of French letters 

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#743]
I beieve that this has been flagged before by @samccsi.

There seems to be an issue in the system where French letters are not recognized. The way the transcription appear makes me think that the turker did submit a correct text in AWS, but that some thing is getting stuck during the import from AWS to RC.

![image](https://cloud.githubusercontent.com/assets/1101585/11841054/81cf9142-a3c8-11e5-9128-d1c0cd3f263d.png)

**Comment by anjesh** [comment]
@manishgs we have implemented the unicode in the workflow, can you check if this particular page is created before or after that implementation.

**Comment by manishgs** [comment]
We've implemented the unicode on sep 21, 2015. [commit] (https://github.com/manishgs/mTurkTask/commit/13c2a2f0022d5f02e554c7bb4d71ff2397919ec3)
The hit submitted on 2015-12-04 after unicode implementation.  [see detail here] (https://requester.mturk.com/mturk/manageHIT?HITId=3L2OEKSTW9YKQOQWZFX6580BWLI8YN)
When i tested last time on sandbox, unicode text were working fine.

**Comment by anjesh** [comment]
Lets open if there's issue with the new HIT assignment.
