### ISSUE TITLE
Status and documentation for country site docker

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#744]
@anjesh to provide outline for suggested implementation of country sites using docker. 

A host government / country site host will have the following options for costumization: 
- Select front page image
- Select colors for site
- Editable pages (at buttom of screen)
- Translation (eg. Tunisia would need French / English)

@charlesyoung any other custom requests from country site hosts should be added here for consideration

**Comment by anderspeders** [comment]
Deploy test docker - using slice for Sierra Leone...

**Comment by anjesh** [comment]
Country subsite Docker is maintained in a separate repo here https://github.com/younginnovations/docker-rc-country-subsite and documentation in the same repo. 

Demo site is here http://rc-site-demo.elasticbeanstalk.com/country/public/ but design and content  discussion is needed here.

**Comment by anderspeders** [comment]
Therefore closing this issue.
