### ISSUE TITLE
Document type: contract --> contractSigned?

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#746]
OCDS seems to have a taxonomy for that includes signed contract. this should fit with RC right?

http://ocds.open-contracting.org/standard/r/1__0__RC/en/schema/codelists/#document-type

@jpmckinney ?

**Comment by jpmckinney** [comment]
Sure. In general I'm not too picky about what makes it into a code list. Some criteria are:

* Is it needed by a clear use case? (Will the value of the system be lower for that use case if the code is missing? Will its absence prevent some use cases?)
* Is it clearly distinct from other codes? (Is its meaning clear? Will people accidentally use this code when they should be using another? Is it, in all relevant respects, the same as an existing code or not?)
* If it's not distinct, then does it narrow an existing code? e.g. "document" is broad, while "contract" is narrower.

In this case, it seems to satisfy the criteria: people want to be able to find the contract with signatures on it, (I assume it's distinct from existing codes, I haven't checked), and it's narrower than existing codes.

**Comment by anderspeders** [comment]
Thanks, closing
