### ISSUE TITLE
OCID identifiers: two types of ids

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#747]
My understanding is that the RC.org system will need two types of OCID: 
- an overall OCID which covers the entire contract with all documents related to the document
- a "release ID" (not sure if this is the correct term, which would provide OCID for each document within a contract group (for example an Environmental Impact Assessment)

I recall that @anjesh might have outlined a process for this, but it would be good to confirm the proposed solution with @jpmckinney before implementation.

**Comment by jpmckinney** [comment]
Hmm, I don't think that's how release ID works. Release ID is only if you are following the specific data publication process anticipated by OCID - which this project is not. I think this project can only implement `ocid`.

**Comment by anderspeders** [comment]
Thanks @jpmckinney, 

So is the conclusion here that the current process for issuing OCID in RC is sufficient?

**Comment by jpmckinney** [comment]
It looks sufficient to me.

**Comment by anjesh** [comment]
This question is answered. Closing.
