### ISSUE TITLE
What happens to the OCID if a contract is changed from Main document to associated document?

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#748]
We need clarity, and possibly rules, on what will happen with OCID if a contract is changed from Main Document to Associated Document or vice-versa. 

cc @jpmckinney @anjesh

**Comment by jpmckinney** [comment]
It depends on the semantics of the field, but my understanding is that it is used to identify the contracting process to which the document is associated, in which case it doesn't change.

**Comment by anjesh** [comment]
Associated document sets OCID using parent_id-release_id to identify with the main contract it is associated with. See https://github.com/NRGI/resourcecontracts.org/issues/583

If associated document is changed to main, then it gets new OCID following the https://github.com/NRGI/resourcecontracts.org/issues/173

**Comment by anjesh** [comment]
This can be closed.
