### ISSUE TITLE
What is the source for the resource code list?

### ISSUE THREAD

**Issue by jpmckinney** [NRGI/resourcecontracts.org#749]
In the [draft Extractives extension](https://docs.google.com/document/d/1uPXFXTRXXc2zi3vo_arrWm_c_gW6KSPG5aAlD2ri5rw/edit#heading=h.fa1zfnxxx6m7), I note that the IMF recommends the [Central Product Classification (CPC) Ver.2.1](http://unstats.un.org/unsd/cr/registry/cpc-21.asp).

/cc @anderspeders

**Comment by anderspeders** [comment]
Resource source list is available here: https://eiti.org/files/scoping_study_for_eiti_data_standards_2015.pdf

I will also add this to the documentation.

**Comment by jpmckinney** [comment]
Can you specific the specific section? That document doesn't have "timber" or many other values used for the resource field.

**Comment by jpmckinney** [comment]
Full list of missing values:

* Acacia
* Agroindustry
* Aluminum
* Ananas comosus (Pineapple plant)
* Bananas
* Base metals
* Bauxite-Aluminum
* Biofuels
* Castor oil (Ricinus communis)
* Cereal crops
* Citrus
* Coffee
* Cotton
* Eucalyptus
* Food crops
* Gas
* Grain legumes (Pulses)
* Groundnuts
* Hydrocarbons
* Jatropha curcas
* Maize (Corn)
* Medicinal plants
* Oil
* Oil crops
* Oil palm or palm oils
* Oil palm products
* Oilseeds
* Other crops
* Palm oil
* Rice
* Rice products
* Rubber
* Rubber products
* Safflower
* Sesame
* Sorghum
* Soy
* Soybeans (Soya beans)
* Sugar
* Sugarcane
* Tea
* Teak (Tectona grandis)
* Theobroma cacao (Cocoa plant)
* Timber
* Timber (Wood)
* Value-added crops

**Comment by anderspeders** [comment]
Thanks, 

OLC resources have until now been updated based on customized CCSI requests. 

@KaitlinCCSI @samCCSI: Could you state if you'd like the resource types above added?

(for what it's worth my recommendation would be that the list above could be a good opportunity to get a standardized list once and for all - while avoiding that your current resource list would need further additions in the future)

**Comment by charlesyoung** [comment]
@anderspeders @SamCCSI @KaitlinCCSI is this still required?
