### ISSUE TITLE
Display of associated documents

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#750]
If a main contract has 4 related contracts (contracts A, B, C, D), all 4 will appear as "Associated documents" on the main contract's contract view page.

1. If I click on contract A, the main contract will be will appear under "Associated documents" on the contract's contract view page. Contracts B, C and D should also appear as Associated documents to contract A. (These three contracts are related to the main contract, so not directly linked to contract A, but in practice they are relevant context.)

2. The design should somehow note the “Main Document” – perhaps by always listing the Main Document first, followed by other associated / related documents.

**Comment by jedm** [comment]
We spec-ed this in September/October for the Main Document to always be listed first in the "Associated" list for any of its children. See attached. Also related to #470 and #624.

![rcolc_ui_contract_mockup_addendum_jmkc_assoc](https://cloud.githubusercontent.com/assets/2153664/12368747/1fbd4984-bba3-11e5-9d04-b4f5eb51eaf1.jpg)

**Comment by upasna01** [comment]
List of associated contracts will be shown if the existing contracts have related documents. Here is the snapshot for it. I assume this issue can be closed for now.
![associated-doc](https://cloud.githubusercontent.com/assets/11477899/13450486/eeaed314-e05d-11e5-8cbc-4d65b71b3be4.png)

**Comment by jedm** [comment]
I believe that the formatting and the header title are not as we had requested, but @anderspeders can confirm.
