### ISSUE TITLE
Loading a contract

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#751]
Issue when loading a contract. 

http://www.resourcecontracts.org/contract/ocds-591adf-CD7524880304RC/view

**Comment by anjesh** [comment]
@manishgs can you check why are we getting this 
![image](https://cloud.githubusercontent.com/assets/120488/12257061/2422acaa-b92b-11e5-97d5-cb4755e8c5d6.png)

**Comment by anjesh** [comment]
It appears that only the metadata for this contract is published and hence we are getting this error (though the error message is not meaningful here). Perhaps we can change the msg to something like "The contract text is not published yet. Please see the --link-to-summary-page-- metadata --link-end-- for now."

**Comment by charlesyoung** [comment]
Thanks @anjesh. 

How many contracts have published metadata but not the contract text?

**Comment by charlesyoung** [comment]
It seems however that you can download both the text and PDF contract although it still needs to be published which is an issue. 

http://www.resourcecontracts.org/search?q=DRC%2C+G%C3%A9camines%2C+MMR%2C+%5BSecakat%5D+-+Busanga+-+JVA+Amend+1%2C+2010&country=cd

**Comment by anjesh** [comment]
This particular bug is same as for https://github.com/NRGI/resourcecontracts.org/issues/765#issuecomment-180984102 

As for your question - How many contracts have published metadata but not the contract text? 
There are (75 + 1) contracts for which metadata is published but not the contract text.

![image](https://cloud.githubusercontent.com/assets/120488/12871724/69c8f63a-cdb0-11e5-83c9-60d946805a26.png)
