### ISSUE TITLE
amla_url and source_url

### ISSUE THREAD

**Issue by jpmckinney** [NRGI/resourcecontracts.org#752]
I don't know why `amla_url` and `source_url` were collected under `url` as `amla` and `source`. Those two properties do not form an object in terms of modeling. They are just two properties of the document (there is no new intermediate object in terms of modeling). So, there are two options:

1. Keep `amla_url` and `source_url` as top-level properties as before
2. Change the `url` property to a `link` property which is an array of Link objects with `url` and `title` properties.

My preference is 1.

**Comment by anjesh** [comment]
I agree. Will go with option 1 then. 
Keep amla_url and source_url separate.

**Comment by sadhakbj** [comment]
- Done.
You can check the API here: http://rc-api-stage.elasticbeanstalk.com/api/contract/1152/metadata
