### ISSUE TITLE
Annotation zooming

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#754]
The annotation box remains where it is, so when the document is zoomed, the box is misplaced as shown below.

![image](https://cloud.githubusercontent.com/assets/13888372/12197416/7e0e17d2-b60f-11e5-968e-1cb1d145307e.png)

![image](https://cloud.githubusercontent.com/assets/13888372/12197423/8e3984a2-b60f-11e5-9227-ad411edfbca9.png)

**Comment by charlesyoung** [comment]
Linked to case #356

**Comment by sadhakbj** [comment]
- Fixed now.
Initially:
![initial](https://cloud.githubusercontent.com/assets/5828622/12503396/0b885fd6-c0fc-11e5-8079-8eca65099f5c.png)

After Zooming:
![after_zoom](https://cloud.githubusercontent.com/assets/5828622/12503403/199f1c7c-c0fc-11e5-9a98-43f96e2a6859.png)
