### ISSUE TITLE
Associated documents

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#755]
Says 'No associated documents available' when there are well associated documents. 

![image](https://cloud.githubusercontent.com/assets/13888372/12199719/143fe75e-b623-11e5-9bdc-d21a18e8e486.png)

**Comment by sadhakbj** [comment]
- Done
![755_done](https://cloud.githubusercontent.com/assets/5828622/12315296/6d8bf654-baa1-11e5-977b-8b59ca472395.png)
