### ISSUE TITLE
Duplicate contracts 

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#756]
Should we allow for the capture of duplicate contracts? 

![image](https://cloud.githubusercontent.com/assets/13888372/12288373/854522ea-b9dc-11e5-8fb7-92f9c29136f2.png)

**Comment by hello-deepak** [comment]
These two contracts have same title but they contain different pdf .
You can view here .

http://resourcecontracts.elasticbeanstalk.com/contract/1582/review 
http://resourcecontracts.elasticbeanstalk.com/contract/1583/review

User can't upload same contract pdf twice but contract may have same title and other metadata. currently, we are only validating pdf file for contract duplication.
