### ISSUE TITLE
Changes to annotations on backend not appearing on front end 

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#759]
I added an annotation to this contract (http://www.openlandcontracts.org/contract/ocds-591adf-CD4492231156OL/view) on the backend about an hour ago - the change has still not appeared on the front end. I have clicked "publish all" several times on the backend, but this doesn't seem to have made a difference. 

Many thanks.

**Comment by JesseCCSI** [comment]
FYI I've also made changes to annotations of the following contracts, none of which have appeared on the front end: 

- http://www.openlandcontracts.org/contract/ocds-591adf-KH3856397364OL/view
- http://www.openlandcontracts.org/contract/ocds-591adf-ET4854285702OL/view

**Comment by anjesh** [comment]
This should be fixed now. Can you try once @JesseCCSI 
We have recently updated our API metadata fields names and structures as per recommedations by James. And a minor system setting was missed. Thanks for pointing out. Please try and let us know if you still face issue. Closing this for now.

**Comment by JesseCCSI** [comment]
Thanks @anjesh , this seems to be working now - will let you know if I notice otherwise.
