### ISSUE TITLE
Improvement in MTurk Interface

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#760]
Include the search by HIT-id in the RC-Mturk admin interface. Currently we have to query in the database to find the give HIT-id (e.g. https://github.com/NRGI/resourcecontracts.org/issues/551)

Include the Amazon MTrurk HIT link in the RC-Mturk admin interface (below) to quickly find the HIT in the amazon Mturk. Ideally when we are viewing the HIT, there should be link called "View HIT in Amazon".

**Comment by sadhakbj** [comment]
We have improved the MTurk Interface in the admin site.
Now we can search the contracts by HIT ID. (as seen in picture below).
![mturk_1](https://cloud.githubusercontent.com/assets/5828622/12776263/a2eced22-ca7c-11e5-9aa1-149f37992476.png)

After I provide HIT ID i am taken to another page:


(We can see that we have added see on amazon link which takes to Amazon task link.
![mturk_2](https://cloud.githubusercontent.com/assets/5828622/12776351/61464386-ca7d-11e5-9cd8-0dc6f4d4759e.png)
)

![mturk_3](https://cloud.githubusercontent.com/assets/5828622/12776386/b568ef7c-ca7d-11e5-9d84-b6a6b5cbf30d.png)
