### ISSUE TITLE
Search input above "Annotations List" should search both annotations and text

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#761]
Currently the "search input" searched for text content only as shown below. 
![image](https://cloud.githubusercontent.com/assets/120488/12385453/549d214a-bde4-11e5-9a1b-01f5ca2fb7d5.png)

As per this issue https://github.com/NRGI/resourcecontracts.org/issues/367, it should search for both annotation and text. The searched results will be listed by page, with one result per page. The annotations will also be listed by page. Annotations will be identified by "annotation icon" used elsewhere. Mock up will be shared shortly.

**Comment by sadhakbj** [comment]
- It's fixed now. 
![761_done](https://cloud.githubusercontent.com/assets/5828622/12745594/26dc7078-c9c2-11e5-8145-fd270ae4f4ff.png)
