### ISSUE TITLE
Admin Module: Type of contract drop down list

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#762]
The 'Type of Contract' drop down list isn't shown. You can access the values but its not clear that there are drop down values. 

![image](https://cloud.githubusercontent.com/assets/13888372/12411427/390db1bc-be87-11e5-98d4-d007a1895a88.png)

**Comment by anderspeders** [comment]
We are allowing multiple types of contract, and thus there is no drop down menu. 

This is for example the case when a contract is: Expliration license; Explitation license

**Comment by anjesh** [comment]
This particular case is due the simple looking and easy combolist UI library we are using https://select2.github.io/examples.html#multiple
