### ISSUE TITLE
Correct CSV export

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#764]
The CSV export is not able to export what appear to be French characters.

![image](https://cloud.githubusercontent.com/assets/120488/12871756/a960963a-cdb1-11e5-9b66-4ab6b9cfde20.png)

by @anjesh - Replaced with the smaller image for quick load.

**Comment by anjesh** [comment]
This csv unicode seems to be working now in the MS-excel, Linux libre office doesn't have this problem. However now the comma needs to be used as a separator now - all the columns are shown in the same column now. 
adding `sep=,` at the top of the csv file correctly parses the column data. @manishgs

**Comment by upasna01** [comment]
This issue is fixed now. Please the changes.
