### ISSUE TITLE
Contract PDF not loading 

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#765]
The contract below isn't loading (error message appears: We're sorry, there is a problem loading the contract. Please contact info@openlandcontracts.org to let us know, or check back later) 

The PDF was in "draft" on the back end -- I published it, but this hasn't fixed the problem. 

http://www.openlandcontracts.org/contract/ocds-591adf-LR3558292037OL/view

**Comment by anjesh** [comment]
API was updated incorporating the suggestions from James, and we created new index for new API, to avoid break PH-site tempoarily. There has been a mistake in index-name, and the publishing didn't publish to the new index and hence new API. It's fixed now. I republished again and it's now showing.
