### ISSUE TITLE
Admin Module: Signature Year

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#768]
Only 2015 and 2016 is in the signature year drop down list. 

![image](https://cloud.githubusercontent.com/assets/13888372/12774718/2a9a751e-ca50-11e5-918a-3d3154585710.png)

**Comment by hello-deepak** [comment]
Signature year is not drop down list ,it is  input field. 2015 and 2016 appears due to cache of your browser. 

Issue of signature year https://github.com/NRGI/resourcecontracts.org/issues/695 .
