### ISSUE TITLE
Published annotations not showing

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#769]
PH-EITI completed their first annotated contract. 

http://resourcecontracts.elasticbeanstalk.com/contract/76

The annotations are displayed on the PH-EITI site. 

http://contracts.ph-eiti.org/contract-view.html?contractId=76&contractTitle=Krominco,%20Incorporated%20-%20MPSA%20No.%20291-2009-XIII%20(Surigao%20Mineral%20Reservation),%202009&totalPages=21

But not on the RC site. 

http://www.resourcecontracts.org/contract/ocds-591adf-PH7733849609RC/view

**Comment by hello-deepak** [comment]
Its fixed now. 

http://www.resourcecontracts.org/contract/ocds-591adf-PH7733849609RC/view

**Comment by charlesyoung** [comment]
@jerico please take note.
