### ISSUE TITLE
Metadata: Company name not published

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#770]
Company names for Sierra Leone contracts are captured and published. 

http://resourcecontracts.elasticbeanstalk.com/contract/701

Although its not showing on the public site. 

http://www.resourcecontracts.org/contract/ocds-591adf-SL0498783225RC

**Comment by anjesh** [comment]
Company name is now displayed.

**Comment by charlesyoung** [comment]
This is still an issue. 

![image](https://cloud.githubusercontent.com/assets/13888372/13102188/a6f2fa3c-d554-11e5-9894-0b6d106c6bd1.png)

![image](https://cloud.githubusercontent.com/assets/13888372/13102242/0ecb0be0-d555-11e5-8886-4696a3e43e4d.png)

**Comment by sadhakbj** [comment]
- Its fixed on country site also:
![770_fixed](https://cloud.githubusercontent.com/assets/5828622/13142047/a4e6e244-d662-11e5-942c-b093302fa631.png)
