### ISSUE TITLE
Tracking missed imports of annotations

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#771]
One missing flagged from Mongolia: 
https://www.documentcloud.org/documents/1097724-investment-agreement-oyu-tolgoi.html

Need to follow up on Afghanistan contracts as well.

**Comment by anderspeders** [comment]
@anjesh has confirmed that an overview will be provided so that the review can be systematised.

**Comment by anderspeders** [comment]
Example: I did a review of Liberia contracts: 

Documentcloud includes 25 annotated contracts: https://www.documentcloud.org/search/Group:%20miningoilcontracts%20Countries:%20%22Liberia%22
RC.org holds: 13 annotated contracts: http://www.resourcecontracts.org/search?q=&country%5B0%5D=lr&page=1

That is a miss rate in migration of ~ 50%

Now, some of these might only hold minimal metadata - but many of them have approx. 20 notes/annotations which seems to indicate more than basic metadata. 

This seems to indicate that we need a comprehensive review across the doc-cloud database to see which were not included in the migration.

**Comment by anderspeders** [comment]
I would suggest an overview such as this as spreadsheet: https://docs.google.com/spreadsheets/d/1kxSqanKv53secCRxjVGtM94tDw5JbzIUnNItsdlnNXI/edit#gid=0

We will need some way to verify if each contract had the annotations successfully migrated.

**Comment by manishgs** [comment]
[Spread sheet ](https://docs.google.com/spreadsheets/d/1kxSqanKv53secCRxjVGtM94tDw5JbzIUnNItsdlnNXI/edit#gid=0)has been updated. 

Please note that following contracts have same pdf file so we linked to same contract ( which is [1215](http://admin.resourcecontracts.org/contract/1215))

http://www.documentcloud.org/documents/1710314-petroleum-agreement-kosmos-cap-boujdour-see.html
http://www.documentcloud.org/documents/1509890-kosmos-energy-block-c13-mauritania-2012.html
http://www.documentcloud.org/documents/1376099-kosmos-energy-suriname-2011.html
http://www.documentcloud.org/documents/1376099-kosmos-energy-suriname-2011.html
http://www.documentcloud.org/documents/1509885-kosmos-energy-block-c8-mauritania-2012.html
http://www.documentcloud.org/documents/1509888-kosmos-energy-block-c12-mauritania-2012.html

**Comment by hello-deepak** [comment]
The annotation of following contract has been migrated.

http://admin.resourcecontracts.org/contract/175
http://admin.resourcecontracts.org/contract/705
http://admin.resourcecontracts.org/contract/9
http://admin.resourcecontracts.org/contract/706
http://admin.resourcecontracts.org/contract/18
http://admin.resourcecontracts.org/contract/1185
