### ISSUE TITLE
Harmonization of annotations currently loaded

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#772]
YI has now been able to review the options for the harmonization required for annotations which does not have the same text. This relates to the implementation of this ticket: https://github.com/NRGI/resourcecontracts.org/issues/694

The new annotation model requires harminization of the current annotation data available in the following cases: 
The <annotation text> field from previously loaded annotations will need to be fitted to the new annotation model in cases where **more than one annotation appear for a specific category and provised different text within each annotation** :

Let's take an example: http://www.resourcecontracts.org/contract/ocds-591adf-NG0817821030RC/view#/pdf/page/14/annotation/13062 

The contract above has several annotations under **Other - operational**. For the conversation to the new annotation model we could go with the following models: 
 
-	A) Apply the first appearing annotation text only: [Annotation 1 only]

A) would be implemented with the following text: 
Operator: The Project Management Team (the “PMT”), i.e. a team made up of personnel from NPDC and Septa appointed by the Management committee and controlled by Septa for a minimum of 3 years and a maximum of 5 years from the date the agreement becomes effective, will be responsible for the carrying out of petroleum operations. After this period, NPDC will take over operations under the agreement; Management Committee: A Management Committee (the “Committee”) must be established within 30 days of the agreement becoming effective in order to direct and supervise all matters relating to petroleum operations and work on the contract area. The Committee must consist of 4 persons appointed by NPDC and 4 appointed by Septa. Unless otherwise agreement by NPDC and Septa, the Committee must meet at an NPDC office once every 3 months from the effective date onwards. Further details regarding the powers and duties of the Committee are contained in Art. 7.

-	B) Merge the various annotation texts: [Annotation text 1; Annotation text 2; etc.]

B) would be implemented with the following text: 
Operator: The Project Management Team (the “PMT”), i.e. a team made up of personnel from NPDC and Septa appointed by the Management committee and controlled by Septa for a minimum of 3 years and a maximum of 5 years from the date the agreement becomes effective, will be responsible for the carrying out of petroleum operations. After this period, NPDC will take over operations under the agreement; Management Committee: A Management Committee (the “Committee”) must be established within 30 days of the agreement becoming effective in order to direct and supervise all matters relating to petroleum operations and work on the contract area. The Committee must consist of 4 persons appointed by NPDC and 4 appointed by Septa. Unless otherwise agreement by NPDC and Septa, the Committee must meet at an NPDC office once every 3 months from the effective date onwards. Further details regarding the powers and duties of the Committee are contained in Art. 7.;  NPDC will take over petroleum operations under the agreement after a minimum of 3 years and a maximum of 5 years from the effective date. After this takeover, Septa will cease to control the Project Management Team. When this takes place, Septa must transfer the following to NPDC: (i) possession of all property and funds held by Septa, (ii) originals of books and accounts, (iii) originals of any documents relating to operations. 

---

I have double checked with YI and it will not be possible to both create the new data model for the annotations without harmonizing existing annotations to this system. 

@KaitlinCCSI @samCCSI could you have a look to see what you think would be a most suitable option?

@anjesh please review that the scenarios are as discussed

**Comment by KaitlinCCSI** [comment]
Before weighing in on preferred option, is there a way (1) to understand how many contracts are in this situation of having more than 1 annotation in a field? And (2) regardless of which option is chosen, to document which contracts _and_ annotation fields this affects and to save an older version of the annotations somewhere before they are changed? This would help us to go in and fix annotations that have been changed, and knowing the answers to both these questions might help us decide on best option.

**Comment by anderspeders** [comment]
Anjesh has confirmed he will provide an overview in a spreadsheet.

**Comment by anjesh** [comment]
Here's the list of all the harmonized annotations in the database. There's a field "Merge Required" - which has Yes if that particular annotation needs to be fixed/merged with another annotation-category of the same contract. There are altogether 249 annotations that need harmonisation. 
[annotations-fixing.xlsx](https://github.com/NRGI/resourcecontracts.org/files/121420/annotations-fixing.xlsx)

**Comment by KaitlinCCSI** [comment]
Thanks, Anjesh. We'll go with Anders's option B: Merge the various annotation texts: [Annotation text 1; Annotation text 2; etc.]

**Comment by anderspeders** [comment]
Thanks @kaitlin, 

@anjesh: Please initiate implementation.

**Comment by SamCCSI** [comment]
@anderspeders @anjesh can you let us know when all annotation entries that have been merged, so that we can efficiently go through the spreadsheet and harmonize as needed?

cc @KaitlinCCSI

**Comment by anderspeders** [comment]
@SamCCSI @KaitlinCCSI: 

Here is my understanding of where we are at in the process.

YI has identified all contracts where there are multiple annotations for the same category. 

In the sheet below you will find these listed. I have filtered the document to show annotation where merge / harmonization is required. Column A provides the contract.  

Document is here: 
https://docs.google.com/spreadsheets/d/1j95EpG0Wyc699aR7QK6-X-UfT6MsI2sz8MNo0soEsEc/edit#gid=67537023

I would suggest that you review the content to see if the general rule you have recommended can apply for them all - or if you wish to conduct custom edits. 

Let me know if this makes sense. 

@manishgs: Please await of recommendations for next steps here.

**Comment by SamCCSI** [comment]
@anderspeders to confirm that we will hold of the auto-harmonization for now.

@anderspeders @anjesh Is it possible for you to produce a similar spreadsheet of annotations needing harmonization for OLC? This would be very useful for us.

**Comment by manishgs** [comment]
Any progress on harmonization process? We need to confirm the process ASAP as we already deployed   new annotation module in [admin demo](http://resourcecontracts-demo1.elasticbeanstalk.com) ([subsite](http://rc-site-demo.elasticbeanstalk.com/rc/public/)) without harmonizing the annotations.

**Comment by SamCCSI** [comment]
@manishgs  Checking with our researcher - will be in touch.

**Comment by SamCCSI** [comment]
@manishgs our researcher has completed the harmonization of annotations, but did not touch PH EITI annotations, as they are under the control of PH EITI staff.

**Please note: Any auto-harmonization must not apply to the PH EITI annotations for this reason.
**
Before giving you the go-ahead, is it possible for you to generate another spreadsheet to identify any instances of more than one entry for an annotation category again? I ask because our researcher found additional instances that weren't included on the previous spreadsheet.

Also, @manishgs @anderspeders @anjesh is it even necessary to run the auto-harmonization if we have had our researcher go through and do this manually?

**Comment by manishgs** [comment]
Here is the regenerated csv file as you requested.
[export2016-03-23.csv.zip](https://github.com/NRGI/resourcecontracts.org/files/185554/export2016-03-23.csv.zip)

Can you please explain how researcher are doing harmonization of annotations? Are they doing from admin system itself or on[ spreadsheet](https://docs.google.com/spreadsheets/d/1j95EpG0Wyc699aR7QK6-X-UfT6MsI2sz8MNo0soEsEc/edit#gid=67537023)?

`is it even necessary to run the auto-harmonization if we have had our researcher go through and do this manually?`
Yes we need to run auto harmonization to work new annotation module perfectly. 
For example, we'll auto merge below annotations  to  "text1 ; text2 ; text3 ; text4"
679	other-financialfiscal	68	yes     text1
679	other-financialfiscal	50	yes     text2
679	other-financialfiscal	52	yes    text3
679	other-financialfiscal	35	yes    text4

**Comment by SamCCSI** [comment]
Thanks @manishgs 

Our researcher has been making changes in the backend (editing or deleting annotations).

He will check this revised spreadsheet now, and I will get back to you.

Can you confirm that you will not auto-harmonize annotations on contracts from the Philippines? cc @anderspeders @charlesyoung

**Comment by anderspeders** [comment]
Thanks @SamCCSI, 

The deployment of the finalized annotation module is pending on the completion of your review. Please confirm when you will have this completed - would Wednesday COB this week be possible?

With regards to the second question; I am unsure what the implications will be for the Philippines site.

**Comment by charlesyoung** [comment]
@manishgs will it be possible to pull a spreadsheet only focusing on the Philippines?

**Comment by upasna01** [comment]
[Here](https://docs.google.com/spreadsheets/d/1j95EpG0Wyc699aR7QK6-X-UfT6MsI2sz8MNo0soEsEc/edit#gid=1643753439) is the annotations for Philippines.

**Comment by anderspeders** [comment]
Ok, @upasna01 @manishgs @anjesh, 

We have not done any edits to the Pilippines annotations. 

We are ready to go on the implementation here. Please address if you have any questions.

**Comment by SamCCSI** [comment]
@anderspeders what does 'implementation' mean here? Is there a risk that the auto-harmonization will alter the Philippines annotations? If so, this should be avoided. cc @charlesyoung

**Comment by anjesh** [comment]
Fixed long time back.
