### ISSUE TITLE
Zooming affects location of annotation marker

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#773]
The marker does not stay circled over the correct text when you zoom in.

We plan to use the markers this way, so this needs to be addressed.

The screenshots were from the back-end. I couldn't find an example on the live site to try this on because the PH EITI site that contains this contract has no zoom bars: http://contracts.ph-eiti.org/contract-view.html?contractId=76&contractTitle=Krominco,%20Incorporated%20-%20MPSA%20No.%20291-2009-XIII%20(Surigao%20Mineral%20Reservation),%202009&totalPages=21#/pdf/page/6/annotation/26618

![image](https://cloud.githubusercontent.com/assets/12913915/12856223/d04d21f6-cc11-11e5-908f-ef6dd093f839.png)
![image](https://cloud.githubusercontent.com/assets/12913915/12856227/d30584f6-cc11-11e5-8799-b4a19b3b05ad.png)

**Comment by manishgs** [comment]
fixed.
