### ISSUE TITLE
Add information on Main contract and Associated document to right bar in contract view page

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#777]
Add the following information to the right bar for the contract view page:  

**Main contract**: This will state the parent contract if there is any
**Associated documents**: This will list the <Associated documents> in relation to the contract

As per contract tally proposal from @KaitlinCCSI @SamCCSI. Could you confirm that this is correctly understood?

Adding below what was listed in the doc: 
Contract View Page (for Associated Documents proposal)
We would link an Associated Document with the Main Document as we are already able to do. Thus, in the contract view page, a user looking at a “Associated Document” document would see the “Main Document” and other Associated Documents listed in the right-hand column (under category “Associated Documents”). 
The design should somehow note the “Main Document” – perhaps by the order, per earlier mockups provided. A user looking at the Main Document would see the Associated Document(s) listed in the right-hand column.

**Comment by anjesh** [comment]
Do you think adding some icon for main contracts and associated documents in this contract view would be helpful to users? Hovering over the icon will show the help text (like this is main contract). We can use the same icons in the search results page when listing the documents (contract vs associated documents).

**Comment by jedm** [comment]
For easy references, see mockup [in comment here in #750](https://github.com/NRGI/resourcecontracts.org/issues/750#issuecomment-172134523]), also #624 and #470 .

**Comment by SamCCSI** [comment]
Thanks all, I think we are all on the same page.

@jedm & @KaitlinCCSI : the only thing the mockups don't cover is how we will signpost  if a main contract is listed, other than listing it at the top of the list of "Related". Underlining the main contract had previously been suggested, and @anjesh has suggested icons above. Any thoughts? I think bold or underlining + hover as described by Anjesh could be enough.

**Comment by jedm** [comment]
Agree that bold and hover should be enough. Would not do underline b/c of natural confusion with links.

Another option would be indents, eg,

• Main Contract
  • Related 1
  • Related 2 
  • Related 3

**Comment by anderspeders** [comment]
Both options sound good to me. 

To clarify further regarding links: Do we agree that we do not simply *list* the documents but also *hyperlink* them? That would be my suggestion anyways given that users would be expected to want to navigate between contracts.

**Comment by SamCCSI** [comment]
I agree hyperlinking to the docs makes sense.

On Mon, Feb 8, 2016 at 5:09 PM, Anders <notifications@github.com> wrote:

> Both options sound good to me.
>
> To clarify further regarding links: Do we agree that we do not simply
> *list* the documents but also *hyperlink* them? That would be my
> suggestion anyways given that users would be expected to want to navigate
> between contracts.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/777#issuecomment-181582805>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School | The Earth Institute, Columbia University
435 W116th St. New York, NY 10027
| (+1)(212) 854-2635 <+1212-854-2635> | (+1)(646) 630-4123 <+1646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by anderspeders** [comment]
Thanks. Sounds good. 

@anjesh: I think this should now be ready for implementation

**Comment by anjesh** [comment]
For now, we will just list all the associated documents. If we are viewing the associated document, the main contract will be the first one in the list. All the files will be listed with links. Titles will be shortened to certain number of characters to fit in the two lines, followed by ellipsis. 

We will look into the possibility of adding icon near the associated document (could be as simple as A within a circle). Hovering over the icon will show that it's an associated document.

**Comment by jedm** [comment]
Based on the comments above, the use of bold on the "main contract" or indent for the "non-main" docs is preferable to the icon. 

(Others please comment if the icon is preferred.)

**Comment by KaitlinCCSI** [comment]
Agree with Jed. If bold for "main contract" looks okay, would go with that
to ensure that less of the "non-main" doc titles are cut off (which would
happen if we indented).

On Wed, Feb 10, 2016 at 8:54 AM, jedm <notifications@github.com> wrote:

> Based on the comments above, the use of bold on the "main contract" or
> indent for the "non-main" docs is preferable to the icon.
>
> (Others please comment if the icon is preferred.)
>
> > On Feb 10, 2016, at 12:30 AM, Anjesh <notifications@github.com> wrote:
> >
> > For now, we will just list all the associated documents. If we are
> viewing the associated document, the main contract will be the first one in
> the list. All the files will be listed with links. Titles will be shortened
> to certain number of characters to fit in the two lines, followed by
> ellipsis.
> >
> > We will look into the possibility of adding icon near the associated
> document (could be as simple as A within a circle). Hovering over the icon
> will show that it's an associated document.
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/777#issuecomment-182406623>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01QgCSlOf&m=90d1cfbb7d98&t=20160210&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01QgCSlOf&m=90d1cfbb7d98&t=20160210&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01QgCSlOf&m=90d1cfbb7d98&t=20160210&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by sadhakbj** [comment]
This has been implemented now as per the decision: 
The main contract is bold and other contracts are displayed as normal:

![associated_doc_bold](https://cloud.githubusercontent.com/assets/5828622/13066585/c4c7ac12-d48f-11e5-9a97-84de79c47242.png)

**Comment by jedm** [comment]
@sadhakbj and @anjesh please advise if this is implemented on the Contract view page and where we can see an example so we can finalize formatting. Thanks.

**Comment by upasna01** [comment]
Link to associated contract is implemened on the Contract view page, in metadata.
Here is the contract with associated documents. Please do verify.

http://www.resourcecontracts.org/contract/ocds-591adf-CG4710691717RC/view
![links](https://cloud.githubusercontent.com/assets/11477899/15524913/4db64ec2-2245-11e6-9d47-ecd40d64591b.png)

**Comment by jedm** [comment]
Deepak can we see an example with multiple documents, to see how lists look and how to differentiate "Parent" documents from "Sibling" documents?

Also, style of heading should be changed. If it is bold it should be all-caps, to match ANNOTATIONS and METADATA headings. Or if it is Initial Caps then should be gray to match the headings above it.

**Comment by upasna01** [comment]
Here is the link contract with multiple associated documents. The parent documents are bold.

Parent Document
http://www.resourcecontracts.org/contract/ocds-591adf-PE1651033763RC/view

Child document
http://www.resourcecontracts.org/contract/ocds-591adf-PE1651033763RC-1553/view

and image for it. Please do verify.
![link](https://cloud.githubusercontent.com/assets/11477899/15607227/f5b7e1ac-2430-11e6-994d-9fb8b148d8a7.png)

**Comment by jedm** [comment]
Looks good. A few fixes, please:

- In previous section, ("Disclosure Mode") delete extra hr after link (first X in image below)
- Delete hr separating first set of details from Associated Docs section (second X in image below)
- Move Associated Docs section higher
- Change Heading text ("Associated Documents") to same color gray as other headings in column - important to be consistent

Finally, I think the simple emphasis of bold for a Parent doc is ok, but I recommend adding a SMALL indentation for "Child" documents. Recommend just two spaces or nbsps. @KaitlinCCSI @anderspeders what do you think?

![assoc_doc](https://cloud.githubusercontent.com/assets/2153664/15660856/9fd735e0-2696-11e6-8d09-5adedb52e51f.jpg)

**Comment by SamCCSI** [comment]
I like the idea of a small indentation for "child" documents.



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School | The Earth Institute, Columbia University
435 W116th St. New York, NY 10027
| (+1)(212) 854-2635 <+1212-854-2635> | (+1)(646) 630-4123 <+1646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

*New Report: Land Deal Dilemmas: Grievances, Human Rights, and Investor
Protections
<http://ccsi.columbia.edu/2016/03/10/land-deal-dilemmas-grievances-human-rights-and-investor-protections/>*
Available at: *http://goo.gl/qctX9I <http://goo.gl/qctX9I>*

**Comment by KaitlinCCSI** [comment]
Agree with small indentation for child docs.

**Comment by upasna01** [comment]
The issue is fixed, please do verify.

http://www.resourcecontracts.org/contract/ocds-591adf-PE1651033763RC-1553/view

![777](https://cloud.githubusercontent.com/assets/11477899/16481640/fe474f3c-3ecb-11e6-8e18-3e1e026b5b42.png)

**Comment by jedm** [comment]
Looks good thanks!
