### ISSUE TITLE
Drop-down Search bar exits the contract you're in

### ISSUE THREAD

**Issue by jedm** [NRGI/resourcecontracts.org#779]
Experiencing an issue from [a single contract page](http://www.resourcecontracts.org/contract/ocds-591adf-GN2128614408RC) where, when you click the site Search at very top of page, Canceling the drop down pulls you out of the page you're in and back to a full-site search results page with all contracts.

![search_cancel_bug1](https://cloud.githubusercontent.com/assets/2153664/12929931/8443e968-cf2a-11e5-8435-d8260ebe0d3c.png)

![screen shot 2016-02-09 at 12 40 00 pm](https://cloud.githubusercontent.com/assets/2153664/12929937/8eea0e2e-cf2a-11e5-8e15-e1525d80640c.png)

**Comment by jedm** [comment]
Relevant to #524 also.

**Comment by anjesh** [comment]
This is a bug.

**Comment by hello-deepak** [comment]
Fixed.
