### ISSUE TITLE
Improve annotation experience: Review annotator JS plug-ins for inspiration / ideas

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#78]
Lots of plug-ins available here:
http://annotatorjs.org/plugins/index.html

Review list and check if any plugins would be useful:

**Comment by anjesh** [comment]
Continuing to next sprint

**Comment by anjesh** [comment]
Just for ideas, so we don't need to assign to particular sprint.

**Comment by upasna01** [comment]
Thank you for your suggestions.
