### ISSUE TITLE
Associated doc attached to wrong contract 

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#780]
See below for screenshots -- I checked the back end and it doesn't appear that this document was associated with the Salala contract. When I click on the hyperlinked Mongolia Ivanhoe associated doc, error 404 appears.  

http://www.openlandcontracts.org/contract/ocds-591adf-LR2859639544OL/view

![salala-associated docs](https://cloud.githubusercontent.com/assets/14910764/13009897/ed5f28c4-d16c-11e5-899f-b5b47af393f7.png)

Salala back end 
![salala-back end](https://cloud.githubusercontent.com/assets/14910764/13009979/6a2b3118-d16d-11e5-8374-3b689fcd192d.png)

Mongolia Ivanhoe back end 
![ivanhoe_back end](https://cloud.githubusercontent.com/assets/14910764/13009976/66cb7852-d16d-11e5-85ca-0763855c1cc3.png)

**Comment by sadhakbj** [comment]
- It's fixed now.
![780_sub_site](https://cloud.githubusercontent.com/assets/5828622/13066531/09af84e0-d48f-11e5-8017-8dae9394def0.png)
