### ISSUE TITLE
Contract quality dashboard - returning wrong results

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#781]
Example: Display all contracts with missing <Signature date>
http://resourcecontracts.elasticbeanstalk.com/contract?type=annotations&word=date-contract-signature&issue=present

Please review the dashboard for wrongly returned values.

**Comment by manishgs** [comment]
Could you please provide us more information or screenshot that displaying wrong results so that we can fix the issue?

**Comment by anderspeders** [comment]
I will need to review this as I cannot see issues at the moment. Will reopen once I find it.
