### ISSUE TITLE
Auto-fit the width of the PDF contract to view

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#782]
![image](https://cloud.githubusercontent.com/assets/1101585/13082864/6dd16810-d4a0-11e5-9fda-72438d51f6da.png)

Feedback from a training with government agency in Mexico: Could we develop auto-fitting for the center window on the contract view page so that users do not have to scroll **horizontally** on the screen?

@samCCSI @KaitlinCCSI: Not sure if you have addressed this in previous issues?

**Comment by KaitlinCCSI** [comment]
I've never noticed this being an issue unless you're zoomed in?

On Tue, Feb 16, 2016 at 10:31 AM, Anders <notifications@github.com> wrote:

> [image: image]
> <https://cloud.githubusercontent.com/assets/1101585/13082864/6dd16810-d4a0-11e5-9fda-72438d51f6da.png>
>
> Feedback from a training with government agency in Mexico: Could we
> develop auto-fitting for the center window on the contract view page so
> that users do not have to scroll *horizontally* on the screen?
>
> @samCCSI <https://github.com/samCCSI> @KaitlinCCSI
> <https://github.com/KaitlinCCSI>: Not sure if you have addressed this in
> previous issues?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/782>.
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01Qj4v8up&m=44ff24a52c93&t=20160216&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01Qj4v8up&m=44ff24a52c93&t=20160216&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01Qj4v8up&m=44ff24a52c93&t=20160216&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by anderspeders** [comment]
Ok, thanks @KaitlinCCSI, 

Suggest not scheduling for current as we still have unfinished business from sprint 13.

**Comment by SamCCSI** [comment]
I encounter this problem (at 100% zoom) on my screen at the office. On my
laptop screen (which is wider) it isn't a problem.

On Fri, Feb 19, 2016 at 10:26 AM, Anders <notifications@github.com> wrote:

> Ok, thanks @KaitlinCCSI <https://github.com/KaitlinCCSI>,
>
> Suggest not scheduling for current as we still have unfinished business
> from sprint 13.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/782#issuecomment-186259303>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School | The Earth Institute, Columbia University
435 W116th St. New York, NY 10027
| (+1)(212) 854-2635 <+1212-854-2635> | (+1)(646) 630-4123 <+1646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by manishgs** [comment]
We can't auto-fit the width of pdf to view.  We've increase the width of pdf view so that scroll will not be shown on the screen which is more than 1250px. To support less than 1250px screen we need to hide metadata section on page load then there will be toggle button to show/hide the section.

**Comment by manishgs** [comment]
Please reopen if you encounter this issue again.
