### ISSUE TITLE
Returned Mech Turk is inserted with html text in introduction

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#783]
![image](https://cloud.githubusercontent.com/assets/1101585/13243922/67a27472-d9d0-11e5-9f1d-4c23aa420636.png)

http://www.resourcecontracts.org/contract/ocds-591adf-CD2705996019RC-1256/view#/text

It seems that the Mech Turk text itself is inserted nicely but that something is going wrong at the start of the text insert.

**Comment by upasna01** [comment]
The issue have been fixed, please review the change.
![dd](https://cloud.githubusercontent.com/assets/11477899/13493978/a106ffa8-e169-11e5-9882-dd4471949764.png)
