### ISSUE TITLE
Sub Site Admin Abilities.

### ISSUE THREAD

**Issue by sadhakbj** [NRGI/resourcecontracts.org#784]
Sub site (olc , rc and country) needs to have admin abilities. So that the admin can
 * Add New Pages 
* Delete the Pages 
* Change Homepage Image , Sidebar Image  
* Change the basic colors.

**Comment by sadhakbj** [comment]
Its implemented in demo site. Please check it here. http://rc-site-demo.elasticbeanstalk.com/country/public/admin/theme

**Comment by charlesyoung** [comment]
Just updated the background image but it hasn't changed. Is it cached? 

![image](https://cloud.githubusercontent.com/assets/13888372/13524737/c44bed24-e205-11e5-8a99-2925691dde37.png)

**Comment by charlesyoung** [comment]
OK works.

**Comment by charlesyoung** [comment]
Looking good, two questions. 

1. I don't think the secondary colour works. 

![image](https://cloud.githubusercontent.com/assets/13888372/13526015/b7d0e506-e20d-11e5-89b7-b99f6e8cd155.png)

2. The Resource and FAQ's pages aren't  shown on the site. How can these pages be made visible? 

![image](https://cloud.githubusercontent.com/assets/13888372/13526081/3f6889ba-e20e-11e5-914c-dc37a8367f5c.png)

**Comment by charlesyoung** [comment]
Is the secondary colour the colour when clicking on the search button? If this is the case then how can the side bar colour be changed?

**Comment by manishgs** [comment]
Secondary color used in hover color like search button and anchor link color in footer.

![screenshot- domain date time 1](https://cloud.githubusercontent.com/assets/3942999/13567087/43e59062-e481-11e5-80c8-6d087597203e.png)

**Comment by charlesyoung** [comment]
Will it be possible to add an option to change the side bar colour? 

Are you factoring in the the new homepage design?

**Comment by sadhakbj** [comment]
Yes it's possible to update the side bar color. This has already been implemented and deployed in the demo site. Please check it once.

**Comment by sadhakbj** [comment]
-
