### ISSUE TITLE
Amending title of item in the "Company" box (on Summary Page) 

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#787]
Please see the screenshot below -- this should be **OpenCorporates ID** (i.e. please add an "s" at the end, and remove the space between "Open" and "Corporates"). 

Many thanks. 

![screen shot 2016-02-26 at 13 46 19](https://cloud.githubusercontent.com/assets/14910764/13354105/c973337c-dc90-11e5-9bd5-b6fee5106053.png)

cc @SamCCSI @KaitlinCCSI

**Comment by upasna01** [comment]
Change have been implemented. Here is the snapshot for it. Please do review.
![opencorporats](https://cloud.githubusercontent.com/assets/11477899/13518208/9b4c7824-e1f3-11e5-9e1b-09b53fe6fef3.png)

**Comment by SamCCSI** [comment]
Looks great, thanks @upasna01
