### ISSUE TITLE
 Clipping feature for annotations

### ISSUE THREAD

**Issue by manishgs** [NRGI/resourcecontracts.org#789]
I've created mocks to illustrate clipping feature for annotation. [Click here](https://app.moqups.com/manish.singh@yipl.com.np/SBjO9Tl4/view) to see the UI. Please review the mocks and we can further discuss clipping feature here is this issue

@anderspeders  @anjesh

**Comment by manishgs** [comment]
Following mockups illustration the workflow for clipping annotations

There will be a menu called "Clip" in header section on every page which shows the current no. of  clipped annotations. 



![screenshot from 2016-03-14 14 59 17](https://cloud.githubusercontent.com/assets/3942999/13741900/f829075a-ea00-11e5-9826-9509dfeb3195.png)


User can clip individual annotation or all annotations at once in contract summary page. 

Red clip icon indicates annotation is already clipped and Gray icon indicates annotation is not clipped.
User can  clip/unclip  annotation by simply clicking the icon button.

![screenshot from 2016-03-14 14 59 45](https://cloud.githubusercontent.com/assets/3942999/13741901/f828de56-ea00-11e5-9d4f-7803028b356c.png)

Single annotation and all annotations of  the contract can be clipped from contract view page.
![screenshot from 2016-03-14 16 22 18](https://cloud.githubusercontent.com/assets/3942999/13741899/f825d972-ea00-11e5-9217-c283eceae855.png)


Following mockup shows how clip page look like. In this page user can see all the clipped annotations. User can remove clipped annotation by clicking remove icon.  There will be anchor link on contract name and annotation which will take user to respective page.

**Share :** user can share clipped annotation to other via email.
**Download :** user can download annotations in excel format.
**Print:** user can print all the annotations.




![screenshot from 2016-03-14 16 17 19](https://cloud.githubusercontent.com/assets/3942999/13741902/f829104c-ea00-11e5-84de-79c0f2901807.png)

@anderspeders

**Comment by manishgs** [comment]
Any feedback? @anderspeders

**Comment by jedm** [comment]
Per #22 , suggestions for hovers added to Google doc linked below. Hovers in mockups from @manishgs above are numbers in vertical order for reference in Google doc.

**Comment by jedm** [comment]
For mockup attached above:

- Add "learn more" link or (?) (or standard Help link for RC/OLC) and link that to full explanation of Clips function
- Change name of function from "Clip" to "Clips"

**Comment by jedm** [comment]
For [last mockup](https://cloud.githubusercontent.com/assets/3942999/13741902/f829104c-ea00-11e5-84de-79c0f2901807.png) attached above:

- Not sure how share functions and options would work - need clarification from YI
- Design, icons and UX for share, download, print, should match share tools in rest of site
- Would this layout look same as standard Search results display as spec-ed or different?
- Not sure how column categories are meant to work - need clarification
- Change page title and feature title to "Clips"

**Comment by anderspeders** [comment]
Thanks @jedm, 

@manishgs: Can you review please?

**Comment by manishgs** [comment]
> the specs provided proposed that Clips function can be switched on and off to avoid visual clutter in Annotations list - need clarification if this is in current UX
We are not implementing clips f

**Comment by manishgs** [comment]
> the specs provided proposed that Clips function can be switched on and off to avoid visual clutter in Annotations list - need clarification if this is in current UX
Current UI have clip icon to add/remove annotation. It'll make user easier to clip/unclip annotation. I don't think it will make visual clutter in annotation list.

> Not sure how share functions and options would work - need clarification from YI
User can share clipped annotation via email. An email will be sent with a link. Shared link will be same excep  page can view the clipped annotation by the

**Comment by manishgs** [comment]
> the specs provided proposed that Clips function can be switched on and off to avoid visual clutter in Annotations list - need clarification if this is in current UX

From user prospective, Clips function on/off feature will add additional step to them so we can skip this feature. If user is viewing annotation they can directly clip/unclip annotation without scrolling to top and on/off the feature. I don't think having clip icon in annotation list will make visual clutter.

> Not sure how share functions and options would work - need clarification from YI

User can share clipped annotation via email.  User can share clips to multiple emails.  Email body will have a link of clipped list page. 

> Would this layout look same as standard Search results display as spec-ed or different?

Yes, we need to design the page to follow the current standard.

> Not sure how column categories are meant to work - need clarification

Category column is annotation category.

**Comment by jedm** [comment]
@manishgs Clipping is an activity that many people will not do, so we should include the On/Off function as spec-ed.

Regarding the other elements, will compile questions for clarification after this week's group check-in. Many thanks for these initial replies!

**Comment by anjesh** [comment]
Further discussion on clips here 
https://github.com/NRGI/resourcecontracts.org/issues/893
