### ISSUE TITLE
annotations buggy

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#793]
In this contract, the annotation boxes at the top of the page only work sometimes -- clicking on them will occasionally link to the relevant annotation in left, but other times clicking on them does nothing.

http://www.openlandcontracts.org/contract/ocds-591adf-SS5768196941OL/view#/pdf/page/2/annotation/25408

**Comment by JesseCCSI** [comment]
FYI none of the annotation boxes and yellow annotation markers appear for me when viewing this contract

**Comment by manishgs** [comment]
fixed.
