### ISSUE TITLE
Migirated OLC contract missing last ten pages

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#794]
Online version has 39 pages. It should have 49 pages.
http://www.openlandcontracts.org/contract/ocds-591adf-CM4083500829OL/view#/pdf/

Here is PDF: https://www.dropbox.com/s/q0kv5en5h2abexa/SGSOC%20Cameroon.pdf?dl=0

Annotations appear on pages after p. 39.

Added complication: this has already been through MT for 38 of the 39 pages, so we don't want to lose those transcriptions once the PDF is re-uploaded.

Can you please advise us on what we should do?

We were planning to teach a masterclass using this contract and OLC on March 18, so would appreciate a quick resolution.

@anderspeders @anjesh 

CC @KaitlinCCSI @jesseccsi

**Comment by manishgs** [comment]
We've added missing pdfs in s3 and pages in database.

Confirm the  pages [here](http://admin.resourcecontracts.org/contract/1150/annotate)

We have also created [MTurk HITs](http://admin.resourcecontracts.org/mturk/1150) for missing pages

You can send text to RC once transcription completed of all missing pages.

**Comment by SamCCSI** [comment]
Thanks @manishgs this is great.

One problem: I got the "Assignment could not be approve." error message when trying to approve one of those MT pages that had been transcribed.

**Comment by manishgs** [comment]
Its fixed now.
