### ISSUE TITLE
Company name drop down list

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#796]
Should there not be a drop down list of existing companies allowing the Uploader to select the company name, if already in the database, rather than creating duplicate companies like below. 

![image](https://cloud.githubusercontent.com/assets/13888372/13496213/99cff5ee-e157-11e5-88c2-7b84cdd1af18.png)

![image](https://cloud.githubusercontent.com/assets/13888372/13496163/5ba83ba0-e157-11e5-901b-ba4341f6282d.png)

**Comment by anderspeders** [comment]
I think there are a few options here: 

1) @anjesh: Could you implement a "pick list" from excitsting company names (in the  ResourceContracts database) on the back end?
2) Charles: We should harmonize names that are obviously the same. I will create a new ticket for this.

**Comment by charlesyoung** [comment]
Relating to case #798

**Comment by charlesyoung** [comment]
@anjesh I noticed that this ticket has been tagged as done. Is it deployed on the demo site?
