### ISSUE TITLE
Harmonize company names that are identical

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#798]
Example here: 
https://cloud.githubusercontent.com/assets/13888372/13496213/99cff5ee-e157-11e5-88c2-7b84cdd1af18.png

This could likely be done by having a review of the full dataset.

**Comment by charlesyoung** [comment]
@anjesh will it be possible to create a xls that lists all the companies which will allow me to check for duplicate companies and harmonize where required?

**Comment by manishgs** [comment]
I've generated unique companies from database .
[company_name_data.xlsx](https://github.com/NRGI/resourcecontracts.org/files/158337/company_name_data.xlsx)
Let us know you when you complete the harmonization.

**Comment by charlesyoung** [comment]
Thanks @manishgs. Can I ask you to add the relevant contract name in attached xls (highlighted cells) because I will need to check the contracts to determine the correct company name. 

Question; are companies captured in upper case (CAMAC ENERGY KENYA LIMITED) compared to capitalized case (CAMAC Energy Kenya Limited) recorded as two different companies? 

[company_name_data.xlsx](https://github.com/NRGI/resourcecontracts.org/files/158465/company_name_data.xlsx)

**Comment by manishgs** [comment]
Could not update the excel sheet you have attached as contract data has been updated on server. I've regenerated the excel sheet with contract name.
[company_name_data.xlsx](https://github.com/NRGI/resourcecontracts.org/files/160940/company_name_data.xlsx)

Regarding you question yes they are treated differently and recorded as two different companies.

**Comment by anderspeders** [comment]
Thanks @manishgs, We'll have a look

**Comment by anjesh** [comment]
@anderspeders @charlesyoung Could you please have a look and advise on the next step?

**Comment by manishgs** [comment]
@anderspeders @charlesyoung  any updates?

**Comment by charlesyoung** [comment]
@manishgs I will get back to you ASAP.

**Comment by manishgs** [comment]
@charlesyoung any updates???

**Comment by charlesyoung** [comment]
@manishgs I will report back by the end of the week.

**Comment by charlesyoung** [comment]
@manishgs take a look at the updated Google sheet. 

https://docs.google.com/spreadsheets/d/1lw9Ep_D9SmSzQgbTUXUtb08bkO0dYRcuEWssPRe10qs/edit#gid=901945309

**Comment by hello-deepak** [comment]
@charlesyoung 
[Earlier](https://docs.google.com/spreadsheets/d/1lw9Ep_D9SmSzQgbTUXUtb08bkO0dYRcuEWssPRe10qs/edit#gid=901945309) document of company has been harmonized .

Here is the doc file of newly extracted company name. https://docs.google.com/spreadsheets/d/1lw9Ep_D9SmSzQgbTUXUtb08bkO0dYRcuEWssPRe10qs/edit#gid=1890862116 .

Please review and update the duplicate company name.

**Comment by charlesyoung** [comment]
Thanks @hello-deepak. 

Just checking however that you are saying that the duplicate company names have been updated because I still see the duplicates.

**Comment by manishgs** [comment]
@charlesyoung 

We did the harmonization using previous [company name mapping](https://docs.google.com/spreadsheets/d/1lw9Ep_D9SmSzQgbTUXUtb08bkO0dYRcuEWssPRe10qs/edit#gid=901945309) but there are still some duplicates name due to latest changes in contract metadata. So please go through the new list and update the mapping column.

**Comment by charlesyoung** [comment]
@manishgs I don't see the updates reflected. 

![image](https://cloud.githubusercontent.com/assets/13888372/17471407/2d0ee104-5d44-11e6-9dbd-7ecd860bed80.png)

![image](https://cloud.githubusercontent.com/assets/13888372/17471385/0f6d077a-5d44-11e6-86ac-8d0136d2563e.png)

**Comment by manishgs** [comment]
@charlesyoung 

Comapany name "A&T Petroleum Company Ltd." was not there when we had generated the contract name list.  List was generated on [Mar 7](https://github.com/NRGI/resourcecontracts.org/issues/798#issuecomment-193145099)  So there are still more duplicate company names. We did the harmonization based on [sheet 1](https://docs.google.com/spreadsheets/d/1lw9Ep_D9SmSzQgbTUXUtb08bkO0dYRcuEWssPRe10qs/edit#gid=901945309) list. 

Now we have regenerated company name list ([sheet 2](https://docs.google.com/spreadsheets/d/1lw9Ep_D9SmSzQgbTUXUtb08bkO0dYRcuEWssPRe10qs/edit#gid=1890862116)) again after harmonization so please go through the list and update the mapping column where necessary. We'll do the harmonization again.

**Comment by manishgs** [comment]
Harmonization of contract name has already been completed. If you found any issues please reopen.
