### ISSUE TITLE
Requests for additional document types

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#799]
EITI Philippines have asked that the following document types are added. These would all be associated documents: 

MRFC – Mine Rehabilitation Fund Committee
MMT – Multi Partite Fund Committee
EIS – Environmental Impact Statement
SDMP – Social Development and Management Plan
EPEP – Environmental Protection and Enhancement Program
MRDP – Mining Rehabilitation and Decommissioning Plan
ISHES – Integrated Safety, Health, Environmental and Social Plan

For some we could group them under excisting - for others we might need to request additional sections.

**Comment by charlesyoung** [comment]
@anderspeders is this still required?

**Comment by KaitlinCCSI** [comment]
This might be example of something to be discussed by tech group since it
could have implications for global sites?
