### ISSUE TITLE
Front end annotation setup

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#8]
Initial work on using annotator.js for annotation workflow. Focus should primarily be on grouping sections of text into contract areas

**Comment by anjesh** [comment]
The annotation module saves the position of the text where the annotation is made. It means that the text has to be finalized before annotation, as any editing done to the contract text might reposition the annotation. Thoughts?

**Comment by anjesh** [comment]
When the text is edited, the annotation get shifted. We managed to get them re-saved when the text gets added. However shifting of the annotation position (e.g. when returns are entered), it's giving some issue. Still need to hack into details.

**Comment by anjesh** [comment]
Annotation setup and working.
