### ISSUE TITLE
Word in dropdown menu cut off again (on advanced search page)

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#800]
![screen shot 2016-03-06 at 7 53 59 am](https://cloud.githubusercontent.com/assets/14825437/13554566/bda52ee2-e370-11e5-9e45-3ddc216dbbb6.png)

**Comment by upasna01** [comment]
The issue is fixed. Please find the snapshot here.
![cuoff](https://cloud.githubusercontent.com/assets/11477899/13776535/be8f35b4-ead2-11e5-8506-61344f21ba41.png)
