### ISSUE TITLE
Annotation box cut off when arriving through advanced search page

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#801]
When clicking into a contract through an annotation search on the advanced search page, the annotation box is cut off; should be fixed. When clicking in the annotations column on the left of the contract view page, the annotation box is not cut off. 

For example, when clicking on the page number where annotation is found to arrive at that annotation in the contract view page:
![screen shot 2016-03-06 at 9 44 35 am](https://cloud.githubusercontent.com/assets/14825437/13555236/a85b2a22-e380-11e5-9ad5-1d5e988efe32.png)

The annotation box is cut off:
![screen shot 2016-03-06 at 9 42 54 am](https://cloud.githubusercontent.com/assets/14825437/13555232/952276ea-e380-11e5-94fd-a1f839553695.png)

But if I am looking at the same contract and then click on that annotation, the annotation box is not cut off:
![screen shot 2016-03-06 at 9 44 23 am](https://cloud.githubusercontent.com/assets/14825437/13555235/a3615d5c-e380-11e5-9c5c-cc89af051b18.png)

**Comment by manishgs** [comment]
This issue has been fixed.
