### ISSUE TITLE
Technical documentation on how OCIDs are assigned

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#802]
Currently we have - as I understand it - the following process in place. 

1) A main contract is assigned an OCID which will cover the full instance of the main contract and associated documents

2) Associated documents are assigned a sub-OCID which will identify the specific document as a part of the "contract group" belonging to the main contract. 

We need this process documented in the wiki. 

Below is a related questions  from @SamCCSI which **may** already be covered under our current process. If not we need to implement the required updates: 
"We need clarity, and possibly rules, on what will happen with OCID if a contract is changed from Main Document to Associated Document or vice-versa. Anjesh has suggested that a new OCID would be generated in this case, but not sure if this would fit within OCDS guidelines. Two examples of situations in which this could occur:
We add an MOU as a main (or unassociated) contract. We later find and add the main investor-state contract related to the MOU. The MOU might then be categorized as a “Associated Document” of the main contract.

- We add an investor-state contract. We later add a renegotiated version of the contract. The first investor-state contract might then be considered a “Associated Document” of the latter contract.

CC @jpmckinney

**Comment by jpmckinney** [comment]
To clarify, an OCID identifies a contracting **process**, not an individual contract. A process can have multiple contracts and multiple documents.

Once you relate a contract or document to a process (thus relating it to that process' OCID), there's no reason to ever change that OCID, unless you made a mistake and there was, in fact, no relation between that contract and that process (e.g. the contract actually belongs to a different process).

**Comment by anderspeders** [comment]
My impression was that the OCID process setup for RC did accommodate this scenario. 

@anjesh: Could you please verify and ensure that this is clearly documented in the wiki?

**Comment by upasna01** [comment]
Here is the technical documentation on how OCID are assigned, please ensure this is understandable.
https://github.com/NRGI/resourcecontracts.org/wiki/Open-Contracting-Identifier
