### ISSUE TITLE
Suggestion: Add country drop down to front page

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#803]
We discussed the front page search on the last call. 

One way to give the front page a more user friendly entry point for search could be to add a **country** drop down to the search. See below how OpenCorporates offers a country dropdown as part of the front page search. 

![image](https://cloud.githubusercontent.com/assets/1101585/13569923/09c179e8-e439-11e5-8d11-cc6b0f561a88.png)

@SamCCSI @KaitlinCCSI @jedm: Let me know what you think?

**Comment by anjhero** [comment]
This will be addressed along with in this issue #873.
