### ISSUE TITLE
Update API v.2 documentation

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#804]
As far as I understand the API documentation has not been updated to reflect the latest changes. 

Could we please proceed with this: https://github.com/NRGI/resourcecontracts.org/wiki/API

I suggest that this ticket also should deal with the need for keeping documentation for the old (still maintained API) v.1.

**Comment by sadhakbj** [comment]
The API Documentation has been updated. Please view it [here.](https://github.com/NRGI/resourcecontracts.org/wiki/API)

**Comment by anderspeders** [comment]
Did this need update as well: https://github.com/NRGI/resourcecontracts.org/wiki/contracts

**Comment by sadhakbj** [comment]
@anderspeders  https://github.com/NRGI/resourcecontracts.org/wiki/contracts page has been updated as well.
