### ISSUE TITLE
Adding anchor links 

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#806]
We've been trying to create a table of contents on the FAQ page, and to use anchor links to link each question in the ToC to the answer lower down on the page. 

The anchor links don't seem to be working (nothing happens when I click on test link). 

What is the best way to add these?

**Comment by JesseCCSI** [comment]
Just checking if there is a quick fix for this? We'd like to make changes to the FAQ page before the World Bank conference next week. Thanks. 

cc @KaitlinCCSI

**Comment by manishgs** [comment]
I've created sample html file for this. Please change the file extension to html and open in browser.
[faq.txt](https://github.com/NRGI/resourcecontracts.org/files/173232/faq.txt)

Create Faq menu links
```
<a href="#q1">Faq Question 1</a>
<a href="#q2">Faq Question 2</a>
```


Faq Text
```
<h1 id="q1">Faq Question 1</h1>
<p>Text</p>

<h1 id="q2">Faq Question 2</h1>
<p>Text</p>
```

Let me know if you have any confusion.

**Comment by JesseCCSI** [comment]
Thanks @manishgs -- I'll try this out next week and confirm that it works before we close the ticket.

**Comment by manishgs** [comment]
Closing this issue. Please open again if you encounter any issue.
