### ISSUE TITLE
Source URLs and "Other" Disclosure Mode not showing on front end

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#807]
We've added source URLs on the back end to most of the contracts for OLC, but they are not showing up on the front end. 

See e.g. 

http://www.openlandcontracts.org/contract/ocds-591adf-LR8579251623OL // http://resourcecontracts.elasticbeanstalk.com/contract/1382/edit

http://www.openlandcontracts.org/contract/ocds-591adf-ET4854285702OL // http://resourcecontracts.elasticbeanstalk.com/contract/1027/edit

cc @KaitlinCCSI

**Comment by JesseCCSI** [comment]
Following up on previous comment, when we select "Other" for "Disclosure Mode", this does not save and does not appear on the front end.

**Comment by KaitlinCCSI** [comment]
@anderspeders @anjesh can we prioritize fixing these two issues this week? Presumably won't take long, and would like to get this fixed before WB land conf starting next week. Thanks.

**Comment by anderspeders** [comment]
@KaitlinCCSI: Flagged now as priority!

**Comment by JesseCCSI** [comment]
Just checking in on the status of this? Looks like the Source URLs and Disclosure Mode when "Other" is selected are still not appearing on the front end.

**Comment by upasna01** [comment]
The Source URLs issue is fixed but not yet deployed.
In case of Disclosure mode, after selecting 'Other', one should fill the text-box. here is the snap-shot for it.
![disclosure-mode](https://cloud.githubusercontent.com/assets/11477899/13699917/a5394a12-e7a5-11e5-823e-54b7600828ff.png)

**Comment by JesseCCSI** [comment]
Thanks @upasna01 -- Will the Source URLs fix be deployed by Monday?

In the case of Disclosure Mode, does this mean that the free text box becomes a mandatory field when we select "Other"? It's not marked as mandatory 

cc @KaitlinCCSI @SamCCSI

**Comment by upasna01** [comment]
Thank you for the correction. 'Other' is marked mandatory now and will be deployed soon. Source URLs have been fixed.

**Comment by upasna01** [comment]
The issue have been fixed. Please change the review.
