### ISSUE TITLE
Homepage > "View all resources"

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#808]
See screenshot below -- this should be changed to match the left hand box ("View All Countries") 

![view all resources](https://cloud.githubusercontent.com/assets/14910764/13584784/128b4c1e-e486-11e5-9b1f-e185e4e1b0ce.png)

**Comment by anderspeders** [comment]
@anjhero Please include this while you upgrade the front page.

**Comment by anjesh** [comment]
Will be addressed in https://github.com/NRGI/resourcecontracts.org/issues/873
