### ISSUE TITLE
Contract Type list

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#811]
The Contract Type list includes 'Investment Promotion Agreement' (10) and 'Investment Promotion Agreements' (144). There is only an option for 'Investment Promotion Agreement' from the backend so should we change all 'Investment Promotion Agreements' to 'Investment Promotion Agreement'? 

![image](https://cloud.githubusercontent.com/assets/13888372/13629788/0fba6402-e5e4-11e5-8fd9-f5f2407a8b0e.png)

**Comment by hello-deepak** [comment]
Fixed.
![resourcecontracts org search contracts](https://cloud.githubusercontent.com/assets/7577697/14105032/c3fc1ade-f5c8-11e5-8a8f-446028332274.png)
