### ISSUE TITLE
Duplicate Annotations Category in drop-down list

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#812]
The 'Annotations Category' list seems to display duplicates i.e. Bonuses and Bonuses // Primes. 

![image](https://cloud.githubusercontent.com/assets/13888372/13629981/536e2fc0-e5e5-11e5-848d-3b356521b4f6.png)

**Comment by hello-deepak** [comment]
We have found these annotations category which is not available in our list in following contracts.

Audit
http://admin.resourcecontracts.org/contract/176
http://admin.resourcecontracts.org/contract/175
http://admin.resourcecontracts.org/contract/18
http://admin.resourcecontracts.org/contract/1185
http://admin.resourcecontracts.org/contract/173

General Information
http://admin.resourcecontracts.org/contract/18

Please replace the category with correct one and publish it.

**Comment by SamCCSI** [comment]
Done.

On Mon, Mar 28, 2016 at 7:47 AM, Deepak <notifications@github.com> wrote:

> We have found these annotations category which is not available in our
> list in following contracts.
>
> Audit
> http://admin.resourcecontracts.org/contract/176
> http://admin.resourcecontracts.org/contract/175
> http://admin.resourcecontracts.org/contract/18
> http://admin.resourcecontracts.org/contract/1185
> http://admin.resourcecontracts.org/contract/173
>
> General Information
> http://admin.resourcecontracts.org/contract/18
>
> Please replace the category with correct one and publish it.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/812#issuecomment-202352417>
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School | The Earth Institute, Columbia University
435 W116th St. New York, NY 10027
| (+1)(212) 854-2635 <+1212-854-2635> | (+1)(646) 630-4123 <+1646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by upasna01** [comment]
The issue seems to be resolved. I think this can be closed now.
