### ISSUE TITLE
Full list of organizationl entities - for review and harmonization

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#813]
@anjesh @manish: Can you please pull a full organizational entities in xlsx format?

We will then conduct a review and return a formatted version.

**Comment by manishgs** [comment]
Here is the link of google spreadsheet
https://docs.google.com/spreadsheets/d/15k-7NCkgu1p2eKgWGZnykASLQoa4gR6fOLskV8mdOhY/edit?ts=566690b1#gid=1708686393
