### ISSUE TITLE
French accents appearing as symbols on OLC frontend

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#814]
If possible can this be fixed quickly? We plan to present on this next week at a conference.

![image](https://cloud.githubusercontent.com/assets/12913915/13647930/52c0c848-e604-11e5-89a5-4fcbb304e457.png)

**Comment by SamCCSI** [comment]
The system lists the accent properly in some nodes (see yellow circle), but not in others (red circles):

![image](https://cloud.githubusercontent.com/assets/12913915/13647980/90f645a2-e604-11e5-9f8d-bd1ece68a31e.png)

**Comment by anderspeders** [comment]
@anjesh: The display of "Ivory Coast" appear to be "Côte d'Ivoire", so I think this is an error in the country code list. 

Please change this so that "Ivory Coast" is the default value projected on front end for both **Country** and **Jurisdiction of incorporation**

**Comment by SamCCSI** [comment]
Thanks @anderspeders 

This accent problem will likely appear again when we initiate a French version of the site, so it might be worth resolving the accent problem with those fields, as well as changing the entry to appear as "Ivory Coast"?

**Comment by upasna01** [comment]
The issue have been fixed. Here is the snapshot for it.
![search](https://cloud.githubusercontent.com/assets/11477899/13773490/8ac302da-eac1-11e5-869e-693eef3f6eed.png)
