### ISSUE TITLE
Request for standard sized annotation box

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#815]
There will be instances where we plan to circle a term that is the source of an annotation.

However, where the annotation source text spans several lines, we will place a small boz to the left. These boxes need to be standardized for uniformity / presentation. Currently, it is very hard to get them looking identical (below is my best attempt). Can we build in a feature for this (in addition to having the ability to set our own size for other boxes)? 

![image](https://cloud.githubusercontent.com/assets/12913915/13648095/0eb75472-e605-11e5-888b-dd316103574c.png)

**Comment by charlesyoung** [comment]
@SamCCSI just a follow up on above question relating to the placement of annotation boxes not covering the text. NMA from Sierra Leone also asked the question.

**Comment by SamCCSI** [comment]
@charlesyoung I will send you our proposal for using annotation markers, previously sent to @anderspeders to give you a better sense of how we plan to proceed. Best to continue the discussion via email. Thanks!

**Comment by SamCCSI** [comment]
Just following up on this request. See screenshot for how we are manually doing this — it looks ok, but is time consuming and will never be uniform.
Thanks.

![image](https://cloud.githubusercontent.com/assets/12913915/15339972/13c5d322-1c55-11e6-923e-a160744333c5.png)

**Comment by manishgs** [comment]
We have implemented drag and resize feature for annotation box.

Do you think we still need this feature? @SamCCSI  @anderspeders

**Comment by SamCCSI** [comment]
Thanks @manishgs

Given the number of different annotators that the system will have, it is still important to have a standard size annotation box.

**Comment by anderspeders** [comment]
Thanks, @SamCCSI Could you clarify where on the CCSI priority list this feature?  

@manishgs Could you please cost this out with a day estimate.

**Comment by anderspeders** [comment]
@manishgs Could you please scope what the time costs would be required for offering a fixed shape annotation box *while* still allowing users to utilize the current flexible annotation shape? 

@SamCCSI please clarify if this lack accuracy?

**Comment by SamCCSI** [comment]
Thanks, that's right. We hope to have the _option_ of a standard sized box but also will need to set our own size some times.
![screen shot 2016-05-26 at 4 55 14 pm](https://cloud.githubusercontent.com/assets/12913915/15589885/c5a7a9e4-2362-11e6-95a1-29fb5c386d3a.png)

**Comment by manishgs** [comment]
Icon added to resize the annotation box to standard size (50X50px)

![screenshot-admin resourcecontracts org 2016-06-06 18-49-29](https://cloud.githubusercontent.com/assets/3942999/15822779/93f6d682-2c17-11e6-881d-63186f2871ea.png)

After clicking standard size icon need to click save button to save on database
![screenshot-admin resourcecontracts org 2016-06-06 18-51-05](https://cloud.githubusercontent.com/assets/3942999/15822909/1bccf6ae-2c18-11e6-9bab-0c975e047288.png)

**Comment by SamCCSI** [comment]
Thanks @manishgs 

I just tried annotating but couldn't see this?

**Comment by manishgs** [comment]
You can see the option buttons when you resize or drag the yellow box.

**Comment by SamCCSI** [comment]
It's not showing. see screenshot:
![image](https://cloud.githubusercontent.com/assets/12913915/15825505/07ea7c60-2bd2-11e6-97e5-f090d443a52b.png)
![image](https://cloud.githubusercontent.com/assets/12913915/15825527/1d719564-2bd2-11e6-8489-bb6eb03e2ed7.png)

**Comment by manishgs** [comment]
We are not clear how to implement fixed size box on creating an annotation so for now It will show the option when you update (drag/resize) the existing annotations.

**Comment by SamCCSI** [comment]
Thanks.

Can you please change the size to 40 pixels wide by 25 pixels high?

**Comment by manishgs** [comment]
box size updated.
@SamCCSI  Please review once.

**Comment by SamCCSI** [comment]
This is exactly what we were hoping for. Many thanks @manishgs !

**Comment by SamCCSI** [comment]
Apologies — will leave this open until we also have the ability to use standard sized box for new annotations (currently we only have this functionality when updating past annotation markers).

**Comment by manishgs** [comment]
@SamCCSI 

Standard sized box option also added while creating an annotation.

![screenshot-admin resourcecontracts org 2016-06-08 18-15-44](https://cloud.githubusercontent.com/assets/3942999/15894354/38861d6e-2da5-11e6-905d-4e89189e02f5.png)

**Comment by manishgs** [comment]
We have button placed on popup to resize the annotation box so closing this issue. Please create new issue if you have any issue regarding standard annotation box.
