### ISSUE TITLE
Eng vs French spellings of countries

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#816]
1. Right now, Côte d'Ivoire (rather than the Eng version 'Ivory Coast') appears in the main list of countries, which all seem to be in English. It is preferable for the English version to appear alongside all other English terms of countries, and for it to automatically switch to the French term if/when we have a French version of the site.

2. When sorting alphabetically by country, the system seems to sort it as 'Ivory Coast' (i.e. starting with 'I' not with 'C'), making it appear after Ethiopia and before Liberia, even though it is still presented as 'Côte d'Ivoire'. This is inconsistent and confusing. Screenshot:
![image](https://cloud.githubusercontent.com/assets/12913915/13648549/344cd84a-e607-11e5-8d13-7b3065fc8845.png)

**Comment by upasna01** [comment]
The issue have been fixed.Here is the snapshot for it.
![search](https://cloud.githubusercontent.com/assets/11477899/13773392/1a6ac900-eac1-11e5-8f19-daa40ddf0c58.png)
