### ISSUE TITLE
Add resource type "Not specified" to metadata

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#817]
Occasionally a contract grants an investor a concession over land but does not specify the resource.

Eg. This contract allows the company to use the land for its "corporate purpose." http://www.openlandcontracts.org/contract/ocds-591adf-CI6564507137OL/view

Yet resource is a required metadata field. It would therefore be useful to have as a resource type "Not specified," so that such contracts can be accurately tagged.

**Comment by manishgs** [comment]
We can make resource type optional instead of adding new resource type "Not specified". If resource is left empty then we can show text "Not specified"  in resource.

Let me know what do you think ? @SamCCSI  @anderspeders

**Comment by manishgs** [comment]
@SamCCSI @anderspeders Please let us know what we need to do her

**Comment by SamCCSI** [comment]
I think having a resource field of "not specified" that you have to select is more precise than making the field non-mandatory. We need to ensure that uploaders make their best effort to label the resource properly.  @anderspeders / @KaitlinCCSI any thoughts?

**Comment by KaitlinCCSI** [comment]
Agree with Sam and am fine with "Not specified"

On Tue, Jun 7, 2016 at 7:06 AM, SamCCSI <notifications@github.com> wrote:

> I think having a resource field of "not specified" that you have to select
> is more precise than making the field non-mandatory. We need to ensure that
> uploaders make their best effort to label the resource properly.
> @anderspeders <https://github.com/anderspeders> / @KaitlinCCSI
> <https://github.com/KaitlinCCSI> any thoughts?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/817#issuecomment-224260384>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AOI33bfOyRL960D5JZlNz5iFF-rlyUAMks5qJV6ugaJpZM4HtIMv>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01R3M5AeV&m=ad130182788f&t=20160607&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01R3M5AeV&m=ad130182788f&t=20160607&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01R3M5AeV&m=ad130182788f&t=20160607&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land, Agriculture, and Human Rights**Columbia Center on Sustainable
Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by upasna01** [comment]
The issue is fixed, please do verify.

![871](https://cloud.githubusercontent.com/assets/11477899/16481136/558044f0-3ec9-11e6-82d7-cc22daf57e00.png)

**Comment by SamCCSI** [comment]
Looks good, thanks.
