### ISSUE TITLE
Clarify if login feature will be required for clipping feature?

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#819]

**Comment by jedm** [comment]
Also noted in #70 and #116. Alternative to required login would be limiting duration of saving Clips to only session length.

**Comment by anderspeders** [comment]
A) Can you clarify if the clipping feature will require login and why?

B) Which part of the feature could be delivered *without* requiring login?

@anjesh @manishgs

**Comment by manishgs** [comment]
For clipping an annotation, print, downloading and viewing each clipped annotation does not required login so these can be delivered without user login.

For sharing annotation to other user requires user login because we need to store annotation in database and generate unique link for remembering the clipped annotations.

**Comment by jedm** [comment]
@manishgs Is it possible to store "each clipped annotation" and the list of user's clipped annotations for a limited time using a session cookie? 

Also, can you please explain about "sharing to other users?" I do not think we have requested this. We have requested sharing by email or social tools just the same as sharing search results or an individual page.

**Comment by manishgs** [comment]
> Is it possible to store "each clipped annotation" and the list of user's clipped annotations for a limited time using a session cookie?

We are using browser local storage for storing clipped annotation. Session/cookie data will be lost when user close the browser but local storage won't be deleted unless user himself delete them.

"Sharing to other users" means the same as you explained, sharing clipped annotation via email and sharing url on social media.

**Comment by jedm** [comment]
@manishgs Does "browser local storage" require a user account? If the storage is local on user's browser, then a session cookie can be used instead, yes? 

Also is it possible to have the session depend on time limit not on open/close browser?

(Please note these are two separate questions. If answer to second question is No, it still may be better to "transfer the risk" of losing work to the user, instead of requiring login.)

**Comment by manishgs** [comment]
> Does "browser local storage" require a user account? If the storage is local on user's browser, then a session cookie can be used instead, yes?

Local storage doesn't required user account.  Session data  is stored on server side whereas cookie data is stored on the users computer.  PHP session variables last until the user closes the browser. 
We can set expiry time on cookie but it only stored limited data so Local storage is better option to store data beside server database.

> Also is it possible to have the session depend on time limit not on open/close browser?
Session is stored on server side so can't set time limit for the session. We can set time limit for cookie but local storage is better option.

**Comment by anderspeders** [comment]
hi @manishgs, 

Could you clarify if it is entirely impossible to enable sharing of clipped annotations without saving it as a user?

**Comment by manishgs** [comment]
There could be two options to share clipped annotation without user module.

**Authenticate by unique key **
User's clippings can be authenticate by unique key. Unique key will be generated when user save clips. Anyone can access clips with the key.

**How it works :**
1. The clips will be stored in the local storage until saved manually. If User want to share clips, they need to save clippings.
2. When user click on share button if clips are not saved yet then user prompt popup with save button. An Unique key (ie. 90c91026fc ) will be generated after saving clips.  The key will be emailed to user for later use
3. Clippings will be stored in json file and they will be stored on AWS s3 cloud.
4. When user share clips, system will send email to the user with the link of the saved clips like http://rc.org/clips/90c91026fc.
5. Unique key can be use later to import clips. 
6. After sharing clipping if user make any changes on clippings, it will not be update on shared link as they are not save yet. So user need to save every time after updating clippings.


Use of email address only

If we are not using user authentication then we can use file based system to store clippings.

**Comment by manishgs** [comment]
There could be two options to share clipped annotation without user module.

#####  1. Authenticate by unique key

User's clips can be authenticate by unique key. Unique key will be generated when user save clips. Anyone can access clips with the key.

**How it works :**

1. Clips will be stored in the local storage at first. If User want to share clips, they need to save clips.
2. When user clicks on share button if clips are not saved yet then user prompt popup with save button An Unique key (ie. 90c91026fc ) will be generated after saving clips.  The key will be emailed to user for later use.
3. Clips will be stored in json file and they will be stored on AWS s3 cloud. System'll auto remove files if they are no longer used for 30 days.
4. When user share clips, system will send email to the user with the link (http://rc.org/clips/90c91026fc.) of the saved clips.
5. Unique key can be use later to import clips. 
6. After sharing clips, if user makes any change on clips, it will not be updated on shared link as they are not save yet. So user need to save every time after updating clips.



##### 2. Use of email address only

There won't be concept of users, but the user will be able to save the clips, share the clips, retrieve the clips using his email address. The clips will be stored in the local storage until saved manually. When the user saves the clips, the system will prompt for the email address. Saving the clips will store those clips in the server against the email address as follows. 

email | clip_id | clip_data
------|-------| ---------
test@gmail.com | a7b3ff0a90c91026fc871ff2b013224b | { annotation_id:514, annotation_id: 314}
new@gmail.com | a68a1f4704f9a498e8525156ad7e849a |{ annotation_id:891, annotation_id: 514, annotation_id: 71}

Then the system will send email to the user with the link of the saved clips like http://rc.org/clips/a7b3ff0a90c91026fc871ff2b013224b. Clicking on the link will retreive all the saved clips in the local storage.

**Comment by anderspeders** [comment]
Thanks @jedm for flagging the need for clarificaiton here today in chat, 

I have now had a review with @byndcivilization - and option 1) appear to live up fully to the key requirement of the group that there should be *no login required* and that it should be easy to share. Only thing to clarify once in use is for how long we should store the clip URL links (this will depend on the use of the feature). 

Keen to hear any thoughts here @KaitlinCCSI @SamCCSI  @jedm

**Comment by jedm** [comment]
I cannot comment until we have clarification from YI, since there are some contradictions here. If user can generate Clips, view, refine, download and share them without needing a key or an email from the site, then that is the right direction. @byndcivilization do you know?

**Comment by SamCCSI** [comment]
Hi all,

Is it possible to delete point 3 from the first option? Or change 30 days to a much longer time period (eg 6 months)? 

Also, what's the difference between having a login system (user and password) and a key system (which requires an email address and a unique key code) in practice? Do the same privacy / security concerns for users present themselves? On the plus side, might a key-based system be administratively easier than a user/password set up?

cc @KaitlinCCSI

**Comment by manishgs** [comment]
> Is it possible to delete point 3 from the first option? Or change 30 days to a much longer time period (eg 6 months)?
@anderspeders

**Comment by anderspeders** [comment]
A few notes from a skype text chat this week with @manishgs; 

@jedm: To clarify there will *not* be requirements for login. The clipping can be shared in two ways - either a) as a URL (saved for 1 year), b) print, c) download or e) it can be send to an email address. 

@SamCCSI: Clips can be stored for 1 year - instead of 30 days.

**Comment by SamCCSI** [comment]
Thanks.



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School | The Earth Institute, Columbia University
435 W116th St. New York, NY 10027
| (+1)(212) 854-2635 <+1212-854-2635> | (+1)(646) 630-4123 <+1646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

*New Report: Land Deal Dilemmas: Grievances, Human Rights, and Investor
Protections
<http://ccsi.columbia.edu/2016/03/10/land-deal-dilemmas-grievances-human-rights-and-investor-protections/>*
Available at: *http://goo.gl/qctX9I <http://goo.gl/qctX9I>*

**Comment by jedm** [comment]
Anders welcome back!

I'm still waiting on the fuller write up on Clippings that you were scheduled to get from YI per our last few chats. Without that, it's not really possible to assess where this feature is at. 

Thanks much and talk to you soon.

Jed

**Comment by hello-deepak** [comment]
Please use #893 issue for any further discussion.
