### ISSUE TITLE
Missing data fields under company from API

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#821]
The company data in te API is missing as far as I can tell: 

 company: {
        name: String,
        address: String,
        founding_date: String,
        corporate_grouping: String,
        opencorporates_url: String,
        identifier: {
          id: String,
          creator: {
            name: String,
            spatial: String

A number of fields are missing from the API: 
[Jurisdiction of Incorporation]: string
[Participation share] <-- this seems to be outside the company object
[Registration Agency]
[Incorporation Date]
[Company Number]

cc @giorgiacek

**Comment by hello-deepak** [comment]
We have changed the company data API accordingly as suggested by @jpmckinney . https://github.com/NRGI/resourcecontracts.org/issues/737

**Comment by jpmckinney** [comment]
* Founding date is incorporation date
* Identifier is number
* Registration agency is the creator of the identifier
* Participation share is not a fact about a company, but about their participation in a project

**Comment by anderspeders** [comment]
@hello-deepak Could please confirm this by updating the API documentation?

**Comment by anderspeders** [comment]
I am missing the field [Jurisdiction of incorporation] in the API.

**Comment by anderspeders** [comment]
Participation share is a statement about the relationship between the entities company and contract, not an attribute of the company.

**Comment by jpmckinney** [comment]
> 

Participation share is a statement about the relationship between the entities company and contract, not an attribute of the company.

The share is not a property of the company in the API.

**Comment by jpmckinney** [comment]
>  I am missing the field [Jurisdiction of incorporation] in the API.

This should be the `name` of the `creator` of the company's `identifier` (i.e. the name of the company register).

**Comment by hello-deepak** [comment]
Here is mapping of form in admin site and api data .

```
{  
   company:{  
      name => Company Name
      address => Company Address,
      founding_date => Incorporation Date,
      corporate_grouping => Corporate Grouping,
      opencorporates_url => OpenCorporates Link,
      identifier:{  
         id => Company Number,
         creator:{  
            name => Registration Agency,
            spatial => Jurisdiction of Incorporation
         }
      }
   },
   is_operator => Operator
   share => Participation Share
}
```

**Comment by manishgs** [comment]
Company data are all present on API so closing this issue.
