### ISSUE TITLE
Document type - missing from API

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#822]
http://rc-api-stage.elasticbeanstalk.com/api/contract/ocds-591adf-NG0817821030RC/metadata

**Comment by hello-deepak** [comment]
Document type has renamed to "type".
 ![rc api stage elasticbeanstalk com api contract ocds 591adf ng0817821030rc metadata](https://cloud.githubusercontent.com/assets/7577697/13735986/2d8d67e8-e9d8-11e5-9e72-8100d19b9ebb.png)

As discussed in this issue https://github.com/NRGI/resourcecontracts.org/issues/734 .
