### ISSUE TITLE
Text search (of annotations) does not include annotation titles / fuzzy searching needs improvement

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#823]
A problem identified by @JesseCCSI. Open this contract: http://www.openlandcontracts.org/contract/ocds-591adf-SL9115158300OL/view#/pdf/page/12/annotation/24904

I want to find the expropriation clause, so I text search "expropriation".

The OCR text hasn't been returned from MT yet, so the text search applies to the annotations only.

No results are returned. This is because the annotation itself contains the word "expropriate" but not "expropriation". The annotation title includes "expropriation" but it is not picked up.

Proposed solutions:
1. Text search (of annotations) should include the text of annotation _titles_ as well.
2. Fuzzy searching should pick up that "expropriate" and "expropriation" are related terms, and return results that include both of those words.

**Comment by jedm** [comment]
This was an issue on original site search too - a limitation of how many sources could be searched (text, metadata, annotation text, annotation title). Do we have a similar limitation here?

**Comment by SamCCSI** [comment]
Fuzzy searching also needs to pick up misspellings as search terms. For example: slight misspelling - “stablization” - produces zero results.

**Comment by hello-deepak** [comment]
We will continue in https://github.com/NRGI/resourcecontracts.org/issues/932 issue for further discussion.
