### ISSUE TITLE
In-text search results in contract view page missing "view more" option 

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#825]
When you run an in-text search in contract view mode, the search returns results in the format below -- no option is provided to view the full search result in the left hand column (e.g. there is no more/ less option that is included when viewing annotations). 

Can this option be added? 

![untitled](https://cloud.githubusercontent.com/assets/14910764/13711956/29457bd0-e78f-11e5-933a-9c2939993862.png)

Note also that, when you click on a search result for an annotation, sometimes this brings up the hovering annotation box, but other times it does not (seems buggy). Even where the hover box does appear, you still can't view the full annotation. 

cc @SamCCSI @KaitlinCCSI

**Comment by hello-deepak** [comment]
View more/less is added in annotation in text-search.
![resourcecontracts org rapu rapu minerals incorporated mpsa no 168 2001 v 2001](https://cloud.githubusercontent.com/assets/7577697/16558102/3d8b1892-4203-11e6-944d-3481ad80d964.png)

**Comment by JesseCCSI** [comment]
Thanks @hello-deepak this works well, though the "more/ less" buttons are not easily distinguishable from the rest of the text when you hover over the search result (please see screenshots below). 

Is it possible to distinguish the "more/ less" buttons, e.g. by making them bold? 

Perhaps @jedm has suggestions on how best to distinguish the buttons, while remaining consistent with the rest of the site? 

Thanks. 

![image](https://cloud.githubusercontent.com/assets/14910764/16596776/6b26ab52-42c3-11e6-8b7e-54e8c2c86103.png)

![image](https://cloud.githubusercontent.com/assets/14910764/16596785/70193d0a-42c3-11e6-8025-f8d52b47d0b3.png)

**Comment by SamCCSI** [comment]
Re-opening in line with Jesse's comment.

**Comment by hello-deepak** [comment]
@JesseCCSI 
Now more/less anchor is distinguishable from search result on hovering by making dark gray for the search result and site color for more/less anchor.

![openlandcontracts org drc industrie de transformation de bois contrat de concession forestiere n 005 4 aout 2011](https://cloud.githubusercontent.com/assets/7577697/16829796/80f3b756-49ba-11e6-90a2-7f60e670381e.png)

Please review . And do open this issue if you find any bug.

**Comment by JesseCCSI** [comment]
Great, thanks @hello-deepak this seems to work well -- will comment and re-open if anything else comes up.
