### ISSUE TITLE
RC admin user rights

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#826]
I want to clarify the RC admin user rights.

@anjesh am I correct in the following:
1. 'Admin' has rights to add all contracts as well as publish all contracts
2. 'Research Associate' has rights to add all contracts but not publish contracts
3. 'Country Admin' has rights to add contracts as well as publish contracts but only for a specific country
4. 'Country Researcher' has rights to add contracts but not publish contracts but only for a specific country

**Comment by charlesyoung** [comment]
@anjesh as discussed can you please remove the rights of the 'Country Researcher' to publish contracts. Can you also please change 'Country Researcher' to 'Country Uploader'.

**Comment by manishgs** [comment]
will address in this issue  https://github.com/NRGI/resourcecontracts.org/issues/844
