### ISSUE TITLE
Regional listing --> then alphabetic within regions

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#827]
For country lists on ResourceContracts (only): 

![image](https://cloud.githubusercontent.com/assets/1101585/13787448/61402ec4-eab2-11e5-8723-d6613bcfc660.png)

a) Suggested breakdown by continents: 
1) Africa
2) Asia
3) Europe
4) Latin America
5) North America
6) Oceania

b) Then alphabetically: 

@anjesh: Do you know a good ISO-defined continent group system?

This is based on feedback from ALSF.

**Comment by anderspeders** [comment]
To clarify this is for: http://www.resourcecontracts.org/countries

To recap I tink there might be two options: 
1) Provide by alphabetical (as now)
2) Provide by regional breakdown
3) Provide both alphabetic listing *and* regional listing 

Any thoughts: @KaitlinCCSI @jedm @samCCSI

**Comment by jedm** [comment]
@anderspeders I like the idea of having two options (like we do with viewing Annotations by page or by topic). If this does not add too much developer time, I would recommend this approach.

And if we go with that, suggest that the regions are listed with Expand/Collapse functions.

**Comment by charlesyoung** [comment]
@anderspeders is this still required?
