### ISSUE TITLE
Remove AMLA link from contract with resource="hydrocarbon", "oil", "gas"

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#828]
Current rule for linking to AMLA on RC.org:

If country= in Africa then link to AMLA

Change this to: 
If country = in Africa *and* resource *is not* "hydrocarbon", "oil", "gas" then link to AMLA

Request from ALSF/AMLA-team

**Comment by upasna01** [comment]
This issue is resolved. Please review it.
