### ISSUE TITLE
Admin: Error when opening contracts from the backend

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#829]
Cannot open below contracts from the backend. 

Carmen Copper Corporation - MPSA No. 264-2008-VII, 2008 
Philsaga Mining Corporation - MPSA No. 262-2008-XIII, 2008
SR Metals, Incorporated - MPSA No. 261-2008-XIII, 2008

![image](https://cloud.githubusercontent.com/assets/13888372/13804315/9155516e-eb54-11e5-867e-01c31ad799ae.png)

**Comment by charlesyoung** [comment]
More contracts flagged with the same issue. 

TVI Resource Development Philippines, Incorporated - MPSA No. 054-96-IX, 1996 
Cagdianao Mining Corporation - MPSA No. 078-97-XIII (Surigao Mineral Reservation), 1997
Rio Tuba Nickel Mining Corporation - MPSA No. 114-98-IV, 1998
Filminera Resources Corporation - MPSA No. 095-97-V, 1997 
Filminera Resources Corporation- MPSA No. 255-2007-V, 2007
Filminera Resources Corporation- MPSA No. 256-2007-V, 2007

@anjesh can you urgently look at this issue. PH-EITI is trying to check/publish the annotations of these contracts.

**Comment by sadhakbj** [comment]
It's fixed now.

**Comment by charlesyoung** [comment]
Thanks @sadhakbj 

It sounds like the issue was related to the deletion of the user who added those contracts. Have we built in checks to ensure that this won't happen again?

**Comment by manishgs** [comment]
Currently we are not checking anything before deleting a user. Now we need to check user activities before deleting them. If user who has added contract, commented .. etc can't be deleted they can be disabled and user who has not involved in any activities can to be deleted.

**Comment by charlesyoung** [comment]
OK thanks.
