### ISSUE TITLE
User story: Annotation process in low bandwith environments [requirements analysis]

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#83]
This user story has been prepared by @samCCSI. To be discussed for an upcoming sprint. 

• -       if we have annotators in low-bandwidth countries, there is a risk they will lose annotation work – eg if internet connection breaks
• -       is there a way to have an alternative spreadsheet process that works as well, so that users in, eg, East Timor, could use a spreadsheet with the exact same terms as the annotation form and then upload it that way? (I imagine this might be possible given that you will be moving all existing annotations to the new site?)
• -       if this is not possible, can you design the upload process so that it uses very little bandwidth, and saves very regularly (like google docs does – after each cell is entered) to avoid lost work if a connection breaks?

**Comment by charlesyoung** [comment]
@anderspeders @SamCCSI is this still required?

**Comment by SamCCSI** [comment]
Thanks @charlesyoung. Given upcoming country-specific site collaborations are taking place in environments with low bandwidth, this is still an important issue to resolve.

**Comment by charlesyoung** [comment]
Agreed.

**Comment by anjesh** [comment]
We need to work on the workflow/process for this case, as mentioned by Anders, spreadsheet seems to be a viable solution for this. Otherwise optimizing/fixing the current codebase for the annotation doesn't seem to work. 

Just quick thoughts, using spreadsheet means we will be sacrificing couple of annotation features like exact position of the annotation and need to replace that with position names like top, middle and bottom. And the rest can of the metadata could be part of the template. If this is one of the priorities, we need to spend/agree on the process soon.

**Comment by SamCCSI** [comment]
@anjesh no objections to using spreadsheet, if that is easiest.

For annotations created this way, a PDF marker (and a text marker) will need to be created, so that users in stronger internet environments still have PDF markers on every annotated contract. It is important to keep the consistency of always having PDF markers.

The top / middle / bottom will work for PDF. Will it work for text as well? Or will the annotator need to specify what text should be highlighted by the text annotation marker?

**Comment by charlesyoung** [comment]
**Note:** 
We will define the required process during S18 and get sign-off on the process and then complete the development next year. Clarity on the add/update process of the annotations, annotation CSV template, how these annotations are placed in the documents (use of position labels like top, middle, bottom).

**Comment by manishgs** [comment]
Following workflow explains creating new annotations only by importing CSV file. For updating annotations  user can use existing editing feature available on contract detail page which is easier process than updating through CSV files.

1. There will be **import button** on contract detail page.
2. There will be download button for **CSV template** beside the import button.
3. User have to fill CSV file in defined format (We'll add format and process on wiki after finalizing the workflow)
 
Below is the sample of CSV file for importing annotations

|Category | Text | Article Reference | Page no. | Top  position | Left position
|---|---|---|---|---|---|
|Name of company executing document| a compagnie franco-tunisienne des pétroles| Art .1 | 2| 10 | 20
| |  |  Art. 2 | 3| 60 | 12|
|Size of concession area| Etap (Entreprise Tunisienne d'Activités Pétrolières).| Preambule| 2| 13 | 60
|Location| le permis se trouve dans la gouvernorat du Kef.| Art. 7 | 2| 13 | 60
| |  |  Art. 4 | 1| 10 | 20|Annotation Category name | Annotation Text | Art.4 | 1| 30 | 10

User can define the annotation position '**Top**' and '**Left**' by using margin, where top left corner is considered origin(0,0) and **Top** is the margin from top and **Left** is the margin from left of the pdf to annotation marker.
**Top** and **Left** margin should be in Percentage value.

Note. Annotation can't not be updated or deleted using this process.

@SamCCSI @charlesyoung Let us know your thoughts.

**Comment by charlesyoung** [comment]
@SamCCSI @KaitlinCCSI will above suggested process work?

**Comment by SamCCSI** [comment]
Thanks @manishgs and @charlesyoung this looks promising.

The top position and left position fields might be a bit too finicky for users, as it will be hard for them to predict exact pixel references.

What about if we just had 4 different vertical positions (1,2,3 or 4) and 3 different horizontal positions (A, B or C):

![image](https://cloud.githubusercontent.com/assets/12913915/21787444/71e7c0e0-d71d-11e6-9f90-b3b2e64edff3.png)

And then user could say annotation marker should be located at A2 or C1, etc. for each:
E.g. of A2 placement:
![image](https://cloud.githubusercontent.com/assets/12913915/21787484/a32e3f30-d71d-11e6-87eb-2f80f97c3820.png)

E.g. of C1 placement:
![image](https://cloud.githubusercontent.com/assets/12913915/21787508/bf4320f0-d71d-11e6-9dc0-9007b9cb1ffb.png)

**Comment by charlesyoung** [comment]
@anjesh will above be feasible or should be discuss in more detail during the Sprint call on the 20/01?

**Comment by anjesh** [comment]
Lets discuss on this as well. I get the point Sam is trying to make here, but it would be good to hear if others also has any say. I am also wondering if it's possible to talk with one or two annotators/researchers about this process to get their perspective on the templates and especially the location points.

**Comment by charlesyoung** [comment]
Ticket not prioritized.
