### ISSUE TITLE
Enable multiple countries to be added to country field

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#830]
Please enable multiple countries to the <Country> field. Currently only one country can be added.

**Comment by manishgs** [comment]
If we allow multiple countries for a contract then following changes need to be considered.
1. update OCID
2. list government entities
3. ES index - metadata and master type
4. update all APIs
5. Subsite - search, detail, view page
6. create command to update current contract metadata

Questions:
1. How do we update OCID?
2. Can user allow to add as many countries as they want? or there will be limit?
3. How do we list government entities?

**Comment by manishgs** [comment]
We need answer of above questions to work on this issue.
@anderspeders

**Comment by anderspeders** [comment]
I will check with Perrine and @samCCSI regarding the use case, as this seems to be a complicated case to handle for a very limited amount of contracts.

**Comment by charlesyoung** [comment]
@anderspeders @SamCCSI is this still required?

**Comment by SamCCSI** [comment]
Currently only needed for some East Timor – Australia contracts. If it will unduly complicate things, I suggest discussing at next tech call.

**Comment by SamCCSI** [comment]
Update to previous comment – it involves other countries as well. We have arrived at the current solution of just uploading the document twice (once for each country) but note that this is not ideal.

**Comment by charlesyoung** [comment]
Labelled as needing discussion.

**Comment by charlesyoung** [comment]
Although this ticket will not to be included in S19 it is noted that CCSI hopes that it can be included in the future. 

cc @SamCCSI @KaitlinCCSI

**Comment by charlesyoung** [comment]
@SamCCSI is this still required?

**Comment by SamCCSI** [comment]
Not in the near term, but good to leave this ticket in the background in
case needed in the future.
