### ISSUE TITLE
Request for spreadsheet of all corporate groupings

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#833]
From one of our researchers: _Looking at the corporate grouping issue, is there anyway to get a spreadsheet similar to the one used for harmonizing company names but that also has a column for corporate grouping? That would at least allow for harmonizing corporate groupings which would cut down on the number of names, and also make it a lot easier to find and remove the smaller names. Especially because in at least some contracts, its not always clear where/on what basis the corporate grouping came from.  _

cc @anderspeders

**Comment by SamCCSI** [comment]
The researcher has also requested a similar list be generated for Government entities.

CC @anderspeders

**Comment by anderspeders** [comment]
@anjesh @manishgs Please do go ahead with this.

**Comment by SamCCSI** [comment]
The researcher is hoping to work on this over the weekend if possible. I know you have competing demands, but if this could be produced today that would be immensely helpful.

Many thanks!

**Comment by upasna01** [comment]
Here is the link for [Corporate Group] (https://docs.google.com/spreadsheets/d/15k-7NCkgu1p2eKgWGZnykASLQoa4gR6fOLskV8mdOhY/edit?ts=566690b1#gid=2013179925) and for the [Government entities](https://docs.google.com/spreadsheets/d/15k-7NCkgu1p2eKgWGZnykASLQoa4gR6fOLskV8mdOhY/edit?ts=566690b1#gid=1708686393) .
