### ISSUE TITLE
Validate before deleting a user in admin

### ISSUE THREAD

**Issue by manishgs** [NRGI/resourcecontracts.org#834]
In current system,  there is not extra checking for deleting a user. If deleted user was involved in contract activities (like add/update contract, publish, comment etc) then user data will be lost and may produce errors. So we should not allow admin to delete user unless user is not involved in contract activities. Those user can be disabled and user who has not involved in any activities can to be deleted.

@anderspeders

**Comment by upasna01** [comment]
Validation before deleting a user in admin have implemented
