### ISSUE TITLE
metadata inconsistencies when using ES aggregations and filters

### ISSUE THREAD

**Issue by giorgiacek** [NRGI/resourcecontracts.org#835]
I think there are some issues with missing metadata that cause me problems when using filters and aggregations with ES queries (within the "master" type). 
These are examples:
1. When aggregating based on  the field "language" I can retrieve only 922 contracts
2. When aggregating based on the field "signature_year" I get only 866 contracts

**Comment by giorgiacek** [comment]
Additionally, when aggregating by resource iron ore gets divided into "Iron" and "ore" so worth looking at the strings.

**Comment by hello-deepak** [comment]
For aggregating contract based on language : 

`{
   "size": 0,
   "aggregations": {
      "language_summary": {
         "terms": {
            "field": "metadata.language"
         }
      }
   }
}`

I found the correct data.
Similarly for "signature_year".

For aggregating resource you can use "resource_raw" of type metadata. Cause the data type of resource in master is analyzed . We have mapped the data type of resource_raw in metadata as not_analyzed which prevents from dividing "Iron ore" int "Iron" and "ore".
