### ISSUE TITLE
72 contracts on OLC - contract tally incorrect? 

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#836]
The contract tally on the front end is displaying 72 contracts (on the homepage, advanced search page, all contracts page, etc.). No one at CCSI has added new contracts to OLC over the past week, so the count should be 70. 

Could you please explain why this happened, and make necessary fixes as needed? Thanks. 

cc @KaitlinCCSI @SamCCSI

**Comment by JesseCCSI** [comment]
Just to note that OLC is now displaying 74 contracts in the tally

**Comment by JesseCCSI** [comment]
Looks like @SamCCSI may have resolved this -- please do not close the ticket until we confirm, but no need to look into this at this point. Thanks.

**Comment by anderspeders** [comment]
Can we close this?

**Comment by JesseCCSI** [comment]
Thanks @anderspeders we're still looking in to this - can we leave open until we confirm whether it's a bug or contracts published in error? 

cc @KaitlinCCSI @SamCCSI

**Comment by anjesh** [comment]
@JesseCCSI Can you see if this can be closed now?

**Comment by JesseCCSI** [comment]
Thanks @anjesh yes this can be closed.

**Comment by anjesh** [comment]
thanks.
