### ISSUE TITLE
Request to export country numbers to excell

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#837]
Request from Perrine:

Do you know if we can extract from the site how many contracts we have per country ?

I know that there is the left side bar but don't know how to get the numbers to be copied and pasted on excel from there.

**Comment by anderspeders** [comment]
This can all be done through the downloaded file from the search page: 

1) Download the dataset from the advanced search page with all contracts (right side)
2) Create a pivot table (rows=country, value=count, filter; document type="contract")

**Comment by anderspeders** [comment]
closing this.
