### ISSUE TITLE
Removed annotation categories re-appearing in dropdown 

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#839]
Some previously removed annotation categories have re-appeared in the category dropdown on the advanced search page -- Please see screenshot below 

![screen shot 2016-03-23 at 09 54 21](https://cloud.githubusercontent.com/assets/14910764/13987309/57392a12-f0dd-11e5-9f8d-d59e4574d7f2.png)

**Comment by hello-deepak** [comment]
I found  two contracts containing these categories "4. Environmental provisions//4. Dispositions environnementales "  and "3. Developers financial obligations//3. Obligations financières du détenteur du titre" .

http://admin.resourcecontracts.org/contract/1134
http://admin.resourcecontracts.org/contract/1133

Please edit and replace the annotation categories with correct category and publish it.

Thank you!

**Comment by SamCCSI** [comment]
Thanks, these should not have been published at all -- all of those
annotations have now been removed.

On Thu, Mar 24, 2016 at 7:27 AM, Deepak <notifications@github.com> wrote:

> I found two contracts containing these categories "4. Environmental
> provisions//4. Dispositions environnementales " and "3. Developers
> financial obligations//3. Obligations financières du détenteur du titre" .
>
> http://admin.resourcecontracts.org/contract/1134
> http://admin.resourcecontracts.org/contract/1133
>
> Please edit and replace the annotation categories with correct category
> and publish it.
>
> Thank you!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/839#issuecomment-200796528>
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School | The Earth Institute, Columbia University
435 W116th St. New York, NY 10027
| (+1)(212) 854-2635 <+1212-854-2635> | (+1)(646) 630-4123 <+1646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>
