### ISSUE TITLE
Tagging of content betweeen pages - and scrolling feature

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#84]
Is it possible to have the pages scroll down the page like a word doc, rather than having to click on p. 2, p.3 and view each page separately? 

This is particularly important when a clause goes over two pages, or when an annotation wants to refer to clauses on different pages, and therefore not *only* a UI issue.

Based on feedback from @samCCSI

**Comment by anderspeders** [comment]
Any thoughts on how this could be done @anjesh @byndcivilization ?

**Comment by anderspeders** [comment]
Please check that this issue is prioritised in this sprint. Would like to see some progress on it as we are getting many user requests on it.

**Comment by anjesh** [comment]
The vertical scroll for text is in place now in rc portal, now annotation is possible for text that run across multiple pages. Similar UI will also be part of the subsite for the viewing of the annotations and text.
