### ISSUE TITLE
Error - PDF file is encrypted

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#841]
http://resourcecontracts.elasticbeanstalk.com/contract/1212

How to resolve?

Here's what it looks like on the front-end: http://www.resourcecontracts.org/contract/ocds-591adf-TL0008220745RC/view

**Comment by manishgs** [comment]
There are free online tool available to unlock encrypted pdf file.  You can[ this site] (http://www.pdfunlock.com/) to remove restrictions and re-upload the file.

**Comment by charlesyoung** [comment]
@SamCCSI I noticed more PDF encryption issues, three of the contracts were uploaded last week. 

http://resourcecontracts.elasticbeanstalk.com/contract?type=pdftext&status=null

**Comment by SamCCSI** [comment]
We will fix these, thanks @charlesyoung 

@manishgs would it be possible for the system to alert our uploaders when the file can't be processed so that they can fix the document there and then, rather than us waiting?

**Comment by manishgs** [comment]
We have contract processing email notification on "Complete" and "Error". The email send to uploaders email.

**Comment by manishgs** [comment]
Reopen if you have any other issues.
