### ISSUE TITLE
404 error for published contract

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#842]
Contract is published and appears on search results
http://resourcecontracts.elasticbeanstalk.com/contract/1339

But when you click on the result to take you to the contract page you receive a 404 error: http://www.resourcecontracts.org/contract/ocds-591adf-CN7577314666RC/view 

![image](https://cloud.githubusercontent.com/assets/12913915/14047498/7f2d389a-f27e-11e5-8fd9-50a36dd2a8fa.png)
![image](https://cloud.githubusercontent.com/assets/12913915/14047504/825e5b8e-f27e-11e5-946d-3b03c58efc6c.png)

**Comment by SamCCSI** [comment]
Another example: http://www.resourcecontracts.org/contract/-1051/view

The advanced search page erroneously inserts "-" infront of the contract number, which makes the link not work.

**Comment by hello-deepak** [comment]
These two contracts are the parent contracts of each other .

http://admin.resourcecontracts.org/contract/1339
http://admin.resourcecontracts.org/contract/1338

which violate the rules of associated contracts .

So please edit the contract (parent contract)  and publish the metadata.

**Comment by anderspeders** [comment]
@samCCSI was this sufficient as answer?

**Comment by SamCCSI** [comment]
@hello-deepak @anderspeders Thanks, but the system won't let me change the first contract to the main contract, rather than an associated contract. It shows a (X) when I try to select "main contract". 

So both contracts are listed as associated documents right now, even though amendment #1 is listed as "(Main)" on the metadata page of amendment #2:
![image](https://cloud.githubusercontent.com/assets/12913915/15016896/3a5b504e-11e1-11e6-97f3-73803cad72d5.png)

All three contracts don't load on front end.

http://www.resourcecontracts.org/contract/ocds-591adf-CN6400265876RC/view
http://www.resourcecontracts.org/contract/ocds-591adf-CN7425606136RC/view
http://www.resourcecontracts.org/contract/ocds-591adf-CN1001064856RC/view

Can you let me know how I can change these so that one is the main contract and the others are associated?

**Comment by hello-deepak** [comment]
Fixed. 

http://www.resourcecontracts.org/contract/ocds-591adf-CN8585698303RC/view
http://www.resourcecontracts.org/contract/ocds-591adf-CN8585698303RC-1338/view
