### ISSUE TITLE
Scoping for User Permissions

### ISSUE THREAD

**Issue by manishgs** [NRGI/resourcecontracts.org#844]
There are some confusions for user role and permissions. To clarify the confusion i 've listed current  permissions and proposed user role and permissions. Please review the permissions and let us know your comments.

**Current system have following user role and permissions**

Role | Permissions for Contract | Permissions for User Management | Activity Logs | Mechanical Turk
-------|-------|---------|---------|-----|---------
Admin | Add, Edit, Delete, Publish Contract (All country) | Add, Edit Delete User ( All Country) | Views All Contract Activities | Add, Reset, Review, Approve, Reject Tasks, send to RC, send to Mturk
Research Associate | Add, Edit, Publish Contract (All country) | No User Rights | Views All Contract Activities | Add, Reset, Review, Approve, Reject Task, send to RC, send to Mturk
Country Admin | Add, Edit, Delete, Publish Contract (only own country) | Add, Edit Delete User ( Only own Country) | Views only own country Contract Activities | Add, Reset, Review, Approve, Reject Tasks, send to RC, send to Mturk for own country
Country Researcher | Add, Edit, Publish Contract (only own country) | No User Rights | Views only own Contract Activities | Add, Reset, Review, Approve, Reject Tasks, send to RC, send to Mturk for own country

**Proposed user role & permissions**

Role | Permissions for Contract | Permissions for User Management | Activity Logs | Mechanical Turk
 -------|-------|---------|---------|-----|---------
Admin | Add, Edit, Delete, Publish Contract (All country) | Add, Edit Delete User ( All Country) | Views All Contract Activities | Add, Reset, Review, Approve, Reject Tasks, send to RC, send to Mturk
Research Associate | Add, Edit, Publish Contract (All country) | No User Rights | Views All Contract Activities | Add, Review, Approve, Reject Task, Send to RC
Country Admin | Add, Edit, Delete, Publish Contract (only own country) | Add, Edit Delete User ( Only own Country) | Views only own country Contract Activities | Add, Reset, Review, Approve, Reject Tasks, send to RC, send to Mturk for own country
Country Uploader | Add, Edit (only own country) | No User Rights | Views only own Contract Activities | Add, Reset, Review, Approve, Reject Tasks for own country

There are few changes on Country Researcher permissions.

@anderspeders @charlesyoung

**Comment by charlesyoung** [comment]
Looks good. We need a country user that has no rights to publish contracts which above addresses.

**Comment by upasna01** [comment]
I think this issue can be closed for now.
