### ISSUE TITLE
Associated documents - contract count and display

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#849]
Apologies for another post on the contract count and associated documents display but I'm not sure about the final outcome of our discussions. 

I uploaded a Sierra Leone EIA and it shows is the contract count as well in the list. It shouldn't show in the contract count but do we show it in the list? 

![image](https://cloud.githubusercontent.com/assets/13888372/14463217/7bac6d62-00ca-11e6-8c31-bfd85be41c3d.png)

**Comment by charlesyoung** [comment]
Link: Add / displaying associated documents without having them appear in contract number tally #603

**Comment by SamCCSI** [comment]
Hi Charles,

EIA is a doc type, not a contract type. So it will show up if you just filter all of Sierra Leone's documents. But if you also add to the filter Doc Type = Contract, then the EIA won't appear.

In our proposal on associated documents and contract tallies, we set this out, and also asked for the word "contracts" in the circle to be changed to "documents", to make this more consistent with the front page tally which says "contracts and associated documents". @anderspeders can we please confirm that this change will be made.

cc @KaitlinCCSI
