### ISSUE TITLE
Annotations duplicate themselves

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#85]
Annotations duplicate themselves if I close it, and then re-open to add a tag:

![image](https://cloud.githubusercontent.com/assets/1101585/8336321/9391d16e-1a71-11e5-8efa-c8d7ff82edf8.png)

Bug reported by @samCCSI

**Comment by anjesh** [comment]
annotation id was not passed as responsed when created, hence re-editing without refreshing page becomes create. Fixed now.
