### ISSUE TITLE
Mechanical Turk

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#850]
I wanted to reset the pending Sierra Leone Mechanical Turk pages but received a 'HIT could not be reset' error. The error is because we only have a very low balance in our account. These tasks should have been auto-reset after the 10 days period but couldn't because of the low balance. 

cc @anderspeders

**Comment by anjesh** [comment]
Will be addressed through this issue https://github.com/NRGI/resourcecontracts.org/issues/795
