### ISSUE TITLE
Changes to annotation module: buggy hovering annotation window

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#853]
The hovering annotation windows still seem buggy 
- sometimes they appear, other times they don’t;  
- sometimes they are cut off, other times they are not; 
- @charlesyoung also noted on March 2 that they don’t necessarily appear in the right place on the page. We’ve also experienced this a couple of times when testing the new version today (but certainly less than on previous occasions with the current version of the site).

**Comment by manishgs** [comment]
fixed.
