### ISSUE TITLE
Changes to annotation module: annotation column display

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#854]
Problem: In the scrolling annotation column, the way things are grouped doesn’t match up with our previous suggestions: at the moment, the page number is listed and then all of the relevant articles are listed (not just the articles on the relevant page), and the whole line is hyperlinked to the page number. 

![image](https://cloud.githubusercontent.com/assets/12913915/14541152/8afa3ef6-0256-11e6-99a4-ffc0e990b9b4.png)

Solution: Each page hyperlink should only contain the articles that are contained on that page — articles appearing on other pages should not be included in the brackets of that page.

It should look like this:
![image](https://cloud.githubusercontent.com/assets/12913915/14541236/f65acc88-0256-11e6-8547-4596176719f4.png)

**Comment by manishgs** [comment]
This is fixed. Please review once. [demo link](http://resourcecontracts-demo1.elasticbeanstalk.com/contract/1822/annotate#/pdf/page/1/annotation/7957)

**Comment by SamCCSI** [comment]
Thanks @manishgs — this is getting there. Some changes that are needed. Let's use the following as an example: 

![image](https://cloud.githubusercontent.com/assets/12913915/14856199/21beff3a-0c65-11e6-8192-122ade979db8.png)

- "P 1" should read "Page 1"
- Multiple refs from same page should be linked — It should "Page 1 (Arts. 1, 2)" rather than "Page 1 (Art. 1), Page 1 (Art. 2)"
- All article references should be on the same line, separated by commas — so this example should read: "Page 1 (Arts. 1, 2), Page 2 (Art. 2), Page 3 (Art. 7)" all on the same line.

**Comment by SamCCSI** [comment]
References need to be listed in page order, and for multiple refs on same page, in numerical order by article.

Right now they are listed in the order in which they were added.

Eg: I just edited one of the annotation sources on p. 1, and now it appears below the refs on p. 3.
![image](https://cloud.githubusercontent.com/assets/12913915/14856479/31f52d6a-0c66-11e6-8045-a3fc6fb8067c.png)

Correct order should be "Page 1 (Arts. 2, 4), Page 2 (Art. 3), Page 3 (Art 9)"

**Comment by manishgs** [comment]
> ....  "Page 1 (Arts. 1, 2)" ...

You grouped annotation by page. In this case annotation link will be on number as shown below :

Page 1 (Arts. [2](http://resourcecontracts-demo1.elasticbeanstalk.com/contract/1822/annotate#/pdf/page/2/annotation/7968), [4](http://resourcecontracts-demo1.elasticbeanstalk.com/contract/1822/annotate#/pdf/page/2/annotation/7968)),

@SamCCSI  Please confirm.

**Comment by SamCCSI** [comment]
@manishgs that would be great!

Can "Arts." also hyperlink to the first annotation marker on that page?

Eg. Page 1 ([Arts. 2](http://resourcecontracts-demo1.elasticbeanstalk.com/contract/1822/annotate#/pdf/page/2/annotation/7968), [4](http://resourcecontracts-demo1.elasticbeanstalk.com/contract/1822/annotate#/pdf/page/2/annotation/7968)),

**Comment by manishgs** [comment]
Its difficult to group article reference like 'Page 2 (Arts. 2, 4)' instead I've shown like this 'Page 2 (Arts. 2,  Art. 4).' Please check on  [Admin](http://admin.resourcecontracts.org/contract/1837/annotate) and [frontend](http://www.resourcecontracts.org/contract/ocds-591adf-TL0077233259RC/view#/pdf/page/27/annotation/3702)
