### ISSUE TITLE
Changes to annotation module: problems when zooming

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#855]
The size of the yellow annotation markers stays the same when you zoom in/ out – this will be an issue if an annotation marker is placed over an entire paragraph/ article.

Our annotators are already complaining about it being very difficult to annotate at 100% because the text size is small.

Regular:
![image](https://cloud.githubusercontent.com/assets/12913915/14541527/5ebaa798-0258-11e6-8271-72ed7347bd56.png)

Large zoom:
![image](https://cloud.githubusercontent.com/assets/12913915/14541537/652eb5d8-0258-11e6-81db-37f54f4a0b89.png)

**Comment by anderspeders** [comment]
@manishgs Do you have an update here?

**Comment by manishgs** [comment]
This issue is not fixed yet. We are exploring workaround for zoom, re-size and moving position of annotation,

**Comment by manishgs** [comment]
fixed.
