### ISSUE TITLE
Changes to annotation module: problems saving on backend

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#856]
We tried making and saving changes to annotations in the PDF view 
- Changes to both the text of the annotation and the article reference number sometimes didn’t save at all, and in other cases only saved the second time I tried making them 
- Sam had raised this point regarding article references in the relevant github thread on March 21, and Jesse raised it in the same thread https://github.com/NRGI/resourcecontracts.org/issues/694#issuecomment-180994051

**Comment by manishgs** [comment]
@SamCCSI 
This issue has been fixed. Please review on [demo](resourcecontracts-demo1.elasticbeanstalk.com)

**Comment by SamCCSI** [comment]
@manishgs thanks this looks good. Will reopen if we encounter more problems.

**Comment by manishgs** [comment]
New Annotation module has been deployed to [admin](http://admin.resourcecontracts.org/contract/1002/annotate) and [frontend](http://www.resourcecontracts.org/contract/ocds-591adf-PH6493643447RC/view#/pdf/page/18/annotation/1183). Please review once.
