### ISSUE TITLE
Changes to annotation module: Changing the annotation category doesn’t work

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#857]
Changing the annotation category doesn’t work (tried changing it from “Legal Enterprise Identifier” to “Company Website”) 
- When Jesse tried to change the annotation category a second time, this saved and worked, but this action: (1) got rid of the annotation text; and (2) cleared the other article reference numbers (i.e. behaved as if Jesse was creating a new annotation) 
- The PDF also did this (was not upside down before): 
![image](https://cloud.githubusercontent.com/assets/12913915/14541667/099227f4-0259-11e6-9509-9498d0605b76.png)

Jesse previously raised this in the relevant github thread on March 22 https://github.com/NRGI/resourcecontracts.org/issues/694#issuecomment-180994051

**Comment by SamCCSI** [comment]
Also from Jesse:

•	When I tried to make any of the above changes, after I saved, the PDF started to be buggy (either the whole PDF page flipped upside down, or a part of the PDF page did so), e.g. 
![image](https://cloud.githubusercontent.com/assets/12913915/14541722/579c550a-0259-11e6-8b59-b1e01599726a.png)

•	We still think there needs to be the ability to change the page number of annotations and the location of the yellow annotation markers

**Comment by manishgs** [comment]
> When Jesse tried to change the annotation category a second time, this saved and worked, but this action: (1) got rid of the annotation text; and (2) cleared the other article reference numbers (i.e. behaved as if Jesse was creating a new annotation)

When changing the annotation category, annotation text will replace with previously saved text of that category. if category is not exist for the contract then text will be empty.


> The PDF also did this (was not upside down before):

Fixed [link](http://resourcecontracts-demo1.elasticbeanstalk.com/contract/1822/annotate#/pdf/page/1/annotation/7957)

> When I tried to make any of the above changes, after I saved, the PDF started to be buggy (either the whole PDF page flipped upside down, or a part of the PDF page did so), e.g. 

Fixed [link](http://resourcecontracts-demo1.elasticbeanstalk.com/contract/1822/annotate#/pdf/page/1/annotation/7957)

> We still think there needs to be the ability to change the page number of annotations and the location of the yellow annotation markers

Page number can be changed from contract summary [page](http://resourcecontracts-demo1.elasticbeanstalk.com/contract/1822)

**Comment by SamCCSI** [comment]
How do we change the page number of an annotation on the contract summary page? It only lets you change text. Clicking on the page number hyperlinks you to that page of the contract:
![image](https://cloud.githubusercontent.com/assets/12913915/14856641/f54fe552-0c66-11e6-9b20-592733337e33.png)

Also, if we change the page number like this, where will the annotation be placed? It will introduce a lot of problems / inaccurate markers. Suggest looking into ability to change location (_and_ page number) of annotation marker CC @anderspeders

**Comment by manishgs** [comment]
@SamCCSI 
you can change page number by double clicking page number of pdf annotation.
![screenshot from 2016-04-27 20 47 08](https://cloud.githubusercontent.com/assets/3942999/14856813/4b4b7f32-0cb9-11e6-956d-f69827a13f6b.png)

Position of the annotation will be same on updated page.

**Comment by SamCCSI** [comment]
I see. Thanks!



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School | The Earth Institute, Columbia University
435 W116th St. New York, NY 10027
| (+1)(212) 854-2635 <+1212-854-2635> | (+1)(646) 630-4123 <+1646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

*New Report: Land Deal Dilemmas: Grievances, Human Rights, and Investor
Protections
<http://ccsi.columbia.edu/2016/03/10/land-deal-dilemmas-grievances-human-rights-and-investor-protections/>*
Available at: *http://goo.gl/qctX9I <http://goo.gl/qctX9I>*

**Comment by manishgs** [comment]
fixed.
