### ISSUE TITLE
"By topic" annotation button is buggy

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#858]
http://www.resourcecontracts.org/contract/ocds-591adf-PH6493643447RC/view

This contract has 25 annotations but when you arrive at the page only two are showing:
![image](https://cloud.githubusercontent.com/assets/12913915/14543877/433c475e-0264-11e6-998a-759ab380a7ef.png)

If you try clicking on a type of topic (eg "Environment" or "Fiscal") there is no change in how annotations are displayed or organized:
![image](https://cloud.githubusercontent.com/assets/12913915/14543911/5f0759a6-0264-11e6-844d-d749f597f0b3.png)
![image](https://cloud.githubusercontent.com/assets/12913915/14543913/62845e3a-0264-11e6-96d2-e087ad6961c7.png)

Only when you click on "By Page" can you see all 25 annotations.
![image](https://cloud.githubusercontent.com/assets/12913915/14543966/9b3496f0-0264-11e6-90d7-1b8eef4a889b.png)

Also, many of the annotation categories are incorrectly filed under OTHER. Eg. "Community consultation" should be under SOCIAL, not OTHER.

**Comment by manishgs** [comment]
Annotation listing issue will be resolve after deploying new annotation module. http://rc-site-demo.elasticbeanstalk.com/olc/public/contract/ocds-591adf-CD1063510722OL/view#/pdf/page/1/annotation/2861

**Comment by anderspeders** [comment]
What is the status here post the new deployment @SamCCSI - still buggy?

**Comment by manishgs** [comment]
This issue is fixed and deployed.

**Comment by SamCCSI** [comment]
Also working nicely now. Thanks @manishgs and @anderspeders
