### ISSUE TITLE
Hit could not be reset

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#859]
![image](https://cloud.githubusercontent.com/assets/1101585/14571598/0c555f5a-0318-11e6-9784-7022b18e9654.png)

I think this issue has been raised before. Would be good to have a status on this?

**Comment by anderspeders** [comment]
Same issue with multiple contracts: http://resourcecontracts.elasticbeanstalk.com/mturk/1512

**Comment by manishgs** [comment]
Reset is working fine. I did reset for http://resourcecontracts.elasticbeanstalk.com/mturk/1512 and didn't get any error. It might be due to MTurk balance that you are not able to reset HIT.

**Comment by anderspeders** [comment]
Ok closing for now.
