### ISSUE TITLE
"Back" button redirects to wrong location in annotation UI 

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#86]
Currently the *Back button* redirects to contract home page. 

Suggestion: 
It would be helpful if back button redirected back one click, and a separate “contract home” button had the function that the Back button currently has.

Submitted by @samCCSI

**Comment by anderspeders** [comment]
@anjesh Did you review this?

**Comment by anjesh** [comment]
Back button is now renamed to "back to contract details". This should be clear and takes to the contract details page now.
