### ISSUE TITLE
Clips - Feature can be turned on/off

### ISSUE THREAD

**Issue by jedm** [NRGI/resourcecontracts.org#860]
Per request in PDF provided for specs, Clippings feature can be turned ON and OFF. The value of this includes:

- Clippings will be an important but minority use case and pages cannot be cluttered with the clip icon next to every annotation/item in a list

- Clippings is designed to allow you to add, remove and refine your list of Clips while the feature is ON, then to keep your list after the selection mode is turned OFF again

When Clippings is ON, UI changes include:

- Clip icon next to each annotation/item in list
- Color change to Clips button
- Additional button titled 'submit' or 'compare' that lets you multiselect then ADD to your Clips list

(Related to discussion in #789)

![rc_olc_clipping_ux_1 5a](https://cloud.githubusercontent.com/assets/2153664/14578502/9a217172-033e-11e6-93d8-0936f6781819.jpg)
![rc_olc_clipping_ux_1 5b](https://cloud.githubusercontent.com/assets/2153664/14578500/99f4ac50-033e-11e6-9811-1af9cd4d482c.jpg)
![rc_olc_clipping_ux_1 5c](https://cloud.githubusercontent.com/assets/2153664/14578501/9a1c26ea-033e-11e6-9348-272a8c2e877b.jpg)

**Comment by manishgs** [comment]
@hello-deepak  Please implement Clips on/off feature.

**Comment by hello-deepak** [comment]
Please review clipping on [demo](http://rc-site-demo.elasticbeanstalk.com/rc/public).

Clip can be done in
* contracts [detail page](http://rc-site-demo.elasticbeanstalk.com/rc/public/contract/ocds-591adf-PH6493643447RC)
* Contract [view page ](http://rc-site-demo.elasticbeanstalk.com/rc/public/contract/ocds-591adf-PH6493643447RC/view)

Clip View 
http://rc-site-demo.elasticbeanstalk.com/rc/public/clip/view

**Comment by hello-deepak** [comment]
Please use #893 issue for any further discussion.
