### ISSUE TITLE
Decisions needed for changing left bar/"burger" menu

### ISSUE THREAD

**Issue by jedm** [NRGI/resourcecontracts.org#862]
For NRGI and CCSI teams, as planned in last call with @anderspeders, here are two options for changing the left bar menu that opens when you click the logo/"hamburger." (We've agreed that the superlong list of all Countries and Resources is not desired.)

Full set of questions (including a couple of inside page issues and smaller questions) are in **[this PDF](https://github.com/NRGI/resourcecontracts.org/files/224928/RC_OLC_homepage.menus.pdf)** - please download. 

Main question is whether we prefer to _combine_ primary navigation (traditional use of left bar) with search shortcuts (current use) or switch over to only nav.

Proposal 1:
- Home
- All Contracts
- View by Country
- View by Resource
- About ResourceContracts
- Glossary
- FAQ

Proposal 2

- Home
- All Contracts
- View by Country
- View by Resource
- About ResourceContracts
- Glossary
- FAQ
- Top Countries _(automated list)_
   -  _[Country w/most docs]_
   -  _[Country w/2d most docs]_
   -  _[Country w/3d most docs]_
- Top Resources _(automated list)_
   -  _[Resource w/most docs]_
   -  _[Resource w/2d most docs]_
   -  _[Resource w/3d most docs]_

**Please see other questions in PDF below...**

@KaitlinCCSI @charlesyoung 

![rc_olc_homepage menus](https://cloud.githubusercontent.com/assets/2153664/14622597/e62c6bd8-057f-11e6-8ff7-5528362883a2.jpg)

**[PDF: RC_OLC_homepage+menus.pdf](https://github.com/NRGI/resourcecontracts.org/files/224928/RC_OLC_homepage.menus.pdf)**

**Comment by charlesyoung** [comment]
The primary search criteria will surely be on country. @jedm can we therefore not consider the sleeker OC country searching option? Also do you feel that the public will want to run a global search, from the home page, on resources? Should this not rather be done through the advanced searching interface?  

![image](https://cloud.githubusercontent.com/assets/13888372/14632125/41e30b16-0617-11e6-952a-7c50882dbfe7.png)

**Comment by jedm** [comment]
@charlesyoung, I do think it's  valuable to include the resources option prominently, yes. 

Which is the "sleeker" approach you're referring to, though, and can you please clarify if you're talking about a top navigation or the left bar menu?

**Comment by anderspeders** [comment]
For NRGI the preference would be for proposal 1 in order to ensure simplicity.

**Comment by jedm** [comment]
>For NRGI the preference would be for proposal 1 in order to ensure simplicity.

Note on left bar - we should also streamline design of left bar for maximum usability, simplicity - in either option!

**Comment by jedm** [comment]
@KaitlinCCSI and @charlesyoung -

Had a good conversation with @anderspeders and we agree that the left bar should be navigation only - as is most traditional. 

We also think that navigation should be consistent on the left/via "burger" menu - and never across the top, even on homepage.

Suggested left navigation items - and wording - are repeated below. **Please confirm no final objections to this.**

Home
All Contracts
View by Country
View by Resource
About ResourceContracts
Glossary
FAQ

After final confirmation, we will assign this thread to YI for implementation. 

Continuation of Charles's good question about per-country search will continue in the #186 Homepage thread. (And apologies to @SamCCSI - who preferred the country shortcuts in the bar!)

**Comment by SamCCSI** [comment]
No objections from me, thanks Jed!



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School | The Earth Institute, Columbia University
435 W116th St. New York, NY 10027
| (+1)(212) 854-2635 <+1212-854-2635> | (+1)(646) 630-4123 <+1646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

*New Report: Land Deal Dilemmas: Grievances, Human Rights, and Investor
Protections
<http://ccsi.columbia.edu/2016/03/10/land-deal-dilemmas-grievances-human-rights-and-investor-protections/>*
Available at: *http://goo.gl/qctX9I <http://goo.gl/qctX9I>*

**Comment by KaitlinCCSI** [comment]
Fine with me, too, although one small request: can we also include a link
to this "additional resources" page (which I think we had agreed to rename
to something else -- Guides?) --
http://www.resourcecontracts.org/page/resources. I think this is a useful
page for users, and fear it may get lost if buried in footer when other
similar pages are available through that nav button.

On Mon, Apr 25, 2016 at 7:52 AM, SamCCSI <notifications@github.com> wrote:

> No objections from me, thanks Jed!
>
>
>
> *SAM SZOKE-BURKE*
> *Legal Researcher**Columbia Center on Sustainable Investment*
> Columbia Law School | The Earth Institute, Columbia University
> 435 W116th St. New York, NY 10027
> | (+1)(212) 854-2635 <+1212-854-2635> | (+1)(646) 630-4123 <+1646-630-4123
> >
> | s.burke@columbia.edu
> | www.ccsi.columbia.edu | @CCSI_Columbia <
> https://twitter.com/CCSI_Columbia>
> | @samszokeburke <http://twitter.com/samszokeburke>
>
> *New Report: Land Deal Dilemmas: Grievances, Human Rights, and Investor
> Protections
> <
> http://ccsi.columbia.edu/2016/03/10/land-deal-dilemmas-grievances-human-rights-and-investor-protections/
> >*
> Available at: *http://goo.gl/qctX9I <http://goo.gl/qctX9I>*
>
> On Fri, Apr 22, 2016 at 7:40 PM, Jed Miller <notifications@github.com>
> wrote:
>
> > @KaitlinCCSI <https://github.com/KaitlinCCSI> and @charlesyoung
> > <https://github.com/charlesyoung> -
> >
> > Had a good conversation with @anderspeders
> > <https://github.com/anderspeders> and we agree that the left bar should
> > be navigation only - as is most traditional.
> >
> > We also think that navigation should be consistent on the left/via
> > "burger" menu - and never across the top, even on homepage.
> >
> > Suggested left navigation items - and wording - are repeated below.
> *Please
> > confirm no final objections to this.*
> >
> > Home
> > All Contracts
> > View by Country
> > View by Resource
> > About ResourceContracts
> > Glossary
> > FAQ
> >
> > After final confirmation, we will assign this thread to YI for
> > implementation.
> >
> > Continuation of Charles's good question about per-country search will
> > continue in the #186
> > <https://github.com/NRGI/resourcecontracts.org/issues/186> Homepage
> > thread. (And apologies to @SamCCSI <https://github.com/SamCCSI> - who
> > preferred the country shortcuts in the bar!)
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/NRGI/resourcecontracts.org/issues/862#issuecomment-213627264
> >
>
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/862#issuecomment-214301575>
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01QKAQ9Kd&m=e308454d9302&t=20160425&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01QKAQ9Kd&m=e308454d9302&t=20160425&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01QKAQ9Kd&m=e308454d9302&t=20160425&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>
*New Report: Land Deal Dilemmas: Grievances, Human Rights, and Investor
Protections
<http://ccsi.columbia.edu/2016/03/10/land-deal-dilemmas-grievances-human-rights-and-investor-protections/>*
Available at: *http://goo.gl/qctX9I <http://goo.gl/qctX9I>*

**Comment by jedm** [comment]
My own opinion is that Glossary, Guides and FAQ are too similar to make it effective having all three. I would suggest "Glossary & Guides." Also because if people see the 2 separate they will need brain time to wonder which is which. 

I do not feel super strongly, though. Any opinions at NRGI? @KaitlinCCSI maybe you can ask Lisa or Perrine?

**Comment by KaitlinCCSI** [comment]
Just polled colleagues. Majority in favor of having these as distinct, but we can perhaps be persuaded if you could describe where the Glossary & Guides link would take you and what that page would look like. Right now the pages seem pretty distinct to us, and useful to have separated, though we understand where the confusion would come from for users looking at the nav button.

**Comment by jedm** [comment]
I'm fine with keeping all three unless anyone else objects strongly.

**Comment by jedm** [comment]
To reduce confusion, what about removing FAQ from the burger menu. Instead, final list for this menu would be as follows below. Users could get to FAQ from footer and from About page. Please share any final thoughts.

Home
All Contracts
View by Country
View by Resource
About ResourceContracts
Glossary
Guides

**Comment by KaitlinCCSI** [comment]
Fine with everyone at CCSI.

**Comment by jedm** [comment]
Dear @anjesh, we are ready to change the menu from the version that copied old site to the more traditional "burger" menu with the items listed immediately above.

Please note that if the new menu is going to have a logo, it must be the same logo (font, spacing, etc.) as is used on the rest of the site.

Many thanks, all, for the input.

**Comment by anderspeders** [comment]
Excellent, thanks for this @jedm @KaitlinCCSI, 

@anjesh @manishgs Please go ahead and implement.

**Comment by anjhero** [comment]
Hi all, 

I have designed two mockups for this. Please check below:

![navigation-drawer](https://cloud.githubusercontent.com/assets/528549/15138710/60d0ad08-16b1-11e6-9cea-252841660ae3.png)
This is similar to the old one where the main page content is pushed to the right and the menu slides in to the screen from the left. 

![navigation - overlay](https://cloud.githubusercontent.com/assets/528549/15138730/7fb5b4ca-16b1-11e6-972f-7fc3e61b4c49.png)
This is a bit different solution from the previous one. On clicking the hamburger icon, a translucent layer overlays the screen and the menu slides in.

**Comment by jedm** [comment]
It looks great! I prefer the standard menu to the other idea. 

Would also remove the icons -- unless they are going to be used consistently throughout the site to represent those locations.

**Comment by KaitlinCCSI** [comment]
I also prefer the standard menu, and don't think we need the icons.

On Tue, May 10, 2016 at 9:47 AM, Jed Miller <notifications@github.com>
wrote:

> It looks great! I prefer the standard menu to the other idea.
>
> Would also remove the icons -- unless they are going to be used
> consistently throughout the site to represent those locations.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/862#issuecomment-218180645>
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01QQCKTO1&m=fb8edddd1b6d&t=20160510&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01QQCKTO1&m=fb8edddd1b6d&t=20160510&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01QQCKTO1&m=fb8edddd1b6d&t=20160510&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by anderspeders** [comment]
Agree with @jedm @KaitlinCCSI. 

Please go ahead with next step.

**Comment by anjhero** [comment]
Here's the final design of the navigation drawer without the icons:

![navigation-drawer](https://cloud.githubusercontent.com/assets/528549/15205574/26d494ce-1838-11e6-9226-2bb7d77819c5.png)

**Comment by jedm** [comment]
Looks good, @anjhero. Please also update the logo in the drawer by using the same exact font sizes and font styles as in the main site logo.

**Comment by manishgs** [comment]
Menu updated on live.
