### ISSUE TITLE
Not saving contract problem..

### ISSUE THREAD

**Issue by gmagnai** [NRGI/resourcecontracts.org#863]
Hello., I need some help about project settings

I cloned this repo and successfully migrated the migrations.
I don't filled aws settings params in .env. Because I don't have AWS account.
It's possible to use this project without aws s3? 

Then i opened the processContractDocument method in ProcessService.php.

It uses sprintf('python %s/run.py -i %s -o %s', $commandPath, $readFilePath, $writeFolderPath)
the $commandPath is equal to config('nrgi.pdf_process_path'); 

1. how can i correctly set "pdf_process_path"?
2. where can i get "run.py"
3. some errors not listed in storage/logs folder. I think NRGI Log is stored by different folder. But i can't find this folder. 

Thank you. Very much!

**Comment by manishgs** [comment]
> It's possible to use this project without aws s3?

There is no option for storage so you need to update code to use other storage option.

> how can i correctly set "pdf_process_path"?

You need to clone this repo https://github.com/anjesh/pdf-processor.
Path will look like this PDF_PROCESSOR_PATH=/var/www/html/nrgi/pdf-processor on your .env file

> where can i get "run.py"

you can run from your terminal.

>some errors not listed in storage/logs folder. I think NRGI Log is stored by different folder. But i can't find this folder.

Can you explain what types of errors not recorded on log file?

**Comment by gmagnai** [comment]
Thank you for helping me. May be error log is  my thing. 
Best regards!
