### ISSUE TITLE
Contracts not loading 

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#864]
A couple of contracts on OLC are showing the "problem loading the contract" message, e.g. 

http://www.openlandcontracts.org/contract/ocds-591adf-CM4228495718OL/view

http://www.openlandcontracts.org/contract/ocds-591adf-SL8106372240OL/view

I can't see any problems on the back end for either of the above. Not sure if this problem is also arising with other contracts on OLC.

**Comment by SamCCSI** [comment]
@anderspeders @anjesh we solved this by re-clicking "Publish all", but that seems unnecessary, given that all categories were marked in green as published. Is there anything that can be done to avoid this final step, or should we instruct our uploaders and annotators to always click 'publish all' after they edit a contract?

cc @JesseCCSI @KaitlinCCSI

**Comment by anderspeders** [comment]
Yes, hitting the "publish" button is always required if you edit content.

**Comment by anderspeders** [comment]
Can we close this?

**Comment by JesseCCSI** [comment]
Thanks @anderspeders. Just to clarify -- will annotators/ uploaders have to click "publish all" (and thus not have the option to publish metadata but not annotations, for example) or do they just need to click "publish" beside the relevant element they'd like to publish, even if it's already marked as published? I just want to make sure we're giving accurate instructions to annotators and uploaders.

**Comment by anderspeders** [comment]
My understanding is that you can still publish by either hit "Publish all" or by hitting "Publish" for the specific type (eg. metadata). 

However *if* there are bugs with publishing flow - this should obviously be addressed.

**Comment by SamCCSI** [comment]
I think the confusing part is that a contract can be marked as green / published, but if you did not click on "publish" or "publish all" after making any changes, it may no longer actually be published, even though it is still labeled as such. 

If there was a way to ensure that the contract's status aligns with the label it has on the back-end, that would be very helpful.

**Comment by anderspeders** [comment]
@manishgs Can you check what options are available here?

**Comment by manishgs** [comment]
@JesseCCSI  @anderspeders 

`Show Pdf Text : No`

Pdf text is set to `No` so these two contracts are not showing on frontend. Update these contract and set `Show Pdf Text` to `Yes` and publish the metadata.

**Comment by JesseCCSI** [comment]
Thanks @manishgs but I'm not sure this is ready for closing -- the initial problem related to the PDF not loading, and did not relate to the text version. Let me know if I'm mistaken, but I believe that changing the setting you referred to will publish the text?

**Comment by SamCCSI** [comment]
Reopening to address Jesse's comment.

**Comment by manishgs** [comment]
There is some issue with publishing workflow. Which will address in this [issue](https://github.com/NRGI/resourcecontracts.org/issues/876)


> ...  believe that changing the setting you referred to will publish the text?
Currently it is not working but Show Pdf Text is used for show/hide text on frontend.
