### ISSUE TITLE
Annotations listings on 'summary' page list "page" wrongly

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#868]
Annotations listings on 'summary' page list "page" wrongly. Should say "Page 1" not "P 1".
![image](https://cloud.githubusercontent.com/assets/12913915/14959059/a28c03d4-105b-11e6-8214-284ceff5a1f1.png)

Also: should only list the relvant article appearing on the page

![image](https://cloud.githubusercontent.com/assets/12913915/14959176/1188535a-105c-11e6-8077-3258e53e74d5.png)

cc @anderspeders @KaitlinCCSI

**Comment by manishgs** [comment]
> Annotations listings on 'summary' page list "page" wrongly. Should say "Page 1" not "P 1".

fixed.

**Comment by anderspeders** [comment]
@SamCCSI Please review if this issue is fully fixed?

**Comment by SamCCSI** [comment]
Thanks, looks good.
