### ISSUE TITLE
Page navigation disappears in the annotation UI view

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#87]
When I click on page 2 of the OCR-processed PDF, I lose the page numbers at top of the screen, so hard to navigate to page 3, 4 etc to review. 

![image](https://cloud.githubusercontent.com/assets/1101585/8336519/323a4dcc-1a73-11e5-8ef9-4a3dbcaccb97.png)

Submitted by @SamCCSI

**Comment by anjesh** [comment]
There has been complete rewriting of js code for this view. This will be fixed in this 2nd sprint.
