### ISSUE TITLE
MT error -- page not fully downloading

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#870]
Please see email from MT transcriber:

Customer ID: A12WRJ2ZMDW3SU
You previously denied two of my hits saying they were incomplete, and have yet to respond to my message that was sent about them not fully showing up. I am sending you a screen shot of this hit because, like the two HITs you rejected, this one also shows only a couple of lines of the scanned page and then is cut off as though it did not scan properly. I have sent you a link with a screenshot of the image.

http://i67.tinypic.com/i5t9j9.png

**Comment by manishgs** [comment]
Here is the link of original pdf : https://rc-stage.s3-us-west-2.amazonaws.com/62/62-opic-resource-corporation-belize.pdf

Please check the 48 and 51 page. They are corrupted.

**Comment by SamCCSI** [comment]
Thanks @manishgs we will try to locate a non-corrupted version.

If we replace the PDF version while MT jobs are pending, will they be lost?

**Comment by manishgs** [comment]
It'll not affect MT jobs. You can provide us the pdf. we'll replace directly in S3.

**Comment by SamCCSI** [comment]
It appears that this is the only version that can be located.
