### ISSUE TITLE
Annotations missing from migration to new RC-site

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#871]
Two issues regarding migration of annotations: 

1) Annotations from this contract:
https://www.documentcloud.org/documents/1385899-kosmos-energy-suriname-block-45-2011.html

was not migrated to: 
http://www.resourcecontracts.org/contract/ocds-591adf-SR5930694500RC/view

2) Contract and annotations were not migrated from this contract: 
https://www.documentcloud.org/documents/1376099-kosmos-energy-suriname-2011.html

@anjesh @manishgs Could you check why this was missed and suggest how we can get these ported to the new site?

**Comment by manishgs** [comment]
> 2) Contract and annotations were not migrated from this contract: 
https://www.documentcloud.org/documents/1376099-kosmos-energy-suriname-2011.html

The contract file is already present in our system. PDF is linked to [Kosmos Energy - Suriname, Block 45, 2011](http://resourcecontracts.elasticbeanstalk.com/contract/1215)

**Comment by upasna01** [comment]
Not all annotations for the contract matches our code list, here is the list please verify and add the missing categories.
https://docs.google.com/spreadsheets/d/1GRS2MkH7lvzJdD6TBHAdsATRbyesK6ucGV95gbrfnzI/edit#gid=1074364414

**Comment by SamCCSI** [comment]
1.
@manishgs The document is already in the system, but we had multiple versions of it on the old site because the document contains multiple contracts within it, and the annotations for each are different.

So we are still missing the separate copy of this document for Block 43, and the annotations that come with it that are present on the old platform: https://www.documentcloud.org/documents/1376099-kosmos-energy-suriname-2011.html

Can you please re-upload?

2.
@upasna01 @anderspeders This doc appears to be filled in. Do you need more information or something else from us?

**Comment by upasna01** [comment]
Category for Local company Name is not known. Also please verify the category for the given list.

**Comment by manishgs** [comment]
@SamCCSI 

1.  Okay we'll upload the contract.
2. Please confirm/update the category mapping.which is in [google sheet ](https://docs.google.com/spreadsheets/d/1GRS2MkH7lvzJdD6TBHAdsATRbyesK6ucGV95gbrfnzI/edit#gid=1074364414)

**Comment by SamCCSI** [comment]
Thanks @manishgs .

For "Local company Name" can we please just DELETE the field, but could your team also please provide a separate spreadsheet with all instances of this category, and the contract to which they are attached, so that we can manually include as relevant? I have included this request in the google sheet as well.

**Comment by manishgs** [comment]
@SamCCSI 

The Spreadsheet is for only missing annotations from migration.

We have generated categories for two JSON  files and its mapping in this[ google spreadsheet.](https://docs.google.com/spreadsheets/d/1GRS2MkH7lvzJdD6TBHAdsATRbyesK6ucGV95gbrfnzI/edit#gid=1074364414). Please go through each category and update where necessary. I've highlighted text to red color which is not mapped you need to fill the mapped category from [this list](https://docs.google.com/spreadsheets/d/15k-7NCkgu1p2eKgWGZnykASLQoa4gR6fOLskV8mdOhY/edit?ts=566690b1#gid=1026941017)

**Comment by upasna01** [comment]
The missing contract is now uploaded please verify.
http://admin.resourcecontracts.org/contract/1844

**Comment by SamCCSI** [comment]
@manishgs I have updated the first spreadsheet.

Regarding the second spreadsheet, I did not understand — what do you need us to add to the second spreadsheet?

**Comment by manishgs** [comment]
>2) Contract and annotations were not migrated from this contract: 
https://www.documentcloud.org/documents/1376099-kosmos-energy-suriname-2011.html

Annotations migrated. Please verify. http://admin.resourcecontracts.org/contract/1844/annotate

**Comment by SamCCSI** [comment]
@manishgs looks good, thank you.

**Comment by upasna01** [comment]
All missing annotations are migrated please verify.
http://admin.resourcecontracts.org/contract/1215/annotate

**Comment by SamCCSI** [comment]
@upasna01 that contract looks good, thanks.

@manishgs Are there other contracts other than the initial two that were to be migrated?

**Comment by SamCCSI** [comment]
@manishgs @upasna01 @anderspeders there were other contracts identified in May 2016 as not having been migrated. We thought that @anderspeders had allocated them to YI but I cannot find the ticket.

They can be found here: https://docs.google.com/a/columbia.edu/spreadsheets/d/1iwhIIDk7CrIVR2IjtGDIfruA1qRLQ4WfbJxlh2uQNI8/edit?usp=sharing

Column B indicates the problem. Column D indicates the action needed. Column F indicates the current status.

Can YI please start working on these, or indicate what else is needed?

Many thanks,
Sam

**Comment by upasna01** [comment]
The renaming button for contract is updated.

![871](https://cloud.githubusercontent.com/assets/11477899/16686643/4b13f096-4533-11e6-92af-d01e15fdb3e7.png)

Also the after clicking the utility button you will be able to rename multiple contracts at a time. Please review and provide your feedbacks.

![8711](https://cloud.githubusercontent.com/assets/11477899/16686710/bf612608-4533-11e6-8056-58e2c2d3b519.png)

**Comment by SamCCSI** [comment]
@upasna01 wrong issue — latest comment belongs here: https://github.com/NRGI/resourcecontracts.org/issues/883

**Comment by upasna01** [comment]
The doc is updated, we don't have jason files for all of the contracts, Please view the google sheet and provide json file for marked contracts.

https://docs.google.com/spreadsheets/d/1iwhIIDk7CrIVR2IjtGDIfruA1qRLQ4WfbJxlh2uQNI8/edit#gid=0

**Comment by manishgs** [comment]
> Upload to new RC.org. The contract needs to be duplicated for Mauretania. The document is uploaded here: http://www.resourcecontracts.org/contract/ocds-591adf-MA4899997941RC/view#/pdf

@SamCCSI  Could you please explain what we need to do for this?

**Comment by upasna01** [comment]
Please provide abbreviations for the Type Of Contract.

https://docs.google.com/spreadsheets/d/1iwhIIDk7CrIVR2IjtGDIfruA1qRLQ4WfbJxlh2uQNI8/edit#gid=891628407

**Comment by SamCCSI** [comment]
@manishgs we had our research intern take care of this, so you don't need to do anything for those cells that have a similar action required (rows 11, 12, 13, 41).

For all the others, I am still not seeing whether you have carried out the action required? Is this still a work in progress?

**Comment by SamCCSI** [comment]
@manishgs What does "Json not found" mean? Can you access the PDF from the document cloud link in column A?

**Comment by manishgs** [comment]
@SamCCSI we can access the pdf from the document cloud link. We are looking for JSON file which contains metadata and annotation. Here is the sample file [408950-drc-dino-steel.json.txt](https://github.com/NRGI/resourcecontracts.org/files/373074/408950-drc-dino-steel.json.txt) which we used to migrate contracts.

**Comment by SamCCSI** [comment]
@manishgs understood.

Could you please let us know when each action has been carried out? Currently it is unclear whether these missing contracts are on the new site. Please also let us know if there are roadblocks to you migrating these missing contracts.

**Comment by manishgs** [comment]
@SamCCSI 
Following contracts have been migrated. 
contributor_organization "Revue des Conventions Miniers" is used in company name. 
Please review the metadata.
http://admin.resourcecontracts.org/contract/2128
http://admin.resourcecontracts.org/contract/2130 (Signature year is missing in json file so 2015 is recorded in db)
http://admin.resourcecontracts.org/contract/2129

**Comment by SamCCSI** [comment]
@manishgs we are still reviewing the three migrated contracts and will be in touch shortly.

Is there any update on the other contracts that need to be migrated? What are we doing for contracts labeled as "Json file not available"?

**Comment by SamCCSI** [comment]
Thanks for those three contracts. 

Is there any other update on the other contracts that need to be migrated?

**Comment by manishgs** [comment]
@SamCCSI 
We don't have the JSON file for other contracts (Please see "YI Comment" column) so Could you please provide us the missing JSON files ?

**Comment by SamCCSI** [comment]
@anderspeders – can you help here locating JSON files? I am not sure what
this refers to.

**Comment by anjesh** [comment]
The missing contracts/annotations URL json is available by replacing html with json in the documentcloud url.

**Comment by manishgs** [comment]
@SamCCSI 

Three contracts are migrated.
[ MCC-Jiangxi Aynak Security Agreement - Afghanistan, 2009 ](http://admin.resourcecontracts.org/contract/2371)
[ MCC-Jiangxi Aynak Water Supply Agreement - Afghanistan, 2009](http://admin.resourcecontracts.org/contract/2370)
[ MCC Jiangxi Aynak Railway Agreement - Afghanistan 2010 ](http://admin.resourcecontracts.org/contract/2369)

Please verify the metadata of above contracts.


Following two contracts does not have required metadata (Resource, Countries, Signature Year) so we are not able to migrate.

Please have look at the json file and you can also manually upload these two contracts..

https://www.documentcloud.org/documents/515244-termes-de-reference-revue-des-contrats-miniers.json
https://www.documentcloud.org/documents/515243-terms-of-reference-mining-contracts-review-process.json

Let us know you need any help.

**Comment by SamCCSI** [comment]
Thanks, verifying now.

Those two links are not contracts, so we will not upload them into the new system. I have updated the spreadsheet. 

Looks like we are still awaiting rows 32 and 34 of the spreadsheet. I can review those when migrated.

**Comment by manishgs** [comment]
Row 32
Contract is already annotated and there are 31 annotations. http://admin.resourcecontracts.org/contract/837

Row 34
Annotations migrated. 
http://admin.resourcecontracts.org/contract/1567

**Comment by manishgs** [comment]
row 32
Contract is already annotated and there are 31 annotations. http://admin.resourcecontracts.org/contract/837

row 34
Annotations migrated. 
http://admin.resourcecontracts.org/contract/1567

Please verify the migrated annotations and let us know remaining issues from annotation migration if any.
