### ISSUE TITLE
Error "Something went wrong with the annotation store"

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#872]
Our annotator had trouble uploading the contract today, with the system repeatedly presenting error messages and losing all of her metadata entries.

I eventually uploaded the contract but now our annotator has encountered the following error while annotating:  "Something went wrong with the annotation store" 
<img width="1280" alt="screen shot 2016-05-04 at 8 40 10 pm" src="https://cloud.githubusercontent.com/assets/12913915/15033900/f4158e9e-123d-11e6-944e-efa075cbf62f.png">

Our annotator reports "until at the third annotation the yellow frame appeared but disappeared right as I was going to the fourth one -- then I got the message "sorry, something went wrong with the annotation store" (see screenshot). I tried three times but it just won't work anymore... "

**Comment by anderspeders** [comment]
@manishgs can you have a look?

There seems to be two issues here (at least): 
- the upload module
- the annotation module

**Comment by manishgs** [comment]
I checked today, Annotation add/update/delete working fine. Didn't get any error message.
@SamCCSI  can you please try again? and let me know if you encounter this issue again.

**Comment by KaitlinCCSI** [comment]
I think I also got this error message a few hours ago when checking the
demo of the clipping feature, so seems like something is still off.

On Thu, May 5, 2016 at 2:45 AM, Manish Gopal Singh <notifications@github.com
> wrote:

> I checked today, Annotation add/update/delete working fine. Didn't get any
> error message.
> @SamCCSI <https://github.com/SamCCSI> can you please try again? and let
> me know if you encounter this issue again.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/872#issuecomment-217095302>
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01QOvJGtK&m=7c6bfa0d8c20&t=20160505&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01QOvJGtK&m=7c6bfa0d8c20&t=20160505&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01QOvJGtK&m=7c6bfa0d8c20&t=20160505&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by manishgs** [comment]
I am not able to replicate the issue as mention above and didn't get any error message yet.  Recently we have updated Pdf annotator plugin so I believe this issue have been resolve. Please reopen if you encounter the issue again.
