### ISSUE TITLE
Text and PDF page numbers aren't linked after text search

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#874]
1. Open http://www.openlandcontracts.org/contract/ocds-591adf-CD0800583637OL/view
2. Search for "19bis" in text.
3. Click result, which takes you to page 12 of text version of contract.
4. Click PDF: Page 1 of the PDF shows, but it labels page one as page 12
![image](https://cloud.githubusercontent.com/assets/12913915/15082735/6f332d48-1397-11e6-8a0f-8b2e4964121e.png)

Could you please fix step 4? When I click from text to PDF, it should take me to the same page, just switching from text to PDF.

**Comment by anderspeders** [comment]
@manishgs Could you check?

**Comment by manishgs** [comment]
This issue is fixed in admin and frontend. Please review once.

**Comment by SamCCSI** [comment]
Working nicely now. Thanks @manishgs



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School | The Earth Institute, Columbia University
435 W116th St. New York, NY 10027
| (+1)(212) 854-2635 <+1212-854-2635> | (+1)(646) 630-4123 <+1646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

*New Report: Land Deal Dilemmas: Grievances, Human Rights, and Investor
Protections
<http://ccsi.columbia.edu/2016/03/10/land-deal-dilemmas-grievances-human-rights-and-investor-protections/>*
Available at: *http://goo.gl/qctX9I <http://goo.gl/qctX9I>*

On Mon, May 9, 2016 at 8:17 AM, Manish Gopal Singh <notifications@github.com
