### ISSUE TITLE
Translation: specific requirements on Arabic

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#875]
The ministry of Tunisia has expressed interest in RC.org - this would require translation of the front end into Arabic. 

Before making any decision on this it would be helpful to understand if Arabic translation can be done for RC.org?

**Comment by anjesh** [comment]
Can we have someone Arabic speaker to guide on this?

**Comment by charlesyoung** [comment]
Linked: System Arabic translation #906
