### ISSUE TITLE
Bug on Contract Publishing Workflow

### ISSUE THREAD

**Issue by manishgs** [NRGI/resourcecontracts.org#876]
- Contract OCID should not be updated when metadata changes (except country/category/parent document change).
-  Text and Pdf are not showing on frontend when metadata publish. 
- Document type is not selected on contract edit form.

@hello-deepak

**Comment by hello-deepak** [comment]
> *Contract OCID should not be updated when metadata changes (except country/category/parent document change).
> *Text and Pdf are not showing on frontend when metadata publish.

There was some issue with OCID update on editing metadata, which is fixed now.
http://www.openlandcontracts.org/contract/1150/view
http://www.openlandcontracts.org/contract/1179/view

>Document type is not selected on contract edit form.

Fixed
