### ISSUE TITLE
Clipping - sharing as URL and email

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#877]
@anjesh, @manishgs: 

Some follow up questions regarding clipping: 
1) How will the user be able to retrieve the clipping as URL? 
2) Where will the button be located that will enable the user to send emails?

cc @jedm

**Comment by jedm** [comment]
Anjesh, if YI can post mocks of the Share Clippings steps, that would be great. (For sharing by email and sharing by social.) Thank you!

**Comment by hello-deepak** [comment]
Clip listing view contains filters, clipped annotations and buttons such as Share, Download and Print.
 
![clip](https://cloud.githubusercontent.com/assets/7577697/15173925/bbad68d8-177e-11e6-8239-0849b000b8b5.png)

## Share

When clicking share button it'll display social sharing links facebook, twitter, google plus and share with email. Clip url will be displayed beside the button.

![share](https://cloud.githubusercontent.com/assets/7577697/15174289/9276bee0-1780-11e6-9960-ee3c39910a08.png).


### Share via email 

![email](https://cloud.githubusercontent.com/assets/7577697/15174436/75a611b6-1781-11e6-84d7-8b745cd4968b.png)

**Comment by jedm** [comment]
This is a good start for helping clarify.

Will the URL (shown above in the tool) be the same as the URL of the page itself (the URL in the browser location bar)?

Will the share tool and buttons be the same in appearance and function as the RC/OLC site share tool or will it be different?

**Comment by manishgs** [comment]
> Will the URL (shown above in the tool) be the same as the URL of the page itself (the URL in the browser location bar)?

Share url will be different. When click on share icon, `http://rc.org/clip/<CODE>` will be shared instead of the page itself.

> Will the share tool and buttons be the same in appearance and function as the RC/OLC site share tool or will it be different?

Design will be the same in appearance.

**Comment by hello-deepak** [comment]
Please review clipping in demo [site](http://rc-site-demo.elasticbeanstalk.com/rc/public) .

**Comment by hello-deepak** [comment]
Please use #893 issue for any further discussion.
