### ISSUE TITLE
Annotation comments disappeared

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#878]
I reviewed the annotations for this contract on April 20, leaving detailed feedback for 90% of entries. This took quite some time.
http://resourcecontracts.elasticbeanstalk.com/contract/757

All comments have now disappeared. 
1 - is this because of the new module being deployed?
2 - is there a way to recover these comments, which took hours to prepare?

**Comment by manishgs** [comment]
I can see the annotations. Can you please share the screenshot where comments are disappeared?

![screenshot-resourcecontracts elasticbeanstalk com 2016-05-11 09-03-28](https://cloud.githubusercontent.com/assets/3942999/15169124/a1ca7734-1757-11e6-97c9-04176fb9cc80.png)

**Comment by SamCCSI** [comment]
@manishgs The annotations are there, but the **comments** that I left for the annotator on each entry have disappeared. That is what I am trying to recover. Thanks!

**Comment by upasna01** [comment]
The issue is fixed now. Please verify.

**Comment by SamCCSI** [comment]
Many thanks @upasna01 this is much appreciated.
