### ISSUE TITLE
Upside down PDF bug 

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#879]
This is happening again on the frontend. I clicked the "<" arrow 5 times quickly and then the PDF went upsidedown. @anderspeders I think we need to review this issue closely, as users who cannot scroll up and down will often want to quickly navigate in this way.

http://www.openlandcontracts.org/contract/ocds-591adf-LR0574998871OL/view#/pdf/page/29/annotation/2365

![image](https://cloud.githubusercontent.com/assets/12913915/15187126/e0bd4c08-176d-11e6-8480-393dfb33f16f.png)

cc @KaitlinCCSI

**Comment by KaitlinCCSI** [comment]
I've labeled as priority; request that we fully address this as soon as possible.

**Comment by anderspeders** [comment]
@anjesh could you please follow up here?

**Comment by SamCCSI** [comment]
This bug still happens when reviewing text on the backend:

![image](https://cloud.githubusercontent.com/assets/12913915/16744544/a21360ae-477f-11e6-8b7c-8795da61feff.png)

**Comment by SamCCSI** [comment]
Still happening on front end. I changed pages at normal speed.

![image](https://cloud.githubusercontent.com/assets/12913915/17264117/fe72760a-55b2-11e6-9027-333be7f4a072.png)

**Comment by manishgs** [comment]
We have refactor reactjs code and pdf loading code on frontend. Now this bug has been resolve. 

@charlesyoung 
Could you please confirm?

**Comment by charlesyoung** [comment]
Still seems an issue with one of the above [examples](http://www.resourcecontracts.org/contract/ocds-591adf-GN9161820781RC/view#/pdf) (page 2).

**Comment by manishgs** [comment]
check the original pdf https://rc-stage.s3-us-west-2.amazonaws.com/919/919-cbg-guinee-2005.pdf
2nd page is upside down.

**Comment by charlesyoung** [comment]
@SamCCSI I'm closing the ticket. 

Please reopen if the issue reappears.
