### ISSUE TITLE
Demo of DRC subsite for demonstration

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#880]
Complete a demo of a DRC subsite featuring French - English translation.

**Comment by charlesyoung** [comment]
@anjesh will it be possible to create a RC DRC country site?

**Comment by charlesyoung** [comment]
Relates to ticket Internationalization #47

**Comment by anjesh** [comment]
we need the translation for the subsite in this spreadsheet https://docs.google.com/spreadsheets/d/1aLnUIKyi6uHb0Ai8Zl3S21wn2ekOapciMUguTCjddig/edit#gid=1810864825 

linked from https://github.com/NRGI/resourcecontracts.org/issues/47#issuecomment-196803183

**Comment by hello-deepak** [comment]
Please review demo  [DRC](http://rc-site-demo.elasticbeanstalk.com/drc/public/) subsite with french translation.

**Comment by charlesyoung** [comment]
Initial comments below. 

[DRC french translation comments.docx](https://github.com/NRGI/resourcecontracts.org/files/291260/DRC.french.translation.comments.docx)

**Comment by charlesyoung** [comment]
Add "Gérer la qualité des données" for the "Contract Quality Issues" link and lets see if it fits the menu.

**Comment by manishgs** [comment]
@charlesyoung 
The issues are fixed. Please review once.

**Comment by charlesyoung** [comment]
Thanks @manishgs, the site is looking good. Minor updates below. 

1.	Below text boxes in English, when capturing metadata

![image](https://cloud.githubusercontent.com/assets/13888372/15709457/22064d48-2805-11e6-98e6-1ac340d04b91.png)

2.	Select in English, when adding an associated document 

![image](https://cloud.githubusercontent.com/assets/13888372/15709463/2acfd4da-2805-11e6-8ca5-e78e747829f0.png)

3 Back should be Retour, review also needs to be translated 

![image](https://cloud.githubusercontent.com/assets/13888372/15709476/45cf3cda-2805-11e6-92b9-f81a2db637fa.png)

**Comment by manishgs** [comment]
Please review the DRC site. French language has been updated. 

http://rc-site-demo.elasticbeanstalk.com/drc/public/

**Comment by upasna01** [comment]
The issue is fixed, please do verify.

http://admin.resourcecontracts.org/contract/create

![880](https://cloud.githubusercontent.com/assets/11477899/16521677/31398616-3fb8-11e6-9d5a-6620e25f29fc.png)
