### ISSUE TITLE
Bulk download option for text

### ISSUE THREAD

**Issue by giorgiacek** [NRGI/resourcecontracts.org#881]
Can we please add a feature that let you download all the text (txt format) of all the contracts (the one selected or all of them) in bulk?

**Comment by hello-deepak** [comment]
Is bulk text is needed for once or to add as a feature?

Bulk download of text create extra heavy load on the server and I think it is not relevant for all users .

**Comment by giorgiacek** [comment]
If it's too heavy on the server then it would be great to have a download
if possible. (need it for text analysis)

**Comment by giorgiacek** [comment]
Is it possible to have this download then?

**Comment by anderspeders** [comment]
@hello-deepak We will need a bulk zipped file with txt formatted documents. Please estimate the time needed for this or propose a viable alternative? 

cc @manishgs

**Comment by byndcivilization** [comment]
@hello-deepak Can we add bulk download behind oAuth. I remember at some point we talked about auth for elastic search anyways. Where are we on this?

**Comment by byndcivilization** [comment]
@anjesh does this solution sound right? Also we may want to use this as an opportunity to talk about migration to nrgi servers or a managed compose.io elastic search instance.

**Comment by hello-deepak** [comment]
Here is [url](http://s3-us-west-2.amazonaws.com/rc-demo/bulktext/allpages.txt.tgz) of bulk text for now.

**Comment by byndcivilization** [comment]
is this a one time download or do you re archive periodically?

**Comment by anjesh** [comment]
@byndcivilization Rather than the php script, we quickly wrote the bash script to prepare the text file dump directly from the database and upload to S3. How often do you need the download. Otherwise we could present a web wrapper in the admin interface, which runs the bash script and shows the link from S3 when prepared. Does this work for you?

**Comment by byndcivilization** [comment]
I think you can just do a weekly or nightly chron and add a link somewhere.

**Comment by giorgiacek** [comment]
Thanks for the bulk download!
However, would it be possible to have **the texts still divided into the original documents?**
Like this (merged), the analysis I can do it's kind of limited.

Thanks!

**Comment by hello-deepak** [comment]
@giorgiacek 
Here is the [url](http://rc-demo.s3-us-west-2.amazonaws.com/textdump/dumptext.zip) for all texts divided into original documents.

**Comment by hello-deepak** [comment]
Bulk download of zipped text feature is added in admin [portal](http://admin.resourcecontracts.org/contract) .
![admin resource contracts](https://cloud.githubusercontent.com/assets/7577697/17057378/4091437e-5039-11e6-83ab-fccc9268d39c.png)

This zip file is updated once a week.
