### ISSUE TITLE
Ability to re-size & move annotation marker

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#882]
Inserting this request into a new thread, as the old thread it was on (#694) was closed, but Anjesh mentioned setting aside time to investigate this.

@anderspeders and @anjesh, any thoughts?

**Original request by Jesse**
Kaitlin, Sam and I discussed this today -- it would really help us if you could provide an estimate of the cost and time involved in implementing the following:

1. having the ability to change the location of the yellow annotation box on the page; and
2. having the ability to re-size the annotation box.

Re point (2), we were looking at how this contract (http://www.resourcecontracts.org/contract/ocds-591adf-PH7733849609RC/view#/pdf/page/10/annotation/26427) was annotated by the Philippines EITI team. The way they have placed the annotation boxes helps to draw the user's eye to the relevant place on the page. We'd like to have the ability to do the same with new contracts on both RC and OLC, and to update the existing contracts without having to re-upload them.

Also, as annotators start to add contracts directly to the site, it's likely that they will make errors in how they place the annotation boxes. Having the ability to change the location and size of annotation boxes will help our team to be more efficient, and will cut down the time needed to review contracts. Currently, if an annotator makes a mistake re the location or size of the box, the reviewer has to re-annotate. This can take a lot of time if many of boxes are incorrectly sized/ placed.

**Anjesh's response**
I totally get this point. However as I have mentioned in couple of other issues, this changing location and re-sizing abiliy in the plugin we are using is not easily doable due to the way the plugin is developed, as far as i have seen the insides of the working-code. I can't come up with effort required and hence cost at this moment. We still need to explore the code to ensure how to cleverly inject these two features in it. Internally we discussed about implementing this functionality under different mode like "box mode", where you will be able to move the boxes and re-size them, then you won't be able to add/edit/delete annotations in that mode. This still requires some research and before that it's hard for me to come up with any numbers. We are not prioritizing this at the moment, but will set aside some time to explore on this.

**Comment by manishgs** [comment]
We've replaced annotorious plugin (which is used for pdf annotation) with our custom annotator plugin.  Which will also address #882 and #855 issues. Please check the the resize and drag feature in [demo](http://resourcecontracts-demo1.elasticbeanstalk.com/contract/1033/annotate)  and let us know your feedback and comments.
@SamCCSI  @anderspeders

**Comment by SamCCSI** [comment]
Thanks @manishgs this is exciting to see.

1. The system froze after I resized one box — I started resizing a second box and then this blue dotted line remained on the page and I couldn't resize anything else. I think it needed time (1 or 2 seconds) to process? If this churn time could be minimized, that would help avoid having to reload the page.

![image](https://cloud.githubusercontent.com/assets/12913915/15358411/48bbba56-1cd2-11e6-9202-7d7a5c512e9b.png)

2. When I manually resize the marker, the shape I choose (with the mouse still clicked) is larger than the shape it actually becomes once I release the mouse. Is there a way to make the shaping function more accurate? See screenshot below — the box ends up being thinner than the shape I wanted.

![image](https://cloud.githubusercontent.com/assets/12913915/15358563/ff68ad86-1cd2-11e6-8500-5aeb238cd1a1.png)


![image](https://cloud.githubusercontent.com/assets/12913915/15358551/f6349752-1cd2-11e6-99ba-8e6d56c7abcd.png)

**Comment by manishgs** [comment]
@SamCCSI 

1)  I'll take 2-3 seconds to process so if you resize/drag another annotation immediately then there was an issue. Now i've disable resize/drag until annotation updated on database.

2) this issue is fixed. 

Please review once and let me know if there is any issue.

**Comment by SamCCSI** [comment]
This looks great, thanks. (2) works well. Is there any way to reduce the 2/3 second processing time?

If not, this is ready to deploy, provided that it won't delete annotation comments on eisting annotations as last time. Can you confirm that won't happen?

**Comment by manishgs** [comment]
Processing time is the total time taken to update database and reload the annotations so we can't reduce the time.

It will not affect annotation comments. It will update only contract view page.

**Comment by SamCCSI** [comment]
No problem. And it won't delete annotation comments on existing annotations like what happened last time we deployed the new module?

**Comment by manishgs** [comment]
last time it wasn't deleted. Only hidden from the design.

**Comment by SamCCSI** [comment]
Ok, then we are happy for this module to be deployed. Thanks!

And if you could make sure that no comments are hidden from the design that would be greatly appreciated.

**Comment by manishgs** [comment]
Deployed.
