### ISSUE TITLE
New Relic monitoring

### ISSUE THREAD

**Issue by byndcivilization** [NRGI/resourcecontracts.org#884]
Can we add a new relic monitor? It  should give us api metrics that GA doesnt give us.

**Comment by charlesyoung** [comment]
@anjesh can you implement this?

**Comment by anjesh** [comment]
Vitamin might have taken care of this with their existing setup (without newrelic), just need to discuss with them once.

**Comment by anjesh** [comment]
Just learned that vitamin is using AWS metrics for the same purpose. We can close this ticket now.
