### ISSUE TITLE
"Highlight" is not an annotation category and should not be in dropdown box

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#886]
See screenshots
![screen shot 2016-05-18 at 1 47 52 pm](https://cloud.githubusercontent.com/assets/14825437/15371033/3a524098-1cff-11e6-8a74-d1d83eaba01d.png)
![screen shot 2016-05-18 at 1 48 09 pm](https://cloud.githubusercontent.com/assets/14825437/15371034/3a5eec94-1cff-11e6-95bc-71b4a349d8cd.png)

**Comment by SamCCSI** [comment]
I have deleted these annotation entries for the Gambia contract and the Ghana contract is back to draft mode, but is it possible to ensure that this category cannot be re-selected?

![image](https://cloud.githubusercontent.com/assets/12913915/15371464/834c2c96-1d09-11e6-93ff-a395b4a66f74.png)

**Comment by manishgs** [comment]
If category is not selected while creating an annotation default category 'Highlight' is stored in database. Now Category and Annotation Text is set to required field so "Highlight" text will not be appear again.
You can check in demo site. http://resourcecontracts-demo1.elasticbeanstalk.com/contract/1823/annotate#/pdf/page/4/annotation/7979

**Comment by SamCCSI** [comment]
We have one contract with draft annotations, some of which are currently
"highlight". If you deploy the new model, will it delete these annotations?
If yes, we need to ask our annotator to change those annotations first so
that nothing is lost.



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School | The Earth Institute, Columbia University
435 W116th St. New York, NY 10027
| (+1)(212) 854-2635 <+1212-854-2635> | (+1)(646) 630-4123 <+1646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

*New Report: Land Deal Dilemmas: Grievances, Human Rights, and Investor
Protections
<http://ccsi.columbia.edu/2016/03/10/land-deal-dilemmas-grievances-human-rights-and-investor-protections/>*
Available at: *http://goo.gl/qctX9I <http://goo.gl/qctX9I>*

**Comment by manishgs** [comment]
Annotation category will not be deleted. You can change the category after deploy as well.

**Comment by SamCCSI** [comment]
Ok thanks.

**Comment by manishgs** [comment]
deployed.
