### ISSUE TITLE
Matching up/Streamlining Contract View and Summary Pages

### ISSUE THREAD

**Issue by jedm** [NRGI/resourcecontracts.org#889]
To make two Contract views match better, and to fix clutter and UI on pages, following changes have been agreed for banners and toolbars of the Contract view (PDF, annotations) page and Contract summary (metadata) page.

Both pages should use 3-row structure in current Summary (“Metadata”) page

A) For Contract View page:
1. Add new row to page structure and move document name from top row to second row
2. Move viewing tools (TEXT/PDF, page/scroll, zoom) to third row
3. Include global search in top right corner. Change text to “Search all documents”
4. Add “View Summary” button (same style as “View Document” button on Summary page) in second row. Use Metadata icon instead instead of eye icon
5. Change “Search in this document” to “Search in document”
6. Move Download and Share tools to third row, right side
7. Change site logo to match global site logo (correct font type, spacing, burger menu, etc.
8. Delete “View Summary” link`

B) For Contract Summary (Metadata) page:
1. Change Back button to match Back button on View page
2. Delete breadcrumb
3. Move global search to top right. Change text to “Search all documents”
4. Move Download and Share tools to right side to match View page

See images for guides.

![slide1](https://cloud.githubusercontent.com/assets/2153664/15382607/8fcdcbc8-1d40-11e6-8a00-83c0f92cb9b6.jpg)
![slide2](https://cloud.githubusercontent.com/assets/2153664/15382608/8fd04286-1d40-11e6-9e69-ce9e1b5a2e1b.jpg)

**Comment by upasna01** [comment]
The is fixed, please do verify.
http://rc-site-demo.elasticbeanstalk.com/rc/public/search?q=

http://rc-site-demo.elasticbeanstalk.com/rc/public/contract/ocds-591adf-PH6493643447RC/view
![889](https://cloud.githubusercontent.com/assets/11477899/16115753/ce0c1d04-33e8-11e6-8d8b-4ad5f3da7ba8.png)

**Comment by jedm** [comment]
About 6 of the 12 requested changes have not been made **(in bold below)** - please fix:

A) For Contract View page:
**1. Add new row to page structure and move document name from top row to second row**
2. Move viewing tools (TEXT/PDF, page/scroll, zoom) to third row
**3. Include global search in top right corner.** Change text to “Search all documents”
**4. Add “View Summary” button (same style as “View Document” button on Summary page) in second row. Use Metadata icon instead instead of eye icon _(see example above)_**
**5. Change “Search in this document” to “Search in document”**
6. Move Download and Share tools to third row, right side **see below**
7. Change site logo to match global site logo (correct font type, spacing, burger menu, etc.
**8. Delete “View Summary” link`**

B) For Contract Summary (Metadata) page:
1. Change Back button to match Back button on View page **see below**
2. Delete breadcrumb
**3. Move global search to top right.** Change text to “Search all documents”
4. Move Download and Share tools to right side to match View page **see below**

For Download and Share buttons, as noted in comp, move ABOVE THE RIGHT COLUMN (not flush with the PDF/page viewing tools. As noted in comp, add hairline separator - the same as between the left column and the viewing tools.

Back button must be the same fixed height as the row that the back button is in. It must not "float." Fix row height.

![screen shot 2016-06-16 at 10 08 20 am](https://cloud.githubusercontent.com/assets/2153664/16125885/9094a5b0-33aa-11e6-9120-66e39d51ad7c.png)

**Comment by hello-deepak** [comment]
Please review this issue [here](http://www.resourcecontracts.org/contract/ocds-591adf-IQ0025841408RC/view) .

**Comment by hello-deepak** [comment]
I think we can close this issue. Please create new issue if you find any .
