### ISSUE TITLE
Matching/Streamlining Icons - Download, Social Sharing

### ISSUE THREAD

**Issue by jedm** [NRGI/resourcecontracts.org#890]
**For download button:** Site has at least five (5) different buttons styles for download. Should be changed to only two (2) styles, as shown in attached image.

**For sharing icons:** 
1) Change social sharing buttons to function like the download button: One (1) icon with different options appearing in dropdown on click, as shown in attached image.
2) Sharing buttons must have simple instruction in HOVER TEXT – to be provided.
3) Email option is still missing from site – please add.

![slide3](https://cloud.githubusercontent.com/assets/2153664/15385229/f7281904-1d54-11e6-80b7-ce1b1d82d211.jpg)
![slide4](https://cloud.githubusercontent.com/assets/2153664/15385228/f7266564-1d54-11e6-9cd4-bbf87ee9fdde.jpg)

**Comment by jedm** [comment]
Relates to #889 re. Contract view and summary
Relates to #265 re. sharing buttons

**Comment by upasna01** [comment]
The issue is foxed now. Please do verify.
![890](https://cloud.githubusercontent.com/assets/11477899/16115374/50c17df0-33e6-11e6-9d96-0b0fcf7cd80b.png)
http://www.resourcecontracts.org

![890](https://cloud.githubusercontent.com/assets/11477899/16115401/6ff136fc-33e6-11e6-82a2-0a3aa0af4558.png)

http://www.resourcecontracts.org/contract/ocds-591adf-PE0065433224RC/view#

**Comment by jedm** [comment]
Buttons have not been standardized. They look different and text is different in several places. Full instructions in the images below.

![slide1](https://cloud.githubusercontent.com/assets/2153664/16137386/a7212884-33e7-11e6-9312-0fbbb176321d.jpg)
![slide2](https://cloud.githubusercontent.com/assets/2153664/16137387/a7218fc2-33e7-11e6-8ab3-4024f9c60110.jpg)
![slide3](https://cloud.githubusercontent.com/assets/2153664/16137388/a737c300-33e7-11e6-9022-4019c3d067e8.jpg)
![slide4](https://cloud.githubusercontent.com/assets/2153664/16137391/a738cb4c-33e7-11e6-8ba2-eeafe9100881.jpg)
![slide5](https://cloud.githubusercontent.com/assets/2153664/16137390/a738da88-33e7-11e6-8f4e-a1181a0d8043.jpg)
![slide6](https://cloud.githubusercontent.com/assets/2153664/16137389/a7388c18-33e7-11e6-93ac-b4eed33c868c.jpg)

**Comment by hello-deepak** [comment]
Please review this issue http://www.resourcecontracts.org/ .

**Comment by upasna01** [comment]
The issue s fixed, the arrow is removed and  consistency in alignment is maintained.
http://www.resourcecontracts.org/
