### ISSUE TITLE
Annotation box alignment issue

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#898]
An issue noted by the Philippines. 'When I move the annotation boxes to align, the  "Save" and "Cancel" buttons get behind the yellow box above, so I cannot click "Save." It just hangs. It happens when the boxes are close to each other. the "Save" button goes behind the other yellow box.'

![image](https://cloud.githubusercontent.com/assets/13888372/15603409/dac97f80-23fa-11e6-8b54-1b16db3b511f.png)

http://resourcecontracts.elasticbeanstalk.com/contract/91/annotate

**Comment by manishgs** [comment]
fixed.
