### ISSUE TITLE
Auto-fill feature issue

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#899]
An issue noted by the Philippines. 'Can we disable the auto-fill feature of the "Article Reference" in the Edit box? It causes the editing to hang.'

![image](https://cloud.githubusercontent.com/assets/13888372/15603485/4da3de10-23fb-11e6-8309-8866bedf3636.png)

**Comment by manishgs** [comment]
Could not understand what you mean here.

![screenshot-localhost 8000 2016-06-01 17-56-42](https://cloud.githubusercontent.com/assets/3942999/15709065/53b540ca-2822-11e6-819e-7b32b0782f3e.png)

Did you mean the editing of article reference in editor pop up box?

**Comment by charlesyoung** [comment]
Feedback from the client. 'The "Article Reference" remembers past inputs, so when I type "11" it shows all the past inputs with "11", such as 11, 11.1, 11.2.a, 11.4.c, etc. When the list gets so long, it hangs. I have to refresh the page. So some annotations have no article references, particularly "11" and sub-markings'.

**Comment by SamCCSI** [comment]
@manishgs when you type in "Art.", there are some auto fill options. Screenshot:

![image](https://cloud.githubusercontent.com/assets/12913915/15778714/eff6cf82-2965-11e6-95c0-6165cb640163.png)

However, they don't display all past article refs entered, so I'm not sure that the auto-complete is working properly. And if PH EITI are saying that it causes they annotation system to hang, then I agree it should be removed.

**Comment by manishgs** [comment]
Now autocomplete is turn off. Please review once.
