### ISSUE TITLE
Document upload workflow

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#9]
Process for getting documents into the system. Use something like a filehash system to see if document exists.

**Comment by anderspeders** [comment]
Rolled over to new sprint

**Comment by anjesh** [comment]
The process is as follows:

When the new contract is uploaded, the system checks the hash of the file against the hash field of contracts table (which stores the hash once it's uploaded to S3). 

If the file hash is present, the uploader should be in the same contract-create page and the following message to be shown
"The contract file is already present in our system. Please check the following <link to contract>Title of contract with which the uploaded file is linked</link> and make necessary updates."

If the file hash is not present in the system, the file is uploaded to the S3 and gets the file hash from the S3 and stores in the hash field of contracts table and show the just uploaded contract view page.
