### ISSUE TITLE
Change "contracts" to "documents" on search results page

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#902]
The tally circle should say "Documents," as it includes contracts + associated documents.

![image](https://cloud.githubusercontent.com/assets/12913915/15686376/f6a2bd16-273d-11e6-8f47-d1838cb8a887.png)

The only time it would be correct for it to say contracts is when a user designs a search term that only returns contracts. Eg:
![image](https://cloud.githubusercontent.com/assets/12913915/15686399/18ca3d42-273e-11e6-90b4-8b96a9c338ad.png)

**Comment by charlesyoung** [comment]
This will be great to implement. Tunisia questioned me this week on how we tally and display contracts and associated documents. We will have to ensure that none of the associated documents are recorded as 'Contract'.

**Comment by upasna01** [comment]
The issue is fixed please do verify.

http://www.resourcecontracts.org/search?q=

![902](https://cloud.githubusercontent.com/assets/11477899/16115477/f1c71214-33e6-11e6-9f95-2f152b320c1c.png)
