### ISSUE TITLE
OCR language support 

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#904]
Does the current OCR process support languages like Arabic, Mongolian and Chinese?

**Comment by manishgs** [comment]
I've uploaded Arabic and Chinese scanned and structured pdf. Below is the result.
 Arabic - Scanned - not supported [link](http://resourcecontracts-demo1.elasticbeanstalk.com/contract/1828)
 Arabic - Structured - not supported [link](http://resourcecontracts-demo1.elasticbeanstalk.com/contract/1827)
 Chinese - Scanned - not supported [link](http://resourcecontracts-demo1.elasticbeanstalk.com/contract/1826)
 Chinese - Structured - supported [link](http://resourcecontracts-demo1.elasticbeanstalk.com/contract/1825)

@SamCCSI

**Comment by charlesyoung** [comment]
@manishgs can you research the requirements needed to OCR Chinese and Arabic contracts? 

cc @anderspeders @anjesh

**Comment by charlesyoung** [comment]
Linked to ticket #938
