### ISSUE TITLE
System Arabic translation

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#906]
Although the translation focus must be on French below Google sheet has some Arabic translations that can be used to look at the complexity of the translation. 

https://docs.google.com/spreadsheets/d/1wVq4-6SX6W8Pk8Tyo87KuqZDhoxosCHzdtCvQkOWaQc/edit?usp=sharing

**Comment by charlesyoung** [comment]
Updated Arabic translations Google sheet. 

https://docs.google.com/spreadsheets/d/1nDS6PbpvC626mV03O-_c4gYNZ-aKBxoGP6FCbnXyHjs/edit?usp=sharing

**Comment by upasna01** [comment]
Some documents are added and require translations, also there are some additions in older documents which also requires translation, please update them.
https://docs.google.com/spreadsheets/d/1nDS6PbpvC626mV03O-_c4gYNZ-aKBxoGP6FCbnXyHjs/edit?ts=576220a8#gid=1829526709

**Comment by charlesyoung** [comment]
Updated Google sheet below. 

https://docs.google.com/spreadsheets/d/1nfBhSK4zA-8d72beDdNQnLTLVorCypDwobKDx0fpDrQ/edit?usp=sharing

**Comment by upasna01** [comment]
The [olc](https://docs.google.com/spreadsheets/d/1nfBhSK4zA-8d72beDdNQnLTLVorCypDwobKDx0fpDrQ/edit#gid=902308079) page is not updated yet, please update.

**Comment by charlesyoung** [comment]
Updated Google sheet below.

https://docs.google.com/spreadsheets/d/1AD8jPAlrR7uoHS2Gr7J6u_Uyozw-OA7e6eQa3QeCdmM/edit?usp=sharing

**Comment by rprajapatii** [comment]
@charlesyoung 

> Updated Google sheet below.
https://docs.google.com/spreadsheets/d/1AD8jPAlrR7uoHS2Gr7J6u_Uyozw-OA7e6eQa3QeCdmM/edit?usp=sharing

Please proivde me access to the above google spreadsheet.

**Comment by rprajapatii** [comment]
@charlesyoung 

> Updated Google sheet below.

https://docs.google.com/spreadsheets/d/1AD8jPAlrR7uoHS2Gr7J6u_Uyozw-OA7e6eQa3QeCdmM/edit?usp=sharing

We have updated arabic translation according to the google sheet. However, we need further insight on:

- to what extent the contents when translated in arabic language are legible.

- which type of content do we need to change to fit in arabic method of reading.

**Comment by anjesh** [comment]
@charlesyoung need someone to verify the text and site for Arabic http://tunisia.resourcecontracts.org/

**Comment by manishgs** [comment]
continue on this issue #1003
