### ISSUE TITLE
Tunisia public site transaltion

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#909]
Implement the French language support for the Tunisia public site.

**Comment by hello-deepak** [comment]
Here is the demo [link](http://rc-site-demo.elasticbeanstalk.com/tn/public/) for Tunisia public site .

**Comment by charlesyoung** [comment]
Thanks @hello-deepak. Couple of issues noted. 

The resource shows correctly (in French when viewing the site in French) in the admin site but not on the public site. 

![image](https://cloud.githubusercontent.com/assets/13888372/16009319/71466822-317c-11e6-827d-ded322d6b138.png)

The date is captured as 2006-01-12 in the admin site but isn't translated in the public site.  

![image](https://cloud.githubusercontent.com/assets/13888372/16009353/972d4fce-317c-11e6-80dc-2bdee41e24c5.png)

There are still some English references. 

![image](https://cloud.githubusercontent.com/assets/13888372/16009397/d1614218-317c-11e6-8b0a-9d80480f0ea1.png)

**Comment by upasna01** [comment]
The issue is fixed please do verify.

**Comment by charlesyoung** [comment]
Reopening, still translation issues as noted below. 

![image](https://cloud.githubusercontent.com/assets/13888372/16293415/01a782e4-391a-11e6-991f-ef01f30956a8.png)

![image](https://cloud.githubusercontent.com/assets/13888372/16293439/26224d66-391a-11e6-8943-571cdeb923c2.png)

**Comment by upasna01** [comment]
The issue is fixed for now, please verify.

http://rc-site-demo.elasticbeanstalk.com/tn/public/contract/ocds-591adf-TN3265676379RC?lang=fr

![909](https://cloud.githubusercontent.com/assets/11477899/16583915/6c67759a-42d8-11e6-8e5a-c44a5fd0bc13.png)
