### ISSUE TITLE
Bug: need to refresh page after adding each annotation

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#910]
From one of our annotators (who is using Google chrome):

_I have to refresh the contract each time after adding an annotation. I am unable to add annotations one after the other without doing that. Also, some of the annotations get saved but haven't been updated once I refresh. So I have to keep redoing the same annotations a few times before they get saved._ 

Here is the contract she was working on: http://resourcecontracts.elasticbeanstalk.com/contract/1755

**Comment by manishgs** [comment]
Fixed. 
@SamCCSI  Please review once.
