### ISSUE TITLE
Multiple repeated annotations categories in dropdown box

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#913]
Multiple annotations categories on both RC and OLC repeat in the dropdown box on the advanced search page - they are provided first in English and then in English/French. See screenshots for a few examples from OLC. Is this is a bug? Or an error introduced by either the internationalization process or by annotators? Let's please address this soon.

![screen shot 2016-06-15 at 8 48 09 pm](https://cloud.githubusercontent.com/assets/14825437/16103103/28e15acc-333b-11e6-871c-111d2bd776f4.png)
![screen shot 2016-06-15 at 8 48 33 pm](https://cloud.githubusercontent.com/assets/14825437/16103104/28e96d66-333b-11e6-8f1c-2a58a80f061d.png)
![screen shot 2016-06-15 at 8 48 47 pm](https://cloud.githubusercontent.com/assets/14825437/16103105/28f14ca2-333b-11e6-86c9-2a207f2d2c43.png)

**Comment by manishgs** [comment]
@KaitlinCCSI  

Fixed. Please review once.

**Comment by KaitlinCCSI** [comment]
Thanks, the repetition was fixed, but new errors have now been introduced. 

- "Legal Enterprise Identifier" and "Project Title" have both been added, but neither of them are annotation categories and so should be removed. (see screenshots)
- Similarly, "Annexes missing" is not an annotation category, and rather is meant to be shown in the righthand metadata column as discussed in #918 . 
- "Pages missing from copy" is also supposed to be a metadata category rather than annotation category. 
- "Name of field, block, deposit or site" is only relevant for RC and isn't supposed to show up on OLC -- it appears even though no documents have been annotated with that category.

I'm concerned by these changes in the list of annotation categories, as it's possible that I have not found all of the new errors that have been introduced. Do you know why these errors happened?

![screen shot 2016-06-27 at 1 25 55 pm](https://cloud.githubusercontent.com/assets/14825437/16390983/b89eb316-3c6a-11e6-8461-1fe7703fd4c6.png)

![screen shot 2016-06-27 at 12 00 49 pm](https://cloud.githubusercontent.com/assets/14825437/16390841/40bf18c2-3c6a-11e6-8555-16edd5d59064.png)
![screen shot 2016-06-27 at 12 00 28 pm](https://cloud.githubusercontent.com/assets/14825437/16390842/40c4bf70-3c6a-11e6-8826-5554cf8c0236.png)

**Comment by manishgs** [comment]
@KaitlinCCSI 
Following are all annotation categories.  I don't think its an error.  You can check [here](http://admin.resourcecontracts.org/quality)  for no. of contracts that have been annotated with these categories.
- Legal Enterprise Identifier
- Project Title
- Annexes missing
- Pages missing from copy
- Name of field, block, deposit or site.


For removing these annotation categories we need to discuss.
@SamCCSI @anderspeders  Let me know your thoughts.

**Comment by SamCCSI** [comment]
- Legal Enterprise Identifier — Also a metadata category so the annotation category can be deleted.
- Annexes missing — Also a metadata category so the annotation category can be deleted.
- Pages missing from copy — Also a metadata category so the annotation category can be deleted.
- Name of field, block, deposit or site — Not supposed to show up on OLC

Can you please prohibit users from entering annotations on the following annotation categories? These are headings, not categories, so should be greyed out if possible.
- I. General information
- II. Summary of terms
- 1. Fundamental provisions
- 2. Community and social obligations
- 3. Developers financial obligations
- 4. Environmental Provisions
- 5. Operational Provisions
- 6. Miscellaneous provisions
- III. Document Notes

There are also zero annotations for "Company website". I suggest this category also be removed.

**Comment by manishgs** [comment]
- We can safely remove 'Annexes missing'  and  'Pages missing from copy' annotation category as they are not in used.

- "Legal Enterprise Identifier" is used in 27 contracts and "Name of field, block, deposit or site"  is used in 156 (including OLC contracts) so provide us the alternative category to replace with the category.

- "I. General information" is used 2 contracts so please update the category in these contracts.

@SamCCSI @anderspeders

**Comment by manishgs** [comment]
@SamCCSI  

> Can you please prohibit users from entering annotations on the following annotation categories? These are headings, not categories, so should be greyed out if possible.
I. General information
II. Summary of terms
1. Fundamental provisions
2. Community and social obligations
3. Developers financial obligations
4. Environmental Provisions
5. Operational Provisions
6. Miscellaneous provisions
III. Document Notes

There is already restriction on selecting Category Headings.

![screenshot-admin resourcecontracts org 2016-08-09 10-12-07](https://cloud.githubusercontent.com/assets/3942999/17504569/e199bc04-5e19-11e6-98be-e14a8aed04f4.png)


Category "Annexes missing' , "Legal Enterprise Identifier",  and "Name of field, block, deposit or site"
 are being used in contracts so we can't remove these categories. Please change the category from  annotations and let us know when you done.

Category "I. General information" is also used in 2 contracts so please update the annotations.

Here is the [link](http://admin.resourcecontracts.org/quality) for the stats

 Let us know if you need any help from us.

cc. @anderspeders

**Comment by anjesh** [comment]
Can you please get back to us on this soon, otherwise we will move this to sprint 18. @anderspeders @SamCCSI

**Comment by SamCCSI** [comment]
Hi @anjesh and @manishgs 

1. Can you grey out these categories while we sort them out so that no more annotation entries for them are added?

- [ ] Legal Enterprise Identifier
- [ ] Annexes missing


2. Is there a way for you to automatically transfer any annotation entry for  "Annexes missing" to the corresponding metadata entry — **Is Annex(es) Missing From Document (metadata field) = Yes** http://admin.resourcecontracts.org/contract?type=annotations&word=annexes-missing-from-copy&issue=present

3. **Pages missing from copy** has zero entries and can be deleted.

4. We will report back on Legal Enterprise Identifier.

Thanks!

**Comment by manishgs** [comment]
@SamCCSI 
1. Category Legal Enterprise Identifier and Annexes missing from copy are disabled in dropdown.
2 Except [this contract ](http://admin.resourcecontracts.org/contract/758)all contracts have Is Annex(es) Missing From Document = Yes, you can update this contract manually.
3. Pages missing from copy removed from the category list.

**Comment by SamCCSI** [comment]
2. Done.

Many thanks Manish.

**Comment by charlesyoung** [comment]
@SamCCSI can we close this ticket?

**Comment by SamCCSI** [comment]
Thanks. Will re-open if we have other requests.
