### ISSUE TITLE
Social media link

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#914]
The social media links, only on the country sites and not on the generic site, are permanently displayed and cannot be 'switched off'. 

![image](https://cloud.githubusercontent.com/assets/13888372/16142317/8dcfb878-3464-11e6-942a-6f5582bc88be.png)

**Comment by upasna01** [comment]
Please specify where did you find the error.

**Comment by charlesyoung** [comment]
http://rc-site-demo.elasticbeanstalk.com/tn/public/contract/ocds-591adf-TN2341011931RC/view

**Comment by upasna01** [comment]
The issue is fixed now, please do verify.
