### ISSUE TITLE
Metadata column 

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#918]
When a contract is marked as having annexe(s) missing from the document, this appears in the metadata column above the Land Matrix ID, without being separated as a horizontal line. 

It should be separated by a line, as with all other items in the metadata column. Please see [this](http://www.openlandcontracts.org/contract/ocds-591adf-CD8532419488OL/view) contract as an example (and screenshot below). 

Many thanks. 

![screenshot 2016-06-21 17 51 29](https://cloud.githubusercontent.com/assets/14910764/16247717/20bfaf04-37d9-11e6-922f-872c0cd0a5b3.png)

**Comment by SamCCSI** [comment]
Can we also change this to the US spelling - '*Annex(es)'* rather than '
Annexe(s)'.

**Comment by hello-deepak** [comment]
Fixed .
![openlandcontracts org drc trans m contrat de concession forestiere n 009 11 secteur lomako 4 aout 2011](https://cloud.githubusercontent.com/assets/7577697/16558236/eadc7aae-4203-11e6-954a-dc480817b666.png)
