### ISSUE TITLE
Tracking changes made to a contract upload

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#92]
As an annotator or admin, it would be useful to be able to see a log of who uploaded/edited/finalized the document, metadata and annotations, and when.

Something like the feature on google docs or on Dropbox events page, that tracks if you edited, added, saved, or deleted a document.

**Comment by anjesh** [comment]
All the activity logs will be maintained. There will be a menu which lists all the activities happening in the portal, with option to filter by contract and user.
![image](https://cloud.githubusercontent.com/assets/120488/8446712/3f4c1ff8-1fce-11e5-8c60-7751053b77bf.png)

There will also be link in the contract page, which will take to the filtered log page. 
![image](https://cloud.githubusercontent.com/assets/120488/8446714/43c8a4a2-1fce-11e5-8077-fa3740eb4bbb.png)

**Comment by anderspeders** [comment]
This looks really good to me,

At some point we also enable administrators to have an overview of contracts <published>, <loaded> or <edited> the last <30 days>, <6 months> and <year>.
