### ISSUE TITLE
Lost annotations and "you are not allowed to search this" error/bug

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#921]
From an annotator:

After almost finalizing the annotations for Syria-Sudan, the last dozen of them has disappeared and I received the notifications "sorry, you are not allowed to search this" (see attached). I disconnected and reconnected to the website and it seems to work alright again, but I wanted to notify it in case it can lead to improvement of the website -- I assume my session was somehow terminated, which is strange because I was really just keeping working on it, but in that case I think it would be great to receive a notification right away so we don't continue to enter/modify annotations that will be lost for so long before receiving that kind of flagging. 

![image](https://cloud.githubusercontent.com/assets/12913915/16347066/b0550e02-3a18-11e6-9171-6186ac881858.png)

**Comment by manishgs** [comment]
@SamCCSI 

> ... "sorry, you are not allowed to search this" (see attached). I disconnected and reconnected to the website and it seems to work alright again, ....

Today I encounter the same issue. I notice that when I browse subsite, the admin session has been terminated and logged out from the admin site. 

We need to fix the session issue and token mismatch issue.

**Comment by anjesh** [comment]
This could also happen during deployment when the sessions get flushed for any logged-in users. If this is recurrent, then we will think of different mechanism to handle the user session so that such issues could be avoided in future. Please let us know if you again get such issue.

**Comment by charlesyoung** [comment]
@SamCCSI can we close this ticket?

**Comment by SamCCSI** [comment]
Will re-open if problem presents itself again.
