### ISSUE TITLE
Adding new resource categories  

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#922]
We added "field crops" as a new resource for [this](http://www.openlandcontracts.org/contract/ocds-591adf-ET6391091833OL/view) contract. However: 

1. The resource does not appear in the metadata column; 
2. On the summary page, when you click on "Field Crops", an error appears (screenshot below); 

If you could look in to this, that would be very helpful. 

![field crops](https://cloud.githubusercontent.com/assets/14910764/16347215/802b2fee-3a19-11e6-9a71-e4a50d9d3715.jpg)

**Comment by hello-deepak** [comment]
This issue is fixed . Please do review.
