### ISSUE TITLE
Bug: Searching from contract view page

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#923]
Relating to changes in this thread https://github.com/NRGI/resourcecontracts.org/issues/895

One bug that needs fixing:

When I am viewing a contract and then click on the search pane, the advanced search features appear.

However, I cannot "click out" of this. 

Please change so that if the user makes the search options appear but then clicks back on the contract view page (anywhere but on the search window itself), the search window disappears.

![image](https://cloud.githubusercontent.com/assets/12913915/16419672/9169c350-3d1c-11e6-8a7f-09eaa1ba6211.png)

**Comment by manishgs** [comment]
There is "Cancel" button on advance search to close search pane .Do you still think we need to add this feature as well, please confirm ? @SamCCSI @jedm @anderspeders

**Comment by jedm** [comment]
I think the appearance of advanced search on click is confusing and Sam is correct that it gets in the way and that removing it is difficult. 

I suggest changing "Cancel" to "Hide." 

I also suggest making the Hide  button look different than the Search and Reset buttons and perhaps moving it to the corner.  Those buttons are for search operations and the Hide button is for the pop up, so it is confusing that they look the same.

**Comment by SamCCSI** [comment]
@jedm 's proposed changes sound great. Given these, we are happy to park the "click out" request for now.

**Comment by charlesyoung** [comment]
@rprajapatii I'm just following up on the suggestions made by @jedm re changing the "Cancel" button to "Hide". There was also a suggestion of making the "Hide" button look different to the Search and Reset buttons.

**Comment by hello-deepak** [comment]
Button is renamed from cancel to hide and "click out " feature has been also done .
![hidebutton](https://cloud.githubusercontent.com/assets/7577697/18871013/2785dda8-84d3-11e6-9810-2664eda7e25b.png)

**Comment by jedm** [comment]
Deepak please see #973 for more recent requests regarding this function. Thank you.

**Comment by anjesh** [comment]
the remaining will be dealt in #973. I think this is good to close.
