### ISSUE TITLE
getting contract/attributes issue

### ISSUE THREAD

**Issue by magnaibayar** [NRGI/resourcecontracts.org#924]
Hello. Im working with frontend API and I have some problem about getting contract attributes. 
I have 2 contract and 2 company. The companies name are : "Epotecmass", "CC Mongolia".
But attributes gives me: "Epotecmass", "CC", "Mongolia"
And contract types same too..

Please, help me..

**Comment by manishgs** [comment]
Its related to API. So will answer on API repository.
