### ISSUE TITLE
Dockerization of full platform

### ISSUE THREAD

**Issue by byndcivilization** [NRGI/resourcecontracts.org#926]
All pieces of platform (except for database and maybe elasticsearch) need to be fully dockerized. This means that env variables and configs  should be set at run time letting containers be completely stateless. YI should not need access to NRGIs AWS account to make this happen.

Instead we should move to the existing continuous deployment methodology of NRGI:
- push staging and production code to github
- webhook integration that triggers a quick build and test of docker images on travis.ci for immediate feedback for all branches
- webhook integration that triggers build --> test --> build image/push to docker hub
- automated nightly or weekly or pulls of of fresh images and redeployment of application components (current NRGI methodolgy deploys docker images on Marathon and does automation with Chronos)

**Comment by anjesh** [comment]
Complete and tested as a part of deployment workflow
