### ISSUE TITLE
Urgent - Annotation hovers don't link to full annotation

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#928]
When I hover over an annotation, there is no longer a hyperlink to take me to the full annotation listing on the left hand side. This used to be a hyperlinked ">>".

This means that users can't easily read more than two lines of an annotation when they are browsing the document page by page.

We are teaching using the site this week. If this could be fixed urgently we would greatly appreciate it.

Example: http://www.resourcecontracts.org/contract/ocds-591adf-PH6493643447RC/view#/pdf/page/11/annotation/1178
![image](https://cloud.githubusercontent.com/assets/12913915/16584920/34a05538-428c-11e6-848e-fdeb81be35f1.png)

**Comment by manishgs** [comment]
link added. Please review once.

**Comment by SamCCSI** [comment]
Looks good, thanks.
