### ISSUE TITLE
Annotation back-end: pages take long time to load

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#929]
There seems to be issues with the loading time of the contract pages when adding annotations. Can this be investigated?

From an annotator who is adding annotations that were already drafted by another researcher:

These annotations are taking very long to do—over an hour—due to the time the pages take to load while navigating through the contract.  The actual annotations themselves probably take 20 minutes, but the wait in-between each is long.  It seems like the more annotations have been entered, the more it slows down.  Additionally, the boxes are always moving elsewhere other than where I placed them and checked the green checkmark, forcing me to repeat that action a few times--also probably related to the slowness.  I wondered if you have this issue too.  If I am just working on a slow internet connection, I will try a few at school next week to see if the page loading time improves.

**Comment by anjesh** [comment]
we haven't had such issue taking long time to load the page. Let us know if you come across such issues in other places. We are also refactoring the js code and that might help fast loading. Keep us updated. We will also let you know when we update the refactored code.

**Comment by charlesyoung** [comment]
@anjesh are we looking at this issue as part of another ticket?

**Comment by anjesh** [comment]
Some aspects (with regards to fast loading) of this particular issue is handled during code refactoring. Not sure if this issue still exists. @SamCCSI might have more to add here such cases are again appearing or not.

**Comment by SamCCSI** [comment]
No additional cases reported to me, so not sure this needs to be prioritized.

**Comment by charlesyoung** [comment]
Will close this ticket, please reopen if required.
