### ISSUE TITLE
Docker roll out

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#93]
As discussed today in slack a Docker roll out will be scheduled for sprint 3. 

cc @anjesh @byndcivilization

**Comment by anjesh** [comment]
Currently the deployment scripts are made ready as per #97 
Docker still need more time

**Comment by anderspeders** [comment]
@anjesh can you update the status here and flag if you need any actions from me or @byndcivilization?

**Comment by anjesh** [comment]
Prepared the working dockerfile for resourcecontracts https://github.com/younginnovations/docker-resourcecontracts.org/
Now need to write similar for elasticsearch, API and subsite. Will continue to next sprint.

**Comment by byndcivilization** [comment]
I'm pushing this as a must for sprint 10.

**Comment by byndcivilization** [comment]
Core design should be a multi container linked deployment using (docker compose)[https://docs.docker.com/compose/] for core stack and a single container for front end site.

**Comment by anderspeders** [comment]
Have we pushed this to post-RC launch @byndcivilization @anjesh ?
