### ISSUE TITLE
Error when downloading word doc from backend

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#931]
I wanted to download a word version of this unpublished document on NRGI's request: http://resourcecontracts.elasticbeanstalk.com/contract/1962

When I clicked Download / Word, I got this error message

http://resourcecontracts.elasticbeanstalk.com/contract/1962/download
Sorry, the page you are looking for could not be found.

**Comment by hello-deepak** [comment]
While creating the contract, the name of text file was not being updated in s3 after completion of extraction process of text from pdf which is fixed now.
