### ISSUE TITLE
Elasticsearch fuzzy matching in Advanced Search/ Text Search

### ISSUE THREAD

**Issue by hello-deepak** [NRGI/resourcecontracts.org#932]
Dealing with typos and spelling mistake while searching.

Implement fuzzy matching in 
- [x] Advanced Search
- [x] Text Search

**Comment by JesseCCSI** [comment]
Thanks @hello-deepak  just to also confirm that the following points from Sam's original comment #823 will be addressed: 

1. Text search (of annotations) should include the text of annotation **titles** as well.
2. Fuzzy searching should pick up that "expropriate" and "expropriation" are related terms, and return results that include both of those words.

cc @SamCCSI

**Comment by hello-deepak** [comment]
Please review the fuzzy matching in [demo site ](http://rc-site-demo.elasticbeanstalk.com/rc/public/).

Here is [wiki](https://github.com/NRGI/resourcecontracts.org/wiki/Fuzzy-Matching-in-Advanced-Search) link for fuzzy search in advance search page .

**Comment by SamCCSI** [comment]
From a quick review this is working nicely.

Eg "Stablization" also searches for "Stab**i**lization"; "expropriate" picks up "expropriated", "expropriation" and "exprop**n**ate"

**Comment by hello-deepak** [comment]
@SamCCSI @charlesyoung 

Can we have confirmation here, to deploy on live site if it is okay .

**Comment by SamCCSI** [comment]
Ok to deploy subject to @charlesyoung 's thoughts.

**Comment by charlesyoung** [comment]
Happy to deploy. 

cc @SamCCSI

**Comment by manishgs** [comment]
deployed on live.

**Comment by JesseCCSI** [comment]
Hi all - it looks like free text searches aren't picking up annotation titles (as requested above) - not sure if this is a bug, or if changes discussed above haven't been fully deployed? 

See e.g. screenshot below - that contract has a "stabilization" annotation, but searching for "stabilization" gives 0 results. 

![image](https://cloud.githubusercontent.com/assets/14910764/24356193/f9def510-12c6-11e7-8be1-9aedbd4b93ff.png)

![image](https://cloud.githubusercontent.com/assets/14910764/24356211/0e0d0112-12c7-11e7-86b0-bdbd70c57e63.png)

**Comment by charlesyoung** [comment]
@manishgs will you be able to look at this ticket today?

**Comment by charlesyoung** [comment]
@JesseCCSI can I close this ticket?

**Comment by SamCCSI** [comment]
@anjesh could your team please take a look at this issue? It's still unresolved. Happy for you to quote how long it should take to resolve. Many thanks.
