### ISSUE TITLE
Capitalizing Government Entity

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#933]
http://resourcecontracts.elasticbeanstalk.com/contract/1984

Our research associate tried to capitalize each letter of the following government entity, but the identifier disappeared. Is there a way for us to edit such entries in the back-end?

Government Entity: sociedade nacional de combustiveis de angola 
Government Identifier: dc2fd95c-cd21-4571-adca-3ab3ab80aae1

**Comment by manishgs** [comment]
Government Entity and Identifier are pulled from joinedupdata.org API. 
Here is the link for the list : http://joinedupdata.org/NRGI/4c61a3a0-8c34-4391-976d-4065f9d47340.html

We need to update on joinedupdata.org. Closing this issue because there is already discussion on this issue #786.
