### ISSUE TITLE
Annotations not published showing on generic RC site

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#935]
Contract annotations, like below, have not been published. 

http://resourcecontracts.elasticbeanstalk.com/contract/70
http://resourcecontracts.elasticbeanstalk.com/contract/74

But it shows on the generic RC site like below. 

http://www.resourcecontracts.org/contract/ocds-591adf-PH8329561979RC/view#/search/Johson%20Gold%20Mining%20Corporation%20-%20MPSA%20No.%20139-99-V%2C%201999
http://www.resourcecontracts.org/contract/ocds-591adf-PH0216420606RC/view#/pdf

The Johson Gold Mining contract also strangely opens in the text and not PDF version of the document.

**Comment by charlesyoung** [comment]
So if I just click on the contract hyperlink no annotations are shown. 

http://www.resourcecontracts.org/contract/ocds-591adf-PH8417537552RC/view

But if I search for the same contract some of the annotations, based on the search, are shown. 

http://www.resourcecontracts.org/contract/ocds-591adf-PH8417537552RC/view#/search/CTP%20Construction%20and%20Mining%20Corporation%20-%20MPSA%20No.%20158-2000-XIII%20%28Surigao%20Mineral%20Reservation%29%2C%202000

**Comment by manishgs** [comment]
> http://www.resourcecontracts.org/contract/ocds-591adf-PH8417537552RC/view#/search/CTP%20Construction%20and%20Mining%20Corporation%20-%20MPSA%20No.%20158-2000-XIII%20%28Surigao%20Mineral%20Reservation%29%2C%202000

I think you are confuse with search result list . This hyperlink showing the search result which are only text search not the contract annotations. You can refer to this issue #888 for detail,

 > http://resourcecontracts.elasticbeanstalk.com/contract/74
There are 38 Annotations in backend but 36 Annotations in frontend. Contract annotations are already published earlier (36 annotations published) but later 2 annotations were added so status changed to draft.

There are confusions in current publishing workflow so we'll address this issue in #778 

Let us know If you have any confusions.

**Comment by manishgs** [comment]
Please comment on issue #778 if you have any issue regarding publishing workflow.
