### ISSUE TITLE
OCR text not processing (since Thursday July 14)

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#936]
Is there a problem with the automatic OCR process? None of the contracts added over the past couple of days have text info.

**Comment by SamCCSI** [comment]
We have also had this problem.

**Comment by SamCCSI** [comment]
Examples: 
http://resourcecontracts.elasticbeanstalk.com/contract/1992
http://resourcecontracts.elasticbeanstalk.com/contract/1994
http://resourcecontracts.elasticbeanstalk.com/contract/1997
http://resourcecontracts.elasticbeanstalk.com/contract/1999
http://resourcecontracts.elasticbeanstalk.com/contract/2002

All have status of processing or pipeline.

**Comment by SamCCSI** [comment]
Prioritizing this as this problem is interfering with out ability to get back to you for other issues — eg. #871

**Comment by manishgs** [comment]
Today we Investigated and found that there was a problem in abbyy processing. Abbyy returned incomplete OCR Text (We repeated the abbyy ocr process multiple times and found this issue on random pdf pages) so contract OCR process could not be completed for contract id - 1992  and queue process remain hung therefore other contract could not be processed. 

We have manually run the document ocr processing for contracts which are structured pdf.

**Comment by SamCCSI** [comment]
Thanks Manish.

What is the proposed solution for contract 1992?

**Comment by anjesh** [comment]
We will have to do that manually for the time being and yet manual processing (without sending to the queues) won't guarantee the full processing of the contracts as the Abbyy OCR service seems to have problem. We have posted an issue in the abbyy forum http://forum.ocrsdk.com/questions/5896/inconsistent-response-from-the-api and others also seem to have the same problem. We are waiting from Abbyy to get back on the issue.

**Comment by SamCCSI** [comment]
Thanks @anjesh.

**Comment by SamCCSI** [comment]
Two more contracts not showing the PDF / text. For status, one says "Processing" and one says "Pipeline"

http://resourcecontracts.elasticbeanstalk.com/contract/2020
http://resourcecontracts.elasticbeanstalk.com/contract/2114

**Comment by charlesyoung** [comment]
In the backend this [contract ](http://resourcecontracts.elasticbeanstalk.com/contract/2021) is still processing with nothing published while on the [frontend ](http://www.resourcecontracts.org/contract/ocds-591adf-TN6660152406RC) the metadata is displayed. 

So 2 issues; the processing problem and metadata displayed on the public site without being published.

**Comment by charlesyoung** [comment]
One more

http://resourcecontracts.elasticbeanstalk.com/contract/2015

**Comment by manishgs** [comment]
Following contracts were on processing status, we've re-run the OCR processing. PDF text of these contracts are not published so please review the contract text and publish them.
1996
2046
2042
2028
2106
2048
2023
2021
2018
2015
2002
