### ISSUE TITLE
Contract backend not displaying all metadata fields

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#937]
Currently, come metadata fields are not displayed on the contract backend. For instance "Year of signature" is missing. This makes it harder to review entries (without having to click on "edit"). For instances where no date is entered but only a year (as occurs in some model contracts) it would be helpful to be able to see the year without clicking "edit".

![image](https://cloud.githubusercontent.com/assets/12913915/17024297/687e95d6-4f25-11e6-880c-27dcf28a7b58.png)

**Comment by manishgs** [comment]
Signature year has been added and order the metadata display according to contract add/edit form.

**Comment by SamCCSI** [comment]
In the edit form, can you please move Show PDF Text to the top, so that it corresponds to where it is located on the backend contract page?

Contract back-end page: it's at the top: 
![image](https://cloud.githubusercontent.com/assets/12913915/18130444/239f86e8-6f5d-11e6-96c5-c5afdce9fcf6.png)

Edit form: it's at the bottom 
![image](https://cloud.githubusercontent.com/assets/12913915/18130455/2ac00de4-6f5d-11e6-8d49-e07437db6969.png)

**Comment by manishgs** [comment]
"Show PDF Text "  field will be removed from edit form and contract detail page after implementing new publishing workflow #778.

**Comment by manishgs** [comment]
Please check the design [here](http://resourcecontracts-demo1.elasticbeanstalk.com/contract/1993)

**Comment by charlesyoung** [comment]
@SamCCSI please check.

**Comment by SamCCSI** [comment]
Thanks, looks good. I will re-open if I discover any other discrepancies.
