### ISSUE TITLE
Verify the working of the french accent characters in OCR process.

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#938]
There are number of cases where the accents are not properly OCRed. Need to verify the OCR process whether it's the OCR issue or if it's something that could be fixed from the code.

**Comment by charlesyoung** [comment]
@anjesh just to confirm that the OCR process relating to above has been modified and will be implemented to the Production site by early next week. 

cc @SamCCSI

**Comment by charlesyoung** [comment]
@anjesh has this been implemented on the Production site?

**Comment by charlesyoung** [comment]
@anjesh can this be deployed on the Production site before we import the new Tunisia contracts as it will improve the OCR'ed text quality?

**Comment by charlesyoung** [comment]
The OCR service has been updated and deployed on the Production site. 

1. PDF contract text 

![image](https://cloud.githubusercontent.com/assets/13888372/18052125/cfa21f66-6df8-11e6-9977-0a137d6218ef.png)

2. Previous OCR text output

![image](https://cloud.githubusercontent.com/assets/13888372/18052139/e7f40aa2-6df8-11e6-993a-f385ec3c46a0.png)

3. Updated OCR text output

![image](https://cloud.githubusercontent.com/assets/13888372/18052154/01ee5fb6-6df9-11e6-8147-a6fda927467a.png)

cc @SamCCSI

**Comment by charlesyoung** [comment]
Add Arabic and Portuguese OCR processing functionality.

**Comment by manishgs** [comment]
Arabic and Portuguese OCR proccessing has been added. Please [ check here ](http://admin.resourcecontracts.org/contract/2330/review)for arabic OCR text

**Comment by charlesyoung** [comment]
Arabic OCR checked, by Tunisia NRGI country officer, and looks good.
