### ISSUE TITLE
Contracts not loading on frontend

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#939]
They seem to just sit for minutes without any of the elements on the vontract page loading

![image](https://cloud.githubusercontent.com/assets/12913915/17070938/b661ef34-502c-11e6-84a8-3e6893ca88c5.png)

**Comment by hello-deepak** [comment]
@SamCCSI 
It's working perfectly fine in my machine.

Are you using some kind of adblock extension in your browser. If you are doing so , you need to disable it. Because it blocks your XMLHttpRequest from your browser, which means your browser is not able to call API.

**Comment by hello-deepak** [comment]
@SamCCSI 
It's working perfectly fine in my machine.

Are you using some kind of adblock extension in your browser. If you are doing so , you need to disable it. Because it blocks your XMLHttpRequest from your browser, which means your browser is not able to call API.

**Comment by SamCCSI** [comment]
Thanks @hello-deepak, all sorted now.
