### ISSUE TITLE
'Grouping' of related contracts

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#94]
As a user it would be useful to see when a contract is part of a 'web' or 'group' of contracts, or has other contracts that are related to it.

For instance: 
Main contract = Concession Agreement
Related contracts = community development agreement relating to the same concession, translated versions of the main contract, etc.

**Comment by anjesh** [comment]
This should be handled with https://github.com/NRGI/resourcecontracts.org/issues/38 and https://github.com/NRGI/resourcecontracts.org/issues/122

Need some real world examples to see how this appears in practice. @anderspeders any examples you could point to?

**Comment by anderspeders** [comment]
Yes, we have an issue for this: #111

**Comment by anjesh** [comment]
Covered in #111. Closing.
