### ISSUE TITLE
Disclosure mode - free text option

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#940]
When stating how the contract was disclosed, we sometimes need to add more information for government- or company-disclosed contracts.

Please add a non-mandatory free text field below disclosure mode. There is a free text field when we select other. We want to have a free text field no matter which disclosure mode we can suggest.

Example: Ethiopian contracts disclosed by government in Amharic. We have them professionally translated. Disclosure mode should be "Government" + Free text: "unofficial translation".

**Comment by manishgs** [comment]
Free text input added on RC Admin.

Disclosure mode on contract view page:
![screenshot-www resourcecontracts org 2016-10-03 15-12-36](https://cloud.githubusercontent.com/assets/3942999/19033336/a19381fa-897d-11e6-97c7-20c6f8428c58.png)


On contract summary page
![screenshot-www resourcecontracts org 2016-10-03 15-13-36](https://cloud.githubusercontent.com/assets/3942999/19033340/a3eeac72-897d-11e6-8ba6-424e49e16ca0.png)

**Comment by SamCCSI** [comment]
Thanks @manishgs . A couple of questions:

1 - It won't say "Other mode" whenever we select "Other" will it? We want it to just display what we write in the free text field.

2 - see image below. Why is there a free text field (1) and a disclosure mode text (2)? 2 seems to be obsolete.

![image](https://cloud.githubusercontent.com/assets/12913915/19092578/53e13622-8a55-11e6-91a1-7c42ccea5355.png)

**Comment by manishgs** [comment]
1

>  - It won't say "Other mode" whenever we select "Other" will it? We want it to just display what we write in the free text field.

I selected "Other"  from dropdown and enter "Other mode"  in free text so it won't display "Other mode". You have enter manually.

2
 
> Example: Ethiopian contracts disclosed by government in Amharic. We have them professionally translated. Disclosure mode should be "Government" + Free text: "unofficial translation".

From above  example, what we understand is when  "Government " is selected, there should be free text. So we added new Disclosure Mode  Text input. 

I think in case of "Other" we need to hide new "Disclosure Mode Text" field.

@SamCCSI 
What do you think?

**Comment by SamCCSI** [comment]
1. Perfect, thanks @manishgs 

2. You can leave both for now; I understand what purpose each field has, and we will develop guidance for users so that they use the correct one. Many thanks!

cc @jesseccsi @KaitlinCCSI
