### ISSUE TITLE
Sierra Leone country subsite standardization

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#941]
Standardize the Sierra Leone country subsite:
1. Don't show the searching menu initially
2. Include all the searching parameters like document type
3. Change contracts to documents 
4. etc

Please ensure that the entire site is standardized.  

![image](https://cloud.githubusercontent.com/assets/13888372/17203701/36b49e52-54a1-11e6-9965-76ebb4eab443.png)

**Comment by manishgs** [comment]
Sierra Leone country subsite has been updated. Please review once.
