### ISSUE TITLE
Add geo-data metadata in the Admin interface

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#942]
This issue is for capturing geo-data in the admin interface only, but we need to add some clarity on how we want to display the data in the front end sites. Once we have the questions answered below, we can start working on this. 
## Process

There will be a separate page to capture the geo data. Once the contract is created, then there will be a link from where the uploader may add location info and coordinates. The following location information will be captured as per [comment here](https://github.com/NRGI/resourcecontracts.org/issues/447#issuecomment-164507588) 
#### Location Information
- Country ADM1 (Already captured)
- Region
- Locality

The region and locality might not be available for all the countries. If available, they will be provided in list, otherwise the uploader will be able to add free-text in both the fields. 
#### Coordinates information
- Area name
- Latitude (degree, minute, second, direction)
- Longitude (degree, minute, second, direction)

**Validation of latitude and longitude**

As explained [here](https://msdn.microsoft.com/en-us/library/aa578799.aspx), 

> Latitude measures how far north or south of the equator a place is located. The equator is situated at 0°, the North Pole at 90° north (or 90°, because a positive latitude implies north), and the South Pole at 90° south (or –90°). Latitude measurements range from 0° to (+/–)90°.
> 
> Longitude measures how far east or west of the prime meridian a place is located. The prime meridian runs through Greenwich, England. Longitude measurements range from 0° to (+/–)180°.

We could use one of the followings for direction (plus/minus or N/S/E/W)

> Degrees/minutes/seconds and N/S/E/W—Latitude and longitude are represented as degrees, minutes, and seconds, followed by a letter indicating the direction from the equator or prime meridian. Minutes and seconds are fractions of a degree: Each minute is one-sixtieth of a degree, and each second is one-sixtieth of a minute; for example, 37º41'26"N 97º20'0"W.
> 
> Degrees/minutes/seconds and Plus/minus—Latitude and longitude are represented as degrees/minutes/seconds and preceded by a minus sign if south of the equator or west of the prime meridian; for example, 37º41'26" –97º20'0".

See an [online coordinates converter here](http://www.sunearthtools.com/dp/tools/conversion.php)
## Questions:

@anderspeders @charlesyoung need your thoughts/feedbacks on the followings.
#### Are the above metadata for coordinates data enough?

Do we need to capture the area as well? See the [sample contract location data](https://cloud.githubusercontent.com/assets/1101585/8641114/85655d3a-28dc-11e5-92eb-bc354a7c1af3.PNG) to see the area being mentioned.
#### Is it ok to capture degree minute second instead of decimals?

 Are there instances where only decimals are captured instead of degree. This [sample contract location data](https://cloud.githubusercontent.com/assets/1101585/8641114/85655d3a-28dc-11e5-92eb-bc354a7c1af3.PNG) has both. If there's only decimals, the uploader will have to convert to degree/minutes/seconds themselves using online converter. Or we could provide the converter or we could also have the option to toggle between the two (decimal vs degree). This will add extra effort. 
#### How are we planning to use the captured geo data (use-cases)?

If we only need to show the point of contract, we could geocode the region->locality to get the coordinates to show the location of contract. Coordinates might be redundant in this case if we don't have any use case of the coordinates. We can show the exact polygons when viewing contract. Just wondering if there are any use-case of the polygon data. This is for the front end display of the coordinates. 
#### How does it affect the associated document?

Please explain how does the geo data capture and display process works in case of associated documents. There are number of confusions here. Once we capture the geo code for primary contract, will there be instances of such geo data in associated documents as well. This will be tricky as it might not reflect the true number of contracts in the map. However we can ensure that only primary contracts are considered when showing the points in the map and ignore the location data of associated documents, if uploader captures the data there.

**Comment by charlesyoung** [comment]
@anjesh many thanks for this. Can I suggest a Skype call next week to discuss in more detail? I will update the ticket subsequent to the call. 

cc @anderspeders

**Comment by charlesyoung** [comment]
Requirement location information split from the requirement coordinates information.
