### ISSUE TITLE
 'Jurisdiction of Incorporation' should list all the countries for Country users [Backend]

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#944]
Sierra Leone RC country users can only select Sierra Leone from the 'Jurisdiction of Incorporation' drop-down list (Admin interface) with no other countries listed.

**Comment by charlesyoung** [comment]
@anjesh can you please take a look at this issue? Thanks

**Comment by manishgs** [comment]
@charlesyoung  
Country user can select only their own country from country dropdown.  They can't choose other country so we are hiding other countries.  In the case of Sierra Leone country subsite, user can only allow to choose  'Sierra Leone' country.

Let us know if there is any confusion.

cc. @anderspeders

**Comment by charlesyoung** [comment]
Its not the country drop-down but the Jurisdiction of Incorporation drop-down.

**Comment by manishgs** [comment]
Fixed.
