### ISSUE TITLE
Language controller on demo site

### ISSUE THREAD

**Issue by jedm** [NRGI/resourcecontracts.org#945]
Please confirm - the language switcher in upper-right corner of demo site is for testing and demo only, correct? It is not planned for live site? 

Thank you.

**Comment by manishgs** [comment]
@jedm  Yes, the language switcher is currently enabled for demo site only. We have not got any confirmation to deploy for live site.

**Comment by jedm** [comment]
For live site, I would suggest the switcher be a link, not a gif, and that it be in upper-right corner on HOMEPAGE ONLY and placed at bottom for inside pages. 

The top of the pages has many key functions and will become even more crowded if the switcher is there.

**Comment by jedm** [comment]
I mean text-only in a small font. No image, no gif. 

For examples please try the OECD website or the UN website. 

Seeking a style that is text only and  less visible.

**Comment by manishgs** [comment]
@jedm  Language Switcher has been updated.  Please review the design and let know your feedback.

**Comment by jedm** [comment]
Looks good. On the mobile version, it would be good if these buttons were smaller.

Also see #873 for problem with different page elements and alignment when switcher is switched to Arabic (a R-to-L language).

**Comment by hello-deepak** [comment]
Language controller is placed in footer .
![langc](https://cloud.githubusercontent.com/assets/7577697/19149913/f10e4c16-8be3-11e6-8010-2408e716fb10.png)
