### ISSUE TITLE
Import contracts for Tunisia CKAN spreadsheet data [Backend]

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#947]
@anjesh as discussed we need to import the contracts template for Tunisia. 

Its not the standard template so an import routine will need to be developed.

**Comment by anjesh** [comment]
We need to write a script to import the Tunisia contracts which are maintained in CKAN. The data are pulled from API into spreadsheet for further data cleaning and enriching with more core RC metadata - which are not present in the CKAN metadata. 

The following tasks are identified

- [ ] Mapping of Tunisia Spreadsheet data to RC metadata
- [ ] Script to read the spreadsheet and import into the RC database
- [ ] Unit tests to test the working of the import script
- [ ] Testing of the imported contracts

The script will be standalone for now, specifically for this import purpose only. Later we need to think of a mechanism where there will be an interface through which the data can be imported. The interface will automatically pull the CKAN data, match against the data in RC and see which contracts are updated and which are not and syncs. This will need broader discussion.

**Comment by charlesyoung** [comment]
[Link](https://docs.google.com/spreadsheets/d/1EGUDJvvK7rJglreBpeixM_OiM1m40GPb2Y_Hrs5fjco/edit#gid=613556742) to the template.

**Comment by charlesyoung** [comment]
Thanks @manishgs, the import looks good although it cannot be tested in full because ABBYY is understandably disabled on the demo site. I will let you know when the spreadsheet has been populated. 

cc @SamCCSI

**Comment by manishgs** [comment]
102 contracts have been imported in demo.

**Two files already exist.**
http://catalog.industrie.gov.tn/dataset/90a7e81f-eefc-4974-8abf-645935a5b6e3/resource/5ab5c044-6286-4eff-8659-930a8244189b/download/contratamilcar.pdf
- http://resourcecontracts-demo1.elasticbeanstalk.com/contract/1829

http://catalog.industrie.gov.tn/dataset/90a7e81f-eefc-4974-8abf-645935a5b6e3/resource/1aef5963-8f74-4209-bde7-3332b34f3833/download/avenantn1aucontratassamilcar006.pdf
- http://resourcecontracts-demo1.elasticbeanstalk.com/contract/1830

**Document Title of 4 contracts have been renamed.**
Avenant N°1 to  Convention Kebili-Avenant N°1 
Avenant N°2 to  Convention Kerkouane-Avenant N°2 
Avenant N°1 to  Convention Kerkouane-Avenant N°1 
Avenant N°1 to  Convention Makther-Avenant N°1 

@charlesyoung 
Please review the contracts and let us know if there any issues.

**Comment by charlesyoung** [comment]
Thanks @manishgs. Besides the Skype message I sent you re the numbers it seems as if the 'Jurisdiction of Incorporation' hasn't been imported. I will also update the contracts / docs missing a 'Jurisdiction of Incorporation'.

**Comment by charlesyoung** [comment]
Linked to ticket 'Verify the working of the french accent characters in OCR process. #938'
