### ISSUE TITLE
Country subsite management guidelines

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#948]
Now that there are multiple country subsites deployed, we need to develop a guidelines on how to manage these country subsites so that all the new changes are reflected in all the country sites. We either need to deploy the changes or we need to contact the site maintainer to pull the latest changes. 

We need to list all the country sites that have been deployed, and maintain the server credentials in some private document. 

This should address the issue of country site standardisation https://github.com/NRGI/resourcecontracts.org/issues/941

**Comment by anjesh** [comment]
Here's a draft https://docs.google.com/document/d/1sIFTvVgBrUUurV7Q3W3-e5yR-x2waAEwv_ZgIHiBozc/edit

**Comment by charlesyoung** [comment]
Closing ticket. Will update the guidelines doc when required.
