### ISSUE TITLE
HTML code appears in text version of contract

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#949]
This text version had been through MT and then amended by a researcher. When looking at it today, it was awash with html code, with the actual proper tet appearing below that code (see second picture).

Can YI look into what might be causing this issue? We have sent show PDF text to "no" for this contract now, given how messy it is. We will delete the code from the text soon.

http://www.openlandcontracts.org/contract/ocds-591adf-CD7799700327OL-2124/view#/text

![image](https://cloud.githubusercontent.com/assets/12913915/17522688/f68e93ee-5e25-11e6-88b6-116621ce86bb.png)

![image](https://cloud.githubusercontent.com/assets/12913915/17522699/01493cf8-5e26-11e6-9692-75ec5ee2f2c1.png)

**Comment by manishgs** [comment]
When copy/pasting from word file all the styles of from word also be copied on editor so now tags other than <br> and <p> will be strip out when saving on admin review text page.
