### ISSUE TITLE
Company name search not returning accurate results

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#950]
When filtering by company name, not all relevant contracts are displayed.

1. Search for Buchanan Renewable Energy, Inc. It appears in the drop-down, but then returns zero contracts.

![image](https://cloud.githubusercontent.com/assets/12913915/17705467/74da7fa8-63a6-11e6-8018-7a651d8bd38b.png)

2. But if you search for investment incentive contracts, the Buchanan Renewable Energy, Inc. appears in search results.

![image](https://cloud.githubusercontent.com/assets/12913915/17705519/a942c4da-63a6-11e6-814e-05394db792bb.png)

http://www.openlandcontracts.org/contract/ocds-591adf-LR0715242793OL

Can we please investigate why the company name search filter is not returning accurate results?

**Comment by SamCCSI** [comment]
Above comment updated -- initially posted before I had finished.

**Comment by hello-deepak** [comment]
Fixed and deployed in live. Please review.

**Comment by SamCCSI** [comment]
Thanks @hello-deepak 

That search works now, but I don't know how to test the problem more generally. Can you let me know what changes you made?

Sam

**Comment by hello-deepak** [comment]
Certain metadata of some contract was not being updated while updating from admin, which is fixed now.

Please reopen if you find any issue .
