### ISSUE TITLE
Add new document category: Document Summary

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#951]
OLC will soon start publishing summaries of deals filed by companies as part of their home government's disclosure requirements (e.g. AIM summaries, which can summarize contract, permits, decrees, etc.) and, potentially, unofficial summaries of local language contracts.

Can you please add a new document type: **Document Summary**

**Comment by manishgs** [comment]
Document type: **Document Summary**  has been added.
