### ISSUE TITLE
RC country sites

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#952]
Please don't run any non-essential updates on the country RC subsites without prior agreement. I noticed that the DRC, Guinea and Tunisia subsite home pages have been updated which has resulted in translation issues and search crashes. Although these sites are not yet in production mode the link has been shared with the relevant decision makers. Please return these sites to the original code.

**Comment by manishgs** [comment]
DRC, Guinea and Tunisia subsite design have been revert back to old design.
