### ISSUE TITLE
Develop a RC to CKAN importer

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#953]
Tunisia will be using RC to capture contracts but also want to display the contracts, with limited metadata, on the governments data portal. A routine will need to be developed to import newly added contracts to the CKAN site. 

cc @anjesh

**Comment by manishgs** [comment]
@charlesyoung 
Could you please provide us the CKAN site url and API?

**Comment by charlesyoung** [comment]
@manishgs this is the CKAN URL: http://catalog.industrie.gov.tn/dataset?groups=contrats-petroliers

Please ask @anjesh to contact the developer he met in Madrid to get the API info.

**Comment by anjesh** [comment]
The ckan API is documented here http://docs.ckan.org/en/latest/api/index.html

**Comment by charlesyoung** [comment]
Moved to milestone unscheduled because YI is waiting for the required CKAN credentials from the government.

**Comment by charlesyoung** [comment]
@anjesh, I'm putting this ticket on-hold for now.
