### ISSUE TITLE
"View all" bug

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#955]
![image](https://cloud.githubusercontent.com/assets/1101585/18126657/2ebf6dd0-6f4a-11e6-99fc-115b36927e59.png)

When going to the *View all* mode for search results no search results are presented. See these two URLs as example: 
http://www.resourcecontracts.org/countries/tn?page=7&all=1 

http://www.resourcecontracts.org/countries/iq?page=5&all=1

**Comment by hello-deepak** [comment]
@anderspeders 
Fixed and deployed in [live](http://www.resourcecontracts.org/) . Please review .
