### ISSUE TITLE
Separate text disclaimer for when text is displayed, but also being worked on by MT

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#957]
If Show PDF = Yes, but the text has been submitted to MT and is not yet finalized, it would be useful to have a separate disclaimer message.

**The text below was created automatically and contains errors and differences from the contract's original PDF file. An improved version of the text will be published in the future. Learn more**

(This won't be used by OLC, as OLC has a policy not to display any text until it has been verified. But for RC this alternative message could be useful in instances where we want to show the text for now to help users search but we also want to have it transcribed so that it is more useful in the future)

**Comment by charlesyoung** [comment]
@SamCCSI I would think that RC should have the same policy used by OLC by only displaying verified text. 

cc @anderspeders
