### ISSUE TITLE
Resource display on right column on contract page

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#958]
Need to have " | " ([space]|[space]) between multiple listed resources on the right column. Here "Paper" and Rice" look like one word even though they are listed as two separate resources.
![image](https://cloud.githubusercontent.com/assets/12913915/18208747/ac0c1f3a-70fe-11e6-99ef-0c026f655a07.png)

For guidance, here is how multiple listed contract types are listed:
![image](https://cloud.githubusercontent.com/assets/12913915/18208795/e2dc4d0a-70fe-11e6-81f7-ddf0b06d2e61.png)

**Comment by manishgs** [comment]
fixed.
