### ISSUE TITLE
Error "Sorry, the page you are looking for could not be found."

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#959]
http://resourcecontracts.elasticbeanstalk.com/contract/2188

**Comment by manishgs** [comment]
Contract with id '2188' is not found in database. Probably this contract is deleted.

**Comment by SamCCSI** [comment]
@manishgs I got to that link from the back-end, so it must have still been listed. Unfortunately that was a week ago so I cannot recall exactly how I got there. Will reopen if this problem re-presents itself.

**Comment by SamCCSI** [comment]
I am told this was previously listed under model contracts. Do you have the ability to find out the title of the contract and/or who deleted it? We just want to make sure we haven't lost anything accidentally.

Many thanks,
Sam

**Comment by manishgs** [comment]
All contract's data are deleted, when deleting a contract so we can't search in database. however when i search on contract activity log I found a contract "Model Contract, Other, 2003" which was deleted by "Amy Baum"  on "2016-08-30 19:08:31"
