### ISSUE TITLE
Update mock subsite based on the APIs

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#96]
After the APIs #89 are developed for contracts metadata, annotations and pdf-text, those APIs will be used to develop subsite. The current subsite for sprint2 is a mock site - which could be later tweaked to develop country specific subsite. The subsite will get the contracts information from the Elasticsearch #17 and hence only published contracts will be available.

**Comment by anderspeders** [comment]
Excellent, 

cc @byndcivilization to check we are good on this approach.

**Comment by anjesh** [comment]
Moving to Sprint 3 for further development. Need to include #43 and update the interface to accommodate further updates in the subsite.

**Comment by anjesh** [comment]
Updated to include faceted search, and various inside pages (document text view, pinning, metadata, annotations view) are updated. Still need improvement, new issue will be created to improve subsite.
