### ISSUE TITLE
Text editing causes page 32 to repeat on page 33, losing the correct text transcription.

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#960]
From one of our researchers:

I just noticed this strange thing that happens when I save pages on the back end text editing. There are times when a page becomes repeated twice which overrides the page that is supposed to be there. Example: Page 32 on [EJ & J](http://resourcecontracts.elasticbeanstalk.com/contract/1382) is now showing up on page 32 and 33. I noticed this happened when I was double checking the line breaks on EJ & J on Friday, but I fixed it by repasting the original MTurk transcript into the correct page. Obviously doing this fix that I did takes up time and it also doesn’t solve the problem because once I saved and published the text it happened again.

**Comment by SamCCSI** [comment]
cc @charlesyoung

**Comment by manishgs** [comment]
We did not notice this issue by saving multiple time on different contracts so closing for now. Please re-open If you encounter this issue again.
