### ISSUE TITLE
Typo in Profit Oil annotation category

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#961]
[_Production Share - "Profit Oil features(triggers for variations in split - IRR, factor, production, etc .)_
](http://www.resourcecontracts.org/search?q=&annotation_category%5B%5D=Production+Share+-+%22Profit+Oil+features%28triggers+for+variations+in+split+-+IRR%2C+factor%2C+production%2C+etc+.%29)
There needs to be a space between ‘features’ and ‘(triggers’

**Comment by hello-deepak** [comment]
Fixed.

Now, there is a space between 'features' and '(trigger'
[Production Share - "Profit Oil features (triggers for variations in split - IRR, factor, production, etc .)](http://www.resourcecontracts.org/search?q=&annotation_category%5B%5D=Production+Share+-+%22Profit+Oil+features+%28triggers+for+variations+in+split+-+IRR%2C+factor%2C+production%2C+etc+.%29)
