### ISSUE TITLE
Verify the Fr translation of RC

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#963]
http://rc-site-demo.elasticbeanstalk.com/rc/public/?lang=fr http://rc-site-demo.elasticbeanstalk.com/olc/public/?lang=fr are ready interms of functionality. There might be text which are not properly translated as we used google translate for some text. So it would be great if we have someone to go through both the sites to verify the fr translations.

**Comment by anjesh** [comment]
@charlesyoung can we have someone go through the text and ensure that Fr translations are good by the end of next week?

**Comment by anjesh** [comment]
OLC is covered in this issue https://github.com/NRGI/resourcecontracts.org/issues/971

**Comment by charlesyoung** [comment]
@anjesh have you applied all the translation updates provided by Amel?

**Comment by manishgs** [comment]
continue on this issue #1004
