### ISSUE TITLE
Update ALSF logo

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#964]
Update the ALSF logo on the redesigned home page. 

cc @anderspeders please provide the image in grayscale.

**Comment by charlesyoung** [comment]
Linked to Homepage redesign #873

**Comment by manishgs** [comment]
![screenshot-rc-site-demo elasticbeanstalk com 2016-09-16 17-31-15](https://cloud.githubusercontent.com/assets/3942999/18584966/df189814-7c33-11e6-8f9c-fa1af0676cb7.png)

Logo updated. Please review once.
