### ISSUE TITLE
French translation of OLC homepage 

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#971]
Hi @rprajapatii as mentioned in #873 we have the following comments regarding the French translation of the OLC homepage: 
- Please use the following in the search box: "Un répertoire de contrats agricoles et forestiers" (rather than "Un dépôt en ligne de Ouvert Land Contracts")
- The text in the center bar below the search box does not translate to French when the site is in French mode, and it also contains "fr" at the end where it shouldn't (see screenshot) 

![french translation](https://cloud.githubusercontent.com/assets/14910764/18721823/2b1d6102-8000-11e6-9b5a-6284e8fa3372.jpg)
- The annotation categories in the Explore box do not translate to French when the site is in French mode (see screenshot) 

![explore box](https://cloud.githubusercontent.com/assets/14910764/18721935/bbe2e7c0-8000-11e6-8c1d-933987e7a444.jpg)
- Auto-populated text prompt in Search box is too big for the box ( @jedm ) 

Some of these requests had already been mentioned by @KaitlinCCSI in #873 but we are separating them here for clarity.

**Comment by rprajapatii** [comment]
@JesseCCSI 

> Please use the following in the search box: "Un répertoire de contrats agricoles et forestiers" (rather than "Un dépôt en ligne de Ouvert Land Contracts")

Done. Will be reflected in demo and live soon.

> The text in the center bar below the search box does not translate to French when the site is in French mode, and it also contains "fr" at the end where it shouldn't 

Done. And also, the french translation can be updated by login via admin account.

![language_update_admin](https://cloud.githubusercontent.com/assets/8087920/19549055/b706b1a0-96c1-11e6-9d78-75ecd9be8f49.png)

> The annotation categories in the Explore box do not translate to French when the site is in French mode 

The french translation can be updated by login via admin account and selecting link option in sidebar below image option.

**Comment by JesseCCSI** [comment]
Thanks @rprajapatii I made the changes on the OLC admin site (openlandcontracts.org/admin), but they aren't showing up on the [demo](http://rc-site-demo.elasticbeanstalk.com/olc/public/?lang=fr) site - is there a way of verifying that the changes have been implemented?

**Comment by manishgs** [comment]
For demo you need to use this url : http://rc-site-demo.elasticbeanstalk.com/olc/public/login

Demo and live sites are using different databases so you need to update on both.

Let us know if you have any confusion.

**Comment by manishgs** [comment]
continue on this issue #1004
