### ISSUE TITLE
Disable auto-generated emails for “MTurk assignments for your action…”

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#972]
Right now any user that uploads a contract to RC/OLC receives auto-generated emails notifying them when pages have been processed on MT. This is usually irrelevant for them, as only Anna (OLC) and Imran (RC) are the ones who actually process the MT jobs. 

Please disable this feature, as it is not helpful and creates more work for uploaders (who have to set up a filter to avoid being inundated with emails).

cc @charlesyoung @anjesh

**Comment by manishgs** [comment]
Uploader's email has been removed from MTurk Notification email.

**Comment by SamCCSI** [comment]
Thanks @manishgs, so is this sent to anyone now? Not sure whose email was removed.

**Comment by manishgs** [comment]
Contract uploader no longer receives the notification for mTurk. Following emails will receive MTurk notifications.

For OLC contracts -  s.burke at columbia.edu, rkw2119 at columbia.edu
For RC contracts - s.burke at columbia.edu

**Comment by SamCCSI** [comment]
rkw2119 at columbia.edu no longer working for us, so should be removed.
