### ISSUE TITLE
OLC homepage - map colors

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#975]
Can YI please provide a mock up of the following options for the OLC homepage "Explore Contracts" map colors? The color used for the "ocean" in the current map clashes with the other homepage colors. It would be great if you could provide a mock up of the following two options: 
1. Match the map colors to the two greens in the "Explore contract terms" box, using the lighter green for the "ocean" and the darker green for relevant countries. 
2. Use a very light green for the "ocean" (e.g. a green that matches the grass in the image used for the background, but is slightly more muted), and keep the green used for the countries as is. 

Please let me know if the above is unclear. 

cc @SamCCSI @KaitlinCCSI

**Comment by SamCCSI** [comment]
Thanks @rprajapatii , we appreciate your efforts on these mock-ups. We will make some further investigations into possible color codes and be back in touch in a week or two.

**Comment by charlesyoung** [comment]
@SamCCSI any feedback on this ticket?

**Comment by SamCCSI** [comment]
@charlesyoung we are working on it -- will be back in touch as soon as we have some color codes

**Comment by KaitlinCCSI** [comment]
Hi, could we please use the following colors (see also screenshot):

For countries with contracts -- Green  ....# 70bf4c
For countries without contracts -- White......# ffffff 
For ocean -- Blue.......# c1dcfa

Thanks!

![map_1 1](https://cloud.githubusercontent.com/assets/14825437/20108180/cc22ec96-a5a0-11e6-91c9-122fefbd447b.jpg)

**Comment by KaitlinCCSI** [comment]
Thanks for changing the map colors. Did you also change the filter on the background photo at top of page? It seems darker than it used to be (see screenshot - old on left, current on right), so doesn't match the new colors as well ... Would prefer either that colors remain as they were, or that they are made a bit more bright blue/purple-y as they seem to be in our mockup above. Thank you!

![screen shot 2016-11-10 at 10 54 02 am](https://cloud.githubusercontent.com/assets/14825437/20186121/5707d620-a734-11e6-8fb2-47cb894a29fb.png)

**Comment by manishgs** [comment]
Color of background image is fixed.
