### ISSUE TITLE
Associated documents should link to contract view page, not contract summary page

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#976]
On the right hand column, the hyperlinks to associated documents should link to contract view page, not the contract summary page, of the relevant contract. This is way more intuitive for users, who are taken to the contract view page (not summary page) when they click on any contract in the search results. 

![image](https://cloud.githubusercontent.com/assets/12913915/18803406/c0527f32-81bd-11e6-8608-343b75f54ad5.png)

**Comment by jedm** [comment]
Agree strongly.

**Comment by hello-deepak** [comment]
Now associated documents are linked to view page .

http://www.resourcecontracts.org/contract/ocds-591adf-TN5800223711RC/view#/pdf
