### ISSUE TITLE
Add Tunisia and Guinea sites to the bottom of RC home page 

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#977]
Please add site icons (and hyperlinks) for Tunisia <http://tunisia.resourcecontracts.org/> and Guinea <http://www.contratsminiersguinee.org/> under "Country Partners" section of RC.

CC @charlesyoung

**Comment by charlesyoung** [comment]
We should add Guinea but not Tunisia for now seeing that the site will only be launched next week. Can be added once launched. We are also doing a French and Arabic language update. The same will apply to the DRC (https://www.mines-rdc.cd/resourcecontracts).

**Comment by charlesyoung** [comment]
@anjesh can you please implement this ticket seeing that the Tunisia site was launched last Friday. 

CC @SamCCSI

**Comment by rprajapatii** [comment]
@SamCCSI , @charlesyoung 

>Please add site icons (and hyperlinks) for Tunisia http://tunisia.resourcecontracts.org/ and Guinea http://www.contratsminiersguinee.org/ under "Country Partners" section of RC.

Tunisia is added in under "country Partners" in live site.

However for Guinea, which background image should we use? I have used a image from http://www.contratsminiersguinee.org/. Conform the following images for Guinea and Congo.

![guinea_partner_country](https://cloud.githubusercontent.com/assets/8087920/19517677/5a25dbd6-9622-11e6-86b4-61a4e9d30a06.jpg)

![congo_country_partner](https://cloud.githubusercontent.com/assets/8087920/19517678/5c71a21c-9622-11e6-9096-6bb9ae3b9c31.jpg)

**Comment by SamCCSI** [comment]
Those look good, subject to what @charlesyoung thinks.

If you had the time, you could also colorize the Guinea photo with the dark
green used on the top of the Guinea site, similar to what you created for
the PHEITI icon.

**Comment by charlesyoung** [comment]
I'm happy with @SamCCSI suggestion. 

Can you please hold on the DRC site because it hasn't officially been launched.

**Comment by rprajapatii** [comment]
@SamCCSI , @charlesyoung 

> If you had the time, you could also colorize the Guinea photo with the dark
green used on the top of the Guinea site, similar to what you created for
the PHEITI icon.

I have attached a image with green overlay for Guinea. Please have a look.

![guinea_country_partner](https://cloud.githubusercontent.com/assets/8087920/19546098/492052b4-96ac-11e6-9307-7b2561fefa00.jpg)

**Comment by SamCCSI** [comment]
Looks good.

There is a typo: it should read "GUINEA" (in English) or "GUINÉE" (in
French).

Because the Guinea site is a French language site, I think we should have
the French spelling in the icon.
