### ISSUE TITLE
Manage languages from admin panel in subsite

### ISSUE THREAD

**Issue by manishgs** [NRGI/resourcecontracts.org#979]
Add following features to admin panel.

- [x] On/off translation feature

- [x] Option to change site default language 
     By default English is default language but site admin can change to French  as default language.

- [x] Option to select/deselect languages
Currently we have English , French and Arabic translation but create option to select all or some of them from admin.

**Comment by manishgs** [comment]
Manage language menu added in admin panel.

Please review. @charlesyoung @SamCCSI @jedm

**Comment by SamCCSI** [comment]
Not sure where to review this – could you provide a screenshot?

**Comment by manishgs** [comment]
Here is the screenshot for manage language page.
![screenshot-www resourcecontracts org 2016-10-05 09-55-01](https://cloud.githubusercontent.com/assets/3942999/19100824/f10510a4-8ae1-11e6-9772-7f9e3a1f08d1.png)

**Default language:** It's for site default language.

**Enable localization:** Select this if you want, site to be multi language.

**Choose Language:**  Select languages to display in language option.
