### ISSUE TITLE
Permissions to publish annotations?

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#981]
Do researchers have permissions to publish annotations? An annotator just had to ask us to click on 'publish' as he did not have the required permissions.

We would prefer that the annotator can publish the annotations themselves.

**Comment by SamCCSI** [comment]
Another researcher has had permission denied when trying to publish metadata.

Can we please adjust permissions so that users with "Research associate" status can publish metadata, text and annotations? 

Adding priority tag, as this is starting to hold up our researchers' work.

cc @charlesyoung @anjesh

**Comment by hello-deepak** [comment]
Fixed .

Now, "Research Associate" have permission to publish and unpublish metadata, text and annotation .
