### ISSUE TITLE
Auto-generating contract name in French & other languages

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#982]
For the Tunisia site and for the general RC site, we need to auto-generate contract names incorporating the French terms for metadata fields like document type / contract type.

E.g. Right now a Tunisian _Convention_ (French term) has the metadata contract type of 'Concession' (English term) so if we auto-generate the contract name it will include the English term, which won't be useful for most Tunisian users. Instead we need to switch to French so that the corresponding French term for the contract type ('Convention') is included in the contract name when we auto-generate it.

cc @charlesyoung @anderspeders

**Comment by charlesyoung** [comment]
Linked to ticket 'Localisation of metadata and annotation (backend) #962'

**Comment by anjesh** [comment]
This auto-generating feature is part of  metadata localisation and will be included there.
