### ISSUE TITLE
Altering the categories checklist for annotations

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#985]
In the back-end, annotators can see which annotation categories they have not yet filled in: 

![image](https://cloud.githubusercontent.com/assets/12913915/19328435/a16b68e8-90a1-11e6-9868-4d0e153e1129.png)

However, right now RC and OLC do not ask annotators to fill in all of those annotation categories. RC requires a maximum of 55 categories ([p. 53 of Admin Guide](https://docs.google.com/document/d/1lawSuSak4sAHitaCtbPs3nhNEM5aR20tdMMj_c_JKtk/edit#heading=h.4v0pj7dvxw43)) and OLC requires a few more ([p. 54 of Admin Guide](https://docs.google.com/document/d/1lawSuSak4sAHitaCtbPs3nhNEM5aR20tdMMj_c_JKtk/edit#heading=h.rlgj0ekz1ywx))

**Request: Would it be possible for CCSI to be able to set which annotation categories appear in the annotation checklist?**

**Comment by manishgs** [comment]
@SamCCSI 
Please provide the category list for RC and OLC, we'll update the checklist according to RC/OLC contract.

**Comment by SamCCSI** [comment]
1. Thanks @manishgs here is the revised checklist: https://docs.google.com/a/columbia.edu/spreadsheets/d/1buks6Aa8LNCaB-czZouyCC1luxURRNzU-GiMNhYGmn8/edit?usp=sharing

2. Can the categories be sorted alphabetically under each cluster category?

**Comment by charlesyoung** [comment]
@manishgs can you please look at Sam's question above.

**Comment by manishgs** [comment]
@SamCCSI 

1. We have a confusion regarding implementing the RC/OLC list, are we also going to update category dropdown according to RC/OLC contract while adding annotation?

2. yes, we can.

**Comment by SamCCSI** [comment]
@manishgs 

1. No, you don't need to do that; we just want the left column checklist on the backend to change according to the code list.

2. Thanks!

**Comment by charlesyoung** [comment]
@manishgs what is the latest with this ticket?

**Comment by manishgs** [comment]
@SamCCSI 

Categories  have been showing under headings on Admin which is not mentioned on google sheet.

![screenshot-admin resourcecontracts org 2017-03-07 11-32-37](https://cloud.githubusercontent.com/assets/3942999/23643427/cd3c3510-0329-11e7-9ecf-7c21516fa332.png)


I have added new sheet "All" in the google sheet which contains all the categories and headings which we are using on our code-list. Could please also add headings (e.g   I. General information, II. Summary of terms, 1. Fundamental provisions etc.) on the RC/OLC categories list?

**Comment by SamCCSI** [comment]
Thanks @manishgs 

We want to get rid of the current headings, which is why hey were not added to the codelist.

On the existing pages (for RC and OLC), the red text fields should be the headings now, to make it consistent with the front end.

Example:
First heading is called 'General'

![image](https://cloud.githubusercontent.com/assets/12913915/23673880/e573583a-0341-11e7-827e-3bbe2112b815.png)

Front end categories:
![image](https://cloud.githubusercontent.com/assets/12913915/23673922/0ebda4e8-0342-11e7-8c88-e6ab919e1b83.png)

**Comment by manishgs** [comment]
Annotation categories updated in checklist section. Please review on [staging](http://admin-staging.resourcecontracts.org/contract/173/annotate)

**Comment by SamCCSI** [comment]
@manishgs this looks great. Please deploy.

**Comment by manishgs** [comment]
Deployed on production.
