### ISSUE TITLE
Button for search only main contracts only - in advanced search

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#987]
We have received a few requests over the year for enabling search for "main contracts only"

This would include all documents categorised as _contract_: 
http://www.resourcecontracts.org/search?q=&document_type%5B%5D=Contract

![image](https://cloud.githubusercontent.com/assets/1101585/19478147/5e499a40-950f-11e6-968b-d63b6a969dc2.png)

**Comment by anjesh** [comment]
@anderspeders @charlesyoung any updates on this? Are we good to go on this?

**Comment by charlesyoung** [comment]
Moved to 'Unscheduled' milestone.
