### ISSUE TITLE
Country Site Sidebar

### ISSUE THREAD

**Issue by manishgs** [NRGI/resourcecontracts.org#988]
We have updated sidebar of country site as shown below.

![screenshot-rc-site-demo elasticbeanstalk com 2016-10-21 16-41-34](https://cloud.githubusercontent.com/assets/3942999/19596272/86255c98-97ad-11e6-98d2-2736fa79457c.png)

http://rc-site-demo.elasticbeanstalk.com/drc/public/

@charlesyoung @SamCCSI 
Let us know your feedback regarding the changes.

**Comment by charlesyoung** [comment]
Looks better and more compact than the current side bar. 

Do we however need to show 'About', 'Guides' and 'Glossary' seeing that it is already noted at the bottom of the page?

**Comment by manishgs** [comment]
Current RC/OLC site have these page links so we keep that links on country site too.

**Comment by manishgs** [comment]
@charlesyoung @SamCCSI 
Could you please confirm the sidebar as shown in image above is okay for you? so that we can make the RC/OLC and country site codebase same and deploy the same codebase to country sites.

**Comment by SamCCSI** [comment]
Looks good, thanks @manishgs

**Comment by charlesyoung** [comment]
Looks good @manishgs

**Comment by anjesh** [comment]
This issue can be closed. 
Country sites will also see similar menu once standardized, will be taken care here https://github.com/NRGI/resourcecontracts.org/issues/994.
