### ISSUE TITLE
DRC multi-sectoral country subsite request

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#991]
We are currently agreeing on a URL for a new multi-sectoral site for the DRC, which will include: 
- Mining contracts published via the DRC RC subsite (https://www.mines-rdc.cd/resourcecontracts/) 
- Agricultural contracts 
- Forestry contracts (some of which are already available on the global OLC [site](http://www.openlandcontracts.org/countries/cd)) 

We expect the URL to be registered shortly. When that happens, we'll need to launch a demo site (and implement other requests relating to this subsite). 

I am adding this ticket now so that it can be included in the planning for Sprint 18. Further details on specific requests will follow shortly. Many thanks. 

cc @KaitlinCCSI @charlesyoung

**Comment by JesseCCSI** [comment]
Per previous conversations with @charlesyoung and @anjesh, I'm listing the following issues here:

- Does YI have all the information needed to create OLC sub-domains? During our call in December, @anjesh mentioned that YI would test credentials and confirm they have all they need. 

- We are waiting to receive a signed MoU for the DRC subsite - once we receive this, we'll need to create a DRC subdomain and demo site. I will revert on this as soon as we have further information.

**Comment by charlesyoung** [comment]
@JesseCCSI just checking if the DRC multi-sectoral country subsite will need to be done by the end of March because all S19 tickets has to be closed by the 31 March.

**Comment by JesseCCSI** [comment]
Please go ahead and set up this demo site (as discussed offline). For the moment, the URL can be drc.openlandcontracts.org. For the demo site, we can start with the DRC docs that are already available on OLC (http://openlandcontracts.org/countries/cd). 

Prior to proceeding, could YI please confirm that the URL can be changed at a later date if needed (e.g. changed to rdc.openlandcontracts.org rather than drc.openlandcontracts.org if country partner so wishes)? 

Many thanks. 

(cc @charlesyoung @KaitlinCCSI)

**Comment by manishgs** [comment]
@JesseCCSI  URL can be changed later but we need to ask Vitamin to update subdomain.

Do we need to set it up on openlandcontracts.com (drc.openlandcontracts.com) too?

**Comment by JesseCCSI** [comment]
Thanks @manishgs - just to clarify, do you mean setting up on openlandcontracts.com so that it re-directs to the .org site? If so, does that take much additional time?

**Comment by manishgs** [comment]
Currently openlandcontracts.com is redirected to openlandcontracts.org. In a same way, Do you want to redirect drc.openlandcontracts.com to drc.openlandcontracts.org too?

**Comment by JesseCCSI** [comment]
Yes, thanks @manishgs

**Comment by manishgs** [comment]
DRC OLC subsite is now live.  drc.openlandcontracts.com / drc.openlandcontracts.org

**Comment by charlesyoung** [comment]
@manishgs the DRC site is an OLC and not RC site so all reference to RC needs to be replaced with OLC. Also I don't think we will need Arabic on this site. 

@JesseCCSI do you have a suitable image that we could use for the home page background?

**Comment by JesseCCSI** [comment]
Thanks @manishgs is this site public already? We just want to launch a demo site for now that isn't public. 

@charlesyoung thanks - will provide an image asap this week.

**Comment by manishgs** [comment]
@JesseCCSI 
Yes, it is public, anyone can view drc.openlandcontracts.org.  Do you want to setup drc-staging.openlandcontracts.org for demo purpose?

Please review the static page content and let us know any changes needed.

**Comment by manishgs** [comment]
Please view the DRC demo site on this url http://staging.drc.openlandcontracts.org/

**Comment by JesseCCSI** [comment]
Thanks @manishgs for setting up the demo site. A few initial comments: 

1. This is an OLC subsite, so references to RC should be removed. Format of references should follow the OLC format, e.g. use term "online repository" rather than "directory" of contracts on homepage and elsewhere. 
2. The logo footer on the About, etc. pages should follow the OLC not RC format. Screenshot: 

![image](https://cloud.githubusercontent.com/assets/14910764/23997271/097197f6-0a27-11e7-939d-435854250f00.png)
 
3. On the English version of the homepage, please change the name of the site to "Democratic Republic of the Congo" (rather than Congo, the Democratic Republic of the). 
4. For the moment, please use this background image for the homepage (it is attribution free): https://pixabay.com/en/banana-plantation-africa-agriculture-2098723/ 
5. We won't need the Arabic version of the site, so please remove that. We will however need the French and English versions. 
6. Please remove all text from the About, FAQ, Guides, Glossary, and Contact Us pages for now. If you need to add text to these pages so they are not empty, please use "Coming soon...". 

Many thanks.

**Comment by manishgs** [comment]
Changes have been made. Please review again.

**Comment by charlesyoung** [comment]
@JesseCCSI apologies as I realise that you are at a conference this week but could you look at this ticket when you have time because we have to close all tickets by next Friday due to the closing of the S19 development budget cycle. Thanks

**Comment by JesseCCSI** [comment]
Many thanks @manishgs. A few points: 

1. I know the name had been changed to Democratic Republic of the Congo, as I looked at the site a couple of days ago and it had been changed, but today it seems to have reverted to "Congo, the Democratic Republic of the" - not sure why this happened? Cleared my cache and was still having the same issue (screenshot below). 


![image](https://cloud.githubusercontent.com/assets/14910764/24276633/5df43e86-100e-11e7-998b-b34c9de710ec.png)

2. In the box for the English version, please use: "An online repository of OpenLandContracts from the Democratic Republic of the Congo". 

3. In the box for the French version, please use: "Un répertoire de contrats agricoles et forestiers de la République démocratique du Congo"  

4. Please change all refs from "RC" to "OLC" e.g. this one: 

![image](https://cloud.githubusercontent.com/assets/14910764/24276554/eee33b0a-100d-11e7-9d22-2f109930d407.png)

5. Please also change the footer to the OLC style footer (again, I think this had been changed during the week, but seems to have reverted to the RC version?): 

![image](https://cloud.githubusercontent.com/assets/14910764/24276619/48890a90-100e-11e7-9b66-053ab2dd2391.png)

**Comment by manishgs** [comment]
@JesseCCSI 
Changes had been done and was deployed 4 days ago but DRC change was not deployed at the time when you are reviewing the site. Sorry for the confusion. Now you can see the changes on DRC staging site. Let us know if there are any changes that need to be done.

**Comment by charlesyoung** [comment]
@JesseCCSI can we close this ticket?

**Comment by JesseCCSI** [comment]
Thanks @manishgs and @charlesyoung all looks good. 

One quick question - the original photo looks brighter than the version on the site (assume it's to do with the filter applied on top). Is it possible to brighten the photo? 

Other than that, we can close this ticket. We can leave as a demo site for now, so please don't deploy the live version. Many thanks.

**Comment by charlesyoung** [comment]
@JesseCCSI I'm going to close this ticket and we can always look at sharpening the photo later. We are under pressure to finish all open tickets by Friday.

**Comment by manishgs** [comment]
We've brighten the photo but still have 10% black overlay.
