### ISSUE TITLE
Fix the project and licence name for Tunisia contracts

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#992]
For all the tunisia contracts, the licence names should be moved to project names and licence names should be empty. The [data file](https://docs.google.com/spreadsheets/d/1EGUDJvvK7rJglreBpeixM_OiM1m40GPb2Y_Hrs5fjco/edit#gid=613556742) has incorrectly placed licence names instead of project names. The contracts should also get re-published after fixing the names to reflect the changes in the subsites.

**Comment by manishgs** [comment]
@charlesyoung 
Fixed and re-published. Please verify.
