### ISSUE TITLE
Standardise country sites 

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#994]
Standardise the language support and code for the country sites. 

@anjesh

**Comment by anjesh** [comment]
Confirming. These are the list of sites that need to be standardized and the language each of these sites to support.

http://www.nma.gov.sl/resourcecontracts [en,fr]
https://www.mines-rdc.cd/resourcecontracts/ [en,fr]
http://tunisia.resourcecontracts.org [en,fr, ar]
http://rc-site-demo.elasticbeanstalk.com/gn/public [en,fr]

**Comment by charlesyoung** [comment]
@anjesh that's correct.

**Comment by manishgs** [comment]
Sierra Leone site is updated. Please update the content of the static pages. 
http://www.nma.gov.sl/resourcecontracts/about
http://www.nma.gov.sl/resourcecontracts/publish-contracts
		
http://www.nma.gov.sl/resourcecontracts

**Comment by charlesyoung** [comment]
Are we using the Tunisia site as the benchmark? 

The SL site doesn't have all the text translated.   

![image](https://cloud.githubusercontent.com/assets/13888372/20214632/14992ec6-a818-11e6-8e0a-e0db36d13b8b.png)

**Comment by charlesyoung** [comment]
Please deploy the clipping function on the country sites.

**Comment by manishgs** [comment]
Sierra Leone, Tunisian and Guinea country site are update. Please review once.

**Comment by charlesyoung** [comment]
@manishgs can you please add the relevant 'FAQs' text to the Sierra Leone site. 

The 'Guides' link also crashes.

**Comment by manishgs** [comment]
Guides page is created.
Do you want to copy content from http://www.resourcecontracts.org/faqs to Sierra Leone site??

**Comment by charlesyoung** [comment]
Yes, please use the standard RC Guides and FAQs text.

**Comment by shashikhanal** [comment]
RC [Guides](http://www.nma.gov.sl/resourcecontracts/guides) and [FAQs](http://www.nma.gov.sl/resourcecontracts/faqs) text are added to Sierra Leone site.

**Comment by charlesyoung** [comment]
Thanks. I'm however reopening the ticket because we still need to standardise the DRC country site once we get access.

**Comment by charlesyoung** [comment]
Please relook at the SL site. The document number is cut off and the advance searching also looks wrong. 

![image](https://cloud.githubusercontent.com/assets/13888372/21932435/43780e3e-d9a9-11e6-89a4-31a43e6b2e1c.png)

![image](https://cloud.githubusercontent.com/assets/13888372/21932489/73cc8736-d9a9-11e6-84a5-f195916d24ee.png)
