### ISSUE TITLE
New OCIDs Generation for the existing contracts.

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#997]
OCIDs need to be generated for the existing contracts following new structure ocds-591adf-[10-random-numbers]. This will ensure that any change in the country and resource type (OLC or RC) will not have any impact on the OCID. OCDS Helpdesk also [confirmed](https://github.com/NRGI/resourcecontracts.org/issues/919) this approach. 

Next we need to make sure that existing OCIDs also don't break and gets redirected to new OCID url.

**Comment by KaitlinCCSI** [comment]
Sounds good to me.

**Comment by charlesyoung** [comment]
@anjesh please implement above suggestion.

**Comment by manishgs** [comment]
New OCID updated. Please verify on demo site. 
Here is the link for old and new ocid mappings for testing
http://rc-site-demo.elasticbeanstalk.com/rc/public/ocid_mapping.json

Let us know if you have any confusion.

**Comment by charlesyoung** [comment]
@KaitlinCCSI please confirm that you are happy.

**Comment by KaitlinCCSI** [comment]
Yes, this is great, thanks. (I don't know what to do with json file, but so long as the old URLs redirect to the new ones, I think this is a great solution).

**Comment by manishgs** [comment]
Deployed in live. Please review once.

**Comment by JesseCCSI** [comment]
Checked several old OLC links and they redirect - thanks @manishgs @anjesh!
